Howto for native navigation
mendix/docs pull request #2799
Opened 2020-10-12 12:48 UTC by KevinVlaanderen

I'll also let my team review this document, so please don't merge right away

2020-10-12 14:37 UTC, jobvs requested changes

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +With native mobile, by default pages are kept in memory, which makes it possible to quickly navigate back (e.g. with hardware back button, or by swiping) and to retain the state on the previous page(
Some ideas for improvement, tried to make it a bit more clear and less technical.

```suggestion
In native mobile apps, pages are kept open by default. This makes it possible to instantly navigate back (e.g. by pressing the back button, or by swiping) while retaining the state of the previous page(s) (e.g. scroll location, active tab). This greatly benefits the overall user experience of the app. This has to be taken into account when developing mobile apps, to make sure that there will not be too many pages open (which will result in bad performance) and data is refreshed/updated accordingly. To manage this, you have more control over the exact navigation flow.
```

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +- Left part: not configurable, but can show a back icon, close icon, or sidebar icon depending on the layout type
We don't have a sidebar yet :)

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +If you open a page in a stack that does not have the bottom bar property enabled, it will not show anymore on any further page, until you go back from the page that disabled it.
This is no longer the case in the new navigation. New behavior is that if you have opened pages in the stack that do not have a bottom bar, those are all closed when you open a page with a bottom bar. Details in UICORE-1005

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Pop-ups can be very useful when asking for input in a certain context. One example is when the you have to scan a QR code. Another example is a wizard (form with multiple steps), as you can still go
Should we mention that pop-up pages can not have a bottom bar? Or under 2.1 that only default pages can have a bottom bar?

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +As mentioned above, by default pages are kept in memory to provide a better user experience, but they must also be managed correctly in order to get great performance and a logical UX/flow through th
Should we use 'kept open' everywhere instead of 'kept in memory', to make it less technical?

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +If the app does not use a bottom bar, by default there is a single stack. This means that pages can be opened, and when a page is closed this page is removed from the app. For example when the app is
This paragraph feels a bit weird.
- 'This means that pages can be opened' is super generic, but seems to be specifically about the fact that there is a single stack. If you have multiple stacks it is also possible to open pages. 
- The 'For example' doesn't seem to be an example.

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +If the bottom bar item is not focused, press will focus that item. Switching to another bottom bar item will not close pages in the focused one. If the item is already focused, press will dismiss all
'pressing it' instead of 'press'?

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +When a page with a Popup layout is opened, a new stack is created and all pages in this stack fully cover the screen. To get back to the previous stack, the popup has to be closed. Within a popup one
Most of the info in 4.1.3 is also there in 2.2. Perhaps we can put it in only one place and link to it from the other place?

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Often there is a need to have control of the history, e.g. which page is shown see when the user presses the hardware back button on Android or when the users does a swipe to go back gesture (swipe f
This mentions two examples for when 'there is a need to have control of the history', but for both examples we currently do not provide any control over it.

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +### 5.1 ake it simple for the user
```suggestion
### 5.1 Make it simple for the user
```

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Where possible, we advise you to use the Close Page action (or the above mentioned variants of the Show Page action) as much as possible, to ensure that you don't keep too many superfluous pages aliv
Again, not sure if readers are familiar with 'memory' which is mentions a lot in this section. Perhaps we can use 'performance'.

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +As mentioned above, when opening pages, these pages are kept in memory, which can cause memory or performance issues. The consequence of this is that the choice between using an Open Page or a Close
```suggestion
As mentioned above, when opening pages, these pages are kept in memory, which can cause memory or performance issues. The consequence of this is that the choice between using an Open Page or a Close Page action should be made more deliberately than with web applications.
```

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Although such behavior can be modeled using the ability to close multiple pages, as described above, we generally recommend the use of popups for such scenarios. Popup pages exist entirely outside of
Really like this section, very clear 👍

2020-10-12 14:37 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Out of the box the bottom bar and top bar have a default styling and the styling can be changed as described [here](/refguide/native-styling-refguide#pages). However, if further customization is need
Not sure what is meant with 'and or model the UI using the open and close page options'?

2020-10-12 16:29 UTC, KevinVlaanderen commented
@jobvs I processed all your feedback. Can you please take another look? Because of the filename mixup, your comments are  not linked to the actual changes anymore, so you'll just have to look at the last commits.

2020-10-13 07:10 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +- Left part: not configurable, but can show a back icon, close icon, or sidebar icon depending on the layout type
Still applies

2020-10-13 07:11 UTC, jobvs commented on content/howto/mobile/native-navigation.md
> +---
Resolved

2020-10-13 07:12 UTC, jobvs commented on content/howto/mobile/native-mobile.md
>  ---
Resolved

2020-10-13 07:12 UTC, jobvs commented on content/howto/mobile/native-navigation.md
> +* [Troubleshoot Common Native Mobile Issues](common-issues)
Resolved

2020-10-13 07:12 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +In general, in web apps, there is only one page open. When a user opens a page the current page, it is replaced with the new one. And when the user navigates back, the previous page is loaded. This h
Resolved

2020-10-13 07:12 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +With native mobile, by default pages are kept in memory, which makes it possible to quickly navigate back (e.g. with hardware back button, or by swiping) and to retain the state on the previous page(
Resolved

2020-10-13 07:12 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +- Left part: not configurable, but can show a back icon, close icon, or sidebar icon depending on the layout type
Still applies

2020-10-13 07:12 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +If you open a page in a stack that does not have the bottom bar property enabled, it will not show anymore on any further page, until you go back from the page that disabled it.
Still applies

2020-10-13 07:13 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Pop-ups can be very useful when asking for input in a certain context. One example is when the you have to scan a QR code. Another example is a wizard (form with multiple steps), as you can still go
Still applies

2020-10-13 07:14 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +As mentioned above, by default pages are kept in memory to provide a better user experience, but they must also be managed correctly in order to get great performance and a logical UX/flow through th
Still applies in a few places, if you agree

2020-10-13 07:14 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +If the app does not use a bottom bar, by default there is a single stack. This means that pages can be opened, and when a page is closed this page is removed from the app. For example when the app is
Still applies

2020-10-13 07:14 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +If the bottom bar item is not focused, press will focus that item. Switching to another bottom bar item will not close pages in the focused one. If the item is already focused, press will dismiss all
Still applies

2020-10-13 07:14 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +When a page with a Popup layout is opened, a new stack is created and all pages in this stack fully cover the screen. To get back to the previous stack, the popup has to be closed. Within a popup one
Still applies

2020-10-13 07:14 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Often there is a need to have control of the history, e.g. which page is shown see when the user presses the hardware back button on Android or when the users does a swipe to go back gesture (swipe f
Still applies

2020-10-13 07:15 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +### 5.1 ake it simple for the user
Resolved

2020-10-13 07:16 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Where possible, we advise you to use the Close Page action (or the above mentioned variants of the Show Page action) as much as possible, to ensure that you don't keep too many superfluous pages aliv
It's still mentioned in this section

2020-10-13 07:16 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +As mentioned above, when opening pages, these pages are kept in memory, which can cause memory or performance issues. The consequence of this is that the choice between using an Open Page or a Close
Resolved

2020-10-13 07:16 UTC, jobvs commented on content/howto/mobile/native-mobile.md
> +Out of the box the bottom bar and top bar have a default styling and the styling can be changed as described [here](/refguide/native-styling-refguide#pages). However, if further customization is need
Gone now, so resolved I guess

2020-10-13 07:32 UTC, KevinVlaanderen commented on content/howto/mobile/native-mobile.md
> +Where possible, we advise you to use the Close Page action (or the above mentioned variants of the Show Page action) as much as possible, to ensure that you don't keep too many superfluous pages aliv
There was one instance remaining, indeed. I replaced it with 'resources' now; is that better?

2020-10-13 10:27 UTC, KevinVlaanderen commented
Processed comments

2020-10-13 11:01 UTC, KevinVlaanderen commented
All yours, @ConnorLand

2020-10-13 11:11 UTC, jobvs approved these changes

2020-10-14 12:03 UTC, ConnorLand commented on content/howto/mobile/native-navigation.md
> +To keep pages open, the navigation system uses multiple stacks of pages. A mobile app can contain multiple stacks at the same time. A stack can be compared to a pile of cards: you can add cards to th
Can you only add stacks to the "top" of the app, or can you slide new stacks in anywhere?

2020-10-14 12:12 UTC, ConnorLand commented on content/howto/mobile/native-navigation.md
> +If a bottom bar item is not focused, pressing it will focus that item. Switching to another bottom bar item will not close pages in the focused one. If the item is already focused, pressing it will d
Correct?

2020-10-14 12:37 UTC, ConnorLand commented on content/howto/mobile/native-navigation.md
> +It is possible to open other pop-up pages inside the pop-up, and all of those together behave as a single stack. When opening a normal page from the pop-up, the pop-ups will be closed first.
Is this paragraph correct?

2020-10-14 13:53 UTC, ConnorLand commented on content/howto/mobile/native-navigation.md
> +*
Are there any other docs our users might need in relation to this topic?

2020-10-16 10:04 UTC, KevinVlaanderen commented on content/howto/mobile/native-navigation.md
> +To keep pages open, the navigation system uses multiple stacks of pages. A mobile app can contain multiple stacks at the same time. A stack can be compared to a pile of cards: you can add cards to th
As a Mendix developer, you don't deal with stacks at all. All you do is open and close pages.
We describe stacks here because the concept is important when trying to understand/predict how the navigation system work/behaves.

2020-10-16 10:05 UTC, KevinVlaanderen commented on content/howto/mobile/native-navigation.md
> +If a bottom bar item is not focused, pressing it will focus that item. Switching to another bottom bar item will not close pages in the focused one. If the item is already focused, pressing it will d
Yes. Maybe "pressing it again" makes it a bit clearer?

2020-10-16 10:08 UTC, KevinVlaanderen commented on content/howto/mobile/native-navigation.md
> +It is possible to open other pop-up pages inside the pop-up, and all of those together behave as a single stack. When opening a normal page from the pop-up, the pop-ups will be closed first.
Yes, that's why we wrote it :trollface:

2020-10-16 10:08 UTC, KevinVlaanderen commented on content/howto/mobile/native-navigation.md
> +It is possible to open other pop-up pages inside the pop-up, and all of those together behave as a single stack. When opening a normal page from the pop-up, the pop-ups will be closed first.
Yes

2020-10-16 11:25 UTC, KevinVlaanderen commented on content/howto/mobile/native-navigation.md
> +*
added a few

2020-10-16 13:15 UTC, ConnorLand approved these changes

2020-10-16 13:15 UTC, merged