Document SAP Fiori 3 Styling
mendix/docs pull request #2857
Opened 2020-11-03 08:46 UTC by MarkvanMents

2020-11-13 19:28 UTC, gauravkrshah requested changes
Please go through review comments. Let me know in case of any questions.

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +{{% todo %}}[Does the construction of the Action Bar need to be described? Why isn't it a building block?]{{% /todo %}}
Not required. Let's remove this from mendix core elements.

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +{{% todo %}}[Do we need a section }#### 2.1.5 Pagination]{{% /todo %}}
Actually not, because Adding a pagination is same as of Atlas UI, so if we can assume that develop is aware of developing app in Mendix,

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* Time
Added - Timepicker control not supported

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* Menu/Navigation
Not supported in menus
Menu having two icons. 
Menu having slider right to show submenu

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* Table
Table having checkboxes and icons can’t be supported. 

Table row selection is possible at row selection level.

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* Tabs
Icons and counter can’t be supported
Icons only Tab can’t be supported.

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* Calendar
Calendar highlighting multiple Dates like Holidays, any other special days can't be supported

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +{{% todo %}}[Is there anything that needs to be mentioned here? Are there any specific use cases or configuration (e.g. for notifications)]{{% /todo %}}
Didn't get this point?

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +There are many different page layouts which you can use to base your page on. These provide you with the building blocks and widgets already arranged to provide an SAP Fiori-style page.
different page templates

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* **light** *(default)*
Quartz light

2020-11-13 19:28 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark**
Quartz Dark

2020-11-17 11:57 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* Table
I've added the bit about row selection, but I don't really understand what it means.

2020-11-17 12:11 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +{{% todo %}}[Is there anything that needs to be mentioned here? Are there any specific use cases or configuration (e.g. for notifications)]{{% /todo %}}
I just wanted to know if there was anything specific we needed to write about the building blocks. For example, how you might use the _Flex Container Left Left_, what the _Shell Bar_ is, how you might use a _Notification Action_ or what the difference is between _List 1_ and _List 4_

2020-11-17 12:16 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* **light** *(default)*
The values I put here are the ones which are used in the Java code and need to be passed in the Java action
![image](https://user-images.githubusercontent.com/35492184/99389115-d8c78980-28d6-11eb-823e-a0b594198d8d.png)
![image](https://user-images.githubusercontent.com/35492184/99389254-0ad8eb80-28d7-11eb-9769-c8fbfb66f985.png)

2020-11-17 12:16 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark**
Not the value that the Java Code takes.

2020-11-17 14:55 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +| Transparent Button | transparent-btn |
Do we need a class for ** borderless list views** ?

2020-11-19 11:55 UTC, gauravkrshah requested changes

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* Table
SAP Fiori allows to show checkboxes to select a row, that is not possible mendix. In order to select row/rows from a table, "selection Mode" properties is available in Table properties.

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +{{% todo %}}[Is there anything that needs to be mentioned here? Are there any specific use cases or configuration (e.g. for notifications)]{{% /todo %}}
we can add that for few of the building blocks. Let's keep this as improvement to this section. First release this and then iteratively we can add information to it.

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark**
yes you are correct. the name mentioned here are the theme names in our SAP Fiori library. What I want to mentioned that theme-light is corresponds to SAP Quartz light and "theme-dark" is correspond to "SAP Quartz Dark".

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +| Ghost | *requires manual CSS class, see [Applying CSS Classes Manually](#apply-css), below* |
Replace ghost with "Transparent". I have updated it in app as well.

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +The **Link button** also has Fiori 3 styling.
change it to for Link Button, see [Applying CSS Classes Manually](#apply-css), below* |

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +| Transparent Button | transparent-btn |
No not required it is added as building block

2020-11-19 11:55 UTC, gauravkrshah commented on content/partners/sap/sap-fiori-3-0.md
> +Standard Mendix **List view** widgets can be used on your pages. However, these cannot be borderless. To create a borderless list view, see [Applying CSS Classes Manually](#apply-css), below.
remove the line "To create a borderless list view, see [Applying CSS Classes Manually](#apply-css), below."
Because borderless list is available as building block.

2020-11-23 13:15 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +{{% todo %}}[Is there anything that needs to be mentioned here? Are there any specific use cases or configuration (e.g. for notifications)]{{% /todo %}}
OK - I'll mark this resolved and we can work on the next iteration.

2020-11-23 13:19 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* Table
Updated this.

2020-11-23 13:21 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark**
OK - I'll add this correspondence.

2020-11-23 13:33 UTC, MarkvanMents commented
@gauravkrshah,
I've updated the document from your comments. Hope this is OK now.
Let me know if you want any more changes, or let me know when I can publish it.
Thanks for all your help and suggestions.

2020-12-01 10:53 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +SAP Fiori 3 is SAP's target design system used to give your SAP C4/HANA application a consistent look and feel. The [SAP Fiori 3 UI Resources](#wrong) module in the Mendix App Store allows you to app
SAP Fiori user experience is a new visual design and appearance for creating UI across SAP Suite of products. SAP Fiori 3 is SAP’s new target design system for all SAP products to support the Intelligent Suite. With [SAP Fiori 3 UI Resource] module within Mendix AppStore, we bring the same visual experience for users to create apps using SAP Fiori 3 design language

2020-12-01 11:24 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* [Widgets](#widgets) – Mendix core widgets have SAP Fiori 3 styling
Mendix core widgets having SAP Fiori 3 styling

2020-12-01 11:25 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* [Building Blocks](#building-blocks) – groups of widgets which can be used to quickly create SAP Fiori styled pages
instead of 
groups of widgets
we can use
grouped widgets

2020-12-01 11:28 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +There are a few cases where you will need to apply some extra CSS classes manually to achieve the correct SAP Fiori look and feel. These are described in [Applying CSS Classes Manually](#apply-css).
instead of 
There are a few cases where you will need to apply ... ...
may be
In exceptional cases, you may need to apply ... ...

2020-12-01 11:30 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +There are also a few SAP Fiori components which are not supported by Mendix core widgets. These are listed in [Unsupported SAP Fiori Components](#unsupported-components), below.
instead of 
There are also a few SAP Fiori components which are not supported by Mendix core widgets
may be
Some Fiori 3 components are not yet supported by Mendix core widgets.

2020-12-01 11:42 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +You can see examples of the Fiori 3 navigation layouts by going to the **Layout** page of the SAP Fiori 3 UI Resources App Store Module. These layouts are designed for use in *Responsive (Web)* appli
instead of 
designed to run in a browser
may be
designed to run on any modern web browser, across any device

2020-12-01 11:43 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* SAP Default (SAP_3_0_UI_Resources)
is underscore missing? 
SAP_Default

2020-12-01 11:46 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +There are many different page templates which you can use to base your page on. These provide you with the building blocks and widgets already arranged to provide an SAP Fiori-style page.
Instead of 
There are many different page templates which you can use to base your page on. These provide you ...
may be
You may use one of the available page templates to rapidly create a compelling UI for your app. The available templates provide you ...

2020-12-01 11:47 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* **light** *(default)* – the SAP Quartz Light theme
instead of 
the SAP Quartz Light theme
may be
equivalent to the SAP Quartz Light theme

2020-12-01 11:47 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark** – the SAP Quartz Dark theme
similar comment as above

2020-12-01 11:48 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark** – the SAP Quartz Dark theme
instead of
the SAP Quartz Dark theme
may be
equivalent to the SAP Quartz Dark theme

2020-12-01 11:55 UTC, satyammx requested changes
comments inline

2020-12-01 15:21 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +SAP Fiori 3 is SAP's target design system used to give your SAP C4/HANA application a consistent look and feel. The [SAP Fiori 3 UI Resources](#wrong) module in the Mendix App Store allows you to app
@satyammx I feel we are doing SAP's selling work here - this is a technical document describing how we are supporting SAP Fiori if the user has decided to use it, not trying persuade people to switch to SAP Fiori.

```suggestion
The SAP Fiori user experience creates a consistent UI across the SAP Suite of products. SAP Fiori 3 is SAP’s new target design system for all SAP products in the *Intelligent Suite*. The  [SAP Fiori 3 UI Resource](#wrong) module in the Mendix App Store allows you to create the same user experience in your Mendix apps.
```

2020-12-01 15:22 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* [Widgets](#widgets) – Mendix core widgets have SAP Fiori 3 styling
```suggestion
* [Widgets](#widgets) – Mendix core widgets having SAP Fiori 3 styling
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* [Building Blocks](#building-blocks) – groups of widgets which can be used to quickly create SAP Fiori styled pages
I'm not sure that "grouped widgets" is more accurate. Is there any reason you want to change it?

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +There are a few cases where you will need to apply some extra CSS classes manually to achieve the correct SAP Fiori look and feel. These are described in [Applying CSS Classes Manually](#apply-css).
Is wanting to use a disabled link or an inverted link exceptional?
Perhaps
```suggestion
There are a couple of cases where you will need to apply some extra CSS classes manually to achieve the correct SAP Fiori look and feel. These are described in [Applying CSS Classes Manually](#apply-css).
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +There are also a few SAP Fiori components which are not supported by Mendix core widgets. These are listed in [Unsupported SAP Fiori Components](#unsupported-components), below.
I assume this means we are planning to support them in a future release?
```suggestion
Some SAP Fiori components are not yet supported by Mendix core widgets. These are listed in [Unsupported SAP Fiori Components](#unsupported-components), below.
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +You can see examples of the Fiori 3 navigation layouts by going to the **Layout** page of the SAP Fiori 3 UI Resources App Store Module. These layouts are designed for use in *Responsive (Web)* appli
```suggestion
You can see examples of the Fiori 3 navigation layouts by going to the **Layout** page of the SAP Fiori 3 UI Resources App Store Module. These layouts are designed for use in *Responsive (Web)* applications, designed to run in any modern web browser, on any device.
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* SAP Default (SAP_3_0_UI_Resources)
Thanks - well spotted.
```suggestion
* SAP_Default (SAP_3_0_UI_Resources)
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +There are many different page templates which you can use to base your page on. These provide you with the building blocks and widgets already arranged to provide an SAP Fiori-style page.
I find this is selling Fiori again.
How about
```suggestion
You can use one of the available page templates to rapidly create a consistent UI for your app pages. The templates provide you with the building blocks and widgets already arranged to provide an SAP Fiori-style page.
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* **light** *(default)* – the SAP Quartz Light theme
```suggestion
* **light** *(default)* – equivalent to the SAP Quartz Light theme
```

2020-12-01 15:37 UTC, MarkvanMents commented on content/partners/sap/sap-fiori-3-0.md
> +* **dark** – the SAP Quartz Dark theme
```suggestion
* **dark** – equivalent to the SAP Quartz Dark theme
```

2020-12-01 15:45 UTC, MarkvanMents commented
@satyammx 
I've applied most of your suggestions. I have made suggestions for the remaining ones - I feel that our documentation is not the place to sell Fiori, so I have tried to write it from the point of view of someone who has already made the decision to use Fiori styling.

Hope this makes sense.
Mark

2020-12-06 21:57 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +* [Building Blocks](#building-blocks) – groups of widgets which can be used to quickly create SAP Fiori styled pages
You are right. on re-reading this, grouped widgets seems less accurate

2020-12-06 21:58 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +There are a few cases where you will need to apply some extra CSS classes manually to achieve the correct SAP Fiori look and feel. These are described in [Applying CSS Classes Manually](#apply-css).
Looks ok to me.

2020-12-06 21:59 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +SAP Fiori 3 is SAP's target design system used to give your SAP C4/HANA application a consistent look and feel. The [SAP Fiori 3 UI Resources](#wrong) module in the Mendix App Store allows you to app
I like this overview much better. 
"SAP Selling" - we discussed that on slack :)

2020-12-06 22:00 UTC, satyammx commented on content/partners/sap/sap-fiori-3-0.md
> +There are many different page templates which you can use to base your page on. These provide you with the building blocks and widgets already arranged to provide an SAP Fiori-style page.
This is much better in my viewpoint.

2020-12-08 14:19 UTC, MarkvanMents commented
All comments are resolved.
@gauravkrshah I still need the links to the App Store modules, but can then publish whenever you like.

2020-12-21 14:03 UTC, MarkvanMents commented
Fiori 3.0 UI published in AppStore: https://marketplace.mendix.com/link/component/116359
Publishing documentation

2020-12-21 14:03 UTC, merged