Explain when client-side constants in offline-first apps get updated
mendix/docs pull request #2907
Opened 2020-11-26 17:51 UTC by omnajjar

2020-11-26 17:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=2907) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=2907) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=2907) it.</sub>

2020-11-26 17:55 UTC, omnajjar commented
Needs team review, will remove the draft flag once we're done reviewing it!

2020-12-02 07:30 UTC, ekrem-aktas commented on content/refguide/constants.md
> +When a constant is exposed to the client, Mendix Runtime sends its value to the client so that in addition to microflow expressions, it will also be accessible from nanoflows and page expressions. Fo
Constants are also updated when with login / logout, shall we add this as well?

2020-12-11 13:11 UTC, omnajjar commented on content/refguide/constants.md
> +When a constant is exposed to the client, Mendix Runtime sends its value to the client so that in addition to microflow expressions, it will also be accessible from nanoflows and page expressions. Fo
Done ✔️

2020-12-14 12:46 UTC, ekrem-aktas commented on content/refguide/constants.md
> +When a constant is exposed to the client, Mendix Runtime sends its value to the client so that in addition to microflow expressions, it will also be accessible from nanoflows and page expressions. Fo
Thanks for the summary @omnajjar , shall we add this as a separate paragraph instead? So the section looks like this:

------
...This means that you should not use sensitive data or secrets such as passwords when a constant is exposed to the client.

For a web or hybrid online app, changes to constant's values are reflected when a user refreshes the browser or restarts the app. For an offline-first application or a PWA app, the app stores the constants' values offline use. The app updates the constant's values in the following cases:
* When a user logs in or logs out in the app.
* When you deploy a new version of the app that contains domain model changes used in the offline-first app.

---- 

We should also not forget to remove PWA while merging this doc to 8.

2020-12-16 09:34 UTC, omnajjar commented on content/refguide/constants.md
> +When a constant is exposed to the client, Mendix Runtime sends its value to the client so that in addition to microflow expressions, it will also be accessible from nanoflows and page expressions. Fo
Will remove PWA mentioning from this PR, and will create another PR for 9 including it 👍🏼

2020-12-16 09:43 UTC, omnajjar commented on content/refguide/constants.md
> +When a constant is exposed to the client, Mendix Runtime sends its value to the client so that in addition to microflow expressions, it will also be accessible from nanoflows and page expressions. Fo
@ekrem-aktas Thanks for the suggestion, it looks better now less compressed in one big sentence!  ✔️

2020-12-16 10:30 UTC, ekrem-aktas approved these changes
LGTM

2020-12-16 10:31 UTC, ekrem-aktas requested changes
We should not mention PWA here

2020-12-16 10:59 UTC, omnajjar commented
> We should not mention PWA here

Done ✔️

2020-12-16 13:10 UTC, ekrem-aktas approved these changes
LGTM

2021-01-04 12:55 UTC, Adam-Dupaski commented
@ConnorLand I think this is for your component, please take a look.

2021-01-04 13:12 UTC, ConnorLand commented
> @ConnorLand I think this is for your component, please take a look.

Thank you. Resolving conflict and merging now.

2021-01-04 13:27 UTC, ConnorLand commented
This PR was meant for the Constants doc in RefGuide8, and successfully did so before the Mx9 migration. Therefore I've taken the text from Osama and updated the RefGuide8 doc myself. 

I'll shut this PR down now, because it targets the Mx9 doc mistakenly.

2021-01-04 13:27 UTC, closed without merging