Documentation on Oracle user/schema creation
mendix/docs pull request #2922
Opened 2020-12-03 14:51 UTC by grootjans

Improve the documentation on setting up Oracle by mentioning explicit privileges. These improvements were possible with the help of Dubai Municipality.

2020-12-03 14:51 UTC, grootjans commented
Needs to be reviewed by the data storage team.

2020-12-03 15:01 UTC, basdebakker requested changes
Some nitpicks added.

2020-12-03 15:01 UTC, basdebakker commented on content/refguide/oracle.md
> +3. Ensure the user has been granted enough quotas to create the resource it needs, or give in an unlimited grant (e.g. `GRANT UNLIMITED TABLESPACE TO mendix`v where 'mendix' is the created user/schem
I'm not sure if a database user counts as a person, but I tend to prefer "they need" and "give them". There also seems to be a spurious "v" after the grant statement.

2020-12-03 15:01 UTC, basdebakker commented on content/refguide/oracle.md
> +During the creation of the Mendix database, the amount of structural modifications made will be dependent on the size of your domain model. If this is quite large, or if theres is a large structural
"theres" should be "there", "values" should be "value"

2020-12-03 15:10 UTC, basdebakker commented on content/refguide/oracle.md
> +- SEQUENCE
Shouldn't these be "CREATE SESSION" and "CREATE SEQUENCE"?

2020-12-04 09:35 UTC, grootjans commented on content/refguide/oracle.md
> +- SEQUENCE
Yes, you are right.

2020-12-04 09:35 UTC, grootjans commented on content/refguide/oracle.md
> +3. Ensure the user has been granted enough quotas to create the resource it needs, or give in an unlimited grant (e.g. `GRANT UNLIMITED TABLESPACE TO mendix`v where 'mendix' is the created user/schem
Not a point I had fully considered, though I think changing it will definitely not harm.

2020-12-04 09:48 UTC, basdebakker commented on content/refguide/oracle.md
> +During the creation of the Mendix database, the amount of structural modifications made will be dependent on the size of your domain model. If this is quite large, or if theres is a large structural
It still says "values", there is only one value of OPEN_CURSORS.

2020-12-04 12:24 UTC, basdebakker approved these changes

2020-12-04 13:36 UTC, grootjans commented on content/refguide/oracle.md
> +During the creation of the Mendix database, the amount of structural modifications made will be dependent on the size of your domain model. If this is quite large, or if theres is a large structural
Fixed.

2020-12-04 13:36 UTC, grootjans commented on content/refguide/oracle.md
> +- SEQUENCE
Fixed

2020-12-04 14:50 UTC, merged

2020-12-04 15:16 UTC, basdebakker commented on content/refguide/oracle.md
> +When setting up an integration with an Oracle backend it is recommended that a user/schema is created with the appropriate number of privileges. In Mendix, we use a single user to update the schema-s
I'd say " the appropriate privileges", the number of them isn't relevant.

The database user doesn't "make" the DML statements, I suggest "execute" or "perform".

2020-12-04 15:16 UTC, basdebakker commented on content/refguide/oracle.md
> +During the creation of the Mendix database, the number of structural modifications made will be dependent on the size of your domain model. If this number is quite large, or if there is a large struc
This wasn't new, but now that I read it again: consider "depend" instead of "be dependent".

2020-12-04 16:03 UTC, ilagordhan commented
@basdebakker thanks for getting back to me.  As this PR is now merged, you can contact me directly if you require further changes.