Release notes for Mendix for Private Cloud - 10 December
mendix/docs pull request #2927
Opened 2020-12-07 13:58 UTC by zlogic

Updated documentation and Release Notes for the new version of Mendix Private Cloud. We're expecting to release it on Thursday, 10 December.

2020-12-08 16:32 UTC, MarkvanMents requested changes
@zlogic 
Can you answer these questions - thanks.

2020-12-08 16:32 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-cluster.md
> +        oc -n {namespace} create secret generic mendix-custom-ca --from-file=custom.crt=custom.crt
@zlogic
Is `mendix-custom-ca` just an example or is it a literal?
Perhaps we should document it as <custom ca filename>?

2020-12-08 16:32 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-config-script.md
> +        oc -n {namespace} create secret generic mendix-custom-ca --from-file=custom.crt=custom.crt
Same comment - is mendix-custom-ca a literal or a variable name?

2020-12-08 16:32 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-supported-environments.md
> +* or doesn't support TLS.
If what doesn't support TLS, the **connection**?

2020-12-09 11:47 UTC, zlogic commented on content/developerportal/deploy/private-cloud-cluster.md
> +        oc -n {namespace} create secret generic mendix-custom-ca --from-file=custom.crt=custom.crt
Yes, this is an example - I've changed it to `{secret}` in a new commit.

2020-12-09 11:47 UTC, zlogic commented on content/developerportal/deploy/private-cloud-config-script.md
> +        oc -n {namespace} create secret generic mendix-custom-ca --from-file=custom.crt=custom.crt
Yes, this is an example - I've changed it to `{secret}` in a new commit.

2020-12-09 11:47 UTC, zlogic commented on content/developerportal/deploy/private-cloud-supported-environments.md
> +* or doesn't support TLS.
I've rephrased it to _or the PostgreSQL server doesn't support TLS connections_ in a new commit

2020-12-09 12:34 UTC, MarkvanMents approved these changes
Great - ready to be published.

2020-12-10 11:04 UTC, zlogic commented
Hi @MarkvanMents, can you please publish PR now?

2020-12-10 11:08 UTC, merged