WIP: Line chart native beta documentation
mendix/docs pull request #2928
Opened 2020-12-07 14:18 UTC by IIsaku

Work in progress

2020-12-07 15:18 UTC, jordanch approved these changes
👍

2020-12-08 08:38 UTC, ConnorLand commented
@IIsaku when this can be merged, please let me know and I'll remove WIP and merge.

2020-12-09 13:09 UTC, jordanch requested changes
typo

2020-12-09 13:09 UTC, jordanch commented on content/refguide/native-styling-refguide.md
> +| `xAxis` | `fontFamily` | Applies a font types to the axis value labels (string). |
types -> type

2020-12-10 12:34 UTC, IIsaku commented on content/refguide/native-styling-refguide.md
> +| `xAxis` | `fontFamily` | Applies a font types to the axis value labels (string). |
I have changed the description a bit.

2020-12-10 12:38 UTC, jordanch commented
👍

2020-12-17 15:06 UTC, ConnorLand approved these changes

2020-12-17 15:18 UTC, merged