[Draft] Remove docs on building dojo custom widgets
mendix/docs pull request #2966
Opened 2020-12-22 09:25 UTC by mlaponder

As building pluggable widgets is preferred over building dojo custom widgets, we removed the docs for mx9 on building dojo custom widgets to encourage people to build pluggable widgets over dojo custom widgets.

2020-12-22 11:02 UTC, ConnorLand commented
We are going to merge this mx9 branch once the beta release is approved. Therefore, in a few days I will ask you to re-target your changes against the new Mx9 documentation. I'll ping you when this is possible @mlaponder . Thank you.

2020-12-23 11:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=2966) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=2966) before we can accept your contribution.<br/>**7** out of **8** committers have signed the CLA.<br/><br/>:white_check_mark: MarkvanMents<br/>:white_check_mark: loket4<br/>:white_check_mark: jogboms<br/>:white_check_mark: passalaqua<br/>:white_check_mark: ConnorLand<br/>:white_check_mark: mlaponder<br/>:white_check_mark: MariaShaposhnikova<br/>:x: ilagordhan<br/><hr/>**ilagordhan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=2966) it.</sub>

2020-12-28 09:05 UTC, ConnorLand commented
Based on my conversation with Marco, Mendix 9 marks a time when we are trying to drive customers away from dojo widgets. We actively don't want people to build new ones. Instead, we'd have them build pluggable widgets instead. So I am going to take these Mx9 docs down.

2021-01-06 15:36 UTC, ConnorLand commented
I'm going to review/merge this tomorrow.

2021-01-19 08:34 UTC, ConnorLand approved these changes

2021-01-19 08:39 UTC, ConnorLand requested changes
Please implement the changes we discussed on slack https://mendix.slack.com/archives/DFYP98R88/p1610962456015000

2021-01-19 08:42 UTC, ConnorLand commented on content/apidocs-mxsdk/apidocs/pluggable-widgets-8.md
> +title: "Pluggable Widgets API"
Based on your confined changes described over slack, are you still going to merge this doc? I don't see how it fits.

2021-01-19 08:43 UTC, ConnorLand commented on content/apidocs-mxsdk/apidocs/pluggable-widgets-8.md
> +category: "API Documentation"
The file title of this doc suggests its only for Mendix 8, but the doc title doesn't reflect that.

2021-01-19 08:45 UTC, mlaponder commented on content/apidocs-mxsdk/apidocs/pluggable-widgets-8.md
> +title: "Pluggable Widgets API"
No I am not, this page will no longer be there, I expect to push my changes later today

2021-01-19 08:46 UTC, ConnorLand commented on content/apidocs-mxsdk/apidocs/pluggable-widgets-8.md
> +title: "Pluggable Widgets API"
Ok sounds good.

2021-01-19 12:00 UTC, ConnorLand approved these changes

2021-01-19 12:18 UTC, merged