Datadog Agent Changes
mendix/docs pull request #3037
Opened 2021-02-03 09:11 UTC by MarkvanMents

2021-02-03 09:20 UTC, MarkvanMents commented
@markbastiaans 
1. Do we need to update the _Summary of Mendix Metrics_ in section 6 of the datadog-metrics.md document?
2. Is the _database.diskstorage.size_ metric the one which is controlled by `DATADOG_DATABASE_DISKSTORAGE_METRIC`?

2021-02-18 09:29 UTC, markbastiaans requested changes
Further comments:

`Datadog logging is supported in Mendix version 7.15 and above.` - we could change this to `Datadog logging and application metrics are supported in Mendix version 7.15 and above.`. The agent will in fact start for lower versions, but it will not work.

Now for the "What metrics does Mendix supply extra" table. I think this should be something like this:

Metric | Description
-- | --
jmx.com.mendix.* | Core runtime metrics
mx.database.diskstorage_size | Disk storage limit for the application database (fixed value)
mx.activity.time | How long a microflow activity takes to run
mx.client.time | The time to handle a request to a request handler that is used by the web ui
mx.microflow.time | How long a microflow takes to run
mx.odata.time | The time to handle an OData request
mx.rest.time | The time to handle a REST request
mx.soap.time | The time to handle a SOAP request

2021-02-18 09:29 UTC, markbastiaans commented on content/developerportal/operate/datadog-metrics.md
> +* system – metrics from the base system running on the platform or PaaS (see the Datadog documentation [System Check](https://docs.datadoghq.com/integrations/system/)) — Mendix only supplies system.p
Not entirely correct - we supply Processes metrics (https://docs.datadoghq.com/integrations/process/) which live inside the `system.process` space.

2021-02-18 09:29 UTC, markbastiaans commented on content/developerportal/operate/datadog-metrics.md
> +Datadog also has a *synthetics* namespace where you can send metrics specifically labelled as coming from tests (see the Datadog documentation [Synthetics](https://docs.datadoghq.com/synthetics/)), b
I would just leave out all mention of Synthetics.

2021-02-19 13:11 UTC, MarkvanMents commented on content/developerportal/operate/datadog-metrics.md
> +| database.diskstorage_size | Disk storage available to the application database (this is a fixed value) |
@markbastiaans in your comment you had this as `mx.database.diskstorage_size` while I had it originally as just `database.diskstorage_size` which is correct?

2021-02-19 13:11 UTC, MarkvanMents commented on content/developerportal/operate/datadog-metrics.md
> +* system – metrics from the base system running on the platform or PaaS (see the Datadog documentation [System Check](https://docs.datadoghq.com/integrations/system/)) — Mendix only supplies system.p
Updated

2021-02-19 13:19 UTC, MarkvanMents commented on content/developerportal/operate/datadog-metrics.md
> +| database.diskstorage_size | Disk storage available to the application database (this is a fixed value) |
Confirmed as mx. Changed.

2021-02-22 08:46 UTC, MarkvanMents commented
Can release now.

2021-02-22 08:46 UTC, merged