SAP deployment 8 February release
mendix/docs pull request #3039
Opened 2021-02-03 14:30 UTC by MarkvanMents

Includes [MCDEP-401], [MCDEP-304], and [MCDEP-293]

2021-02-05 04:10 UTC, gauravkrshah requested changes
Kindly review comments.

2021-02-05 04:10 UTC, gauravkrshah commented on content/releasenotes/developer-portal/sap-cloud-platform.md
> +* We added the ability to enable *Dynatrace* for your app deployed to SAP BTP.
Added ability to define custom environment variables for you app deployed on SAP BTP. You can enable Dynatrace for your deployed to SAP BTP by selecting variables from supported list.

2021-02-05 04:10 UTC, gauravkrshah commented on content/developerportal/deploy/sap-cloud-platform.md
> +* **DT_PAAS_TOKEN** – the token for integrating your Dynatrace environment with Cloud Foundry
this details is mentioned here https://github.com/mendix/cf-mendix-buildpack#dynatrace
Not sure we can prefer giving link to mention details here

2021-02-05 05:54 UTC, mayankmendix commented on content/developerportal/deploy/sap-cloud-platform.md
> +* **DT_PAAS_TOKEN** – the token for integrating your Dynatrace environment with Cloud Foundry
Also, the change is of generic type, that is to add custom env variables. And for Dynatrace we have added DT variables in supported variables list.

2021-02-05 09:06 UTC, MarkvanMents commented on content/developerportal/deploy/sap-cloud-platform.md
> +* [Runtime](#runtime-tab) – custom environment variables which control the behavior of the Mendix Runtime
Should we include both uses of custom environment variables? They can only add the ones we specify, not any other variables they might want to give to the SAP Cloud Foundry environment?
```suggestion
* [Runtime](#runtime-tab) – custom environment variables which define "User-Provided Variables" in SAP cloud foundry environment which can be used to control the behavior of the Mendix Runtime
```

2021-02-05 09:06 UTC, MarkvanMents commented on content/developerportal/deploy/sap-cloud-platform.md
> +* **DT_PAAS_TOKEN** – the token for integrating your Dynatrace environment with Cloud Foundry
I missed that in the UX - I'll add a bit more about "unsupported" variables.

2021-02-05 09:06 UTC, MarkvanMents commented on content/releasenotes/developer-portal/deployment.md
> +| [SAP Cloud Platform](sap-cloud-platform) | February 8th, 2020 |
```suggestion
| [SAP Cloud Platform](sap-cloud-platform) | February 8th, 2021 |
```

2021-02-05 10:28 UTC, MarkvanMents commented on content/developerportal/deploy/sap-cloud-platform.md
> +* [Runtime](#runtime-tab) – custom environment variables which control the behavior of the Mendix Runtime
OK - I've now seen how you can add your own variables. I'll add this in the runtime tab section.

2021-02-05 10:33 UTC, MarkvanMents commented on content/releasenotes/developer-portal/sap-cloud-platform.md
> +* We added the ability to enable *Dynatrace* for your app deployed to SAP BTP.
```suggestion
* We added the ability to define custom environment variables for you app deployed on SAP BTP.
* We added the ability to enable *Dynatrace* for your app deployed to SAP BTP by selecting variables from the supported custom environment variables list.
```

2021-02-05 11:26 UTC, MarkvanMents commented on content/developerportal/deploy/sap-cloud-platform.md
> +* **DT_PAAS_TOKEN** – the token for integrating your Dynatrace environment with Cloud Foundry
I've added more information about the generic environment variables.
I think it is better to have a brief summary here than point people at the buildpack, which has lots of other information in it which may not be relevant.

2021-02-10 08:33 UTC, MarkvanMents commented
SAP portal released.

2021-02-10 08:33 UTC, merged