Workflows in Studio Pro
mendix/docs pull request #3072
Opened 2021-02-18 16:07 UTC by MariaShaposhnikova

Main documents for the review in the refguide folder:
The **Workflows** section in **Application Logic**:
- workflows 
- workflow-properties
- user-task
- decisions-in-workflows
- parallel-split
- call-microflow

Page-related:
- on-click-event (Sections 3.13-3.16)

Microflow-related:
- call-workflow
- open-user-task
- open-workflow-page
- set-task-outcome

Security&Settings:
- module-security (Section 4)
- project-settings (Section 7)

2021-02-19 13:57 UTC, JefHellemansMendix reviewed
Images that might need to be updated later:
- add-user-role.png (Workflow Essentials will change to one module called Workflow Commons (1))
- call-microflow.png (Best practice for now is to add the role to the caption (Reason 2))
- decision.png (2)
- demo-users.png (MxSSOCustomizations will be removed (Reason 3))
- domain-model.png (Best practice for now is to have a separate Employee entity containing all the attributes, which is associated with an EmployeeOnboarding entity (Reason 4))
- employee-form-default.png (4)
- employees-page.png (4)
- new-page.png (3)
- prepare-desk-form.png (4)
- prepare-desk.png (2)
- project-security.png (1 & 3)
- read-only-form.png (4)
- select-module-roles-dialog.png (1 & 3)
- select-workflow.png (1 & 3)
- specify-devices-form.png (4)
- specify-location-form.png (4)
- workflow-with-specify-device-task.png (2)
- call-workflow-properties.jpg (If we get around to it, we want to add an explanation to this variable name property)
- call-workflow.jpg (not sure if the icon is final here, will check with UX (Reason 5))
- decision-example.jpg (2)
- open-user-task.jpg (5)
- open-workflow-page.jpg (5)
- parallel-split.jpg (system tasks are executed by the system, so no role is involved here (Reason 6))
- set-task-outcome.jpg (5)
- user-task-properties.jpg (task name is not meant to make the task uniquely identifiable (Reason 7))
- workflow-activities.jpg (5)
- call-microflow-example.jpg (2)
- edit-workflow-name.png (4)

2021-02-23 15:20 UTC, JefHellemansMendix commented on content/refguide/workflow-activities.md
> +* **Open workflow page** – opens an overview page specified in [workflow properties](workflow-properties)
Again, this will be renamed.

2021-02-23 15:20 UTC, JefHellemansMendix commented on content/refguide/workflow-properties.md
> +**Workflow entity** is an entity that is used as a workflow context. It should be a **Workflow Context** entity from the **System** module or its **specialization**. For more information on workflow-
I can't really think of a use-case where you would just use the entity straight from the System module, as it doesn't allow you to have any of your own data in your workflow (neither on the entity directly, nor via association to other custom entities).

Might also be worth mentioning somewhere (not necessarily this document) that we recommend to keep the workflow entity "clean", as in, only have attributes on there that are important for the current instance of your workflow, and add other data via associations. An example of this would be an `Expense` entity linked to an `Expense_Request` workflow entity, so the expense itself does not need to be aware of potential workflow attributes such as approvals or the current status.

2021-02-23 15:20 UTC, JefHellemansMendix commented on content/refguide/workflow-properties.md
> +### 2.3 Display Information Section {#display-info}
Same comments here as on the user task. We only display these properties if you use the `Workflow Commons` module. Otherwise they're just stored on a system entity somewhere and you can implement their usage yourself.

2021-02-23 15:20 UTC, JefHellemansMendix commented on content/refguide/workflow-properties.md
> +**Due in** allows you to set a deadline for the workflow and keep track of it. However, this is not an automatic reminder but rather a deadline you reference when keeping track of the workflow.
Same comment as for the `Due in` property on user tasks.

2021-02-24 14:50 UTC, MariaShaposhnikova commented on content/refguide/parallel-split.md
> +The parallel split is used to have parallel processes in your workflow. For example, when onboarding a new employee, you can have several processes running in parallel: the HR preparing necessary doc
Added, thanks!

2021-02-24 14:51 UTC, MariaShaposhnikova commented on content/refguide/project-settings.md
> +**Enable workflow** allows you to toggle the workflow functionality for your app project.
Deleted. Will the User Entity setting stay?

2021-02-24 15:01 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +For example, you can add filters and assign a task to a user in the IT department. When the workflow reaches this user task, the task will appear in their inbox:
Changed.

2021-02-24 15:16 UTC, MariaShaposhnikova commented on content/refguide/workflow-activities.md
> +* **Open workflow page** – opens an overview page specified in [workflow properties](workflow-properties)
Added a to-do comment for myself to double-check the names.

2021-02-24 15:17 UTC, MariaShaposhnikova commented on content/refguide/open-workflow-page.md
> +title: "Open Workflow Page"
Added a to-do comment for myself to double-check this.

2021-02-24 15:18 UTC, MariaShaposhnikova commented on content/refguide/on-click-event.md
> +* [Open workflow page](#open-workflow-page)
Added a to-do comment for myself to double-check this.

2021-02-24 15:24 UTC, JefHellemansMendix commented on content/refguide/project-settings.md
> +**Enable workflow** allows you to toggle the workflow functionality for your app project.
It will stay, yes. Maybe in the future this is an interesting one to bring up to a higher level, as a general User Entity for your entire application, but for now it will stay the same as what it is now.

2021-02-24 15:46 UTC, MariaShaposhnikova commented on content/refguide/workflow-properties.md
> +**Workflow entity** is an entity that is used as a workflow context. It should be a **Workflow Context** entity from the **System** module or its **specialization**. For more information on workflow-
I will just say that it should be a specialization of the Workflow Context entity then. I will also add the recommendation about the Workflow entity here, because this document gives the most details on it.

2021-02-25 12:04 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Due in** allows you to set a deadline for the user task and keep track of it. However, this is not an automatic reminder but rather a deadline you reference when keeping track of the user task.
Discussed during the call, added information about the System module and the Workflow Commons modules.

2021-02-25 12:04 UTC, MariaShaposhnikova commented on content/refguide/workflow-properties.md
> +### 2.3 Display Information Section {#display-info}
Discussed during the call, added information about the System module and the Workflow Commons modules.

2021-02-25 12:04 UTC, MariaShaposhnikova commented on content/refguide/workflow-properties.md
> +**Due in** allows you to set a deadline for the workflow and keep track of it. However, this is not an automatic reminder but rather a deadline you reference when keeping track of the workflow.
Discussed during the call, added information about the System module and the Workflow Commons modules.

2021-02-25 12:04 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Task name** is displayed in the running app. The **Task name** can contain parameters that are written between braces, e.g. {1}.
Discussed during the call, added information about the System module and the Workflow Commons modules.

2021-02-25 12:05 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Task Description** is a description of the workflow displayed in the running app. The description can contain parameters that are written between braces, e.g. {1}.
Discussed during the call, added information about the System module and the Workflow Commons modules.

2021-02-25 13:09 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +* Your project has the WorkflowEssentials module.
Hi Jef,
this how-to uses the Workflow Commons module, isn't this settings set up automatically for you when you use it?
>set up the User Entity setting in your project settings.

2021-02-25 13:18 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +4. Set the **Caption** property to **Specify Device**.
Changed.

2021-02-25 13:30 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +5. If you create a microflow from the workflow, parameters and the **Complete task** activity are added automatically. Open your microflow and make sure it has the **Complete task** activity:
I've deleted information about the Complete task as it is no longer true, only the parameter is added. I'll retake the screenshots too.

2021-02-26 15:08 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +11. By default, all attributes are added to the data view with the employee details. You need to leave only the attributes related to the task. You also need to make sure that the manager can change
Thanks for pointing out this best practice. Discussed this with Daniel. I'll add this to my to-do list but it does not have to be changed for end of March, other things have higher priorities.

2021-02-26 15:18 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +    1. Set **Task name** to **Specify_Location** and set **Caption** to **Specify Location** referring to steps 2-4 of the [Selecting a Device for the New Hire](#select-device) section.
Changed to **Name**.

2021-02-26 15:19 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +3. To be able to differentiate this user task from other ones, set the **Task name** property to **SpecifyDevice**.
I got confused between Name, Caption, and Task name. I've changed it to the **Name** property.

2021-02-26 15:57 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +* Your project has the WorkflowEssentials module.
Discussed over Slack that I should verify what entity to recommend later.

2021-03-02 15:09 UTC, DanielDamMx commented on content/refguide/activities.md
> +|         | Set task outcome | Sets which outcome the [user task](user-task) should follow. |
Set task outcome -> Mention that this can be used to complete a user task using a microflow to do some custom validations

2021-03-03 09:03 UTC, DanielDamMx commented on content/refguide/expressions.md
>  Expressions changes a value based on a function or combination of functions.
I think it is wise to add a few examples of places where expression logic is typically used. I.e. specific examples in microflows, pages, workflows.

2021-03-03 09:05 UTC, DanielDamMx commented on content/refguide/microflow.md
> +![Expose as Microflow Actin](attachments/microflows-and-nanoflows/microflow-expose.jpg)
Typo: Actin -> Action

2021-03-03 09:07 UTC, DanielDamMx commented on content/refguide/open-user-task.md
> +
we should include where to place such a button (in which data view)

2021-03-03 09:08 UTC, DanielDamMx commented on content/refguide/open-workflow-page.md
> +The **Open user task** properties pane consists of the following sections:
Open workflow page right? It says open user task here

2021-03-03 09:12 UTC, DanielDamMx commented on content/refguide/set-task-outcome.md
> +The **Open user task** properties pane consists of the following sections:
Set task outcome, not open user task properties

2021-03-03 09:13 UTC, DanielDamMx commented on content/refguide/user-task.md
> +For example, you can add filters and assign a task to a user with the Manager role:
Not "a user" but "users with the Manager role"

2021-03-03 09:13 UTC, DanielDamMx commented on content/refguide/user-task.md
> +User task allows you to assign a workflow task to a certain user.
a certain user or group of users.

2021-03-03 09:14 UTC, DanielDamMx commented on content/refguide/user-task.md
> +**Task name** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. If you are using the **Workflow Commons** module,
And I think it is used in the Inbox too

2021-03-03 09:16 UTC, DanielDamMx commented on content/refguide/user-task.md
> +#### 2.1.3 Parameters {#parameters}
do we need to explain the use of parameters in expressions here, or point to documentation elsewhere?

2021-03-03 09:17 UTC, DanielDamMx commented on content/refguide/user-task.md
> +**Due in** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. For example, you can use it to set a deadline for th
Can be displayed or used in dashboards to highlight tasks running late.

2021-03-03 09:19 UTC, DanielDamMx commented on content/refguide/user-task.md
> +**Due in** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. For example, you can use it to set a deadline for th
it is also used in dashboards when you use WorkflowCommons

2021-03-03 09:20 UTC, DanielDamMx commented on content/refguide/user-task.md
> +The outcomes property allows you to create new outcomes for the user task. These outcomes can be referred to by other elements, such as a button. For example, you have a process when you need to appr
Explain that outcomes will translate to different paths in the editor

2021-03-03 09:25 UTC, DanielDamMx commented on content/refguide/user-task.md
> +**Task page** is an overview page where the allowed roles can track the progress of the use tasks and view its details, such as its comments or attachments. When you create a page, you can use a user
"Task page is the page that an assigned user will use to inspect their task and complete it. You can also allow users to add comments or attachments on this page."

(then also refer to the Atlas page templates and snippets contained in WorkflowCommons)

Also mention that the expectation is that each user task has their own dedicated page. When you generate it from this screen, page templates are filtered to only show the compatible ones for page generation.

And we should also explain page generation (what happens under the hood with data views).

2021-03-03 09:26 UTC, DanielDamMx commented on content/refguide/user-task.md
> +**Assign user task using** allows you to manage what users will the task be assigned to. You can filter users using XPath or implement a more complicated logic and add several checks using a microflo
more complicated -> "or implement more flexible logic"

2021-03-03 09:27 UTC, DanielDamMx commented on content/refguide/user-task.md
> +
describe that the return type of the microflow should be user entity

2021-03-03 09:29 UTC, DanielDamMx commented on content/refguide/workflow-properties.md
> +We recommend to keep the workflow entity "clean", meaning, to only have attributes on it that are important for the current instance of your workflow and add other data via associations.
as discussed let's add one or two example domain models here to really make the point clear, it is quite crucial to get this right

2021-03-03 09:30 UTC, DanielDamMx commented on content/refguide/workflow-properties.md
> +The **Workflow name** can contain parameters that are written between braces, e.g. {1}.
If you are using workflow commons this is used in the Admin center and on the Workflow admin page

2021-03-03 09:30 UTC, DanielDamMx commented on content/refguide/workflow-properties.md
> +##### 2.3.3.1 Adding New Parameters
Idem, do we need to specify all of this parameter info again or point to it?

2021-03-03 09:32 UTC, DanielDamMx commented on content/refguide/workflow-properties.md
> +### 2.6 Workflow Page Section {#workflow-page}
"Workflow page is an overview page where the allowed roles (e.g. the process administrator) can track the progress of the workflow and its tasks."

When you generate a page from this screen, page templates are filtered to only show the compatible ones for page generation.

(then also refer to the Atlas page templates and snippets contained in WorkflowCommons)

And we should also explain page generation (what happens under the hood with data views).

2021-03-03 09:33 UTC, DanielDamMx commented on content/refguide/workflows.md
> +Workflow is a visual language in Mendix Studios that allows you to build extendable processes. It is fully integrated with other visual languages, such as the microflow editor and page editor.
Do we use Mendix Studios or should we just use "Studio Pro and Studio"

2021-03-03 09:34 UTC, DanielDamMx commented on content/refguide/workflows.md
> +[User task](user-task) – a central element in a workflow that allows you to assign a task to a certain user using filters or microflows.
a central element in a workflow that allows you to assign a task to a certain user or group of users using filters or microflows

2021-03-03 09:35 UTC, DanielDamMx commented on content/refguide/workflows.md
> +{{% todo %}}[Do we need to describe actions that are so simple or shall I leave them for Studio only?]{{% /todo %}}
do whatever we do for microflows, pages etc

2021-03-03 09:36 UTC, DanielDamMx commented on content/refguide/workflows.md
> +* **WorkflowVersion** – This System entity is used for versioning and for the internal administration in the Runtime. When you add an activity and run your workflow, a new version will be created.
move WorkflowVersion down as last

2021-03-03 09:38 UTC, DanielDamMx commented on content/refguide/workflows.md
> +* `$workflowData` – an instance of a Workflow entity (usually a specialization of **System.WorkflowContext**)
not just "a Workflow entity" -> the workflow entity that is configured for a specific workflow

2021-03-03 09:39 UTC, DanielDamMx commented on content/refguide/workflows.md
> +{{% todo %}}[Do we need this info? Might be better when searching for the relevant info but we didn't include such info in other visual editor documents]{{% /todo %}}
I am not against this, but if we do we should also refer to page elements. I like the searchability indeed

2021-03-03 09:39 UTC, DanielDamMx commented on content/refguide/workflows.md
> +## 7 Workflow-Specific On-Click Events
Ah, this is the page part. Suggestion: name "Pages" in title

2021-03-03 12:07 UTC, MariaShaposhnikova commented on content/refguide/project-settings.md
> +**User entity** defines the entity which the user targeting is based on. You can use the attributes of this entity in an XPath.
What explanation shall I add here?

2021-03-03 12:08 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +| XPath     | Allows you to filter users who should be assigned the user task. For example, you can assign a certain task only to users with the Manager user role. |
Mentioned that you can use attributes of this entity and added a cross-reference.

2021-03-03 12:17 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Task name** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. If you are using the **Workflow Commons** module,
I will write that it is used on preconfigured pages.

2021-03-03 12:21 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +#### 2.1.3 Parameters {#parameters}
This is a standard explanation of a parameter in documentation, we have parameters in various places of Studio Pro. For me " attributes the value of which will be displayed" is understandable for developers, especially with examples on screenshots.

2021-03-03 12:24 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Due in** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. For example, you can use it to set a deadline for th
Is this instead of "you can use it to set a deadline for the user task and display it in your app."?

2021-03-03 12:44 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +The outcomes property allows you to create new outcomes for the user task. These outcomes can be referred to by other elements, such as a button. For example, you have a process when you need to appr
I will write: "Outcomes are translated into different outgoing paths of the user task and can be referred to by other elements, such as a button."

2021-03-03 13:01 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Task page** is an overview page where the allowed roles can track the progress of the use tasks and view its details, such as its comments or attachments. When you create a page, you can use a user
"(then also refer to the Atlas page templates and snippets contained in WorkflowCommons)"
The page templates for the page generation or are there any preconfigured pages?

"When you generate it from this screen, page templates are filtered to only show the compatible ones for page generation." 
This is a rewrite of "When you create a page, you can use a user task-specific page templates." but I think I should delete this info, because this is the way Studio Pro works, so this sentence is too general and does not add anything. 

"And we should also explain page generation (what happens under the hood with data views)."
Unless there is something specific for the workflows, I would not mention it here. Also, I am not sure how to track changes in page templates in the future.

2021-03-03 13:03 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +
I will write "The return type of the microflow should be the User Entity set in Project Settings". (and a cross-reference to the document).

2021-03-03 13:16 UTC, MariaShaposhnikova commented on content/refguide/workflow-properties.md
> +##### 2.3.3.1 Adding New Parameters
I don't think so, because there are example in screenshots below and because parameters are used in many places of Studio Pro. But we can transfer an example from the screenshot into text here. 
"Parameters are attributes the value of which will be displayed. For example, you can display the name of the new employee who is being onboarded using the Name parameter."

2021-03-03 13:18 UTC, MariaShaposhnikova commented on content/refguide/workflow-properties.md
> +### 2.6 Workflow Page Section {#workflow-page}
idem to the user tasks. Let's discuss this one, because page generation is not unique for this property.

2021-03-03 13:39 UTC, MariaShaposhnikova commented on content/refguide/workflows.md
> +Workflow is a visual language in Mendix Studios that allows you to build extendable processes. It is fully integrated with other visual languages, such as the microflow editor and page editor.
According to our Product Naming Guide: Where you are describing a feature applicable to both Mendix Studio and Studio Pro, use “Mendix Studio and Studio Pro.” However, after you introduce the names of both products once and need to refer to them together again, use “the Mendix Studios.” Since this is the first time we introduce them for this section, I'll change it to “Mendix Studio and Studio Pro.”

2021-03-03 13:52 UTC, MariaShaposhnikova commented on content/refguide/activities.md
> +|         | Set task outcome | Sets which outcome the [user task](user-task) should follow. |
If I write: "This activity can be used to add custom validations and complete the user task upon them. " will it be correct?

2021-03-03 13:52 UTC, MariaShaposhnikova commented on content/refguide/activities.md
> +|         | Call workflow    | Calls a workflow. Arguments can be passed to the workflow and the result can be stored in a variable. |
Copied it from the Call microflow activity. I will delete this.

2021-03-03 13:58 UTC, MariaShaposhnikova commented on content/refguide/application-logic.md
> +Application logic in Mendix can be implemented via microflows, nanoflows, and workflows. You can change a value based on a function or combination of functions using expressions.
Will we use the same criteria for these differences? 
For example, this is the only thing I have on Microflows and Nanoflows:
"Microflows run in the runtime server and can therefore not be used in offline apps, while nanoflows run directly on the browser/device and can be used in an offline app. Furthermore, most of the actions in nanoflows run directly on the device, so there is also a speed benefit for logic which does not need access to the server."
If we use a table we should compare workflows against the same criteria: offline-online apps, but this is not how it differs from microflows and nanoflows. What do we want to add here except the waiting concept that we discussed?

2021-03-03 14:02 UTC, MariaShaposhnikova commented on content/refguide/call-microflow.md
> +Parameters of the selected microflow. Depending on the selected microflow, you will see a list of its parameters. Parameters pass data to the element. To view **Parameters**, click the ellipsis icon
This is how it works across Studio Pro, not sure if we should mention these details here.

2021-03-03 14:10 UTC, MariaShaposhnikova commented on content/refguide/call-microflow.md
> +**Outcomes** depends on the return value of the microflow. For example, for the Boolean, you have **true** and **false** outcomes, and for the enumeration: an outcome per each enumeration value and a
Not sure how to put it. "When the return type or value is not Boolean or enumeration, you will have a single outcome"?

2021-03-03 14:14 UTC, MariaShaposhnikova commented on content/refguide/call-workflow.md
> +The object which you want to use as a context.
Added "It should be a specialization of the Workflow Context entity from the System module".

2021-03-03 14:25 UTC, MariaShaposhnikova commented on content/refguide/on-click-event.md
> +* **Commit** – Specifies whether the object should be committed when running a workflow.
I will add "The object should be a specialization of the Workflow Context entity from the System module." as I am not sure that it's only the data view. Can be from a data grid, a reference set selector and other selectors, for example?

2021-03-03 17:07 UTC, MariaShaposhnikova commented on content/refguide/open-user-task.md
> +
This is about a microflow activity, not an on-click event.

2021-03-03 17:38 UTC, MariaShaposhnikova commented on content/refguide/module-security.md
> +**Workflow access** defines which workflows can be accessed by users with a certain module role.
Asked Ivan: triggered.

2021-03-03 17:53 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +If you are using the **Workflow Commons** module, when the workflow reaches this user task, the task will appear in the user's inbox:
What I wanted to say here was that if you are using Workflow Commons, you will have a preconfigured Task Inbox. Perhaps I should delete this to avoid confusion?

2021-03-04 15:20 UTC, MariaShaposhnikova commented on content/refguide/activities.md
> +|         | Set task outcome | Sets which outcome the [user task](user-task) should follow. |
I will write: "This activity can be used to complete a user task using a microflow with custom validations."

2021-03-05 14:15 UTC, MariaShaposhnikova commented on content/refguide/call-microflow.md
> +Parameters of the selected microflow. Depending on the selected microflow, you will see a list of its parameters. Parameters pass data to the element. To view **Parameters**, click the ellipsis icon
Add later

2021-03-05 14:17 UTC, MariaShaposhnikova commented on content/refguide/call-microflow.md
> +**Outcomes** depends on the return value of the microflow. For example, for the Boolean, you have **true** and **false** outcomes, and for the enumeration: an outcome per each enumeration value and a
When there is no return type

2021-03-05 14:19 UTC, MariaShaposhnikova commented on content/refguide/call-workflow.md
> +The object which you want to use as a context.
It should be of the entity type set in the Workflow property (link).

2021-03-05 14:22 UTC, MariaShaposhnikova commented on content/refguide/on-click-event.md
> +* **Commit** – Specifies whether the object should be committed when running a workflow.
"the object" check how it's described in other places

2021-03-05 14:24 UTC, MariaShaposhnikova commented on content/refguide/project-settings.md
> +**User entity** defines the entity which the user targeting is based on. You can use the attributes of this entity in an XPath.
Point to the exact property. Microflow expects this entity as a return type. (link to user task)

2021-03-05 14:26 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +If you are using the **Workflow Commons** module, when the workflow reaches this user task, the task will appear in the user's inbox:
When the wf reaches the user task, the task is created and will be displayed in the inbox if you're using Workflow Commons

2021-03-05 14:29 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Task name** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. If you are using the **Workflow Commons** module,
If you are using the **Workflow Commons** module, the **Task name** is used in page templates and on preconf pages to identify the task..

2021-03-05 14:31 UTC, MariaShaposhnikova commented on content/refguide/activities.md
> +|         | Set task outcome | Sets which outcome the [user task](user-task) should follow. |
For example....

2021-03-05 15:21 UTC, MariaShaposhnikova commented on content/refguide/application-logic.md
> +Application logic in Mendix can be implemented via microflows, nanoflows, and workflows. You can change a value based on a function or combination of functions using expressions.
Discussed during the call that we will not add a table for now.

2021-03-05 17:27 UTC, MariaShaposhnikova commented on content/refguide/on-click-event.md
> +* **Commit** – Specifies whether the object should be committed when running a workflow.
Added this sentence to the paragraph: An element calling this event should be placed in a data container connected to the workflow entity defined in its properties. 
For the **Commit** property itself, I wrote: Specifies whether the **data container** object should be committed when running a workflow.

And for **Complete Task** on-click event added: An element calling this event should be placed in a data container connected to the System.WorkflowUserTask entity. 
For the **Commit** property of the **Complete task** event: Specifies whether the **data container** object should be committed when running a workflow.

2021-03-10 10:40 UTC, MariaShaposhnikova commented on content/refguide/user-task.md
> +**Due in** is stored in the System module on the **UserTask** entity as an attribute and its data can be dynamically displayed in the running app. For example, you can use it to set a deadline for th
refers to page templates. Page templates & dashboards.

2021-03-10 10:48 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +* Your project has the WorkflowEssentials module.
Point to another how-to

2021-03-12 14:29 UTC, JefHellemansMendix reviewed
content/refguide/attachments/call-microflow/call-microflow.jpg > these properties have a `Custom mendix SSO user` parameter. We're going to change that when we get rid of the Custom SSO module.

2021-03-12 16:13 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +5. In the **Select Module Roles** dialog box, select the **Workflow Administrator** role and click **OK**. {{% todo %}}[Is this correct?]{{% /todo %}}
So, according to my how-to, I need to tell them select the HR role here in addition to the Workflow Administrator??

2021-03-12 16:14 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +5. In the **Select Module Roles** dialog box, select the **Workflow Administrator** role and click **OK**. {{% todo %}}[Is this correct?]{{% /todo %}}
For now changed to: In the Select Module Roles dialog box, select the Workflow Administrator and the HR role and click OK. These roles are now able to start the workflow.

2021-03-15 09:38 UTC, JefHellemansMendix commented on content/howto/logic-business-rules/workflow-how-to-configure.md
> +5. In the **Select Module Roles** dialog box, select the **Workflow Administrator** role and click **OK**. {{% todo %}}[Is this correct?]{{% /todo %}}
Correct.

2021-03-15 09:43 UTC, JefHellemansMendix requested changes

2021-03-15 09:43 UTC, JefHellemansMendix commented on content/refguide/module-security.md
> +For each combination you can indicate whether or not the module role has access to the workflow. You can also edit this information in a [workflow](workflow-properties) using the **Allowed roles** pr
This doesn't really mean access. It's just who can **start** the workflow. Everything else within the workflow depends on how the access on those user tasks is set up.

2021-03-29 09:06 UTC, MariaShaposhnikova commented on content/refguide/module-security.md
> +For each combination you can indicate whether or not the module role has access to the workflow. You can also edit this information in a [workflow](workflow-properties) using the **Allowed roles** pr
Changed

2021-03-31 15:45 UTC, merged