WIP: [WC-97] Add documentation for rewritten badge widget
mendix/docs pull request #3086
Opened 2021-02-25 13:46 UTC by IIsaku

The badge widget has been converted to a pluggable widget (v2.0.0) that will only be supported on MX 9 and above. I kept the old widget documentation as well, since mx developers can still use these widgets with mx 7 or 8.

2021-02-25 15:25 UTC, Keraito requested changes
Looks good, just some minor structure remarks and 1 rendering error that you should probably address 😄

2021-02-25 15:25 UTC, Keraito commented on content/appstore/widgets/badge.md
> +The [Badge](https://appstore.home.mendix.com/link/app/50325/) widget shows a value inside colored badge or label.
```suggestion
The [Badge](https://appstore.home.mendix.com/link/app/50325/) widget shows a value inside a colored badge or label.
```

2021-02-25 15:25 UTC, Keraito commented on content/appstore/widgets/badge.md
> +4. Select a brand style with the "Style" design property to give the badge or label a suitable color.
![image](https://user-images.githubusercontent.com/5955441/109174447-2761ab00-7785-11eb-9ee2-0e0280e2f2ea.png)
Based on Github markdown preview this doesn't render correctly. 

Also don't think this needs to be a numerated list since it's not like you will always do these steps together in this particular order right?

Second and third can just be combined.

2021-02-25 15:25 UTC, Keraito commented on content/appstore/widgets/badge.md
> +## 2 Configuration
I would make this `## Usage`, then L21 something like `### Default usage`, and then L26 something like `Optional configurations`.

2021-02-25 15:25 UTC, Keraito commented on content/appstore/widgets/badge.md
> +3. Select an "On click" action to trigger the action when the button is activated.
```suggestion
3. Select an "On click" action to trigger the action when the button is clicked.
```

I would also elaborate on the fact that the badge in this scenario becomes an actual `button` and fully accessible (potentially what this means unless it's too techy)

2021-02-26 07:55 UTC, IIsaku commented on content/appstore/widgets/badge.md
> +The [Badge](https://appstore.home.mendix.com/link/app/50325/) widget shows a value inside colored badge or label.
I will change this.

2021-02-26 08:08 UTC, IIsaku commented on content/appstore/widgets/badge.md
> +4. Select a brand style with the "Style" design property to give the badge or label a suitable color.
The Github markdown isn't important here. It's about whether it displays correctly on the Mendix docs website. 🙂 

I will change the optional steps to an unordered list and combine the navigate instructions with the actual configuration action step. The Github Markdown will probably be fixed now as well.

2021-02-26 08:10 UTC, IIsaku commented on content/appstore/widgets/badge.md
> +## 2 Configuration
I would keep the title configuration. Usage implies more to how the end-user will use the widget. We are targetting MX devs. @ConnorLand What do you think?

2021-02-26 08:15 UTC, IIsaku commented on content/appstore/widgets/badge.md
> +3. Select an "On click" action to trigger the action when the button is activated.
I will elaborate on this. The introduction already includes that it's a fully accessible button.

2021-02-26 08:27 UTC, Keraito approved these changes
LGTM

2021-02-26 08:27 UTC, Keraito commented on content/appstore/widgets/badge.md
> +- Select an "On click" action to convert the badge into a button which will execute this action when clicked or activated with an Enter or Space key press.
```suggestion
- Select an "On click" action to convert the badge into a button which will execute this action when clicked on or activated with an Enter or Space key press.
```

2021-02-26 08:27 UTC, Keraito commented on content/appstore/widgets/badge.md
> +## 2 Configuration
Ahhh I wasn't aware of that. My comment wasn't so much about the specific phrasing of the titles, rather about using proper subtitle (h3) tags since that's what "Steps:" and "Optional steps" feels like.

2021-02-26 08:33 UTC, Adam-Dupaski commented
@ConnorLand this is a better one for you, let me know if you have questions.

2021-03-04 13:34 UTC, ConnorLand commented on content/appstore/widgets/badge.md
> +## 2 Configuration
I would keep it `## 2 Configuration` here. There's so little text it can all fit under the one configuration heading, and indeed "Configuration" is an appropriate descriptor.

2021-03-04 13:34 UTC, ConnorLand approved these changes

2021-03-31 16:27 UTC, merged