Workflows in Studio
mendix/docs pull request #3089
Opened 2021-03-01 12:39 UTC by MariaShaposhnikova

Main documents for the review in the **studio** folder:
The **Workflows** category:

- workflows
- workflow-properties
- worklfows-user-task
- workflows-general-activities
- workflows-system-actions

Page-related:

- page-editor-widgets-events-section (Sections 2.4-2.7)

Microflow-related:

- microflows (Section 3.4)

Domain Model:

- domain-models (Section 2.1)

Security:

- settings-security

2021-03-11 15:06 UTC, JefHellemansMendix requested changes

2021-03-12 11:22 UTC, MariaShaposhnikova commented on content/studio/workflow-properties.md
> +The **Display Information** section defines the workflow name and its description that are displayed in the running (published) app.
Yes, Cit Devs will start working on workflows using an app template, so they will already have this module.

2021-03-12 14:52 UTC, MariaShaposhnikova commented on content/studio/workflow-properties.md
> +![Permissions Section](attachments/workflow-properties/permissions.jpg)
I'll resolve this conversation for now, and will add it as a to-do to check on later.

2021-03-12 15:13 UTC, MariaShaposhnikova commented on content/studio/workflows-general-activities.md
> +![Decision Example](attachments/workflows-general-activities/decision-example.jpg)
Changed

2021-03-12 15:16 UTC, MariaShaposhnikova commented on content/studio/workflows-user-task.md
> +![Task Inbox](attachments/workflows-user-task/task-inbox.jpg)
Added a to-do for myself to update it.

2021-03-12 15:29 UTC, MariaShaposhnikova commented on content/studio/workflows-user-task.md
> +![User Task Templates](attachments/workflows-user-task/user-task-templates.jpg)
I've deleted info about page templates as it works like this everywhere in Studio, not just for workflows. You get relevant page templates.

2021-03-12 15:30 UTC, MariaShaposhnikova commented on content/studio/workflows-user-task.md
> +![Outcomes Section](attachments/workflows-user-task/outcomes.jpg)
Thank you! Since this is a minor thing, I've added it as a to-do later for myself.

2021-03-15 09:35 UTC, JefHellemansMendix approved these changes

2021-03-31 16:09 UTC, merged