[WC-109] Add documentation for refactored progress bar widget
mendix/docs pull request #3100
Opened 2021-03-03 11:28 UTC by Keraito

Similar to https://github.com/mendix/docs/pull/3086:

The progress bar widget has been converted to a pluggable widget that will only be supported on MX 9 and above. I kept the old widget documentation as well, since mx developers can still use these widgets with mx 7 or 8.

2021-03-03 11:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3100) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3100) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3100) it.</sub>

2021-03-04 08:37 UTC, jordanch requested changes
minor grammatical change, elsewise LGTM 👍

2021-03-04 08:37 UTC, jordanch commented on content/appstore/widgets/progress-bar.md
> +Under the **Appearance** tab, the following styling properties can be adjusted to the progress bar:
..."adjusted **for** the progress bar" is maybe better?

2021-03-04 08:52 UTC, Keraito commented on content/appstore/widgets/progress-bar.md
> +Under the **Appearance** tab, the following styling properties can be adjusted to the progress bar:
I got stuck in my head with this verb in the context of "_adjust to_ the situation". Changed it! I also assume someone will go over this language/grammar wise cuz of the "Needs language review" label 😄

2021-03-04 12:29 UTC, ConnorLand commented on content/appstore/widgets/progress-bar.md
> +Under the **Appearance** tab, the following styling properties can be adjusted to the progress bar:
"Adjusted for" the progress bar is indeed better. Verb + preposition idioms in English are so tricky. Thanks for the good PR.

2021-03-04 12:30 UTC, ConnorLand approved these changes

2021-03-05 12:55 UTC, Keraito commented
@jordanch I updated this based on the new design specs per https://github.com/mendix/widgets-resources/pull/496. Could you re-review? The commit that matters is 9ec464f.

2021-03-26 10:37 UTC, ConnorLand approved these changes

2021-03-26 10:52 UTC, jordanch approved these changes

2021-03-31 16:10 UTC, merged