[WC-170] Add docs for renaming dropdown option to toggle in Mendix 9 [9.0.5]
mendix/docs pull request #3113
Opened 2021-03-09 10:38 UTC by tamelbrun

Added a section to the existing documentation about renaming design properties to include the new possibility to rename a dropdown option to a separate toggle property.

2021-03-10 09:47 UTC, IIsaku requested changes

2021-03-10 09:47 UTC, IIsaku commented on content/apidocs-mxsdk/apidocs/design-properties.md
> +The design property above is a replacement for the removed option **Styling option 3** of **My Dropdown Property** and will be set to **Yes** if that option was selected.
It is nice to mention here as well that the dropdown will have no option selected anymore.

2021-03-10 10:13 UTC, tamelbrun commented on content/apidocs-mxsdk/apidocs/design-properties.md
> +The design property above is a replacement for the removed option **Styling option 3** of **My Dropdown Property** and will be set to **Yes** if that option was selected.
I've added a sentence to clarify this.

2021-03-10 10:17 UTC, IIsaku commented on content/apidocs-mxsdk/apidocs/design-properties.md
> +The design property above is a replacement for the removed option **Styling option 3** of **My Dropdown Property** and will be set to **Yes** if that option was selected.
Resolved

2021-03-11 09:47 UTC, ConnorLand approved these changes

2021-03-31 16:09 UTC, merged