Deploy Mendix in HA on Windows in Microsoft Azure
mendix/docs pull request #3133
Opened 2021-03-15 14:10 UTC by ilionxedekeijzer

I was requested to write this by the Runtime Core team. It will need a technical review by @jveldhuizen before merging into the production documentation.

2021-03-15 15:20 UTC, MarkvanMents commented
Converted to draft to prevent accidental merging.

2021-03-15 15:25 UTC, MarkvanMents reviewed
Have just made comments on the lines which are causing the CI/CD to fail.
Not urgent to change them.

2021-03-15 15:25 UTC, MarkvanMents commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* [Mendix deployment on Microsoft Windows](/deploy/deploy-mendix-on-microsoft-windows)
```suggestion
* [Mendix deployment on Microsoft Windows](/developerportal/deploy/deploy-mendix-on-microsoft-windows)
```

2021-03-15 15:25 UTC, MarkvanMents commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Two or more servers configured as described in the [Deploy Mendix on Microsoft Windows](/deploy/deploy-mendix-on-microsoft-windows) guide. Make sure these servers have an extra data disk added to s
```suggestion
* Two or more servers configured as described in the [Deploy Mendix on Microsoft Windows](/developerportal/deploy/deploy-mendix-on-microsoft-windows) guide. Make sure these servers have an extra data disk added to store the Mendix application files!
```

2021-03-15 15:25 UTC, MarkvanMents commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +aliases:
Don't think we need an alias here - hopefully there aren't any bits of the product pointing to the wrong file?

2021-03-17 08:27 UTC, jveldhuizen commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +In a clustered environment there are some tasks (for example, cleaning up expired user sessions from the database) that can only be handled by one of the cluster members. By default, each Mendix app
Can you replace 'this' in the last sentence by 'this setting', so it will be:

So if you have a two server cluster, add this setting on one server and if you have five servers in your cluster, add it on four of them.

2021-03-17 08:31 UTC, jveldhuizen commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Two or more servers configured as described in the [Deploy Mendix on Microsoft Windows](/deploy/deploy-mendix-on-microsoft-windows) guide. Make sure these servers have an extra data disk added to s
I'm not sure if it's immediately clear what is meant by 'the Mendix application files'. Someone can accidentally think about the 'uploaded files' here.

Maybe it's more clear if you say:  
Make sure these servers have an extra data disk added which you configure to use as the location of apps and server files in the Mendix Service Console preferences!

2021-03-18 12:12 UTC, feddovanede commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +## 5 Configuring Azure Blob Storage as shared storage
Do you need to do this on _all_ servers?

2021-03-19 09:56 UTC, MarkvanMents commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +In a clustered environment there are some tasks (for example, cleaning up expired user sessions from the database) that can only be handled by one of the cluster members. By default, each Mendix app
```suggestion
In a clustered environment there are some tasks (for example, cleaning up expired user sessions from the database) that can only be handled by one of the cluster members. By default, each Mendix app server will execute these tasks, which can lead to issues. Disable executing these tasks on all servers **except one** by adding the Custom Mendix setting _com.mendix.core.isClusterSlave_ to _true_. So if you have a two server cluster, add this setting on one server and if you have five servers in your cluster, add it on four of them.
```

2021-03-23 13:18 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +## 5 Configuring Azure Blob Storage as shared storage
Clarified that this is indeed needed on all servres, as well as adding a section about the _com.mendix.storage.PerformDeleteFromStorage_ setting.

2021-03-23 13:20 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Two or more servers configured as described in the [Deploy Mendix on Microsoft Windows](/deploy/deploy-mendix-on-microsoft-windows) guide. Make sure these servers have an extra data disk added to s
Replaced the old text with your suggestion. Linking to paragraph 3.5 of the other document would be a good idea, but I was unable to find out how to make a link in the other document.

2021-03-23 13:20 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +In a clustered environment there are some tasks (for example, cleaning up expired user sessions from the database) that can only be handled by one of the cluster members. By default, each Mendix app
Modified this as suggested.

2021-03-23 13:22 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +aliases:
This was copied from the 'deploy-mendix-on-microsoft-windows' page, removed it now.

2021-03-23 13:22 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Two or more servers configured as described in the [Deploy Mendix on Microsoft Windows](/deploy/deploy-mendix-on-microsoft-windows) guide. Make sure these servers have an extra data disk added to s
Modified this as suggested.

2021-03-23 13:22 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* [Mendix deployment on Microsoft Windows](/deploy/deploy-mendix-on-microsoft-windows)
Modified this as suggested.

2021-03-25 16:11 UTC, grootjans commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +This document has been created as an example for setting up a high available Mendix Runtime Server environment on Windows, using the Microsoft Azure cloud platform. This will probably require some ad
I would change 

This 

> will probably require some adaptation to your situation as it is not a complete guide or a supported 'best practice' for deploying a Mendix hosting environment.
To:
will probably require some adaptation to your situation, as this guide is meant to illustrate what Mendix system and settings to take into account, and not a complete guide or a supported 'best practice' for deploying a Mendix hosting environment.

That will illustrate what goal this is for (not just the converse)

2021-03-25 16:14 UTC, grootjans commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +In a clustered environment there are some tasks (for example, cleaning up expired user sessions from the database) that can only be handled by one of the cluster members. By default, each Mendix app
Perhaps change

> that can only be handled

to 

> that should only be handled

2021-04-09 12:01 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +In a clustered environment there are some tasks (for example, cleaning up expired user sessions from the database) that can only be handled by one of the cluster members. By default, each Mendix app
Modified as suggested.

2021-04-09 12:01 UTC, ilionxedekeijzer commented on content/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +This document has been created as an example for setting up a high available Mendix Runtime Server environment on Windows, using the Microsoft Azure cloud platform. This will probably require some ad
Modified as suggested.

2021-04-12 14:23 UTC, MarkvanMents requested changes
Hi Erik (@ilionxedekeijzer)
This PR seems to contain the changes which were also in #3094.
Is that right?
I have already proofread and approved those changes so, if the same documents do appear in both, perhaps it is best to merge #3094 into the branch for this PR rather than applying both to mendix/docs/development?

We can discuss this here, or on Slack if you prefer.

Other than that, everything looks good to go.

2021-04-15 09:55 UTC, MarkvanMents commented
As discussed with Jonathan (@jveldhuizen ) merging this into a new branch so that I can merge #3094 and do a review before merging to development.

2021-04-15 09:59 UTC, merged