Add docs for Data grid 2 module
mendix/docs pull request #3155
Opened 2021-03-23 15:00 UTC by diego-antonelli

In this PR I am adding the documentation for Data grid 2 module into AppStore content section.

2021-03-23 18:18 UTC, Keraito commented on content/appstore/modules/data-grid-2.md
> +![Date filter settings](attachments/data-grid-2/date-filter-settings.png)
```suggestion

![Date filter settings](attachments/data-grid-2/date-filter-settings.png)
```

So that the text and image are not on the same line

2021-03-23 18:18 UTC, Keraito commented on content/appstore/modules/data-grid-2.md
> +{{% /alert %}}
Is this the syntax? because they don't show up like alerts in Github preview.

2021-03-24 09:23 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +{{% /alert %}}
Yes, its syntax for alerts in the build system for the docs

2021-03-24 09:27 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +{{% /alert %}}
It will result in something similar to this
![image](https://user-images.githubusercontent.com/45102481/112286405-94386a00-8c8b-11eb-9c9a-51bf55dc36ec.png)

2021-03-24 15:45 UTC, ConnorLand approved these changes

2021-03-24 15:45 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +It allows users to match date attributes based on these predefined criteria:
@ConnorLand this sentence is wrong. Number filter doesnt work with date

2021-03-24 15:45 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +It allows users to match date attributes based on these predefined criteria:
Same comment here, it only works with String attributes

2021-03-24 15:48 UTC, ConnorLand commented on content/appstore/modules/data-grid-2.md
> +It allows users to match date attributes based on these predefined criteria:
This is weird, maybe I copy/pasted something incorrectly. Thanks, I'll fix it.

2021-03-24 15:48 UTC, ConnorLand commented on content/appstore/modules/data-grid-2.md
> +It allows users to match date attributes based on these predefined criteria:
This is weird, maybe I copy/pasted something incorrectly. Thanks, I'll fix it.

2021-03-24 15:50 UTC, ConnorLand requested changes
I gotta fix some stuff

2021-03-24 16:07 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +It allows users to match date attributes based on these predefined criteria:
👍

2021-03-24 16:07 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +It allows users to match date attributes based on these predefined criteria:
👍

2021-03-25 12:45 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +The **Number filter** allows users to match date attributes based on these predefined criteria:
```suggestion
The **Number filter** allows users to match decimal, integer and long attributes based on these predefined criteria:
```

2021-03-25 12:46 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +**Text filter** allows users to match date attributes based on these predefined criteria:
```suggestion
**Text filter** allows users to match string attributes based on these predefined criteria:
```

2021-03-25 12:49 UTC, diego-antonelli commented on content/appstore/modules/data-grid-2.md
> +The **Number filter** allows users to match date attributes based on these predefined criteria:
```suggestion
The **Number filter** allows users to match decimal, integer, and long attributes based on these predefined criteria:
```

2021-03-26 10:44 UTC, ConnorLand approved these changes

2021-03-31 16:27 UTC, merged