update JS actions docs with async/await
mendix/docs pull request #3185
Opened 2021-03-29 13:51 UTC by bahkostya

2021-03-29 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3185) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3185) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3185) it.</sub>

2021-03-31 13:11 UTC, Robinfr requested changes
Reviewed, needs a few changes 😄

2021-03-31 13:11 UTC, Robinfr commented on content/howto/extensibility/best-practices-javascript-actions.md
> +TODO
There is a TODO here. But I think the part below here still needs to change a bit. We might not have to mention that you don't have to call `resolve` since there is no `Promise.resolve` in any example and we simply `return` the result in the updated examples.

What do you think?

2021-03-31 13:11 UTC, Robinfr commented on content/howto/extensibility/best-practices-javascript-actions.md
>  This function uses the browser promise API:
There is no mention of promises in this code tho aside from the usage of `async/await` so I'm not sure that we need to mention this. Maybe instead replace it with: "This function uses the Fetch API:"

2021-03-31 13:11 UTC, Robinfr commented on content/howto/extensibility/best-practices-javascript-actions.md
> +    * [Async functions](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await)
This doesn't seem aligned with the other items in the list.

2021-03-31 14:09 UTC, bahkostya commented on content/howto/extensibility/best-practices-javascript-actions.md
> +TODO
I agree, do you think we should remove the block below completely? 

> As this is a part of a promise already, it does not need to call a `resolve` function or return a promise itself — this makes error handling on promises easier, as a single error function can be used to catch errors at all three steps: fetch, parse JSON, and accessing the data (for a more detailed explanation, see the [MDN promise documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise))

2021-03-31 14:21 UTC, bahkostya commented on content/howto/extensibility/best-practices-javascript-actions.md
> +TODO
Or can be changed to something like:

> As this is an async function, error handling at all three steps: fetch, parse JSON, and accessing the data can be done inside a single `try...catch` block (for a more detailed explanation, see the [MDN documentation for error handling with async/await](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await#adding_error_handling)).

2021-04-01 06:52 UTC, Robinfr commented on content/howto/extensibility/best-practices-javascript-actions.md
> +TODO
I would replace it with the second block. I think in this instance, explaining more is probably better 😄

2021-04-01 07:02 UTC, bahkostya commented on content/howto/extensibility/best-practices-javascript-actions.md
>  This function uses the browser promise API:
fixed

2021-04-01 07:03 UTC, bahkostya commented on content/howto/extensibility/best-practices-javascript-actions.md
> +    * [Async functions](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous/Async_await)
yep, by accident had settings in IDE set to spaces, but this project uses tabs, fixed now

2021-04-01 07:37 UTC, Robinfr approved these changes

2021-04-01 07:38 UTC, Robinfr commented
@ConnorLand ready for your review 😄

2021-04-02 12:41 UTC, ConnorLand approved these changes

2021-04-02 12:45 UTC, merged