Update sync limitations: multiple sync attempts
mendix/docs pull request #3220
Opened 2021-04-02 15:31 UTC by govorov

2021-04-02 15:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3220) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3220) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3220) it.</sub>

2021-04-06 14:19 UTC, omnajjar requested changes

2021-04-06 14:19 UTC, omnajjar commented on content/refguide/offline-first.md
> +If you try to trigger another synchronization process while the synchronization is in progress, the error message will be shown:
I think here we should only outline the limitation and provide a link to the synchronize action limitation section for extra details about it., something like: 

> Running multiple synchronization processes at the same time is not supported, for more details [link_to_action]

2021-04-06 14:19 UTC, omnajjar commented on content/refguide/synchronize.md
> +If you try to trigger another synchronization process while the synchronization is in progress, the error message will be shown:
🎄 I think the word `following` is missing here, so it should be: 

>... progress, the _following_ error message will be shown:

2021-04-06 14:21 UTC, omnajjar requested changes

2021-04-07 14:35 UTC, govorov commented on content/refguide/offline-first.md
> +If you try to trigger another synchronization process while the synchronization is in progress, the error message will be shown:
Good point. Fixed :coffee:

2021-04-07 14:35 UTC, govorov commented on content/refguide/synchronize.md
> +If you try to trigger another synchronization process while the synchronization is in progress, the error message will be shown:
Fixed :coffee:

2021-04-07 14:35 UTC, govorov commented on content/refguide8/offline-first.md
> +Running multiple synchronization processes at the same time is not supported, regardless the type (full/selective).
:heavy_check_mark:

2021-04-07 14:35 UTC, govorov commented on content/refguide8/synchronize.md
> +If you try to trigger another synchronization process while the synchronization is in progress, the error message will be shown:
:heavy_check_mark:

2021-04-12 08:29 UTC, omnajjar approved these changes

2021-04-12 12:31 UTC, ConnorLand approved these changes

2021-04-12 12:31 UTC, merged