Update moving-from-atlas-2-to-3.md
mendix/docs pull request #3244
Opened 2021-04-12 07:55 UTC by thijsvdmeer83

I believe suggested files have been mixed up at some point.

2021-04-12 07:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3244) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3244) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3244) it.</sub>

2021-04-13 08:57 UTC, jordanch requested changes
File locations are correct, some text seems to have been copied and does not apply to the context.

2021-04-13 08:57 UTC, jordanch commented on content/refguide/moving-from-atlas-2-to-3.md
> +| 2          | Modifications to Atlas styling in:<ul><li>*theme_atlas2/styles/web/sass/app/_custom.scss*</li> | There are two options based on your requirements: <ul><li>If the variables apply to the
This point relates to changes in styling, not variables. Variables are e.g. colour values and styling includes e.g. classes and CSS properties and values/variable references. 

> If the variables apply to the app level... 

This should read, "If the styling applies..." 

> If you want to extract the variables into a reusable module

This should read, "If you want to extract the styles..."

The file locations for this point (2) are correct.

2021-04-13 09:56 UTC, thijsvdmeer83 reviewed
Modified text as indicated.

2021-04-13 10:33 UTC, ConnorLand approved these changes

2021-04-13 11:11 UTC, jordanch approved these changes

2021-04-13 11:23 UTC, merged