[WC-439] Add docs for the new barcode scanner widget
mendix/docs pull request #3297
Opened 2021-04-29 10:41 UTC by Keraito

New docs for new barcode scanner widget that will be introduced. code PR is in https://github.com/mendix/widgets-resources/pull/586. 

## For the docs team

Can you take a look after a technical review has been performed? I will let you know when.

2021-04-30 07:33 UTC, jordanch requested changes
Nice 💪 I have a few suggestions and found a typo.

2021-04-30 07:33 UTC, jordanch commented on content/appstore/widgets/barcode-scanner.md
> +This attribute will be used to store the resulting string of the barcode detection in.
I find this sentence difficult to read. I suggest, "The barcode detection result, being a string, will be committed to this attribute."

2021-04-30 07:33 UTC, jordanch commented on content/appstore/widgets/barcode-scanner.md
> +- **Barcode** - the attribute on the data view object in which the string result of the barcode detection will be stored in.
If you agree with my above suggestion, this could also be reworded.

2021-04-30 07:33 UTC, jordanch commented on content/appstore/widgets/barcode-scanner.md
> +  This property is by defauled enabled.
by default*

2021-04-30 07:33 UTC, jordanch commented on content/appstore/widgets/barcode-scanner.md
>  tags: ["marketplace", "marketplace component", "widget", "barcode scanner", "phonegap", "platform support"]
Will this also work in phonegap or should this tag be removed?

2021-04-30 07:50 UTC, Keraito commented on content/appstore/widgets/barcode-scanner.md
>  tags: ["marketplace", "marketplace component", "widget", "barcode scanner", "phonegap", "platform support"]
nice catch, this was leftover from previous native implementation. will remove 😄

2021-04-30 08:40 UTC, jordanch requested changes

2021-04-30 08:40 UTC, jordanch commented on content/appstore/widgets/barcode-scanner.md
> +- **Barcode** - the attribute on the data view object in which the barcode detection, being a string, will be stored in.
Apologies, I should have been more clear. I suggest, "the attribute of the Data view object which will store the barcode detection result, which is a string."

2021-04-30 09:24 UTC, Keraito commented on content/appstore/widgets/barcode-scanner.md
> +- **Barcode** - the attribute on the data view object in which the barcode detection, being a string, will be stored in.
```suggestion
- **Barcode** - the attribute of the data view object which will store the barcode detection result, which is a string.
```

2021-04-30 10:54 UTC, jordanch approved these changes

2021-04-30 11:42 UTC, Keraito commented
@Adam-Dupaski This is now ready for a language review 😄

2021-05-05 09:29 UTC, Keraito commented
@Adam-Dupaski @ConnorLand in case my previous message was missed 😄 

Also please do not merge this since the widget itself has not been released yet. I will let you know when this can be merged!

2021-05-05 09:44 UTC, Adam-Dupaski commented
@Keraito thanks, will review.

2021-05-05 11:12 UTC, Adam-Dupaski approved these changes

2021-05-07 08:14 UTC, leonardomendix approved these changes

2021-05-07 08:16 UTC, Keraito commented
@Adam-Dupaski based on testing from @leonardomendix I added a small note regarding the storing attribute in 401d015. Can you review again?

2021-05-07 09:02 UTC, Adam-Dupaski commented
@Keraito reviewed, thanks for the update.

2021-05-28 11:22 UTC, Keraito commented
@Adam-Dupaski this can be merged now

2021-05-28 11:24 UTC, merged