Private Cloud release notes May 4
mendix/docs pull request #3299
Opened 2021-04-29 12:49 UTC by zlogic

Updated documentation and release notes for the upcoming Private Cloud release.

2021-05-03 10:49 UTC, MarkvanMents requested changes
Hi Dmitrii (@zlogic )
Thanks for the comprehensive release notes.
I have one question about the httpproxy exclusion list - if you could address that to make it clearer for the customer?

2021-05-03 10:49 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-cluster.md
> +	* a special DNS label (`*`) indicates that no proxying should be done
I don't understand what putting `*` here would do.
We are listing the IPs for which no proxying should be done. If we list `*` is that a double negative? In other words, if we put `*` here than proxying has to be done for all IP addresses, even if we have added some other IP addresses here?

2021-05-03 11:59 UTC, zlogic commented on content/developerportal/deploy/private-cloud-cluster.md
> +	* a special DNS label (`*`) indicates that no proxying should be done
This is documentation from a third-party library, and the way I understand this works is:

* `*` is a double-negative, which means "do not use the proxy for any IP addresses or domains".
* If `*` is on the **No proxy for** list, adding any domains or IP addresses will not have any effect. `*,example.com,1.2.3.4/8` means "do not use the proxy for any IP address - and also don't use the proxy for `example.com` and `1.2.3.4/8`". Which is identical to just using `*`.

2021-05-04 09:03 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-cluster.md
> +	* a special DNS label (`*`) indicates that no proxying should be done
OK - updated.

2021-05-04 09:03 UTC, MarkvanMents approved these changes

2021-05-04 09:38 UTC, zlogic commented
Thank you @MarkvanMents! Can you please publish the release notes now?

2021-05-04 09:55 UTC, merged