Reinstate V3 to V4 Migration Tool
mendix/docs pull request #3377
Opened 2021-05-26 09:50 UTC by MarkvanMents

Was reverted temporarily.

2021-07-27 11:06 UTC, ravi4mendix requested changes
Adding changes for the new features that are added to the tool. Will share new updated images shortly.

2021-07-27 11:06 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +
New changes to be added:

```
### Two ways to transfer database data

The system is capable of transferring database data from v3 to v4 in the following two ways:

1. Live replication using AWS Database Migration Service (DMS).
2. PostgreSQL dump and restore.

AWS DMS allows changes on v3 to be replicated to v4 as they happen. This means smaller downtime during final migration.
However, it is important to note that sometimes AWS DMS replication fails to transfer the data correctly. When this happens we automatically detect the failure and switch to database dump and restore mode. In this case you will see the "Force database dump restore" checkbox marked automatically on the UI. Dump-restore mode could also be forced from the UI by ticking the “Force database dump restore” checkbox.

### Process with AWS DMS
```

2021-07-27 11:06 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +
Add a Note here:

```
**NOTE** : Do not mark the "Force database dump restore" checkbox
```

2021-07-27 11:06 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +
New changes to be added here

```
8. Once initial data transfer is complete, progress will be at 100% but data will be kept synchronized from v3 to v4.

### Process with PostgreSQL dump and restore

1. Follow steps 1-5 mentioned above in [Process with AWS DMS](#process-with-aws-dms) .

2. Mark the "Force database dump restore" checkbox and then click **Replicate data and files**.

    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.

    This is a one time database copy from v3 to v4 node unlike live replication. This is recommended in the following cases:

    * Database replication with AWS DMS fails to replicate the data correctly
    * Database replication with AWS DMS fails with validation errors

3. Once data transfer is complete, progress will be at 100%.
```

2021-07-27 11:06 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +* a button to **Stop replication** if the tool is currently replicating, or **Start replication** if the tool is currently stopped
Line 140 to be updated like below

```
* a button to **Stop replication** with "interrupt" option if the tool is currently replicating, or **Start replication** if the tool is currently stopped
```

2021-07-27 11:06 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +2. Click **Stop** next to the migration you want to test.
New changes to be added here

```
2. Click **Stop replication** next to the migration you want to test.

    **Note:** If replication is interrupted (i.e. “Interrupt” checkbox is marked) data on v4 could be incomplete, especially if this is done before progress has reached 100%.
   ```

2021-07-27 12:28 UTC, ravi4mendix requested changes
<img width="2239" alt="select-v3-node-to-migrate" src="https://user-images.githubusercontent.com/47148298/127153580-40c3e74a-dd0a-4334-b22a-a42243e616d0.png">
<img width="2227" alt="migration-status" src="https://user-images.githubusercontent.com/47148298/127153584-b567bd5b-d58e-4dce-90d2-f1e0d6e996a6.png">

Attaching new screenshots to replace existing ones with the same names.

2021-07-27 13:23 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +
https://github.com/mendix/docs/pull/3377/commits/6623947a8d6f583b8237528f5e777545e9efe467

2021-07-27 13:25 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +* a button to **Stop replication** if the tool is currently replicating, or **Start replication** if the tool is currently stopped
https://github.com/mendix/docs/pull/3377/commits/44772b3fbcfd6f72e324fde9c9e148bdf29b5a4a

2021-07-27 13:28 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +2. Click **Stop** next to the migration you want to test.
https://github.com/mendix/docs/pull/3377/commits/9ae99d23c7f854bb919294f5cf17ab6d362a151a

2021-07-27 13:36 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +
https://github.com/mendix/docs/pull/3377/commits/c1ed2798a77249460a15992812bd71515131fb2f

2021-07-27 13:42 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +
https://github.com/mendix/docs/pull/3377/commits/d57ca1d61a9688f81f7d58cae31dc2ef57d1fe77

2021-07-27 13:49 UTC, Adam-Dupaski commented
> 
> 
> <img alt="select-v3-node-to-migrate" width="2000" src="https://user-images.githubusercontent.com/47148298/127153580-40c3e74a-dd0a-4334-b22a-a42243e616d0.png">
> 
> <img alt="migration-status" width="2000" src="https://user-images.githubusercontent.com/47148298/127153584-b567bd5b-d58e-4dce-90d2-f1e0d6e996a6.png">
> 
> Attaching new screenshots to replace existing ones with the same names.

https://github.com/mendix/docs/pull/3377/commits/ca310d135a6340c92282db401ee989dac4c9d4aa

2021-07-27 13:50 UTC, Adam-Dupaski commented
@MarkvanMents please review upon return.

2021-07-27 14:07 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +
@Adam-Dupaski can you please move the lines 158-171 right here.

```
### Process with PostgreSQL dump and restore

1. Follow steps 1-5 mentioned above in [Process with AWS DMS](#process-with-aws-dms) .

2. Mark the "Force database dump restore" checkbox and then click **Replicate data and files**.

    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.

    This is a one time database copy from v3 to v4 node unlike live replication. This is recommended in the following cases:

    * Database replication with AWS DMS fails to replicate the data correctly
    * Database replication with AWS DMS fails with validation errors

3. Once data transfer is complete, progress will be at 100%.
```

2021-07-27 14:19 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +
https://github.com/mendix/docs/pull/3377/commits/4d04e307fbbc2f26b9c242c0712f5e5442ad80b2

2021-07-28 12:34 UTC, igor-mendix commented
4.3.3, point 2: "The replication process will copy all the data in the database, including files based on FileDocument entities, such as images, which are stored in the storage of the v3 app node." - this is confusing. It seems like it only applies to dump-restore mode, but it's not related to DB copy mode at all because this is done by file sync part.
In the same place, regarding use case scenarios. We don't expose information about the kind of DMS failure that was experienced. For now it just transitions to "failed" state, so we should simplify this. Maybe something like "DMS fails after several attempts or there's critical data validation failure in which case dump-restore mode will be forced automatically"

Also it is worth noting that dump-restore will be run twice: once on replication activation, second on replication stop (if "interrupt" flag is not set).

"The migration page lists all the ongoing migrations, including the following information:" this should be a separate header. Right now it seems to be a part of dump-restore mode.

In this section it is also worth noting that file and row counts are not realtime and may be slightly off if the v3 app is running. And maybe also note that for file sync it is refreshed on every sync run (5 minutes pause between stop of the previous one and start of the new one, not exactly every 5 minutes), and for dump-restore it's refreshed twice when actual process is run on start and on stop as mentioned above.

Maybe also a note about displayed times: they depict how much time the last operation took (be it file sync or dump-restore). These timings add to downtime, but as file sync and dump-restore are run in parallel, only the bigger one will contribute directly to the downtime.It is also recommended to stop replication at least once because upon stop there are more operations that take additional time. If the replication is stopped, last operation timing will include these additional operations thus being more accurate.

2021-07-28 14:12 UTC, ravi4mendix requested changes
Some more updates

2021-07-28 14:12 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +
```
It is important to note that if you have forced database dump restore during the initial replication or it was automatically turned on due to a detected failure with AWS DMS replication in that case the final migration will have considerable downtime.
The displayed times on the `Migration Status` page depict how much time the last operation took (be it file sync or database dump restore). These timings add to downtime, but as file sync and dump-restore are run in parallel, only the bigger one will contribute directly to the downtime.
 ```

2021-07-28 14:43 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    This is a one-time database copy from the v3 to v4 node, unlike live replication. This is recommended in the following cases:
There's a mixup here a bit. It is forced automatically only on validation failure. But it is also recommended to switch to dump-restore mode if there are multiple failures.

2021-07-28 14:51 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.
Files are stored on the appnode. IMO we should remove "files based on ..." part altogether and just say "...copy all files and data in the database"

2021-07-28 14:53 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.
IIRC we also store files on database if the microflow is designed in such a manner. That is the reason I have mentioned this. Is it not true?

2021-07-28 14:56 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    This is a one-time database copy from the v3 to v4 node, unlike live replication. This is recommended in the following cases:
Fixed it now.

2021-07-28 14:56 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    This is a one-time database copy from the v3 to v4 node, unlike live replication. This is recommended in the following cases:
So I'd replace the 3 rows Ravi mentioned with:
"This is a one-time database copy from the v3 to v4 node, unlike live replication. Database dump and restore will be forced automatically if AWS DMS data integrity check fails after multiple attempts. DMS may fail for other reasons but it does not trigger fallback to dump-restore mode because it is usually recoverable if replication is restarted. If DMS keeps failing then it is advised to force dump-restore mode manually by ticking the relevant checkbox."

2021-07-28 14:59 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +
Also worth adding:
"It is also recommended to stop replication at least once because upon stop there are more operations that take additional time. If the replication is stopped, last operation timing will include these additional operations thus being more accurate."

2021-07-29 07:23 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +    This is a one-time database copy from the v3 to v4 node, unlike live replication. This is recommended in the following cases:
https://github.com/mendix/docs/pull/3377/commits/9908a3e6b93c05a6ca47c5448210ee7d3c236763

2021-07-29 07:24 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +The migration page lists all the ongoing migrations, including the following information:
https://github.com/mendix/docs/pull/3377/commits/e35ae2451e62fc3355f4be1441de8d975fa87044

2021-07-29 07:42 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +* A button to **Stop replication** with an **Interrupt** option if the tool is currently replicating or a **Start replication** option if the tool is currently stopped
https://github.com/mendix/docs/pull/3377/commits/0212b6555d689a7bf9b6965e2f094d49a61fde28

2021-07-29 08:26 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +    ![Status of the Migration](attachments/migrating-to-v4/migration-status.png)
https://github.com/mendix/docs/pull/3377/commits/ad675f5d3e842c01a04fce8935f296afa6a9af5a

2021-07-29 08:33 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +
https://github.com/mendix/docs/pull/3377/commits/43138c59eb55eef3c83d406d9f856520663c742e

2021-07-29 08:41 UTC, Adam-Dupaski commented on content/developerportal/deploy/migrating-to-v4.md
> +
https://github.com/mendix/docs/pull/3377/commits/e6f292ba50876ddd5ef1ca6847c9bd7372de2dc8

2021-07-29 08:42 UTC, Adam-Dupaski commented
@MarkvanMents can pick up more updates from the 2nd.

2021-07-29 10:58 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.
This I don't know :(

2021-08-03 09:23 UTC, MarkvanMents reviewed
@ravi4mendix
Hi Ravi,
I've now done a final proofread - the changes are in this commit: https://github.com/mendix/docs/pull/3377/commits/f1f277dbc2548e8db84cec2b07f3010f8e4c09af.
I have added a few questions, but we can publish this now and update the document later if customers have issues around these subjects.
Let me know whether changes are needed, or whether you want me to publish.
Thanks.

2021-08-03 09:23 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +2.  Select the **Force database dump restore** check box, then click **Replicate data and files**.
Does the v3 app need to be stopped for this to work, or can you do a dump when the v3 app is running?

2021-08-03 09:23 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +The migration page lists all the ongoing migrations, including the following information:
Is the information displayed on the migration page the same for both AWS DMS and dump/restore?

2021-08-03 09:23 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
What is the difference between interrupt and not interrupt? Can we be clearer for the customer?
My assumption is:
1) Without interrupt, the stop button will not stop immediately but will continue until replication is 100%
2) For AWS DMS with interrupt, the stop button will stop the replication immediately, leaving the replication possibly incomplete and inconsistent
3) For dump/restore with interrupt, the incomplete dump will be thrown away.

Can you confirm or correct this?

2021-08-03 09:23 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes), then the apps and environments will not be renamed and the apps in the original v3 e
Is this only relevant for AWS DMS, or is there a 20 minute timeout on dump/restore as well?

2021-08-03 09:23 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the v3 appnode.
Are you still happy with keeping this about `FileDocument` entities? There doesn't seem to be a resolution to this discussion (https://github.com/mendix/docs/pull/3377#discussion_r678380965).

2021-08-03 10:15 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +2.  Select the **Force database dump restore** check box, then click **Replicate data and files**.
We can do the dump while it's still running. The only point when the app has to be stopped is final migration.

2021-08-03 10:23 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +The migration page lists all the ongoing migrations, including the following information:
It is pretty much the same. The only difference is that there's indication what mode (DMS or dump-restore) is used.

2021-08-03 10:25 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
1. Correct
2. Correct
3. The dump being taken on v3 is streamed directly to restore on v4, thus if it's interrupted only part of data will be present on v4. Which basically means the database is incomplete and unusable.

2021-08-03 10:27 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
The whole idea behind exposing the interrupt feature is to give a user the ability to correct mistakes. For example, if he selected wrong environments.

2021-08-03 10:28 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes), then the apps and environments will not be renamed and the apps in the original v3 e
Oh my, we totally missed this. Thanks for catching it. We'll have to think how to better organize this on the backend.

2021-08-03 10:43 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes), then the apps and environments will not be renamed and the apps in the original v3 e
Right, now I remembered. In case of dump-restore mode, we were thinking to add measured time of the last dump-restore operation to these 20 minutes. This measured time is shown in the interface.

This is not implemented yet, but I'll do it today if there's no opposition.

2021-08-03 10:47 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
I think it would be nice to make it a bit more explicit? How about the following?
```suggestion
* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
    * if you click **Stop replication** the replication will stop when all the data is replicated
    * if you check the **Interrupt** option, replication will stop immediately when you click **Stop replication** leaving the v4 database in an incomplete and probably inconsistent state
```

2021-08-03 10:50 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +2.  Select the **Force database dump restore** check box, then click **Replicate data and files**.
Thanks - don't need to add anything here then.

2021-08-03 11:02 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +The migration page lists all the ongoing migrations, including the following information:
Great - no change needed there either.

2021-08-03 11:06 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes), then the apps and environments will not be renamed and the apps in the original v3 e
So can I say:
```suggestion
If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes for AWS DMS — for dump restore it is 20 minutes longer than the duration of the previous replication), then the apps and environments will not be renamed and the apps in the original v3 environments will be restarted.
```

2021-08-03 13:02 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes), then the apps and environments will not be renamed and the apps in the original v3 e
"duration of previous replication" may not be right away clear to the customer. I'd say something like "for dump-restore it is set to 20 minutes plus measured operation time, which is displayed in the UI".

2021-08-03 13:05 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
"if you check the **Interrupt** option, replication will stop immediately" - I'd say "replication will terminate running operation as soon as possible". It's not exactly immediately because it'd still do some cleanup before marking it fully stopped.

2021-08-03 13:13 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +If the replication process fails during the final migration, or it times out (the timeout is fixed at 20 minutes), then the apps and environments will not be renamed and the apps in the original v3 e
Have updated the suggestion above ☝️

2021-08-03 13:14 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +* The **Stop replication** button with an **Interrupt** option if the tool is currently replicating
Have updated the suggestion above ☝️

2021-08-03 13:18 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.
It seems we're mixing up stuff here. So if we have `FileDocument` entities in the database (which are basically files, but stored in the database if I understand correctly) then we can mention that. But I don't think this is necessary because database is transferred fully. Why should we emphasize one specific record type? This only complicates things.

In addition to `FileDocument` entities that reside on the dbnode (and are transferred to RDS), there are also ordinary files that reside on the appnode (and are transferred to S3). But we don't mention that. Neither in this paragraph, nor in DMS-related list.

This is why my proposal to simplify this to having only "...copy all files and data in the database" stands.

2021-08-03 13:21 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the v3 appnode.
I've added a comment in the original thread. @ravi4mendix what do you think?

2021-08-03 13:24 UTC, igor-mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.
Or maybe better to say "...copy all file and database records".

2021-08-03 13:30 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the V3 appnode.
OK,
The thing about a `FileDocument` entity is that it is just a pointer to a file on disk. So when the app wants the content, it actually pulls it from a file, rather than from the table.
But I suppose the customer could have done something else which created files which are _not_ FileDocuments, so I'll make it more general.

2021-08-03 13:34 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the v3 appnode.
[Repeat of my other response]
The thing about a `FileDocument` entity is that it is just a pointer to a file on disk. So when the app wants the content, it actually pulls it from a file, rather than from the table.
But I suppose the customer could have done something else which created files which are _not_ FileDocuments, so I'll make it more general.
How about:
```suggestion
    The replication process will copy all the data in the database as well as all the files which are stored on the v3 appnode.
```

2021-08-03 13:38 UTC, MarkvanMents commented on content/developerportal/deploy/migrating-to-v4.md
> +    The replication process will copy all the data in the database, and files based on `FileDocument` entities, such as images, which are stored in the storage of the v3 appnode.
Discussion moved to here: https://github.com/mendix/docs/pull/3377#discussion_r681749667

2021-08-04 09:51 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    * if you check the **Interrupt** option, replication will stop as soon as possible when you click **Stop replication** leaving the v4 database in an incomplete and probably inconsistent state
Can we add one more piece of information here
```
if you check the **Interrupt** option, replication will stop as soon as possible when you click **Stop replication** leaving the v4 database in an incomplete and probably inconsistent state. In the UI you will see the state as failed when you select this option.
```

2021-08-04 09:58 UTC, ravi4mendix commented on content/developerportal/deploy/migrating-to-v4.md
> +    * if you check the **Interrupt** option, replication will stop as soon as possible when you click **Stop replication** leaving the v4 database in an incomplete and probably inconsistent state
Thanks for fixing this. Let's publish it now. We can always improve it. :)

2021-08-04 10:10 UTC, merged