SAP connectors support for OData V4
mendix/docs pull request #3427
Opened 2021-06-11 13:26 UTC by MarkvanMents

New release - awaiting confirmation of the date.

2021-06-13 06:29 UTC, gauravkrshah commented on content/partners/sap/use-sap-odata-model-creator.md
>  OData Model Creator for SAP solutions will produce a module which is in Mendix version 7.23.6. To use the module you will have to create your app in, or upgrade your app to, Mendix version 7.23.6 or
Mendix version is upgraded to 8.15.1.

2021-06-13 06:30 UTC, gauravkrshah requested changes
Please update supported Mendix version to 8.15.1 or above.

2021-06-14 08:33 UTC, MarkvanMents commented on content/partners/sap/use-sap-odata-model-creator.md
>  OData Model Creator for SAP solutions will produce a module which is in Mendix version 7.23.6. To use the module you will have to create your app in, or upgrade your app to, Mendix version 7.23.6 or
Hi Gaurav,
Will customers on 7.23 still be able to use the old version of the model creator?
We are still supposed to be supporting Mx7 and I hope this is not going to impact any SAP customers who are still on Mx 7 LTS.

2021-06-14 13:03 UTC, gauravkrshah commented on content/partners/sap/use-sap-odata-model-creator.md
>  OData Model Creator for SAP solutions will produce a module which is in Mendix version 7.23.6. To use the module you will have to create your app in, or upgrade your app to, Mendix version 7.23.6 or
Hi Mark, 
Upgrade of Mendix version is to support latest Mendix version 9.x. New model created will require Mendix v8.15.1 or above.  They will not be backward compatible. All SAP connectors modules are on the same Mendix version.

2021-06-14 14:47 UTC, MarkvanMents commented on content/partners/sap/use-sap-odata-model-creator.md
>  OData Model Creator for SAP solutions will produce a module which is in Mendix version 7.23.6. To use the module you will have to create your app in, or upgrade your app to, Mendix version 7.23.6 or
Thanks for the clarification.

2021-06-14 15:12 UTC, MarkvanMents commented on content/partners/sap/use-sap-odata-model-creator.md
>  OData Model Creator for SAP solutions will produce a module which is in Mendix version 7.23.6. To use the module you will have to create your app in, or upgrade your app to, Mendix version 7.23.6 or
Minimum version updated.

2021-06-14 17:11 UTC, gauravkrshah reviewed
Looks Good

2021-06-14 17:12 UTC, gauravkrshah approved these changes

2021-06-16 10:10 UTC, mayankmendix commented on content/partners/sap/sap-odata-connector.md
> -{{% alert type="warning" %}}
We are also releasing SAPODataConnector also and adding support for OData V4 (only GET calls).
For this kindly add here something like "OData version 4 support is added from OData Connector for SAP solutions v5.3.0, Only for GET functions".

2021-06-16 10:10 UTC, mayankmendix commented on content/partners/sap/use-sap-odata-connector.md
> -{{% alert type="warning" %}}
Same as above.

2021-06-16 10:11 UTC, mayankmendix commented on content/releasenotes/developer-portal/sap-cloud-platform.md
Kindly also add release notes for SAP OData Connector as well for OData V4 support (for GET functions).

2021-06-16 11:22 UTC, MarkvanMents commented
@mayankmendix 
Hi Mayank,
I've updated the documents as requested in this last commit (https://github.com/mendix/docs/pull/3427/commits/c0ec0a3d0b44e73db99e88d5f03b3fd126d8e584).
Please let me know when you are happy and I can publish.
Thanks.

2021-06-16 12:39 UTC, MarkvanMents commented
Changes approved over Slack.

2021-06-16 12:39 UTC, merged