Change absolute references to relative ones (TW-1344)
mendix/docs pull request #3443
Opened 2021-06-16 12:24 UTC by Luyao-Zhang-1

2021-06-17 08:20 UTC, MarkvanMents commented on CONTRIBUTING.md
> +* [How to Contribute to the Mendix Documentation](content/developerportal/community-tools/contribute-to-the-mendix-documentation)
Hi @Luyao-Zhang-1 
The links should not contain "content". This is the folder where the original markdown is kept within GitHub.
When the site is built, the HTML generated from the content folder is put in the **root** of the site.
So here, the URL is `https://docs.mendix.com/developerportal/community-tools/contribute-to-the-mendix-documentation` and the relative link is `/developerportal/community-tools/contribute-to-the-mendix-documentation`.
In other words, if I am looking at a page `https://docs.mendix.com/refguide/something` I can go to a file in the same folder by just using the file name `(something-else)`, but to go to a different space, like developerportal, I need to go back to the root of the site `(/developerportal/something-new)`. But I don't need to put the whole 'https://docs.mendix.com' because then if I'm looking at a different version (development build or, in the future, a localised build) it will always take me to the *production* site.
```suggestion
* [How to Contribute to the Mendix Documentation](/developerportal/community-tools/contribute-to-the-mendix-documentation)
```

2021-06-17 15:12 UTC, Luyao-Zhang-1 commented on CONTRIBUTING.md
> +* [How to Contribute to the Mendix Documentation](content/developerportal/community-tools/contribute-to-the-mendix-documentation)
@MarkvanMents and I talked about this. We see that the full references should be kept in this file because this file will not be published on our docs site.

2021-06-17 15:16 UTC, Luyao-Zhang-1 commented on CONTRIBUTING.md
> +* [How to Contribute to the Mendix Documentation](content/developerportal/community-tools/contribute-to-the-mendix-documentation)
We should avoid using `../` and `../../` in the cross-references, because this can lead to problems if we ever change the current folder structure. In the commit #b84dcad, I removed all the `../` and `../../` in the cross-references.

2021-06-18 10:40 UTC, MarkvanMents requested changes
Hi @Luyao-Zhang-1 
Looks good. just a couple of things on the two documents which are for the GitHub repo rather than our site.
Adam is assigned to this, so I'll let him do the final review.

2021-06-18 12:05 UTC, Adam-Dupaski commented
Reviewed, merging

2021-06-18 12:05 UTC, merged