Document behaviour for Sorting Reference Sets in Mx8.
mendix/docs pull request #3496
Opened 2021-06-30 15:56 UTC by snajahi

Once this section is reviewed, it will be copied to both Mx7 & Mx9 documentation as well.

2021-06-30 15:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3496) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3496) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3496) it.</sub>

2021-07-13 10:03 UTC, ishan1729 requested changes
Few minor comments, otherwise LGTM!

2021-07-13 10:03 UTC, ishan1729 commented on content/refguide/ordering-behavior.md
> +#### 3.1.1 HSQLDB
_3.1.1_ is a **H4** while 3.1.2, 3.1.3 is a **_H3_**. Let's use **H4** for both.

2021-07-13 10:26 UTC, ishan1729 approved these changes
LGTM!

2021-07-14 06:59 UTC, Adam-Dupaski approved these changes

2021-07-14 06:59 UTC, merged

2021-07-16 11:05 UTC, snajahi commented on content/refguide7/oql-order-by-clause.md
> +For detials on the default ordering behavior of NULL values, see [NULL Values Order Behavior](ordering-behavior#null-ordering-behavior) section of *Order by Behavior*.
There's a small typo, detials should be details