Update administrator.md
mendix/docs pull request #3520
Opened 2021-07-12 10:41 UTC by feddovanede

Add description of data restore process

2021-07-12 12:23 UTC, MarkvanMents requested changes
Good suggestion, Feddo (@feddovanede ).
I've made a couple of suggestions - you can commit them if you agree.
I also had a question about whether we should highlight this as another difference on our list of differences between free and licensed apps.
I can publish this once we have agreed what to do with my changes.

2021-07-12 12:23 UTC, MarkvanMents commented on content/refguide/administrator.md
> +The MxAdmin user is not created automatically when you deploy your app. For licensed environments the MxAdmin user is created when you change the password for the first time.
```suggestion
The MxAdmin user is not created automatically when you deploy your app as a Free App. For licensed environments the MxAdmin user is created when you change the password for the first time, for example through the [Environment Details](/developerportal/deploy/environments-details) for the Mendix Cloud.
```
@feddovanede , is this a difference between licensed and Free Apps which we should mention here: https://docs.mendix.com/developerportal/deploy/mendix-cloud-deploy#free-app?

2021-07-12 12:23 UTC, MarkvanMents commented on content/refguide/administrator.md
> +When your Free App has never been deployed, and the database still needs to be created, the data snapshot in your project will be restored to the database of your Free App, if a data snapshot is pres
```suggestion
When your Free App *has never been deployed, and the database still needs to be created*, any data snapshot you have added to your project will be restored to the database of your Free App. You can use this process to add the MxAdmin user to your Free App by doing the following:
```

2021-07-13 13:02 UTC, feddovanede commented on content/refguide/administrator.md
> +The MxAdmin user is not created automatically when you deploy your app. For licensed environments the MxAdmin user is created when you change the password for the first time.
We could. But the MxAdmin user is also not created automatically when you deploy to a licensed node. The only difference is that for licensed nodes there is a **Change Admin Password** button that will _create_ the MxAdmin user if it doesn't exist yet. If it does exist, it just updates the password. This button is not available for Free Apps.

2021-07-13 15:30 UTC, feddovanede commented on content/refguide/administrator.md
> +The MxAdmin user is not created automatically when you deploy your app. For licensed environments the MxAdmin user is created when you change the password for the first time.
Look good to me!

2021-07-14 07:36 UTC, MarkvanMents approved these changes

2021-07-14 07:37 UTC, merged