[WIP][DAT-2574] Callable Statements Documentation
mendix/docs pull request #3544
Opened 2021-07-19 01:02 UTC by snajahi

2021-07-27 12:54 UTC, dahfjkg requested changes

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +Once you have imported the Database Connector into your app, you will have the **Database Connector** category available in the **Toolbox**. The connector supports five actions: **Execute query**, **
minor: I would list the actions alphabetically.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The **Execute callable statement** microflow action is used to execute stored procedures. This action has no output and expects an input object of type `DatabaseConnector.Statement` which should defi
- `is used to execute stored procedures` — this is not entirely correct. You can also call anonymous functions.
- `This action has no output` is a bit misleading since the Statement object can contain both input and output parameters. I would say something along the lines of "This action takes an object of type `DatabaseConnector.Statement` as an input. That object contains associations to input and output parameters of the call"

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The **Execute callable statement** microflow action is used to execute stored procedures. This action has no output and expects an input object of type `DatabaseConnector.Statement` which should defi
I would briefly mention the rest of the parameters here — credentials and JDBC URL

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The **contents** attribute of the `DatabaseConnector.Statement` type should contain the statement body (i.e. the SQL content). An association with a `DatabaseConnector.Parameter` type is also availab
- `The **contents** attribute` — I would use exactly the same name as in the module, `Content`

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The **contents** attribute of the `DatabaseConnector.Statement` type should contain the statement body (i.e. the SQL content). An association with a `DatabaseConnector.Parameter` type is also availab
It is not entirely clear from this description what is meant by statement body. I think we should include at least one example of usage somewhere in this guide.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The `DatabaseConnector.Parameter` type uses the **Name** and **Position** attributes to refer to either the parameter name or position in the stored procedure. It also has a **ParameterMode** attribu
I would mention that `Name` and `Position` should not be used in the same statement: in one statement all parameters should be identified uniformly by name or uniformly by position.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +For complex SQL object types, the `DatabaseConnector.ParameterObject` can be used. The **SQLTypeName** attribute should be set to the underlying SQL type.
1. I would mention that object type needs to be defined in the database before the statement is executed.
2. I wonder if we should mention that this is applicable only to some databases. As I understand, objects are available in Oracle and PostgreSQL, but in some databases there is no such concept.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The many-to-many association with `DatabaseConnector.Parameter` allows for flexibility to define any object hierarchy needed to accurately represent the underlying SQL typ, i.e. Objects with primitiv
I would not focus on the association type here because it is an implementation detail. In fact, it would be better to have a 1-many association from `ParameterObject` to `Parameter` owned by `ParameterObject`, but Mendix does not allow that.

I would rephrase this and say that attributes of the object can be defined as specializations of `DatabaseConnector.Parameter` using `ParameterObject_Parameter` association. The module supports all specializations as long as they are supported by the underlying database.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +The many-to-many association with `DatabaseConnector.Parameter` allows for flexibility to define any object hierarchy needed to accurately represent the underlying SQL typ, i.e. Objects with primitiv
I would also mention that attributes within an object are identified by position.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +List parameters are also supported and usable via the `DatabaseConnector.ParameterList` type. The **SQLTypeName** attribute should refer to the SQL list name:
`SQLTypeName` should be a list type defined in the database beforehand, not name.

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> +This type also defines a many-to-many association with `DatabaseConnector.Parameter` for flexibility purposes. Lists of primitive types, list of objects and list of lists should be possible to repres
see my comments for Objects

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> + The parameterized actions are only available with Database Connector versions 3.0.0 and above. For these, it is necessary to use Mendix [8.6.0](/releasenotes/studio-pro/8.6#860).
shall we update this block to mention callable statements? or we can remove it altogether since we support modules in 8.12 now

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
> + The **Execute query** and **Execute parameterized query** actions should be used for querying objects with a `SELECT` SQL command. The **Execute statement** and **Execute parameterized statement** a
- `all other commands` — I would be more specific here. Would it be correct to say `All DML commands` or are there other commands that can be executed this way?

2021-07-27 12:54 UTC, dahfjkg commented on content/appstore/connectors/database-connector.md
>  * Avoid having a user input as part of your dynamic SQL queries and statements (in the future, using parameters with queries or statements will be supported)
This seems outdated

2021-07-27 12:56 UTC, dahfjkg commented
`content/appstore/connectors/attachments/database/Thumbs.db` does not need to be in this PR

2021-08-03 06:53 UTC, dahfjkg commented
Passed the internal review. We will create another PR to add some examples later. @Adam-Dupaski

2021-08-03 09:03 UTC, Adam-Dupaski commented
@dahfjkg if it's no longer in draft, please click Ready for Review to take it out of the draft state. Can this be merged right away after my review?

2021-08-03 09:45 UTC, Adam-Dupaski commented
Thanks @snajahi - I will review and merge when done.

2021-08-03 10:58 UTC, Adam-Dupaski approved these changes

2021-08-03 10:58 UTC, merged