Update: Introduce new sync mode 'Synchronize Unsynchronized Objects'
mendix/docs pull request #3546
Opened 2021-07-19 12:46 UTC by omnajjar

Docs update for Mx 9.4.0

2021-07-20 07:58 UTC, ConnorLand approved these changes

2021-07-21 14:10 UTC, ConnorLand approved these changes

2021-07-21 14:13 UTC, ConnorLand commented
@omnajjar is waiting for approval and then we can remove the Draft label.

2021-07-22 12:50 UTC, ekrem-aktas requested changes
Some comments:

* At the beginning, we say: "The Synchronize action has two modes:". No longer true.
* On section 6 there's mention of the following: "...regardless the of type (full or selective)." We can remove the full or selective part.
* Should we explicitly note that the new synchronization mode and selective synchronization do not respect the Synchronization configuration?
* Synchronization Behavior section seems like only applies to SS. Maybe we can extend it a bit with something like: "This section describes the behavior for "Synchronize unsynchronized objects" and "Synchronize selected objects" modes."
* The first sentence in the synchronization behavior section implicitly applies to SS only. Shall we make it explicit?

2021-07-23 13:11 UTC, ekrem-aktas approved these changes

2021-07-26 08:23 UTC, Adam-Dupaski approved these changes

2021-07-27 06:39 UTC, merged