[MOO-270] Add docs for nanoflow home pages
mendix/docs pull request #3548
Opened 2021-07-19 13:41 UTC by govorov

2021-07-19 13:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3548) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3548) before we can accept your contribution.<br/><hr/>**Stas Govorov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3548) it.</sub>

2021-07-19 14:17 UTC, smarki submitted a review, later dismissed

2021-07-19 14:35 UTC, govorov commented on content/howto/general/setting-up-the-navigation-structure.md
> +Home page nanoflows are not triggered on hot reload in order to keep the same page open upon reloading.
Removed ✔️

2021-07-19 15:06 UTC, ConnorLand commented
@Adam-Dupaski this is the new documentation mentioned in 9.4 RN (quoted below). I will make sure this is ready to go come 9.4 release day.

"We added more control to the startup flow of native mobile apps. Next to a page, you can now configure a nanoflow as a home page (for example, to show a setup wizard the first time an end-user opens the app). A nanoflow home page works similarly to how a microflow home page works for a web app. Check out the documentation for details."

2021-07-20 06:09 UTC, ekrem-aktas requested changes

2021-07-20 06:09 UTC, ekrem-aktas commented on content/howto/general/setting-up-the-navigation-structure.md
> +Make sure that the nanoflow contains a *Show Page* activity, or shows a page via a JavaScript action, otherwise the user will not see anything.
Otherwise, the application will keep showing the splash screen?

2021-07-20 06:09 UTC, ekrem-aktas commented on content/howto/general/setting-up-the-navigation-structure.md
> +Similar to selecting a page, you can specify a nanoflow as a home page for native profiles.
"... for the native profile of your app"?

2021-07-20 06:09 UTC, ekrem-aktas commented on content/howto/general/setting-up-the-navigation-structure.md
> +## 5 Setting a Nanoflow as a Home Page {#nanoflow-home-page}
Should we mention the following?

Some runtime behavior such as:
* Mention that the nf homepage will be executed after the initial synchronization.
* The splash screen of the app will be shown until the nanoflow executes a *Show Page* activity.

Some modelling behavior:
* An error in the homepage nanoflow can render the app unusable. Therefore recommend handling errors for actions that can fail, such as microflow calls.
* For long-running nanoflows: The best practice of showing a page early and reporting the progress?

2021-07-20 07:53 UTC, ConnorLand commented on content/howto/general/setting-up-the-navigation-structure.md
> +For more information, see the [Setting a Nanoflow as a Home Page](#nanoflow-home-page) chapter.
It is the ## 5 Setting a Nanoflow as a Home Page {#nanoflow-home-page} section below. I will resolve this.

2021-07-20 07:55 UTC, ConnorLand commented
Hi @ekrem-aktas and @govorov . After you resolve what you can between the two of you, I'll check in on this PR later today and edit.

2021-07-21 11:27 UTC, govorov commented on content/howto/general/setting-up-the-navigation-structure.md
> +Make sure that the microflow contains a *Show Form* activity, otherwise the user will not see anything.
Fair point, changed 👍 
This particular line is about startup microflows, but I fixed it too.

2021-07-21 11:32 UTC, govorov commented on content/howto/general/setting-up-the-navigation-structure.md
> +Make sure that the nanoflow contains a *Show Page* activity, or shows a page via a JavaScript action, otherwise the user will not see anything.
✔️

2021-07-21 11:33 UTC, govorov commented on content/howto/general/setting-up-the-navigation-structure.md
> +For native mobile profiles you can set a nanoflow as a home page, either as a default or as a role-based.
✔️

2021-07-21 11:34 UTC, govorov commented on content/howto/general/setting-up-the-navigation-structure.md
> +Similar to selecting a page, you can specify a nanoflow as a home page for native profiles.
✔️

2021-07-21 11:58 UTC, govorov commented on content/howto/general/setting-up-the-navigation-structure.md
> +## 5 Setting a Nanoflow as a Home Page {#nanoflow-home-page}
✔️

2021-07-21 14:05 UTC, ConnorLand approved these changes

2021-07-21 14:06 UTC, ekrem-aktas approved these changes

2021-07-27 06:39 UTC, merged