WIP - Data Hub: Share Data Between Apps
mendix/docs pull request #3565
Opened 2021-07-26 14:44 UTC by ezagroba

2021-07-28 10:51 UTC, dtitenko requested changes

2021-07-28 10:51 UTC, dtitenko commented on content/data-hub/share-data/index.md
> +To use the Mendix Data Hub a license is required, which also includes the integration of Data Hub in Studio Pro. The license enables you to discover all the shared assets that are registered in your
Duplication in phrasing.
```suggestion
To use the Mendix Data Hub a license is required. The license enables you to discover all the shared assets that are registered in your organization and also use the Data Hub integration in Studio Pro to consume the shared datasets for building apps.
```

2021-07-28 10:51 UTC, dtitenko commented on content/data-hub/share-data/index.md
> +	![](attachments/share-data/customer-overview-home-page.png)
I see you removed this image, but it's still used here.

2021-07-28 10:55 UTC, dtitenko commented on content/data-hub/share-data/index.md
> +1.  In the **Attributes** tab, click **New** to create the following attributes for the entity:
https://www.markdownguide.org/basic-syntax/#ordered-lists
Remark for myself and next reviewer. Ordered list do not need to be sequential. 👍

2021-07-28 11:00 UTC, dtitenko commented on content/data-hub/share-data/index.md
> +1. Your app was deployed to the **Mendix Free App** or **Sandbox** environment Check **Sandbox** to include it in the search results, then click **Apply Filters**.
![image](https://user-images.githubusercontent.com/2493536/127311677-143f4cf3-a289-47d8-a052-171b95e20929.png)

```suggestion
1. Your app was deployed to the **Mendix Free App** or **Sandbox** environment Check **Sandbox** to include it in the search results, then click **Apply**. 
```

2021-07-29 07:02 UTC, ezagroba commented on content/data-hub/share-data/index.md
> +	![](attachments/share-data/customer-overview-home-page.png)
I'm not sure why github is showing the diff this way, but I updated the screenshot and named it the same thing.

2021-07-29 07:05 UTC, ezagroba commented on content/data-hub/share-data/index.md
> +To use the Mendix Data Hub a license is required, which also includes the integration of Data Hub in Studio Pro. The license enables you to discover all the shared assets that are registered in your
I expect we're taking this whole paragraph out in a few weeks, but true that the current situation is not ideal.

2021-07-29 07:22 UTC, dtitenko approved these changes

2021-07-29 08:58 UTC, MariaShaposhnikova commented on content/data-hub/share-data/index.md
> +1.  In the **Attributes** tab, click **New** to create the following attributes for the entity:
@dtitenko , @ezagroba , while this is true that Markdown will be rendered correctly even if a list is not sequential, this is not the best practice to create lists like this. Such lists make it harder to review the document or to find the correct step when, for example, a user submits a feedback saying, there is a typo in step 4. Please do not number them like this in the future.

2021-07-29 15:46 UTC, MariaShaposhnikova commented on content/data-hub/share-data/index.md
> + 6. Repeat steps 5a and 5b to create attributes *FirstName*, *LastName*, *CompanyName*, *Address* and set type to *String* for all of them.
I've deleted a table from here because it's not the best practice to have a table and an image together, they look clustered. Also I did not include information on the default value of the _CustomerID_ attribute as default value is set to 1 automatically, the user does not have to change it.

2021-07-30 13:20 UTC, MariaShaposhnikova commented
@ezagroba , I've completed the review, shall I publish changes?

2021-07-30 13:36 UTC, ezagroba commented
@MariaShaposhnikova Yes, go ahead.

2021-07-30 13:39 UTC, merged