Add description for new `Use QuerySegment` feature of consumed odata
mendix/docs pull request #3612
Opened 2021-08-18 13:51 UTC by dfedorenko

…service

2021-08-18 13:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3612) before we can accept your contribution.<br/><hr/>**Dima Fedorenko** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3612) it.</sub>

2021-08-19 06:55 UTC, joostverhoog requested changes

2021-08-19 06:55 UTC, joostverhoog commented on content/refguide/consumed-odata-service.md
An attachment in /content/refguide8 was changed. This feature is for Mendix 9, right? I expected the attachment change in /content/refguide/

2021-08-19 06:55 UTC, joostverhoog commented on content/refguide/consumed-odata-service.md
> +*  **Use QuerySegment** – instructs application to use OData's QuerySegment notation ([OData specification](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_Pa
We should add a note to indicate the version in which this feature was introduced, so that people using an older version of Studio Pro 9 will not be confused by this setting not being there

2021-08-19 06:55 UTC, joostverhoog commented on content/refguide/consumed-odata-service.md
> +*  **Use QuerySegment** – instructs application to use OData's QuerySegment notation ([OData specification](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_Pa
I would prefer to start with a low-code-like explanation about what happens, and the consequences, and at the end link them to the details in the OData spec.

So something like: When set to 'No', this app retrieves data using GET requests. When set to 'Yes', it uses POST requests. The URL's of these GET request may become very long, whereas the POST requests have short URL's. Make sure that the service supports this feature. You can't set the value to 'Yes' for OData 3 services, or if the service indicates that it doesn't support it. See the --deeplink--OData specification--/deeplink-- for more details.

2021-08-19 13:03 UTC, joostverhoog commented on content/refguide/consumed-odata-service.md
> +*  **Use QuerySegment** – instructs application to use OData's QuerySegment notation ([OData specification](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_Pa
Looks good now

2021-08-19 13:03 UTC, joostverhoog commented on content/refguide/consumed-odata-service.md
> +*  **Use QuerySegment** – instructs application to use OData's QuerySegment notation ([OData specification](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_Pa
Looks good now

2021-08-19 13:04 UTC, joostverhoog approved these changes

2021-08-19 15:21 UTC, Adam-Dupaski approved these changes

2021-08-19 15:21 UTC, Adam-Dupaski commented
@joostverhoog can this be published right away?

2021-08-20 09:34 UTC, dfedorenko commented
@Adam-Dupaski this for Studio Pro 9.6.0. Also added this in property description.

2021-09-28 07:03 UTC, merged