Workflow beta migration documentation
mendix/docs pull request #3663
Opened 2021-09-03 12:47 UTC by JefHellemansMendix

2021-09-07 07:52 UTC, MitchelMx requested changes
Overall looks good, just one small comment.

2021-09-07 07:52 UTC, MitchelMx commented on content/howto/logic-business-rules/workflow-beta-migration.md
> +After upgrading to a newer Mendix version (9.6 or above), you will notice that your context entities will have become non-persistable. This is due to the `WorkflowContext` entity being removed from t
No need to make persistable, removing the generalization will do that automatically.

2021-09-07 09:39 UTC, MariaShaposhnikova commented
@JefHellemansMendix , I moved the document to the refguide and reviewed it on a high level. 
This phrase from the introduction is perfect for the release notes, but I rewrote it for the refguide: 
"We introduced workflows as a Beta feature in Mendix 9 and have received great feedback from our community. You were eager to test it out and provide us with your point of view on how to further improve the functionality, and we have done so with the Mendix 9.6 release."

2021-09-07 12:18 UTC, MariaShaposhnikova commented on content/refguide/workflow-beta-migration.md
> +4. The `WorkflowInstance` entity has been renamed to `Workflow`, as we felt this was more in line with how entity naming should be done in Mendix.
Was it decided that we rename it back to WorkflowInstance?

2021-09-09 13:33 UTC, JefHellemansMendix commented on content/refguide/workflow-beta-migration.md
> +4. The `WorkflowInstance` entity has been renamed to `Workflow`, as we felt this was more in line with how entity naming should be done in Mendix.
Last time the team discussed this we decided on `Workflow`, because technically every entity in Mendix stores "instances" and just `Workflow` is more in line with how entity naming is done in Mendix.

2021-09-09 14:26 UTC, MariaShaposhnikova commented on content/howto/logic-business-rules/workflow-beta-migration.md
> +After upgrading to a newer Mendix version (9.6 or above), you will notice that your context entities will have become non-persistable. This is due to the `WorkflowContext` entity being removed from t
@JefHellemansMendix , shall I change the text to "You can simply remove the generalization and this will automatically make your entity persistable again"?

2021-09-28 07:18 UTC, merged