Add documentation for Gallery widget
mendix/docs pull request #3674
Opened 2021-09-06 16:11 UTC by diego-antonelli

2021-09-07 07:43 UTC, ConnorLand commented on content/appstore/modules/gallery.md
> +
Is this line missing an example picture?

2021-09-07 07:47 UTC, IIsaku requested changes
Nice descriptive documentation! I added a few feedback points.

2021-09-07 07:47 UTC, IIsaku commented on content/appstore/modules/gallery.md
> +The [Gallery](https://marketplace.mendix.com/link/component/xxx) widget, a replacement for both the template grid and listview, can be used to build beautiful lists and grids across all your device t
```suggestion
The [Gallery](https://marketplace.mendix.com/link/component/xxx) widget, a replacement for both the template grid and list view, can be used to build beautiful lists and grids across all your device types (desktop, tablet and mobile). Featuring the same filtering and sorting as seen in the [Data Grid 2](https://marketplace.mendix.com/link/component/116540), combine with the options to vary the number of columns per device type, the Gallery widget gives you the power to create amazing grid and list experiences for every user.
```

2021-09-07 07:47 UTC, IIsaku commented on content/appstore/modules/gallery.md
> +![Example of configuration properties](attachments/gallery/settings.png)
Nice idea to use images for the options. The downside is the information isn't accessible for everyone. @ConnorLand What do you think?

2021-09-07 07:47 UTC, IIsaku commented on content/appstore/modules/gallery.md
> +In this example we check the value of `StringAttribute` and then apply the class `.my-name-class` if the attribute is equal to `my name` to the cell:
I think this is here by mistake.

2021-09-07 07:47 UTC, IIsaku commented on content/appstore/modules/gallery.md
> +The attributes selected here will be used for the matching filter placed inside the composable region. When using multiple attribute the filters will auto-select the matching attributes and then comb
```suggestion
The attributes selected here will be used for the matching filter placed inside the composable region. When using multiple attributes the filters will auto-select the matching attributes and then combine in an `OR expression` the desired filter value. Make sure you just have 1 filter widget for each type, example `Text Filter` and `Number Filter`.
```

2021-09-07 07:47 UTC, IIsaku commented on content/appstore/modules/gallery.md
> +In the new Gallery widget is possible to add sorting widgets to the composable region and use them based on the configurations available in the `Sorting tab`. In order to make the attributes availabl
```suggestion
In the new Gallery widget it is possible to add sorting widgets to the composable region and use them based on the configurations available in the `Sorting tab`. In order to make the attributes available for the sorting widgets you need to select an attribute and define its name to be shown in the sort button.
```

2021-09-07 09:03 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +
Fixed, my bad

2021-09-07 09:04 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +In this example we check the value of `StringAttribute` and then apply the class `.my-name-class` if the attribute is equal to `my name` to the cell:
Fixed

2021-09-07 09:28 UTC, IIsaku commented on content/appstore/modules/gallery.md
> +The [Gallery](https://marketplace.mendix.com/link/component/xxx) widget, a replacement for both the template grid and listview, can be used to build beautiful lists and grids across all your device t
```suggestion
The [Gallery](https://marketplace.mendix.com/link/component/xxx) widget, a replacement for both the template grid and list view, can be used to build beautiful lists and grids across all your device types (desktop, tablet and mobile). Featuring the same filtering and sorting as seen in the [Data Grid 2](https://marketplace.mendix.com/link/component/116540), combine with the options to vary the number of columns per device type, the Gallery widget gives you the power to create amazing grid and list experiences for every user.
```

2021-09-07 09:32 UTC, IIsaku approved these changes

2021-09-07 09:34 UTC, IIsaku commented
@ConnorLand The technical review is completed. It's all yours now 🙂

2021-09-08 12:44 UTC, ConnorLand commented on content/appstore/modules/gallery.md
> +![Example of configuration properties](attachments/gallery/settings.png)
It's a nice idea, but I think it will be less of a doc dependency if we just describe all options in order using text. This way we don't have to replace the screenshot if any one thing changes. @diego-antonelli could you remove the image please? I think the text already covers the content quite well.

2021-09-08 13:44 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +![Example of configuration properties](attachments/gallery/settings.png)
Fine by me @ConnorLand

2021-09-08 13:45 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +![Example of configuration properties](attachments/gallery/settings.png)
Done

2021-09-09 12:04 UTC, ConnorLand commented on content/appstore/modules/gallery.md
> +- Auto number
@diego-antonelli is it possible for this to be changed to "Autonumber" (one word) in the product? This would match other instances in the product a little better.

2021-09-09 12:10 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +- Auto number
Sure, i will change in the widget itself. Do you need me to change in this doc? @ConnorLand

2021-09-09 12:21 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +- Auto number
Done

2021-09-09 12:41 UTC, ConnorLand commented on content/appstore/modules/gallery.md
> +In the new Gallery widget it is possible to add sorting widgets to the composable region and use them based on the configurations available in the `Sorting tab`. In order to make the attributes avail
Is `Sorting tab` referring to code here? Because if it's referring to the sorting tab UI element, I'd like to change this to **Sorting** tab.

2021-09-09 12:50 UTC, diego-antonelli commented on content/appstore/modules/gallery.md
> +In the new Gallery widget it is possible to add sorting widgets to the composable region and use them based on the configurations available in the `Sorting tab`. In order to make the attributes avail
Its an UI element in the configurations

2021-09-14 07:28 UTC, diego-antonelli commented
Closing this PR in favor of https://github.com/mendix/docs/pull/3698

2021-09-14 07:28 UTC, closed without merging