[WC-730]: add docs for new image widget
mendix/docs pull request #3676
Opened 2021-09-07 07:50 UTC by Keraito

- This is gonna be a new image widget
- Will be released in 9.6.0
- Because it's a new widget, the marketplace link is pending

2021-09-07 09:25 UTC, IIsaku requested changes
Nice documentation. I added two points to have a look at.

2021-09-07 09:25 UTC, IIsaku commented on content/appstore/widgets/image.md
> +* **Responsive** (default: **Yes**) - When set to **Yes**, the image will never get larger than its original size. It can become smaller.
Maybe explain here also what responsive means: growing with the parent container...

2021-09-07 11:42 UTC, Keraito commented on content/appstore/widgets/image.md
> +* **Responsive** (default: **Yes**) - When set to **Yes**, the image will never get larger than its original size. It can become smaller.
Fixed

2021-09-07 12:04 UTC, Adam-Dupaski commented
@Luyao-Zhang-1 assigning this to @ConnorLand instead, as he worked on the original PR.

2021-09-28 07:18 UTC, ConnorLand approved these changes

2021-09-28 07:23 UTC, merged