Private Cloud data migration tool (no planned release date - can be reviewed at a convenient time)
mendix/docs pull request #3694
Opened 2021-09-13 09:28 UTC by zlogic

We've built a "data migration tool" that can transfer the database and all files between Mx for Private Cloud environments.
This tool is also compatible with backups created in the Mendix Cloud V4 portal - so it can be used to transfer data between Mx4PC and Mendix Cloud V4 environments.

We'd like to release this tool as an MVP/preview feature to collect customer feedback and see which features should be improved first.

The tool is ready to be published - at any convenient date or time (it's not a high priority and doesn't have any committed/planned release date).

2021-09-20 12:39 UTC, MarkvanMents requested changes
Hi Dmitrii,
@zlogic 
I've proofread this and you can see my changes in https://github.com/mendix/docs/pull/3694/commits/afc17ebfec935b352905d5e75ab92a066a60674c

I've also asked a couple of questions.

Once you've had a look and confirmed that I haven't changed anything substantially then I can approve and publish.

2021-09-20 12:39 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-data-transfer.md
> +* [Linux](https://mendix-private-cloud-resources-prod.s3.eu-west-1.amazonaws.com/mxpc-data-migration/linux/0.0.1/mxpc-data-migration-0.0.1-linux-amd64.tar.gz)
Is an S3 bucket the best place to host these?
Wouldn't a GitHub repo in the Mendix domain give customers more confidence that this is really a Mendix tool?
Or perhaps a tab in the Mx4PC portal?
Not sure whether Mendix has a best practice for this.

2021-09-20 12:39 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-data-transfer.md
> +cat <<EOF > /tmp/mendix-backup-restore.yaml
Is this <<EOF a typo? Or is it part of the instructions to make the yaml file.
I think it would be best to just list what needs to be in the yaml file and let the user create it and execute it using their preferred method?

2021-09-23 13:44 UTC, zlogic commented on content/developerportal/deploy/private-cloud-data-transfer.md
> +* [Linux](https://mendix-private-cloud-resources-prod.s3.eu-west-1.amazonaws.com/mxpc-data-migration/linux/0.0.1/mxpc-data-migration-0.0.1-linux-amd64.tar.gz)
I've moved the artifacts to be hosted in Mendix CDN.

When this tool is ready for release, we'll add a link in the Private Cloud Portal so that it's easier to find.

2021-09-23 13:52 UTC, zlogic commented on content/developerportal/deploy/private-cloud-data-transfer.md
> +cat <<EOF > /tmp/mendix-backup-restore.yaml
If a user runs this command in a Bash terminal, it will write everything between the `cat <<EOF > /tmp/mendix-backup-restore.yaml` and `EOF` lines into /tmp/mendix-backup-restore.yaml.

I've rephrased this part - to let the user decide what's the best way to create this file.

2021-09-24 07:59 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-data-transfer.md
> +* [Linux](https://mendix-private-cloud-resources-prod.s3.eu-west-1.amazonaws.com/mxpc-data-migration/linux/0.0.1/mxpc-data-migration-0.0.1-linux-amd64.tar.gz)
Great - thanks.

2021-09-24 08:00 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-data-transfer.md
> +cat <<EOF > /tmp/mendix-backup-restore.yaml
Thanks - I think that makes it clearer (for me, anyway).

2021-09-24 08:01 UTC, MarkvanMents approved these changes
Let me know when you are ready to publish.
Great documentation - as always.
Mark.

2021-09-27 08:57 UTC, zlogic commented
Thank you @MarkvanMents! Can you please publish these changes?

2021-09-27 09:01 UTC, merged