For 9.6.0 release: description of new Metrics functionality and its microflow activities
mendix/docs pull request #3711
Opened 2021-09-16 17:16 UTC by jveldhuizen

@RTI team: can you review this?

@Documentation team: can you review this after approval of the RTI team? Other question: we refer to some images in the microflow activity descriptions, like we do in the workflow activity descriptions. Should we add these images or do you want to make them?

2021-09-17 12:14 UTC, hugomendix commented on content/refguide/metrics.md
> +  `flavour`: Specifies the variant of the StatsD protocol to use.
Is this a typo? It doesn't match the examples, which state `flavor`.

2021-09-17 12:14 UTC, hugomendix commented on content/refguide/metrics.md
> +  `domain`: Jmx domain to publish the metrics.
Shouldn't `enabled` be added here as well? It is specified in one of the examples.

2021-09-17 12:14 UTC, hugomendix commented on content/refguide/metrics.md
> +Filters helps in filtering metrics based on given criterias. Below is the syntax,
Criteria is already plural (meervoud), so no s should be added.

2021-09-17 12:36 UTC, atennapel commented on content/refguide/metrics-counter.md
> +The value used to increment the counter's value. Values are specified with [expressions](expressions) and should be of type Integer/Long.
This value cannot be negative.

2021-09-17 12:51 UTC, hugomendix commented on content/refguide/metrics-counter.md
> +The value used to increment the counter's value. Values are specified with [expressions](expressions) and should be of type Integer/Long.
Can it be zero or must it be strictly positive?

2021-09-17 13:07 UTC, atennapel commented on content/refguide/metrics-counter.md
> +The value used to increment the counter's value. Values are specified with [expressions](expressions) and should be of type Integer/Long.
0 is allowed currently.

2021-09-17 13:08 UTC, hugomendix commented on content/refguide/metrics-counter.md
> +The value used to increment the counter's value. Values are specified with [expressions](expressions) and should be of type Integer/Long.
OK, just checking ;-)

2021-09-20 09:18 UTC, jveldhuizen commented on content/refguide/metrics.md
> +  `flavour`: Specifies the variant of the StatsD protocol to use.
Yes, it should be `flavor`.

2021-09-20 09:19 UTC, jveldhuizen commented on content/refguide/metrics.md
> +  `domain`: Jmx domain to publish the metrics.
No, the example is wrong. JMX and Prometheus don't have `enabled` as property (anymore).

2021-09-20 09:19 UTC, jveldhuizen commented on content/refguide/metrics.md
> +Filters helps in filtering metrics based on given criterias. Below is the syntax,
Indeed!

2021-09-20 09:24 UTC, jveldhuizen commented on content/refguide/metrics-counter.md
> +The value used to increment the counter's value. Values are specified with [expressions](expressions) and should be of type Integer/Long.
Added.

2021-09-20 13:44 UTC, hugomendix approved these changes

2021-09-20 13:47 UTC, atennapel approved these changes
Comments handled.

2021-09-21 11:51 UTC, MarkvanMents requested changes
Hi Jonathan @jveldhuizen 
Looks really good - haven't made very many changes.
Just have 3 questions which I wasn't sure about. We can publish anyway and deal with them later if necessary.

I will review the images once it is published as it is difficult to edit images which are on a fork. But they look good enough to publish, just minor things like a missing frame which can be picked up later.

2021-09-21 11:51 UTC, MarkvanMents commented on content/refguide/metrics.md
> +Settings for the specific registry. Each registry has different settings depending upon the type. Depending upon the default type of the settings in metrics, we can pass the settings or leave it to t
Not entirely sure what you mean by the following:

> Depending upon the default type of the settings in metrics, we can pass the settings or leave it to the default (if possible).

I'm not sure we need this sentence at all?

2021-09-21 13:17 UTC, jveldhuizen commented on content/refguide/metrics-counter.md
> +### 3.3 Tags
An example costs time to create... but it's also dependent on the kind of Registry (StatsD, Influx, Prometheus, etc.) how it's visible. https://micrometer.io/docs/concepts#_tag_naming gives some information. This url (without the #_tag_naming) is already at the end of this document. Is that enough? Otherwise, is it good enough to add this link here too?

2021-09-21 13:23 UTC, jveldhuizen commented on content/refguide/metrics.md
> +Settings for the specific registry. Each registry has different settings depending upon the type. Depending upon the default type of the settings in metrics, we can pass the settings or leave it to t
Indeed, I think you can remove this sentence.

2021-09-22 07:45 UTC, MarkvanMents commented on content/refguide/metrics-gauge.md
> +### 3.2 Value
Great - thanks for the confirmation.

2021-09-22 07:46 UTC, MarkvanMents commented on content/refguide/metrics-counter.md
> +### 3.3 Tags
I'll add the link - I think that will help people understand things a bit better.

2021-09-22 07:48 UTC, MarkvanMents approved these changes
I'll add links for information about tags. Then we are ready to go with 9.6.0
Great documentation @jveldhuizen  - thanks for putting in the work to get the format, menu structure, and all the rest right.

2021-09-22 07:52 UTC, MarkvanMents commented on content/refguide/metrics.md
> +Settings for the specific registry. Each registry has different settings depending upon the type. Depending upon the default type of the settings in metrics, we can pass the settings or leave it to t
Done.

2021-09-28 07:07 UTC, merged

2021-09-28 07:20 UTC, MarkvanMents commented
Images reviewed.