[WC-843] Rename properties in image-web widget general tab
mendix/docs pull request #3855
Opened 2021-11-04 11:34 UTC by raffiar

I changed a few property names in Tab-General (Data source -> Image type, etc)
Moved properties from one tab to another (**Background** moved to **Data Source**)
And changed the caption of **Conditional Visibility** element

2021-11-04 11:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=3855) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=3855) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=3855) it.</sub>

2021-11-04 13:21 UTC, raffiar commented
@Adam-Dupaski This PR still needs technical review. Can we please add @Keraito and @diego-antonelli to the Reviewers list?

2021-11-04 14:05 UTC, Adam-Dupaski commented
@raffiar sure, I'll also add `WIP` to the title and add a label for tech-review.

2021-11-04 14:06 UTC, Adam-Dupaski commented
@Keraito cannot add you as a Reviewer along with @diego-antonelli for some reason, please note here requested review.

@ConnorLand please be aware of WIP reviews.

2021-11-04 14:34 UTC, ConnorLand commented
> @Keraito cannot add you as a Reviewer along with @diego-antonelli for some reason, please note here requested review.
> 
> @ConnorLand please be aware of WIP reviews.

Will do.

2021-11-04 14:36 UTC, raffiar commented
> @Keraito cannot add you as a Reviewer along with @diego-antonelli for some reason, please note here requested review.
> 
> @ConnorLand please be aware of WIP reviews.

Thank you

2021-11-05 08:55 UTC, Keraito requested changes

2021-11-05 08:55 UTC, Keraito commented on content/appstore/widgets/image.md
> +	* Design properties will have no effect
This is incorrect, so please remove it.

2021-11-05 08:55 UTC, Keraito commented on content/appstore/widgets/image.md
> +* **Background image** - used to render image as a background
For the docs team: the widget descriptions states "Whether the image is rendered as a background" if we want to align for cinsistency.

2021-11-05 08:55 UTC, Keraito commented on content/appstore/widgets/image.md
> +* **Background image** - used to render image as a background
I also think the indentation was messed up. @raffiar please try to keep this consistent since the docs team has a certain formatting. Make sure your IDE formatter doesn't try funny stuff here 😄

2021-11-05 08:56 UTC, Keraito commented on content/appstore/widgets/image.md
> +	* Design properties will have no effect
After you remove this, you can request the docs team to review this.

2021-11-05 09:02 UTC, Keraito commented on content/appstore/widgets/image.md
>  ### 3 Styling
One more change request: can you add the new design property for align content?

2021-11-05 12:32 UTC, raffiar commented on content/appstore/widgets/image.md
> +* **Background image** - used to render image as a background
I think something is wrong with the GitHub preview. Because in a file and also in real preview it shows correct spacing.

2021-11-08 11:02 UTC, raffiar commented
Hi @ConnorLand, I would like to ask you if there's any editor config file available for this project?

2021-11-08 12:45 UTC, Keraito commented on content/appstore/widgets/image.md
> +* **Background image** - used to render image as a background
weird 🤔

2021-11-08 12:45 UTC, Keraito approved these changes

2021-11-08 12:48 UTC, Keraito commented
Approved from technical side, all yours now @ConnorLand. Please check the indentation/spacing stuff tho, something seems to be going weird there.

2021-11-08 13:49 UTC, ConnorLand commented
> Hi @ConnorLand, I would like to ask you if there's any editor config file available for this project?

Hi. I'm not familiar with those files in relation to docs. Can you provide a little more detail on what you need?

2021-11-08 14:23 UTC, ConnorLand commented
> > > Hi @ConnorLand, I would like to ask you if there's any editor config file available for this project?
> > 
> > 
> > Hi. I'm not familiar with those files in relation to docs. Can you provide a little more detail on what you need?
> 
> Basically, it's a file that configures indents in specific files. so for example `.md` files should use `1 tab `instead of `2-4 spaces`

Ah gotcha. We do not have such a file. For tabbing items in, please use 1 tab. I will go through this PR and make sure everything is formatted before merge.

2021-11-16 08:02 UTC, diego-antonelli approved these changes

2021-11-17 08:55 UTC, raffiar commented
Hi @ConnorLand , This PR is approved by @diego-antonelli and @Keraito , can you please take a look and say when it can be merged?

2021-11-17 08:58 UTC, ConnorLand commented
> Hi @ConnorLand , This PR is approved by @diego-antonelli and @Keraito , can you please take a look and say when it can be merged?

Yep, will review and merge today.

2021-11-17 09:40 UTC, ConnorLand approved these changes

2021-11-17 09:47 UTC, ConnorLand commented
I've merged and will review the indentation on our site to make sure it looks good @raffiar .

2021-11-17 09:47 UTC, merged