Mendix Operator Technical Appendix: 1 Introduction to Operators
mendix/docs pull request #3868
Opened 2021-11-11 15:42 UTC by MarkvanMents

Initial Draft

2021-11-15 09:32 UTC, zlogic requested changes

2021-11-15 09:40 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +- The `Runtime` CR uses the `Endpoint`'s status `appURL` - so that the Mendix app knows its external URL, even if the URL is automatically generatd by the Ingress controller or load balancer.
Hi Dmitrii - am doing a language review at present.
Best to wait until I've gone through the document once and then we can look at what I've missed.
Sorry I wasn't clear on the status.

2021-11-15 11:44 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +- [Minio](https://docs.min.io/minio/k8s/) - an Operator that manages Minio clusters and allows to manage self-hosted S3-combatible blob storage servers
Done

2021-11-15 11:44 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +- The `Runtime` CR uses the `Endpoint`'s status `appURL` - so that the Mendix app knows its external URL, even if the URL is automatically generatd by the Ingress controller or load balancer.
Done

2021-11-15 12:05 UTC, MarkvanMents reviewed
Hi Dmitrii (@zlogic )
I've now proofread the document, and tried to break up some of the very long blocks of text.

I've added four comments/questions. And I've removed the "draft" status to indicate it is ready for review.

Let me know when you are happy with the document and I can publish.

Mark

2021-11-15 12:05 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +At the moment, it is not possible to install one global instance of the Operator for the entire cluster.
Do we want to say "At the moment" or just describe the current state?
If this is planned to be changed in the next couple of sprints, it might be worth keeping, but otherwise I would suggest just describing what the Operator does _now_

2021-11-15 12:05 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +The Operator cannot update `StorageInstance`s at the moment, it can only create or delete them. If you update a `StoragePlan` that is currently in use by one or several `StorageInstance`s (environmen
Do we want to say "at the moment" - see comments above.

2021-11-18 12:57 UTC, zlogic commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +At the moment, it is not possible to install one global instance of the Operator for the entire cluster.
Yes, indeed "at the moment" can be removed - it was a feature that was planned some time ago, but no longer a priority and will not be implemented any time soon.

2021-11-18 13:00 UTC, zlogic commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +The Operator cannot update `StorageInstance`s at the moment, it can only create or delete them. If you update a `StoragePlan` that is currently in use by one or several `StorageInstance`s (environmen
Yes, indeed, "at the moment" can be removed, there's no timeline when this might change.

2021-11-18 15:58 UTC, zlogic commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +It is safe to update the an existing `MendixApp` CR while the Operator is still processing changes. For example, if you have decided to deploy a new MDA, but forgot to update some microflow constants
Kubernetes will notify the Operator to run the next control loop, and then the Operator will detect and cancel changes that are already running - replacing then with the updated configuration.

2021-11-18 15:59 UTC, zlogic commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +Even if the `mendix-operator` deployment is stopped and started again after some time, it will be able to process any changes that happened while the Operator was not running. This also means that in
Yes, indeed, this is a better explanation.

2021-11-18 16:16 UTC, zlogic commented
@MarkvanMents I've completed my review, the documentation looks good. Can you apply the changes you've proposed, and publish the changes?

2021-11-22 08:28 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +It is safe to update the an existing `MendixApp` CR while the Operator is still processing changes. For example, if you have decided to deploy a new MDA, but forgot to update some microflow constants
Great - I'll leave it as it is then.

2021-11-22 08:30 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +The Operator cannot update `StorageInstance`s at the moment, it can only create or delete them. If you update a `StoragePlan` that is currently in use by one or several `StorageInstance`s (environmen
```suggestion
The Operator cannot update `StorageInstance`s, it can only create or delete them. If you update a `StoragePlan` that is currently in use by one or several `StorageInstance`s (environments), it will not automatically update the `StorageInstance`s that were already created. Also, some changes such as switching to another database server will migrate the data between servers.
```

2021-11-22 08:30 UTC, MarkvanMents commented on content/developerportal/deploy/private-cloud-technical-appendix-01.md
> +At the moment, it is not possible to install one global instance of the Operator for the entire cluster.
```suggestion
It is not possible to install one global instance of the Operator for the entire cluster.
```

2021-11-22 08:32 UTC, MarkvanMents commented
I've updated the document and will merge now.

2021-11-22 08:41 UTC, merged