[RTI-364] Add ScheduledEventsCleanupAge and ProcessedTasksCleanupAge runtime settings
mendix/docs pull request #3899
Opened 2021-11-19 16:31 UTC by atennapel

For Mx9.9.

2021-11-22 06:46 UTC, Adam-Dupaski approved these changes

2021-11-22 07:26 UTC, hugomendix requested changes

2021-11-22 07:26 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ScheduledEventsCleanupAge** | This settings specifies (in milliseconds) how old completed scheduled events can be before they are removed from the database. By default this settin
- It sounds a big strange to state that the "setting is off". Maybe rephrase to: "When this setting is not specified, no cleanup is performed."
- Typo: "settings" -> "setting"

2021-11-22 07:26 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ScheduledEventsCleanupAge** | This settings specifies (in milliseconds) how old completed scheduled events can be before they are removed from the database. By default this settin
The term "scheduled events" might be confusing, because the model also contains scheduled events, which are obviously not removed. We could state more clearly that the `System.ScheduledEventInformation` rows are cleaned up from the database.

2021-11-22 07:26 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ProcessedTasksCleanupAge** | This settings specifies (in milliseconds) how old completed processed tasks can be before they are removed from the database. By default this setting
Same comments as for scheduled events.

2021-11-22 07:49 UTC, Adam-Dupaski commented
@MarkvanMents please take a look at these comments and further changes requested from Hugo

2021-11-22 10:25 UTC, atennapel commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ScheduledEventsCleanupAge** | This settings specifies (in milliseconds) how old completed scheduled events can be before they are removed from the database. By default this settin
Updated.

2021-11-22 10:25 UTC, atennapel commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ProcessedTasksCleanupAge** | This settings specifies (in milliseconds) how old completed processed tasks can be before they are removed from the database. By default this setting
Updated.

2021-11-22 10:29 UTC, hugomendix approved these changes

2021-11-22 11:52 UTC, MarkvanMents approved these changes
Proofread - looks good

2021-12-06 10:20 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ScheduledEventsCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ScheduledEventInformation table have to be before they are removed from the datab
Can we added the following note or alert to this?
> When turning on the cleanup after having used scheduled events for a long time, there might be many events to cleanup, which will done when the runtime server starts. This many cause additional database load, but will not block the startup. It is recommended not to do this during a busy period.

2021-12-06 10:21 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ProcessedTasksCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ProcessedQueueTask have to be before they are removed from the database. Only rows
Can we added the following note or alert to this?

>    When turning on the cleanup after having used many tasks over a long time period, there might be many processed tasks to cleanup, which will done when the runtime server starts. This many cause additional database load, but will not block the startup. It is recommended not to do this during a busy period.

2021-12-06 11:51 UTC, MarkvanMents requested changes
Hi @hugomendix 
Can you have a look at my suggestions. I feel that this is adding information to this table which could perhaps be explained in the documents which cover these two processes specifically.

I think it might be good to add this information there in any case, as customers might not look here for this information if they are implementing a task queue or scheduled event.

2021-12-06 11:51 UTC, MarkvanMents commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ScheduledEventsCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ScheduledEventInformation table have to be before they are removed from the datab
This seems a lot of information in this table.
Would it be better to add a section to https://docs.mendix.com/refguide/scheduled-events#5-additional-information which explains this setting more thoroughly and then link to that?

2021-12-06 11:51 UTC, MarkvanMents commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ProcessedTasksCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ProcessedQueueTask have to be before they are removed from the database. Only rows
This seems a lot of information in this table.
Would it be better to add a section to https://docs.mendix.com/refguide/task-queue#configuration which explains this setting more thoroughly and then link to that?

2021-12-06 13:36 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ScheduledEventsCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ScheduledEventInformation table have to be before they are removed from the datab
Yes, that sounds like a good idea. Still, we want to prevent having an angry customer, because he turned on this setting without reading the disclaimer.

2021-12-06 13:36 UTC, hugomendix commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ProcessedTasksCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ProcessedQueueTask have to be before they are removed from the database. Only rows
Yes, that sounds like a good idea. Still, we want to prevent having an angry customer, because he turned on this setting without reading the disclaimer.

2021-12-06 13:54 UTC, MarkvanMents commented on content/refguide/custom-settings.md
> +| **com.mendix.core.ProcessedTasksCleanupAge** | This setting specifies (in milliseconds) how old rows in the System.ProcessedQueueTask have to be before they are removed from the database. Only rows
Can you update the documents I referenced and add them to the PR? Then I can review them.
Thanks.

2021-12-08 08:39 UTC, atennapel commented
Closing in favour of: https://github.com/mendix/docs/pull/3948

2021-12-08 08:39 UTC, closed without merging