Release notes for Operator 2.2.0.
mendix/docs pull request #3930
Opened 2021-12-01 10:06 UTC by cstevandy

TBD release date, but the context is ready to be reviewed

2021-12-02 12:21 UTC, MarkvanMents requested changes
Hi Christian (@cstevandy )
I can't actually edit this pull request at all. It may be because you have made a PR from Dmitrii's fork and so GitHub won't allow me any access at all.
Can you look at the questions/comments below and see if you can commit the changes and respond to the other questions.
Otherwise, I may have to merge this into my own branch so that I can edit it.
Thanks for the PR.

2021-12-02 12:21 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +* We have fixed an issue where attempting to apply a custom TLS configuration in non-interactive mode with `mxpc-cli` failed with a panic error.
What do you mean by a 
> panic error

is this something that customers will recognize?

2021-12-02 12:21 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +* To improve the security score of all Mendix for Private Cloud images, we replaced a deprecated [operator-sdk v0.18.2](https://v0-18-x.sdk.operatorframework.io/docs/) dependency with a maintained ve
Have you checked with Frank about this discussion of security?

2021-12-02 12:21 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +  * This update allows us to address [CVE-2020-8565](https://access.redhat.com/security/cve/cve-2020-8565), [CVE-2020-26160](https://access.redhat.com/security/cve/cve-2020-26160) and [CVE-2020-29652
```suggestion
  * This update allows us to address [CVE-2020-8565](https://access.redhat.com/security/cve/cve-2020-8565), [CVE-2020-26160](https://access.redhat.com/security/cve/cve-2020-26160) and [CVE-2020-29652](https://access.redhat.com/security/cve/cve-2020-29652). These CVEs do not affect previously released versions of Mendix for Private Cloud.
```

2021-12-02 12:21 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +  * This is an internal library change and doesn't change the behavior of any Mendix for Private Cloud components.
```suggestion
  * This internal library change does not change the behavior of any Mendix for Private Cloud components.
```

2021-12-02 12:21 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +* When switching *Review and Apply* screen in `mxpc-cli`, previous results will be cleared.
Not sure I understand exactly what this is. Would
```suggestion
* When switching to the *Review and Apply* screen in `mxpc-cli`, previous results will be cleared.
```
cover it?

2021-12-06 09:19 UTC, zlogic commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +* We have fixed an issue where attempting to apply a custom TLS configuration in non-interactive mode with `mxpc-cli` failed with a panic error.
Yes, this was based on an error report from a customer (unfortunately there's no support ticket number that we can reference)

2021-12-06 09:41 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +* We have fixed an issue where attempting to apply a custom TLS configuration in non-interactive mode with `mxpc-cli` failed with a panic error.
OK, We can leave it there if customers are going to recognize it!

2021-12-06 09:42 UTC, MarkvanMents commented on content/releasenotes/developer-portal/mendix-for-private-cloud.md
> +* To improve the security score of all Mendix for Private Cloud images, we replaced a deprecated [operator-sdk v0.18.2](https://v0-18-x.sdk.operatorframework.io/docs/) dependency with a maintained ve
Approved by Frank by email.

2021-12-06 09:45 UTC, MarkvanMents approved these changes
Looks good.
I'll fix the dates when I publish it, so we don't have to worry about the editing issue.
I need to add something to our featured page anyway.
Let me know when you are ready to publish.
Mark

2021-12-06 11:27 UTC, zlogic commented
Thank you @MarkvanMents, can you publish these release notes now?

2021-12-06 11:36 UTC, merged