[UFC-403] Update documentation with adding platform selection in javascript actions
mendix/docs pull request #4007
Opened 2021-12-21 14:08 UTC by EnasAbdelrazek

2021-12-21 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=4007) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=4007) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=4007) it.</sub>

2021-12-22 09:02 UTC, Robinfr requested changes
Reviewed, needs a couple of changes.

2021-12-22 09:02 UTC, Robinfr commented on content/refguide/javascript-actions.md
> +To use a JavaScript action call from a nanoflow; then all actions in that nanoflow must be for the same platform.
```suggestion
When using a JavaScript action for a specific platform in a nanoflow, it will restrict the platform for that nanoflow. E.g. only native pages can be opened in a nanoflow that contains a JavaScript action where the platform is set to "Native".
```

2021-12-22 09:02 UTC, Robinfr commented on content/refguide/javascript-actions.md
> +All (default)
Suggest making this is a proper markdown list

2021-12-22 09:02 UTC, Robinfr commented on content/refguide/javascript-actions.md
> +To use a JavaScript action call from a nanoflow; then all actions in that nanoflow must be for the same platform.
Would add an empty line above this to make it easier to read.

2021-12-22 10:58 UTC, MarkvanMents commented
@EnasAbdelrazek 
Is this an immediate change, or does it need to wait for a future release?

2021-12-22 13:08 UTC, EnasAbdelrazek commented
It is needed for release 9.10.0

2021-12-22 15:04 UTC, Robinfr requested changes

2021-12-22 15:04 UTC, Robinfr commented on content/refguide/javascript-actions.md
> +{{% image_container width="400" %}}![javascript settings](attachments/javascript-actions/javascript-action-settings-with-platform.png){{% /image_container %}}
I think you forgot to update the reference?

2021-12-23 08:46 UTC, Robinfr approved these changes
Looks good from the technical perspective. Can be reviewed by technical writers 👍

2021-12-23 11:06 UTC, MarkvanMents approved these changes
Changes look good - approving.
@EnasAbdelrazek - have you signed the CLA? It makes it easier to check that the PR has passed all its checks. If you have, don't worry - GitHub sometimes fails to register it correctly.
![image](https://user-images.githubusercontent.com/35492184/147231890-f85b8c3d-c787-4b4c-a114-bc3b532d9978.png)

2022-01-25 09:49 UTC, merged