Replace Core.execute with Core.microflowCall
mendix/docs pull request #4008
Opened 2021-12-21 14:43 UTC by MarkvanMents

2021-12-21 14:50 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +```java
Replaced picture with code block.
Can you check that it is still OK Java!

2021-12-21 14:50 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +        Core.microflowCall(this.InitiatizationMicroflow) .inTransaction(true) .withParams(newObject) .execute(getContext());
This is the changed call. Can you proofread?
NB, I have passed `newObject` using `.withParams`. This isn't documented in [microflowCall](https://apidocs.rnd.mendix.com/9/runtime/com/mendix/core/Core.html#microflowCall(java.lang.String)) but does seem to be part of [MicroflowCallBuilder](https://apidocs.rnd.mendix.com/8/runtime/com/mendix/core/actionmanagement/MicroflowCallBuilder.html).
Is this correct (Java isn't my strong suit).

2021-12-21 14:50 UTC, MarkvanMents commented on content/howto/logic-business-rules/java-api-tutorial.md
> +	String formattedString = (String) Core.microflowCall ("MyFirstModule.FormatString") .inTransaction(true) .withParam("inputString", inputString) .execute(context);
Can you confirm this is correct Java!

2021-12-21 15:04 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +        Core.microflowCall(this.InitiatizationMicroflow) .inTransaction(true) .withParams(newObject) .execute(getContext());
If there is one parameter, like in this case, you can use [withParam](https://apidocs.rnd.mendix.com/9/runtime/com/mendix/core/actionmanagement/MicroflowCallBuilder.html#withParam(java.lang.String,java.lang.Object)). `withParam` takes two arguments, the name of the microflow parameter and its value. You are missing the name here.
Also it is convention to put the MicroflowBuilder fluent API calls (inTransaction, withParams) below each other, aligned on the dot.

2021-12-21 15:13 UTC, reinouts commented on content/howto/logic-business-rules/java-api-tutorial.md
> +	String formattedString = (String) Core.microflowCall ("MyFirstModule.FormatString") .inTransaction(true) .withParam("inputString", inputString) .execute(context);
It may be correct Java but the canonical way to invoke a microflow of which you know the name, is to use its proxy.
This will prevent runtime errors should the microflow name ever change.
In this case that would be `myfirstmodule.proxies.microflows.formatString(getContext(), inputString);`
To make this a bit less verbose you could add an `import` statement on top like this:
`import static myfirstmodule.proxies.microflows.formatString;` and then in the `executeAction()` method you would simply write `return formatString(getContext(), inputString);`. 
In either case you can remove the `Map<String,Object> parameters` declaration as you don't use it any more.

2021-12-21 16:06 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +            Map<String, ? extends IMendixObjectMember<?>> members = DefaultObject.getMembers(getContext());
Can be simplified:
```java
var members = DefaultObject.getMembers(getContext());
```

2021-12-21 16:07 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +                IMendixObjectMember<?> m = members.get(key);
Can be simplified:
```java
var m = members.get(key);
```

2021-12-21 21:46 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +    ArrayList<IMendixObject> resultList = new ArrayList<IMendixObject>();
Use an interface rather than a specific List implementation:
`List<IMendixObject> resultList = new ArrayList<>();`

2021-12-22 10:39 UTC, MarkvanMents commented
Hi @reinouts 
Thanks for all the input.
Hugo is out today, but he is also going to review this tomorrow. I'll pick up your suggestions after he has had a look.

2022-01-04 10:40 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +    ArrayList<IMendixObject> resultList = new ArrayList<IMendixObject>();
@reinouts - all I have done here is to pick up the original implementation and change the Core.execute() call.

Can someone from runtime look at this code and perhaps rewrite it completely if it needs bringing up to date.

2022-01-04 10:40 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +            Map<String, ? extends IMendixObjectMember<?>> members = DefaultObject.getMembers(getContext());
See comment above - wasn't planning a complete rewrite, but perhaps it needs it.

2022-01-04 10:40 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +                IMendixObjectMember<?> m = members.get(key);
See comment above - wasn't planning a complete rewrite, but perhaps it needs it.

2022-01-04 10:40 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +        Core.microflowCall(this.InitiatizationMicroflow) .inTransaction(true) .withParams(newObject) .execute(getContext());
But my understanding is that `newObject` isn't a single parameter but a list of key/value pairs. According to [MicroflowCallBuilder](https://apidocs.rnd.mendix.com/9/runtime/com/mendix/core/actionmanagement/MicroflowCallBuilder.html) it looks like I should be able to pass this using `withParams` - `withParam` would also need a name.

But I'm not a Java developer, so perhaps I am misreading the script?

2022-01-04 10:40 UTC, MarkvanMents commented on content/howto/logic-business-rules/java-api-tutorial.md
> +	String formattedString = (String) Core.microflowCall ("MyFirstModule.FormatString") .inTransaction(true) .withParam("inputString", inputString) .execute(context);
Thanks for the input @reinouts.
As a technical writer, I was trying to resolve this the simplest way possible, since someone had already written the Java code. However, if this example needs completely rewriting to bring it up to date I can do that as you suggest.

2022-01-04 16:40 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +            Map<String, ? extends IMendixObjectMember<?>> members = DefaultObject.getMembers(getContext());
Java rewritten - comment is now outdated.

2022-01-04 16:41 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +    ArrayList<IMendixObject> resultList = new ArrayList<IMendixObject>();
Java rewritten - comment is now outdated.

2022-01-04 16:42 UTC, MarkvanMents commented on content/howto/logic-business-rules/java-api-tutorial.md
> +	String formattedString = (String) Core.microflowCall ("MyFirstModule.FormatString") .inTransaction(true) .withParam("inputString", inputString) .execute(context);
@reinouts 
I'm a bit confused as to exactly what the Java snippet will look like after I've made the changes you suggest.
Can you perhaps let me have what you think the whole snippet should be, then I can update the document accordingly.
Slack is fine if that is easier than posting it here.
Thanks.

2022-01-04 20:35 UTC, reinouts requested changes

2022-01-04 20:35 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +          .execute(this.getContext());
`this.` is unnecessary, just `getContext()` will do.

2022-01-04 20:35 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +    logger.info(String.format("creating list of %d %s objects, initialized by %s",
For this example to compile, you should declare a `logger` first with something like `Core.getLogger("MyLogNode");`

2022-01-04 20:35 UTC, reinouts commented on content/howto/logic-business-rules/java-api-tutorial.md
> +	String formattedString = (String) Core.microflowCall ("MyFirstModule.FormatString") .inTransaction(true) .withParam("inputString", inputString) .execute(context);
You would first add the following import statement on top of the class:
`import static myfirstmodule.proxies.microflows.Microflows.formatString;`
then, this `formatString()` helper method is completely redundant and can be removed. 
You can now directly invoke `formatString(getContext(), "this is an unformatted string")` (note the order of the parameters) in the code example at the bottom of paragraph 2. This will execute the FormatString microflow.

2022-01-05 08:39 UTC, reinouts commented on content/howto/extensibility/howto-connector-kit.md
> +    logger.info(String.format("creating list of %d %s objects, initialized by %s",
Sorry, I should have been more explicit: the declaration is:
`var logger = Core.getLogger("MyLogNode");`

2022-01-05 08:42 UTC, reinouts commented on content/howto/logic-business-rules/java-api-tutorial.md
> +import static myfirstmodule.proxies.microflows.Microflows.formatString;
Important to note here that the `import`  statement should be **on top of** the class, you cannot put it right before the `formatString()` invocation.

2022-01-05 08:44 UTC, reinouts commented on content/howto/logic-business-rules/java-api-tutorial.md
> +import static myfirstmodule.proxies.microflows.Microflows.formatString;
See [other comment](https://github.com/mendix/docs/pull/4008/files#r778635626).

2022-01-05 10:33 UTC, MarkvanMents commented on content/howto/logic-business-rules/java-api-tutorial.md
> +import static myfirstmodule.proxies.microflows.Microflows.formatString;
Added more context - hopefully the import is now in the right place and clear to the reader.

2022-01-05 10:37 UTC, MarkvanMents commented on content/howto/extensibility/howto-connector-kit.md
> +    logger.info(String.format("creating list of %d %s objects, initialized by %s",
You have to realize that my Java ability is read-only and be very explicit if I need to actually write something!
Corrected in https://github.com/mendix/docs/pull/4008/commits/2123e383127218d850c9089bf6da0d406737fe33

2022-01-05 10:40 UTC, reinouts approved these changes
LGTM.

2022-01-05 13:17 UTC, merged