Missing steps
mendix/docs pull request #4019
Opened 2021-12-23 09:37 UTC by ChrisdeG

Please revise this document from a clean computer while many small steps are missing. I added a few.

2021-12-30 12:15 UTC, smarki requested changes

2021-12-30 12:15 UTC, smarki commented on content/howto/mobile/native-build-locally.md
> +If no device is available use **AVD Manager** to add a device.
it used to be that "running" would pop to add a device. Apparently now Android Studio will fail with a random error.
Here's the screenshot to be added
![image](https://user-images.githubusercontent.com/4354327/147750260-6e19e22b-76fc-49e9-8439-dd760e1289a7.png)

2021-12-30 12:15 UTC, smarki commented on content/howto/mobile/native-build-locally.md
> +accept the licenses with **sdkmanager --licenses** after installing in the bin directory
I would expect installing Android Studio and following the wizard would install everything correctly

2022-01-05 14:07 UTC, ConnorLand commented on content/howto/mobile/native-build-locally.md
>  * Install [Android SDK](https://developer.android.com/studio) and [platform tools](https://developer.android.com/studio/releases/platform-tools)
I have made this change.

2022-01-05 14:08 UTC, ConnorLand commented on content/howto/mobile/native-build-locally.md
> +accept the licenses with **sdkmanager --licenses** after installing in the bin directory
Made the change, noted it in the comment below this one.

2022-01-05 14:10 UTC, ConnorLand commented on content/howto/mobile/native-build-locally.md
> +   Mendix native mobile apps make use of **Build Variants** to build a release app or a custom developer app. The idea of **Build Variants** is a Gradle build system concept for sharing the same code
We may have collapsible content options in the future stack. For now I am keeping the information as regular text without a screenshot, as it seems fairly clear.

2022-01-05 14:11 UTC, ConnorLand commented on content/howto/mobile/native-build-locally.md
> +If no device is available use **AVD Manager** to add a device.
Thank you, I will add the screenshot.

2022-01-05 14:24 UTC, ConnorLand commented on content/howto/mobile/native-build-locally.md
> +* Install [Android Studio](https://developer.android.com/studio) and [platform tools](https://developer.android.com/studio/releases/platform-tools), taking care to complete the wizard in Android Stud
Does this look good now @stmarkidis ?

2022-01-05 14:27 UTC, smarki commented on content/howto/mobile/native-build-locally.md
> +* Install [Android Studio](https://developer.android.com/studio) and [platform tools](https://developer.android.com/studio/releases/platform-tools), taking care to complete the wizard in Android Stud
licenses in this instance, need to be accepted not installed, more like TOS for the SDKs that are installed as part of the wizard.

2022-01-05 14:35 UTC, ConnorLand approved these changes

2022-01-05 14:36 UTC, ConnorLand commented
Thank you for sharing your clean computer experiences @ChrisdeG !

2022-01-05 14:36 UTC, merged