[NC-19] add native radio buttons
mendix/docs pull request #4022
Opened 2021-12-23 10:55 UTC by Ahmad-Elsayed

2021-12-23 10:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=4022) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=4022) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=4022) it.</sub>

2021-12-23 14:55 UTC, Ahmad-Elsayed commented
Work in progress, yet to be released.

2021-12-24 12:32 UTC, jordanch requested changes

2021-12-24 12:32 UTC, jordanch commented on content/refguide/native-styling-refguide.md
> +		<radioButtonItemContainerDisabledStyle>
This doesn't seem right to me when compared to the [Atlas changes](https://github.com/mendix/widgets-resources/blob/nc/radio-buttons/packages/pluggableWidgets/radio-buttons-native/src/ui/Styles.ts#L4) also when compared to below, where all the data cells in Element column represent "top-level" properties in the styling object

2021-12-28 09:53 UTC, jordanch requested changes

2021-12-28 09:53 UTC, jordanch commented on content/refguide/native-styling-refguide.md
> +			<circularBtnDisabledStyle/>
Does `circularButtonStyle` contain `circularBtnDisabledStyle`? Based on the information below in the table, this isn't the case; everything's top-level. Which is correct?

2021-12-29 10:24 UTC, Ahmad-Elsayed commented on content/refguide/native-styling-refguide.md
> +			<circularBtnDisabledStyle/>
updated

2021-12-31 14:01 UTC, jordanch commented
Looks good to me :)

2022-02-23 15:43 UTC, ConnorLand approved these changes

2022-03-24 12:40 UTC, ConnorLand reviewed
We'll rebase before merge in order to solve conflicts. If conflicts are still there, I'll implement the changes in manually myself.

2022-04-06 12:12 UTC, closed without merging