Service Authentication Best Practice
mendix/docs pull request #4060
Opened 2022-01-12 10:39 UTC by MarkvanMents

2022-01-31 10:49 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +First, you need to answer the question **Requires authentication** with *Yes* or *No*.
```suggestion
Rewrote line 80-88

First, you need to answer the question **Requires authentication** with *Yes* or *No*.

Generally the platform guides you towards choosing *Yes* for the API endpoints you create. 
Intuitively this seems correct, as when the *Yes* option is toggled on. Mendix Studio Pro will reveal a variety of authentication options.
And these options will restrict which users or external systems have access to your API endpoint.
From a security perspective this is exactly what we want.

However choosing between *Yes* and *No* is not this straight forward.
Choosing *Yes* will force your API requests to be executed in the context of a user account and requires an active session to be established. 
Not having to establish the user account and it's related session can have a significant performance impact for your API.
This is why *No* can still be a viable for your API, and it might even be the recommended option in general.

The best practices when selecting *No* as the requires authentication option are:
- Provide the HTTP Response as a parameter to the microflow used as the API handler.
- Extract any required header information from the HTTP Request, this could be an "X-API-Key" header or "Authorization" header.
- Perform your own validations on this header information at the very start of the API handling microflow.
- Abort execution of the rest of the API handling microflow when validations fail.
- Directly manipulate the status code and response in the HTTP response entity that was provided as a parameter,
- Use this in combination with IP restrictions and certificates, creating a secure bubble of trusted requesting users and systems.

{{% alert type="warning" %}}
Choosing *No* without these restrictions will allow anyone on the internet to make requests to your API endpoint at any time and at any rate, which can seriously affect your app's response and even cause server failure.
{{% /alert %}}

Choosing *Yes* comes with the benefits of having the timezone and language settings available for that API user account.

```

2022-01-31 10:50 UTC, Marnix-IxD requested changes
I added a suggested changes for line 80-88 subsection 5.1

2022-01-31 11:12 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +First, you need to answer the question **Requires authentication** with *Yes* or *No*.
```suggestion
First, you need to answer the question **Requires authentication** with *Yes* or *No*.

Generally the platform guides you towards choosing *Yes* for the API endpoints you create. 
Intuitively this seems correct, as when the *Yes* option is toggled on. Mendix Studio Pro will reveal a variety of authentication options.
And these options will restrict which users or external systems have access to your API endpoint.
From a security perspective this is exactly what we want.

However choosing between *Yes* and *No* is not this straight forward.
Choosing *Yes* will force your API requests to be executed in the context of a user account and requires an active session to be established. 
Not having to lookup the user account and creating a session can have a significant performance impact for your API.
This is why *No* can still be a viable for your API, and it might even be the recommended option in general.

The best practices when selecting *No* as **Requires authentication** option are:
- Provide the HTTP Response as a parameter to the microflow used as the API handler.
- Extract any required header information from the HTTP Request, this could for example be an "X-API-Key" header or "Authorization" header.
- Perform your own validations on this header information at the very start of the API handling microflow.
- Abort execution of the rest of the API handling microflow when validations fail.
- Directly manipulate the status code and response in the HTTP response entity that was provided as a parameter,
- Use this in combination with IP restrictions and certificates, creating a secure bubble of trusted requesting users and systems.

By performing your authentication checks this way, you will have the flexibility of the Custom authentication option described in section 5.2.3, but it comes with the most minimal performance hit. At the expense of losing the user context, which in most scenario's is acceptable for API's.

{{% alert type="warning" %}}
Choosing *No* without these restrictions will allow anyone on the internet to make requests to your API endpoint at any time and at any rate, which can seriously affect your app's response and even cause server failure.
{{% /alert %}}

Choosing *Yes* comes with the benefits of having the timezone and language settings available for that API user account. And can also be used for better traceability of changes made through API requests. And also gives the possibility to apply restrictions to requested entities based on the System.User used for the API account.

```

2022-01-31 11:12 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +It is highly recommended to set this to *Yes* for any endpoint you create. This will restrict which users or external systems have access to your API endpoint, and when.
```suggestion
It is highly recommended to set this to *Yes* for any endpoint you create. This will restrict which users or external systems have access to your API endpoint, and when.

```

2022-01-31 12:27 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +It is highly recommended to set this to *Yes* for any endpoint you create. This will restrict which users or external systems have access to your API endpoint, and when.
```suggestion
It is highly recommended to set this to *Yes* for any endpoint you create. This will restrict which users or external systems have access to your API endpoint, and when.
Delete this
```

2022-01-31 12:28 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +*No* is only a viable choice when it is used in combination with IP restrictions and certificates, creating a secure bubble of trusted requesting users and systems.
```suggestion
```

2022-01-31 12:28 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +{{% alert type="warning" %}}
```suggestion
```

2022-01-31 12:29 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +Choosing *No* without these restrictions will allow anyone on the internet to make requests to your API endpoint at any time and at any rate, which can seriously affect your app's response and even c
```suggestion
```

2022-01-31 12:29 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +{{% /alert %}}
```suggestion
```

2022-01-31 14:04 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +This is why choosing *No* can still be a viable for your API, and it might even be the recommended option in general.
```suggestion
This is why choosing *No* can still be viable for your API, and it might even be the recommended option in general.

```

2022-01-31 14:08 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +This means that the same advice around certificate usage and IP restrictions applies.
```suggestion
This means that the same advice around certificate usage and IP restrictions applies and performing the authentication inside the API handling microflow itself.
```

2022-01-31 14:11 UTC, Marnix-IxD requested changes
Made some minor adjustments, remove an "a" and added a sentence for backreferencing the same information in 5.1

2022-01-31 14:16 UTC, MarkvanMents reviewed
Hi Marnix,
I've made a couple of proofreading suggestions, but the content looks great.

Let me know if you have any more suggestions.

Should we get a positive signoff from someone else before publishing?

Thanks

2022-01-31 14:16 UTC, MarkvanMents commented on content/howto/security/best-practices-security.md
> +This is why choosing *No* can still be a viable for your API, and it might even be the recommended option in general.
Made another suggestion, above.

2022-01-31 14:18 UTC, MarkvanMents commented on content/howto/security/best-practices-security.md
> +This means that the same advice around certificate usage and IP restrictions applies.
Updated suggestion

2022-01-31 14:20 UTC, Marnix-IxD commented
> 

I'm expecting one more person to give his stamp of approval before we can publish. I'm happy with the changes you've made. And feel the documentation is much more complete this way on this subject.

2022-01-31 14:44 UTC, MarkvanMents commented
Great - I'll wait for the final reviewer to approve.
Thanks.

2022-02-01 07:57 UTC, rik-bos commented on content/howto/security/best-practices-security.md
> +- Extract any required header information from the HTTP Request – this could, for example, be an "X-API-Key" header or "Authorization" header
The recommendation is to also add this header explicitly as input parameter to the MF so it will appear in the swagger docs hosted at `rest-doc`. This will ensure that the try it functionality is not broken.

2022-02-01 07:57 UTC, rik-bos commented on content/howto/security/best-practices-security.md
> +- Manipulate the status code and response directly in the HTTP response object that was provided as a parameter
(I'd explicitly add 401 (unauthorized, i.e. not authenticated properly) and 403 (forbidden, i.e. authenticated, but no access to this resource / endpoint) here.

2022-02-01 07:57 UTC, rik-bos commented on content/howto/security/best-practices-security.md
> +- Use the option in combination with IP restrictions and certificates, creating a secure bubble of trusted requesting users and systems
I don't agree with this recommendation in this location. This is not more or less imporant than when Mx handles the authentication at REST level. So If we want to mak ethis recommendation, I'd move it to a higher level.

2022-02-01 08:03 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +- Extract any required header information from the HTTP Request – this could, for example, be an "X-API-Key" header or "Authorization" header
great addition indeed

2022-02-01 08:19 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +- Manipulate the status code and response directly in the HTTP response object that was provided as a parameter
Agree, this could be explicitly mentioned.

2022-02-01 09:52 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +- Extract any required header information from the HTTP Request – this could, for example, be an "X-API-Key" header or "Authorization" header
```suggestion
- Extract any required header information from the HTTP Request – this could, for example, be an "X-API-Key" header or "Authorization" header
- Configure required headers for authentication as part of a published REST operation, and add it explicitly to the API handling microflow as an input parameter. This could, for example, be an "X-API-Key" header or "Authorization" header. By adding the header as an input parameter it will be included in the generated swagger documentation hosted at `/rest-doc`. Here it can be manually set as a parameter and used as part of the "try it out" feature for that API operation.
```

2022-02-01 09:58 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +- Manipulate the status code and response directly in the HTTP response object that was provided as a parameter
```suggestion
- Manipulate the status code and response directly in the HTTP response object that was provided as a parameter. Returning a `401 Unauthorized`  in the cases where authentication failed, and `403 Forbidden` in cases where the authentication was successful, however the provided information doesn't grant access to the requested resource or isn't allowed to execute the rest of that API operation's logic.
```

2022-02-01 10:09 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +
```suggestion

#### 5.3 Limiting API access through IP restrictions and certificates
Additional API security measures could be implemented through the use of [IP restrictions and / or certificates](/developerportal/deploy/access-restrictions) , creating a secure bubble of trusted requesting users and systems.
```

2022-02-01 10:11 UTC, Marnix-IxD commented on content/howto/security/best-practices-security.md
> +- Use the option in combination with IP restrictions and certificates, creating a secure bubble of trusted requesting users and systems
I moved it towards a sub-chapter 5.3

2022-02-01 14:00 UTC, Marnix-IxD approved these changes
Couldn't spot any further changes. Happy with the current document.

2022-02-01 14:26 UTC, merged