[MOO-494] Add docs for dangling references
mendix/docs pull request #4068
Opened 2022-01-13 20:34 UTC by govorov

2022-01-14 11:13 UTC, smarki requested changes

2022-01-14 11:13 UTC, smarki commented on content/refguide/offline-first.md
> +4. All the changed and new objects are sent to the server, and the content of the files is linked to the objects. The server performs referential integrity validation of the objects (see the [Danglin
I miss the significance of why a single network request is used. I am not sure we want to go into detail, but without extra info it's not helpful to a reader?

2022-01-14 11:13 UTC, smarki commented on content/refguide/offline-first.md
> +3. If there are any changed or new file objects, their content is uploaded to the server and stored there temporarily. Each file is uploaded in a separate network request.
Same as below; I am not sure why the separate network request is usefull if left unexplained in this context.

2022-01-14 11:13 UTC, smarki commented on content/refguide/offline-first.md
> +For example, when a committed `City` object refers to an uncommitted `Country` object, synchronizing the `City` object alone will yield an invalid `Country` object reference, which is a dangling refe
Maybe simplify the language more. Does commit has the meaning we thing for a user?
In offline context, commit means saving to the database, do we actually verify danglin references then? 

Is commit the right verb to describe the operation of sync and saving to the database?

2022-01-14 11:13 UTC, smarki commented on content/refguide/offline-first.md
> +A dangling reference error is a modeling error.
These deserve their own sections. Could we split dangling references and how to avoid them to their own page?

2022-01-14 11:14 UTC, smarki commented on content/refguide/offline-first.md
> +A dangling reference error is a modeling error.
Maybe a database integrity section or something

2022-01-14 14:48 UTC, govorov commented
Add info blocks mentioning that deletes are not supported in mx < 9.7.

2022-01-14 20:04 UTC, govorov commented on content/refguide/offline-first.md
> +For example, when a committed `City` object refers to an uncommitted `Country` object, synchronizing the `City` object alone will yield an invalid `Country` object reference, which is a dangling refe
> do we actually verify danglin references then?

The validation happens upon sync only. The wording here is a bit misleading, good point.

> Is commit the right verb to describe the operation of sync and saving to the database?

We call it "commit" everywhere in the docs, there's a nanoflow activity called "Commit", etc. 
That's the wording we use. The concept of committing an object is known to those who read the docs. 
We also explicitly mention that sync works at the database level.

2022-01-14 20:11 UTC, govorov commented on content/refguide/offline-first.md
> +4. All the changed and new objects are sent to the server, and the content of the files is linked to the objects. The server performs referential integrity validation of the objects (see the [Danglin
A single network request implies that the operation is kind of atomic.
There's also a difference between upload and download, where for the latter we use one request per entity.

I do feel we can elaborate more on the differences between single/multiple requests, but I don't really know where to draw the line to be honest.

2022-01-15 07:52 UTC, ekrem-aktas requested changes

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +For example, when a committed `City` object refers to an uncommitted `Country` object, synchronizing the `City` object alone will yield an invalid `Country` object reference, which is a dangling refe
"Commit" is the correct word to use indeed: intended as "saving to the offline db" and here specifies the state of the objects. Dangling reference check does not happen at commit time, but when the committed object is synchronised.

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +To prevent them from happening during selective synchronization make sure you either select both sides of the association for the synchronization
The suggestion of selecting both objects wouldn't work because `Country` is stated as uncommitted above.

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +This breaks referential integrity of the object because it references a non-existing object in the runtime database.
```suggestion
This breaks referential integrity of the object because it references an object that only exists on the device database.
```

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +1. As the local database can be modified only by committing or deleting an object, such an object can be either a new object created while offline, or an existing object previously synced from the se
> all committed objects from the list of selected objects are checked.

This is a leftover from dangling reference description: we don't "check" anything anymore. But we can say "included" to mention which objects are selected for synchronization. 

We also don't seem to mention "Synchronize unsynced objects" mode.

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +3. If there are any changed or new file objects, their content is uploaded to the server and stored there temporarily. Each file is uploaded in a separate network request.
We can continue with: "If upload of a file fails, the whole synchronization is aborted without causing any changes in both the server and local database.

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +5. Any configured before- or after-commit or before- or after-delete event handlers on these objects will run on the server as usual: after the data has been uploaded and before it is downloaded.
* We also execute create event handlers for new objects.
* "... and before local database is updated. This means any further changes you make to the synchronised objects in the event handlers will be updated in the local database in the download phase"

There's one exception to the description above - changing the contents of a file entities aren't reflected back. Maybe important to mention.

2022-01-15 07:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +A dangling reference error is a modeling error.
+1 for a separate section, but we have more stuff to put under such a section. That's why I'd do it in a separate story.

2022-01-17 11:58 UTC, smarki commented on content/refguide/offline-first.md
> +4. All the changed and new objects are sent to the server, and the content of the files is linked to the objects. The server performs referential integrity validation of the objects (see the [Danglin
Exactly that is my point. We know that; will a customer understand that?

2022-01-17 12:00 UTC, smarki commented on content/refguide/offline-first.md
> +4. All the changed and new objects are sent to the server, and the content of the files is linked to the objects. The server performs referential integrity validation of the objects (see the [Danglin
I think a more explanatory sentence; like the operation happens in one request and that's the reason why, similar to Ekrem's suggestion is aggreable with me.

2022-01-17 13:29 UTC, govorov commented on content/refguide/offline-first.md
> +3. If there are any changed or new file objects, their content is uploaded to the server and stored there temporarily. Each file is uploaded in a separate network request.
✔️

2022-01-17 13:37 UTC, govorov commented on content/refguide/offline-first.md
> +The synchronization process consists of two phases. In the [upload phase](#upload), your app updates the server database with the new or changed objects that are committed. In the [download phase](#d
✔️

2022-01-17 13:55 UTC, govorov commented on content/refguide/offline-first.md
> +To prevent them from happening during selective synchronization make sure you either select both sides of the association for the synchronization
Good point. Fixed ✔️

2022-01-17 14:02 UTC, govorov commented on content/refguide/offline-first.md
> +This breaks referential integrity of the object because it references a non-existing object in the runtime database.
This text is exactly what the runtime logs in the console. Do you suggest to change it there as well? The existing version is fine with me, as it's the message shown by the runtime, so "non-existing" is not ambiguous in this case.

2022-01-17 16:13 UTC, govorov commented on content/refguide/offline-first.md
> +1. As the local database can be modified only by committing or deleting an object, such an object can be either a new object created while offline, or an existing object previously synced from the se
It's not about dangling in any way, it's about selecting what data to synchronize indeed. If you find "checked" controversial, we can replace it with "selected for synchronization" for instance.

2022-01-17 16:16 UTC, govorov commented on content/refguide/offline-first.md
> +1. As the local database can be modified only by committing or deleting an object, such an object can be either a new object created while offline, or an existing object previously synced from the se
"Check" here means "scan the db and pick what needs to be synced". "Checked" and "included" for sync are not the same sets: an object can be "checked" (entire database in case of full sync) but not "included" (as we include only dirty) for sync.

Alternalively, we can say something like "for full sync all ditry objects are included". What do you think?

2022-01-17 17:15 UTC, govorov commented on content/refguide/offline-first.md
> +5. Any configured before- or after-commit or before- or after-delete event handlers on these objects will run on the server as usual: after the data has been uploaded and before it is downloaded.
Nice catch Ekrem 👍 Added.

2022-01-19 12:52 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +This breaks referential integrity of the object because it references a non-existing object in the runtime database.
Yes, I'd also change it on the logs as well - but noticed that my version needs adjustment - we need the drop "database" from it because a dangling object can be a new one that has not yet been committed to the offline database.

2022-01-19 12:54 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +1. As the local database can be modified only by committing or deleting an object, such an object can be either a new object created while offline, or an existing object previously synced from the se
Indeed I misunderstood the usage of the check here - with your explanation is makes sense. I'd keep it as-is.

2022-01-19 13:02 UTC, ekrem-aktas requested changes

2022-01-19 13:02 UTC, ekrem-aktas commented on content/refguide/offline-first.md
> +This validation ensures that none of the synchronized objects have associations pointing to an object that exists only in the device database.
I think we should drop "database" from the end of the sentence.

2022-01-20 12:49 UTC, govorov commented on content/refguide/offline-first.md
> +This validation ensures that none of the synchronized objects have associations pointing to an object that exists only in the device database.
✔️

2022-01-20 12:52 UTC, govorov commented on content/refguide/offline-first.md
> +This breaks referential integrity of the object because it references a non-existing object in the runtime database.
Let's do this as a separate change set after we change the message in the runtime then. Created a small story.

2022-01-24 14:54 UTC, ConnorLand commented
@stmarkidis have changes been made to your satisfaction?

2022-01-24 14:58 UTC, smarki approved these changes

2022-01-24 15:00 UTC, ConnorLand approved these changes

2022-01-25 09:20 UTC, merged