Workflows Changes in 9.10
mendix/docs pull request #4092
Opened 2022-01-19 15:46 UTC by MariaShaposhnikova

2022-01-20 15:54 UTC, MariaShaposhnikova commented on content/refguide/workflows.md
> +{{% todo %}}[Is information in this section still relevant?]{{% /todo %}}
Is information up-to-date in this section?

2022-01-20 15:54 UTC, MariaShaposhnikova commented on content/refguide/workflows.md
> +{{% todo %}}[Is information in this section still relevant?]{{% /todo %}}
Is information up-to-date in this section?

2022-01-20 15:54 UTC, MariaShaposhnikova commented on content/refguide/workflow-setting-up-app.md
> +{{% todo %}}[Is information in this section still relevant?]{{% /todo %}}
Is information up-to-date in this section?

2022-01-21 16:11 UTC, JefHellemansMendix requested changes

2022-01-21 16:11 UTC, JefHellemansMendix commented on content/refguide/workflows.md
> +{{% todo %}}[Is information in this section still relevant?]{{% /todo %}}
**WorkflowTaskDefinition** has become **WorkflowUserTaskDefinition**, and no longer includes system activities. **Obsolete** is also called **IsObsolete**.

2022-01-21 16:11 UTC, JefHellemansMendix commented on content/refguide/workflows.md
> +{{% todo %}}[Is information in this section still relevant?]{{% /todo %}}
Yes, this is correct.

2022-01-24 08:19 UTC, MariaShaposhnikova commented on content/studio/workflows.md
> +Workflows in Studio are temporarily unavailable for apps with Mendix version 9.6 and above. We introduced workflows as a Beta feature in Mendix 9 and are now incorporating feedback we received from o
@JefHellemansMendix , do you mean that workflows will be re-enabled for Studio in 9.10?

2022-01-24 08:25 UTC, JefHellemansMendix commented on content/studio/workflows.md
> +Workflows in Studio are temporarily unavailable for apps with Mendix version 9.6 and above. We introduced workflows as a Beta feature in Mendix 9 and are now incorporating feedback we received from o
Yes, although it might not make it on time for release day.

2022-01-24 08:54 UTC, MariaShaposhnikova commented on content/refguide/workflows.md
> +{{% todo %}}[Is information in this section still relevant?]{{% /todo %}}
Updated.

2022-01-25 09:22 UTC, merged