Studio Pro 9.11 introduces updatable microflow
mendix/docs pull request #4119
Opened 2022-01-27 13:36 UTC by joostverhoog

2022-01-27 15:41 UTC, osoykan requested changes

2022-01-27 15:41 UTC, osoykan commented on content/refguide/published-odata-resource.md
> +1. It checks that the request is formatted correcly, rejecting things like specifying a string value for an integer attribute.
`correcly` -> `correctly`

2022-01-27 15:42 UTC, osoykan commented on content/refguide/published-odata-resource.md
> +1. It checks that the request is formatted correcly, rejecting things like specifying a string value for an integer attribute.
Fixed it.

2022-01-27 15:43 UTC, osoykan approved these changes

2022-02-07 05:55 UTC, Adam-Dupaski commented
@johannahemminger please do a language review here and see if you can identify why the PR build is failing

2022-02-07 08:49 UTC, Adam-Dupaski commented on content/refguide/published-odata-resource.md
> +Use the checkbox for **Updatable (write)** to indicate that clients can update the values of attributes and associations.
@johannahemminger please reference SG for "checkbox"

2022-02-07 08:49 UTC, Adam-Dupaski commented on content/refguide/published-odata-resource.md
> +The action **Call a microflow** allows you to replace the third step (committing the changes to the database) with your own logic. Specify a microflow that takes the entity as a parameter, and option
@johannahemminger can you cross-reference the doc for "Call a microflow"?

2022-02-07 08:51 UTC, Adam-Dupaski commented on content/refguide/published-odata-resource.md
> +The action **Call a microflow** allows you to replace the third step (committing the changes to the database) with your own logic. Specify a microflow that takes the entity as a parameter, and option
@johannahemminger cross-reference link text for "Commit activity" should be reviewed - is that the exact name of the activity, and do we include "activity" in the link text?

2022-02-07 08:51 UTC, Adam-Dupaski commented on content/refguide/published-odata-resource.md
> +This *Call a microflow* action was introduced in Studio Pro [9.11.0](/releasenotes/studio-pro/9.11).
@johannahemminger is italics the best formatting choice for the activity name, and should it be called an "action" or "activity"?

2022-02-07 12:00 UTC, Adam-Dupaski commented on content/refguide/published-odata-resource.md
> +The action [Call a microflow](/refguide/on-click-event#call-microflow) allows you to replace the third step (committing the changes to the database) with your own logic. Specify a microflow that take
@johannahemminger are you sure that's the correct cross-reference - that goes to a section describing UI that already exists, but this is not supposed to come out till 9.11? Is supposed to be an on-click event or related to the Microflow call activity? Also, you call it an "action" in line 121, but in line 124 it's called an activity - consistency needed here.

2022-02-08 14:31 UTC, johannahemminger commented on content/refguide/published-odata-resource.md
> +The action [Call a microflow](/refguide/on-click-event#call-microflow) allows you to replace the third step (committing the changes to the database) with your own logic. Specify a microflow that take
@Adam-Dupaski should it link back to the RN here? And if not, how can I see other docs that are being looked over for the upcoming release? For the second point action is for the "Call the Microflow" as it is an Action in the UI, while activity describes what is executed in the microflow.

2022-02-08 14:38 UTC, Adam-Dupaski commented on content/refguide/published-odata-resource.md
> +The action [Call a microflow](/refguide/on-click-event#call-microflow) allows you to replace the third step (committing the changes to the database) with your own logic. Specify a microflow that take
@johannahemminger it doesn't need to link to the RN here, but you probably need to determine if additional documentation is necessary for this. Is that the correct section for the cross-reference? Or is something additionally new necessary? Since this is your component, these would be questions for you to ask and verify with the dev. Otherwise, you can see the PRs being worked on for 9.11 for doc changes, and ask anyone else on the team who may be working on this (but since this is your component, probably not necessary).

2022-02-10 15:54 UTC, johannahemminger commented on content/refguide/published-odata-resource.md
> +The action [Call a microflow](/refguide/on-click-event#call-microflow) allows you to replace the third step (committing the changes to the database) with your own logic. Specify a microflow that take
Clarified with Joost, the new thing is the option in a particular pane in Studio Pro. Calling a microflow is an action that can be selected instead of the default behavior. I'm updating the doc accordingly

2022-02-21 15:11 UTC, Adam-Dupaski approved these changes

2022-02-23 15:16 UTC, merged