Marketplace scan report
mendix/docs pull request #4210
Opened 2022-02-21 09:53 UTC by Adam-Dupaski

2022-02-21 09:57 UTC, Adam-Dupaski commented
@KseniiaIankina please take a look and leave comments if necessary

2022-02-22 10:06 UTC, KseniiaIankina requested changes
Thank you Adam for preparing this documentation piece ! Could you please correct one typo and then it is approved.

2022-02-22 10:06 UTC, KseniiaIankina commented on content/appstore/general/share-app-store-content.md
> +If the virus scan report is invalid or there is some issue with it, the [Marketplace approval proecess](/appstore/general/share-app-store-content#approval) will reject the component and it will not b
Link - there is a typo "Marketplace approval process"

2022-02-22 10:06 UTC, KseniiaIankina commented on content/appstore/general/share-app-store-content.md
>  ![](attachments/share-app-store-content/package.jpg)
Rajesh will add a different attachment - latest one

2022-02-22 11:11 UTC, Adam-Dupaski commented on content/appstore/general/share-app-store-content.md
>  ![](attachments/share-app-store-content/package.jpg)
Okay, please ensure it uses the same example data.

2022-02-23 10:14 UTC, Adam-Dupaski commented
Merged #4225

2022-02-23 10:14 UTC, closed without merging