Update images and documentation for Model Creator
mendix/docs pull request #4259
Opened 2022-03-07 14:09 UTC by MarkvanMents

2022-03-15 07:13 UTC, gauravkrshah requested changes
Please update

2022-03-15 07:13 UTC, gauravkrshah commented on content/partners/sap/sap-data-models.md
> +The module contains a constant whose value is the service root of the OData service. For example, the **GWSAMPLE_BASIC** data model, generated from the SAP Catalog Service using the Model Creator for
name need to be changed to "Model Creator for SAP Integrations"

Have to be update at every place

2022-03-15 07:13 UTC, gauravkrshah commented on content/partners/sap/sap-odata-connector.md
> +You can use the [Model Creator for SAP solutions](https://sapodatamodelcreator.mendixcloud.com/) to generate a data model from the metadata of your OData service, exposed from your SAP back-end syste
link url - https://sapmodelcreator.mendixcloud.com/

have to be done at every place

2022-03-15 07:13 UTC, gauravkrshah commented on content/partners/sap/use-sap-odata-model-creator.md
> +description: "Presents the use of the OData functions of the Model Creator for SAP solutions."
Change Description to like:
Describes how to use Model Creator to generate/create Mendix model for SAP OData service

2022-03-15 07:13 UTC, gauravkrshah commented on content/partners/sap/use-sap-odata-model-creator.md
> +The Model Creator for SAP solutions will produce a module which is in Mendix version 8.15.1. To use the module you will have to create your app in, or upgrade your app to, Mendix version 8.15.1 or ab
Mendix version is 8.18.10

2022-03-18 14:49 UTC, MarkvanMents commented on content/partners/sap/use-sap-odata-model-creator.md
> +The Model Creator for SAP solutions will produce a module which is in Mendix version 8.15.1. To use the module you will have to create your app in, or upgrade your app to, Mendix version 8.15.1 or ab
Done

2022-03-18 14:49 UTC, MarkvanMents commented on content/partners/sap/sap-data-models.md
> +The module contains a constant whose value is the service root of the OData service. For example, the **GWSAMPLE_BASIC** data model, generated from the SAP Catalog Service using the Model Creator for
Done

2022-03-18 14:49 UTC, MarkvanMents commented on content/partners/sap/sap-odata-connector.md
> +You can use the [Model Creator for SAP solutions](https://sapodatamodelcreator.mendixcloud.com/) to generate a data model from the metadata of your OData service, exposed from your SAP back-end syste
Done

2022-03-18 14:49 UTC, MarkvanMents commented on content/partners/sap/use-sap-odata-model-creator.md
> +description: "Presents the use of the OData functions of the Model Creator for SAP solutions."
Done

2022-03-21 12:50 UTC, gauravkrshah requested changes
Looks Good. Two changes:
1. Most of the places, "Model creator for SAP Solutions" need to be replaced with "Model Creator for SAP Integrations"
2. Images need to be updated as with new release it is Header text is updated to "Model Creator for SAP Integrations"

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-data-models.md
> +Any OData service can be used to generate a data model using the Model Creator for SAP solutions. See [How To Use the Model Creator for SAP Integrations](/partners/sap/use-sap-odata-model-creator/) f
Model Creator for SAP Integrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-data-models.md
> +The module contains a constant whose value is the service root of the OData service. For example, the **GWSAMPLE_BASIC** data model, generated from the SAP Catalog Service using the Model Creator for
Model Creator for SAP Integrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +You can use the [Model Creator for SAP solutions](https://sapmodelcreator.mendixcloud.com/) to generate a data model from the metadata of your OData service, exposed from your SAP back-end system, or
SAP Integrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +You can create a data model by inspecting the service metadata. The response from the service can be used in the [Model Creator for SAP solutions](https://sapmodelcreator.mendixcloud.com/) to generat
Model Creator For SAP Integrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +This data model for the GWSAMPLE_BASIC service can be obtained from the [Model Creator for SAP solutions](https://sapmodelcreator.mendixcloud.com/). To create the data model, you do one of the follow
SAP Integrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +* You can find it in the **SAP Catalog Service** of the [Model Creator for SAP solutions](https://sapmodelcreator.mendixcloud.com/)
SAP Integrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +In both cases, save the file you download from the **Model Creator for SAP solutions** and then, using the instructions in [How to Use Model Creator for SAP Integrations](/partners/sap/use-sap-odata-
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +* [Model Creator for SAP Solutions](https://sapmodelcreator.mendixcloud.com/)
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +* [Model Creator for SAP Solutions](https://sapmodelcreator.mendixcloud.com/)
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +Handcrafting a Mendix domain model for these OData services would be a lot of work. The Model Creator for SAP solutions automates this process by creating a Mendix module for the selected service con
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +The Model Creator for SAP solutions will produce a module which is in Mendix version 8.18.10. To use the module you will have to create your app in, or upgrade your app to, Mendix version 8.18.10 or
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +Open the [Model Creator for SAP solutions - OData](https://sapmodelcreator.mendixcloud.com/link/odata), where you will be asked how you want to generate your model:
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +The Model Creator for SAP solutions is not currently available in the Marketplace within Studio Pro. It can only be run in a browser.
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +The Model Creator for SAP solutions is an app in the Marketplace. Search for it in the Mendix Marketplace, or find it here: [Model Creator for SAP solutions - OData](https://sapmodelcreator.mendixclo
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +You can also generate the data model from the metadata by providing the URL to the Model Creator for SAP solutions.
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +1. Click **URL** on the OData page of the Model Creator for SAP solutions.
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/use-sap-odata-model-creator.md
> +* [Model Creator for SAP Solutions](https://sapmodelcreator.mendixcloud.com/link/odata)
SAP Intergrations

2022-03-21 12:50 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-odata-connector.md
> +This is an object which is based on an entity type which is a specialization of the OdataObject entity in the OData Connector for SAP solutions domain model. These entities are the ones created in th
How these entities can be downloaded from Marketplace?
I know this is older document, but this line appears to be confusing.

2022-03-21 14:25 UTC, MarkvanMents commented on content/en/docs/partners/sap/sap-odata-connector.md
> +This is an object which is based on an entity type which is a specialization of the OdataObject entity in the OData Connector for SAP solutions domain model. These entities are the ones created in th
@gauravkrshah 
There used to be some OData modules pre-made in the Marketplace. I think they were mainly for customers to quickly test SAP.
Looks like there aren't any now, so I'll look at updating this.

2022-03-22 06:55 UTC, MarkvanMents commented
Merging
Will use a new PR to update the rest of the images.

2022-03-22 06:55 UTC, merged