Provide more details on access rule evaluation
mendix/docs pull request #4317
Opened 2022-03-17 19:17 UTC by jds-mendix

2022-03-17 19:21 UTC, sinteur approved these changes
Documents the behaviour of new objects properly.

2022-03-21 14:05 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +When a persistable object is passed to the runtime server as part of the request, the object is retrieved from the database. At that time the access rules are evaluated based on the values retrieved
I find this confusing.
If I change a persistable object in the client and then ask the runtime to commit the change, I don't want the runtime server to read the object from the database. This would overwrite my changes.
I assume it will only read it from the database _after_ it has committed any changes that I have made to the object.

2022-03-21 14:07 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +### 3.2 Persisted Objects
There is nothing about Non-persistable objects here.
Is this because there are no rules on non-persistable objects?
If there are access rules for NP objects, I think we should mention it.

2022-03-21 14:08 UTC, MarkvanMents requested changes
Hi Jan-David @jds-mendix 

I have made a couple of comments. Can you see if they make sense and whether they need any update to the text.

If no changes are needed, this is ready to be published.

2022-03-21 14:08 UTC, jdsalchow commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +When a persistable object is passed to the runtime server as part of the request, the object is retrieved from the database. At that time the access rules are evaluated based on the values retrieved
You are absolutely right, this is incomplete. What actually happens is that the client sends "changes" and an object id. The request is than processed as follows:

1. the object is retrieved from the database according to the id and its access rules are evaluated
2. changes, if any, are applied to the object

2022-03-21 14:09 UTC, jdsalchow commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +### 3.2 Persisted Objects
NP objects cannot have XPath constraints, so those don't need to be evaluated

2022-03-21 14:10 UTC, jdsalchow commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +### 3.2 Persisted Objects
It would not hurt mentioning that here I guess ;)

2022-03-21 14:11 UTC, jdsalchow commented
Hi @MarkvanMents, I have  responded. Shall I make changes or do you want to?

2022-03-21 16:22 UTC, MarkvanMents commented
> Hi @MarkvanMents, I have responded. Shall I make changes or do you want to?

Perhaps better if you make the changes? Especially the one about when the object is retrieved and how the access rules are then applied? Then I'm sure it is technically correct.

But let me know in the unlikely event that you are struggling to find the words 😀.

2022-03-23 15:54 UTC, jds-mendix commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +### 3.2 Persistable Objects
@MarkvanMents I actually meant `Persisted Objects`, i.e. those actually stored in the database, as opposed to `New Objects`. I think this division also works though

2022-03-24 08:28 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules.md
> +### 3.2 Persistable Objects
Ah, I see. I'm so used to correcting people who use Persistable wrongly I didn't see the difference.

I think this might be too subtle for the reader - perhaps I need to say **Objects Stored in the Database**.
```suggestion
### 3.2 Objects Stored in the Database
```

2022-03-24 08:34 UTC, MarkvanMents approved these changes
Great update. It's much clearer to me now.
I have suggested a change to the heading to reflect your intention. Can you review/commit that changes, then I can publish this.
Thanks for your work in explaining this.
Mark

2022-03-24 09:35 UTC, jds-mendix commented
Nice suggestion @MarkvanMents. Can we merge it?

2022-03-24 10:45 UTC, MarkvanMents commented
Merging.
Thanks for all your work.

2022-03-24 10:46 UTC, merged