WIP: column chart
mendix/docs pull request #4324
Opened 2022-03-18 10:41 UTC by Ahmad-Elsayed

Work in progress, yet to be released.

2022-03-18 12:29 UTC, ConnorLand commented
Thanks for your PR description @Ahmad-Elsayed . Does this PR require a tech check by Jordan? If so, I can put a Technical Verification Required label on it as well.

2022-03-18 13:06 UTC, Ahmad-Elsayed commented
@ConnorLand yes it requires @jordanch review.

2022-06-15 06:51 UTC, UrazAkgultan requested changes
Good work 👍 

I've left some comments

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `columns` > `customColumnStyles` > `any_custom_column_style_name` > `column` | `color` | Applies a color to the column (string). If columns are configured to have labels, the labels will be the sam
It should be `columnColor` instead of `color`.

```suggestion
| `columns` > `customColumnStyles` > `any_custom_column_style_name` > `column` | `columnColor` | Applies a color to the column (string). If columns are configured to have labels, the labels will be the same color as the column. |
```

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +    </columnColorPalette>
I think you should move the slash mark to the end of the word.

```suggestion
    <columnsOffset/>
    <columnColorPalette/>
```

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `grid` | `padding` | Applies padding to all sides of the grid (number). This makes axis value labels visible. |
Didn't apply padding to the grid.

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `grid` | `paddingHorizontal` | Applies padding to the horizontal sides of the grid (number). This makes axis value labels visible. |
Didn't apply padding to the horizontal sides of the grid.

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `grid` | `paddingVertical` | Applies padding to the vertical sides of the grid (number). This makes axis value labels visible. |
Didn't apply padding to the vertical sides of the grid.

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `xAxis` | `lineWidth` | Applies a width to the axis line (number). |
Didn't apply width to the axis line. (same for yAxis)

2022-06-15 06:51 UTC, UrazAkgultan commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `columns` | `columnColorPalette` | Provides colors to columns that do not have a column color configured (string with list of colors separated by ';'). |
I created a color list like this `columnColorPalette: "#00ffdd;#00ff50;#5000ff;#f2ff00;"` but it only applied the first color to the columns.

2022-06-15 08:25 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `columns` > `customColumnStyles` > `any_custom_column_style_name` > `column` | `color` | Applies a color to the column (string). If columns are configured to have labels, the labels will be the sam
done

2022-06-15 08:26 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +    </columnColorPalette>
done

2022-06-15 09:30 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `grid` | `padding` | Applies padding to all sides of the grid (number). This makes axis value labels visible. |
fixed in the widget code

2022-06-15 09:30 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `grid` | `paddingHorizontal` | Applies padding to the horizontal sides of the grid (number). This makes axis value labels visible. |
fixed in the widget code

2022-06-15 09:30 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `grid` | `paddingVertical` | Applies padding to the vertical sides of the grid (number). This makes axis value labels visible. |
fixed in the widget code

2022-06-15 09:30 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `xAxis` | `lineWidth` | Applies a width to the axis line (number). |
fixed , should be width

2022-06-15 09:31 UTC, Ahmad-Elsayed commented on content/en/docs/refguide8/mobile/native-mobile/native-styling-refguide.md
> +| `columns` | `columnColorPalette` | Provides colors to columns that do not have a column color configured (string with list of colors separated by ';'). |
this should be a color for each series

2022-06-15 11:17 UTC, UrazAkgultan approved these changes
LGTM 👍

2022-06-16 09:55 UTC, Ahmad-Elsayed commented
@MarkvanMents @ConnorLand we are working on releasing this widget to the marketplace today, so your review will be appreciated

2022-06-16 10:00 UTC, MarkvanMents approved these changes

2022-06-16 14:44 UTC, MarkvanMents commented
Confirmed over Slack.

2022-06-16 14:44 UTC, merged