Clean up file comments and update to Docsy v0.1.0
mendix/docs pull request #4367
Opened 2022-03-29 10:59 UTC by NatasaKralj

I changed comment formatting in html partials from html comments to go template comments.
I adjusted comments and contents in SCSS files to match Docsy v0.1.0.
I added a fix for the height of headers, to allow for selection of items above them.
I adjusted layouts files to match Docsy v0.1.0 templates.

When trying to upgrade the following files to Docsy v0.1.0, I could not get a new version to work:
`layouts/partials/page-meta-lastmod.html`
`layouts/partials/page-meta-links.html`
I added comments to the files, will make a to do in our ongoing effort doc.

2022-03-29 15:11 UTC, MarkvanMents requested changes, later dismissed
Seems to be a different issue. Unrelated to comment style. Ignore comment below.

~Need to review whether we are doing comments right. See comments below, but one of the changes certainly hasn't worked.~
~I think that the {{ /* comments work in documents, but in partials/shortcodes the templater doesn't recognize them? Or perhaps having {{ inside {{ messes things up.~

~We should probably go back to using <!-- comments in most places, and then review what gets built to see if we need to change anything?~

2022-03-29 15:11 UTC, MarkvanMents commented on layouts/partials/navbar.html
> +{{/* {{ $cover := and (.HasShortcode "blocks/cover") (not .Site.Params.ui.navbar_translucent_over_cover_disable) }}
Should we have a comment here?
Do we actually need this, or have we commented out every call to navbar and therefore we don't have to overwrite the Docsy version at all?

2022-03-29 15:11 UTC, MarkvanMents commented on layouts/partials/print/render.html
> +{{/* MvM: Remove ToC from the printed section pages
**Not related to comment style!**
~This doesn't seem to have worked - need to rethink which comments need to be in HTML comments and which in GoTemplate comments.~
![image](https://user-images.githubusercontent.com/35492184/160642571-214873de-2c49-4be0-8004-2c2179ae76d2.png)

2022-03-29 15:17 UTC, MarkvanMents commented on layouts/partials/print/render.html
> +{{/* MvM: Remove ToC from the printed section pages
Oh no - wasn't that? Perhaps I'm misremembering. It is the other way around on the current site 😅 so that wasn't quite right either.
But doesn't look like it is a comment issue, so I take that back.
![image](https://user-images.githubusercontent.com/35492184/160645606-ac0962f5-7380-49c4-aea9-7f25879fcc1d.png)

2022-03-29 15:35 UTC, MarkvanMents reviewed
Found the strange behaviour with the print partial

2022-03-29 15:35 UTC, MarkvanMents commented on layouts/docs/baseof.print.html
> -          <div class="col-12 col-md-3 col-xl-2 td-sidebar d-print-none">
These are the lines which were making the print gutter appear to the left rather than the right!

2022-03-29 15:35 UTC, MarkvanMents commented on layouts/docs/baseof.print.html
>            <main class="col-12 col-md-9 col-xl-8 pl-md-5" role="main">
This displays the print version on the whole screen without empty columns on either side
```suggestion
          <main class="col-12 col-md-12 col-xl-12 pl-md-5" role="main">
```
Can you try this out and see if it looks OK for you.

2022-03-30 07:38 UTC, NatasaKralj commented on layouts/docs/baseof.print.html
>            <main class="col-12 col-md-9 col-xl-8 pl-md-5" role="main">
Fixed with `<main class="col-12 pl-md-5" role="main">`

2022-03-30 07:40 UTC, NatasaKralj commented on layouts/partials/navbar.html
> +{{/* {{ $cover := and (.HasShortcode "blocks/cover") (not .Site.Params.ui.navbar_translucent_over_cover_disable) }}
If we don't comment it out, we have to add 3 more files from Docsy into layouts to comment out the call to navbar.

2022-03-30 07:45 UTC, NatasaKralj commented on layouts/partials/navbar.html
> +{{/* {{ $cover := and (.HasShortcode "blocks/cover") (not .Site.Params.ui.navbar_translucent_over_cover_disable) }}
Added a comment to the top of the file for more information.

2022-03-30 13:12 UTC, NatasaKralj commented
I fixed the last 2 partials to be updated to Docsy v0.1.0.
I also changed the Edit button property to take the user to the file blob on GH, but the edit page directly.

2022-03-31 08:09 UTC, NatasaKralj commented
Approved via slack, merging

2022-03-31 08:09 UTC, merged