Advanced Audit Trail doc
mendix/docs pull request #4443
Opened 2022-04-11 13:52 UTC by Luyao-Zhang-1

2022-04-12 10:56 UTC, SnuktheGreat reviewed
Hey, this is Dennis here. Snuk the Great is my private GitHub account that I linked to Mendix as well. It seemed like a good idea at the time, but now I realise it will get confusing fast haha.

I added some comments, but Rik would know beter better for most of these.

2022-04-12 10:56 UTC, SnuktheGreat commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail allows you to trace changes, gain detailed insight in reading and writing data, use infinitely-scalable and fully-indexed data search, and have dashboards, alerting and connectiv
The following items are on the roadmap, but not implemented:
- Insight into reads
- Alerting
- Connectivity to data warehouses

2022-04-12 10:56 UTC, SnuktheGreat commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +With this app service, you can create audit snapshots of objects to store an Audit Trail. This Audit Trail is centralized and sent to a long-term data storage, and therefore supports complex search q
"You can create audit snapshots" - The system creates these automatically. You just need to configure it.

2022-04-12 10:56 UTC, SnuktheGreat commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +*  Decoupling: when the external system is down, the snapshots will be stored in the local database, thus ensuring that the main system will keep on working without a dependency on the external datab
Instead of writing "when the external system is down" I would suggest something like "when the external system can not be reached". For instance, for when the internet can not be reached or there are network issues on either side.

2022-04-12 10:56 UTC, SnuktheGreat commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +  * Environment Name: the name of the environment, which sould be unique in your audit data storage, for example, *myApp-prod*
I think we should add a warning here too, that if they use the wrong application name, it can not be fixed afterwards. If two applications use the same name, the audit trail will not be able to distinguish between the two, effectively breaking the audit trail for both applications irreversibly.

2022-04-12 16:00 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +description: "Describes the configuration and usage of the Advanced Audit Trail app service, which is available in the Mendix Marketplace."
test

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail uses Kafka and Elasticsearch, shown in the intergration diagram below:
We have build a software stack on top of ... to leverage their utility for audit trail in Mendix

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail allows you to trace changes, use infinitely-scalable and fully-indexed data search, and have dashboards. Once configured, the system automatically creates audit snapshots of obje
Let's remove `dashboards`

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +* Create, store, and display a trail of open actions
I'd remove this line

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +* Trace a list of events, instead of persistent data, by logging a non-persistent entity (use the Object Code for making the trail recognizable)
I'd remove this line

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.1 Typical Use Cases
I'd add something along the lines of Compliance, regulated markets and GxP

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.3 Limitations
Can be removed, no longer applicable

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +* Advanced Audit Trail can only be used with Studio Pro 9 versions starting with [9.11.1](https://docs.mendix.com/releasenotes/studio-pro/9.11/).
Prereq is now `9.12`

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.3 Limitations
A limitation is that the module can only be configured using SP and not with Studio (web)

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +5. Make sure that the scheduled events are enabled in the deployment environments.
Due to protected modules we don't show the scheduled events in SP, they have to be enabled in the cloud portal

2022-04-12 17:40 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +    {{% alert color="warning" %}}Access from and to the long-term data storage is based on service accounts. This means that once a user can access the **Snippet_Settings**, they can access all data
`DisplayUser` -> `DisplayOnly`

2022-04-13 09:31 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.3 Limitations
All the app services cannot be used with Studio, so I would leave this out from the limitations.

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Followed the instructions in the [Importing Content from the App Explorer](/appstore/general/app-store-content/#import) section in *Use Marketplace Content in Studio Pro* to import the **AdvancedAudi
There has been a rename (to align the modules with the product name):
* AdvancedAuditSnapshots --> AdvancedAuditTrail
* AdvancedAuditSnapshotsUI --> AdvancedAuditTrailUI

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +   {{% alert color="info" %}}Due to protected modules, we don not show scheduled events in Studio Pro.{{% /alert %}}
`don` --> `do`

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +3. Implement the **Before Commit** (**BCo**) and **Before Delete** **(Bde)** events (see the examples). Use the events on the domain model settings (**BCo** / **BDe**).
We should add a warning / implementation note that for Specializations / Generalizations the developer should only add the event to the generalized object _or_ to all the specializations (since the events will be triggered "double" if this is not configured correctly).

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +3. Implement the **Before Commit** (**BCo**) and **Before Delete** **(Bde)** events (see the examples). Use the events on the domain model settings (**BCo** / **BDe**).
We should warnings / implementation notes:
* when an object is committed without events, this change is not audited unless people explicitly add a `Create Snapshot` / `Create Snapshot (List)` action before the commit
* when there are multiple before commit / delete events that may change the object, the order is not guaranteed (see https://docs.mendix.com/refguide/event-handlers/). This means that some changes could theoretically fall outside the context of an audit.

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +3. Implement the **Before Commit** (**BCo**) and **Before Delete** **(Bde)** events (see the examples). Use the events on the domain model settings (**BCo** / **BDe**).
We can refer that some compliancy schemes may require you to never delete an object and that this should be implemented outside the context of the audit trail module.

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +    {{% alert color="warning" %}}Access from and to the long-term data storage is based on service accounts. This means that once a user can access the **Snippet_Settings**, they can access all data
ACT_Object_OpenAuditTrailPrettyView --> `Query Snapshots for object`

2022-04-14 13:53 UTC, rik-bos commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 3.5 Implementing Custom User Logging (Optional)
I'd add a 3.5 before the current 3.5:
### 3.5 Implement Additional Info

* Possibility to add additional info to the snapshot (e.g. to capture why a user has done a specific change)
* Use `Set additional info for snapshots`
* All snapshots that will be created in this microflow, after this action ran, will have this additional info

2022-05-30 13:08 UTC, brfreekmx requested changes

2022-05-30 13:08 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.6 Solution Package
Can we change this Module packages and also link to the Core and UI module package? These will become upgradable separately through the marketplace.

2022-05-30 13:08 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +To use Advanced Audit Trail, you need to install [Atlas Core](https://marketplace.mendix.com/link/component/117187) and [Atlas Web Content](https://marketplace.mendix.com/link/component/117183) in yo
Another dependency is the UI module. This should also be listed to the dependencies?

2022-05-30 13:08 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +For an example implementation of each display formatter, see the **ExampleImplementation** module in the [Advanced Audit Trail solution package](https://marketplace.mendix.com/link/component/120236).
Can we leave this line out for now? We're not sure yet if we can release the solution package as an app service directly.

2022-05-30 13:16 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +For an example implementation of each display formatter, see the **ExampleImplementation** module in the [Advanced Audit Trail solution package](https://marketplace.mendix.com/link/component/120236).
Done. Also removed the following section for the same reason:

### 1.6 Solution Package

For a working copy, see [Advanced Audit Trail solution package](https://marketplace.mendix.com/link/component/120236).

2022-05-30 13:25 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +To use Advanced Audit Trail, you need to install [Atlas Core](https://marketplace.mendix.com/link/component/117187) and [Atlas Web Content](https://marketplace.mendix.com/link/component/117183) in yo
Added this module as a dependency.

2022-05-30 13:37 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.6 Solution Package
Maybe it's better to remove this section, because it's not clear yet if the solution package will be released as an app service directly?

2022-06-15 11:16 UTC, brfreekmx requested changes

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail allows you to trace changes and use infinitely-scalable and fully-indexed data search. Once configured, the system automatically creates audit snapshots of objects to store an au
creates audit snapshots of objects to store **in** the audit trail.

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +*  Supports searching full-text search on the data, search on changed data, and exporting data to CSV format using [Kibana](https://www.elastic.co/guide/en/kibana/index.html)
Can we remove the reference to Kibana from this line?

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail contains an [add-on module](refguide/consume-add-on-modules-and-solutions/). Mendix Studio does not support add-on modules. It should be disabled for your app.
Can we change this to something like:
Advanced Audit Trail contains an add on core module. This is only supported from Mendix 9.12.0 and onwards?

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +* You need to have external data storage to store your audit data that runs in the Mendix Cloud.
Can we change this to something like:
You need to have a subscription for the Advanced Audit Trail App service to store your data in an external data store that runs in the Mendix Cloud?

For now the customers do not bring their own external data storage which this implies.

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.5 Dependencies
You also need to install the audit trail core module. can we refer to that as well?

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Followed the instructions in the [Importing Content from the App Explorer](/appstore/general/app-store-content/#import) section in *Use Marketplace Content in Studio Pro* to import the **AdvancedAudi
The AdvancedAuditTrail module will be renamed to Advanced Audit Trail Core, where the AdvancedAuditTrailUI will be renamed to Advanced Audit Trail UI

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +5.  Make sure that the [scheduled events](#scheduled-events) are enabled in the cloud portal.
One space to many?

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +    *  Environment Name: This is the name of the environment within Kibana, which should be unique in your audit data storage, for example, *myApp-prod*. Do not use any whitespace for the environment
Due to a technical limitation we also don't support the tilde ~ character, can this be added?

2022-06-15 11:16 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +4. Add search to the navigation, or implement the Query Snapshots for object action.
Can this be changed to something like:
4. Add the open search page microflow (AdvancedAuditTrailUI.ACT_SnapshotQuery_CreateAndShowSearch) to the navigation.

The latter part Implement the Query Snapshots is unclear and not really applicable as the ACT_ flow already has the desired implementation.

2022-06-15 11:35 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +3.  Implement the **Before Commit** (**BCo**) and **Before Delete** **(Bde)** events (see the examples). Use the events on the domain model settings (**BCo** / **BDe**).
Can you remove the reference **(see the examples)** to the ExampleImplementation module? The module won't be included in neither core/UI module, so any references to it may confuse developers.

2022-06-15 11:38 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail contains an [add-on module](refguide/consume-add-on-modules-and-solutions/). Mendix Studio does not support add-on modules. It should be disabled for your app.
While I agree with what Freek says, I do think it's important to document that the core module is not compatible with Mendix Studio.

2022-06-15 11:51 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +*  Offers admin interface to search through the external database (across entities)
Can you change the word "admin" to "auditor"?

2022-06-15 11:52 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +
6. Configure the Kafka endpoint, username and password

2022-06-15 11:52 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +
7. Configure the Kibana endpoint, username and password

2022-06-15 11:53 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +*  Allows the user to add a page to the interface where they have to specify why a change is made – once added, this will be automatically added to all the tracked changes
Allows the developer to configure an input field where additional information can be supplied about the snapshot to be created - once addded, this will be category will be automatically added to all snapshots

2022-06-15 11:54 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +- **SE_CleanupSnapshotCache**: This cleans up the cached data based on the retention settings – **OnlyDeleteProcessedItems** and **LogRetentionDays**.This occurs daily at 3:00 AM UTC.
Misses a space prior to the last sentence.

2022-06-15 11:59 UTC, trongbtran commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +It is possible to add additional info to the snapshot (e.g. to capture why a user has done a specific change). Use `Set additional info for snapshots`. All snapshots that will be created in this micr
It is possible to submit additional information to the snapshot (e.g., in order to provide a rationale on why said action has taken place on the object in question). Developers can configure this feature for certain actions (creation, deletion, updating). To use this feature the developer must use the 'Set additional info for snapshots' java action (JA_SetAdditionalInfo) that is included in the module.

2022-06-15 12:05 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +Advanced Audit Trail contains an [add-on module](refguide/consume-add-on-modules-and-solutions/). Mendix Studio does not support add-on modules. It should be disabled for your app.
Ah check, you're right. @Luyao-Zhang-1 please ignore this.

2022-06-16 07:31 UTC, brfreekmx requested changes

2022-06-16 07:31 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +
Isn't this part of 3. Configure the constants (this links to the next paragraph explaining about the kafka and kibana endpoint/credential configuration)

2022-06-16 07:31 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +
Same as above.

2022-06-16 07:31 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +    *  **LogRetentionDays**: the days that the records be kept in the database
This should be SnapshotRetentionDays instead of LogRetentionDays.

2022-06-16 07:31 UTC, brfreekmx commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +- **SE_CleanupSnapshotCache**: This cleans up the cached data based on the retention settings – **OnlyDeleteProcessedItems** and **LogRetentionDays**.This occurs daily at 3:00 AM UTC.
LogRetentionDays should be SnapshotRetentionDays

2022-06-16 09:30 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +*  Supports searching full-text search on the data, search on changed data, and exporting data to CSV format using [Kibana](https://www.elastic.co/guide/en/kibana/index.html)
@brfreekmx link (https://www.elastic.co/guide/en/kibana/index.html) is removed.

2022-06-16 09:41 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +* You need to have external data storage to store your audit data that runs in the Mendix Cloud.
@brfreekmx :+1::skin-tone-3: Will also remove the note below it:
`Your applications do not have to be deployed in the Mendix Cloud, as long as they can connect to the external data storage. So it is possible to have a multi-cloud setup with Mendix Cloud to store your audit data and a different cloud to deploy your applications.`

2022-06-16 09:47 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +### 1.5 Dependencies
@brfreekmx I am confused - isn't this doc for the Advanced Audit Trail core module?

2022-06-16 09:50 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/app-services/advanced-audit-trail.md
> +5.  Make sure that the [scheduled events](#scheduled-events) are enabled in the cloud portal.
It is, but it is necessary to add an extra space if there is a short code following the bullet point – this is one of the weird Markdown rules that we have to follow.

2022-08-11 09:39 UTC, merged