Add index page for new charts module
mendix/docs pull request #4445
Opened 2022-04-11 15:27 UTC by iobuhov

In this PR we adding new docs page for upcoming charts module.
This module is not yet released, but we working hard on publishing it to marketplace. Please, reach someone in Web Content team to align merge/release dates.

Right now this PR includes:
- [x] Index page (in progress)
- [ ] Area chart page
- [ ] Bar chart page
- [ ] Bubble chart page
- [ ] Column chart page
- [ ] Heatmap chart page
- [ ] Line chart page
- [ ] Pie chart page
- [ ] Time series chart

2022-04-26 07:19 UTC, Keraito commented
@iobuhov right now your PR descriptions mention that only 2 pages were done, can we already do a tech review or should we wait?

2022-04-28 11:25 UTC, Keraito reviewed
Generally looks good, very nice screenshots. Have minor remarks/questions. After addressing those, the docs team can take this as I think the structure (and grammar) can be optimized a bit cc @ConnorLand

2022-04-28 11:25 UTC, Keraito commented on content/en/docs/appstore/modules/charts/_index.md
> +### Dimensions
@ConnorLand this section is basically the same as https://github.com/mendix/docs/blob/development/content/en/docs/appstore/widgets/maps.md#36-dimensions. So maybe it's better to just copy it as it also explains the relationships between the different properties.

2022-04-28 11:25 UTC, Keraito commented on content/en/docs/appstore/modules/charts/_index.md
> +##
@iobuhov you're missing a title here

2022-04-28 11:25 UTC, Keraito commented on content/en/docs/appstore/modules/charts/_index.md
> +## Migration from Charts v1 and v2 to Charts Module
Just to make sure: we're going from v2 to v3. The new ones are v3.

2022-04-28 11:25 UTC, Keraito commented on content/en/docs/appstore/modules/charts/_index.md
> +<!-- Add screenshots of marketplace with Charts module -->
@iobuhov are you gonna pick this up?

2022-04-29 07:54 UTC, iobuhov commented on content/en/docs/appstore/modules/charts/_index.md
> +<!-- Add screenshots of marketplace with Charts module -->
No, I'll remove it

2022-04-29 08:31 UTC, iobuhov commented
@ConnorLand, ready for your review.

2022-06-14 14:30 UTC, ConnorLand requested changes
Almost done. I just need to do a final check on references to "version 3" and references to the "new widget" (must be changed to "new module").

2022-06-15 12:09 UTC, ConnorLand approved these changes

2022-06-15 12:20 UTC, merged