AWS S3 Connector and Authentication Module
mendix/docs pull request #4450
Opened 2022-04-12 14:41 UTC by MarkvanMents

2022-04-13 12:19 UTC, MarkvanMents reviewed
I have added some questions which arose during the writing of this connector document.

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +The Java Actions you can use are listed below. You can drag them into your microflows from **App** > **Marketplace modules** > **AWSS3Connector** > **_USE_ME**.
Do you have any plans to set the Java actions as Expose as microflow action so customers see them in the Microflow Toolbox.
Perhaps as Get S3 Object or something?
![image](https://user-images.githubusercontent.com/35492184/163175784-08e02161-e60d-4c35-80f4-58c6f17c832b.png)

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +#### 3.2.2 List Prefix
Not sure how useful this is, since you don't allow listing objects by prefix.

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +**Parameters**
Should there be a way of filtering this list, by `prefix` for example. It could be very large.

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This will return a maximum of 1000 objects from your S3 bucket.
Do we use the default of 1000 objects, or override it in our API call?
If there are more than 1000 objects, could we use `start-after` to let users get the _next_ 1000 objects?

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `S3Object` – the object which you want to download — the object must contain the `Key` of the object and be associated with the desired `Bucket`
Does this have to be associated with a Bucket, or does it use `BucketName` from the S3Object entity. What happens if the associated Bucket and the `BucketName` point to different buckets?

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `Document` – contains the data you want to upload to AWS S3 Storage — the `Name` attribute of the document contains the `Key` of the S3 object where the content is put
I assume that there is no restriction on the value of `Name` and that it can be something like `/folder/subfolder/foo.bar`

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This action puts the contents of a `Document` object into a single object defined by an object of entity type `S3Object`. The name of the object is the `Name` attribute of the `Document`. This action
Please confirm that Put will work for both Create and Update.

2022-04-13 12:19 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `S3Object` – the object which you want to delete — the object must contain the `Key` of the object and be associated with the `Bucket` it is in
What is the minimum information that needs to be in the S3Object?
Does it use `BucketName` from the attribute or the association?

2022-04-20 10:15 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +The Java Actions you can use are listed below. You can drag them into your microflows from **App** > **Marketplace modules** > **AWSS3Connector** > **_USE_ME**.
yes, nice idea. we will do it.

2022-04-20 10:15 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +The Java Actions you can use are listed below. You can drag them into your microflows from **App** > **Marketplace modules** > **AWSS3Connector** > **_USE_ME**.
yes, nice idea. we will do it.

2022-04-20 10:19 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +**Parameters**
do you mean searching in prefix lists

2022-04-20 10:19 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +**Parameters**
do you mean searching in prefix lists

2022-04-20 10:21 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This will return a maximum of 1000 objects from your S3 bucket.
Good point. we need to provide input param to pass this value.

2022-04-20 10:21 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This will return a maximum of 1000 objects from your S3 bucket.
Good point. we need to provide input param to pass this value.

2022-04-20 10:21 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This will return a maximum of 1000 objects from your S3 bucket.
> Do we use the default of 1000 objects, or override it in our API call? If there are more than 1000 objects, could we use `start-after` to let users get the _next_ 1000 objects?



> Do we use the default of 1000 objects, or override it in our API call? If there are more than 1000 objects, could we use `start-after` to let users get the _next_ 1000 objects?

Good point. we need to provide input param to pass this value.

2022-04-20 10:21 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This will return a maximum of 1000 objects from your S3 bucket.
> Do we use the default of 1000 objects, or override it in our API call? If there are more than 1000 objects, could we use `start-after` to let users get the _next_ 1000 objects?



> Do we use the default of 1000 objects, or override it in our API call? If there are more than 1000 objects, could we use `start-after` to let users get the _next_ 1000 objects?

Good point. we need to provide input param to pass this value.

2022-04-20 12:14 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +**Parameters**
In the API spec, there seems to be only one way to limit the number of objects retrieved, which is specifying the **prefix** in the request URI.
https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax
Otherwise, you have to list everything in the bucket (with a maximum of 1000 items per call, unless you hide that from the customer and always download a list of everything - but that could lead to a huge list).

Since you have an action to list prefixes, you could then use the prefix to just list objects with a specific prefix.

2022-04-20 12:57 UTC, gauravkrshah reviewed
We are working on changes to resolve region access issue. I will update you once these changes will be done. An Additional parameter will be added to java actions

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `S3Object` – the object which you want to delete — the object must contain the `Key` of the object and be associated with the `Bucket` it is in
ideally yes. let me check if this can be removed.

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-authentication.md
> +4. Either create an access key by clicking **Create access key** or use an existing **Access key ID**. This is the value to be stored in the `AccessKey` attribute of `StaticCredentials`.
this will be renamed as "AccessKeyId" in the module

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-authentication.md
> +The AWS Authentication Module records static credentials in your app's database which are used to authenticate to an AWS Service.
in your app's database in encrypted form

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-authentication.md
> +* AccessKey – the access key id which can be obtained from the AWS Console
will be renamed as AccessKeyId

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +When using the Java actions, results will be stored in the following entity types, which also need to be passed to other Java actions to specify on which object(s) an action is to be performed.
Doesn't clear to me, what exactly want to convey with text "which also need to be passed to other Java actions to specify on which object(s) an action is to be performed." and below table

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `S3Object` – the object which you want to download — the object must contain the `Key` of the object and be associated with the desired `Bucket`
looking if bucketname can be removed from S3Object and taken from association for moveObject use case.

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This action puts the contents of a `Document` object into a single object defined by an object of entity type `S3Object`. The name of the object is the `Name` attribute of the `Document`. This action
yes, Put will work for Create and Update both. If the object is already exists, then it will override the previous one unless versioning policy is defined.

2022-04-20 12:57 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `Document` – contains the data you want to upload to AWS S3 Storage — the `Name` attribute of the document contains the `Key` of the S3 object where the content is put
There are restrictions or recommendations mentioned at https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html

2022-04-21 07:45 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This action puts the contents of a `Document` object into a single object defined by an object of entity type `S3Object`. The name of the object is the `Name` attribute of the `Document`. This action
Thanks

2022-04-21 08:04 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +When using the Java actions, results will be stored in the following entity types, which also need to be passed to other Java actions to specify on which object(s) an action is to be performed.
I'm trying to say that the Java actions use entity objects to decide what information to get - i.e. you can't pass the information using variables or constants.
Therefore you have to pass an object to the Java action so that it knows what to do.
The table is there to duplicate the information in the image for those people who need to use a screen reader.

2022-04-21 08:16 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-authentication.md
> +The AWS Authentication Module records static credentials in your app's database which are used to authenticate to an AWS Service.
Updated

2022-04-21 08:16 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-authentication.md
> +4. Either create an access key by clicking **Create access key** or use an existing **Access key ID**. This is the value to be stored in the `AccessKey` attribute of `StaticCredentials`.
Updated

2022-04-21 08:16 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-authentication.md
> +* AccessKey – the access key id which can be obtained from the AWS Console
Updated

2022-04-21 08:16 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +* Object of type `Document` – contains the data you want to upload to AWS S3 Storage — the `Name` attribute of the document contains the `Key` of the S3 object where the content is put
Added a link.

2022-05-03 10:22 UTC, MarkvanMents reviewed
Updated for changes to modules

2022-05-03 10:22 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +When using the Java actions, results will be stored in the following entity types, which also need to be passed to other Java actions to specify on which object(s) an action is to be performed.
Updated, hope this is clearer now.

2022-05-03 10:22 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +This will return a maximum of 1000 objects from your S3 bucket.
Tested and returns all objects (over 16000) in the test S3 buckets.

2022-05-03 10:24 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-authentication.md
> +The AWS Authentication Module records static credentials in your app's database which are used to authenticate to an AWS Service.
No longer applicable.

2022-05-04 05:35 UTC, gauravkrshah requested changes
Thanks! Mark. Looks good. one minor change please update.

2022-05-04 05:35 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-authentication.md
> +The AWS Authentication Module records encrypted static credentials in your app's database which are used to authenticate to an AWS Service.
Remove this. This module no more store credentials.  This module provides java actions to accept static credentials.

2022-05-04 05:35 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +The Java actions provided in the module need AWS credentials. These are stored using the [AWS Authenticator Module](/appstore/connectors/aws-authentication/). This needs to be set up as described in
replace "stored" with "provided"

2022-05-04 06:56 UTC, MarkvanMents reviewed
Thanks for the review. I didn't have the time I would have liked to fully review the document. Good to have another pair of eyes spotting what I missed.

2022-05-04 06:56 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-authentication.md
> +The AWS Authentication Module records encrypted static credentials in your app's database which are used to authenticate to an AWS Service.
Well spotted. I missed that. Removed.

2022-05-04 06:56 UTC, MarkvanMents commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +The Java actions provided in the module need AWS credentials. These are stored using the [AWS Authenticator Module](/appstore/connectors/aws-authentication/). This needs to be set up as described in
Done.

2022-05-05 04:49 UTC, gauravkrshah approved these changes

2022-05-05 06:57 UTC, MarkvanMents commented
Thanks @gauravkrshah 
I just need to add the links to the Marketplace, once they are released, and then I can publish.
Please let me know when you are ready to go.
Mark

2022-05-12 08:04 UTC, MarkvanMents commented
Component IDs have been assigned. Publishing.

2022-05-12 08:04 UTC, MarkvanMents commented
Component IDs have been assigned. Publishing.

2022-05-12 08:04 UTC, merged

2022-10-28 13:09 UTC, CasperSpronk27 commented on content/en/docs/appstore/connectors/aws-authentication.md
> +You can now use the AWS Authentication Module in your app by using the `Get Static Credentials` microflow action, available in the **Toolbox**.
Get Static Credentials can be changed with Get Session Credentials

2022-10-28 13:10 UTC, CasperSpronk27 commented on content/en/docs/appstore/connectors/aws-s3-connector.md
> +1. Provide a **Credentials** object which you have retrieved using the `GetStaticCredentials` microflow in the [AWS Authenticator Module](/appstore/connectors/aws-authentication/) — this needs to be
GetStaticCredentials can be replaced with GetSessionCredentials