[Draft] Add documentation for PW association property [9.13]
mendix/docs pull request #4451
Opened 2022-04-12 14:58 UTC by mlaponder

2022-04-19 08:34 UTC, tamelbrun requested changes

2022-04-19 08:34 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +`status` is similar to the one exposed for `DynamicValue`. It indicates if the value's loading has finished and if loading was successful. Similarly to `DynamicValue`, `EditableValue` keeps returning
I suspect that this was copied from `EditableValue`, but it should be `ModifiableValue` here ;)

2022-04-19 08:34 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +ModifiableValue is used to represent values that can be changed by a pluggable widget client component and is passed only to [association properties](/apidocs-mxsdk/apidocs/pluggable-widgets-property
Should `ModifiableValue` (and similarly, `EditableValue` in the first sentence of that section) be formatted as code here?

2022-04-19 08:34 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +The type the component receives for the association property depends on the allowed association types. If only references are allowed the component receives a `ReferenceValue` which is defined as `Mo
I would say "The type received by the component" instead, but maybe @ConnorLand would already pick up on this when dotting all the i's and crossing all the t's :P.

2022-04-19 08:34 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +### 4.4 ModifiableValue {#modifiable-value}
@ConnorLand, do you see any problems with changing the numbering of existing sections? (I do think the order of the sections makes more sense this way.)

2022-04-19 09:16 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +`status` is similar to the one exposed for `DynamicValue`. It indicates if the value's loading has finished and if loading was successful. Similarly to `DynamicValue`, `EditableValue` keeps returning
Ah, sloppy pasted indeed 🤦 , fixed

2022-04-19 09:17 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +ModifiableValue is used to represent values that can be changed by a pluggable widget client component and is passed only to [association properties](/apidocs-mxsdk/apidocs/pluggable-widgets-property
I think it should, also updated some other types as well

2022-04-19 09:17 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +The type the component receives for the association property depends on the allowed association types. If only references are allowed the component receives a `ReferenceValue` which is defined as `Mo
I agree, fixed

2022-04-20 11:44 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +### 4.4 ModifiableValue {#modifiable-value}
I like the new way. Changing the numbers should not be a problem.

2022-04-20 16:18 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +### 4.4 ModifiableValue {#modifiable-value}
Awesome, then we'll keep it like this :).

2022-04-20 16:18 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +The type the component receives for the association property depends on the allowed association types. If only references are allowed the component receives a `ReferenceValue` which is defined as `Mo
✨

2022-04-20 16:19 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +`status` is similar to the one exposed for `DynamicValue`. It indicates if the value's loading has finished and if loading was successful. Similarly to `DynamicValue`, `EditableValue` keeps returning
✨

2022-04-20 16:19 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +ModifiableValue is used to represent values that can be changed by a pluggable widget client component and is passed only to [association properties](/apidocs-mxsdk/apidocs/pluggable-widgets-property
I noticed, noice! ✨

2022-04-20 16:21 UTC, tamelbrun approved these changes

2022-04-25 10:39 UTC, ConnorLand approved these changes

2022-04-28 08:01 UTC, merged