Release notes for LM-134, LM-752 & LM-449
mendix/docs pull request #4485
Opened 2022-04-21 14:58 UTC by ajinkya-takle

Release notes for changes that were made as of part of LM-134, LM-752 & LM-449

2022-04-21 14:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=4485) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=4485) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=4485) it.</sub>

2022-04-22 06:54 UTC, MarkvanMents requested changes
Hi @ajinkya-takle ,
1. I don't see any updates to the documentation for https://docs.mendix.com/developerportal/operate/trends-v4/. I think that if there are new graphs, we should have them in the documentation and tell customers what they mean. For examples, are there any limits to the numbers or size of files which they can have on storage that they need to be aware of.
2. Can you sign the CLA - it isn't so important for Mendix employees, but means that it is clearer on our dashboard what needs to be done.

Can you let me know what is being done about updating the documentation?

2022-04-22 07:16 UTC, ajinkya-takle commented
Hi @MarkvanMents,
Thank you for reviewing & fine tuning the releasing notes for us.
For the new graphs that we want to add, here is the MR https://github.com/mendix/docs/pull/4323 that is already open. I see that you need the images for the new graphs. I will add the images on your comments shortly.

2022-04-22 08:44 UTC, MarkvanMents approved these changes

2022-04-22 08:44 UTC, merged