[NC-675] add onchange behavior to text area native widget
mendix/docs pull request #4487
Opened 2022-04-21 22:29 UTC by Ahmad-Elsayed

Feature is not released yet

2022-04-25 17:17 UTC, pratikgoyal9 requested changes

2022-04-25 17:17 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +This option will work as in previous versions of Studio Pro. Text Area will apply changes when a value is not the same as previously saved value in the database and one of the following conditions is
Will this option work with previous versions of Studio Pro? No, right?

2022-04-25 17:17 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* On enter key pressed: This will trigger on change and on enter key press events
On press of the enter key, no `onChangeBehavior` would be triggered in a text area. Instead, the user should be navigated to the next line in the same text area. So, user does not leave the current text area in this context. 

According to me, the user can only leave the textarea by pressing the tab key(in case of the web) or by tapping any other part of the screen except in the current text area. So, this event should be removed.

@jordanch @cjfhodges Would you like to add your two cents?

2022-04-25 17:17 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* Blurred: This will trigger on change and on leave events
I've no idea how this would work, where can I find and test the `Blurred` feature?

2022-04-26 07:58 UTC, jordanch commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* On enter key pressed: This will trigger on change and on enter key press events
Makes sense. Probably missed after copying from (text box)[https://github.com/mendix/docs/blob/4487/content/en/docs/refguide/modeling/pages/input-widgets/text-box.md].

2022-04-28 14:17 UTC, Ahmad-Elsayed commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* Blurred: This will trigger on change and on leave events
when you touch screen outside the input and the keyboard, the input shouldn't be active, keyboard should be dismissed and then the `onChange` event should be called if `apply changes` property is set to `when user leaves input field`

2022-04-29 07:54 UTC, pratikgoyal9 approved these changes

2022-04-29 07:55 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* Blurred: This will trigger on change and on leave events
Ah okay! Good to know that it's called a `Blurred` condition.

2022-04-29 07:56 UTC, pratikgoyal9 requested changes

2022-04-29 07:56 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +Text Area will apply changes when a value is not the same as previously saved value in the database and one of the following condition is met:
Since we removed the other condition, it should be like the below:

`Text Area will apply changes when a value is not the same as previously saved value in the database and the following condition is met:`

2022-04-29 08:51 UTC, pratikgoyal9 approved these changes
Good work @Ahmad-Elsayed 👍

2022-05-11 09:30 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +Text Area will apply changes when a value is not the same as previously saved value in the database and one of the following condition is met:
Fixed!

2022-05-11 12:57 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +This option will work as in previous versions of Studio Pro. Text Area will apply changes when a value is not the same as previously saved value in the database and one of the following conditions is
Fixed, should be resolved!

2022-05-11 12:57 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* On enter key pressed: This will trigger on change and on enter key press events
Fixed, should be resolved!

2022-05-11 12:57 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +* Blurred: This will trigger on change and on leave events
Fixed, should be resolved!

2022-05-19 11:52 UTC, ConnorLand approved these changes

2022-06-03 08:26 UTC, merged