[NC-591] Add autofocus option to TextBox and TextArea native widgets
mendix/docs pull request #4499
Opened 2022-04-26 11:05 UTC by Ahmad-Elsayed

WIP

2022-05-19 10:34 UTC, pratikgoyal9 requested changes

2022-05-19 10:34 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +If `true`,  the TextArea will be rendered focused and the device keyboard is opened.
It should be "text area"

2022-05-19 10:34 UTC, pratikgoyal9 commented on content/en/docs/refguide/modeling/pages/input-widgets/text-box.md
> +If `true`,  the Textbox will be rendered focused and the device keyboard is opened.
It should be "text box"

2022-05-19 10:37 UTC, Ahmad-Elsayed commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +If `true`,  the TextArea will be rendered focused and the device keyboard is opened.
done

2022-05-19 10:37 UTC, Ahmad-Elsayed commented on content/en/docs/refguide/modeling/pages/input-widgets/text-box.md
> +If `true`,  the Textbox will be rendered focused and the device keyboard is opened.
done

2022-05-19 10:38 UTC, Ahmad-Elsayed commented on content/en/docs/refguide/modeling/pages/input-widgets/text-area.md
> +If `true`,  the TextArea will be rendered focused and the device keyboard is opened.
V 9.15

2022-05-19 10:52 UTC, pratikgoyal9 approved these changes

2022-05-19 11:11 UTC, ConnorLand approved these changes

2022-06-28 07:25 UTC, ConnorLand approved these changes

2022-06-29 13:49 UTC, merged