Data validation and error handling for external entities
mendix/docs pull request #4523
Opened 2022-05-02 14:07 UTC by johannahemminger

https://mendix.atlassian.net/browse/TW-1643

2022-05-02 14:24 UTC, johannahemminger commented
@ezagroba can you check this out?

2022-05-03 09:18 UTC, johannahemminger commented
@joostverhoog Could you check this out? Thx

2022-05-13 12:12 UTC, joostverhoog requested changes

2022-05-13 12:12 UTC, joostverhoog commented on content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
> +You can [set up data validation](/howto/data-models/setting-up-data-validation/) to check on inserted or updated data between your apps. An insert validation microflow in the domain model of the clie
The page consumed-odata-service-requirements is intended to list the requirements that a Mendix app has on the service that is being consumed. I suggest that we write about how to validate incoming updates, inserts and deletes in /refguide/published-odata-resource/, and write about how to handle those validation errors in in /refguide/send-external-object/ and /refguide/delete-external-object/.

2022-05-13 12:12 UTC, joostverhoog commented on content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
> +{{< figure src="/attachments/refguide/modeling/integration/consumed-odata-service-requirements/validate-data-client-app.png" alt="client app validation" >}}
I think examples are better suited for the how-to section of the docs, not in the refguide. That's also the place where the relation between different features is better explained. Maybe we can turn this into a how-to?

2022-05-13 12:34 UTC, johannahemminger commented on content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
> +You can [set up data validation](/howto/data-models/setting-up-data-validation/) to check on inserted or updated data between your apps. An insert validation microflow in the domain model of the clie
Sounds good, I'll make those changes!

2022-05-13 12:38 UTC, johannahemminger commented on content/en/docs/refguide/modeling/integration/consumed-odata-services/consumed-odata-service-requirements.md
> +{{< figure src="/attachments/refguide/modeling/integration/consumed-odata-service-requirements/validate-data-client-app.png" alt="client app validation" >}}
Sure, I'll create a task to do that. Thanks for your input!

2022-06-08 12:39 UTC, merged