Doc for the Advanced Audit Trail UI module
mendix/docs pull request #4529
Opened 2022-05-03 11:59 UTC by Luyao-Zhang-1

2022-06-15 11:18 UTC, brfreekmx requested changes

2022-06-15 11:18 UTC, brfreekmx commented on content/en/docs/appstore/modules/advanced-audit-trail-ui.md
> +### 1.2 Solution Package
Can this paragraph be removed?

2022-06-15 11:18 UTC, brfreekmx commented on content/en/docs/appstore/modules/advanced-audit-trail-ui.md
> +To download and install the Advanced Audit Trail UI module in your app, follow the instructions in the [Importing Content from the App Explorer](/appstore/general/app-store-content/#import) section i
Can the "After the app service is installed" link to the Advanced Audit Trail App Service documentation?

2022-06-16 09:02 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/modules/advanced-audit-trail-ui.md
> +### 1.2 Solution Package
@brfreekmx I removed the paragraph about the solution package.

2022-06-16 09:07 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/modules/advanced-audit-trail-ui.md
> +To download and install the Advanced Audit Trail UI module in your app, follow the instructions in the [Importing Content from the App Explorer](/appstore/general/app-store-content/#import) section i
@brfreekmx I think `the app service` here is actually a mistake. It should be changed `the module`. The module here refers to the Advanced Audit Trail UI module.

2022-06-17 07:50 UTC, Luyao-Zhang-1 commented on content/en/docs/appstore/modules/advanced-audit-trail-ui.md
> +To download and install the Advanced Audit Trail UI module in your app, follow the instructions in the [Importing Content from the App Explorer](/appstore/general/app-store-content/#import) section i
@brfreekmx Added Advanced Trail Core to the Installation section as well.

2022-06-17 08:52 UTC, Luyao-Zhang-1 commented
The UI module doc is moved to the [same PR as the core module](https://github.com/mendix/docs/pull/4443), since the two docs will be released together. I will close this PR.

2022-06-17 08:52 UTC, closed without merging