Add link into every figure shortcode
mendix/docs pull request #4575
Opened 2022-05-13 12:30 UTC by NatasaKralj

The shortcode change adds the link parameter to every figure shortcode that doesn't contain it. This makes clicking on the image open it in a new tab.

2022-05-16 10:35 UTC, MarkvanMents requested changes

2022-05-16 10:35 UTC, MarkvanMents commented on layouts/shortcodes/figure.html
> +    {{- else -}}
Seems to be a bug in the way you are implementing the {{ else }}.
![image](https://user-images.githubusercontent.com/35492184/168574503-59e25c63-b83f-4096-b77f-f53b082fc8c8.png)
![image](https://user-images.githubusercontent.com/35492184/168574732-befbc1b7-bfc8-4106-87e3-f9269b4a787c.png)

Also, I think we should respect the `target` if someone has used it in the [figure shortcode](https://gohugo.io/content-management/shortcodes/#figure). Perhaps something like:
`target="{{ with .Get "target" }}{{ . }}{{ else }}_blank{{ end }}"`
Can we discuss?

2022-05-17 09:16 UTC, MarkvanMents commented on layouts/shortcodes/figure.html
> +    {{- end }} target="{{ with .Get "target" }}{{ . }}{{ else }}_blank{{ end }}"{{ with .Get "rel" }} rel="{{ . }}"{{ end }}></a>
`</a>` is in the wrong place. Image needs to be within the tags. <a><img></a>
But looking much better!
If you want to work on this before Friday, then do so.

2022-05-20 13:13 UTC, NatasaKralj commented on layouts/shortcodes/figure.html
> +    {{- end }} target="{{ with .Get "target" }}{{ . }}{{ else }}_blank{{ end }}"{{ with .Get "rel" }} rel="{{ . }}"{{ end }}></a>
Fixed, removed extra </a> tag.

2022-05-20 13:15 UTC, merged