Add documentation for latesthttpresponse in Send External Object action
mendix/docs pull request #4593
Opened 2022-05-19 09:02 UTC by osoykan

2022-05-19 09:55 UTC, joostverhoog requested changes

2022-05-19 09:55 UTC, joostverhoog commented on content/refguide/send-external-object.md
> +However, its `Content` attribute will be left empty in most cases to minimize memory usage.
Can we specify in which cases it's empty?

2022-05-19 09:55 UTC, joostverhoog commented on content/refguide/send-external-object.md
> +The `$latestHttpResponse` variable is of the [HttpResponse](http-request-and-response-entities#http-response) type. It is available after a **Send External Object** activity.
It's also available after the Delete External Object activity, right? Shouldn't we add documentation there?

2022-05-19 09:55 UTC, joostverhoog commented on content/refguide/send-external-object.md
> +## 3 Response Handling
It looks like this document repeats number 3 for Response Handling and Related now

2022-05-19 09:55 UTC, joostverhoog commented on content/refguide/send-external-object.md
> +* The **Response handling** is **Store in an HTTP response** and the call succeeded
Is this part of the Studio Pro UI now?

2022-05-19 10:46 UTC, osoykan commented on content/refguide/send-external-object.md
> +However, its `Content` attribute will be left empty in most cases to minimize memory usage.
I've checked it again to validate, it is always filled, so I'm deleting this part.

2022-05-19 10:56 UTC, osoykan commented on content/refguide/send-external-object.md
> +* The **Response handling** is **Store in an HTTP response** and the call succeeded
removed

2022-05-19 10:56 UTC, osoykan commented on content/refguide/send-external-object.md
> +## 3 Response Handling
changed

2022-05-19 10:57 UTC, osoykan commented on content/refguide/send-external-object.md
> +The `$latestHttpResponse` variable is of the [HttpResponse](http-request-and-response-entities#http-response) type. It is available after a **Send External Object** activity.
added

2022-05-19 11:17 UTC, joostverhoog requested changes

2022-05-19 11:17 UTC, joostverhoog commented on content/refguide/send-external-object.md
> +The `$latestHttpResponse` variable is of the [HttpResponse](http-request-and-response-entities#http-response) type. It is available after **Send External Object**, **Delete External Object** activiti
I expected a change in the page for delete external object as well, and no mention of that activity here.

2022-05-19 11:17 UTC, joostverhoog commented on content/refguide/send-external-object.md
> +This variable can be accessed from any microflow action in the scope.
Isn't it called a microflow _activity_ rather than a microflow _action_?

2022-05-19 12:23 UTC, osoykan commented on content/refguide/send-external-object.md
> +The `$latestHttpResponse` variable is of the [HttpResponse](http-request-and-response-entities#http-response) type. It is available after **Send External Object**, **Delete External Object** activiti
I see. But there is no page for delete external object as far as I searched in the docs.

2022-05-19 12:24 UTC, osoykan commented on content/refguide/send-external-object.md
> +This variable can be accessed from any microflow action in the scope.
addressed

2022-05-19 12:25 UTC, osoykan commented on content/refguide/send-external-object.md
> +The `$latestHttpResponse` variable is of the [HttpResponse](http-request-and-response-entities#http-response) type. It is available after **Send External Object**, **Delete External Object** activiti
Also removed `Delete External Object` addition from here.

2022-05-19 15:03 UTC, johannahemminger commented on content/refguide/send-external-object.md
> +The `$latestHttpResponse` variable is of the [HttpResponse](http-request-and-response-entities#http-response) type. It is available after **Send External Object**, **Delete External Object** activiti
https://docs.mendix.com/refguide/delete-external-object/ - do you mean this one?

2022-05-20 07:58 UTC, closed without merging

2022-05-20 08:00 UTC, osoykan commented
Please refer this PR: https://github.com/mendix/docs/pull/4596, this one is based on outdated development