re-added deploying-native-app
mendix/docs pull request #4657
Opened 2022-06-03 14:05 UTC by jdiehl

Updated structure

2022-06-03 16:36 UTC, jdiehl commented
@ConnorLand I have outlined the content for the mobile start page (/refguide/mobile/). Can you take a look and work some editorial magic?

2022-06-08 11:45 UTC, ConnorLand approved these changes

2022-06-08 11:46 UTC, ConnorLand commented
> @ConnorLand I have outlined the content for the mobile start page (/refguide/mobile/). Can you take a look and work some editorial magic?

It would be my pleasure. I will add my edits in this PR and then merge it.

2022-06-08 11:47 UTC, ConnorLand requested changes
I'll make some edits here and then merge into the working branch.

2022-06-21 08:09 UTC, ConnorLand commented on content/en/docs/refguide/mobile/_index.md
> +* Native Apps are styled using React Native
Comment for reference.

2022-06-21 12:56 UTC, ConnorLand approved these changes

2022-06-21 12:57 UTC, merged