Add link to figure
mendix/docs pull request #4703
Opened 2022-06-20 09:18 UTC by NatasaKralj

Figure shortcode currently sets any image src as a link, to be able to open the image in a new tab/browser on click. This does not play nice with any link that follows in `[{{< figure src="someImage.png" >}}](https:alinktosomepage)` format. A quick workaround is to insert link into figure, like this `[{{< figure src="someImage.png" link="https:alinktosomepage" >}}](https:alinktosomepage)`.

2022-06-20 09:27 UTC, MarkvanMents requested changes
Can we immediately simplify the links, rather than leaving the legacy link as well?

2022-06-20 09:27 UTC, MarkvanMents commented on content/en/docs/howto/general/install.md
> +[{{< figure src="/attachments/howto/general/install/download.png" link="https://marketplace.mendix.com/link/studiopro/" >}}](https://marketplace.mendix.com/link/studiopro/)
Can just be:
```suggestion
{{< figure src="/attachments/howto/general/install/download.png" link="https://marketplace.mendix.com/link/studiopro/" >}}
```
Any reason you want to keep the old method as well?

2022-06-20 11:13 UTC, NatasaKralj commented on content/en/docs/howto/general/install.md
> +[{{< figure src="/attachments/howto/general/install/download.png" link="https://marketplace.mendix.com/link/studiopro/" >}}](https://marketplace.mendix.com/link/studiopro/)
The suggestion is now applied to every edited link. No need for this to be a temporary fix, getting rid of the markdown link allows this to be the permanent solution. Thank you @MarkvanMents

2022-06-21 08:54 UTC, MarkvanMents approved these changes
Looks great.
Go for it.

2022-06-21 09:11 UTC, MarkvanMents requested changes
@NatasaKralj 
I've made four changes. Can you check that I've understood them correctly.
Didn't realize we used that construction so often! Need to make sure we have this improved format in the documentation.
Thanks for picking this up.
Once you have dealt with the comments, you can merge straight away.

2022-06-21 09:11 UTC, MarkvanMents commented on content/en/docs/refguide7/desktop-modeler/application-logic/microflows/_index.md
> +| {{< figure src="/attachments/refguide7/desktop-modeler/application-logic/microflows/16843951.png" >}} link="/refguide7/error-event/" | [Error Event](/refguide7/error-event/) | An error event define
```suggestion
| {{< figure src="/attachments/refguide7/desktop-modeler/application-logic/microflows/16843951.png" link="/refguide7/error-event/" >}}  | [Error Event](/refguide7/error-event/) | An error event defines a location where the microflow will stop and throw an error that occurred earlier. If you call a microflow, you may want to know whether any errors occurred within the microflow or not. |
```

2022-06-21 09:11 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/_index.md
> +| {{< figure src="/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/retrieve.png" alt="retrieve" link="/refguide/retrieve/" >}}](/refguide/retrieve/) | [Retrieve](/
```suggestion
| {{< figure src="/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/activities/retrieve.png" alt="retrieve" link="/refguide/retrieve/" >}} | [Retrieve](/refguide/retrieve/) | Gets one (or more) associated objects of another object. Furthermore, this activity can also get one or more objects directly from a database. |
```

2022-06-21 09:11 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/nanoflows/_index.md
> +| {{< figure src="/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/continue-event.png" alt="continue event" link="/refguide/continue-event/" >}}](/refguide/continu
```suggestion
| {{< figure src="/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/continue-event.png" alt="continue event" link="/refguide/continue-event/" >}} | [Continue event](/refguide/continue-event/) | Used to stop the current iteration of a loop and continue with the next iteration. Continue events can only be used inside a [loop](/refguide/loop/). |
```

2022-06-21 09:11 UTC, MarkvanMents commented on content/en/docs/refguide7/desktop-modeler/application-logic/common-elements/activities/_index.md
> +| {{< figure src="/attachments/refguide7/desktop-modeler/application-logic/common-elements/activities/918124.png" link="/refguide7/generate-document/" >}}](/refguide7/generate-document/) | [Generate
```suggestion
| {{< figure src="/attachments/refguide7/desktop-modeler/application-logic/common-elements/activities/918124.png" link="/refguide7/generate-document/" >}} | [Generate document](/refguide7/generate-document/) | Generate document can be used to create a document of a certain type based on a [template](/refguide7/document-templates/). |
```

2022-06-21 10:46 UTC, merged