Document mx check and mx show-version
mendix/docs pull request #4721
Opened 2022-06-22 12:28 UTC by mrseanryan

Document these mx commands which we released already:

- mx check
- mx show-version

note: for `check` the text mentions a feature that will be released in SP 9.16

2022-06-22 12:30 UTC, mrseanryan commented
@MarkvanMents ready for review

2022-06-23 08:35 UTC, MarkvanMents requested changes
Hi Sean (@mrseanryan )
I've reviewed the whole document, rather than just the changes.
If there is information which is only for Mx 9.16, then we can't release it until then. Should we take that out and put it into a separate PR so we can put this out now.
We should also be clear which commands work in which versions, so customers in 9.1 don't try something that only works in 9.12 and above.

Let me know what we can do here to get the information out to customers as soon as possible.
Mark

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +`mx convert [OPTIONS] INPUT`
mx check, surely.
```suggestion
`mx check [OPTIONS] INPUT`
```

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +### 3.3 mx create-project Command
Should this be deprecated and replaced with
`mx create-app`
?

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
>  | `mx create-project --app-name "MyFirstApp" --output-dir "C:/Projects/MyFirstApp"` | Creates an app named `MyFirstApp` in the *C:/Projects/MyFirstApp* folder using all the default parameters. |
The options here are quoted. In `mx convert` they are not quoted. Should we be consistent and always quote the parameters?

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +The `mx convert` command converts the app(s) MPK file(s) to a specific Studio Pro version. For example, if you are using the mx command-line tool for Mendix version 9.12.2.44241, then `mx convert` wi
Why does this work on the MPK file when all the others work on the MPR file?
I think this could cause confusion and errors.
Studio Pro also works on the MPR file when it does a conversion.

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +The `mx check` command checks the app MPR file for issues such as Errors, Warnings, Deprecations or Performance recommendations.
I assume this only works if the MPR file is the same version as mx.exe?
If so, I think we should say so.
And does this work for all versions of Mx9, or only from a particular release?

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +#### 3.3.2 Examples
Would be nice to have an example with a `sprintr-app-id` so customers can see the format of this.

We also don't use Sprintr in customer facing documentation, so can you think of a better name for this option? I assume that it isn't going to be the same as a Team Server app id?

2022-06-23 08:35 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +| `language-code` | Optional | The default language of the app. |
Is this really completely optional, or does it default to en-US?
What happens in Studio Pro if there is no default language set?

2022-06-23 12:21 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +The `mx convert` command converts the app(s) MPK file(s) to a specific Studio Pro version. For example, if you are using the mx command-line tool for Mendix version 9.12.2.44241, then `mx convert` wi
hm my understanding is that `show-version` and `check` are run on apps that are already in use on the user's machine (and any conversion has already been done). So they are in the 'extracted' state which has an MPR file.

Whereas `convert` is for some app that is not yet in use, and needs to be converted.
`convert` takes a MPK file, or else a folder.

If we want to change how this behaves, that would be some future work 🤔  not related to this PR.

2022-06-23 13:02 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +### 3.3 mx create-project Command
Possibly - that would be for SOLP team

2022-06-23 13:09 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +The `mx check` command checks the app MPR file for issues such as Errors, Warnings, Deprecations or Performance recommendations.
I will update.

notes:
- mx check == 9.10
- mx show-version == 9.4
- mx convert = (has always been in SP9)

future:
- mx check --performance ==  9.16

2022-06-23 13:12 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +#### 3.3.2 Examples
I believe `sprintr-app-id` is a Team Server app ID.

I will check  ...

2022-06-23 13:19 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +#### 3.3.2 Examples
yes they are the same.

The value is a GUID. 
When accessing the app portal (on sprintr OR on Team Server) it can be seen in the browser's URL

sprintr example:
https://sprintr.home.mendix.com/link/buzz/1a428ea7-b00e-4166-9b23-20b7bf88a70d

team server example:

https://teamserver.sprintr.com/1a428ea7-b00e-4166-9b23-20b7bf88a70d

2022-06-23 13:26 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +| `language-code` | Optional | The default language of the app. |
In the source code there is a hard-coded default `en_US`

2022-06-23 13:26 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +| `language-code` | Optional | The default language of the app. |
So, yes it really optional.

2022-06-23 13:28 UTC, mrseanryan commented
> Hi Sean (@mrseanryan ) I've reviewed the whole document, rather than just the changes. If there is information which is only for Mx 9.16, then we can't release it until then. Should we take that out and put it into a separate PR so we can put this out now. We should also be clear which commands work in which versions, so customers in 9.1 don't try something that only works in 9.12 and above.
> 
> Let me know what we can do here to get the information out to customers as soon as possible. Mark

Great!

I will split out the 9.16 specific items to a separate PR.

2022-06-23 14:00 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
>  | `mx create-project --app-name "MyFirstApp" --output-dir "C:/Projects/MyFirstApp"` | Creates an app named `MyFirstApp` in the *C:/Projects/MyFirstApp* folder using all the default parameters. |
hm normally the quoting is not needed.

so maybe it makes sense to remove the quotes ?

2022-06-23 14:00 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +### 3.3 mx create-project Command
(unless I can do in some future crafting ... )

2022-06-23 14:02 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
>  | `mx create-project --app-name "MyFirstApp" --output-dir "C:/Projects/MyFirstApp"` | Creates an app named `MyFirstApp` in the *C:/Projects/MyFirstApp* folder using all the default parameters. |
related: most of the commands use `Windows` folder separators like `\`
but `mx create-project` uses Unix style.

suggest: `mx create-project` text be changed to be consistent with the other commands

what do you think?

2022-06-23 14:10 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +`mx convert [OPTIONS] INPUT`
done

2022-06-23 14:10 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +The `mx check` command checks the app MPR file for issues such as Errors, Warnings, Deprecations or Performance recommendations.
done

2022-06-23 16:58 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +#### 3.3.2 Examples
done

2022-06-24 09:13 UTC, MarkvanMents requested changes
Hi Sean,
Thanks for your responses.
Can you just check my suggestion and update the quoted strings and directory paths. Then I can publish this.

Thanks for all your work.

2022-06-24 09:13 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +The `mx convert` command converts the app(s) MPK file(s) to a specific Studio Pro version. For example, if you are using the mx command-line tool for Mendix version 9.12.2.44241, then `mx convert` wi
Thanks for the explanation. I've changed the text to highlight more that it is MPKs and not MPRs. If we get lots of support calls I can add a big banner, but I'll leave it for now.

2022-06-24 09:13 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +| `language-code` | Optional | The default language of the app. |
I think putting en_US is more accurate. The first example shows that you don't need to put any options.
```suggestion
| `language-code` | en_US | The default language of the app. | 
```

2022-06-24 09:13 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
>  | `mx create-project --app-name "MyFirstApp" --output-dir "C:/Projects/MyFirstApp"` | Creates an app named `MyFirstApp` in the *C:/Projects/MyFirstApp* folder using all the default parameters. |
Great catch.
Yes, I think we should be consistent and use either all Windows style or all Unix style.
And perhaps remove the quotes - but I assume it will work if you quote directory paths with spaces. I think we can assume that customers know this.

2022-06-24 09:21 UTC, MarkvanMents requested changes
Hi - sorry another couple of suggestions.
I don't think we need to put versions on the functions which are available for all Mendix 9 versions, so i've suggested removing them.
Then, with the other suggestions, I think we can publish.

2022-06-24 09:21 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +### 3.2 mx convert Command [version 9+]
I think we can remove the version information as it is in all Mx 9 versions?
```suggestion
### 3.2 mx convert Command
```

2022-06-24 09:21 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool.md
> +### 3.3 mx create-project Command [version 9+]
```suggestion
### 3.3 mx create-project Command
```

2022-06-24 10:11 UTC, mrseanryan commented on content/en/docs/refguide/general/mx-command-line-tool.md
>  | `mx create-project --app-name "MyFirstApp" --output-dir "C:/Projects/MyFirstApp"` | Creates an app named `MyFirstApp` in the *C:/Projects/MyFirstApp* folder using all the default parameters. |
done

2022-06-24 10:12 UTC, mrseanryan commented
> Hi - sorry another couple of suggestions. I don't think we need to put versions on the functions which are available for all Mendix 9 versions, so i've suggested removing them. Then, with the other suggestions, I think we can publish.

done!

I think it is ready now, let me know if I missed anything.

2022-06-24 10:32 UTC, MarkvanMents approved these changes
Thanks Sean, @mrseanryan 
I'll publish this and then review the other one to see if it needs rebasing or anything.
Thanks for working with me.
Mark

2022-06-24 10:33 UTC, merged