WIP: Add how to for requesting generic permission
mendix/docs pull request #4722
Opened 2022-06-22 15:18 UTC by Ahmad-Elsayed

Generic permission should allow the users to request any available device permission.

2022-06-23 13:02 UTC, jordanch requested changes
Good job 👏

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +### 3.1 permission name
Nit: probably needs Sentence case

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +Keep in mind that the permission names are different for each platform, so for example if you need to request permission to access reading contacts, you will need to call the actions two times: one f
Nit: `iOS`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +|`NanoflowCommons.Enum_PermissionStatus.granted`|The permission is granted after requesting the user or it was already granted previously|
`...after requesting the user?` This sounds a bit strange. Can it be reworded? 
Maybe: after requesting permission from the user

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +This an example for requesting contact access permission for Android and IOS devices.
Nit: `iOS`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- You can get the running platform (Android or IOS) through using `Get device info` action from Native mobile section in the Toolbox.
Nit: `iOS`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- Then you can branch your nanoflow using a decision which check for the system name.
I suggest rewording this to:
`then you can branch your logic based on the current platform`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- Then for Android branch, you can use Generic permission action with a permission name of `READ_CONTACTS_ANDROID`.
I suggest `of e.g. <permission name>`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- For Ios branch, you can also use a generic permission action with a permission name of `CONTACTS_IOS`.
I suggest `of .e.g. <name>`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +## Deployment
Is this part describing deployment or native app building? IMO, it's more about building that deployment

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +To do that you can navigate to App permissions while using native ui builder and add the permissions you are using in your application for Ios and Android.
Nit: `Native Builder UI`

2022-06-23 13:02 UTC, jordanch commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +To do that you can navigate to App permissions while using native ui builder and add the permissions you are using in your application for Ios and Android.
Nit: `iOS`

2022-06-24 07:47 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +### 3.1 permission name
Done

2022-06-24 07:49 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +Keep in mind that the permission names are different for each platform, so for example if you need to request permission to access reading contacts, you will need to call the actions two times: one f
done

2022-06-24 07:50 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +|`NanoflowCommons.Enum_PermissionStatus.granted`|The permission is granted after requesting the user or it was already granted previously|
done

2022-06-24 07:50 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +This an example for requesting contact access permission for Android and IOS devices.
done

2022-06-24 07:50 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- You can get the running platform (Android or IOS) through using `Get device info` action from Native mobile section in the Toolbox.
done

2022-06-24 07:51 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- Then you can branch your nanoflow using a decision which check for the system name.
done

2022-06-24 07:52 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- Then for Android branch, you can use Generic permission action with a permission name of `READ_CONTACTS_ANDROID`.
done

2022-06-24 07:52 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +- For Ios branch, you can also use a generic permission action with a permission name of `CONTACTS_IOS`.
done

2022-06-24 07:54 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +To do that you can navigate to App permissions while using native ui builder and add the permissions you are using in your application for Ios and Android.
done

2022-06-24 08:03 UTC, Ahmad-Elsayed commented on content/en/docs/howto/mobile/native-mobile/implementation/use-generic-permission.md
> +## Deployment
done

2022-06-24 09:19 UTC, jordanch approved these changes

2022-07-14 14:52 UTC, pratikgoyal9 requested changes

2022-07-14 14:52 UTC, pratikgoyal9 commented on content/en/docs/appstore/modules/nanoflow-commons.md
> +| Permissions         | RequestGenericPermission     |
@Ahmad-Elsayed Should be part of "Native mobile"

2022-08-08 10:18 UTC, merged