Update Background Gradient styling refguide
mendix/docs pull request #4742
Opened 2022-06-28 13:36 UTC by UrazAkgultan

2022-06-29 10:57 UTC, ConnorLand approved these changes

2022-06-29 11:04 UTC, ConnorLand requested changes
Uraz will add a style property before we merge this

2022-06-30 11:00 UTC, Ahmad-Elsayed approved these changes

2022-07-08 13:27 UTC, pratikgoyal9 requested changes

2022-07-08 13:27 UTC, pratikgoyal9 commented on content/en/docs/refguide/mobile/designing-mobile-user-interfaces/native-styling-element-guide.md
> +| `angle` | | Line of direction. A value of 0 is equivalent to top; increasing values rotate the design clockwise. |
Would be nice to mention the values range as well. Takes a value from `0` to `360`

2022-07-11 12:27 UTC, pratikgoyal9 commented on content/en/docs/refguide/mobile/designing-mobile-user-interfaces/native-styling-element-guide.md
> +| `angle` | | Line of direction. A value of 0 is equivalent to top; increasing values rotate the design clockwise. |
Implemented and verified.

2022-07-11 13:09 UTC, pratikgoyal9 commented
Hi @ConnorLand This PR has been reviewed technically from Native-Content side. Once, you are ready to publish to master, you can do so. We would release the updated widget today.

2022-07-11 14:33 UTC, ConnorLand approved these changes

2022-07-11 14:35 UTC, merged