Added release notes for new operator release and updated the document…
mendix/docs pull request #4770
Opened 2022-07-05 07:33 UTC by Nidhi251289

…ation for startupProbe and terminationGracePeriodSeconds

2022-07-05 10:32 UTC, MarkvanMents requested changes
Hi Nidhi (@Nidhi251289)
I have proofread the documents - let me know if I've misunderstood anything.
I have also added a couple of places where I think we could point to further documentation to explain things.
Let me know if you have any questions.
Mark

PS - there were a lot of files called `.DS_Store` in the Pull Request. Not sure how they got there, but they aren't needed for our site so I've deleted them. Can you check that you aren't adding them back in if you make any more commits. Thanks.

2022-07-05 10:32 UTC, MarkvanMents commented on content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
> +* When connecting to the Development Portal, the Mendix Gateway Agent will now trust CAs specified through Custom TLS Trust
Can we put a link to where we mention "Custom TLS Trust" I can't find that phrase in our documentation.

2022-07-05 10:32 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +In this example, the application will have a maximum of 5 minutes (30 * 10 = 300s) to finish its startup. Once the startup probe has succeeded once, the liveness probe takes over to provide a fast re
I can't find anywhere that the `restartPolicy` is mentioned in our documentation. Can we add it to our documentation or link the the K8s documentation which covers it?

2022-07-05 10:32 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +A startupProbe should be used when the application in your container could take a significant amount of time to reach its normal operating state. Applications that would crash or throw an error if th
Should I be calling them "startupProbe" as in the setting, or would it be better to use natural language and say "startup probe" except when I am specifically talking about the YAML key?

2022-07-05 10:51 UTC, Nidhi251289 commented on content/en/docs/releasenotes/deployment/mendix-for-private-cloud.md
> +* When connecting to the Development Portal, the Mendix Gateway Agent will now trust CAs specified through Custom TLS Trust
https://docs.mendix.com/developerportal/deploy/private-cloud-cluster/#custom-tls is the link

2022-07-05 10:51 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +In this example, the application will have a maximum of 5 minutes (30 * 10 = 300s) to finish its startup. Once the startup probe has succeeded once, the liveness probe takes over to provide a fast re
ok. https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#restart-policy
We can add above link

2022-07-05 10:52 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +A startupProbe should be used when the application in your container could take a significant amount of time to reach its normal operating state. Applications that would crash or throw an error if th
if we are referring to yaml, then startupProbe
else, startup probe

2022-07-05 12:43 UTC, MarkvanMents requested changes
Hi Nidhi,
I've made the changes you suggest, but have one more question about the Operator Configuration Manifest.
Then I think we are done if you are happy with my changes.

2022-07-05 12:43 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +* `Liveness`, `readiness`, `startupProbe`, and `terminationGracePeriodSeconds` – these are used for all Mendix app deployments in the namespace — any changes made in the Deployments will be discarded
Two questions:

1. Shouldn't this be `runtimeLivenessProbe`, `runtimeReadinessProbe`, `runtimeStartupProbe`, and `runtimeTerminationGracePeriodSeconds` these are the values in the YAML
2. Does it make sense for the `runtimeStartupProbe` and `runtimeTerminationGracePeriodSeconds` in the deployment to be overwritten by the `OperatorConfiguration`? Surely, you want to be able to set the `startupProbe` and `terminationGracePeriodSeconds` for each app in the namespace, as indicated in the new documentation we have just added? Or are these values optional and the customer can use them if they want to set these values at the namespace level?

2022-07-05 13:04 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +* `Liveness`, `readiness`, `startupProbe`, and `terminationGracePeriodSeconds` – these are used for all Mendix app deployments in the namespace — any changes made in the Deployments will be discarded
In general, the above terms are known as Liveness`, `readiness`, `startupProbe`, and `terminationGracePeriodSeconds. The runtime term is used specifically in our CRDS.

The thing is normally the values are already set on namespace level. The above values are default values which will come into effect if the customer dont configure anything on the operator level.

2022-07-05 13:36 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +* `Liveness`, `readiness`, `startupProbe`, and `terminationGracePeriodSeconds` – these are used for all Mendix app deployments in the namespace — any changes made in the Deployments will be discarded
OK - I'll leave it for now. We can pick it up if customers have any questions later.
Thanks for the reply.

2022-07-05 13:36 UTC, MarkvanMents approved these changes

2022-07-13 07:37 UTC, MarkvanMents commented
Released 12 July.

2022-07-13 07:42 UTC, merged