Update explanation of app metrics
mendix/docs pull request #4799
Opened 2022-07-11 11:43 UTC by johannahemminger

https://mendix.slack.com/archives/C015ZNPFRPX/p1657186737783599

2022-07-11 11:48 UTC, johannahemminger commented
@MarkvanMents changing this explanation because of the confusion with business events, if you can take a look and let me know what you think.

2022-07-12 07:10 UTC, MarkvanMents requested changes
Looks good.
Have made one suggestion for a change, but you don't have to accept it and I don't have to approve it again before you merge.

2022-07-12 07:10 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
> +* **APPMETRICS_TARGET** – enables sending application runtime and custom business metrics to HTTP endpoints of different monitoring solutions, such as **InfluxDB**, while ignoring micrometer endpoint
Would it be better to have InfluxDB as a link rather than bold - it isn't a UX element nor a setting?

It looks OK - lacks some information for the novice user (i.e. me), but I think that anyone who wanted to use it would understand what is going on from what is written here.
```suggestion
* **APPMETRICS_TARGET** – enables sending application runtime and custom business metrics to HTTP endpoints of different monitoring solutions, such as [InfluxDB](https://www.influxdata.com/), while ignoring micrometer endpoints
```

2022-07-12 07:47 UTC, johannahemminger commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments-details.md
> +* **APPMETRICS_TARGET** – enables sending application runtime and custom business metrics to HTTP endpoints of different monitoring solutions, such as **InfluxDB**, while ignoring micrometer endpoint
Good suggestions, thanks @MarkvanMents . Will change and merge.

2022-07-12 07:53 UTC, merged