Tekton documentation updates.
mendix/docs pull request #4910
Opened 2022-08-12 07:59 UTC by walkline

2022-08-12 08:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=4910) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=4910) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=4910) it.</sub>

2022-08-12 08:49 UTC, Adam-Dupaski commented
@MarkvanMents note the base branch

2022-08-15 16:36 UTC, MarkvanMents requested changes
Hi Anton (@walkline )
I've made some changes.
For some reason it looks like the CLA hasn't been signed. Can you do that - makes it easier to spot which Pull Requests are really failing.
Let me know if you have any questions - otherwise I can merge this into the other PR.
Thanks for the contribution.

2022-08-16 13:27 UTC, MarkvanMents approved these changes

2022-08-16 13:28 UTC, merged