Add a draft on Validation Assist
mendix/docs pull request #4919
Opened 2022-08-15 14:24 UTC by MariaShaposhnikova

@amirap , please review the PR.

2022-09-06 18:28 UTC, shirvanoff requested changes

2022-09-06 18:28 UTC, shirvanoff commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +url: /refguide/mx-assist-page-bot/
@MariaShaposhnikova url should be '/refguide/validation-assist/'
Also, I believe, it would be better to remove all mentions of 'page bot' (you could align it with Amir).

2022-09-06 18:28 UTC, shirvanoff commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +tags: ["studio pro", "mendix assist", "AI", "assistant", "bot", "page bot", "validation bot", "validation"]
Instead of 'page bot' could you please use 'validation assist'?

2022-09-06 18:28 UTC, shirvanoff commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +The MxAssist Page Bot has the Validation Assist as part of it. [Validation rules](https://docs.mendix.com/refguide/validation-rules/) are conditions that should be satisfied before an object is commi
'The MxAssist Page Bot has the Validation Assist as part of it' could you please review it with Amir?

2022-09-06 18:28 UTC, shirvanoff commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +To enable the Validation Assist, open **Edit** > **Preferences** > the **Mendix Assist** tab > the **Page Bot** section > **Enable Validation Assist**. For more information, see [Preferences](/refgui
We hide this option and VA enabled by default

2022-09-06 18:28 UTC, shirvanoff commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +8. In the **Page Assist** dialog box, click **Open the microflow** to view the configured microflow:
The dialog title rename with 'Validation Assist' (instead of 'Page Assist')

2022-09-12 11:06 UTC, amirap commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +tags: ["studio pro", "mendix assist", "AI", "assistant", "bot", "page bot", "validation bot", "validation"]
Agreed. 
Also let's remove "AI", "page bot"
Also add "data validations", "field validation", "form validation"

2022-09-12 11:06 UTC, amirap commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +## 1 Introduction
The Validation Assist helps developers to build validation microflows in a more automated way using pre-built expressions. [Validation rules](https://docs.mendix.com/refguide/validation-rules/) are conditions that should be satisfied before an object is committed. There are different ways to [set up data validations](https://docs.mendix.com/howto/data-models/setting-up-data-validation/) in Mendix. Currently, building data validations in microflows is a manual and repetitive task.

2022-09-12 11:06 UTC, amirap commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +## 1 Introduction
I suggest the above text as the new introduction

2022-09-12 11:06 UTC, amirap commented on content/en/docs/refguide/modeling/mx-assist-studio-pro/mx-assist-page-bot.md
> +To enable the Validation Assist, open **Edit** > **Preferences** > the **Mendix Assist** tab > the **Page Bot** section > **Enable Validation Assist**. For more information, see [Preferences](/refgui
Yes. The whole paragraph can be deleted.

2022-09-30 08:34 UTC, merged