Migration from SVN to Git
mendix/docs pull request #4925
Opened 2022-08-16 13:16 UTC by MariaShaposhnikova

2022-08-16 13:17 UTC, MariaShaposhnikova commented
@tknippenberg , please review the PR.

2022-08-17 05:52 UTC, tknippenberg reviewed
> Creates a *local* commit: a set of changes with a message that you can jump back to. Changes are not submitted to the server, unless you check the **Push** checkbox.

consider changing to 

> Creates a *local* commit: a set of changes with a message that you can jump back to. Changes are not submitted to the server, unless the **Push** checkbox is checked.

2022-08-17 05:56 UTC, tknippenberg reviewed
These sentence feels a bit weird to me.
> Current version-controller is in Team Server SVN

Last part of the sentence feels weird.
> Inform your team members that they should commit their changes before migration has started not to lose their uncommitted changes.

2022-08-17 05:57 UTC, tknippenberg approved these changes
Overall looks good to me!

2022-08-17 05:58 UTC, tknippenberg commented
@grootjans , if you like you can take another look. I don't think it's necessary per se.

2022-08-17 11:09 UTC, MariaShaposhnikova commented
@tknippenberg , thank you for the review! I have rewritten sentences that you had comments on.

2022-08-17 11:09 UTC, MariaShaposhnikova commented
@Luyao-Zhang-1 , could you please take a look if the Developer Portal part looks good to you?

2022-08-17 14:25 UTC, Luyao-Zhang-1 approved these changes

2022-08-17 14:25 UTC, Luyao-Zhang-1 commented on content/en/docs/developerportal/collaborate/team-server/migrate-to-git.md
> +* App has maximum 100 revisions across all branches (we plan to increase this maximum the coming months)
```suggestion
* Your app has maximum 100 revisions across all branches (we plan to increase this maximum in the coming months)
```

2022-11-14 10:48 UTC, tknippenberg requested changes
The "(Optional) Migration scheduled" email won't be sent yet as we don't have scheduling options yet. Can this still be removed?

2022-11-14 13:47 UTC, MariaShaposhnikova commented
@tknippenberg , sure, I've delete this information.

2022-11-21 13:11 UTC, merged