Add documentation for linked association properties
mendix/docs pull request #4945
Opened 2022-08-19 13:17 UTC by legio-vi-ferrata

TODO

2022-08-19 13:21 UTC, ConnorLand commented
Hi @legio-vi-ferrata . Is this API doc update associated with a future release date?

2022-08-19 13:47 UTC, legio-vi-ferrata commented
Hello @ConnorLand, yes, this is the documentation additions and updates for a new feature (Linked Association Properties) to be released with 9.17.

2022-08-19 14:06 UTC, tamelbrun requested changes
First review pass complete :)

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    myAssociationReferenceSet: ListAssociationValue<ObjectItem[]>;
This should be `ListReferenceValue` and `ListReferenceSetValue`, the types we actually generate in the pluggable widget tools.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Some examples of builder functions are `equals`, `greaterThan`, `lessThanOrEqual` for filtering on `DateTime` or `Decimal` attributes. Functions like `startsWith`, `contains` are useful for filtering
This is incorrect: `equals` and `notEquals` are also available for reference sets, but only for comparison with `empty()`.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    const filterCond = contains(association(this.props.myAssociationReference.id), literal([objectItem1, objectItem2]));
This should be referring to `this.props.myAssociationReferenceSet`.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
`empty()` is not actually used in this example, but it might be a good idea to add that. At the same time, `contains` is missing from this import.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Similarly, to apply a condition so that only the objects that are associated with at least the first two objects that are brought by the selectable objects datasource will be returned:
This sentence is very complicated to read. I would suggest `that are brought by` -> `from` and maybe also `so that only ... will be returned` -> `to match only ...`. (The latter would also apply to the previous sentence on line 258.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In some use cases it is necessary to apply more complex filtering conditions. For example if a use case requires fetching only items where `myAttributeString` starts with `"B"` and `myAttributeBoolea
Given that the other props are referred to by name, let's do the same for the association property: "...and `myAssociationReference` is associated with another object" or something to that effect.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +This allows the client component to access associated values of individual items from a `ListValue`. `ListReferenceValue` and `ListReferenceSetValue` are both objects and their definition are as foll
definition -> definitions

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +  get: (item: ObjectItem) => DynamicValue<T>; // NOTE: DynamicValue obtained from ListAssociationValue always readonly
The `NOTE:` is unnecessary as `DynamicValue` - unlike `EditableValue` - is _always_ read-only.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +{{% /alert %}}
This warning is not necessary, for the same reason: `DynamicValue` is _always_ read-only.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
1. Lost -> List
2. The references to type `<T>` are inaccurate. In the case of associations, the generated type is either `ListReferenceValue` (which always produces `DynamicValue<ObjectItem>`), `ListReferenceSetValue` (which always produces `DynamicValue<ObjectItem[]>`) or `ListReferenceValue | ListReferenceSetValue` (which must be discriminated first using the `type` property).

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +If you want to access the individual attributes of this associated item, you can use an attribute property. Refer to [Obtaining Attribute Value section](/apidocs-mxsdk/apidocs/pluggable-widgets-clien
We should add "...attribute property _linked to the selectable objects data source and pass the associated item to it_" (or something to that effect).

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +[Association](/apidocs-mxsdk/apidocs/pluggable-widgets-property-types/#association) property determines which association types could be configured for that property. For example a property may allow
determines -> defines
may allow -> may be configured to allow

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
An `else if` is not a good example, as it will trigger an ESLint warning. (After checking `type === "Reference"`, the type of the `type` property is narrowed to `"ReferenceSet"` and the second check is flagged as always true. We can do three things: convert it to a switch, convert it to two separate ifs, or simply remove the second check (which might be confusing at first glance but compile-accurate).

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
I would put this in a separate alert box.

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
🎄 Let's also change this "Datasource property" into a link, while we're at it :).

2022-08-19 14:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
As previously suggested, let's add the "The ability to link an association property..." alert box here as well.

2022-08-19 14:23 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Some examples of builder functions are `equals`, `greaterThan`, `lessThanOrEqual` for filtering on `DateTime` or `Decimal` attributes. Functions like `startsWith`, `contains` are useful for filtering
Do you think I should include that information as well? I think this is just a paragraph that includes some examples, not an exhaustive list of all functions. Therefore; `Filtering based on associations is also possible. For example, you can use equals with references and contains with reference sets.` would be my attempt at fixing this. What do you think?

2022-08-19 14:44 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +{{% /alert %}}
Complete removal or just the DynamicValue part?

2022-08-19 15:00 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +If you want to access the individual attributes of this associated item, you can use an attribute property. Refer to [Obtaining Attribute Value section](/apidocs-mxsdk/apidocs/pluggable-widgets-clien
> If you want to access the individual attribute **values** of this associated ~item~ **object**, you can use an > attribute property linked to the selectable objects data source and pass the associated ~item~ **object** to it using its get function.

What do you think?

2022-08-19 15:01 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +[Association](/apidocs-mxsdk/apidocs/pluggable-widgets-property-types/#association) property determines which association types could be configured for that property. For example a property may allow
Should I fix those for the Attribute part as well?

2022-08-19 15:03 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
I guess the same for Attribute part, as well?

2022-08-19 15:14 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Some examples of builder functions are `equals`, `greaterThan`, `lessThanOrEqual` for filtering on `DateTime` or `Decimal` attributes. Functions like `startsWith`, `contains` are useful for filtering
Mentioning a few examples instead of everything would indeed be a good alternative. My main issue was that the part about `contains` being the only function available for reference sets was not just an example, it was a lie ;).

2022-08-19 15:16 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +[Association](/apidocs-mxsdk/apidocs/pluggable-widgets-property-types/#association) property determines which association types could be configured for that property. For example a property may allow
Ah, it was adapted from there? Yeah, let's take this opportunity to make that better as well 🎄

2022-08-19 15:17 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +{{% /alert %}}
Complete removal, the entire warning makes no sense here. It was only necessary for attributes because there you were getting an `EditableValue` that was not actually ever editable. _That_ required a warning :).

2022-08-19 15:21 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +If you want to access the individual attributes of this associated item, you can use an attribute property. Refer to [Obtaining Attribute Value section](/apidocs-mxsdk/apidocs/pluggable-widgets-clien
I think the reference to the `get()` function is a bit overkill, that's why we're referring to the `[Obtaining Attribute Value section]` for the details. I don't have a strong preference between `object` and `item`,  but the previous sentence uses associated _object_, so that would make it more consistent.

2022-08-19 15:23 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
Attribute properties don't have a `selectableObjects` attribute in the XML, so no ;).

2022-08-19 15:33 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
Yeah, I meant data sources in general and yeah, it would be even nicer if we did it for all properties not just Attribute. I'll proceed with that.

2022-08-19 17:13 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    myAssociationReferenceSet: ListAssociationValue<ObjectItem[]>;
Done.

2022-08-19 17:14 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Some examples of builder functions are `equals`, `greaterThan`, `lessThanOrEqual` for filtering on `DateTime` or `Decimal` attributes. Functions like `startsWith`, `contains` are useful for filtering
Done.

2022-08-19 17:14 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    const filterCond = contains(association(this.props.myAssociationReference.id), literal([objectItem1, objectItem2]));
Done.

2022-08-19 17:15 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
Partially done. I added contains. More on using empty() in the example later.

2022-08-19 17:16 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Similarly, to apply a condition so that only the objects that are associated with at least the first two objects that are brought by the selectable objects datasource will be returned:
Done for both parts.

2022-08-19 17:17 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In some use cases it is necessary to apply more complex filtering conditions. For example if a use case requires fetching only items where `myAttributeString` starts with `"B"` and `myAttributeBoolea
Done.

2022-08-19 17:17 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +This allows the client component to access associated values of individual items from a `ListValue`. `ListReferenceValue` and `ListReferenceSetValue` are both objects and their definition are as foll
Done.

2022-08-19 17:17 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +  get: (item: ObjectItem) => DynamicValue<T>; // NOTE: DynamicValue obtained from ListAssociationValue always readonly
Done.

2022-08-19 17:18 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +{{% /alert %}}
Done.

2022-08-19 17:18 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
Partially done. I fixed the type. More on `<T>` later.

2022-08-19 17:20 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +If you want to access the individual attributes of this associated item, you can use an attribute property. Refer to [Obtaining Attribute Value section](/apidocs-mxsdk/apidocs/pluggable-widgets-clien
Done.

2022-08-19 17:21 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +[Association](/apidocs-mxsdk/apidocs/pluggable-widgets-property-types/#association) property determines which association types could be configured for that property. For example a property may allow
Done for both parts.

2022-08-19 17:21 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
Done.

2022-08-19 17:23 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
Done and I **also** made a small adjustment for the description of selectableObjects.

2022-08-22 11:39 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Some examples of builder functions are `equals`, `greaterThan`, `lessThanOrEqual` for filtering on `DateTime` or `Decimal` attributes. Functions like `startsWith`, `contains` are useful for filtering
👍🏻

2022-08-22 11:41 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    const filterCond = contains(association(this.props.myAssociationReference.id), literal([objectItem1, objectItem2]));
The reference (no pun intended) on line 278 is still wrong :).

2022-08-22 11:42 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    myAssociationReferenceSet: ListAssociationValue<ObjectItem[]>;
👍🏻

2022-08-22 11:45 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Similarly, to apply a condition so that only the objects that are associated with at least the first two objects that are brought by the selectable objects datasource will be returned:
:+1:

2022-08-22 11:46 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In some use cases it is necessary to apply more complex filtering conditions. For example if a use case requires fetching only items where `myAttributeString` starts with `"B"` and `myAttributeBoolea
Now that we're at it, let's fix the grammar of those last two sentences (both here and in their original location):
_Note that checks for the `filterable` flag have been omitted for simplicity. Real widgets should always take the `filterable` flag into account._

2022-08-22 11:47 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +This allows the client component to access associated values of individual items from a `ListValue`. `ListReferenceValue` and `ListReferenceSetValue` are both objects and their definition are as foll
:+1:

2022-08-22 11:48 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +  get: (item: ObjectItem) => DynamicValue<T>; // NOTE: DynamicValue obtained from ListAssociationValue always readonly
:+1:

2022-08-22 11:48 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +{{% /alert %}}
👍🏻

2022-08-22 11:49 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +If you want to access the individual attributes of this associated item, you can use an attribute property. Refer to [Obtaining Attribute Value section](/apidocs-mxsdk/apidocs/pluggable-widgets-clien
👍🏻

2022-08-22 11:49 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +[Association](/apidocs-mxsdk/apidocs/pluggable-widgets-property-types/#association) property determines which association types could be configured for that property. For example a property may allow
:+1:

2022-08-22 11:50 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
Now that it has its own alert box, remove the "And" :)

2022-08-22 11:57 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
I noticed an existing typo in the description for `dataSource` for the `widgets` property:
```Specifies the path to a [`datasource`](#datasource) property linked to this widget's property```
That apostrophe is wrong, it should be _widgets_ (plural). Let's clean that up as well :).

2022-08-23 07:52 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
How about, simply `console.log(this.props.myAssociationOnDatasource.type)`?

2022-08-23 08:02 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    const filterCond = contains(association(this.props.myAssociationReference.id), literal([objectItem1, objectItem2]));
Done. 🤦

2022-08-23 08:06 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
We have an example with empty, in the one immediately above this. Do you mean that I should also include an empty check in this specific example? (This example demonstrates reference sets and it uses contains. Isn't an empty check redundant for this example?)

2022-08-23 08:08 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In some use cases it is necessary to apply more complex filtering conditions. For example if a use case requires fetching only items where `myAttributeString` starts with `"B"` and `myAttributeBoolea
Done. I also fixed some other `filterable` mentions that lacked the article 'the'. But this section is under ListValue. It does not have association and attribute counterparts. Therefore I am not sure what you mean by 'original location'?

2022-08-23 08:09 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
Done. 🤦‍♂️

2022-08-23 08:10 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
I noticed this 'and' when I first looked at your comment and pushed without fixing it. 🤦‍♂️

2022-08-23 08:11 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
Oh yeah... This is an awesome finding. :) Fixed it.

2022-08-23 08:11 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
The same version annotation you mean?

2022-08-23 09:49 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
I was considering it, especially because I'm worried about the discoverability of `equals/notEquals(empty())` for reference sets if it is not mentioned anywhere in the examples. At the same time, I think it would make these simple examples too complicated.

Let's add an `equals(empty())` filter for reference sets to the Advanced Filtering section instead, it already has a similar filter for references.

(And remove `empty` from the imports here, then. :))

2022-08-23 09:53 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In some use cases it is necessary to apply more complex filtering conditions. For example if a use case requires fetching only items where `myAttributeString` starts with `"B"` and `myAttributeBoolea
I think that at first glance the references for `filterable` looked more similar to me than they actually were :P. But yeah, my intent was to fix the articles everywhere 👍🏻.

2022-08-23 09:54 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
That would completely defeat the purpose of showing the discriminated union (and subsequent type narrowing) at work.

2022-08-23 09:54 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
👍🏻

2022-08-23 09:56 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
Did you also put the code formatting around it? I don't see it in the current diff.

2022-08-23 09:57 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
Yes, the one that no longer starts with And ;)

2022-08-23 10:16 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
I pushed a "slightly more liberal" new version for describing this.

2022-08-23 10:22 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
Then, I am inclined towards simply removing the second check and perhaps indicating the obvious (narrowing down of type) in a comment perhaps? (Below is an example.) What do you say?

`
if (this.props.myAssociationOnDatasource.type === "Reference") {
    console.log("Reference association");
} else {
    // TypeScript will narrow it down to "ReferenceSet" the type property is NOT "Reference"
    console.log("ReferenceSet association");
}
`

switch and two separate ifs seems sub-optimal to me.

2022-08-23 10:29 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
Fixed: I was inclined to put it right after the heading at first (similar to Attribute Property) but there is another annotation before the end of the section and I placed our addition next to that.

2022-08-23 10:33 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
Oh, sorry. When I first read your comment, I thought by `code formatting` you meant adding it to a spell check dictionary or something. 🤦‍♂️ I added the code formatting now. (Assuming I understood correctly this time: You just meant to make it like this: `code formatting`.)

2022-08-23 11:01 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
I would avoid the word "property" (ambiguous in this context), simply "type" will suffice. But otherwise, I think this is indeed the most elegant solution.

2022-08-23 11:09 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
In general, I think it would better to place it right after the paragraph that mentions the version-specific feature (`association` in this case), so that people won't accidentally overlook this. On the other hand, this is a relatively small section. @ConnorLand, what do you think?

2022-08-23 11:11 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
That is `indeed` what I `meant` :).

2022-08-23 11:31 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
The current sentence has become a long-winding sequence of commas and parentheses. I would propose the following simplified version:

> ```In order to work with an object or objects that are associated with a particular item returned by `ListValue`, first an instance of `DynamicValue<ObjectItem>` (for `ListReferenceValue`) or `DynamicValue<ObjectItem[]>` (for `ListReferenceSetValue`) should be obtained by calling `get` with the item. If the association property has been configured to allow both types of associations, the type of the property is defined as `ListReferenceValue | ListReferenceSetValue` and a check on its `type` should be done to narrow down the type.```

2022-08-23 11:35 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
I just spotted this sentence:
_"It is possible to determine type of association by checking `type` field on a property."_
-> _"It is possible to determine the type of association by checking the `type` field on an association property."_

2022-08-23 11:36 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
And I would add a comma after "For example" here:
_"For example a property may allow associations of type `Reference` and not `ReferenceSet`."_

2022-08-23 12:20 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
> I would avoid the word "property" (ambiguous in this context), simply "type" will suffice. But otherwise, I think this is indeed the most elegant solution.
> 
> (And maybe the ALL CAPS on NOT is a bit overkill. :))

My new proposal: TypeScript will narrow it down to "ReferenceSet" when the type ~property~ _field_ is not _equal to_ "Reference"

2022-08-23 12:36 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
> I just spotted this sentence: _"It is possible to determine type of association by checking `type` field on a property."_ -> _"It is possible to determine the type of association by checking the `type` field on an association property."_
> 
> (Edit: maybe we should also add something like "This is useful if the property has been configured to allow both references and reference sets.")

**Summary of Proposals:** Some small additions and also doing the same thing for the same part in Attribute Property.

**Proposal 1:** 
"For example a property may be configured to allow attributes of type `String` and `Integer` in order to present progress."
->
"For example, _an attribute_ property may be configured to allow attributes of type `String` and `Integer` in order to present progress."

**Proposal 2:**
"It is possible to determine type of attribute by checking `type` field on a property."
->
"It is possible to determine _the_ type of attribute by checking _the_ `type` field on _an attribute_ property."

**Proposal 3:**
"For example a property may allow associations of type `Reference` and not `ReferenceSet`."
->
"For example, _an association_ property may _be configured to_ allow associations of type `Reference` and not `ReferenceSet`."

**Proposal 4:**
"It is possible to determine type of association by checking `type` field on a property."
->
"It is possible to determine _the_ type of association by checking _the_ `type` field on _an association_ property. This is useful if the property has been configured to allow both references and reference sets."

2022-08-23 12:45 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
I think putting it right after the paragraph that mentions the feature is a good practice. Sometimes it leads to duplicated alert boxes, but as long as we keep the alert boxes short it is ok (and a best practice).

2022-08-23 13:02 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
We can do it. Which word or words should have the anchor, or should I add something like "See Association Type for more information."?

2022-08-23 13:06 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
Would you like me to relocate the existing alert box to the top of the section as well? (Right after the heading.)

2022-08-23 13:24 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
Yes, I think all alert boxes that just pertain generically to a property (like "This prop was introduced in version X" or "the ability to do x in y was introduced in version Y") should go right after the heading at the top of the section.

2022-08-23 13:31 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    myAssociationReferenceSet: ListAssociationValue<ObjectItem[]>;
Resolved this conversation.

2022-08-23 13:31 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Some examples of builder functions are `equals`, `greaterThan`, `lessThanOrEqual` for filtering on `DateTime` or `Decimal` attributes. Functions like `startsWith`, `contains` are useful for filtering
Resolved this conversation.

2022-08-23 13:31 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Similarly, to apply a condition so that only the objects that are associated with at least the first two objects that are brought by the selectable objects datasource will be returned:
Resolved this conversation.

2022-08-23 13:31 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +[Association](/apidocs-mxsdk/apidocs/pluggable-widgets-property-types/#association) property determines which association types could be configured for that property. For example a property may allow
Resolved this conversation.

2022-08-23 13:31 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +And the ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
Resolved this conversation.

2022-08-23 13:32 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
> My new proposal: TypeScript will narrow it down to "ReferenceSet" when the type ~property~ _field_ is not _equal to_ "Reference"

"Field" is not really JS/TS terminology. Why not drop it altogether? "Type" by itself is perfectly clear in this context.

2022-08-23 13:34 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
Proposal 1-4 seem fine to me.
On a side note: you need to be very careful, it looks like you're force-pushing away commits added by Connor. Did you use force-with-lease?

2022-08-23 13:40 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
I meant that the _Association Type_ section currently does not have an anchor/hashtag that we can link to. I think a separate sentence is more clear; if I recall correctly, we do this in other places as well.

2022-08-23 13:59 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
The existing alert box is not about a version, actually:

> Only list datasources are supported, therefore specifying `isList="true"` is required.

To me, this alert box is more about a platform limitation, not generically applying to all properties. But, having one alert box at the top of the section and one below seems sub-optimal to me.

2022-08-23 14:02 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
Ah... that's what I was afraid of... :(

2022-08-23 14:16 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
Right, so please just put one (perhaps at the top).

2022-08-23 14:51 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
**I propose:** In some use cases it is necessary to apply more complex filtering conditions. For example if a use case requires fetching only items where `myAttributeString` starts with `"B"` and `myAttributeBoolean` is set to `true`, or items where ~`myAttributeNumber` is greater than `10` and~ `myAssociationReference` is associated with another object _while `myAssociationReferenceSet` is not associated with other objects; meaning objects that has at least one singular association but no multiple associations._ In order to construct such a condition, special filter builders `and` and `or` have to be used. The following code sample shows how to use them. Note that checks for the `filterable` flag have been omitted for simplicity. Real widgets should always take the `filterable` flag into account.

```ts
import { attribute, association, literal, startsWith, equals, greaterThan, and, or } from "mendix/filters/builders";

// in the widget code
if (/* check that all properties are filterable */) {
    const filterCond = or(
        and(
            startsWith(attribute(this.props.myAttributeString.id), literal("B")),
            equals(attribute(this.props.myAttributeBoolean.id), literal(true))
        ),
        and(
            // REMOVING THIS: greaterThan(attribute(this.props.myAttributeNumber.id), literal(10)),
            notEquals(association(this.props.myAssociationReference.id), empty()),
            // ADDING THIS:
            equals(association(this.props.myAssociationReferenceSet.id), empty())
        )
    );
    this.props.myDataSource.setFilter(filterCond);
} else {
    console.log("Some attribute is not filterable");
}
```

2022-08-23 14:53 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
A complex filter made of two attribute components, two association components? That's why I removed the greaterThan filter but we can carry it over to the attribute group as well?

2022-08-23 15:00 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
We're dealing with two different types of alert boxes here: one is a warning about a limitation of data source properties in general, the other is specifically about the version in which `association` was added (which would go right after the paragraph which mentions `association`). Since the limitation is enforced by the XML validation and therefore impossible to overlook, I think its existing location at the bottom of the section is preferable.

2022-08-23 15:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
I don't see a reason to remove anything from the filter conditions, it's an advanced filter after all. And I think that _"; meaning objects... etc."_ only introduces clutter and confusion, I would remove it.

2022-08-23 15:12 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with the associated object of a particular item of a `ListValue` first an instance of `DynamicValue<T>` should be obtained by calling `ListReferenceValue.get` or `LostReferenceSetVal
Done.

2022-08-23 15:14 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
All done. (@ConnorLand, sorry again; I promise to be more careful next time.)

2022-08-23 15:14 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
Done.

2022-08-23 15:22 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
No reason programmatically but we are describing the filter in the paragraph above it. The sentence becomes weirder to me as we add stuff to it. But I can easily roll that back, of course.

2022-08-23 15:26 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
Done.

2022-08-23 15:31 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
The info box about `association` is now _before_ the paragraph that mentions it, which feels really counter-intuitive to me.

2022-08-23 15:43 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
You meant, placing the box after the paragraph that mentions linking with other attributes.
If so, it should be done now.

2022-08-24 11:00 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +import { association, literal, notEquals, empty } from "mendix/filters/builders";
👍🏻

2022-08-24 11:04 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +} else if (this.props.myAssociationOnDatasource.type === "ReferenceSet") {
Alright, I think I can live with it 👍🏻.

2022-08-24 11:05 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `selectableObjects` | Yes      | Property Path  | The path to a Datasource property that will provide selectable objects for the association                          |
👍🏻

2022-08-24 11:05 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The datasource property allows widgets to work with object lists. The client component will receive value prop of type [`ListValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#
👍🏻

2022-08-24 11:06 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +    const filterCond = contains(association(this.props.myAssociationReference.id), literal([objectItem1, objectItem2]));
👍🏻

2022-08-24 13:24 UTC, ConnorLand commented
Is this commit of mine correct? It's the one selectable object's data source right? https://github.com/mendix/docs/pull/4945/commits/f9c1bfbddd69d0086499b359edc9ca3ad798a713

2022-08-24 15:04 UTC, tamelbrun commented
> Is this commit of mine correct? It's the one selectable object's data source right? [f9c1bfb](https://github.com/mendix/docs/commit/f9c1bfbddd69d0086499b359edc9ca3ad798a713)

The plural was correct: the selectable objects data source is defined using the `selectableObjects` attribute of the association property.

2022-08-24 15:09 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +The optional `universe` field represents an attribute's possible array values. For more information, see the `universe` field of [EditableValue](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis/#
The previous version, "an array of possible values of an attribute", was correct. An attribute does not have array values :). One small improvement on this would be "an array of possible values **for** an attribute".

2022-08-24 15:20 UTC, tamelbrun requested changes

2022-08-24 15:20 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with an object or objects with a particular item returned by `ListValue`, first an instance of `DynamicValue<ObjectItem>` (for `ListReferenceValue`) or `DynamicValue<ObjectItem[]>` (
The removed phrase "that are associated with" is necessary for this statement to be correct, as the association property deals with associations between objects.

2022-08-29 09:24 UTC, ConnorLand approved these changes

2022-08-29 09:28 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +The optional `universe` field represents an attribute's possible array values. For more information, see the `universe` field of [EditableValue](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis/#
Done

2022-08-29 09:29 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +In order to work with an object or objects with a particular item returned by `ListValue`, first an instance of `DynamicValue<ObjectItem>` (for `ListReferenceValue`) or `DynamicValue<ObjectItem[]>` (
Corrected

2022-08-29 13:37 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Similarly, code like this can apply a condition to match only the objects that are associated with at least the first two objects from the selectable objects' data source:
I think this term is more correct as "selectable objects data source" or even simply `selectableObjects`. Technically, this "selectable objects data source" is defined in the XML, just like any other `datasource` (meaning there is no separate property `type` like `selectableObjectsDatasource`, just `datasource`) and while, it is correct in a sense that this `datasource` belongs to the `selectableObjects`; in the rest of our documentation where this is being referred to, we just use the nominal form (not possessive) "selectable objects data source". And I think the `datasource` itself is technically owned by the widget, not `selectableObjects` attribute that it is linked to.

Also of note, the difficulty regarding one of our most frequently used terms: `datasource`. Codebase-wise it is currently being referred to as `datasource` (depending on where in code it is involved with, either as `datasource` or as `dataSource`)  but actually as a technical concept in Mendix platform, in English, we refer to it as data source. (It should be written as two words.)

@alihcsumer @mlaponder @tamelbrun, would you agree?

2022-08-29 14:00 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +If a `dataSource` attribute is not specified the client will receive a `ReferenceValue` for references (singular references), possibly a `ReferenceSetValue` for reference sets (multiple references),
I think this should be just or:

> The client will receive, `ReferenceValue` ... or `ReferenceSetValue` ... or a union of them.

That should be the idea and the correct statement. Because the supplied value (depending on how the widget is defined in its XML definition file) is exclusive among those three options. It cannot be `ReferenceValue` and `ReferenceSetValue`, it will be either one of those or a (`TypeScript`) union like this: `ReferenceValue | ReferenceSetValue`

And also, it is not actually client that is receiving the prop (and therefore the mentioned values) but the **client component** of a pluggable widget which is essentially a React component. (The client reads the XML and handles instantiation of the properties per widget and supplies them to the widgets as React props.) We can adjust this, too, I guess, while we are at it, if you guys also agree.

2022-08-30 11:53 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +Similarly, code like this can apply a condition to match only the objects that are associated with at least the first two objects from the selectable objects' data source:
@ConnorLand I agree with @legio-vi-ferrata here, I don't think the apostrophe is needed here. imo if the apostrophe is dropped we are good to go here.

2022-08-30 11:57 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +If a `dataSource` attribute is not specified the client will receive a `ReferenceValue` for references (singular references), possibly a `ReferenceSetValue` for reference sets (multiple references),
@ConnorLand I agree also with @legio-vi-ferrata that just a `or` would be better. I think we should go with that suggestion.

2022-08-30 12:20 UTC, ConnorLand commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +If a `dataSource` attribute is not specified the client will receive a `ReferenceValue` for references (singular references), possibly a `ReferenceSetValue` for reference sets (multiple references),
I've changed the language per the suggestion

2022-08-31 11:49 UTC, merged