Kk proofreading deployment2
mendix/docs pull request #4953
Opened 2022-08-22 13:50 UTC by katarzyna-koltun-mx

@Adam-Dupaski, @MarkvanMents I proofread the second article in the Deployment batch. Can you let me know if you have any comments?

2022-08-26 13:18 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Activity
"Custom Domains"

I also see "Access Restriction Profiles" for Technical Writing v4 app - to be listed here?

2022-08-26 13:18 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Services**
"Services" tab has "Services" and "Activity" sections - to be listed as sub-items?

2022-08-26 13:19 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +{{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/environments/deployment-package.png" alt="The Deployment Package Repository section" >}}
Nice idea moving screenshot from start to below some key info

2022-08-26 13:21 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Create a Package from Team Server** - select a branch to build the revision that it contains
Please verify these are en dashes and not hyphens

2022-08-26 13:22 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Upload** - upload an *.mda* package file from your local device
".mda" or "MDA" ?

2022-08-26 13:22 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Deploy** - transport the package from the Team Server to the selected environment
"Team Server" (no need for "the")

2022-08-26 13:22 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* Environment name - for example, *Acceptance*
Italics for an example?

2022-08-26 13:23 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* Environment status - indicated by the color of the checkmark by the environment name:
"checkmark" or "check mark" ?

2022-08-26 13:25 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Runtime** - the Mendix Studio Pro version on which the app is built, for example, *9.5.0*
Version "on which" or "with which" ?

Italics for example?

2022-08-26 13:34 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Setup Studios Deployment** - the [Technical Contact](/developerportal/collaborate/app-roles/#technical-contact) can set the target environment to which apps will be deployed from Studio and Studi
Is this really "Setup" as a verb in the UI?

2022-08-26 13:35 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Operations carried out by the Mendix Operations Desk are not currently logged in the activity log.
What is this "Operations Desk" ? First time I've heard that. Defined in another doc?

2022-08-26 13:37 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Operations carried out by the Mendix Operations Desk are not currently logged in the activity log.
It's not clear to me the relationship between these 2 sentences in the alert. The fact that there is a line break between them - while still in the alert - further complicates things IMO. I do not use or recommend adding line breaks between text in an alert. An alert should be compact and with direct coherent messaging. Are these 2 sentences related? If not, should they be 2 separate alerts?

2022-08-26 13:38 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +In the **Custom Domain** tab, you can manage your custom domain certificates on an application level, as well as see an overview of linked custom domains.
"on an application level" or "on the level of the application" or "at the application-level" ? A few factors here to consider.

2022-08-29 11:52 UTC, MarkvanMents requested changes
Hi Kasia,
Some nice changes here.
I have made some comments.
My main worry is that by combining the standard environments with the flexible environments that section becomes much more difficult to follow - each bullet point now has a condition associated with it ("does this apply to my set of environments") rather than the original where the reader can say "do I have flexible or standard environments" and then go and read the appropriate section.

Let me know what you think.

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Activity
Access Restriction Profiles are already in the document (line 23).

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
>  * **Custom Domain**
```suggestion
* **Custom Domains**
```

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
>  * Expire date of the deployment package
Resolving my own typo 😀
```suggestion
* Expiry date of the deployment package
```

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Upload** - upload an *.mda* package file from your local device
I'm not sure it matters - but technically I don't think it has to have the suffix `.mda` so perhaps MDA is better. Or just say "upload a deployment package from your local device" and avoid the issue entirely?

There seems to be an inconsistency across the site - 42 occurencies of `MDA` and 10 of `*.mda`. Nothing in our style guide at present.

(MDA = [Mendix Deployment Archive](https://d25bt5g8n19u8d.cloudfront.net/product-naming/other-terms/#mendix-deployment-archive)).

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
>  * Deployment package
Perhaps "Deployment package name" might be better, it isn't the whole package?

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +{{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/environments/deployment-package.png" alt="The Deployment Package Repository section" >}}
Image seems a bit old - headings are all caps and the buttons are round instead of square. If it is easy to get a new picture, we could update it, but the content is the same so not high priority!

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * View the package size, description, build output, and an overview of the environments that are currently running on this package
package runs in an environment, not the other way around. Correcting my own text!
```suggestion
    * View the package size, description, build output, and an overview of the environments that are currently running this package
```

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Details**:
Missing "Delete" here!
```suggestion
* **Delete** – delete a deployment package which was previously uploaded or created for this app
* **Details**:
```

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    {{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/environments/deploy-flex-environments.png" alt="The Environments section with flexible environments" >}}
I really don't think we should combine the standard environments with the flexible environments. The formats are sufficiently different and have enough differences that I find having several bullets which are only for flexible environments makes it difficult to see at a glance what you can do. 

I would reverse this and go back to two separate sections. 

Reasoning:
1. They look very different
3. There is a PROD indicator for flexible environments
4. There is a Plan for flexible environments
5. There is a search box for flexible environments
6. You can sort flexible environments
7. You can't "Transport to Production" for flexible environments
8. Most customers have standard environments and do not need to know about the features of flexible environments.

We can discuss this if you think there is a middle way to clarify the documentation.

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* Environment status - indicated by the color of the checkmark by the environment name:
Or just "check".
[MW](https://www.merriam-webster.com/dictionary/check)
> a mark typically ✓ placed beside an item to show it has been noted, examined, or verified.

If we go with "check mark" it needs a space according to [MS](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/c/check-checkbox-check-mark)

And perhaps "next to the environment name" to avoid having two "by"s in the sentence performing different roles?

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Runtime** - the Mendix Studio Pro version on which the app is built, for example, *9.5.0*
This is horrible to try to explain.
If you build an app with Mendix version 9.5.0, you need to run it with the Runtime version 9.5.0. So the version numbers are the same, but you are not technically referring to Studio Pro in the UX but the runtime version.

So, that is why my original was a bit vague about what the runtime actually meant.

I am sort of hoping that one day you won't need a different runtime for every version of Mendix, but I don't think that will happen in a hurry!

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Operations carried out by the Mendix Operations Desk are not currently logged in the activity log.
The second sentence defines "Operations carried out by the Mendix Operations Desk". Since this is an internal name, then perhaps we should combine the information and get rid of the internal reference. See suggestion below.

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
>  These are activities which are performed on a customer's behalf only with written approval through a Mendix Support ticket.
To resolve Adam's comment above,
```suggestion
Operations performed on a customer's behalf through an authorized Mendix support ticket are not currently logged in the activity log.
```

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +In the **Permissions** tab, the [Technical Contact](/developerportal/collaborate/app-roles/#technical-contact) and other team members who have the Manage Permissions permission can manage various per
Do we want to avoid "Manage Permissions permission" - it's a bit of a mouthful (or eyeful!). And perhaps replace one of the occurrences of "permission". This is somewhere that a UX writer/designer might help.
```suggestion
In the **Permissions** tab, the [Technical Contact](/developerportal/collaborate/app-roles/#technical-contact) and other team members who have permission to Manage Permissions can manage access to the environments for each team member. Team members who have permission to Deploy, Publish, and Monitor can view the permissions.
```

2022-08-29 11:52 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Team members who have the Deploy, Publish, and Monitor permission can see which services are enabled or disabled.
Might want to change this back if you accept the change above?

2022-08-30 10:43 UTC, katarzyna-koltun-mx commented
> Hi Kasia, Some nice changes here. I have made some comments. My main worry is that by combining the standard environments with the flexible environments that section becomes much more difficult to follow - each bullet point now has a condition associated with it ("does this apply to my set of environments") rather than the original where the reader can say "do I have flexible or standard environments" and then go and read the appropriate section.
> 
> Let me know what you think.

@MarkvanMents Makes sense - I've split them off to be clearer. Let me know what you think. Thank you!

2022-08-30 11:05 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +### 2.2.2 Without Flexible Environments
Hi Kasia,
Thanks for making the change.
I would put the _Standard Environments_ section first, since that is what 90% of customers will have. I would also call it something like **Standard Environments** rather than _Without Flexible Environments_ as it makes it sound like the customer has an inferior product. Flexible environments are only really used by companies who have a very complex infrastructure (PostNL for example) and isn't needed by most customers.

And similarly, change the language in the text - so just say "If your node has the standard set of environments" and remove the "If your node does not support flexible environments," bit.

2022-09-01 08:40 UTC, MarkvanMents approved these changes

2022-09-01 08:42 UTC, merged