Proofread first file in the runtime batch
mendix/docs pull request #5022
Opened 2022-09-08 16:10 UTC by katarzyna-koltun-mx

@Adam-Dupaski @MarkvanMents I've proofread the first file in the runtime batch, please let me know any feedback. Thank you!

2022-09-09 10:20 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The Mendix Runtime is an interpreter which runs a Mendix model and serves pages to the user.
Cross-reference possible to a doc describing/defining "Mendix model"? Would "Mendix app model" be clearer?

2022-09-09 10:20 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The Mendix Runtime is an interpreter which runs a Mendix model and serves pages to the user.
"user" or "end-user" ?

2022-09-09 10:27 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +Each patch version of Mendix comes with its own version of the Mendix Runtime which implements the features which are available in that version of Mendix. For example, runtimes for Mendix 8.4.1 and 8
I think we need to clarify and decide on "Mendix version" vs "Studio Pro version" throughout. Here, would it be sufficient to say, "Each patch version of Studio Pro comes with its own version of the Mendix Runtime" ? Because the version numbers are really determined by Studio Pro, not Mendix Runtime on its own, and not "Mendix" on its own either. Studio Pro determines the number.

Accordingly, it should be, "Mendix Runtimes for Studio Pro 8.4.1 and 8.4.2 are different"

(Also, it should be "Mendix Runtime" throughout, not just "runtime")

For "patch version," consider adding a cross-reference link to https://docs.mendix.com/releasenotes/studio-pro/lts-mts/

2022-09-09 11:08 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The Mendix Runtime consists of two parts: the [Runtime Server](/refguide/runtime-server/) and the [Mendix Client](/refguide/mendix-client/). The relationship between the two is shown in the chart bel
Is that really a "chart"? Also, we don't need borders for diagrams.

2022-09-09 11:08 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The *Runtime Server* is launched on a cloud platform. It executes microflows, and connects to files, the relational database, and any other required services. It waits to be contacted by the Mendix C
Why is this italicized?

2022-09-09 11:09 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The *Runtime Server* is launched on a cloud platform. It executes microflows, and connects to files, the relational database, and any other required services. It waits to be contacted by the Mendix C
(Issue below as well)

2022-09-09 11:10 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The *Runtime Server* is launched on a cloud platform. It executes microflows, and connects to files, the relational database, and any other required services. It waits to be contacted by the Mendix C
"The Runtime Server is described in more detail in [Runtime Server](/refguide/runtime-server/)." - is there a better more minimal way to write the cross-reference that doesn't require mentioning "Runtime Server" twice? 

(Issue below as well)

2022-09-09 12:46 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +Each of the components of Mendix Runtime is described below:
Colon not necessary to lead into sub-sections with sub-headings, should just be a period.

2022-09-09 12:47 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +This is the hardware on which the Mendix app is deployed. It is usually provided as Infrastructure as a Service (IaaS), which provides virtual machines in the public or private cloud. However, the in
"infrastructure as a service (IaaS)" - not a proper noun so doesn't need title case

2022-09-09 12:48 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +This is the storage location for data files used by the app. More specifically, it contains the value of *FileDocument* objects, including images, which are binary objects that are stored outside the
Why is FileDocument italicized? We should not use italics for emphasis. This is not a file name or format, either, and not a UI element. So probably no formatting?

2022-09-09 12:50 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +Also called the **App Container**, this launches and exposes the Runtime Server. At least one instance must exist, but to provide high availability and better performance there can be many instances.
Is "**App Container**" bolded because it is in the UI? We should not use bold for emphasis. 

If it's in the UI, can you cross-reference a doc that describes it, preferably with a screenshot?

Or, should it be "App Container" ?

2022-09-09 12:52 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +This is the server side of the Mendix Runtime. For more information, see [Runtime Server](/refguide/runtime-server/).
Is this section really necessary when Runtime Server is described in detail above (and also has the same cross-reference link above)?

2022-09-09 12:53 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +This is the server side of the Mendix Runtime. For more information, see [Runtime Server](/refguide/runtime-server/).
Should there be a first sub-section above to clarify that: "2.1 Runtime Server and Mendix Client" ?

2022-09-09 12:54 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The CDN (Content Delivery Network) contains static configuration information which is needed by the client. These include the files needed to start the Mendix Client from a browser, Cascading Style S
"content delivery network (CDN)" - fully write out the acronym's words first

2022-09-09 12:55 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +The CDN (Content Delivery Network) contains static configuration information which is needed by the client. These include the files needed to start the Mendix Client from a browser, Cascading Style S
"Cascading Style Sheets (CSS files)" - probably doesn't need to be explained, "CSS" should be common enough for the reader to not require fully writing it out?

2022-09-09 12:56 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/_index.md
> +This is the web browser (for example, Google Chrome) or mobile device (for example, an iPhone) which allows the user to interact with the app. It typically has a screen, pointer device, and input dev
Same thing as for Runtime Server - is this section really necessary, isn't it just repeating what in the intro for section 2 (or a new 2.1 sub-section)?

2022-09-19 06:33 UTC, MarkvanMents requested changes
Thanks for the review, Kasia.
There are some comments from Adam and myself. Can you look at these and address those which need addressing.
If you have questions please come back to me/us and we can discuss them.

Great that these documents are getting more attention.

Mark

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +The Mendix Runtime is an interpreter which runs a Mendix model and serves pages to the user.
Usually we use "Mendix Model" (https://docs.mendix.com/refguide/using-eclipse/), although I have seen "app model". I don't think we need both.

We could refer to this document: https://docs.mendix.com/apidocs-mxsdk/mxsdk/understanding-the-metamodel/ but it is a bit detailed. In the end, I think the concept of the Mendix model comes out in the child documents under this one but perhaps we need a better description somewhere like [App Modeling](https://docs.mendix.com/refguide/modeling/). The terminology was more obvious when Studio Pro was called the Mendix Modeler.

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +Each patch version of Mendix comes with its own version of the Mendix Runtime which implements the features which are available in that version of Mendix. For example, runtimes for Mendix 8.4.1 and 8
Not sure I agree on "Studio Pro" version.
In the end we have a **Mendix** version. That version number carries through to the Mendix Model, which Studio Pro you need to create that model, which runtime deploys that version, and the Server distribution in the related downloads. It should also apply to the [Model SDK](https://docs.mendix.com/releasenotes/sdk/model-sdk-4/) as there is a new one of those for every Mendix (minor) version - although for some reason they use a completely different versioning system.

I think the "Mendix version" is what drives all the others, not the "Studio Pro version". Studio Pro is just a modeling tool to allow you to work with a specific Mendix version. Using "Studio Pro version" makes it much more difficult to document all the other parts of the platform.

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +The *Runtime Server* is launched on a cloud platform. It executes microflows, and connects to files, the relational database, and any other required services. It waits to be contacted by the Mendix C
It is italicized to link it to a labelled element on the diagram above. I think it helps, but perhaps there are other ways of doing that.
Later on there is a heading for each labelled element on the diagram  - I think Adam's solution, below, of having a heading for Runtime Server and Runtime Client before this section and removing them from where they are at present is a great solution.

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +This is the hardware on which the Mendix app is deployed. It is usually provided as Infrastructure as a Service (IaaS), which provides virtual machines in the public or private cloud. However, the in
But the abbreviation _does_ use title case, so using it in the full version links it to the way the abbreviation is always presented, and helps the reader remember what the abbreviation stands for, since this is the first (and probably only) time it is used in the document.
However, I'm happy for it to be changed if you thing this capitalization doesn't help.

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +This is the storage location for data files used by the app. More specifically, it contains the value of *FileDocument* objects, including images, which are binary objects that are stored outside the
It is a specific sort of generalized object with specific features (it saves content in an S3 bucket) which no other generalizations have. If you use it, it does appear in the UX.
![image](https://user-images.githubusercontent.com/35492184/190661746-8c7a0028-564a-4b14-ba10-8eb404c4bee8.png)
Could perhaps say:
> it contains the value of objects of entity types which are specializations of the `System.FileDocument` entity

to make it more explicit?

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +Also called the **App Container**, this launches and exposes the Runtime Server. At least one instance must exist, but to provide high availability and better performance there can be many instances.
👍

2022-09-19 06:33 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/_index.md
> +This is the server side of the Mendix Runtime. For more information, see [Runtime Server](/refguide/runtime-server/).
👍

2022-09-19 07:51 UTC, MariaShaposhnikova commented on content/en/docs/refguide/runtime/_index.md
> +Each patch version of Mendix comes with its own version of the Mendix Runtime which implements the features which are available in that version of Mendix. For example, runtimes for Mendix 8.4.1 and 8
Hi Adam and Mark,
Mark asked me for my input from the Studio perspective. When explaining Studio version and its correlation to Studio Pro, we use "Mendix version". In the [Studio Ranges & Mendix Versions](https://docs.mendix.com/studio/general-versions/) document, we say "The Mendix version is the version of the you are editing. Mendix version correlates to Mendix Studio Pro version, but is broader, as the Mendix version is the version of the whole platform including Mendix Studio Pro and Mendix Runtime." In the Studio UI, you can see the information on the Studio version and Mendix version.

2022-09-20 14:03 UTC, Luyao-Zhang-1 commented on content/en/docs/refguide/runtime/_index.md
> +Each patch version of Mendix comes with its own version of the Mendix Runtime which implements the features which are available in that version of Mendix. For example, runtimes for Mendix 8.4.1 and 8
"The Mendix version is the version `of the` you are editing" Isn't a word missing here in this sentence?

2022-09-20 14:37 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +The Mendix Runtime is an interpreter which runs a Mendix model and serves pages to the user.
I've decided to link the page that Mark suggested.

2022-09-20 14:42 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +Each patch version of Mendix comes with its own version of the Mendix Runtime which implements the features which are available in that version of Mendix. For example, runtimes for Mendix 8.4.1 and 8
Per Mark and Maria, keeping "Mendix version".

Generally discussed runtime vs. Mendix Runtime with Mark and we both feel that in some cases, "runtime" is more suitable.

Added link to "patch version".

The error that Luyao pointed out is for another document - @MariaShaposhnikova let me know if you want me to fix it, or if you're planning to do it/have already done it yourself.

2022-09-20 14:58 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +The Mendix Runtime consists of two parts: the [Runtime Server](/refguide/runtime-server/) and the [Mendix Client](/refguide/mendix-client/). The relationship between the two is shown in the chart bel
Changed to diagram as that's more accurate.

Cropped the image to remove the border.

2022-09-20 15:41 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +Each of the components of Mendix Runtime is described below:
Fixed.

2022-09-20 15:42 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +This is the hardware on which the Mendix app is deployed. It is usually provided as Infrastructure as a Service (IaaS), which provides virtual machines in the public or private cloud. However, the in
I checked and IaaS appears to be the standard way to capitalize this term.

2022-09-20 15:42 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +Also called the **App Container**, this launches and exposes the Runtime Server. At least one instance must exist, but to provide high availability and better performance there can be many instances.
Removed the bolding.

2022-09-20 15:44 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +The CDN (Content Delivery Network) contains static configuration information which is needed by the client. These include the files needed to start the Mendix Client from a browser, Cascading Style S
Done.

2022-09-21 15:14 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +This is the storage location for data files used by the app. More specifically, it contains the value of *FileDocument* objects, including images, which are binary objects that are stored outside the
I don't think this would increase the clarity of the sentence. I'll go with Adam's suggestion as in this context, this isn't mentioned as part of the UI.

2022-09-21 15:36 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +This is the server side of the Mendix Runtime. For more information, see [Runtime Server](/refguide/runtime-server/).
Done.

2022-09-21 15:39 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +This is the web browser (for example, Google Chrome) or mobile device (for example, an iPhone) which allows the user to interact with the app. It typically has a screen, pointer device, and input dev
Done.

2022-09-21 15:39 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +The *Runtime Server* is launched on a cloud platform. It executes microflows, and connects to files, the relational database, and any other required services. It waits to be contacted by the Mendix C
Done.

2022-09-21 15:39 UTC, katarzyna-koltun-mx commented on content/en/docs/refguide/runtime/_index.md
> +The *Runtime Server* is launched on a cloud platform. It executes microflows, and connects to files, the relational database, and any other required services. It waits to be contacted by the Mendix C
Done.

2022-09-21 15:42 UTC, MariaShaposhnikova commented on content/en/docs/refguide/runtime/_index.md
> +Each patch version of Mendix comes with its own version of the Mendix Runtime which implements the features which are available in that version of Mendix. For example, runtimes for Mendix 8.4.1 and 8
Good catch, thank you @Luyao-Zhang-1! @katarzyna-koltun-mx , I have fixed it on development.

2022-09-21 16:01 UTC, merged