Updated IIoT for Makers doc for IDL OData workflow
mendix/docs pull request #5035
Opened 2022-09-13 10:14 UTC by Sezalpr

Hi @MarkvanMents @StefanKellerSiemens, 
Please review this pull request.

2022-09-13 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=5035) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=5035) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=5035) it.</sub>

2022-09-14 13:18 UTC, MarkvanMents requested changes
Hi @Sezalpr,
Great PR, I have proofread and made some very minor changes in this commit: https://github.com/mendix/docs/pull/5035/commits/8e4e5d17b86423fe0b969ef591c26feee7109969

I have made two additional comments, can you look at these and we can discuss the best way forward to resolve them.

Thanks very much for providing a PR which needed so little work from my end.

Mark

2022-09-14 13:18 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mindsphere-app-service.md
> +1. You will now see the lists of your already existing contracts or an indication that no contracts are created yet.
Is this one list of all the contracts, or are there several lists? If only one list of contracts then:
```suggestion
1. You will now see a list of your already existing contracts or an indication that no contracts are created yet.
```

2022-09-14 13:18 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mindsphere-app-service.md
> +    {{< figure src="/attachments/partners/siemens/mindsphere/mindsphere-app-service/idl_contract_summary.png" alt="data-lake-manager" >}}
The image file has been committed with the name `idl_contract_summary.PNG`, rather than `idl_contract_summary.png`. Browsers are case-sensitive, so the file isn't linked properly. Can you reupload it with the correct name (you may have to delete it and then create it, as github is sometimes case insensitive.

I can sort this out later if you can't sort it out yourself, but I'll have to wait until we merge the PR and I have full R/W access to the branch.

2022-09-14 13:21 UTC, Adam-Dupaski commented
@Yiyun333 a nice PR where changes were requested (I added the label FYI)

2022-09-15 08:12 UTC, Sezalpr commented on content/en/docs/partners/siemens/mindsphere/mindsphere-app-service.md
> +1. You will now see the lists of your already existing contracts or an indication that no contracts are created yet.
Updated

2022-09-15 08:12 UTC, Sezalpr commented on content/en/docs/partners/siemens/mindsphere/mindsphere-app-service.md
> +    {{< figure src="/attachments/partners/siemens/mindsphere/mindsphere-app-service/idl_contract_summary.png" alt="data-lake-manager" >}}
File name updated

2022-09-16 09:39 UTC, MarkvanMents approved these changes
Thanks for making the changes.
Approving this PR. 
From my side this is now ready to publish. Please let me know when the feature is released - I expect to hear from you on 21 September if all goes well.
Yours
Mark

2022-09-29 15:31 UTC, MarkvanMents commented
Approved by Tushar in email.

2022-09-29 15:31 UTC, merged