Document native database encryption [9.18]
mendix/docs pull request #5042
Opened 2022-09-14 11:13 UTC by ekrem-aktas

This PR documents the new offline-first database encryption feature. Will be part of the 9.18 release.

2022-09-14 11:43 UTC, ilia-kurganskii commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
I'm not sure about this section regarding security. We explain how to get access to a database it could be used against users

2022-09-14 11:44 UTC, diego-antonelli requested changes

2022-09-14 11:44 UTC, diego-antonelli commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +Local database encryption requires the latest version of the native template. If this setting is enabled using an older version of the native template, the app will not start. Be careful about the te
Maybe instead of mention latest version of NT we could be more specific saying v6.3.0 and higher

2022-09-14 11:44 UTC, diego-antonelli commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.4 Disabling Database Encryprion
Typo

2022-09-14 11:44 UTC, diego-antonelli commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
I am not sure if we should mention this step, seems very sensitive data.

2022-09-14 12:00 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
Do we think this is a piece of privileged information? I assume if someone has access to the files of the app, it is a matter of copying everything.

2022-09-14 12:01 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +Local database encryption requires the latest version of the native template. If this setting is enabled using an older version of the native template, the app will not start. Be careful about the te
That's something I've been considering as well. Will do

2022-09-14 12:04 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
Ilya mentioned the same concern. Do we think this is so sensitive? It is already publicly available with a simple search: https://stackoverflow.com/questions/60964637/how-to-get-the-path-of-sqlite-db-in-react-native

2022-09-14 12:06 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
Or even mentioned here: https://github.com/andpor/react-native-sqlite-storage#opening-a-database

2022-09-14 12:17 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +Local database encryption requires the latest version of the native template. If this setting is enabled using an older version of the native template, the app will not start. Be careful about the te
Done ✔️

2022-09-14 12:18 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.4 Disabling Database Encryprion
Fixed, thank you for noticing it!

2022-09-14 12:36 UTC, ilia-kurganskii commented
Great job!

2022-09-14 12:50 UTC, diego-antonelli commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
Indeed, but maybe we are simplifying the way to get the info here 😅

2022-09-14 13:13 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
Yup, we're saving some time (probably minutes) indeed. Hiding this information feels like security through obscurity though, which I believe does not improve the security in a meaningful way.

Maybe we should consider if we have enough reason(s) to keep this section. I added this section because there are no observable side effects when DB encryption is enabled. There is no way for our customers to verify this feature works as intended. They need to take our word for it that the DB is encrypted. They can hire a security firm to verify it (not all customers have this option though), or verify it themselves (which is the goal of this section).

A side note - in terms of security, I'd be more concerned about the last section: "4.7 -> How Does Database Encryption Work" as it mentions the implementation details and does not seem to provide value to our customers. If you share the same concern, I can remove it.

2022-09-14 13:44 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
Resolving this discussion as it is a duplicate of [this one].(https://github.com/mendix/docs/pull/5042#discussion_r970696674)

2022-09-14 13:59 UTC, diego-antonelli commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +### 4.6 How Can I Verify That The Database Is Encrypted?
I think 4.7 is fine, I will resolve this thread for now as Frank may give you more info.

2022-09-20 09:38 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +How does local database encryption work? Local database encryption works by creating a random key when the app is started for the first time. The database file is encrypted with this key, which is st
@ConnorLand thank you for the edits! I believe @jdiehl prefers to have this information as the last section on purpose, because it is technical information, and not needed by all readers. (I had it up as well before, and he suggested to move it down during our drafts)

2022-09-26 09:28 UTC, ConnorLand commented on content/en/docs/refguide/mobile/using-mobile-capabilities/offlinefirst-data/local-data-security.md
> +How does local database encryption work? Local database encryption works by creating a random key when the app is started for the first time. The database file is encrypted with this key, which is st
Gotcha. I think the info should be high up to inform certain personas of the basics. However, I've made it into an easily skippable subsection to address Jonathan's feedback. I think this is a good compromise. https://github.com/mendix/docs/pull/5042/commits/ba10f763285c654906bcfd27f78dfdf2a2ef3097

2022-09-26 11:23 UTC, ConnorLand approved these changes

2022-09-30 08:28 UTC, merged