Update native logging docs
mendix/docs pull request #5051
Opened 2022-09-15 11:27 UTC by omnajjar

This should me part of docs Mx9.18

2022-09-15 11:29 UTC, omnajjar commented
This is still a work in progress and needs review from the team once we're done, we'll unmark it as a draft

2022-09-15 14:02 UTC, ConnorLand commented
This was closed because the changes weren't in place before the 9.18 freeze. Thus, this doc update will happen in 9.19.

2022-09-30 14:23 UTC, ConnorLand commented
I had edited this text and it's good to merge from my evaluation. If 9.18.1 happens when I'm on vacation, please give the PR one final language check and then merge it. I'll check the merged content with Osama when I return.

2022-09-30 14:23 UTC, ConnorLand approved these changes

2022-10-06 11:38 UTC, ekrem-aktas requested changes

2022-10-06 11:38 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
> +When the app goes to background, the native client will save buffered log message on the file system and will restore them once the app is active again. This is in case log messages reach the limit b
```suggestion
When the app goes to the background or closes, the native client will save buffered log messages on the file system and will restore them once the app is active again.
```

The following sentence below is not clear (to me). What do we want to explain here?

>  This is in case of log messages reach the limit but there is no network connectivity when the native client would attempt to send these log messages.

2022-10-06 11:38 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
> +The native client stores log messages locally on the device. When **Enable sending logs to runtime** is selected, the native client will attempt to send log messages whenever a quota of 1,000 message
```suggestion
The native client stores logs on the device's memory. When **Enable sending logs to runtime** is selected, the native client will attempt to send logs whenever a quota of 1,000 logs has been reached or after 1 hour from the last sending attempt.
```

2022-10-06 11:38 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
> +From Mendix Studio Pro 9.18.1 and above log messages are filtered based on the log levels set in the Cloud Portal app.
Should we add a warning that enabling "trace" may cause too many logs to be sent to the runtime server, so it should not be kept on for longer time frames?

2022-10-06 11:38 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
> +In this scenario, it will discard older messages so that it will not overflow with too many logs. An additional `info` log message will be added with the number of discarded logs and the timestamps o
Should we also mention the format of the logs, such as the unique session id and the date/time of the log as the date in the cloud portal is the date of the collection, not the date of the log itself.

2022-10-06 11:38 UTC, ekrem-aktas commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
>  * Crash logs are not supported currently
I think this is partially true - we do log client crashes, and they are sent to the runtime with the logs. But we don't log native crashes, which I believe happen less.

2022-10-10 11:14 UTC, omnajjar commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
>  * Crash logs are not supported currently
Corrected!

2022-10-10 11:14 UTC, omnajjar commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
> +From Mendix Studio Pro 9.18.1 and above log messages are filtered based on the log levels set in the Cloud Portal app.
Added!

2022-10-10 11:14 UTC, omnajjar commented on content/en/docs/refguide/mobile/distributing-mobile-apps/logging.md
> +In this scenario, it will discard older messages so that it will not overflow with too many logs. An additional `info` log message will be added with the number of discarded logs and the timestamps o
Done! ✅

2022-10-11 07:54 UTC, ekrem-aktas approved these changes
Thank you for improving the docs! 👏

2022-10-11 08:09 UTC, ConnorLand approved these changes

2022-10-11 08:11 UTC, ConnorLand commented
Hey @omnajjar is this still a draft or is it ready for release day?

2022-10-11 08:37 UTC, omnajjar commented
> Hey @omnajjar is this still a draft or is it ready for release day?

@ConnorLand it is ready for release.

2022-10-14 11:49 UTC, merged