Add descriptions to children docs
mendix/docs pull request #5058
Opened 2022-09-16 08:18 UTC by Yiyun333

Commit part of the changes for Studio Pro Guide

2022-09-26 09:23 UTC, MarkvanMents requested changes
Hi @Yiyun333 
Great work. I only have a couple of comments.
Do you have a spell checker in VS Code or whatever you are using to edit? I think that some of the typos would have been picked up by a spell checker. Let me know if you need help in adding a spell checker to your system.
But generally very good and makes the documentation look like it is supposed to and helps the customers find the information they need.
Thanks.

2022-09-26 09:23 UTC, MarkvanMents commented on content/en/docs/refguide/general/third-party-licenses.md
> +description: "Describes where to find the available thrid-party licenses in Mendix."
typo
```suggestion
description: "Describes where to find the available third-party licenses in Mendix."
```

2022-09-26 09:23 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/pages/_index.md
> +description: "Presents an overvies of the features of pages and relevant page resources in Studio Pro."
type
```suggestion
description: "Presents an overview of the features of pages and relevant page resources in Studio Pro."
```

2022-09-26 09:23 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/new-merge-algorithm.md
> +description: "Introduces a new merge algorithm and how to enable it to resolve conflicts."
I think we need a new verb for "how to enable"?
```suggestion
description: "Introduces a new merge algorithm and describes how to enable it to resolve conflicts."
```

2022-09-26 09:23 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/on-premises-svn.md
> +description: "Introduces how to work with SVN on-premises version control server."
Not sure whether this should be "**_an_** SVN on-premises version control server"

But I see that it matches the rest of the document, so let's leave it for now.

(Applies also to the git server - so something to review later).

2022-09-26 09:23 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/metrics.md
> +description: "Describes how to congifure and report metrics in Mendix."
typo
```suggestion
description: "Describes how to configure and report metrics in Mendix."
```

2022-09-26 11:39 UTC, Yiyun333 commented on content/en/docs/refguide/version-control/on-premises-svn.md
> +description: "Introduces how to work with SVN on-premises version control server."
No problem. I will keep it like this for now.

2022-09-26 12:08 UTC, Yiyun333 commented
> Hi @Yiyun333 Great work. I only have a couple of comments. Do you have a spell checker in VS Code or whatever you are using to edit? I think that some of the typos would have been picked up by a spell checker. Let me know if you need help in adding a spell checker to your system. But generally very good and makes the documentation look like it is supposed to and helps the customers find the information they need. Thanks.

Great tool! Thanks, Mark! I've accepted all the commits you suggested here. After your approval, I will merge this PR :)

2022-09-27 07:09 UTC, MarkvanMents approved these changes
Thanks for picking up my suggestions.
Approving now.
Don't know what you have agreed with Adam about reviewing this PR, but as far as I'm concerned you can merge it.

2022-09-27 07:26 UTC, Yiyun333 commented
> Thanks for picking up my suggestions. Approving now. Don't know what you have agreed with Adam about reviewing this PR, but as far as I'm concerned you can merge it.

Thanks Mark! As far as I know, Adam is not involved in this PR. So far, it's just you and me.

2022-09-27 07:32 UTC, merged