Add descriptions to children docs-Studio Pro How-tos
mendix/docs pull request #5082
Opened 2022-09-21 16:22 UTC by Yiyun333

2022-09-22 15:29 UTC, MarkvanMents requested changes
Hi @Yiyun333 ,
This is really great. The site looks so much better when it is built and it will help the customers navigate.
I've added a couple of comments, mainly about trying to be consistent in the use of "Describes" or "Presents". I feel it looks nicer if there is a consistency in what is written - particularly since 90% of the descriptions are consistent.
There are a few docs where the description could also be more consistent with the other descriptions:
/howto/integration/exposing-data-to-bi-tools-using-odata.md
/howto/extensibility/explore-connectors-and-adapters.md
/howto/monitoring-troubleshooting/detect-and-resolve-performance-issues.md

And this file doesn't have a full stop at the end of the description, while all the others do!
/howto/integration/version-rest-service.md

I built the branch locally and found it easier to proofread and to spot inconsistencies. I would never have seen them if I'd tried to work through the pull request.

Let me know if you have any questions or don't like my suggestions.

Thanks for working on this.

Mark

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/data-models/create-a-basic-data-layer.md
> +description: "Describes how to create entities and attributes, add enumerations, create associations, and delete association behavior with Studio Pro."
Is this deleting the behavior or deleting the association? It reads like the former.

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/general/_index.md
> +description: "Describes introductory how-tos about Mendix Studio Pro basics and best practices."
I think "Presents" works better here. Like you have written in some other descriptions.

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/integration/_index.md
> +description: "Describes a list of how-tos about integrating Mendix applications with other systems and services."
```suggestion
description: "Presents a list of how-tos about integrating Mendix applications with other systems and services."
```
for consistency

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/front-end/ux-best-practices.md
> +description: "Presents best practices written by a UX Designer for contributing to the app development process."
I think "Describes" is best for single documents, "Presents" is better for a document which is a list of further how-tos. Perhaps you can think about this description, it feels a bit awkward compared to the other ones you have written. Let me know if you want to bounce some ideas around on how to improve it.

![image](https://user-images.githubusercontent.com/35492184/191781347-71379223-15ec-4d71-83f7-63b7d4782b3b.png)

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/logic-business-rules/translatable-validation-messages.md
> +description: "Gives an overview of how to use translatable validation messages."
I like "Describes" for consistency with all the others. How about
```suggestion
description: "Describes the use of translatable validation messages."
```

Or you could begin "Describes how to…" for consistency with the other descriptions.

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/logic-business-rules/string-concatenation.md
> +description: "Presents three examples as well as best practices on configuring string concatenation."
Describes...?

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/integration/implement-cicd-pipeline.md
> +description: "Describes how you can use the available Mendix APIs with any mainline orchestrators to build a simple CICD pipeline."
Do we have a standard for CICD or CI/CD. I tend to use the latter, and that is what is in the document title, but I'm not sure we have any guidance about it.

Do you have time to research this a bit in the Microsoft style guide and elsewhere?

2022-09-22 15:29 UTC, MarkvanMents commented on content/en/docs/howto/monitoring-troubleshooting/clear-warning-messages.md
> +description: "Describes how to eliminate design time warnings by viewing and clearing warning messages."
Hyphenated (I think?)
```suggestion
description: "Describes how to eliminate design-time warnings by viewing and clearing warning messages."
```

2022-09-23 08:42 UTC, Yiyun333 commented on content/en/docs/howto/data-models/create-a-basic-data-layer.md
> +description: "Describes how to create entities and attributes, add enumerations, create associations, and delete association behavior with Studio Pro."
I changed it to "configure the delete behavior for associations".

2022-09-23 08:43 UTC, Yiyun333 commented on content/en/docs/howto/general/_index.md
> +description: "Describes introductory how-tos about Mendix Studio Pro basics and best practices."
Changed it to "presents".

2022-09-23 08:47 UTC, Yiyun333 commented on content/en/docs/howto/front-end/ux-best-practices.md
> +description: "Presents best practices written by a UX Designer for contributing to the app development process."
Good find! I've changed "presents" to "describes" for single documents.

2022-09-23 08:48 UTC, Yiyun333 commented on content/en/docs/howto/logic-business-rules/translatable-validation-messages.md
> +description: "Gives an overview of how to use translatable validation messages."
Changed.

2022-09-23 08:51 UTC, Yiyun333 commented on content/en/docs/howto/logic-business-rules/string-concatenation.md
> +description: "Presents three examples as well as best practices on configuring string concatenation."
Sometimes it's not so clear whether to use "describes" and "presents", but I will stick to the rule that for single documents, I will use "describes", and for docs that have a list of other docs, I will use "presents".

2022-09-23 09:02 UTC, Yiyun333 commented on content/en/docs/howto/integration/implement-cicd-pipeline.md
> +description: "Describes how you can use the available Mendix APIs with any mainline orchestrators to build a simple CICD pipeline."
I will use CI/CD. The Miscrosoft style guide does not have a specific rule for this, but when I search CICD and CI/CD there, it only shows usage of CI/CD, so I guess that's the rule :)

2022-09-23 11:23 UTC, Yiyun333 commented
> Hi @Yiyun333 , This is really great. The site looks so much better when it is built and it will help the customers navigate. I've added a couple of comments, mainly about trying to be consistent in the use of "Describes" or "Presents". I feel it looks nicer if there is a consistency in what is written - particularly since 90% of the descriptions are consistent. There are a few docs where the description could also be more consistent with the other descriptions: /howto/integration/exposing-data-to-bi-tools-using-odata.md /howto/extensibility/explore-connectors-and-adapters.md /howto/monitoring-troubleshooting/detect-and-resolve-performance-issues.md
> 
> And this file doesn't have a full stop at the end of the description, while all the others do! /howto/integration/version-rest-service.md
> 
> I built the branch locally and found it easier to proofread and to spot inconsistencies. I would never have seen them if I'd tried to work through the pull request.
> 
> Let me know if you have any questions or don't like my suggestions.
> 
> Thanks for working on this.
> 
> Mark

@MarkvanMents Thank you very much for your feedback. I've made changes according to your comments. Please have a look again, and if there are no further issues/suggestions, I will merge this PR.

2022-09-23 14:53 UTC, MarkvanMents approved these changes
All looks good.
Thanks for doing this.

2022-09-26 11:34 UTC, merged