Document the requirement for Atlas 2 or for PWAs
mendix/docs pull request #5110
Opened 2022-09-29 07:25 UTC by WimJongeneel

This PR documents the requirement for a recent version of Atlas 2 or 3 when using the PWA features.

2022-10-03 13:45 UTC, Robinfr requested changes

2022-10-03 13:45 UTC, Robinfr commented on content/en/docs/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app.md
> +PWAs require the app to use a recent version of Atlas 2 or Atlas 3.
Should be "Atlas 2 or newer". Just in case we ever release Atlas 4 some day.

2022-10-05 12:21 UTC, Robinfr approved these changes

2022-10-19 13:35 UTC, ConnorLand approved these changes

2022-10-20 08:41 UTC, merged