Permanent Volumes for Kubernetes deployment
mendix/docs pull request #5116
Opened 2022-09-30 10:00 UTC by MarkvanMents

Add information on permanent volumes for Kubernetes deployments as discussed in issue  #4853
Also proofread for style

2022-09-30 10:15 UTC, MarkvanMents reviewed
I've added a few comments on things about which I was unsure.
@zlogic and @elliotclements-mendix, can you look at this and see if it solves the issues or just raises more.
Because this is written as a how-to, the idea is that the customer can have a working deployment at the end of it. Therefore, the instructions for persistent storage should be executable within the context of the how to.

Let me know your thoughts.
Thanks.
Mark

2022-09-30 10:15 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
>  All the configuration files used in this how-to are also available on GitHub.
Don't know where these files are? Can't see anything obvious in mendix/docs or mendix/docker-mendix-buildpack.
I think we should remove this and just suggest copying and pasting from the code blocks in the document?

2022-09-30 10:15 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +* Build your image in Minikube, using the steps in the [Docker](/developerportal/deploy/docker-deploy/) page.
Moved this to a prerequisite as there were no instructions on how to do it, it just said it had to be done first.
Is there anything else we need to say here?

2022-09-30 10:15 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> -You'll need to build your image in Minikube if you haven't done so yet. See [Docker](/developerportal/deploy/docker-deploy/) for the steps to do this.
Moved to prerequisite.

2022-09-30 10:15 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +```yaml
Is this the right thing to do.
I think the yaml does more than just add persistent volumes. However, it doesn't match exactly with the instructions on database configuration and deployment/stateful set in the other yaml.
Is there any way to pull out what is relevant to persistent volumes and indicate what the reader should do with them?

2022-09-30 10:15 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +If the application makes use of persistable FileDocument or FileImage entities, a persistent volume (PV) storage service needs to be attached as well. See [Mendix System Requirements](/refguide/syste
Is it true that we are still using node-bound storage with the new section we have added about adding persistent storage?

2022-09-30 14:08 UTC, zlogic requested changes

2022-09-30 14:08 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
>  All the configuration files used in this how-to are also available on GitHub.
I think the files are available in https://github.com/mendix/kubernetes-howto, but they look very outdated. Indeed, it would be better to remove any references to that repository.

2022-09-30 14:08 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +* Build your image in Minikube, using the steps in the [Docker](/developerportal/deploy/docker-deploy/) page.
The document doesn't mention it, but most likely the user would need to use [minikube build](https://minikube.sigs.k8s.io/docs/commands/image/#minikube-image-build) instead of `docker build`.

2022-09-30 14:08 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +Kubernetes is the standard Docker orchestration platform supported by Mendix. For details on supported version of Kubernetes see [Mendix System Requirements](/refguide/system-requirements/). If possi
Could you rephrase this as _Kubernetes is the standard container orchestration platform..._

Kubernetes and Docker parted ways (https://kubernetes.io/blog/2022/05/03/dockershim-historical-context/), they share the same basic principles and can use the same container images, but otherwise they don't depend on each other.

2022-09-30 14:08 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +If the application makes use of persistable FileDocument or FileImage entities, a persistent volume (PV) storage service needs to be attached as well. See [Mendix System Requirements](/refguide/syste
The example provided below needs an extra component, a [volume provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/provisioner.md) to use node-bound storage. Otherwise the app will not start until a local volume provisioner is installed and configured. I've provided a comment how to use node-bound storage directly, bypassing a volume provisioner below.

2022-09-30 14:08 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
>  kubectl create -f mendix-app-secrets.yaml
I think there's an easier way to fix host (node)-bound storage, just change
```
          volumeMounts:
            - mountPath: "/build/data/files"
              name: mendix-data
```
to
```
          volumeMounts:
            - mountPath: "/opt/mendix/build/data/files"
              subPath: files
              name: mendix-data
```

in this example `StatefulSet`.

2022-09-30 14:08 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +```yaml
I think the StatefulSet example below is out of date and is using incorrect paths - so this section is not required.

2022-10-03 13:45 UTC, MarkvanMents reviewed
@zlogic 
Hi Dmitrii,
I've updated the files from your comments. Can you let me know if this is now OK or whether there is anything further that needs doing.
Thanks for your quick review.
Mark

2022-10-03 13:45 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +Kubernetes is the standard Docker orchestration platform supported by Mendix. For details on supported version of Kubernetes see [Mendix System Requirements](/refguide/system-requirements/). If possi
I'm a bit confused about this as the documentation refers to the "Docker Buildpack".
Is there a way we can make this a bit clearer?
We can pick this up in a separate change if it is too much to do it now.

2022-10-03 13:45 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +* Build your image in Minikube, using the steps in the [Docker](/developerportal/deploy/docker-deploy/) page.
```suggestion
* Build your image in Minikube, using the steps in the [Docker](/developerportal/deploy/docker-deploy/) page and replacing Docker commands such as `docker build`  with Minikube equivalents such as `minikube image build`.
```

2022-10-03 13:45 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +```yaml
Removed

2022-10-03 13:45 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
>  kubectl create -f mendix-app-secrets.yaml
Updated, see below

2022-10-03 13:45 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +If the application makes use of persistable FileDocument or FileImage entities, a persistent volume (PV) storage service needs to be attached as well. See [Mendix System Requirements](/refguide/syste
I assume the changes I made to the `mendix-app.yaml` cover everything we need to do here?

2022-10-03 13:45 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +docker push <hub-user>/<repo-name>:<tag>
Should this be `minikube push` or is `docker push` OK?

2022-10-04 10:42 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +Kubernetes is the standard Docker orchestration platform supported by Mendix. For details on supported version of Kubernetes see [Mendix System Requirements](/refguide/system-requirements/). If possi
If I understand correcly, originally Kubernetes users would build app images using Docker Buildpack and then deploy them into Kubernetes using the YAMLs from this document. Mx4PC is intended to provide a higher level interface (a web UI for Connected mode or a MendixApp manifest for Standalone mode). But when this document was originally written, Mx4PC didn't exist yet and so the only way to deploy apps into Kubernetes was by using Docker Buildpack.

2022-10-04 10:46 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +* Build your image in Minikube, using the steps in the [Docker](/developerportal/deploy/docker-deploy/) page.
I made a mistake, can you change `minikube build` to `minikube image build`?

2022-10-04 10:46 UTC, zlogic commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +docker push <hub-user>/<repo-name>:<tag>
I've double-checked, and the command should be:
* `minikube image push <hub-user>/<repo-name>:<tag>` instead of `docker push ...`
* `minikube image build` instead of `docker build` or `minikube build`

2022-10-04 10:47 UTC, zlogic commented
@MarkvanMents Looks good to me, just one comment from my side - instead of `docker build` `docker push`, the command should be `minikube image build` and `minikube image push`.

2022-10-04 14:48 UTC, MarkvanMents reviewed
@zlogic 
Thanks for the review.
Let me know if the two proposals are now correct and I'll commit them and merge (unless you have any other concerns.

2022-10-04 14:48 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +* Build your image in Minikube, using the steps in the [Docker](/developerportal/deploy/docker-deploy/) page.
Edited. Does that look better?

2022-10-04 14:48 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/docker-deploy/run-mendix-on-kubernetes.md
> +docker push <hub-user>/<repo-name>:<tag>
So this?
```suggestion
minikube image push <hub-user>/<repo-name>:<tag>
```

2022-10-10 09:50 UTC, MarkvanMents commented
As discussed, will merge now - if there is anything else we can pick it up later, but this is an improvement on the current document!
Thanks for your help Dmitrii (@zlogic )

2022-10-10 09:53 UTC, merged