Multiple attributes can be the key
mendix/docs pull request #5127
Opened 2022-10-04 12:57 UTC by joostverhoog

In Studio Pro 9.19.0, multiple attributes can be the key of a published OData resource (OData version 4 services only)

2022-10-06 13:51 UTC, sbont requested changes

2022-10-06 13:51 UTC, sbont commented on content/en/docs/refguide/modeling/integration/wrap-services-odata.md
> +Select a combination of attribute with the following constraints:
missing s "attribute**s**"

2022-10-06 13:51 UTC, sbont commented on content/en/docs/refguide/modeling/integration/wrap-services-odata.md
> +3. In the **Key Selection** dialog box, move the key attributes to the right side.
In this line (and in the topics above) we talk about "attributes" (plural), in the previous lines we mention key as a singular thing - should we word it here more consistently?

2022-10-06 13:55 UTC, joostverhoog commented on content/en/docs/refguide/modeling/integration/wrap-services-odata.md
> +Select a combination of attribute with the following constraints:
That's indeed a typo

2022-10-06 13:56 UTC, joostverhoog commented on content/en/docs/refguide/modeling/integration/wrap-services-odata.md
> +3. In the **Key Selection** dialog box, move the key attributes to the right side.
An entity has a single key (singular), consisting of one or more attributes. Could you indicate where you see inconsistencies?

2022-10-06 14:22 UTC, sbont commented on content/en/docs/refguide/modeling/integration/wrap-services-odata.md
> +3. In the **Key Selection** dialog box, move the key attributes to the right side.
I mean that in line 55 of published-odata-resource we mention `3.1 Selecting Attributes as the Key`, in this paragraph title and line 141 we only use the singular of `attribute`. Hope this clarifies

2022-10-07 06:01 UTC, joostverhoog commented on content/en/docs/refguide/modeling/integration/wrap-services-odata.md
> +3. In the **Key Selection** dialog box, move the key attributes to the right side.
I see. I changed lines 127, 139 and 141. I think my confusion was that this comment is about line 145, and that line seems fine.

2022-10-11 12:23 UTC, johannahemminger approved these changes

2022-10-25 09:56 UTC, merged