[WTF-1212] Add explanation for fallback text feature
mendix/docs pull request #5163
Opened 2022-10-11 16:46 UTC by legio-vi-ferrata

**NOTE:** This documentation change is for an existing feature that hasn't been described in the docs; therefore the changes in this PR are applicable immediately.

2022-10-12 12:30 UTC, legio-vi-ferrata commented
@tamelbrun is kindly invited for a review. :)

2022-10-12 14:28 UTC, tamelbrun requested changes

2022-10-12 14:28 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. When used with parameters, every parameter annotation in the text is replaced with the value of their corresponding attributes
Parameters can also be expressions, so we should mention those too. And it feels like "a greeting message to a user" was a lot less random than "information about a book". (What book? How book? Why book? :P) Maybe we can expand that example a bit more. Something like _"For example, if you have a page that deals with books, you can show information about a particular book by..."_ etc.?

2022-10-12 14:28 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +Parameters are essentially attributes whose values will be displayed. To view **Parameters**, do one of the following:
I would get rid of _essentially_ (clutter). And the same applies here: parameters can also be expressions (which the current documentation seems to blissfully ignore :P).

2022-10-12 14:28 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +6. In the **Fallback text** setting, write the text you would like to display when a context object is not available from the surrounding data widget.
Small improvement: _"...when no context object is available from the surrounding data widget"_.

2022-10-12 14:39 UTC, legio-vi-ferrata commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. When used with parameters, every parameter annotation in the text is replaced with the value of their corresponding attributes
Perhaps, that hypothetical data view listens to a list view and then the fallback text would be functioning for until the end-user selects an item from the list? (Something like: "You need to select a book from the list.") That would be much more like a real-world scenario I guess compared to what I have been focused on: making the user (technically) understand that it is the lack of a whole object, not just an empty attribute. :D

2022-10-12 16:39 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. When used with parameters, every parameter annotation in the text is replaced with the value of their corresponding attributes
I was thinking about a similar scenario, yeah 👍🏻. Good thing that you needed to update all the screenshots anyway... ;)
(But let's double-check that having no selection is possible for list views, otherwise a data grid would be a better example.)

2022-10-14 14:12 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +6. In the **Fallback text** setting, write the text you would like to display when a context object is not available from the surrounding data widget.
Done.

2022-10-14 14:12 UTC, legio-vi-ferrata commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +Parameters are essentially attributes whose values will be displayed. To view **Parameters**, do one of the following:
Done.

2022-10-14 14:15 UTC, legio-vi-ferrata commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. When used with parameters, every parameter annotation in the text is replaced with the value of their corresponding attributes
Done.

2022-10-14 14:25 UTC, tamelbrun requested changes

2022-10-14 14:25 UTC, tamelbrun commented on content/en/docs/refguide/modeling/application-logic/expressions/_index.md
> +## 19 Parse & Format Decimal Function Calls(#expressions-formatter-functions)
These should be curly braces, right? (And a space before. :))

2022-10-14 14:25 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +Parameters are attributes or expressions whose values will be displayed as part of the text defined in the caption setting. To view **Parameters**, do one of the following:
I think that should be `**Caption**`.

2022-10-17 10:18 UTC, legio-vi-ferrata commented
Screenshots are outdated relative to the previous adjustments.

2022-10-18 15:27 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/refguide/modeling/application-logic/expressions/_index.md
> +## 19 Parse & Format Decimal Function Calls(#expressions-formatter-functions)
Done.

2022-10-18 15:27 UTC, legio-vi-ferrata commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +Parameters are attributes or expressions whose values will be displayed as part of the text defined in the caption setting. To view **Parameters**, do one of the following:
Done.

2022-10-18 15:51 UTC, tamelbrun requested changes

2022-10-18 15:51 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. A parameter can be an attribute of a context object or an [expression](/refguide/expressions/) which also have access to the s
- _...an expression which also **has** access to..._
- _...with the value of its corresponding attribute or expression._ (A single parameter has a single attribute or expression, so using plural here is wrong.)
- I just noticed that this says "listen to this data grid", but the screenshot says "listens to widget 'bookListView'" 🙈

2022-10-19 09:28 UTC, legio-vi-ferrata commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. A parameter can be an attribute of a context object or an [expression](/refguide/expressions/) which also have access to the s
Done.

2022-10-19 16:56 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. When used with parameters, every parameter annotation in the text is replaced with the value of their corresponding attributes
✨

2022-10-19 16:56 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +Parameters are essentially attributes whose values will be displayed. To view **Parameters**, do one of the following:
✨

2022-10-19 16:56 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +6. In the **Fallback text** setting, write the text you would like to display when a context object is not available from the surrounding data widget.
✨

2022-10-19 16:56 UTC, tamelbrun commented on content/en/docs/refguide/modeling/application-logic/expressions/_index.md
> +## 19 Parse & Format Decimal Function Calls(#expressions-formatter-functions)
✨

2022-10-19 16:56 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +Parameters are attributes or expressions whose values will be displayed as part of the text defined in the caption setting. To view **Parameters**, do one of the following:
✨

2022-10-19 16:56 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. A parameter can be an attribute of a context object or an [expression](/refguide/expressions/) which also have access to the s
✨

2022-10-20 12:38 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. A parameter can be an attribute of a context object or an [expression](/refguide/expressions/) which also has access to the su
What is "parameter annotation"? A caption?
I would also link to the Parameters section below to avoid confusion with page parameters.

2022-10-21 09:41 UTC, tamelbrun commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. A parameter can be an attribute of a context object or an [expression](/refguide/expressions/) which also has access to the su
Ah, I missed that one: that should be "parameter placeholder", which is the terminology used in consistency errors as well. (They show up as {1}, {2}, etc. in the screenshots.)

2022-10-21 12:22 UTC, ConnorLand commented on content/en/docs/refguide/modeling/pages/text-widgets/text.md
> +The text widget displays a text which can optionally contain parameters. A parameter can be an attribute of a context object or an [expression](/refguide/expressions/) which also has access to the su
Awesome Mert. I've updated the term here: https://github.com/mendix/docs/pull/5163/commits/5288f222acc2c2d07aa7c788e652cc28028e3079

2022-10-24 11:16 UTC, ConnorLand approved these changes

2022-10-24 11:22 UTC, merged