[WTF-1175] Add reference documentation for return type depending on another property (9.20)
mendix/docs pull request #5181
Opened 2022-10-14 17:20 UTC by legio-vi-ferrata

**IMPORTANT**: This PR is currently in the process of internal review by WTF team.

New Feature: WTF-1173

2022-10-17 10:09 UTC, tamelbrun requested changes

2022-10-17 10:09 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +
I think this is redundant. We already refer to expression property at the beginning of this section _and_ it already mentions that the type `<T>` depends on the return type of the expression property.

2022-10-17 10:09 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `[Property Path]`      | `DynamicValue<T>` where `T` will depend on the configured types of the target attribute |
We should not put this into a single table, as the last entry refers to the contents of a completely different XML attribute (and thereby conflicts with the earlier statement about `[Type]`). It would be better to create two subsections, one for `type` and one for `assignableTo`, and avoid the `[replacement value]` concept altogether. (I reserve the right to have review comments on the rewritten version later. :P)

2022-10-17 10:09 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +{{% /alert %}}
Feels like overkill. Changing the first line of 4.1.2 to "...must contain a single `<returnType>` element" would be sufficient.

2022-10-17 10:09 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`assignableTo` attribute was introduced in Mendix [9.20](/releasenotes/studio-pro/9.20/).
- `The` is missing :)
- I don't think we link to the release notes anywhere else in the docs where we mention a version-specific feature. (One could also argue that it's a bit redundant to link to release notes which mention a feature which they have already found in the docs. :P)
- Maybe we should also mention (once the `type` / `assignableTo` split is done) that `type` was required in Mendix 9.19 and earlier.

2022-10-17 12:55 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +
Done.

2022-10-17 12:57 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +
This removal caused one of the section links (that I added in the first place) to become redundant. Along with it, I contributed a small improvement for other section links as well.

2022-10-17 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `[Property Path]`      | `DynamicValue<T>` where `T` will depend on the configured types of the target attribute |
Updated, ready for review.

2022-10-17 13:24 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +{{% /alert %}}
Done.

2022-10-17 13:27 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`assignableTo` attribute was introduced in Mendix [9.20](/releasenotes/studio-pro/9.20/).
- Grammar is fixed.
- Added an info box about the pre-9.20 behaviour
- Release notes actually seem to be everywhere but as an example this one's right from home => 

> ### 4.5 Association {#association}
> 
> {{% alert color="info" %}}
> This property type was introduced in Mendix [9.13](/releasenotes/studio-pro/9.13/).
> {{% /alert %}}
> 
> The association property type allows a widget to work directly with both reading and writing associations between entities. Depending on the widget's purposes, a widget should define association types it supports.
> 
> If a `dataSource` attribute is not specified the client will receive a `ReferenceValue` for references (singular references), a `ReferenceSetValue` for reference sets (multiple references), or a union of them. For more information, see the [ModifiableValue](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis/#modifiable-value) section of *Client APIs Available to Pluggable Widgets*.
> 
> `When a `dataSource` attribute is specified and configured by the user, it is passed as a [`ListReferenceValue` or `ListReferenceSetValue`](/apidocs-mxsdk/apidocs/pluggable-widgets-client-apis-list-values/#listassociationvalue) depending on the configuration of the property. For more information, see the [Datasource](#datasource) section below.
> 
> {{% alert color="info" %}}
> The ability to link association properties to a data source was introduced in Mendix [9.17](/releasenotes/studio-pro/9.17/).
> {{% /alert %}}`

2022-10-17 13:34 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`assignableTo` attribute was introduced in Mendix [9.20](/releasenotes/studio-pro/9.20/).
Ah, I stand corrected! Maybe this was done afterwards by the docs team, we didn't have those links in the past. Then by all means, keep them in ;). I'll take a look at the rest.

2022-10-17 13:59 UTC, tamelbrun requested changes

2022-10-17 13:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The `<returnType>` (required) — An expression property must contain a `<returnType>` element in order to define the return type of the expression. The Mendix Platform will ensure the that configured
"The" is not required here: `<returnType>` is code, not a noun :).

2022-10-17 13:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
I would use a table, similar to the other tables for XML attributes.

My suggestion for terminology:
```
`type` | No | String | A fixed return type, which must be one of the supported fixed return types
`assignableTo` | No | Property Path | Specifies the path to an [`attribute`](#attribute) property which will determine the return type when configured
```

I think we can also mention more clearly that one of the two attributes _must_ be specified.

2022-10-17 13:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.1 Pre-Determined Return Types
Suggestion: Fixed Return Type

2022-10-17 13:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.2 Attribute Dependent Return Type
Suggestion: Return Type Assignable To An Attribute

Suggestion for phrasing: "You can use `assignableTo` to specify that the return type of the expression property should depend on the attribute property with the given property path. This means that the value of the expression will be _assignable_ to the attribute configured for that attribute property (using `setValue`).

(I'm avoiding attribute-as-in-XML here to avoid confusion. We can probably link to some things to clarify even further. And I'm name-dropping "assignable" here as much as possible. :D)

We won't need a table for this one, but we do need an example that shows the resulting union type if the attribute property has more than one possible type.

2022-10-17 15:44 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The `<returnType>` (required) — An expression property must contain a `<returnType>` element in order to define the return type of the expression. The Mendix Platform will ensure the that configured
🤦‍♂️ Fixed.

2022-10-17 16:06 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
Updated, ready for review.

2022-10-17 16:09 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
I kept the description paragraph but I'm feeling like it is redundant, too. I'd like to hear what you think.

2022-10-17 16:11 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
And for the description, I kind of favored "in a pre-determined way" over "fixed way"; should I revise it?

2022-10-17 17:01 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.2 Attribute Dependent Return Type
Done except for the links for clarification. Can you give me an example?

2022-10-17 17:07 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
I would avoid the "way" altogether :). For example:

_The return type of an expression can be defined using either the `type` or the `assignableTo` attribute._

This should be enough information, given that the table explaining them follows immediately.

2022-10-17 17:16 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +{{% /alert %}}
Using a warning box for this feels too intrusive. See my other comment for a suggestion on how to merge this into the sentence above the table.

2022-10-17 17:17 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can set a pre-determined return type for your expression property with one of the supported types from the table.
pre-determined -> fixed

Suggestion: _...with one of the supported fixed types below._

2022-10-17 17:19 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can use `assignableTo` to specify that the return type of the expression property should depend on the attribute property with the given property path. This means that the value of the expression
Maybe we have a suitable link for `setValue`?

2022-10-17 17:29 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `[Property Path]` | `DynamicValue<T>` where `T` will depend on the configured types of the target attribute |
No need to use a table for this, we have already specified that the XML attribute is a property path. Let's focus on the typings here.

Suggestion, make it two sentences: _The client component will receive a `DynamicValue<T>` where `T` depends on the possible types of the target attribute. If the attribute property allows for more than one type, the type of the actual value depends on the attribute that has been configured._

That last part is to reduce possible confusion over what that union type really means. I would propose a similar addition below the example.

2022-10-17 17:40 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The client component will receive the prop (for the expression property) with the value `DynamicValue<string | boolean>`.
DynamicValue is a type, not a value.

Suggestion: _The client component will receive a `myExpression` prop of type `DynamicValue<string | boolean>`._ (This is more in line with the wording used elsewhere, but adjusted to refer to this specific example.)

Suggestion to add: _This is a union type of all possible value types for the expression. The actual type of the value depends on the attribute configured for the `myAttribute` property. For an attribute of type `String`, the value will be a `string`; otherwise, it will be a `boolean`._

2022-10-17 17:44 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.2 Attribute Dependent Return Type
See my comment below, I was thinking primarily of `setValue` (in `EditableValue`).

2022-10-18 02:31 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
Done.

2022-10-18 02:31 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.1 Pre-Determined Return Types
Done.

2022-10-18 02:32 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.2 Attribute Dependent Return Type
Continuing from the comment down below.

2022-10-18 02:33 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +{{% /alert %}}
Done.

2022-10-18 02:33 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can set a pre-determined return type for your expression property with one of the supported types from the table.
Done.

2022-10-18 02:38 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can use `assignableTo` to specify that the return type of the expression property should depend on the attribute property with the given property path. This means that the value of the expression
Done, but I used the section link for editable values but the specific part for `setValue` is among the description down to the section heading. I am not sure if it is going to be obvious for someone who navigates using this link.

Do we have a technique for anchoring to a paragraf?

2022-10-18 02:38 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `[Property Path]` | `DynamicValue<T>` where `T` will depend on the configured types of the target attribute |
Done.

2022-10-18 02:39 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The client component will receive the prop (for the expression property) with the value `DynamicValue<string | boolean>`.
Done.

2022-10-18 11:37 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can use `assignableTo` to specify that the return type of the expression property should depend on the attribute property with the given property path. This means that the value of the expression
I'm not sure, but I think that linking to `EditableValue` while mentioning `setValue` in the link is probably good enough :).

2022-10-19 16:58 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/pluggable-widgets-client-apis-list-values.md
> +
✨

2022-10-19 16:58 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `[Property Path]`      | `DynamicValue<T>` where `T` will depend on the configured types of the target attribute |
✨

2022-10-19 16:58 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +{{% /alert %}}
✨

2022-10-19 16:58 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`assignableTo` attribute was introduced in Mendix [9.20](/releasenotes/studio-pro/9.20/).
✨

2022-10-19 16:58 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The `<returnType>` (required) — An expression property must contain a `<returnType>` element in order to define the return type of the expression. The Mendix Platform will ensure the that configured
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +An expression's return type can be defined in a pre-determined way using `type` attribute, or you set the return type to be always the same with the widget's another attribute property using `assigna
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.1 Pre-Determined Return Types
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +##### 4.1.2.2 Attribute Dependent Return Type
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +{{% /alert %}}
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can set a pre-determined return type for your expression property with one of the supported types from the table.
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +You can use `assignableTo` to specify that the return type of the expression property should depend on the attribute property with the given property path. This means that the value of the expression
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `[Property Path]` | `DynamicValue<T>` where `T` will depend on the configured types of the target attribute |
✨

2022-10-19 16:59 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The client component will receive the prop (for the expression property) with the value `DynamicValue<string | boolean>`.
✨

2022-11-25 14:43 UTC, ConnorLand approved these changes

2022-11-29 14:27 UTC, merged