Updates to integration landing page
mendix/docs pull request #5239
Opened 2022-10-28 12:43 UTC by johannahemminger

2022-10-31 07:18 UTC, joostverhoog requested changes

2022-10-31 07:18 UTC, joostverhoog commented on content/en/docs/refguide/modeling/integration/_index.md
> +Lack of contracts and schemas give you an easy start to using REST. However, many REST endpoints return complex data.
REST does have contracts (OpenApi) and schemas (JSON schema). It is true that they are not required (as written in line 16), but this line suggest that they are not there. Studio Pro even supports both.

2022-10-31 08:10 UTC, sbont commented on content/en/docs/refguide/modeling/integration/_index.md
> +OData is a set of best practices for building REST APIs that standardizes many aspects of REST APIs. It describes how you should provide filtering, sorting, and pagination on your resources, as well
I think that the `(see Expose Data to BI Tools Using OData)` bit misses the link to https://docs.mendix.com/howto/integration/exposing-data-to-bi-tools-using-odata/

2022-11-01 07:52 UTC, johannahemminger commented on content/en/docs/refguide/modeling/integration/_index.md
> +Lack of contracts and schemas give you an easy start to using REST. However, many REST endpoints return complex data.
Yeah that's a strange line, will get rid of it. Thanks!

2022-11-01 08:02 UTC, merged