BAPI using SNC Connection
mendix/docs pull request #5358
Opened 2022-11-28 15:32 UTC by MarkvanMents

2022-12-07 07:55 UTC, gauravkrshah requested changes
Hi Mark, kindly look at review comments and let me know if any more details required.

2022-12-07 07:55 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-bapi-connector.md
> +#### 6.1.1 Using an SNC Connection
This should go in parallel to section 4.1#SAP System Connection Details.
so connecting to SAP system using SNC is an alternative way to provide connection details for setting development environment using Studio Pro.
We still have to find out how to run it on SAP BTP, so for now let's mention it for running in Studio pro for local set up

2022-12-07 07:55 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-bapi-connector.md
> +The values for the properties can be found in the **Connection Properties** of the BAPIs which you can see by right-clicking the BAPI in the **SAP GUI for Java**. The options from the **Expert Settin
These are not connection properties of BAPI, it is connection properties of SAP server. so we can put it like:
values for the properties can be found in the **Connection Properties** of the SAP server to want to connect. Go to SAP GUI (don't mention of Java) and view "connection Properties" of the SAP server to connect. 
blurred the parameter values as this is specific to Siemens system, not to make public.

2022-12-07 16:20 UTC, MarkvanMents commented
@gauravkrshah 
Hi Gaurav,
I've made some changes based on your comments. Does it look better now? Thanks.

2022-12-08 09:30 UTC, gauravkrshah approved these changes
Looks Good

2022-12-08 11:25 UTC, MarkvanMents commented
Update already released - publication approved over Slack.

2022-12-08 11:25 UTC, merged