Add reference documentation for snippet parameters
mendix/docs pull request #5403
Opened 2022-12-07 12:43 UTC by jeffersonRibeiro

This PR add reference documentation for the new to be released `Snippet Parameters` in Studio Pro 9.21.

Updates:
- Snippet ref guide to include parameters
- Snippet call to include snippet settings
- Data view ref guide to include snippet parameters as context data source
- Add new consistency errors CE1154, CE1570 and CE8116
- Screenshots

2022-12-13 09:02 UTC, mlaponder requested changes

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
typo: "paramenters" -> "parameters".

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
Zero or many sounds a bit odd to me, I think zero or more is more common. I think we can polish this sentence a bit, st like (mostly stolen from page parameters ;-) ):

A snippet defines the list of parameters it expects. To change the parameters of the snippet, click the Parameters button in the top bar. This opens a dialog box which allows you to add, modify, and remove parameters. The Parameters button shows the current number of parameters in its caption, while its tooltip shows the name and type of each parameter. For more information about snippet parameters, see the [Parameters](add link here) section in snippet properties.

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +In the example below, the snippet is defining 1 parameter of name **Order** and type **MyFirstModule.Order**.
defines a single parameter with name ...

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +**Snippet Parameters** work the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level without the need for a Data View or any
Why the 1 parameter restriction? I can have multiple parameters and select attributes from snippet parameters and use the parameters by name in expressions right?

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +**Snippet Parameters** work the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level without the need for a Data View or any
I don't think we capitalize "data view" and "data container" in the docs

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
> +The **Snippet** property shows the name of the snippet that the snippet call will invoke
End the sentence with a ".". Maybe just "display" instead of invoke?

2022-12-13 09:02 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
> +The **Snippet settings** property opens a dialog box enabling you to configure the snippet call arguments that will be passed to the snippet
I would make it a bit more explicit: "it opens a dialog which shows a list of parameters of the selected snippetand the objects that will be passed to each of them."

2022-12-13 09:38 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
What do you think of changing the first sentence to this ?

`
A snippet like on page paramenters can expect zero or more parameters. To change the parameters of the snippet, click the Parameters button in the top bar. This opens a dialog box which allows you to...
`

Just to make the text less redundant. The first sentence in the snippet introduction also starts with "snipets define.."

2022-12-13 09:42 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
Fixed ✨

2022-12-13 09:43 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +In the example below, the snippet is defining 1 parameter of name **Order** and type **MyFirstModule.Order**.
Fixed ✨

2022-12-13 09:43 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +**Snippet Parameters** work the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level without the need for a Data View or any
Fixed ✨

2022-12-13 09:44 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
> +The **Snippet** property shows the name of the snippet that the snippet call will invoke
I also prefer "display"

Fixed ✨

2022-12-13 09:46 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
> +The **Snippet settings** property opens a dialog box enabling you to configure the snippet call arguments that will be passed to the snippet
I changed it slightly to:

`
The **Snippet settings** property opens a dialog which shows a list of parameters of the selected snippet and the objects that will be passed to each of them.
`

To make it more consistent with the snippet property. What do you think ?

2022-12-13 10:48 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
As discussed with @mlaponder in a quick call, the text changed to:

`A snippet expects zero or more parameters. To change the parameters of the snippet...`

2022-12-13 10:49 UTC, jeffersonRibeiro commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +**Snippet Parameters** work the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level without the need for a Data View or any
As discussed with @mlaponder in a quick call, the text has been improved to:

`**Snippet Parameters** works the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level, for example when creating expressions or selecting attributes.`

2022-12-13 15:42 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
✨

2022-12-13 15:42 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +A snippet like on page paramenters can accept zero or many parameters. The number of parameters a snippet is defining is indicated by parentheses next to the parameters icon in the top left corner of
✨

2022-12-13 15:43 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +In the example below, the snippet is defining 1 parameter of name **Order** and type **MyFirstModule.Order**.
✨

2022-12-13 15:43 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +**Snippet Parameters** work the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level without the need for a Data View or any
✨

2022-12-13 15:44 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
> +The **Snippet settings** property opens a dialog box enabling you to configure the snippet call arguments that will be passed to the snippet
✨

2022-12-13 15:48 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/structure-widgets/snippet-call.md
> +The **Snippet** property shows the name of the snippet that the snippet call will invoke
✨

2022-12-13 15:48 UTC, mlaponder commented on content/en/docs/refguide/modeling/pages/page-resources/snippet.md
> +**Snippet Parameters** work the same way as [Page Parameter](/studio/page-parameter/) with the difference that snippet's parameter can be accessed at top level without the need for a Data View or any
✨

2022-12-13 15:54 UTC, jeffersonRibeiro commented
@ConnorLand, all the comments by @mlaponder have been resolved. Could you give the last review and approve ?

2022-12-16 10:47 UTC, ConnorLand commented
> @ConnorLand, all the comments by @mlaponder have been resolved. Could you give the last review and approve ?

Yep, on it now.

2022-12-16 13:31 UTC, ConnorLand approved these changes

2022-12-20 08:00 UTC, merged