Database connector for AWS RDS
mendix/docs pull request #5470
Opened 2022-12-28 17:27 UTC by katarzyna-koltun-mx

2022-12-30 08:50 UTC, MarkvanMents requested changes
Hi Kasia,
Content is great.
I just happened to look at it because I wanted to see whether our linter (which Natasa is in the process of automating) would complain about the embedded lists not having spaces above and below them (it does complain about the top level lists if they have no spaces!). It doesn't and Hugo parses them correctly, so it isn't an issue.

You probably haven't finished reviewing this and would have picked up what is in my comments anyway, but since I was looking at the file I picked up a couple of things in the formatting. The linter was helpful with the code block, but doesn't help with the alert formatting unfortunately. I'll talk to Natasa about whether this is something we can add to the linting.

I also added a note about IP addresses which you might want to think about. Let me know if you want to discuss.

Content-wise, the PR looks great.

2022-12-30 08:50 UTC, MarkvanMents commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +        Store the username and password in a safe location.
This looks wrong when built.
For formatting this has to either be on the same line as the alert tag, or start in column 1.
It's a weirdness in markdown/Hugo.

2022-12-30 08:50 UTC, MarkvanMents commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +            ```text {linenos=false}
The linter picked this up as having the wrong indentation (one too far to the right).
Also, sql is a valid language tag, so you could use this to get automatic highlighting.

2022-12-30 08:50 UTC, MarkvanMents commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +        {{% alert color="info" %}}
This has the same issue as the one mentioned above when built. Indented alert blocks are a pain until you get used to them.

2022-12-30 08:50 UTC, MarkvanMents commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +    6. Select the IP address of your Mendix app as the source.
Can you just check on this with the devs? I'm not sure that you can identify a single IP address for an app running on Mendix Cloud - you may have to whitelist all the IP addresses mentioned here: https://docs.mendix.com/developerportal/deploy/mendix-ip-addresses/#22-outgoing-ip (I'm pretty sure it is the outgoing one you are interested in). You may even want to link to this doc?

2023-01-16 15:37 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +            ```text {linenos=false}
Done.

2023-01-16 16:38 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +        Store the username and password in a safe location.
Done.

2023-01-16 16:38 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +        {{% alert color="info" %}}
Done.

2023-01-17 15:27 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/aws/amazon-rds-database-connector.md
> +    6. Select the IP address of your Mendix app as the source.
Done.

2023-01-17 15:55 UTC, merged