Improve Catalog registration explanation
mendix/docs pull request #5477
Opened 2023-01-02 15:50 UTC by johannahemminger

2023-03-15 08:43 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +If you (or your company) have a Mendix license and a Data Hub license, you have a Data Hub Catalog! Log in with your company credentials to hub.mendix.com to see what metadata has been shared in your
A license is not needed to use the Catalog :) Neither a Data Hub, or a Mendix license.

2023-03-15 08:44 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +Data Hub Catalog is an open, standards-based metadata repository that enables Mendix developers and business admins to discover and explore data sources throughout their connected ecosystem. This res
What are business admins, do we use this terminology in other places?

2023-03-15 08:58 UTC, johannahemminger commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +If you (or your company) have a Mendix license and a Data Hub license, you have a Data Hub Catalog! Log in with your company credentials to hub.mendix.com to see what metadata has been shared in your
Wait, then how can someone log into hub.mendix.com if they don't have a Mendix license?

2023-03-15 09:00 UTC, johannahemminger commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +Data Hub Catalog is an open, standards-based metadata repository that enables Mendix developers and business admins to discover and explore data sources throughout their connected ecosystem. This res
No, true, I can adjust the wording here.

2023-03-15 10:18 UTC, thijsrohof requested changes
Hi Johanna, left a few comments and proposed some changes 👍

2023-03-15 10:18 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +Our [Share Data Between Apps](/data-hub/share-data/) guide helps you build an app and use the Catalog to share data. Follow the steps to get a better idea how it works! You can also follow [Write Dat
Maybe be more specific? "use the Catalog to share data between two Mendix apps."

2023-03-15 10:18 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/manage-data-sources/curate.md
> +description: "Describes how to curate and enhance findability of data assets in Data Hub Catalog."
maybe also add understandability? So: "escribes how to curate and enhance findability and understandability"

Although, that does sound a bit odd, maybe use another synonym..

2023-03-15 10:18 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/manage-data-sources/security.md
>  title: "Data Accessibility and Security"
I think we need to revisit this whole section, as this is highly intertwined with External Entities. This page made some sense when looking at it from a Data Hub perspective, but not so much anymore from a single Catalog perspective imho.

2023-03-15 10:18 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/manage-data-sources/user-roles.md
> +* Register published OData V4 Services for non-Mendix apps manually
We support OData v2, 3 & 4 :)

2023-03-15 10:18 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +If you (or your company) have a Mendix license and a Data Hub license, you have a Data Hub Catalog! Log in with your company credentials to hub.mendix.com to see what metadata has been shared in your
Well, you can just create an account right?

2023-03-15 10:19 UTC, thijsrohof commented on content/en/docs/data-hub/data-hub-catalog/get-started.md
> +If you (or your company) have a Mendix license and a Data Hub license, you have a Data Hub Catalog! Log in with your company credentials to hub.mendix.com to see what metadata has been shared in your
A license (any paid plan) is not needed to use the Catalog.

2023-04-06 12:26 UTC, johannahemminger commented on content/en/docs/data-hub/data-hub-catalog/manage-data-sources/security.md
>  title: "Data Accessibility and Security"
I will create a separate Jira issue for this.

2023-04-12 11:55 UTC, merged