Kk aws fixes dynamo
mendix/docs pull request #5501
Opened 2023-01-06 18:08 UTC by katarzyna-koltun-mx

2023-01-09 08:09 UTC, brfreekmx requested changes

2023-01-09 08:09 UTC, brfreekmx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +    {{< figure src="/attachments/appstore/connectors/aws-dynamodb/createobject.png" alt="The microflow with the Create activity added">}}
Could the line on the canvas be aligned so there is no bend in it?

2023-01-09 08:09 UTC, brfreekmx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +    {{< figure src="/attachments/appstore/connectors/aws-dynamodb/addloop.png" alt="The microflow with the loop added">}}
Could the line on the canvas be aligned so there is no bend in it?

2023-01-09 08:09 UTC, brfreekmx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +    {{< figure src="/attachments/appstore/connectors/aws-dynamodb/listtables.png" alt="The ACT_ListTables microflow with the ListTables activity">}}
Could the line on the canvas be aligned so there is no bend in it?

2023-01-10 13:48 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +    {{< figure src="/attachments/appstore/connectors/aws-dynamodb/addloop.png" alt="The microflow with the loop added">}}
Done.

2023-01-10 13:48 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +    {{< figure src="/attachments/appstore/connectors/aws-dynamodb/listtables.png" alt="The ACT_ListTables microflow with the ListTables activity">}}
Done.

2023-01-10 13:48 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +    {{< figure src="/attachments/appstore/connectors/aws-dynamodb/createobject.png" alt="The microflow with the Create activity added">}}
Done.

2023-01-11 08:23 UTC, brfreekmx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +        For more information about the required parameters and how to obtain them, see [AWS Authentication](/appstore/connectors/aws/aws-authentication/).
Can we change this reference, this still implies that the AWS authentication docs explain how to configure it. 
Preferably we mention that the **constants** in these folders should be configured accordingly and next show the table with the constants and the explanation for it. This I think is now in the "constants" section of this doc.

2023-01-11 08:23 UTC, brfreekmx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
>  To help you work with the Amazon DynamoDB connector, the following sections of this document list the available entities, enumerations, and activities that you can use in your application.
It seems like the doc skips from chapter 1 to chapter 3

2023-01-12 12:38 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
>  To help you work with the Amazon DynamoDB connector, the following sections of this document list the available entities, enumerations, and activities that you can use in your application.
How do you mean? Chapter 2 is Installation. It's a link to another document (general instructions on installing Marketplace connectors) but it's there.

2023-01-12 12:40 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
> +        For more information about the required parameters and how to obtain them, see [AWS Authentication](/appstore/connectors/aws/aws-authentication/).
I've rewritten the section per feedback from Trong, and also made changes to the base AWS Authentication connector doc, to indicate more clearly which parts don't apply to platform-supported connectors. Can you take a look & let me know what you think?

2023-01-12 14:35 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-dynamodb.md
>  To help you work with the Amazon DynamoDB connector, the following sections of this document list the available entities, enumerations, and activities that you can use in your application.
N/m I noticed that the numbering was broken below the microflow config section. Fixed.

2023-01-12 16:25 UTC, merged