Migrating apps to another cloud
mendix/docs pull request #5530
Opened 2023-01-13 12:17 UTC by katarzyna-koltun-mx

2023-01-13 12:18 UTC, katarzyna-koltun-mx commented
Work in progress, I still need to rewrite the doc so it's not focused on v3 migration, but wanted to share it with support

2023-02-01 18:04 UTC, katarzyna-koltun-mx commented
@MarkvanMents I drafted a document about cloud migration. Could you let me know your feedback?

2023-02-01 18:04 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +* Have a [Mendix Cloud](/developerportal/deploy/mendix-cloud-deploy/) node available. This must have the subdomain name `<current-app-name>-v4`. To request a licensed Cloud Node, use the [Request New
I'm not sure if that's correct, where can I verify this?

2023-02-01 18:05 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +1. Open the [Migration Tool](https://v3-v4-migration.mendixcloud.com/), `https://v3-v4-migration.mendixcloud.com/`.
Needs verification.

2023-02-01 18:06 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    4. Renames the subdomain of the original app and all environments to be `<current-app-name>-v3`.
Needs verification

2023-02-01 18:06 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    3. Renames the subdomain of the app running on Mendix Cloud v4 and **all** environments to be `<current-app-name>-v4`
Needs verification

2023-02-07 09:19 UTC, MarkvanMents requested changes
Hi Kasia, (@katarzyna-koltun-mx )
I think we need to find out the status of the migration app. I fear that it wasn't designed for V4 to V4 migrations, and I'm not sure they will want to support it going forwards in any case.

Section 5 looks fine to have in the app - doesn't seem to be Cloud version specific, so I don't think it will need much refinement.

Let me know if you can't find the right person to talk to about the migration tool.

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +This document explains how to migrate your licensed app from one Mendix public cloud datacenter to another.
Perhaps a use case, an example, and/or a link to the list of data centers https://docs.mendix.com/developerportal/deploy/mxcloudv4/#2-where-will-my-data-be-hosted

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +* If you are currently using a VPN to secure your app, you will have to use one of the recommended methods discussed in [Securing Outgoing Connections from Your Application](/developerportal/deploy/s
I don't think these are relevant any more. They were changes between Cloud V3 and Cloud V4.

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +## 4 Using the Migration Tool
Is this migration tool still available? For me it is offline?
It was written specifically for V3 to V4, so I'm not sure it will work for V4 to V4 anyhow.
I think that customers will have to do this manually?

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +* Have a [Mendix Cloud](/developerportal/deploy/mendix-cloud-deploy/) node available. This must have the subdomain name `<current-app-name>-v4`. To request a licensed Cloud Node, use the [Request New
This was the case before, the migration tool used the -v4 suffix automatically when switching between the V3 and V4 app. Need to check with the team behind it - perhaps Ravi Singh would know the best person to talk to?

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +1. Open the [Migration Tool](https://v3-v4-migration.mendixcloud.com/), `https://v3-v4-migration.mendixcloud.com/`.
Seems to be offline for me.

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +Database dump-restore will run twice – once on replication activation, and again on the stop of replication (if the **Interrupt** option has not been set – for details, see the section below). This i
To the new app (both apps are now V4)
```suggestion
Database dump-restore will run twice – once on replication activation, and again on the stop of replication (if the **Interrupt** option has not been set – for details, see the section below). This is to ensure that the latest data on the source database for your application is copied to the new app.
```

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    * If you check the **Interrupt** option, replication will stop as soon as possible when you click **Stop replication** leaving the v4 database in an incomplete and probably inconsistent state. On
```suggestion
    * If you check the **Interrupt** option, replication will stop as soon as possible when you click **Stop replication** leaving the database for the new app in an incomplete and probably inconsistent state. On the Migration Status page you will see the state as *failed* when you select this option.
```

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    4. Renames the subdomain of the original app and all environments to be `<current-app-name>-v3`.
If it calls it v3 that is going to be confusing.
But I'm not sure this app is going to be available?

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    3. Renames the subdomain of the app running on Mendix Cloud v4 and **all** environments to be `<current-app-name>-v4`
```suggestion
    3. Renames the subdomain of the new app and **all** environments to be `<current-app-name>-v4`
```

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    4. Removes the `-v3` suffix from the subdomain name of the original v3 app and **all** environments
The original app is not going to be a v3 app any more.

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +{{% /alert %}}
Not if the migration tool is no longer available.

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +{{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/migrating-to-v4/migratev4.png" >}}
Picture still refers to V3

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +## 5 Migrating the App Manually
I think this is the section that will make it to the final document.

2023-02-07 09:19 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +    {{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/mxcloudv4/migrating-to-v4/download-package.png" >}}
This image has a very old version of Mendix in it. I think I need to look at linking a much more up-to-date app with our production environment!

(It's on my backlog!)

2023-02-21 08:56 UTC, katarzyna-koltun-mx commented
@MarkvanMents I've updated the PR after talking to Ravi - the v3 tool is not used for v4 migrations and has been taken offline.

2023-02-23 12:14 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +* If you are currently using a VPN to secure your app, you will have to use one of the recommended methods discussed in [Securing Outgoing Connections from Your Application](/developerportal/deploy/s
@schrysinas Hi Stamatios, could you take a look at that comment from Mark? Should I delete the above prereqs?

2023-02-23 12:15 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/migrating-to-different-cloud.md
> +This document explains how to migrate your licensed app from one Mendix public cloud datacenter to another.
@schrysinas I'd like to add a use case as Mark suggested. What reason could someone have to migrate their app to a different node?

2023-02-28 16:28 UTC, merged