Update feature release calendar
mendix/docs pull request #5535
Opened 2023-01-16 13:31 UTC by johannahemminger

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/_index.md
> +## 2 Documents in This Category
We usually have **Documents in This Category** for only highest level categories. Please see similar documents for alignment:
https://docs.mendix.com/refguide/object-activities/
https://docs.mendix.com/refguide/workflow-activities/

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
> +category: ML Kit Activities
This is not needed in the metadata.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/_index.md
> +These activities can only be used in **Microflows**.
In similar documents we have this warning per activity.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
> +Studio Pro [9.23](/releasenotes/studio-pro/9.23/) and above supports machine learning (ML) model integration in Mendix apps. Collectively called the *Machine Learning (ML) Kit*, this functionality al
"Runtime" is usually capitalized and called "Mendix Runtime" instead of "Mendix Studio Pro Runtime", please see [Product Naming Guide](Capitalize in instances when referring to Runtime as part of the Mendix Platform. The best practice is to use a definite article for additional clarity: “the Mendix Runtime.").

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
> +## 2 Properties
Please align with similar documents in the category where possible. For example: 
https://docs.mendix.com/refguide/apply-jump-to-option/
https://docs.mendix.com/refguide/aggregate-list/

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/ml-kit-activities/call-ml-model.md
> +* **Output object** – name of the output object (for example, `outputObject`)
Does the activity have a **Common Section** as all other activities? For example: https://docs.mendix.com/refguide/cast-object/

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Studio Pro [9.23](/releasenotes/studio-pro/9.23/) and above supports machine learning (ML) model integration in Mendix apps. Collectively called the *Machine Learning (ML) Kit*, this functionality al
Please see the comment above about Mendix Runtime

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +The ONNX Runtime is based on the ONNX standard, and is an optimized inference engine for efficiently running any model converted to the ONNX format across different hardware and operating systems wit
Please align the capitalization of "Runtime" for both Mendix Runtime and ONNX.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Learn more about the machine learning kit in the following documents:
This duplicates information in Integration, I would keep it in one place.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
> +#If moving or renaming this doc file, implement a temporary redirect and let the respective team know they should update the URL in the product. See Mapping to Products for more details.
Are all of these documents mapped?

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/_index.md
> +## 2 Documents in This Category
Please see my comment above on **Documents in This Category**, it works with only high-level categories.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/_index.md
> +Studio Pro [9.23](/releasenotes/studio-pro/9.23/) and above supports machine learning (ML) model integration in Mendix apps. Collectively called the *Machine Learning (ML) Kit*, this functionality al
We repeat this introduction in several docs. The best practice is to avoid repetition. It is better to have a cross-reference or a shorter introduction.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
> +{{< figure src="/attachments/refguide/modeling/integration/ml-kit/design-patterns/advanced-inference-patterns/design-pattern-ensembles.png" alt="." >}}
alt requires a description of an image, if there is no description, we don't need it, afaik. Applies to other images as well.

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
> +Domain Model of an ensemble model:
```suggestion
An example of a domain model of an ensemble model:
```

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
> +{{< figure src="/attachments/refguide/modeling/integration/ml-kit/design-patterns/advanced-inference-patterns/ensembles-domain-model.png" alt="." >}}
This one is a microflow example, not a domain model as I see in the local build. Please use borders for images according to our style guide (this applies to other images as well).

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
> +Example Microflow
```suggestion
An example of a microflow:
```

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/advanced-inference-patterns.md
> +A model pre-processor makes some data available for the first model, and the output is injected into the second model as an input. Ultimately, that output will be used for the final prediction.
```suggestion
A model pre-processor makes some data available for the first model, and the output is injected into the second model as an input. Ultimately, that output is used for the final prediction.
```

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/mapping-documents/ml-model-mapping.md
> +For a list of supported models, see [Supported Frameworks and Libraries](/refguide/machine-learning-kit/using-ml-kit/#supported-frameworks).
```suggestion
For a list of supported models, see the [Supported Frameworks and Libraries](/refguide/machine-learning-kit/using-ml-kit/#supported-frameworks) section in *Using ML Kit*.
```

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/mapping-documents/ml-model-mapping.md
> +1. Convert your model to ONNX format (see [Converting Your Model to ONNX](/refguide/machine-learning-kit/using-ml-kit/#convert-ml-model)).
```suggestion
1. Convert your model to ONNX format (see the [Converting Your Model to ONNX](/refguide/machine-learning-kit/using-ml-kit/#convert-ml-model) section in *Using ML Kit*).
```

2023-02-27 16:21 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/mapping-documents/ml-model-mapping.md
> +3. Click **Import model** to import your ONNX file.
I would also add a screenshot with a ML Model mapping example and a **Read More** section with cross-references to Machine Learning Kit category. 
Does ML Model Mapping have any properties?

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +To use the ML model in your app, you will import it to create a mapping document.
```suggestion
To use the ML model in your app, you import it to create a mapping document.
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +This will generate two non-persistable entities representing your ML Model input and outputs (see [Persistable and Non-Persistable Entities](#persist-nonpersist-entities) below).
```suggestion
This generates two non-persistable entities representing your ML Model input and outputs (see [Persistable and Non-Persistable Entities](#persist-nonpersist-entities) below).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +This will generate two non-persistable entities representing your ML Model input and outputs (see [Persistable and Non-Persistable Entities](#persist-nonpersist-entities) below).
```suggestion
This will generate two non-persistable entities representing your ML Model input and outputs (see the [Persistable and Non-Persistable Entities](#persist-nonpersist-entities) section below).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +If error CE1790 appears, you will need to [set dynamic tensor shapes](#set-dynamic-shapes).
```suggestion
If error CE1790 appears, you need to [set dynamic tensor shapes](#set-dynamic-shapes).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The ML model in ONNX format will be placed in the `mlsource/<your_module_name>` folder from the App/Show App Directory in Explorer.
Please see our style guide on using the Future Tense, we try to use Present Tense where possible.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +###### 2.2.2.2.1 Setting Dynamic Tensor Shape Mapping (Error 1790) {#set-dynamic-shapes}
By "Error" do you mean consistency error? They are usually referred to as CE{error_number} in docs because this is how they appear in the UI for users.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +{{% alert color="info" %}}Some these shapes should be handled in [Java Action pre- and post-processors](#java-pre-post) you may have.{{% /alert %}}
```suggestion
{{% alert color="info" %}}Some of these shapes should be handled in [Java Action pre- and post-processors](#java-pre-post) you may have.{{% /alert %}}
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +You now have a [peristable](/refguide/persistability/) entity in your domain model that you can set as the type you need, and that can be used in [pre- and post-processors](#pre-post-processors).
```suggestion
You now have a [persistable](/refguide/persistability/) entity in your domain model that you can set as the type you need, and that can be used in [pre- and post-processors](#pre-post-processors).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Drag and drop the [Call ML model](/refguide/call-ml-model/) activity from the toolbar in the Microflow editor to use call and use your ML model in your application logic..
```suggestion
Drag and drop the [Call ML model](/refguide/call-ml-model/) activity from the Toolbox in the microflow editor to use call and use your ML model in your application logic.
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The **Call ML model** activity is an **ML Kit** activity in the **Toolbar**. Detailed documentation on the properties of this activity can be found in the [Call ML model](/refguide/call-ml-model/) pa
```suggestion
The **Call ML model** activity is an **ML Kit** activity in the **Toolbox**. Detailed documentation on the properties of this activity can be found in the [Call ML model](/refguide/call-ml-model/) page.
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The **Call ML model** activity is an **ML Kit** activity in the **Toolbar**. Detailed documentation on the properties of this activity can be found in the [Call ML model](/refguide/call-ml-model/) pa
Please see the cross-reference style in our Style guide.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +{{< figure src="/attachments/refguide/modeling/integration/ml-kit/ml-kit/ml-model-created-entities.png" alt="Example of a netron.app schema." >}}
This is not the best practice to have several images one by one without a text. Can the description be added? Or can they be grouped in one image/diagram?

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Create pre-processed inputs with **Create object** activity for inference inside your Mendix App, and consume the inference output with microflow [expressions](/refguide/expressions/).
```suggestion
Create pre-processed inputs with **Create object** activity for inference inside your Mendix app, and consume the inference output with microflow [expressions](/refguide/expressions/).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +A **Create Object** activity is used for the first part in order to transfer entities from the Domain Model to the model input object.
```suggestion
A **Create Object** activity is used for the first part in order to transfer entities from the domain model to the model input object. 
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +{{< figure src="/attachments/refguide/modeling/integration/ml-kit/ml-kit/create-object.png" alt="Details of the log message in a microflow example." >}}
This is not the best practice to have several images one by one without a text. Can the description be added? Or can they be grouped in one image/diagram?

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Integrating machine learning models can sometimes require using a more complex structure. This incudes having a pre-processor, the model itself, and a post-processor:
```suggestion
Integrating machine learning models can sometimes require using a more complex structure. This includes having a pre-processor, the model itself, and a post-processor:
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The *pre-processor* is the block of code that manipulates the data before being injected into the model. Some common examples of the pre-processing are [normalization](https://towardsdatascience.com/
Please see our style guide for links and cross-references.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Currently, it is required to have any multidimensional data as a string encoded using the base64 format. Any multidimensional data has to be encoded, either in string base64 format if you are using n
```suggestion
Currently, it is required to have any multidimensional data as a string encoded using the base64 format. Any multidimensional data has to be encoded, either in string base64 format if you are using non-persistable entities, or binary streams if you opt for persistable entities for the model in the mapping (see the [Persistable and Non-Persistable Entities](#persist-nonpersist-entities) section in this document).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +In this example, the [Call ML Model][Call ML model](/refguide/call-ml-model/) activity adapts to the model output. If you intend to use a multidimensional output in this stage (such as in the ResNet)
The link to the section is missing
```suggestion
In this example, the [Call ML Model][Call ML model](/refguide/call-ml-model/) activity adapts to the model output. If you intend to use a multidimensional output in this stage (such as in the ResNet), it will come out string-encoded using base64, and will probably require post-processing.
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Once you import your model, the Call ML Model activity allows you to add your input variable coming from the previous action, and name your output to be used in any ulterior steps:
```suggestion
Once you import your model, the **Call ML Model** activity allows you to add your input variable coming from the previous action, and name your output to be used in any ulterior steps:
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Data transformations are usually complex tasks, and often require mathematical libraries or even more complex pieces of software (think OpenCV for computer vision). As a result, sometimes they are no
```suggestion
Data transformations are usually complex tasks, and often require mathematical libraries or even more complex pieces of software (think OpenCV for computer vision). As a result, sometimes they are not integrated into the model. In this case, the best way to perform these transformations in Mendix is using Java Actions (see [Extending Your Application with Custom Java](/refguide/extending-your-application-with-custom-java/)).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +#### 3.2.1 Pre-processing using Java Actions
```suggestion
#### 3.2.1 Pre-processing Using Java Actions
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +This uses a [Random Forest](https://www.kaggle.com/code/prashant111/random-forest-classifier-tutorial) example trained with the Iris/Setosa dataset. The output is a long value, representing a flower
"This" what? section?

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The rationale for using a post-processor is quite similar to the pre-processor but in the opposite direction. We’re going to extract something out of the model and do something with it. For more comp
"We’re going to extract something out of the model and do something with it."
this phase is very unclear to me. We also avoid using "we" because it usually means "we, Mendix". Here it means "you" - you, as a user, are going to do something. I would rewrite this sentence and make it clear what a user is going to do.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +To learn more about design patterns that can be applied to the Inference process, and specifications that for pre/post-processing while using Mendix components, Java Actions, or embedding it into the
```suggestion
To learn more about design patterns that can be applied to the Inference process, and specifications that for pre/post-processing while using Mendix components, Java actions, or embedding it into the model directly, see our documentation on [Design Patterns](/refguide/machine-learning-kit/design-patterns/).
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +See [Versioning] for details on versioning schemes
For details on versioning schemes, see the [Versioning](#versioning) section below.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +{{< figure src="/attachments/refguide/modeling/integration/ml-kit/ml-kit/advanced-model-rendering.png" alt="Example of how two models are rendered by the call ML model activity." >}}
Is this image a table? It is quite small and does present it in the best way. Please consider redoing it in Snagit.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The [Monitoring and Troubleshooting](/howto/monitoring-troubleshooting/) guide in Studio Pro helps
Please follow our style guide for cross-references.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +Typically microflows that contain an MLKit activity may also be composed of various helper activities (e.g. Java Actions, Aggregate List Activities) in order to provide necessary input features to th
```suggestion
Typically microflows that contain an MLKit activity may also be composed of various helper activities (e.g. Java actions, Aggregate List activities) in order to provide necessary input features to the model or parse its outputs. Tools that are provided by Studio Pro can be easily used for monitoring and troubleshooting. 
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +    Warning
We usually do not document warnings. Do error codes have these links in the Errosr Pane?

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +    Error
If the description of the error duplicates what is written in the UI I would remove it for maintenance pusposes. We usually add extra guidance when we document errors.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/using-ml-kit/_index.md
> +The responsibility of the Mendix Runtime is to make an inference call on the model which is integrated into an app via the `Call ML Model` activity. While making a prediction on the model, Mendix Run
```suggestion
The responsibility of the Mendix Runtime is to make an inference call on the model which is integrated into an app via the **Call ML Model** activity. While making a prediction on the model, Mendix Runtime publishes several metrics on the ML Engine log node available in the Console and application logs. These instance-based metrics are provided in each inference call to provide insights to the Mendix developers.
```

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/pre-post-processor-patterns.md
> +A post-processor activity
Please add a sentence before the image, and a ":". This applies to other images in this doc.

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/pre-post-processor-patterns.md
> +Let’s take a look into some examples.
We avoid using "us", the user themselves looks at exmaples, without us,

2023-02-27 17:07 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/design-patterns/pre-post-processor-patterns.md
> +#### 1.2.2 Java Actions for data transformation features
Capitalization

2023-02-27 17:22 UTC, MariaShaposhnikova commented
Hey Johanna,
That is a lot of work done for this documentation! 
I added comments but they are not critical, you can implement them also after the release and merge. I tried adding some in suggestions that I hope you find easier to accept or reject than a usual comment.

2023-02-28 09:12 UTC, merged

2023-02-28 12:12 UTC, amirap requested changes

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Studio Pro [9.23](/releasenotes/studio-pro/9.23/) and above supports machine learning (ML) model integration in Menidx apps. Collectively called the *Machine Learning (ML) Kit*, this functionality is
supports machine learning (ML) model integration in Menidx apps >>> 
supports a novel approach for integrating machine learning (ML) models in Mendix apps

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Studio Pro [9.23](/releasenotes/studio-pro/9.23/) and above supports machine learning (ML) model integration in Menidx apps. Collectively called the *Machine Learning (ML) Kit*, this functionality is
Menidx > Mendix

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +To use a ML model in your app, you need to convert it to ONNX, then import it to create a model mapping.
a ML model > an ML model

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +To use a ML model in your app, you need to convert it to ONNX, then import it to create a model mapping.
create a model mapping > create an ML model mapping

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +To embed your ML model into a Mendix app, you need to convert your model into the ONNX format. Depending upon the frameworks and tools used to create the ML model, there are many tools and sources to
To embed your ML model into a Mendix app > To embed your ML model into a Mendix app using the ML Kit

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Examples include the following:
<img width="803" alt="Screenshot 2023-02-28 at 10 47 16" src="https://user-images.githubusercontent.com/9138856/221815663-0780244b-fd3f-4933-b30f-b1cf45cc49ff.png">

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Examples include the following:
This is the one we had in confluence. I suggest to add this, either as a pic or preferable extract the urls and add them as bulletpoint

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +To use the ML model in your app, you will import it to create a mapping document.
you will import it to create a mapping document. > you need to import it to create an ML mapping document.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +### 2.2 Importing a Model and Creating the Mapping {#import-model}
Importing a Model and Creating the Mapping > Importing an ML Model and Creating the ML Mapping Document

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Several models (including EasyOCR and Yolo) have tensors with dynamic shapes. In these cases, decide on a tensor mapped static shape and attribute type in a mapped entity before integrating in microf
In these cases, decide on a tensor mapped static shape and attribute type in a mapped entity before integrating in microflows. > In these cases, fill in a tensor shape and an attribute type in the mapped entity.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +{{% alert color="info" %}}Some these shapes should be handled in [Java Action pre- and post-processors](#java-pre-post) you may have.{{% /alert %}}
Some might need to handle some of dynamic tensor shapes in [Java Action pre- and post-processors](#java-pre-post) > Some of these shapes should be handled in [Java Action pre- and post-processors](#java-pre-post) you may have.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +After importing a model, two [non-persistable](/refguide/persistability/) entities will be created using the input type.
After importing a model, two [non-persistable](/refguide/persistability/) entities will be created using the input type. > After importing a model, two [non-persistable](/refguide/persistability/) entities will be created using the ML model input and output.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +### 2.3 Using the Model in a Microflow {#use-model-microflow}
I suggest using the 'ML' in all titles > Using the ML Model ...

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +For non-structured data, such as most of the tensors for Neural Networks, an entity attribute will be a `String`.  This is because Base64 is used to to encode the tensors to and from MLKit.
Clarify using the slack conversation

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +##### 2.4 Logistic Regression Example
this seems to have a wrong header level, it's 2.4 but shows as x.x.x.x.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +##### 2.3.1.2 Call ML Model Activity Details
Perhaps its 2.3.2?

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +In this example, the [Call ML Model][Call ML model](/refguide/call-ml-model/) activity adapts to the model output. If you intend to use a multidimensional output in this stage (such as in the ResNet)
there is a big in the doc for this part. please check
the [Call ML Model][Call ML model](/refguide/call-ml-model/)

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +ML Kit comes with native support to [ONNX Runtime](https://onnxruntime.ai/about.html), which means Mendix developers are free to use the right machine learning framework or library for their use case
Rephrased the paragraph

ML Kit comes with native support to [ONNX Runtime](https://onnxruntime.ai/about.html) which means Mendix developers can use the native ONNX operators. However, Mendix developers are free to use their preferred  machine learning framework or library such as Tensorflow, PyTorch, scikit-learn, and XGBoost to build their ML models, pre-processing, and post-processing actions.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +### 4.2 Pre-Trained Models
I suggest promoting this section to the H1, as the section 4

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +### 4.2 Pre-Trained Models
Also rephrase the whole section as following:

The ONNX community provides an ML model repository, called [ONNX Model Zoo](https://github.com/onnx/models), where common computer vision and language models can be found. The ONNX Model Zoo is a collection of pre-trained, state-of-the-art models in the ONNX format contributed by community members. Accompanying each model are [Jupyter notebooks](http://jupyter.org/) for model training and running inference with the trained model. The notebooks are written in Python and include links to the training dataset, as well as references to the original paper that describes the model architecture.

All the ONNX models in the ONNX zoo should be compatible with the Mendix ML Kit. You can pick up any model from this repository, customize it with your own data and integrate it in your Mendix app using the ML Kit.

To integrate a pre-built (propriety or public) ML model into a Mendix app, consider the following:
Compatibility of the model internal representation (IR) version with the ML Kit
Compatibility of the model OpSets with the ML Kit
For details on versioning schemes, see the [Versioning](https://docs.mendix.com/refguide/machine-learning-kit/using-ml-kit/#versioning) section below.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +### 4.2 Pre-Trained Models
Pre-trained ML Models

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +## 5 Monitoring and Troubleshooting
Machine learning models might be placed in the core of a Mendix application that makes automated decisions, and data quality is a crucial part of a machine learning system. Because of this, Mendix developers need to implement and configure monitoring tools that track not only service health but also the input and output of the MLKit actions. >>
Machine learning models are often placed in the core of an application to makes automated decisions. Therefore, it's advised that Mendix developers to implement and configure monitoring tools that track not only service health, but also the input and output of the ML Kit actions.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +ONNX values could be in multiple I/O types. The most common type is a Tensor. As mentioned in the examples, a Tensor could represent a primitive value, string, a boolean, or multi-dimensional form of
Here are the types that are unsupported by MLKit. > Below are the common types and their support status in the ML Kit.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +To integrate a pre-trained model with an unsupported type from model repositories (e.g. ONNX Model Zoo), one can use graph editing tools (e.g. onnx.helper, graphsurgeon) to convert an unsupported typ
Let's add the link to
onnx.helper > https://onnx.ai/onnx/api/helper.html
graphsurgeon > https://github.com/NVIDIA/TensorRT/tree/master/tools/onnx-graphsurgeon

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +This is not supported.
This is currently not supported.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +2.  My model outputs diverge from my training environment from the results in Studio Pro. What now?
Rephrasing:

The output from my model outputs in the training environment is different from the outputs in Studio Pro.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +1.  My model did not import properly. Anything I can do?
Rephrasing: 
My model does not import properly.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +3.  My model crashes Studio Pro or its execution is too slow. Can this be fixed?
Rephrasing:

My model crashes Studio Pro or its execution is too slow.

2023-02-28 12:12 UTC, amirap commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +4.  I have an exception when executing the model or running it. How can I handle this?
Rephrasing:

I have an exception when executing the model or running it.

2023-02-28 12:19 UTC, johannahemminger commented on content/en/docs/refguide/modeling/integration/machine-learning-kit/_index.md
> +Examples include the following:
Thanks, I added them in this PR: https://github.com/mendix/docs/pull/5698