updated the PCLM with more information on operator and ingress configuration
mendix/docs pull request #5581
Opened 2023-01-26 16:33 UTC by katarzyna-koltun-mx

Original PR 5570 - published too early, rolled back & created a new PR

2023-01-27 10:09 UTC, katarzyna-koltun-mx commented
Discussed with Nidhi - this PR will stay in draft status for now, and later on it might be closed or deleted.

2023-01-27 10:12 UTC, katarzyna-koltun-mx commented
Wait to publish the PR until Nidhi gives the go ahead.

2023-01-30 15:40 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +Once you have patched the Mendix Operator, all app environments which are controlled through the operator will have licenses applied automatically.
Can you pick this up, Kasia?

From Niels (in Support)
> Hi Mark, I just had a short discussion with Mario on how to apply the Runtime license when using the PCLM. The documentation says that the Runtime licenses will be applied automatically, but the Runtime will only pick it up when the environment is restarted. Could we add that to the documentation

2023-01-31 13:16 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +Once you have patched the Mendix Operator, all app environments which are controlled through the operator will have licenses applied automatically.
@Nidhi251289 can you take a look at Mark's comment and let me know if it's OK to add it to documentation?

2023-05-02 12:53 UTC, katarzyna-koltun-mx commented
@oscarpfernandez @Nidhi251289 I've added the prerequisite info and the beta note. Let me know if you have any comments.

2023-05-03 15:18 UTC, oscarpfernandez commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +The credentials you have created for an operator or admin type user need to be stored in the repository. You also need to patch the Mendix Operator with the location of pclm server and credentials fo
_"...You also need to patch the Mendix Operator **and Agent..."**_ - please update this sentence.

Note: the Agent also needs to know via a new secret the credentials and URL for PCLM. More details in the following comments.

2023-05-03 15:18 UTC, oscarpfernandez commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +stringData:
This is incorrect. These fields should only be `data` as they are base64 encoded.

```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <secret-name>
data:
  username: <base64-encoded username>
  password: <base64-encoded password>
```

2023-05-03 15:18 UTC, oscarpfernandez commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +```
We should reiterate here that this command is all that is required to configure PCLM both for the Mendix Operator and Agent, and the following secrets are just to illustrate where the modifications happen.

2023-05-03 15:18 UTC, oscarpfernandez commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +
The Agent's secret is `mendix-agent-pclm` and has the following format.

```yaml
 apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: <secret-name>
data:
  username: <base64-encoded username>
  password: <base64-encoded password>
  server-url: <base64-encoded PCLM URL>
```

2023-05-03 15:18 UTC, oscarpfernandez commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +```
We should add the restart commands of the `Mendix Agent` as well, so it can load its own configuration secret.

```
kubectl -n <namespace> scale deployment mendix-agent --replicas=0
kubectl -n <namespace> scale deployment mendix-agent --replicas=1
```

2023-05-05 15:28 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +Once you have patched the Mendix Operator, all app environments which are controlled through the operator will have licenses applied automatically.
yes, we can add that.

2023-05-09 15:28 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +```
Done.

2023-05-09 15:41 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +stringData:
Done.

2023-05-09 15:44 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +The credentials you have created for an operator or admin type user need to be stored in the repository. You also need to patch the Mendix Operator with the location of pclm server and credentials fo
Done.

2023-05-10 07:37 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +The credentials you have created for an operator or admin type user need to be stored in the repository. You also need to patch the Mendix Operator with the location of pclm server and credentials fo
@katarzyna-koltun-mx i dont see in the document where we mention about patches in Agent and the secret created for it.

2023-05-10 12:34 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +Once you have patched the Mendix Operator, all app environments which are controlled through the operator will have licenses applied automatically.
Done.

2023-05-10 12:39 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +```
Done.

2023-05-10 12:42 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +
Done.

2023-05-10 12:43 UTC, katarzyna-koltun-mx commented
@Nidhi251289 @oscarpfernandez I've made the requested corrections, can you review and let me know if there's anything I should change?

2023-05-10 12:45 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +The credentials you have created for an operator or admin type user need to be stored in the repository. You also need to patch the Mendix Operator with the location of pclm server and credentials fo
@Nidhi251289 I made the changes locallybut forgot to merge, sorry. :) All is merged now and ready for your review.

2023-06-06 07:35 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +* Mendix Operator in version 2.10 or above
can you change the operator version to 2.11.0

2023-06-06 07:36 UTC, Nidhi251289 requested changes
Hi Kasia
can you please make the above change which i have mentioned. Change Supported operator version from 2.10.0 to 2.11.0

2023-06-08 10:41 UTC, Nidhi251289 commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +If you are migrating a Mendix Operator and Mendix apps which are already licensed to use the PCLM, you will need to remove the existing licenses. If your namespace was never licensed, please ignore t
Replace this with:

If you have manually configured static runtime licenses (offline licenses), PCLM will not replace those licenses (only the runtime licenses applied via Subscription secret will be replaced). 
If your namespace was never licensed, please ignore this section.

2023-06-08 10:43 UTC, Nidhi251289 requested changes
@katarzyna-koltun-mx kindly make the requested changes in the documentation

2023-06-08 11:58 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +* Mendix Operator in version 2.10 or above
Done.

2023-06-08 12:00 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-license-manager.md
> +If you are migrating a Mendix Operator and Mendix apps which are already licensed to use the PCLM, you will need to remove the existing licenses. If your namespace was never licensed, please ignore t
Done.

2023-06-08 12:01 UTC, katarzyna-koltun-mx commented
@Nidhi251289 All done. Let me know if I should go ahead and publish.

2023-06-12 08:26 UTC, merged