document nanoflow and microflow convertion that was introduced in 9.24
mendix/docs pull request #5774
Opened 2023-03-19 17:13 UTC by EnasAbdelrazek

2023-03-20 10:21 UTC, Robinfr approved these changes

2023-03-20 10:49 UTC, Robinfr commented
Enas requested to make one more changes, so please don't merge yet.

2023-03-20 10:49 UTC, Robinfr requested changes
Enas requested to make some changes

2023-03-21 08:18 UTC, Robinfr approved these changes
Good to go.

2023-03-27 11:18 UTC, Yiyun333 approved these changes

2023-03-28 10:23 UTC, merged