Kk sap fiori
mendix/docs pull request #5835
Opened 2023-03-31 18:01 UTC by katarzyna-koltun-mx

2023-04-03 10:05 UTC, gauravkrshah requested changes

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +title: "SAP Native Resources Module"
rename it SAP Horizon Native UI resources

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +description: "The SAP Native Resources Module allows you to use SAP Fiori UI resources in your native mobile Mendix app, to make the UI consistent with SAP products."
SAP Horizon Native UI resources module allows you to create Native apps having Fiori Horizon theme UI styling.

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +tags: ["SAP", "Fiori", "UI", "resources"]
Add Native

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +The [SAP Native Resources Module](!TO BE ADDED) allows you to use SAP Fiori UI resources in your native mobile Mendix app in order to create a UI that is consistent with the UI of SAP products built
SAP Fiori UI resources and SAP Horizon Native UI resources both are different. so for native apps SAP Horizon Native UI resources, this will be used to give Fiori Look and styling

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +* Components - Mendix core components with a SAP Fiori look and feel
let change it as SAP Fiori Horizon theme look and feel

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +You may want to use this module if you are building a native mobile Mendix app not built on an SAP template, but you still want the app layout and theme to be consistent with your SAP apps.
you may want to use this module if you are building a native mobile Mendix app with SAP Fiori Horizon theme. This will make your native app to be consistent with SAP Fiori UI based applications.

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +After you install the connector, you can find it in the **App Explorer**, in the **SAP_Native_Resources** section. The connector provides a number of [components](#components), [building blocks](#bui
install the connector, "connector" is not appropriate here as it is UI resource module

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +If you want to customize any component according to your requirements, add the new class to the component and write style in the respective files in **SAP_Native_Resources > Styling > native > compon
I would say make it as separate section customization or alert out from components section. Because it is applicable to who module. something like Any custom styling can be added by following https://docs.mendix.com/howto/front-end/customize-styling-new/#23-adding-custom-styling

2023-04-03 10:05 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +There are some predesigned pages that you can use to quickly create a native page UI. You can choose these templates while creating a new page in your native mobile app.
you can use to quickly create a native page, remove "UI"

2023-04-03 14:49 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +title: "SAP Native Resources Module"
Done.

2023-04-03 14:51 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +description: "The SAP Native Resources Module allows you to use SAP Fiori UI resources in your native mobile Mendix app, to make the UI consistent with SAP products."
Done.

2023-04-03 14:51 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +tags: ["SAP", "Fiori", "UI", "resources"]
Done.

2023-04-04 16:18 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +title: "SAP Native Resources Module"
Done.

2023-04-04 16:19 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +* Components - Mendix core components with a SAP Fiori look and feel
Done.

2023-04-04 16:21 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +You may want to use this module if you are building a native mobile Mendix app not built on an SAP template, but you still want the app layout and theme to be consistent with your SAP apps.
Done.

2023-04-04 17:13 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +After you install the connector, you can find it in the **App Explorer**, in the **SAP_Native_Resources** section. The connector provides a number of [components](#components), [building blocks](#bui
Done.

2023-04-04 17:13 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +There are some predesigned pages that you can use to quickly create a native page UI. You can choose these templates while creating a new page in your native mobile app.
Done.

2023-04-05 17:57 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +The [SAP Native Resources Module](!TO BE ADDED) allows you to use SAP Fiori UI resources in your native mobile Mendix app in order to create a UI that is consistent with the UI of SAP products built
Done.

2023-04-05 18:00 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +If you want to customize any component according to your requirements, add the new class to the component and write style in the respective files in **SAP_Native_Resources > Styling > native > compon
Not sure if I understood correctly, please take a look and let me know what you think.

2023-04-13 10:13 UTC, gauravkrshah approved these changes
Looks good. Please update as mentioned in the comments.

2023-04-13 10:13 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +The [SAP Horizon Native UI Resources module](!TO BE ADDED) allows you to design your native mobile app pages with SAP Fiori-styled widgets and building blocks as part of your layout. The module uses
"SAP Horizon"

2023-04-13 10:13 UTC, gauravkrshah commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +If you want to customize any component according to your requirements, add the new class to the component and write style in the respective files in **SAP_Native_Resources > Styling > native > compon
Acutally what I am saying Customization of module should go as separate section in the document not as an alert. 
For example like here - https://mendixtechnologybv-my.sharepoint.com/:w:/r/personal/srishti_mishra_mendix_com/_layouts/15/Doc.aspx?sourcedoc=%7BA5BB1B02-2DE3-47F8-9192-3CE93399FC8F%7D&file=SAP%20Native%20Resource.docx&action=default&mobileredirect=true&DefaultItemOpen=1&login_hint=Gaurav.Shah%40mendix.com&ct=1681380455952&wdOrigin=OFFICECOM-WEB.START.EDGEWORTH&cid=4cd4f041-a714-4238-99f8-9fd8256534ea&wdPreviousSessionSrc=HarmonyWeb&wdPreviousSession=bacde65f-dc55-4328-87f5-b77b590dcd86

2023-04-17 15:27 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +If you want to customize any component according to your requirements, add the new class to the component and write style in the respective files in **SAP_Native_Resources > Styling > native > compon
I'm not sure if there's currently enough info there to warrant a separate Configuration section. Maybe we could provide an example of customization that could be implemented, like a sample js file? Do you think that would be helpful?

2023-04-19 14:13 UTC, katarzyna-koltun-mx commented on content/en/docs/partners/sap/sap-fiori-3-0/sap-native-resources-module.md
> +The [SAP Horizon Native UI Resources module](!TO BE ADDED) allows you to design your native mobile app pages with SAP Fiori-styled widgets and building blocks as part of your layout. The module uses
Done.

2023-04-26 09:36 UTC, merged