Inclusive language
mendix/docs pull request #6004
Opened 2023-05-04 07:29 UTC by Adam-Dupaski

2023-05-04 07:32 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +<internal environment name>-main
@katarzyna-koltun-mx not sure if these are examples or are they in the code?

2023-05-04 07:32 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Deploying a Mendix app with primary and secondary nodes
@katarzyna-koltun-mx please review

2023-05-04 07:33 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +An app with an ephemeral database cannot have more than one replica. Only the first (primary) replica will be able to start.
@katarzyna-koltun-mx  please review

2023-05-04 07:33 UTC, Adam-Dupaski commented on content/en/docs/howto8/extensibility/build-javascript-actions/create-native-javascript-action.md
> +In this section you will install the external library [react-native-nfc-manager](https://www.npmjs.com/package/react-native-nfc-manager) which makes adding NFC functionality easier. Mendix Studio Pro
@MarkvanMents no clear owner, can you please review?

2023-05-04 07:34 UTC, Adam-Dupaski commented on content/en/docs/howto8/extensibility/build-javascript-actions/create-native-javascript-action.md
> +* The GitHub React Native community post [Autolinking](https://github.com/react-native-community/cli/blob/main/docs/autolinking.md)
New link, no review necessary

2023-05-04 07:34 UTC, Adam-Dupaski commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/native-debug.md
> +React Developer Tools is [an app](https://github.com/facebook/react/tree/main/packages/react-devtools) which will allow you to see investigate the way your native page is rendering, adjust things lik
New link, no review necessary

2023-05-04 07:34 UTC, Adam-Dupaski commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/deploying-native-app-cli.md
> +1. Commit these changes to your project's primary branch so consecutive builds have the tablet settings enabled.
@ConnorLand please review

2023-05-04 07:35 UTC, Adam-Dupaski commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/how-to-devapps-cli.md
> +    1. Creates a branch named `developer` based on the commited changes to your `primary` <br />
@ConnorLand not sure if this is an example or this is in the code?

2023-05-04 07:35 UTC, Adam-Dupaski commented on content/en/docs/refguide/mobile/distributing-mobile-apps/native-debug.md
> +React Developer Tools is [an app](https://github.com/facebook/react/tree/main/packages/react-devtools) which will allow you to see investigate the way your native page is rendering, adjust things lik
New link, no review necessary

2023-05-04 07:36 UTC, Adam-Dupaski commented on content/en/docs/refguide/modeling/integration/rest-services/published-rest-services/published-rest-service/_index.md
> +To save a service's [OpenAPI (Swagger) documentation](/refguide/open-api/) somewhere on your machine, simply right-click the service in the **App Explorer** and select **Export swagger.json** (or jus
New link, no review necessary

2023-05-04 07:36 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
@MarkvanMents please review

2023-05-04 07:37 UTC, Adam-Dupaski commented on content/en/docs/refguide8/mobile/native-mobile/native-builder.md
> +This parameter specifies an app icon file. The image must be a *.png* file, and have a resolution of 1024x1024. Mendix will do the resizing for you. If a file path is not provided, default app icons
@ConnorLand please review

2023-05-04 07:37 UTC, Adam-Dupaski commented on content/en/docs/refguide8/modeling/integration/published-rest-services/published-rest-service/_index.md
> +To save a service's [OpenAPI (Swagger) documentation](/refguide8/open-api/) somewhere on your machine, simply right-click the service in the **Project Explorer** and select **Export swagger.json** (o
New link, no review necessary

2023-05-04 07:37 UTC, Adam-Dupaski commented on content/en/docs/refguide8/modeling/integration/published-rest-services/published-rest-technical-details/open-api.md
> +Every [published REST service](/refguide8/published-rest-service/) is automatically documented. The system generates a *swagger.json* file that conforms to the [OpenAPI 2.0 specification](https://git
New link, no review necessary

2023-05-04 07:38 UTC, Adam-Dupaski commented on content/en/docs/refguide8/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
@MarkvanMents please review

2023-05-04 07:38 UTC, Adam-Dupaski commented on content/en/docs/refguide9/mobile/distributing-mobile-apps/native-debug.md
> +React Developer Tools is [an app](https://github.com/facebook/react/tree/main/packages/react-devtools) which will allow you to see investigate the way your native page is rendering, adjust things lik
New link, no review necessary

2023-05-04 07:38 UTC, Adam-Dupaski commented on content/en/docs/refguide9/modeling/integration/rest-services/published-rest-services/published-rest-service/_index.md
> +To save a service's [OpenAPI (Swagger) documentation](/refguide9/open-api/) somewhere on your machine, simply right-click the service in the **App Explorer** and select **Export swagger.json** (or ju
New link, no review necessary

2023-05-04 07:38 UTC, Adam-Dupaski commented on content/en/docs/refguide9/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
@MarkvanMents please review

2023-05-04 07:39 UTC, Adam-Dupaski commented on content/en/docs/releasenotes/studio-pro/7/7.18.md
> +* We fixed an out-of-memory issue on cluster followers caused by persistent session objects. (Ticket 80910)
@MarkvanMents please review

2023-05-04 07:39 UTC, Adam-Dupaski commented on content/en/docs/releasenotes/studio-pro/7/7.23.md
> +* We fixed an out-of-memory issue on cluster followers caused by persistent session objects. (Ticket 80910)
@MarkvanMents please review

2023-05-04 07:39 UTC, Adam-Dupaski commented on content/en/docs/releasenotes/studio-pro/8/8.0.md
> +* We fixed an out-of-memory issue on cluster followers caused by persistent session objects. (Ticket 80910)
@MarkvanMents please review

2023-05-04 09:23 UTC, ConnorLand commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/deploying-native-app-cli.md
> +1. Commit these changes to your project's primary branch so consecutive builds have the tablet settings enabled.
LGTM

2023-05-04 09:24 UTC, ConnorLand commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/how-to-devapps-cli.md
> +    1. Creates a branch named `developer` based on the commited changes to your `primary` <br />
I think this is in the code. I'll check with MOO and see if they've changed the name of it.

2023-05-04 09:24 UTC, ConnorLand commented on content/en/docs/refguide8/mobile/native-mobile/native-builder.md
> +This parameter specifies an app icon file. The image must be a *.png* file, and have a resolution of 1024x1024. Mendix will do the resizing for you. If a file path is not provided, default app icons
I think this is in the code. I'll check with MOO and see if they've changed the name of it.

2023-05-04 09:36 UTC, ConnorLand commented on content/en/docs/refguide8/mobile/native-mobile/native-builder.md
> +This parameter specifies an app icon file. The image must be a *.png* file, and have a resolution of 1024x1024. Mendix will do the resizing for you. If a file path is not provided, default app icons
Ah, I've confirmed. All instances of master except the first one in the alert at the top of the doc can be changed to "main".

2023-05-04 09:36 UTC, ConnorLand commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/how-to-devapps-cli.md
> +    1. Creates a branch named `developer` based on the commited changes to your `primary` <br />
Please change this to "main".

2023-05-04 09:42 UTC, Adam-Dupaski commented on content/en/docs/howto8/mobile/native-mobile/build-native-apps/use-cli-docs/how-to-devapps-cli.md
> +    1. Creates a branch named `developer` based on the commited changes to your `primary` <br />
https://github.com/mendix/docs/pull/6004/commits/cce13fd60ef96278a5f7dd2f7d0d4341bd3d0ab8

2023-05-04 11:22 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +<internal environment name>-main
Reached out to the team for clarification.

2023-05-04 11:22 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +An app with an ephemeral database cannot have more than one replica. Only the first (primary) replica will be able to start.
Reached out to the team for clarification.

2023-05-04 11:26 UTC, Adam-Dupaski commented on content/en/docs/refguide8/mobile/native-mobile/native-builder.md
> +This parameter specifies an app icon file. The image must be a *.png* file, and have a resolution of 1024x1024. Mendix will do the resizing for you. If a file path is not provided, default app icons
So leaving the committed changes, thanks.

2023-05-04 12:57 UTC, MarkvanMents requested changes
@Adam-Dupaski 
Have reviewed.
I don't think it makes sense to change terminology where it is explicitly used in the product. I think that the change should be led by the product, otherwise it becomes confusing. Have listed this below.

Other changes look good.

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Deploying a Mendix app with primary and follower nodes
I don't think this change makes much sense since we are talking about using the setting [com.mendix.core.isClusterSlave](https://docs.mendix.com/refguide/custom-settings/#commendixcoreisClusterSlave) and the section below is still called [Configure Cluster Slave Nodes](https://docs.mendix.com/developerportal/deploy/deploy-mendix-ha-on-windows-in-microsoft-azure/#3-configure-cluster-slave-nodes)

I think this should wait until they rename the Mendix setting.

```suggestion
* Deploying a Mendix app with primary and slave nodes
```

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a PostgreSQL database, the Mendix Operator requires a primary account with permissions to create new users and databases.
Don't think "primary" works here.
This is probably better termed a `root` account, or an account with `root privileges`.
Although in Wikipedia, the main article is named [Superuser](https://en.wikipedia.org/wiki/Superuser), so perhaps that is better.

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/howto8/extensibility/build-javascript-actions/create-native-javascript-action.md
> +In this section you will install the external library [react-native-nfc-manager](https://www.npmjs.com/package/react-native-nfc-manager) which makes adding NFC functionality easier. Mendix Studio Pro
I think this one is @ConnorLand 's (https://github.com/mendix/docs/pull/2104)
I think you can change this as the native-builder was updated in v3.2.1 to use **main**.

The image still needs to be updated: 
![image](https://user-images.githubusercontent.com/35492184/236210026-74b0df21-1805-431d-87e6-c474c42a60b9.png)

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
[The setting which customers need to use is `isClusterSlave`](https://github.com/search?q=repo%3Amendix%2Fcf-mendix-buildpack%20slave&type=code) so using different terminology is confusing.
I think we should not make changes which are related to this setting until the setting name is changed in the product. There is no point in us making things confusing if these changes are not going to be made in the product as well.

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/refguide9/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
[The setting which customers need to use is `isClusterSlave`](https://github.com/search?q=repo%3Amendix%2Fcf-mendix-buildpack%20slave&type=code) so using different terminology is confusing.
I think we should not make changes which are related to this setting until the setting name is changed in the product. There is no point in us making things confusing if these changes are not going to be made in the product as well.

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/releasenotes/studio-pro/7/7.18.md
> +* We fixed an out-of-memory issue on cluster followers caused by persistent session objects. (Ticket 80910)
Looks good as we are not mentioning the specific runtime setting here.

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/releasenotes/studio-pro/7/7.23.md
> +* We fixed an out-of-memory issue on cluster followers caused by persistent session objects. (Ticket 80910)
Looks good as we are not mentioning the specific runtime setting here.

2023-05-04 12:57 UTC, MarkvanMents commented on content/en/docs/releasenotes/studio-pro/8/8.0.md
> +* We fixed an out-of-memory issue on cluster followers caused by persistent session objects. (Ticket 80910)
Looks good as we are not mentioning the specific runtime setting here.

2023-05-04 12:59 UTC, MarkvanMents commented
> 
> Other changes look good.

Except where "master account" meant "Superuser account", where I think we should use "superuser" (or, perhaps "root") - but these are in @katarzyna-koltun-mx 's area, so perhaps she can make a decision?

2023-05-05 07:13 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a PostgreSQL database, the Mendix Operator requires a primary account with permissions to create new users and databases.
@katarzyna-koltun-mx can you please verify what is best here?

Maybe: `a Superuser account with root privileges and permissions to create new users and databases` ?

2023-05-05 07:13 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a SQL Server database, the Mendix Operator requires a primary account with permissions to create new users and databases.
@katarzyna-koltun-mx same question here as above.

2023-05-05 07:30 UTC, Adam-Dupaski commented on content/en/docs/howto8/extensibility/build-javascript-actions/create-native-javascript-action.md
> +In this section you will install the external library [react-native-nfc-manager](https://www.npmjs.com/package/react-native-nfc-manager) which makes adding NFC functionality easier. Mendix Studio Pro
Will keep as `main`, thanks.

@ConnorLand screenshot in this doc needs an update for `main` or to be deleted entirely, can you please pick this up?

2023-05-05 07:58 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
I agree, reverted change: https://github.com/mendix/docs/pull/6004/commits/0627d405042f5c8ff30f1cafc5fc32819f4f36b0

2023-05-05 07:59 UTC, Adam-Dupaski commented on content/en/docs/refguide/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
Also: https://github.com/mendix/docs/pull/6004/commits/a4466fc842812b5899058f47475c80cec3bc6ff8

2023-05-05 08:02 UTC, Adam-Dupaski commented on content/en/docs/refguide8/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
Reverted change via above: https://github.com/mendix/docs/pull/6004/commits/296c1f0b4cd33b884b9ee97d236f0d795d8f77ff

2023-05-05 08:03 UTC, Adam-Dupaski commented on content/en/docs/refguide9/runtime/clustered-mendix-runtime.md
> +The Cloud Foundry Buildpack determines which cluster node becomes the cluster leader and which become cluster followers.
I agree, reverted change: https://github.com/mendix/docs/pull/6004/commits/7334a7c9dec241a810e0b06f92e4e6a97aaee71a

2023-05-05 08:52 UTC, ConnorLand commented on content/en/docs/howto8/extensibility/build-javascript-actions/create-native-javascript-action.md
> +In this section you will install the external library [react-native-nfc-manager](https://www.npmjs.com/package/react-native-nfc-manager) which makes adding NFC functionality easier. Mendix Studio Pro
I will update this.

2023-05-05 09:09 UTC, ConnorLand commented on content/en/docs/howto8/extensibility/build-javascript-actions/create-native-javascript-action.md
> +In this section you will install the external library [react-native-nfc-manager](https://www.npmjs.com/package/react-native-nfc-manager) which makes adding NFC functionality easier. Mendix Studio Pro
Updated in this commit https://github.com/mendix/docs/pull/6004/commits/b005d2a460a51a193cee29caaae7cfa17ca76686

2023-05-05 12:02 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +<internal environment name>-main
@Adam-Dupaski This comes from the code and would require a product change.

2023-05-05 12:03 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +Below is an example of the Deployment definition of an app. In this example, the Deployment definition is called `b8nn6lq5-main`:
@Adam-Dupaski This is also taken from the code and cannot be changed without a product change.

2023-05-05 12:05 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +        node-type: main
@Adam-Dupaski This is also from the code, however the whole metadata section can be compressed to #... (like in some other lines above).

2023-05-05 12:06 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +An app with an ephemeral database cannot have more than one replica. Only the first (primary) replica will be able to start.
@Adam-Dupaski Dmitrii suggests "leader" rather than "primary", since they're already using "leader" elsewhere.

2023-05-05 12:08 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a PostgreSQL database, the Mendix Operator requires a primary account with permissions to create new users and databases.
@Adam-Dupaski Accepted by Dmitrii.

2023-05-05 12:08 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a SQL Server database, the Mendix Operator requires a primary account with permissions to create new users and databases.
"Superuser" will be fine.

2023-05-05 12:09 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Deploying a Mendix app with primary and slave nodes
@Adam-Dupaski I think "slave" should be updated too. OK to change.

2023-05-08 07:23 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +<internal environment name>-main
Thanks, reverted: https://github.com/mendix/docs/pull/6004/commits/5b149d68dfad317293348a44042ef798733e7cd7

2023-05-08 07:23 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +Below is an example of the Deployment definition of an app. In this example, the Deployment definition is called `b8nn6lq5-main`:
Thanks, reverted: https://github.com/mendix/docs/pull/6004/commits/5b149d68dfad317293348a44042ef798733e7cd7

2023-05-08 07:23 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-cluster/_index.md
> +        node-type: main
Thanks, reverted: https://github.com/mendix/docs/pull/6004/commits/5b149d68dfad317293348a44042ef798733e7cd7

2023-05-08 07:25 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +An app with an ephemeral database cannot have more than one replica. Only the first (primary) replica will be able to start.
Thanks, updated: https://github.com/mendix/docs/pull/6004/commits/fd4e3f3cc097086de740aabd44016117962abd50

2023-05-08 07:25 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a PostgreSQL database, the Mendix Operator requires a primary account with permissions to create new users and databases.
Thanks, updated: https://github.com/mendix/docs/pull/6004/commits/fd4e3f3cc097086de740aabd44016117962abd50

2023-05-08 07:26 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/private-cloud/private-cloud-supported-environments.md
> +To use a SQL Server database, the Mendix Operator requires a primary account with permissions to create new users and databases.
Thanks, updated: https://github.com/mendix/docs/pull/6004/commits/98c982ffd697e9fadeb94212fa49dd625841820a

2023-05-08 07:29 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/deploy-mendix-ha-on-windows-in-microsoft-azure.md
> +* Deploying a Mendix app with primary and slave nodes
Thanks, updated: https://github.com/mendix/docs/pull/6004/commits/3156188e4cc819e2e54ccc78c8e42eb0a54329b1

2023-05-08 07:32 UTC, merged