Update docs for new page URL features
mendix/docs pull request #6030
Opened 2023-05-10 09:08 UTC by WimJongeneel

The new features for page URLs are to be released in Mendix 10.0.0 Beta 2. Related to [UFC-696].

2023-05-10 09:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=6030) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=6030) before we can accept your contribution.<br/><hr/>**Wim Jongeneel** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=6030) it.</sub>

2023-05-12 09:12 UTC, Robinfr requested changes
I would like to see atleast one screenshot around configuring the page URL.

2023-05-12 09:12 UTC, Robinfr commented on content/en/docs/refguide/modeling/pages/page/page-properties.md
> +Page URLs are not supported for pages with NPE parameters
Should be written out, e.g.:

```suggestion
Page URLs are not supported for pages that have non-persistable entities as parameters
```

2023-05-15 08:01 UTC, Robinfr approved these changes
Can be checked by tech writer @Adam-Dupaski

2023-05-15 09:52 UTC, ConnorLand commented
Hello. I talked with Jonathan Diehl today about upcoming improvements to Page URLs and Deeplinking. I see this PR is slated for Beta 2. 

How big of a portion of the Page URL updates does this PR capture? Will there be bigger Page URL PRs/updates for GA?

2023-05-15 09:59 UTC, Robinfr commented
Hi @ConnorLand it's likely there will be more changes for Page URLs and other related features for the docs for GA. We want to get these docs out there, as we want people to start playing around with the feature in beta 2.

2023-05-17 12:14 UTC, ConnorLand approved these changes

2023-06-01 07:17 UTC, merged