Update docs for new list aggregation functions
mendix/docs pull request #6044
Opened 2023-05-15 12:25 UTC by WimJongeneel

Planned for release in Menxix 10 Beta 2.  Part of [UFC-842]

2023-05-16 08:35 UTC, Robinfr requested changes
Few things that need to be fixed.

2023-05-16 08:35 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible for if the Function is Average, Minimum, Maximum or Sum. For those function you can here define if you want to aggregate with an attribute or an expression. For All, Any a
```suggestion
This option is only visible if the Function is Average, Minimum, Maximum or Sum. For those functions, you can define if you want to aggregate using an attribute or an expression.
```

You don't need to mention that it is hidden for the rest. Also fixed a typo.

2023-05-16 08:35 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +### 3.4 Expression
This and the next section have incorrect section numbers.

2023-05-17 10:53 UTC, Robinfr commented
@ConnorLand Can be reviewed by tech writers.

2023-05-17 10:54 UTC, Robinfr approved these changes

2023-05-17 10:55 UTC, Yiyun333 commented
> @ConnorLand Can be reviewed by tech writers.

Thanks @Robinfr! I'll pick this up.

2023-05-19 16:31 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible if the **Function** is **Reduce**. The expression here will be used as the initial value for the aggregation. When aggregating with **Reduce** over an empty list, the resu
@WimJongeneel In this sentence `The expression here will be used as the initial value for the aggregation.`, do you mean that the result of the whole expression will be used as the initial value?

I am a bit confused, because from this sentence `Otherwise this initial value will be the value of $currentResult when the Expression is evaluated for the first item`, it seems that only the value of `$currentResult` will be used as the initial value. How about when the expression is `$currentResult + $currentObject/Name` in the example you gave above?

2023-05-19 16:31 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible if the **Function** is **Reduce**. The expression here will be used as the initial value for the aggregation. When aggregating with **Reduce** over an empty list, the resu
@WimJongeneel In this sentence` When aggregating with **Reduce** over an empty list, the result will be this initial value.`, can we be a bit more explicit about the result here? Like, what kind of result usually it is when aggregating with **Reduce** over an empty list?

2023-05-19 16:36 UTC, Yiyun333 commented
@WimJongeneel I've reviewed the content and the style of the PR in this commit: https://github.com/mendix/docs/pull/6044/commits/d747041a6195a1fdcc9d7226434bbcd09582d79b.

I also left two comments above. Please let me know if I've made any changes that are technically not correct. Thanks!

2023-05-22 07:34 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible if the **Function** is **Reduce**. The expression here will be used as the initial value for the aggregation. When aggregating with **Reduce** over an empty list, the resu
> @WimJongeneel In this sentence The expression here will be used as the initial value for the aggregation., do you mean that the result of the whole expression will be used as the initial value?

Yes, that is true. The entire expression in the 'Initial expression' field will be evaluated first and will be the value of `$currentResult` before we iterate over the items in the list.

After that it will iterate over the items in the list and the value of `$currentResult` will be updated to the result of the expression in the 'Expression' field (for each step in the iteration). Within this expression you can use the current value of `$currentResult` to create a new value for `currentResult`. 

So in the example and for a list `[ { Name: 'Product_1' }, { Name: 'Product_2' }, { Name: 'Product_3' }  ]` the value of `$currentResult` will go through 4 values:

* `'Product names: '`: after evaluating the initial expression and before iterating
* `'Product names: Product_1'`: previous value + `$currentObject/Name` where `$currentObject` is the first item in the list
* `'Product names: Product_1Product_2'`: previous value + `$currentObject/Name` where `$currentObject` is the second item in the list
* `'Product names: Product_1Product_2Product_3'`: previous value + `$currentObject/Name` where `$currentObject` is the third item in the list

And the last value is then the result of the aggregation.

For an empty list it is the result of evaluating is the initial expression because nothing more will happen after the first step.

2023-05-22 09:01 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible if the **Function** is **Reduce**. The expression here will be used as the initial value for the aggregation. When aggregating with **Reduce** over an empty list, the resu
@WimJongeneel Thanks a lot for the explanation. I think I mixed up the expression you put in the **Initial value** field and the expression you put in the **Expression** field.

 I just made the distinguishment a bit more clear in the doc. From my understanding, the initial value will first be the result of the entire expression in the **Initial value** field. If the aggregation is not over an empty list, the initial value will then be updated to the value of `$currentResult` when **Expression** is evaluated for the first item. Is my understanding correct? Please see my update in [this ](https://github.com/mendix/docs/pull/6044/commits/50a4da2a6ae7fa8e4aeabe39d68cd667570ec744)commit.

2023-05-22 15:00 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible if the **Function** is **Reduce**. The expression here will be used as the initial value for the aggregation. When aggregating with **Reduce** over an empty list, the resu
Yes, looks good from my side

2023-05-22 15:46 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/activities/list-activities/aggregate-list.md
> +This option is only visible if the **Function** is **Reduce**. The expression here will be used as the initial value for the aggregation. When aggregating with **Reduce** over an empty list, the resu
Great!

2023-05-23 10:08 UTC, Yiyun333 approved these changes
PR is approved and I will merge it along with the 10.0.0 Beta 2 release.

2023-06-01 07:42 UTC, merged