S3 updates
mendix/docs pull request #6046
Opened 2023-05-15 17:24 UTC by katarzyna-koltun-mx

2023-05-16 07:28 UTC, trongbtran requested changes
We've removed an attribute from the CreateBucketRequest entity and therefore all references towards this attribute and its underlying document can be removed to avoid confusion.

2023-05-16 07:28 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +| ACL | Describes the canned ACL (access control list) to apply to the bucket |
This attribute has been removed, therefore we can remove this row.

2023-05-16 07:28 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +#### 4.3.2 ENUM_BucketCannedACL {#enum-bucketcannedacl}
The ACL attribute was a reference to this document. This document has also been removed. Therefore we can remove this line and correspondingly its table.

2023-05-16 17:56 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +#### 4.3.2 ENUM_BucketCannedACL {#enum-bucketcannedacl}
Done.

2023-05-16 17:57 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +| ACL | Describes the canned ACL (access control list) to apply to the bucket |
Done.

2023-05-16 17:58 UTC, katarzyna-koltun-mx commented
@trongbtran About the sample microflow, which service would be best to use as an example?

2023-05-22 14:57 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +    3. In the autocomplete dialog, select **AWSTwinMakerConnector.AWS_Region**, then type *.* and select your AWS region from the list.
This line refers to an AWS Twinmaker document.

2023-05-22 14:57 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +        {{< figure src="/attachments/appstore/connectors/aws-iot-twinmaker/awsregions.png" alt="The list of AWS regions">}}
I suppose this reference shouldn't matter much as it's static content?

2023-05-22 14:57 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +12. In the **Member** section, click **New**, and then select **BucketName** as the member.
Maybe it's a wise disclaimer to add that the contents of the BucketName attribute MUST be all lowercase. Otherwise the S3 service will return an error.

2023-05-22 14:57 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +15. In the **Toolbox** pane, search for the **Retrieve** activity, drag it onto the microflow area, and position it between the **CreateBucket** activity and the microflow end event.
Every step following the 15th step is not necessary, the CreateBucketResponse is an object with a single attribute called Location. After invoking the CreateBucket action, that object and the value in the Location attribute is everything returned to the end-user.

2023-05-22 15:54 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +    3. In the autocomplete dialog, select **AWSTwinMakerConnector.AWS_Region**, then type *.* and select your AWS region from the list.
Fixed.

2023-05-22 15:55 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +        {{< figure src="/attachments/appstore/connectors/aws-iot-twinmaker/awsregions.png" alt="The list of AWS regions">}}
I'll take some more screenshots when I finalize the microflow, and I'll update this one as well. Pending the discussion tomorrow.

2023-05-22 15:57 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +12. In the **Member** section, click **New**, and then select **BucketName** as the member.
Done.

2023-05-22 15:58 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +15. In the **Toolbox** pane, search for the **Retrieve** activity, drag it onto the microflow area, and position it between the **CreateBucket** activity and the microflow end event.
Done.

2023-06-06 11:35 UTC, trongbtran reviewed
It all looks great, I found one minor inconsistency.

2023-06-06 11:35 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +| `REDUCED_REDUNDANCY` | REDUCED_REDUNDANCY | Selecting this enumeration value stores an object according to the RRS (reduced redundancy storage) class |
The REDUCED_REDUNDANCY caption isn't bolded like the other captions.

2023-06-07 12:29 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-s3-connector.md
> +| `REDUCED_REDUNDANCY` | REDUCED_REDUNDANCY | Selecting this enumeration value stores an object according to the RRS (reduced redundancy storage) class |
Fixed.

2023-06-07 13:01 UTC, merged