Add documentation bring your own kafka
mendix/docs pull request #6170
Opened 2023-06-13 13:06 UTC by JansenNick

2023-06-13 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=6170) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=6170) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=6170) it.</sub>

2023-06-13 13:20 UTC, johannahemminger commented
Thanks @JansenNick for this PR! When should this be merged? ASAP, or on 10GA release date?

2023-06-13 13:45 UTC, JansenNick commented
@johannahemminger once we release the 3.6.0 business events module with the bring your own kafka changes, Pritika and some internal teams are still testing the new module.

With regards to the updated documentation, feel free to make edits as you see fit.

2023-06-13 14:12 UTC, stefanus-heath requested changes

2023-06-13 14:12 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +4. Bring your own Kafka
Here we want to please say (Beta) behind it.  .... 

_Mendix apps running in Mendix for Private Cloud (Bring your own Kafka).  This functionality is still in beta testing_

2023-06-13 14:12 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +If you are deploying an app to production that contains a published business event service, you might receive a warning that it is not possible to enable the event broker service. If you see this mes
"you may receive a warning" ?

2023-06-13 14:12 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +To deploy to a private cloud using your own Kafka cluster, you can make use of the the `EventBrokerSpace` constant. This constant can be set to values like test, acceptance or production based on in
Here we need to add that BYOK is in a beta stage (under licensing we should add more info on this)

2023-06-13 14:12 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +To deploy to a private cloud using your own Kafka cluster, you can make use of the the `EventBrokerSpace` constant. This constant can be set to values like test, acceptance or production based on in
"Kafka topic for environment" does not read well

2023-06-13 14:12 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +To deploy to a private cloud using your own Kafka cluster, you can make use of the the `EventBrokerSpace` constant. This constant can be set to values like test, acceptance or production based on in
Do we explain channel anywhere else?

2023-06-13 14:12 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +### 6.4 Bring your own Kafka
_Mendix for Private Cloud (Bring your own Kafka)_

2023-06-14 08:21 UTC, johannahemminger commented on content/en/docs/appstore/modules/business-events.md
> +To deploy to a private cloud using your own Kafka cluster, you can make use of the the `EventBrokerSpace` constant. This constant can be set to values like test, acceptance or production based on in
Yes I'll link to it!

2023-06-21 07:21 UTC, merged