AWS SiteWise doc draft
mendix/docs pull request #6334
Opened 2023-07-21 13:56 UTC by katarzyna-koltun-mx

2023-07-21 13:56 UTC, katarzyna-koltun-mx commented
Created a draft for the team to edit.

2023-09-04 07:20 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +6. In the **Edit parameters** section, edit the **AWS_Region** parameter, and provide a value by using a variable or an expression. For a list of available AWS regions, see [AWS_Region](#aws_region).
We've edited the naming convention for enumeration documents to be prefixed with "ENUM", as such AWS_Region is now being phased out of all our connector content.

2023-09-04 07:22 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INCOMPATIBLE_COMPUTE_LOCATION` | INCOMPATIBLE_COMPUTE_LOCATION |  |
"The provided compute location is incompatible."

2023-09-04 07:22 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INCOMPATIBLE_FORWARDING_CONFIGURATION` | INCOMPATIBLE_FORWARDING_CONFIGURATION |  |
The provided forwarding configuration is incompatible.

2023-09-04 07:24 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INTERNAL_FAILURE` | INTERNAL_FAILURE |  |
"an internal error has occurred."

2023-09-04 07:24 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `VALIDATION_ERROR` | VALIDATION_ERROR |  |
"A validation error was returned."

2023-09-04 07:25 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `LIMIT_EXCEEDED` | LIMIT_EXCEEDED |  |
"The monitoring limit has been exceeded."

2023-09-04 07:25 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INTEGER` | INTEGER | The variable is of type string. |
The variable is of type integer.

2023-09-04 07:25 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `_DOUBLE` | DOUBLE | The variable is of type string. |
The variable is of type double.

2023-09-04 07:25 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `_BOOLEAN` | BOOLEAN | The variable is of type string. |
The variable is of type boolean.

2023-09-04 07:25 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `STRUCT` | STRUCT | The variable is of type string. |
The variable is of type struct.

2023-09-04 07:29 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +### 3.2 Configuring a Microflow for an AWS Service
For this section, I propose to change the action we take as an example to be ListAssetModels instead of GetAssetPropertyValue. GetAssetPropertyValue requires at least one asset, which requires at least one asset model, delaying a fast implementation and realization of value using our connector.

I'll add comments for lines to be changed/added below.

2023-09-04 07:30 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +After you configure the authentication profile for AWS IoT SiteWise, you can implement the functions of the connector by using the provided activities in microflows. For example, to retrieve an asset
After you configure the authentication profile for AWS IoT SiteWise, you can implement the functions of the connector by using the provided activities in microflows. For example, to retrieve a list of available asset models, implement the [ListAssetModels](#list-asset-models) activity by doing the following steps:

2023-09-04 07:30 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +2. Enter a name for your microflow, for example, *ACT_GetAssetPropertyValue*, and then click **OK**.
Enter a name for your microflow, for example, *ACT_ListAssetModels*, and then click **OK**.

2023-09-04 07:31 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +3. In the **App Explorer**, in the **AmazonRekognitionConnector** > **Operations** section, find the **GetAssetPropertyValue** activity.
3. In the **App Explorer**, in the **AWSIoTSiteWiseConnector** > **Operations** section, find the **ListAssetModels** activity.

2023-09-04 07:31 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
4. Drag the **ListAssetModels** activity onto the work area of your microflow.

2023-09-04 07:32 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
4. In your **Toolbox**, drag the **Create Object** activity onto the work area of your microflow.

2023-09-04 07:33 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
5. In the **Entity** field, select **ListAssetModelsRequest**.

2023-09-04 07:34 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
6. Drag the **ListAssetModels** activity onto the work area of your microflow.

2023-09-04 07:34 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +5. Double-click the **GetAssetPropertyValue** microflow activity to configure the required parameters.
7. Double-click the **ListAssetModels** microflow activity to configure the required parameters.

2023-09-04 07:35 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +9. Position the **Retrieve** activity between the **GetAssetPropertyValue** activity and the microflow end event.
9. Position the **Retrieve** activity between the **ListAssetModels** activity and the microflow end event.

2023-09-04 07:35 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +10. Double-click the **Retrieve** activity.
Not necessary, can be removed.

2023-09-04 07:38 UTC, trongbtran requested changes
Added some comments for missing information/incorrect information to be changed.

2023-09-05 16:51 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +6. In the **Edit parameters** section, edit the **AWS_Region** parameter, and provide a value by using a variable or an expression. For a list of available AWS regions, see [AWS_Region](#aws_region).
Done.

2023-09-05 16:52 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INCOMPATIBLE_COMPUTE_LOCATION` | INCOMPATIBLE_COMPUTE_LOCATION |  |
Done.

2023-09-05 16:52 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INCOMPATIBLE_FORWARDING_CONFIGURATION` | INCOMPATIBLE_FORWARDING_CONFIGURATION |  |
Done.

2023-09-05 16:53 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INTERNAL_FAILURE` | INTERNAL_FAILURE |  |
Done.

2023-09-05 16:53 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `VALIDATION_ERROR` | VALIDATION_ERROR |  |
Done.

2023-09-05 17:10 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `LIMIT_EXCEEDED` | LIMIT_EXCEEDED |  |
Done.

2023-09-05 17:10 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `INTEGER` | INTEGER | The variable is of type string. |
Done.

2023-09-05 17:10 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `_DOUBLE` | DOUBLE | The variable is of type string. |
Done.

2023-09-05 17:31 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `_BOOLEAN` | BOOLEAN | The variable is of type string. |
Done.

2023-09-05 17:31 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| `STRUCT` | STRUCT | The variable is of type string. |
Done.

2023-09-05 17:32 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +9. Position the **Retrieve** activity between the **GetAssetPropertyValue** activity and the microflow end event.
Done.

2023-09-05 17:32 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +5. Double-click the **GetAssetPropertyValue** microflow activity to configure the required parameters.
Done.

2023-09-05 17:33 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
Done.

2023-09-05 17:34 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
Done.

2023-09-05 17:55 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +4. Drag the **GetAssetPropertyValue** activity onto the work area of your microflow.
Done.

2023-09-05 17:56 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +3. In the **App Explorer**, in the **AmazonRekognitionConnector** > **Operations** section, find the **GetAssetPropertyValue** activity.
Done.

2023-09-05 17:56 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +2. Enter a name for your microflow, for example, *ACT_GetAssetPropertyValue*, and then click **OK**.
Done.

2023-09-05 17:57 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +After you configure the authentication profile for AWS IoT SiteWise, you can implement the functions of the connector by using the provided activities in microflows. For example, to retrieve an asset
Done.

2023-09-05 17:57 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +### 3.2 Configuring a Microflow for an AWS Service
Done.

2023-09-06 06:06 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +12. In the **Select Association** dialog box, in the **Association** section, click **Select**, and then select **GetAssetPropertyValue** as the association.
12. In the **Select Association** dialog box, in the **Association** section, click **Select**, and then select **ListAssetModels** as the association.

2023-09-06 06:06 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +14. Configure a method for triggering the **ACT_GetAssetPropertyValue** microflow. For example, you can trigger a microflow by associating it with a custom button on a page in your app. For an exampl
14. Configure a method for triggering the **ACT_ListAssetModels** microflow. For example, you can trigger a microflow by associating it with a custom button on a page in your app. For an example of how this can be implemented, see [Creating a Custom Save Button with a Microflow](/refguide/creating-a-custom-save-button/).

2023-09-06 06:07 UTC, trongbtran commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| P`ROPAGATING` | PROPAGATING | The asset model's changes are propagating to its assets. |
| `PROPAGATING` | PROPAGATING | The asset model's changes are propagating to its assets. |

2023-09-06 06:07 UTC, trongbtran requested changes
Minor change requests

2023-09-06 07:51 UTC, oenerayca commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +After you configure the authentication profile for AWS IoT SiteWise, you can implement the functions of the connector by using the provided activities in microflows. For example, to retrieve an asset
So the rest of this part is about ListAssetModels but the explanation is about GetAssetPropertyValue and the activity is given as ListAssets, so I am going to suggest some changes assuming that we are explaining how to implement **ListAssetModels**. 

For example, to retrieve a list of asset models, implement the [ListAssetModels](#list-asset-models) activity by doing the following steps:

2023-09-06 11:02 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +12. In the **Select Association** dialog box, in the **Association** section, click **Select**, and then select **GetAssetPropertyValue** as the association.
Done.

2023-09-06 11:03 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +14. Configure a method for triggering the **ACT_GetAssetPropertyValue** microflow. For example, you can trigger a microflow by associating it with a custom button on a page in your app. For an exampl
Done.

2023-09-06 11:04 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +| P`ROPAGATING` | PROPAGATING | The asset model's changes are propagating to its assets. |
Done.

2023-09-06 11:05 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/aws/aws-iot-sitewise.md
> +After you configure the authentication profile for AWS IoT SiteWise, you can implement the functions of the connector by using the provided activities in microflows. For example, to retrieve an asset
Done.

2023-09-06 11:38 UTC, merged