updated links and curl requests in Catalog for upcoming V5 Api changes
mendix/docs pull request #6375
Opened 2023-08-03 13:59 UTC by gmzakpinar

2023-08-04 07:43 UTC, MarkvanMents requested changes
Hi Gamze (@gmzakpinar)
Thanks for the PR.
Looks good. I've made a couple of review comments which may need to be looked at.
Mark

2023-08-04 07:43 UTC, MarkvanMents commented on content/en/docs/catalog/manage/search.md
> +    "TotalResults": 177,
Does this example have to be so long? It breaks up reading the document.
If it has to be this big, could the example use either of the following solutions:
1.  JSON inside an expandable section like this

**<details><summary>Click to see JSON response body</summary>**
``` json
this is the json
```
</details>

2. In a section at the end of the document?

2023-08-04 07:43 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +curl --location --request PUT 'https://catalog.mendix.com/rest/registration/v5/applications/{AppUUID}' \
Below, we use `{application_UUID}` - should be be consistent and either change this one, or the ones below?

2023-08-04 07:43 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +curl --location --request PUT 'https://catalog.mendix.com/rest/registration/v5/applications/{application_UUID}/environments/{EnvironmentUUID}' \
Where does `{EnvironmentUUID}` come from? It isn't mentioned as one of the things you need, above.

2023-08-04 07:43 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +curl --location --request PUT 'https://catalog.mendix.com/rest/registration/v5/applications/{AppUUID}' \
Where does `{AppUUID}` come from? It isn't mentioned as one of the things you need, above.

2023-08-04 07:43 UTC, MarkvanMents commented on content/en/docs/catalog/manage/search.md
> +            "Href": "https://catalog.mendix.com/rest/search/v4/data?offset=0&contractType=OData&query=Customer&limit=20"
This response uses the V4 API.

2024-05-30 09:13 UTC, NammNguyen commented on content/en/docs/catalog/manage/search.md
> +    "TotalResults": 177,
Hi Mark, we will be releasing the V5 version of our API soon so I'll be revisiting this PR and work on your review comments. 

To answer this question, yes it has to be this big. This is actually just the search result response with a single Endpoint. I've put the example in a details section as you mentioned

2024-05-30 11:04 UTC, NammNguyen commented on content/en/docs/catalog/register/register-data.md
> +curl --location --request PUT 'https://catalog.mendix.com/rest/registration/v5/applications/{AppUUID}' \
Good point, It is not mentioned anywhere you need it, just the application name. I've updated it to show a POST call where you don't need it

2024-05-30 11:06 UTC, NammNguyen commented on content/en/docs/catalog/register/register-data.md
> +curl --location --request PUT 'https://catalog.mendix.com/rest/registration/v5/applications/{application_UUID}/environments/{EnvironmentUUID}' \
Same as above, updated it so you don't need it

2024-05-30 11:39 UTC, NammNguyen commented on content/en/docs/catalog/manage/search.md
> +            "Href": "https://catalog.mendix.com/rest/search/v4/data?offset=0&contractType=OData&query=Customer&limit=20"
Good catch, fixed

2024-06-03 14:37 UTC, MarkvanMents reviewed
Looks great.
I've made a couple of suggestions, but nothing major.
Glad this has finally made it to publication!

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/manage/search.md
> +<details><summary> Example </summary>
I think a bit more text as the summary, and perhaps **bold**, would make this more obvious. I nearly missed it and I knew it was here 😀

It could be something like my original suggestion: 
**Click to see JSON response body**
or something else?

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
>  ```curl
```suggestion
```bash
```
([curl is not a recognized language](https://github.com/PrismJS/prism/issues/1160) so the format is bad).

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +Use the application_UUID to register your environment.
```suggestion
Use the application `uuid` to register your environment.
```
Format to link back to the JSON you get back which has the name `uuid`.

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
>  ```curl
```suggestion
```bash
```

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +Use the application_UUID and the environment_UUID to register one or more services.
```suggestion
Use the application `uuid` and the environment `uuid` to register one or more services.
```

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +
```suggestion
```
Extra line - not needed.

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
> +For more details on what can and cannot be provided in these fields, see the [API specification](https://datahub-spec.s3.eu-central-1.amazonaws.com/registration_v5.html#/Register/put_applications__Ap
We can publish the spec directly on the docs site if you want. We now support Swagger.
But we can discuss this as a future change.

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
>  ```curl
```suggestion
```bash
```

2024-06-03 14:37 UTC, MarkvanMents commented on content/en/docs/catalog/register/register-data.md
>  ```curl
```suggestion
```bash
```

2024-06-04 08:24 UTC, NammNguyen commented on content/en/docs/catalog/manage/search.md
> +<details><summary> Example </summary>
Good suggestion, that will make it more obvious

2024-06-04 08:26 UTC, NammNguyen commented on content/en/docs/catalog/register/register-data.md
> +For more details on what can and cannot be provided in these fields, see the [API specification](https://datahub-spec.s3.eu-central-1.amazonaws.com/registration_v5.html#/Register/put_applications__Ap
Yes agreed, all our specs are currently on S3 and they are quite big with lots of schemas

2024-06-11 11:07 UTC, quinntracy commented
@MarkvanMents @NammNguyen Have you both finished your updates? If so, I can mark this PR as approved so we can merge it when appropriate.

2024-06-11 12:21 UTC, MarkvanMents commented
> @MarkvanMents @NammNguyen Have you both finished your updates? If so, I can mark this PR as approved so we can merge it when appropriate.

I don't have anything else.

2024-06-14 12:53 UTC, MarkvanMents approved these changes
Looks good now.

2024-06-20 07:19 UTC, MarkvanMents commented
Release confirmed over Slack

2024-06-20 07:26 UTC, merged