MindSphere goes Insights Hub
mendix/docs pull request #6484
Opened 2023-09-05 11:24 UTC by StefanKellerSiemens

Please assign this pull request to Mark van Ments and please do not merge bevor we release our new app store modules.

2023-10-02 11:49 UTC, MarkvanMents requested changes
Thanks for the PR @StefanKellerSiemens and @HeikoOsigus - there is a lot of work in there. Sorry I didn't do it earlier, but I was waiting for a response to my email question.

I've done a proofread which you can see in this commit: https://github.com/mendix/docs/pull/6484/commits/5c2ca9ee3f2ddacfa504d53a6191fd6b473e6eb9

I have also made a couple of comments below, which I'd like you to address.

Do we need a note somewhere about the renaming as existing MindSphere-enabled apps will still have the old names.
Is there a process they need to follow to upgrade to the new modules with the new names?

Please can you look at the changes and my questions and let me know whether any further changes are needed and when you would like this to be published.

2023-10-02 11:49 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-development-considerations.md
> +You can select Insights Hub icons from Siemens Insights Hub Web Content to be displayed as SVGs in your application.
You've changed the title to 'glyphicons' but still talk about SVGs in the text. Should these be consistent?

2023-10-02 11:49 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-module-details.md
> +## 4 Siemens Insights Hub Web Content{#msthemepack}
Above you rename this **Siemens Insights Hub Widgets**

2023-10-02 11:49 UTC, MarkvanMents commented on content/en/docs/releasenotes/catalog/_index.md
> +* **Insights Hub** applications are now indicated with the display of the Insights Hub logo for all associated assets in the Catalog.
Is this true? Has the logo in the Catalog been changed.

I think it is better to leave the release notes alone and add a new release note to say that MindSphere has been replaced by Insights Hub whenever the update is made to Catalog.

2023-10-02 11:49 UTC, MarkvanMents commented on content/en/docs/appstore/modules/deep-link.md
> +    * When using the module with a Siemens Insights Hub app, use `/sso-login.html?redirect_uri=` as a login location (Insights Hub SSO V2.0 and above is required, for versions below V4.0 use mindsphe
I find this confusing as we talk about Insights Hub SSO V2.0 and then talk about versions below V4.0.
Are we talking about two different modules here, or is there some other way we can make it clearer?

2023-10-09 08:48 UTC, StefanKellerSiemens commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-development-considerations.md
> +You can select Insights Hub icons from Siemens Insights Hub Web Content to be displayed as SVGs in your application.
Good catch, should be consistent, maybe we just remove the SVG part?

2023-10-09 08:50 UTC, StefanKellerSiemens commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-module-details.md
> +## 4 Siemens Insights Hub Web Content{#msthemepack}
We have a theme which is called **Siemens Insights Hub Web Content** and we have widgets which has been called **Siemens MindSphere Web Widgets** and nowadays only **Siemens Insights Hub Widgets**. So we have two different things here, and the title fits for me.

2023-10-09 08:51 UTC, StefanKellerSiemens commented on content/en/docs/releasenotes/catalog/_index.md
> +* **Insights Hub** applications are now indicated with the display of the Insights Hub logo for all associated assets in the Catalog.
OK, we can do as you suggesting.

2023-10-09 08:55 UTC, StefanKellerSiemens commented on content/en/docs/appstore/modules/deep-link.md
> +    * When using the module with a Siemens Insights Hub app, use `/sso-login.html?redirect_uri=` as a login location (Insights Hub SSO V2.0 and above is required, for versions below V4.0 use mindsphe
We talk just about one module here. At least the version V2.0 is needed.
But if you use a version >= 2.0 < 4.0 (old ones) you have to use mindsphere-login.html and not sso-login.

Maybe we do not need to explain how it works with older version. What is the Mendix philosophy? Just talking about the latest and greatest?

2023-10-09 09:24 UTC, MarkvanMents requested changes
@StefanKellerSiemens 
I've resolved most of the issues and made a couple of suggestions.
Can you review them and commit the changes if you are happy (or let me know and I will commit them).
I think we are ready to publish once those changes are committed.
Thanks for the PR and all the work you have put into it.
Mark

2023-10-09 09:24 UTC, MarkvanMents commented on content/en/docs/appstore/modules/deep-link.md
> +    * When using the module with a Siemens Insights Hub app, use `/sso-login.html?redirect_uri=` as a login location (Insights Hub SSO V2.0 and above is required, for versions below V4.0 use mindsphe
I think we should still talk about old versions, but probably rephrase it a bit to make it clearer (to me!)
```suggestion
    * When using the deep link module with a Siemens Insights Hub app, use `/sso-login.html?redirect_uri=` as the login location if you are using version 4.0 and above of Insights Hub SSO. For versions of Insights Hub SSO between version 2.0 and version 4.0 use `mindsphere-login.html` as the `redirect_uri`. Insights Hub SSO below version 2.0 does not support login location on deep links.
```

2023-10-09 09:24 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-development-considerations.md
> +You can select Insights Hub icons from Siemens Insights Hub Web Content to be displayed as SVGs in your application.
```suggestion
You can select Insights Hub icons from Siemens Insights Hub Web Content to be displayed in your application.
```

2023-10-09 09:24 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-development-considerations.md
> +You can select Insights Hub icons from Siemens Insights Hub Web Content to be displayed as SVGs in your application.
👍 see suggestion below.

2023-10-09 09:24 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mendix-on-mindsphere/mindsphere-module-details.md
> +## 4 Siemens Insights Hub Web Content{#msthemepack}
👍 I'll mark this as resolved.

2023-10-09 09:24 UTC, MarkvanMents commented on content/en/docs/releasenotes/catalog/_index.md
> +* **Insights Hub** applications are now indicated with the display of the Insights Hub logo for all associated assets in the Catalog.
Changes reverted in https://github.com/mendix/docs/pull/6484/commits/675e81f8f0c2ea90c53d0a82c03e161a11b0b038

2023-10-09 10:16 UTC, MarkvanMents approved these changes
Ready to be published when artifacts are published.

2023-10-27 15:09 UTC, MarkvanMents commented
Approval for publication given over email.

2023-10-27 15:22 UTC, merged