Autofetch and Push-Pull experience updates
mendix/docs pull request #6487
Opened 2023-09-06 11:37 UTC by mikita-haurykau

2023-09-06 12:40 UTC, tknippenberg approved these changes
Added two more remarks. I think it's ready to go.

2023-09-06 12:40 UTC, tknippenberg commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +Studio Pro uses [Autofetch](/refguide/auto-fetch/) to discover changes on the server. If by the moment you click Commit the remote changes are known to Studio Pro, the Commit dialog will contain a no
Can you change "autofetch" to "automatic fetching" please?

2023-09-06 12:40 UTC, tknippenberg commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/remote-local-rebase.png
I don't think you're referencing this file. Can it be removed from the PR?

2023-09-06 12:52 UTC, mikita-haurykau commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/remote-local-rebase.png
Corrected in last commit

2023-09-06 12:52 UTC, mikita-haurykau commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +Studio Pro uses [Autofetch](/refguide/auto-fetch/) to discover changes on the server. If by the moment you click Commit the remote changes are known to Studio Pro, the Commit dialog will contain a no
Corrected in last commit

2023-09-06 12:58 UTC, MarkvanMents commented
@mikita-haurykau 
Is this for 10.3, or immediate publication?

2023-09-07 15:07 UTC, MarkvanMents requested changes
@mikita-haurykau 
I've proofread this and made some changes.
Also asked a few questions about things.
Can you have a look, and also confirm that this PR is for 10.3

2023-09-07 15:07 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +Select **Enable automatic fetching from a repository** to enable the [Automatic fetch mechanism](/refguide/auto-fetch/).
According to auto-fetch.md, you can also set the fetch interval here, but I don't see that mentioned.

2023-09-07 15:07 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/auto-fetch.md
> +* the number of outgoing commits – commits that exist on your machine (local commits) but are not pushed to the remote
I think we could make this even clearer by emphasizing that we are talking about the current branch:
```suggestion
* the number of incoming commits that exist on this branch of the remote but are not pulled to your machine yet
* the number of outgoing commits that exist on this branch on your machine (local commits) but are not pushed to the remote 
```

2023-09-07 15:07 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +The features described in this section were introduced in Mendix version 10.3.
Is this true for all the features in this section?

2023-09-07 15:07 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +While you were working on your branch somebody may have pushed their changes to the server already. In this case pushing isn’t possible and you will need to take further action first.
I think we should specify that they are using the same branch.
```suggestion
While you were working on your branch somebody may have pushed their changes to the same branch on the server already. In this case pushing isn’t possible and you will need to take further action first.
```

2023-09-07 15:07 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +{{< figure src="/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png" alt="The local changes consist of commits 1, 4, and 5 while the remote server has commi
I'm not sure about this picture. It looks very similar to the pictures about working on separate branches, but in this case we are talking about working on a single branch. I had to think twice about it, and a citizen developer might not spot the difference.

2023-09-07 15:08 UTC, MarkvanMents commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
I'm not sure about this picture. It looks very similar to the pictures about working on separate branches, but in this case we are talking about working on a single branch. I had to think twice about it, and a citizen developer might not spot the difference.

2023-09-12 08:13 UTC, MarkvanMents commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
Just in case you miss the [original comment](https://github.com/mendix/docs/pull/6487#discussion_r1318756572):
>  I'm not sure about this picture. It looks very similar to the pictures about working on separate branches, but in this case we are talking about working on a single branch. I had to think twice about it, and a citizen developer might not spot the difference.

2023-09-19 09:53 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +Select **Enable automatic fetching from a repository** to enable the [Automatic fetch mechanism](/refguide/auto-fetch/).
This newly-added setting is called **Enable automatic fetching from a remote repository**. It's missing the word "remote" in the above doc update. 

I also think we need to describe the **Fetch interval, minutes** setting here as well.

2023-09-19 09:53 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +Select **Enable automatic fetching from a repository** to enable the [Automatic fetch mechanism](/refguide/auto-fetch/).
There are also two settings in this **Version contorl** tab that are missing descriptions: **Truncate long values** under the **Changes** section, and **Show warning on updating marketplace modules** under the **Solution warning** section. These settings are already there before 10.3 though. The former is already there in SP 9 (I checked 9.24). I wonder who can help to add the descriptions (or verify the descriptions if we add them ourselves)?

2023-09-22 07:11 UTC, mikita-haurykau commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
It is indeed very similar 
Technically the concept is the same. only branches differ

2023-09-22 12:43 UTC, MarkvanMents requested changes
Hi @mikita-haurykau 
Thanks for responding to my initial questions.
I have made a couple more changes and there are a couple of items in the preference pane which are not documented.
Can you have one more look through my questions and let me have some answers. I can also ask in #mcr-support if someone else knows the answers.
Thanks.

2023-09-22 12:43 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +This setting was introduced in Mendix version 10.3.
Actually, @mikita-haurykau, it seems to be there in my version of 10.2. When was it actually released?

2023-09-22 12:43 UTC, MarkvanMents commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
Is there a way of drawing it so that it looks less like two branches? Perhaps by changing the labels to "Server version" and "Local version containing your work"?

2023-09-22 12:43 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +{{< figure src="/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png" alt="The local changes consist of commits 1, 4, and 5 while the remote server has commi
Dealt with below.

2023-09-22 12:43 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +Select **Enable automatic fetching from a repository** to enable the [Automatic fetch mechanism](/refguide/auto-fetch/).
Updated in commit https://github.com/mendix/docs/pull/6487/commits/388814e9c249dd0e355857fd680ace8406d64658

2023-09-22 12:43 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> -### 5.2 Subversion
This seems to be removed in Mx 10 - OK to remove this section?

2023-09-22 12:43 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +#### 5.3.1 Truncate Long Values
What does this do?

2023-09-22 12:43 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +#### 5.4.1 Show Warning on Updating Marketplace Modules
What does this do?

2023-09-22 13:26 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> -### 5.2 Subversion
@MarkvanMents I've removed this section in my PR here: https://github.com/mendix/docs/pull/6435/files#r1328913756. Its subsection below also has an anchor `#enable` that is used in another two version control docs. I've created a new anchor for the **Enable Private Version Control with Git** section and updated the anchor in the two version control docs using the new anchor (I've actually [tagged](https://github.com/mendix/docs/pull/6435/files#r1328942119) you in my PR for your review on this update). So perhaps it's better not to delete this section in your PR to avoid any merge conflicts later?

2023-09-22 14:48 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> -### 5.2 Subversion
OK - I'll put it back in and you can remove it.

2023-09-22 14:51 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> -### 5.2 Subversion
Thanks!

2023-09-22 15:02 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> -### 5.2 Subversion
I'll also leave a label to remind me that the sections numbers will need to be updated 😀

2023-09-22 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> -### 5.2 Subversion
Done: https://github.com/mendix/docs/pull/6487/files/22f40fa864c180243cdeaf4191a0ca5d7f26e27a..924b1aa02cc0724f12829aee8b27b0ce6359944b

2023-09-25 07:27 UTC, mikita-haurykau commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +This setting was introduced in Mendix version 10.3.
Autofetch was releases in 10.2 
You are right

2023-09-25 07:35 UTC, mikita-haurykau commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
Updated the image.

2023-09-25 07:36 UTC, mikita-haurykau commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +#### 5.3.1 Truncate Long Values
Good question. Lets create a separate MR to address these improvements as they don't block the current changes.

2023-09-25 07:36 UTC, mikita-haurykau commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +#### 5.4.1 Show Warning on Updating Marketplace Modules
Good question. Lets create a separate MR to address these improvements as they don't block the current changes.

2023-09-25 11:21 UTC, MarkvanMents reviewed
@mikita-haurykau 
Thanks for all your work on this PR.
I've removed the sections which you've agreed to pick up later, and made a final commit to reflect your answers to my questions.
This looks ready for publication with Mx 10.3, so I'll approve it.

2023-09-25 11:21 UTC, MarkvanMents commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/server-your-work.png
Great! Thanks for that.

2023-09-25 11:21 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +This setting was introduced in Mendix version 10.3.
```suggestion
This setting was introduced in Mendix version 10.2.
```

2023-09-25 11:21 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
I'll take these out of this PR. Will you be able to pick these up and make a new PR after 10.3 is released @mikita-haurykau ?
```suggestion
```

2023-09-25 12:31 UTC, MarkvanMents approved these changes

2023-09-26 09:40 UTC, merged