SOLP-1808 Import module refguide
mendix/docs pull request #6491
Opened 2023-09-06 13:46 UTC by mikita-haurykau

2023-09-06 15:01 UTC, MarkvanMents commented
@mikita-haurykau - is this for Mendix 10.3?

2023-09-11 06:54 UTC, mikita-haurykau commented
> @mikita-haurykau - is this for Mendix 10.3?

Yes

2023-09-11 15:10 UTC, MarkvanMents requested changes
Hi @mikita-haurykau 
Thanks for the PR.
I've proofread it and resolved a few other editing issues which were left from previous submissions.
I've left a few comments and questions which I'd like you to look at and respond to.
Thanks
Mark

2023-09-11 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/_index.md
> -## 4 mx Tool Options
Moved this to the top.

2023-09-11 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/adaptable.md
> +* `Y` is the number of the parameter the error is related to (if applicable). The first parameter is parameter 0.
I think it helps to remind customers that we start counting at 0.

2023-09-11 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/adaptable.md
> +| `--help` | | Shows help for the `mx show-app-version` command and exits. |
The `-h` parameter doesn't work (Mendix 10.2.0.14269).
I don't know if this is intentional, but I've changed it throughout the documentation so it matches the product.

2023-09-11 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/module.md
> +{{% alert color="info" %}}
Added to the top as it is the only OPTION and there was no placeholder for [OPTIONS] in the command templates.

2023-09-11 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/module.md
> +Exit code 111
Shouldn't this be `101` since it is `Module.mxmodule` which is protected and cannot be imported.

2023-09-11 15:10 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/module.md
> +Exit code 303
Shouldn't this be `313` since it is `App.mpr` which already contain the module?

2023-09-21 12:53 UTC, mikita-haurykau commented on content/en/docs/refguide/general/mx-command-line-tool/module.md
> +Exit code 111
it should be 111

the exit code consists of three digits XYZ:

X determines the error type:
**1 - parameter validation error**
2 - output-related error
3 - errors related to the execution of the operation

Y is the number of the parameter the error is related to
**module is the first parameter**

Z determines error details:
**1 - Module you are trying to import is protected and cannot be imported.**

2023-09-21 12:55 UTC, mikita-haurykau commented on content/en/docs/refguide/general/mx-command-line-tool/module.md
> +Exit code 303
303 is the correct value

parameter files are valid on their own (i.e. first parameter is a module, it is valid, second parameter is a project and it is valid)

The error happens during the import operation so 
1 - parameter validation error
2 - output-related error
**3 - errors related to the execution of the operation**

Y is the number of the parameter the error is related to
**0 as both parameters are correct**

Z determines error details:
1 - Module you are trying to import is protected and cannot be imported.
2 - Module you are trying to import is Theme module and cannot be imported.
**3 - Project already contains a module with the name of an importing module. Thus the module can't be imported.**  this is what we figured when tried to add a module there
4 - Module is not found in the MPK package
5 - Project Version is not supported by the current version of Mx.exe
6 - Project can't be loaded
7 - Module can't be loaded
8 - Import of a module failed. Result project can't be saved.

2023-09-21 12:59 UTC, mikita-haurykau commented on content/en/docs/refguide/general/mx-command-line-tool/adaptable.md
> +* `Y` is the number of the parameter the error is related to (if applicable). The first parameter is parameter 0.
do we mention numbers anywhere in the documentation?
technically parameter number 0 is the name of the app

2023-09-22 13:19 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/adaptable.md
> +* `Y` is the number of the parameter the error is related to (if applicable). The first parameter is parameter 0.
Ah - I've looked at your explanations below and I understand better now. You put zero if neither parameter has an error. So perhaps say
```suggestion
* `Y` is the number of the parameter the error is related to (if applicable). It the error is not related to the parameters, this is zero.
```

2023-09-22 13:19 UTC, MarkvanMents commented on content/en/docs/refguide/general/mx-command-line-tool/module.md
> +Exit code 111
Thanks for the explanation. I was confused about the Y parameter, but I understand it now. Thanks.

2023-09-22 13:21 UTC, MarkvanMents requested changes
Thanks for your review and explanations @mikita-haurykau 
I didn't understand the use of 0 as the parameter position, so thanks for clarifying it.
I have made a suggestion for a slight change to avoid the misunderstanding - does it look OK to you.
Otherwise this PR is ready to be published.
Thanks.

2023-09-26 09:21 UTC, MarkvanMents approved these changes

2023-09-26 09:21 UTC, merged