Document microflow URLs and update page URL documentation
mendix/docs pull request #6520
Opened 2023-09-15 08:43 UTC by WimJongeneel

Planned for 10.3

2023-09-19 11:42 UTC, ConnorLand commented on content/en/docs/refguide/modeling/pages/data-widgets/data-view.md
> +| Context          | A data source that uses a context object which is already available, such as a page parameter, snippet parameter or the object of a surrounding data container. Page parameters ar
I need to check this change, but it's a discrepancy I found while editing this PR.

2023-09-19 11:55 UTC, Robinfr requested changes

2023-09-19 11:55 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +Microflow URLs allow you to execute a microflow when the user navigates to a specific URL within your application. The microflow will be executed during the client startup, just before the home page
> When the microflow executes a [Show page](/refguide/on-click-event/#show-page) action.

What? I'm missing half a sentence I think

2023-09-19 11:55 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +Microflow URLs allow you to execute a microflow when the user navigates to a specific URL within your application. The microflow will be executed during the client startup, just before the home page
> The microflow's full URL will be the base URL of your application, followed by `/p/`, followed by the page's configured URL.

I think you mean microflow's configured URL?

2023-09-19 11:55 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +Take this URL for an example: `http://example.mendixcloud.com/p/microflow`.
Usually, if you give an example, you're going to say something about the example. But here, we just have an example, and then.. nothing? 

I think what you were trying to do is give an example for the previous paragraph, in that case you can change this to something like:

```suggestion
For example: `http://example.mendixcloud.com/p/microflow`.
```

But it should be part of the previous paragraph (at the end).

2023-09-19 11:55 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +In the microflow URL dialog box, the configured URL is shown together with an example URL with example values filled in for the parameters. It and also shows how the parameter will be retrieved:
```suggestion
In the microflow URL dialog box, the configured URL is shown together with an example URL with example values filled in for the parameters. It also shows how the parameter will be retrieved:
```

2023-09-19 11:55 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +URLs are not supported for microflows that have non-persistable entities or lists as parameters.
Are there any types of parameters/attributes we don't support? Such as date times?

2023-09-19 12:55 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +URLs are not supported for microflows that have non-persistable entities or lists as parameters.
We do mention the supported types above:

> Any attribute or primitive parameter of types `Boolean`, `Decimal`, `Enumeration`, `Integer`, `Long`, or `String` can be used in the URL.

But we could also add it to the limitations here, but then we should also do the same for the Page URL documentation.

2023-09-20 14:03 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/microflow.md
> +URLs are not supported for microflows that have non-persistable entities or lists as parameters.
Ah if it's mentioned already it's fine.

2023-09-20 14:07 UTC, Robinfr approved these changes

2023-09-20 14:08 UTC, Robinfr commented
@ConnorLand Can be reviewed by you :) (Though I think you already started 😄)

2023-09-22 07:30 UTC, Yiyun333 commented
@ConnorLand I've finished my review on the microflow URL section. Please continue with your review.

2023-09-22 07:59 UTC, Yiyun333 commented
> @ConnorLand I've finished my review on the microflow URL section. Please continue with your review.

Sorry! I had to fix an anchor error in the build. Now there is no error in the build. Please continue :)

2023-09-25 11:44 UTC, ConnorLand approved these changes

2023-09-26 08:52 UTC, merged