Document reverse association direction
mendix/docs pull request #6521
Opened 2023-09-15 13:00 UTC by EnasAbdelrazek

2023-09-15 13:58 UTC, MarkvanMents requested changes
@EnasAbdelrazek 
Can you let me know what this actually does, as I think it is unclear from the description.

2023-09-15 13:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/associations/_index.md
> +You can reverse the association direction by right-clicking your association and selecting **Reverse direction**.
@EnasAbdelrazek 
What effect does this have on the association? I think we should clarify this for the customer. My assumption is:

1. A `1-*` becomes a `*-1` and vice-versa.
2. It has no effect on a `*-*` or a `1-1` association.

Can you confirm this so I can add it to the document?

2023-09-19 07:07 UTC, WimJongeneel requested changes

2023-09-19 07:07 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/domain-model/associations/_index.md
> +
I think we should also document what happens to existing data when using this option, is it migrated or lost? (I think the last, but then we properly should put a big red warning box here.)

2023-09-21 11:47 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/associations/_index.md
> +You can reverse the association direction by right-clicking your association and selecting **Reverse direction**.
It will exchange the ownership of the association. Reversing an association changes how you access associated entities. For example, if you initially had a one-to-many association from "Customer" to "Order" (1-*), it means each customer can have multiple orders. When reversed, you can access related customers from an order entity.

In all cases, all retrieval queries should be updated according to the new direction of the association.

In the case of a - (*-*) or a (1-1) association when both entities refer to each other bidirectionally, reversing the association should have no significant effect on the relationship itself.
The only thing you might need to consider is the new generated association name.

2023-09-21 11:58 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/associations/_index.md
> +
It will be new relationship structure. so the references will be deleted but the existing objects will stay.

2023-09-21 13:21 UTC, WimJongeneel approved these changes

2023-09-22 13:02 UTC, MarkvanMents reviewed
@EnasAbdelrazek and @WimJongeneel 
Thanks for your reviews and update of the documentation to include the additional information.
I have proofread this, so could you just check it once more to confirm I haven't changed the meaning.
Then this will be read to be published on

2023-09-22 13:02 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/associations/_index.md
> +
Thanks for this. I've updated the warning a little to emphasize that the actual objects are not deleted.

2023-09-22 13:02 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/associations/_index.md
> +You can reverse the association direction by right-clicking your association and selecting **Reverse direction**.
@EnasAbdelrazek Thanks for putting all this into an update. I've proofread this, can you just check it still says what you wanted it to say.

2023-09-25 07:59 UTC, EnasAbdelrazek commented
@MarkvanMents Thanks for your update, I have reviewed it and it looks great.

2023-09-25 08:21 UTC, MarkvanMents approved these changes
PR approved and ready to be published with Mendix version 10.3

2023-09-26 09:20 UTC, merged