Kk sap event mesh
mendix/docs pull request #6533
Opened 2023-09-19 13:56 UTC by katarzyna-koltun-mx

SAP Event Mesh connector

2023-10-03 11:45 UTC, gauravkrshah requested changes
Hi Kasia, kindly look comments and let me know if questions any.

2023-10-03 11:45 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +The following roles are required for the user to be able to configure the SAP Enterprise Messaging service:
As these roles need to be enabled at SAP subaccount level, we should specify it. something like

User should be assigned with below roles in SAP BTP subaccount from SAP Enterprise Messaging service is being used/provisioned.

2023-10-03 11:45 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +To ensure that your app can connect to the SAP service, you must also bind and configure the Enterprise Messaging service.
you must also bind and configure the Enterprise Messaging service - this appears little confusing to me, as there is separate activity of configuration after binding. Actually while service instance configuration has to be provided.
can we rephrase it like - SAP Enterprise Messaging service (event mesh) instance has to be created with desired configuration and service instance should be bind to app.

2023-10-03 11:45 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +The **Event Mesh Configurator** provides a user friendly interface to create the JSON required to configure the required Enterprise Messaging service. To bind and configure the service, perform the f
required to create Enterprise Messaging service instance with desired configuration.

2023-10-03 11:45 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +2. Click **⚙️ Configurator** to open the configurator.
configuration has to be applied while creating service instance. So Enterprise Messaging service will be in Available Services section then click on configurator.

2023-10-03 11:45 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +The domain model is a data model that describes the information in your application domain in an abstract way. For more information, see [Domain Model](/refguide/domain-model/).
Let us include event mesh connector domain model image, to explain each entity.

2023-10-03 11:45 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +* Queue or queues subscribed to the topic that you want to delete
After explaining all the actions, Let us include few microflows images to show how these actions will be used. Alternatively after every action once image can be include to demonstrate its usage.

2023-10-04 11:15 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +The following roles are required for the user to be able to configure the SAP Enterprise Messaging service:
Done.

2023-10-04 11:16 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +To ensure that your app can connect to the SAP service, you must also bind and configure the Enterprise Messaging service.
Done.

2023-10-04 11:30 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +The **Event Mesh Configurator** provides a user friendly interface to create the JSON required to configure the required Enterprise Messaging service. To bind and configure the service, perform the f
Done.

2023-10-04 11:32 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +2. Click **⚙️ Configurator** to open the configurator.
Done.

2023-10-04 11:37 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +The domain model is a data model that describes the information in your application domain in an abstract way. For more information, see [Domain Model](/refguide/domain-model/).
Done.

2023-10-04 14:02 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +* Queue or queues subscribed to the topic that you want to delete
Done.

2023-10-04 14:03 UTC, katarzyna-koltun-mx commented
@gauravkrshah I've done the requested updates. Please let me know if there's anything else, or if I should publish.

2023-10-06 11:29 UTC, mayankmendix commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +* Management of processes for all queues and topics
It should be 'Management of queues and queue subscriptions'

2023-10-06 11:29 UTC, mayankmendix commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +* Publishing an event to a queue
It should be just 'Publishing a cloud event'

2023-10-06 12:30 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +* Management of processes for all queues and topics
Done.

2023-10-06 12:30 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +* Publishing an event to a queue
Done.

2023-10-06 12:31 UTC, katarzyna-koltun-mx commented
@mayankmendix I've made the requested corrections. Let me know when we're ready to publish.

2023-10-10 06:38 UTC, gauravkrshah requested changes
Hi Kasia, 

Apart from few minor add/update everything looks fine. 
sample microflow images needs to be changed. Let me know if you need any in images. Thanks!

2023-10-10 06:38 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
>  1. Ensure that the **enterprise-messaging** service is in the status **Services To Be Bound** in Developer Portal. See the [Services Tab](/developerportal/deploy/sap-cloud-platform/#binding-services)
Point #2 states that Event mesh should be available in "Available Services" section while #1 says in "Services to be bound" section both are mutually exclusive. If services is in "To be bound" then it will not be in Available services.

In EM case, this needs to be Available services section to create instance

2023-10-10 06:38 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
>      * **EM Name** - enter a display name for the service.
this link https://help.sap.com/docs/event-mesh/event-mesh/syntax-for-service-descriptor?locale=en-US 
can be given in case more details of every parameter for configuration need to be understand

2023-10-10 06:38 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
>  The `PublishCloudEvent` activity allows you to publish events that are compliant with the Cloud Events specification. It requires the following parameters:
link to cloud events specifications - https://github.com/cloudevents/spec/tree/v1.0

this will clarify which version is supported.

2023-10-10 06:38 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +##### 4.3.3.1 Sample Microflow
sample microflow does not looks proper. it is missing the icon placed on java actions for example "consume message" looks like this - 
<img width="271" alt="image" src="https://github.com/mendix/docs/assets/25194234/b6a8f464-25bf-406d-ab8c-d79d48ea3806">

2023-10-10 06:38 UTC, gauravkrshah commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +##### 4.3.3.1 Sample Microflow
publish is like this 
<img width="195" alt="image" src="https://github.com/mendix/docs/assets/25194234/c503ba98-dd07-4823-9932-98f4cde59c43">

2023-10-11 15:16 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
>  1. Ensure that the **enterprise-messaging** service is in the status **Services To Be Bound** in Developer Portal. See the [Services Tab](/developerportal/deploy/sap-cloud-platform/#binding-services)
Done.

2023-10-11 15:18 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
>      * **EM Name** - enter a display name for the service.
Done.

2023-10-11 15:19 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
>  The `PublishCloudEvent` activity allows you to publish events that are compliant with the Cloud Events specification. It requires the following parameters:
Done.

2023-10-11 15:26 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/connectors/sap/sap-event-mesh-connector.md
> +##### 4.3.3.1 Sample Microflow
With this one, I'm not sure. Should this action be placed before, after or instead of one of the existing actions? I'm using the microflow ACT_PublishMessageToTopic/Queue from the SAP Connectors app.

2023-10-16 13:41 UTC, merged