sap UI themes
mendix/docs pull request #6549
Opened 2023-09-21 14:00 UTC by katarzyna-koltun-mx

2023-09-21 14:15 UTC, mayankmendix commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +You can also give the end-use the option to choose their own theme. There is an example of this on the **Home** page of the Web UI Package for SAP Fiori theme Marketplace Module. The end-user can cli
Now there are more than one dark theme and more than one light theme, so maybe we can just say that "click a button to switch between themes".

2023-09-21 14:16 UTC, mayankmendix commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +To do this you need to trigger a nanoflow which passes a variable containing the name of the theme to the **ChangeTheme_JavaScript_Action** JavaScript action. This changes the theme and implements it
After the "name of the theme", kindly mention 'from above list'.

2023-09-21 14:17 UTC, mayankmendix commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +* **theme-horizon-morning**
We need to mark a default theme. Need to confirm with Gaurav and will update.

2023-09-21 14:17 UTC, mayankmendix commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
In the introduction part of the page, lets also add that with Quartz themes now we also support Horizon evening and morning theme.

2023-09-22 15:04 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +You can also give the end-use the option to choose their own theme. There is an example of this on the **Home** page of the Web UI Package for SAP Fiori theme Marketplace Module. The end-user can cli
Done.

2023-09-22 15:05 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +To do this you need to trigger a nanoflow which passes a variable containing the name of the theme to the **ChangeTheme_JavaScript_Action** JavaScript action. This changes the theme and implements it
Done.

2023-09-22 15:06 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
Done.

2023-09-22 15:07 UTC, katarzyna-koltun-mx commented
@mayankmendix I've made the requested corrections, let me know about the default theme after you've discussed it with Gaurav.

2023-09-25 17:27 UTC, gauravkrshah commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +* **theme-horizon-morning**
@katarzyna-koltun-mx @mayankmendix there is no default theme in package. Default theme has to be mentioned in the index.html of the application like this:
<html class="theme-quartz-light">
Following themes are supported by the package
.theme-quartz-light
.theme-quartz-dark
.theme-horizon-morning
.theme-horizon-evening

2023-09-25 18:00 UTC, gauravkrshah requested changes

2023-09-25 18:00 UTC, gauravkrshah commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +To do this you need to trigger a nanoflow which passes a variable containing the name of the theme to the **ChangeTheme_JavaScript_Action** JavaScript action. This changes the theme and implements it
This javascript action is not part of UI_resource_package. Its upto developer how they implement change theme functionality. remove this line.

2023-09-25 18:00 UTC, gauravkrshah commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +The Mendix module gives you access to designing your pages with SAP Fiori-styled widgets and building blocks as part of your layout. You can also allow end-users to select a theme and apply it immedi
it would be good, if supported themes are mentioned as list. Let's put Horizon first and then Quartz's

2023-09-25 18:00 UTC, gauravkrshah commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +You can also give the end-use the option to choose their own theme. There is an example of this on the **Home** page of the Web UI Package for SAP Fiori theme Marketplace Module. The end-user can cli
This is not part of UI resource package.  Let's not mention this.
 theme change example is available in demo app  which is available on marketplace as community module.

2023-09-25 18:00 UTC, gauravkrshah commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +To do this you need to trigger a nanoflow which passes a variable containing the name of the theme from the above list to the **ChangeTheme_JavaScript_Action** JavaScript action. This changes the the
this nanoflow is not part of UI resource package, it is available as example in demo app. Let's not mention this. Its up to developer how they want to set variable value.

2023-09-28 08:20 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +You can also give the end-use the option to choose their own theme. There is an example of this on the **Home** page of the Web UI Package for SAP Fiori theme Marketplace Module. The end-user can cli
Done.

2023-09-28 08:20 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +To do this you need to trigger a nanoflow which passes a variable containing the name of the theme from the above list to the **ChangeTheme_JavaScript_Action** JavaScript action. This changes the the
Done.

2023-09-28 08:20 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +To do this you need to trigger a nanoflow which passes a variable containing the name of the theme to the **ChangeTheme_JavaScript_Action** JavaScript action. This changes the theme and implements it
Done.

2023-09-28 09:20 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +The Mendix module gives you access to designing your pages with SAP Fiori-styled widgets and building blocks as part of your layout. You can also allow end-users to select a theme and apply it immedi
Done.

2023-09-28 09:20 UTC, katarzyna-koltun-mx commented
@gauravkrshah All corrections done, let me know when I can publish.

2023-09-28 14:25 UTC, gauravkrshah approved these changes
one minor update.

2023-09-28 14:25 UTC, gauravkrshah commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +The Mendix module gives you access to designing your pages with SAP Fiori-styled widgets and building blocks as part of your layout. You can also allow end-users to select a theme and apply it immedi
replace this "You can also allow end-users to select a theme and apply it immediately" something like this
Mendix app can be build with following themes.

giving theme selecting to user is app feature, which is not part of UI_resource package

2023-10-02 12:32 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/sap-ui-resources/_index.md
> +The Mendix module gives you access to designing your pages with SAP Fiori-styled widgets and building blocks as part of your layout. You can also allow end-users to select a theme and apply it immedi
Done. Will merge the PR now.

2023-10-02 12:33 UTC, merged