Documentation for Managed Dependencies
mendix/docs pull request #6561
Opened 2023-09-25 13:46 UTC by akkrishnakumar

This PR contains a new page to describe the new managed dependency feature introduced in v10.3

2023-09-25 13:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/mendix/docs?pullRequest=6561) <br/>All committers have signed the CLA.

2023-09-25 13:54 UTC, Adam-Dupaski commented
CC @MarkvanMents for visibility via components update

2023-09-25 14:16 UTC, tknippenberg commented on static/attachments/refguide/java-programming/managed-dependencies/unknown-dependency.png
Can we do screenshots that aren't on a 1920x1080 resolution? So resize Studio Pro so in the screenshot there is a lot less useless space. Now the contents of the dialogue are unreadable without zooming.

2023-09-25 14:18 UTC, tknippenberg commented on static/attachments/refguide/java-programming/managed-dependencies/unknown-dependency.png
Or perhaps there shouldn't be screenshots at all for the errors, not sure. @MarkvanMents will know :)

2023-09-25 14:57 UTC, emiruner commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Once `Gradle` has resolved and downloaded all dependencies successfully, it places them in the `vendorlib` directory. This directory is used to store `.jar` files of all the managed dependencies. Con
This paragraph is almost same with the previous one.

2023-09-25 14:58 UTC, emiruner commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Most dependencies can be managed using this new Dependency Synchronization feature. But sometimes, users can have a custom jar which they are experimenting on, or which is simply not available in any
Would `Managed Dependencies feature` be better instead of `Dependency Synchronization feature`?

2023-09-25 14:59 UTC, emiruner commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +The platform-supported Marketplace modules created by Mendix have been updated with a custom mechanism to automatically migrate to managed dependencies. Each module with Java dependencies contains a
Should we omit the details about automatic migration, i.e. the sentence `Each module...`?

2023-09-25 15:25 UTC, emiruner reviewed
Added some comments.

2023-09-25 19:44 UTC, MarkvanMents commented
Hi @akkrishnakumar 
Akhil, a couple of things:

1. Please can you commit changes rather than doing a force push. I have twice had to do a manual merge of my changes with yours as the original commit disappears.
2. Please can you sign the CLA for our records, it means that we can see both checks passing (although for Mendixites we can use your text anyway, but it makes our process cleaner).

I will continue to work on this tomorrow morning and hope to have a version for final review by around 11:00

2023-09-26 07:28 UTC, lvanengelen commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +The platform-supported Marketplace modules created by Mendix have been updated with a custom mechanism to automatically migrate to managed dependencies. Each module with Java dependencies contains a
I'm unsure whether 'platform-supported Marketplace modules' is a known thing outside of Mendix, so should we even have this paragraph?

2023-09-26 08:51 UTC, MarkvanMents requested changes
Hi @akkrishnakumar 
Hi Akhil,
I've now done a full proofread of the document. There are a couple of outstanding issues and questions - can you have a look at them?

I've removed all references to the gradle identifier being `group:artifact:version` as the user never sees them like that - they enter the three variables in different text fields in the UX.

2023-09-26 08:51 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Once `Gradle` has resolved and downloaded all dependencies successfully, it places them in the `vendorlib` directory. This directory is used to store `.jar` files of all the managed dependencies. Con
Removed.

2023-09-26 08:51 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Most dependencies can be managed using this new Dependency Synchronization feature. But sometimes, users can have a custom jar which they are experimenting on, or which is simply not available in any
Changed.

2023-09-26 08:51 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +The platform-supported Marketplace modules created by Mendix have been updated with a custom mechanism to automatically migrate to managed dependencies. Each module with Java dependencies contains a
I think it is best to leave this out, it just makes it more complex and the customer doesn't need to know how it works.

2023-09-26 08:51 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +{{% todo %}}Need to ask Leroy for the SS{{% /todo %}}
This still needs to be done.

2023-09-26 08:51 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Dependency information is included per module and included in Marketplace Modules. The actual dependency artifacts are not included, as these are automatically synchronized upon import.
What do you mean by
> The actual dependency artifacts are not included, as these are automatically synchronized upon import.

Do you mean that the .jars are not added to the vendorlib in the module, but are created in the app's vendorlib when synchronization is run?

2023-09-26 08:51 UTC, MarkvanMents commented on static/attachments/refguide/java-programming/managed-dependencies/unknown-dependency.png
I agree with the visibility - but I'm not sure the screenshots add anything. Is it OK to remove them?

2023-09-26 08:57 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
>  {{< figure src="/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-dialog.png" >}}
This image is now incorrect - it doesn't have the tabs on it.

2023-09-26 09:03 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
These changes don't make any sense to me. The first section should be an introduction to Module Settings.
I'll restructure it.

2023-09-26 09:17 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
> +Access to this functionality is currently limited and can be gained through the [Mendix Component Partner Program](/appstore/creating-content/partner-program/) and the [Mendix Commercial Solution Par
Are you also restricted when setting the **Module Version**

2023-09-26 09:28 UTC, akkrishnakumar commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +The platform-supported Marketplace modules created by Mendix have been updated with a custom mechanism to automatically migrate to managed dependencies. Each module with Java dependencies contains a
Agreed, we can remove the 2nd paragraph

2023-09-26 09:45 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
Restructured module-settings.
@akkrishnakumar - can you have a look and see if this is now OK?

2023-09-26 09:49 UTC, MarkvanMents commented on static/attachments/refguide/java-programming/managed-dependencies/unknown-dependency.png
Removed in this commit: https://github.com/mendix/docs/pull/6561/commits/bba1e309378b1aea9855e43404e03eb6c5730345

2023-09-26 09:51 UTC, akkrishnakumar commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Dependency information is included per module and included in Marketplace Modules. The actual dependency artifacts are not included, as these are automatically synchronized upon import.
Yes.

2023-09-26 09:52 UTC, akkrishnakumar commented on static/attachments/refguide/java-programming/managed-dependencies/unknown-dependency.png
We can remove the screenshots

2023-09-26 09:58 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +The platform-supported Marketplace modules created by Mendix have been updated with a custom mechanism to automatically migrate to managed dependencies. Each module with Java dependencies contains a
@lvanengelen 
Hi Leroy.
Platform-supported Marketplace modules are definitely a thing. They are the ones which we document on the docs site and many companies will only use modules which are platform supported so that they can get support from us if they have issues.

So I think the first half of the paragraph is definitely worth including.

2023-09-26 10:12 UTC, lvanengelen commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
>  {{< figure src="/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-dialog.png" >}}
Replaced it with two images: one for each tab.

2023-09-26 10:16 UTC, lvanengelen commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
I'm mostly ok with the update, but
> Module settings allow you to set Java managed dependencies, choose the type of the module when you build your app, and set a version for certain module types.
The MCR team owns the **Export** part of this dialog. I'm unsure whether the wording here ('...when you build your app') is entirely correct.

2023-09-26 10:18 UTC, lvanengelen commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
> +Access to this functionality is currently limited and can be gained through the [Mendix Component Partner Program](/appstore/creating-content/partner-program/) and the [Mendix Commercial Solution Par
I don't know the details about the **Export** part of the dialog, I just kept the original text when restructuring this page. The MCR team should know the details.

2023-09-26 10:51 UTC, lvanengelen commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
Removed the part I am unsure about ('when you build your app') so we won't block on this.

2023-09-26 10:52 UTC, lvanengelen commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
> +Access to this functionality is currently limited and can be gained through the [Mendix Component Partner Program](/appstore/creating-content/partner-program/) and the [Mendix Commercial Solution Par
I suggest we leave this up for the MCR team to clarify in a different PR.

2023-09-26 12:13 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
Great. Thanks.

2023-09-26 12:17 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Dependency information is included per module and included in Marketplace Modules. The actual dependency artifacts are not included, as these are automatically synchronized upon import.
@akkrishnakumar can I then say:
```suggestion
Dependency information is included per module and included in Marketplace Modules. The actual dependency artifacts are created in the `vendorlib` folder automatically when synchronization is run when the module is imported.
```

2023-09-26 12:17 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/modules/module-settings.md
>  {{< figure src="/attachments/refguide/modeling/app-explorer/modules/module-settings/module-settings-dialog.png" >}}
Thanks.

2023-09-26 12:23 UTC, lvanengelen commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Dependency information is included per module and included in Marketplace Modules. The actual dependency artifacts are not included, as these are automatically synchronized upon import.
I have a small preference of mentioning that the artifacts are not part of the module, but if you think that's too much detail we can leave it out.

2023-09-26 12:31 UTC, lvanengelen commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +Dependency information is included per module and included in Marketplace Modules. The actual dependency artifacts are not included, as these are automatically synchronized upon import.
```suggestion
Dependency information is included per module and included in Marketplace Modules. The actual artifacts (`.jar` files) are not part of the module. They are downloaded in the `vendorlib` folder automatically when synchronization is run when the module is imported.
```

2023-09-26 12:37 UTC, MarkvanMents commented
Publication approved over Slack.

2023-09-26 12:45 UTC, MarkvanMents approved these changes

2023-09-26 12:45 UTC, merged