Language review for Mendix Public Cloud
mendix/docs pull request #6587
Opened 2023-10-02 12:42 UTC by dbreseman

2023-10-06 09:57 UTC, MarkvanMents requested changes
@dbreseman 
Hi Dana,
I've started my review but am taking a break now so will submit a partial review.
Generally this is a great improvement and makes the document much better.
I have made a few comments on your changes. Feel free to discuss them (here or in person) - I'm open to changing my opinion!
I'll try to do the rest of the review later today.

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Access Restriction Profiles, including TLS Certificate Profiles and IP Filtering Profiles
Not sure about this change. You are now duplicating "Access Restriction Profiles" and it doesn't seem to add any information.

Were you concerned that there is more to Access Restriction Profiles than just the two things mentioned here?

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Activity
I found it confusing that there are three bullet points which are now **Activity**. (Perhaps only because I am reviewing changes, or perhaps not?). I wonder if we ought to categorize them to make it clearer why they are there?
e.g. Permissions Activity, Deployment Activity, and Services Activity?

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +For standard environments, your node has production and acceptance environments. Optionally, it can also include a test environment.
Do you think we need to have "Optionally," here, or is the optionality carried by the "can"?

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +For standard environments, your node has production and acceptance environments. Optionally, it can also include a test environment.
Also, I think we should perhaps say
```suggestion
For standard plans, your node has production and acceptance environments. Optionally, it can also include a test environment.
```
Otherwise it gets confusing.

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Red x – there is at least one critical alert
"Red cross", since we describe the other icons, rather than just showing them?

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Runtime**, the Studio Pro version with which the app is built (for example, 7.6.0)
Perhaps we should update the image and put some Mendix 10 mdas there instead?
Version 7 is no longer supported!

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Red x – there is at least one critical alert
See above.

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Runtime**, the Studio Pro version with which the app is built (for example, 7.6.0)
In the image the examples are different from the previous image (e.g. `7.22.2.44474` rather than `7.6.0`), but perhaps we should look at getting a newer image in any case.

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Plan** for the environment; for more information, see [Details](/developerportal/deploy/environments-details/)
```suggestion
* **Plan** for the environment; for more information, see [Environment Details](/developerportal/deploy/environments-details/)
```

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +In the **Permissions** tab, the [Technical Contact](/developerportal/general/app-roles/#technical-contact) and other team members who have the **Manage Permissions** permission can manage various per
Cannot see the the **Deploy, Publish, and Monitor** permission. Is this actually the **Transport Rights** and  **Access to Monitoring** permissions?
![image](https://github.com/mendix/docs/assets/35492184/e2b4f642-cf33-49df-a0a9-56b4ad22b463)

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Mendix Event Broker** – required to use [Mendix Business Events](/appstore/modules/business-events/) on Production apps
Not sure what this was supposed to be saying! I think perhaps it meant ***on* the Environments page**. But I don't think we need this. We also have a list with a single bullet point (for historical reasons!) so perhaps we should completely rewrite.
```suggestion
The custom services that are available on the app level.

Only one service is available: **Mendix Event Broker** – required to use [Mendix Business Events](/appstore/modules/business-events/) on Production apps.
```

Or something like that?

But I wonder if we need to mention the available services here at all? Since services are enabled on a per company basis different people might have different lists. Perhaps we should scrap the subsections altogether and just have the information on enabling?

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Team members who have **Deploy, Publish, and Monitor** permission can see which services are enabled or disabled.
permission name?

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/maintenance-windows.md
> +Planned maintenance is a maintenance operation that will be (or has been) carried out. It is shown in local time, with the offset from Coordinated Universal Time noted. For example, if you are in a t
Nice that the example times match!

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/maintenance-windows.md
> +{{% alert color="info" %}}
I think this deserves a warning 🤔

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/maintenance-windows.md
> +    {{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/maintenance-windows/maintenance1.png" alt="Environments page" >}}
I don't believe we need alt text here. The image is [decorative](https://www.w3.org/WAI/tutorials/images/decorative/) in that it (and the alt text you are suggesting) doesn't tell you anything which isn't in the text above.
So, I think it like https://www.w3.org/WAI/tutorials/images/decorative/#example-3-image-with-adjacent-text-alternative

2023-10-06 09:57 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/maintenance-windows.md
> +    {{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/maintenance-windows/maintenance1.png" alt="Environments page" >}}
Although looking at the [standards](https://www.w3.org/TR/WCAG20-TECHS/H67) it seems it still needs to have a null alt attribute - which is actually what we say in our style guide (I'd better go back and do that 😀.

2023-10-06 10:50 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Access Restriction Profiles, including TLS Certificate Profiles and IP Filtering Profiles
I agree, this is a bit clunky. I made the change because all the other sub-bullets list the names of the sections within the tab, and that's the name of the section within the the Access Restriction Profiles tab. Looking at it again though, none of the sub-bullets seem to add particularly valuable information. Maybe it's better to just list tab names here, without any sub-bullets?

2023-10-06 10:51 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +For standard environments, your node has production and acceptance environments. Optionally, it can also include a test environment.
Completely agree on both points. I'll update.

2023-10-06 10:53 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/maintenance-windows.md
> +{{% alert color="info" %}}
Sure, I can revert this. What rationale do you use for determining info vs warning?

2023-10-06 10:56 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Runtime**, the Studio Pro version with which the app is built (for example, 7.6.0)
Makes sense. I've been wondering if it's okay to make changes in the dummy profile, so I'll make a note to bring this up when we talk this afternoon.

2023-10-06 11:00 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Mendix Event Broker** – required to use [Mendix Business Events](/appstore/modules/business-events/) on Production apps
Removing this section makes sense to me. Do I need to verify that with anyone on the Cloud team, or is that change fine to just make as a docs decision?

2023-10-06 11:03 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/maintenance-windows.md
> +    {{< figure src="/attachments/developerportal/deploy/mendix-cloud-deploy/maintenance-windows/maintenance1.png" alt="Environments page" >}}
Ah, interesting. Would you consider all three screenshots in this doc decorative?

2023-10-06 11:10 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Team members who have **Deploy, Publish, and Monitor** permission can see which services are enabled or disabled.
This is consistently capitalized (and sometimes italicized) in the docs, so I think it's the name, but I haven't managed to verify it in the product. Do you know where this permission is set?

2023-10-06 11:11 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +Team members who have **Deploy, Publish, and Monitor** permission can see which services are enabled or disabled.
Nvm—just saw your comment about this above.

2023-10-06 11:20 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +In the **Permissions** tab, the [Technical Contact](/developerportal/general/app-roles/#technical-contact) and other team members who have the **Manage Permissions** permission can manage various per
It must be something else—I can view the permissions without those two enabled. I wonder if this is still relevant? I haven't found it anywhere in the Developer Portal.
<img width="879" alt="image" src="https://github.com/mendix/docs/assets/142491015/27d933ca-cca6-48d6-ba7d-3c88ff0671fc">

2023-10-06 11:22 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-cloud-status.md
> +Mendix hosts a variety of services in the cloud. These include the environments for apps that are deployed to Mendix Cloud, as well as various online services (such as Buzz Project Management).
I didn't anything called Buzz Project Management. Maybe this can just be changed to "such as project management"?

2023-10-06 11:29 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +In the **Permissions** tab, the [Technical Contact](/developerportal/general/app-roles/#technical-contact) and other team members who have the **Manage Permissions** permission can manage various per
Looks like it's supposed to be part of the user role, but I'm not seeing it there either: <img width="922" alt="image" src="https://github.com/mendix/docs/assets/142491015/c666048b-e673-47c5-ba98-a9c63fa4e631">

2023-10-06 11:35 UTC, Adam-Dupaski commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-cloud-status.md
> +Mendix hosts a variety of services in the cloud. These include the environments for apps that are deployed to Mendix Cloud, as well as various online services (such as Buzz Project Management).
Buzz exists, "Project Management" is outdated and should be for "apps": https://docs.mendix.com/developerportal/general/buzz/#app-buzz

2023-10-06 12:04 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-cloud-status.md
> +Mendix hosts a variety of services in the cloud. These include the environments for apps that are deployed to Mendix Cloud, as well as various online services (such as Buzz Project Management).
Thanks!

2023-10-10 14:53 UTC, MarkvanMents reviewed
@dbreseman 
There is so much here that I have run out of time to review it.
Looks great.
I've made a few more comments. 
Come back to me if you have any questions or want to discuss anything I've mentioned. Otherwise, pick up what you think needs to be picked up and then merge.
If there is anything that needs more research, you can always make a Jira issue and return to it later.
The changes here are a great improvement. Thanks for all your hard work.
Mark

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-cloud-request-headers.md
> +There may be additional headers that are set by Mendix Cloud but not documented in the table above. Do not rely on the presence of these headers and their values. They are for internal use only and a
There is no deprecation handling below 😀
Perhaps you could look at _Blame_ for this doc and see whether you can find what was there and where it has gone (if it wasn't too long ago).

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-cloud-status.md
> +The status of all these services is reported on the [Mendix Platform Status](https://status.mendix.com/) page.
Being picky: perhaps
```suggestion
The status of each of these services is reported on the [Mendix Platform Status](https://status.mendix.com/) page.
```

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-ip-addresses.md
> +You can retrieve this IP address by performing a DNS lookup for this domain. For example, you could  go to http://ping.eu/nslookup/ (not 127.0.0.1).
Don't really understand the bit in brackets (not 127.0.0.1).
I think we could make it clearer that the URL is for a service which enables DNS lookup?

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +    * Access Restriction Profiles, including TLS Certificate Profiles and IP Filtering Profiles
Sounds good - try that.

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +In the **Permissions** tab, the [Technical Contact](/developerportal/general/app-roles/#technical-contact) and other team members who have the **Manage Permissions** permission can manage various per
Do you want to ask in #dep Slack channel, or do a bit more research. We could also have a quick meeting to do a bit more research together if that would help.

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/environments.md
> +* **Mendix Event Broker** – required to use [Mendix Business Events](/appstore/modules/business-events/) on Production apps
I'm now puzzled by the suggestion I made as there are suddenly two bullets - but I think they are the same bullet duplicated.

Best thing is to get together with Quinn and look into the Event Broker. I think this is something that Johanna introduced and is part of Integration. Let me know if you need more information.

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/mendix-ip-addresses.md
> +| ------ | -------- | ------------ | ----------- |
Although you can do this to make the Markup look a bit nicer, it doesn't really help (in my opinion) when the rest of the table is quite difficult to read in Markdown anyway.

The Markdown definition says that it only needs 3 hyphens.

But keep the change if it helps you!

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
> +In the *Permissions* section, you can manage access to your environments for each team member.
I wonder if **Permissions** should be bold, as it is a UX term which we will encounter in a moment.

Perhaps
> In the **Permissions** tab of the **Environments** page …

?

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
> +Team members who have permission to **Deploy, Publish, and Monitor** can view the permissions.
I wonder if the role **Cloud Access** used to be called **Deploy, Publish, and Monitor**? It might make sense - particularly given the description of the role.
![image](https://github.com/mendix/docs/assets/35492184/58f8ac4a-5197-4397-80cd-2d2d305eda24)

2023-10-10 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
> +The Technical Contact and team members specifically allowed to manage permissions can set the following node permissions: **Manage Permissions**, **Transport Rights**, **Access to Backups**, **Receiv
Great - accessibility.

2023-10-18 08:27 UTC, dbreseman commented on content/en/docs/developerportal/deploy/mendix-cloud-deploy/node-permissions.md
> +Team members who have permission to **Deploy, Publish, and Monitor** can view the permissions.
Confirmed! Thanks for the solve.

2023-10-18 13:09 UTC, merged