Updating history view to add changes info
mendix/docs pull request #6608
Opened 2023-10-05 12:59 UTC by blis-mendix

2023-10-10 12:36 UTC, MarkvanMents requested changes
@blis-mendix
Thanks for the PR and all the additional information about the history pane. I've put the 10.4 label on it so it is published with the release of 10.4.

Looks good in general, but I have a couple of questions/comments. Can you have a look and let me know your opinion.

Thanks

2023-10-10 12:36 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +A unique alphanumeric identifier of the revision in the repository. The revision identifier is unique for a whole repository.
Should we mention here that this is the Git commit id (hash)?

2023-10-10 12:36 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/Solution.png" width=32 alt="Solution version changes icon" >}} | Solution version changes| Indicates that th
Can we be a bit clearer what this means. Do you mean that the app now has a new version of a solution module? Perhaps we should point at the solutions module documentation https://docs.mendix.com/refguide/configure-add-on-and-solution-modules/.

Is this icon also shown if you add a new solution module, or delete an existing one?

2023-10-10 12:36 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesModel.png" width=32 alt="Model changes icon" >}} | Model changes | Indicates that there were some
Are you sure this is only the Domain Model. Or is it changes to the whole app model?

2023-10-10 12:36 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +The user-entered message saved with the commit. If the message is long, you can read it more easily in the Message tab page, below.
I wonder if we should be more neutral about the commit message. Might the message be generated automatically by a merge or when resolving conflicts?

Or perhaps by an API in the future?

2023-10-10 13:10 UTC, blis-mendix commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +The user-entered message saved with the commit. If the message is long, you can read it more easily in the Message tab page, below.
As we learned lately we have flows in which it is not only user created.

2023-10-10 13:13 UTC, blis-mendix commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesModel.png" width=32 alt="Model changes icon" >}} | Model changes | Indicates that there were some
Not 100%, @mikita-haurykau would probably knon.

2023-10-10 13:18 UTC, blis-mendix commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/Solution.png" width=32 alt="Solution version changes icon" >}} | Solution version changes| Indicates that th
It means that the add on solution was updated to new version,  so publisher created new solution version and user upgraded it in his application. Pointing to doc seems great idea to better explain users what it is about exactly. 

From what I see only upgrading the version has this icon, adding solution doesn't.

2023-10-10 13:19 UTC, blis-mendix commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +A unique alphanumeric identifier of the revision in the repository. The revision identifier is unique for a whole repository.
Honestly not sure, would user need this information?

2023-10-11 12:04 UTC, MarkvanMents reviewed
@blis-mendix
I've responded below. There are a couple of questions for @mikita-haurykau , so I'll ask him to review it as well so he can pick those up.
If you are happy with my suggestions, you can commit them yourself or indicate that you are happy and I can commit them.
Thanks for your work on this PR.
Mark

2023-10-11 12:04 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +A unique alphanumeric identifier of the revision in the repository. The revision identifier is unique for a whole repository.
It might help if they are trying to do something outside Studio Pro?
@mikita-haurykau - what do you think?

2023-10-11 12:04 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/Solution.png" width=32 alt="Solution version changes icon" >}} | Solution version changes| Indicates that th
How about:
```suggestion
| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/Solution.png" width=32 alt="Solution version changes icon" >}} | Solution version changes | Indicates that a [solution module](https://docs.mendix.com/refguide/configure-add-on-and-solution-modules/) used in the app was updated. |
```

2023-10-11 12:04 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +The user-entered message saved with the commit. If the message is long, you can read it more easily in the Message tab page, below.
So can we just remove the "user-entered" like this?
```suggestion
The message saved with the commit. If the message is long, you can read it more easily in the Message tab page, below.
```

2023-10-11 12:16 UTC, tknippenberg commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +The user-entered message saved with the commit. If the message is long, you can read it more easily in the Message tab page, below.
Yes, let's do that @MarkvanMents.

2023-10-11 12:17 UTC, tknippenberg commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +A unique alphanumeric identifier of the revision in the repository. The revision identifier is unique for a whole repository.
Yes, that's good to add @MarkvanMents.

2023-10-11 12:21 UTC, tknippenberg commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesModel.png" width=32 alt="Model changes icon" >}} | Model changes | Indicates that there were some
This is not limited to the Domain Model, but 'model changes' in general. 

In the "for example" section I'd suggest mentioning Domain Model, Microflows and Pages - as that gives a good idea what is part of the model.

2023-10-12 13:40 UTC, MarkvanMents reviewed
@tknippenberg 
Thanks for the responses. I've made changes to reflect your answers.
@blis-mendix 
I just have one outstanding suggestion for your review, then this will be ready for publication when Mx 10.4 is released.
Thanks

2023-10-12 13:40 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +A unique alphanumeric identifier of the revision in the repository. The revision identifier is unique for a whole repository.
Updated in dae3dda0e6eaf1e347ad4c1ee7d5cabdb40eba9c

2023-10-12 13:40 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/version-control-menu/history-dialog.md
> +| {{< figure src="/attachments/refguide/modeling/menus/version-control-menu/history-dialog/RevChangesModel.png" width=32 alt="Model changes icon" >}} | Model changes | Indicates that there were some
Updated in dae3dda0e6eaf1e347ad4c1ee7d5cabdb40eba9c

2023-10-30 14:59 UTC, MarkvanMents approved these changes
I've made my suggested change as it didn't change the sense of the document.
Approving ready for release tomorrow.

2023-10-31 10:54 UTC, merged