Proofreading sap1
mendix/docs pull request #6653
Opened 2023-10-16 11:57 UTC by Karuna-Mendix

2023-10-19 05:38 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +Configuring a REST call needs following tab entries:
Should I also provide the list of tabs here including hyperlinks to particular section?

2023-10-19 05:41 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +Below HTTP Headers do the following:
Should I also provide the list of tabs here including hyperlinks to particular section?

2023-10-26 14:53 UTC, MarkvanMents requested changes
Hi Karuna (@Karuna-Mendix )
This is a great improvement. I've made a couple of comments below. Let me know if you have any questions.
Thanks
Mark

2023-10-26 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +The [SAP Destination Service](/developerportal/deploy/sap-cloud-platform/sap-destination-service/) is a part of the [OData Connector for SAP solutions](https://docs.mendix.com/appstore/connectors/sap
I don't think you need "part of", I think you can just say "part of"?
```suggestion
The [SAP Destination Service](/developerportal/deploy/sap-cloud-platform/sap-destination-service/) is part of the [OData Connector for SAP solutions](https://docs.mendix.com/appstore/connectors/sap/sap-odata-connector/) and enables OData calls to be made using SAP destinations configured on SAP Business Technology Platform ([SAP BTP](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/)). However, you can also use the destination information provided by the [SAP Destination Service](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/sap-destination-service/) to make calls to non-OData services using Mendix native actions for consuming REST and SOAP.
```

2023-10-26 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +* Configured a **PrincipalPropagation** destination to an on-premise REST or SOAP service in your SAP BTP account; For more information, see [SAP Destination Service](/developerportal/deploy/sap-clou
I know this isn't one of your changes but our product naming guide (other Mendix terms) prefers "on-premises" to "on-premise"

2023-10-26 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +**Get Destination** action returns a **Destination** object. This is named as *DestinationObject* in the above example, and is used to configure the subsequent REST or SOAP call.
```suggestion
The **Get Destination** action returns a **Destination** object. This is named as *DestinationObject* in the above example, and is used to configure the subsequent REST or SOAP call.
```

2023-10-26 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +Configuring a REST call needs following tab entries:
You could, but since there are only two sections and they fit on one page it probably isn't necessary. But no harm in adding them.

2023-10-26 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +Below HTTP Headers do the following:
No - this is just specifying what needs to be added as custom headers to the REST call.

Good to remove one of the "following"s in this sentence, however I think "The" is better than "Below" in this case.
```suggestion
The HTTP Headers do the following:
```

2023-10-26 14:53 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +* Request to return the data in JSON format
Since there is a one-to-one relation to the table rows below, you could put these explanations as a third column in the table if you wanted. But they are also OK where they are.

2023-10-27 11:07 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +Configuring a REST call needs following tab entries:
That make sense. List should contain at least 3+ points.

2023-10-30 12:45 UTC, Karuna-Mendix commented
Closed accidently.

2023-10-30 13:14 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +Below HTTP Headers do the following:
Done https://github.com/mendix/docs/pull/6653/commits/c7096d922ea049ff7ffcce87b3c9f6aa8919b59d

2023-10-30 13:14 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +The [SAP Destination Service](/developerportal/deploy/sap-cloud-platform/sap-destination-service/) is a part of the [OData Connector for SAP solutions](https://docs.mendix.com/appstore/connectors/sap
done https://github.com/mendix/docs/pull/6653/commits/c7096d922ea049ff7ffcce87b3c9f6aa8919b59d

2023-10-30 13:15 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +**Get Destination** action returns a **Destination** object. This is named as *DestinationObject* in the above example, and is used to configure the subsequent REST or SOAP call.
Done https://github.com/mendix/docs/pull/6653/commits/c7096d922ea049ff7ffcce87b3c9f6aa8919b59d

2023-10-30 13:15 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +* Request to return the data in JSON format
Kept as it is.

2023-10-30 13:15 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-destination-with-rest.md
> +* Configured a **PrincipalPropagation** destination to an on-premise REST or SOAP service in your SAP BTP account; For more information, see [SAP Destination Service](/developerportal/deploy/sap-clou
done https://github.com/mendix/docs/pull/6653/commits/c7096d922ea049ff7ffcce87b3c9f6aa8919b59d

2023-10-30 15:19 UTC, MarkvanMents approved these changes
Thanks for making those changes. Looks great.
Can be merged whenever you want.

2023-11-01 12:13 UTC, Karuna-Mendix commented
Corrected changes for SAP Destination Service

2023-11-01 12:13 UTC, merged