Proofreading SAP2
mendix/docs pull request #6673
Opened 2023-10-20 05:22 UTC by Karuna-Mendix

2023-10-25 12:14 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +The application autoscaler service for [SAP Business Technology Platform (SAP BTP)](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/) enables applications to automatically increase
Verified with developer that this is not an UI text.

2023-10-26 14:33 UTC, MarkvanMents requested changes
Hi Karuna (@Karuna-Mendix),
Lots of good changes here.
I've made a couple of comments, can you look at them and let me know if you have any questions about what I've said.

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +The application autoscaler service for [SAP Business Technology Platform (SAP BTP)](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/) enables applications to automatically increase
Great to remove the bold.
I'm not sure that it is the _service_ which is based on the schedule - it is the automatic change of resources that is based on the schedule.
Perhaps
```suggestion
The application autoscaler service for [SAP Business Technology Platform (SAP BTP)](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/) enables applications to automatically increase or decrease the number of instances of your app. These changes can be based on a schedule, or based on the value of a metric.
```

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +Selecting the **autoscaler** service, expands the entry to allow you to enter more details about the service you wish to bind, namely the **Plan** and the **File** which contains the configuration.
Don't think we need a comma before "expands", it is not an introductory phrase.

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* **File** – the file which contains the JSON to configure the autoscaler — more information, including the contents of the configuration file can be found in [Application Autoscaler Service](https:/
This new link does not contain any information about the JSON file. Can you check with the development team if this is a better suggestion?
https://help.sap.com/docs/application-autoscaler/application-autoscaler/defining-scaling-policy

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Memory consumed - monitors memory consumption in megabytes (memoryconsumed) or in percentage (memoryutil)
These hyphens should be n-dashes `–` not hyphens `-`
```suggestion
* Memory consumed – monitors memory consumption in megabytes (memoryconsumed) or in percentage (memoryutil)
```

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Schedule-based scaling – scaling based on a schedule, see [Scheduled Scaling](#schedule) section below
You need a 'the' here. You can see "Scheduled Scaling", but you see "the Scheduled Scaling section"
```suggestion
* Schedule-based scaling – scaling based on a schedule, see the [Scheduled Scaling](#schedule) section below
```

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Dynamic scaling – scaling based on the values of metrics, see [Dynamic Scaling](#dynamic)section below
```suggestion
* Dynamic scaling – scaling based on the values of metrics, see [Dynamic Scaling](#dynamic) section below
```

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Click **Download Configuration File** to create a file containing the correct JSON for your autoscaler configuration; you can then upload this file as a configuration of your autoscaler service.
I think this is still **the** configuration. Although you can create multiple configurations, I think you can only upload one configuration to the service.
```suggestion
* Click **Download Configuration File** to create a file containing the correct JSON for your autoscaler configuration; you can then upload this file as the configuration of your autoscaler service.
```

2023-10-26 14:33 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +Do not attempt to enter overlapping schedules, as it causes the scaling to fail.
I don't think this comma is needed.

2023-10-31 11:05 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +The application autoscaler service for [SAP Business Technology Platform (SAP BTP)](https://docs.mendix.com/developerportal/deploy/sap-cloud-platform/) enables applications to automatically increase
I agree. Corrected in https://github.com/mendix/docs/pull/6673/commits/be785809847f6b0b1d0a54e88bccaceb697d2a72

2023-10-31 11:05 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +Selecting the **autoscaler** service, expands the entry to allow you to enter more details about the service you wish to bind, namely the **Plan** and the **File** which contains the configuration.
done https://github.com/mendix/docs/pull/6673/commits/be785809847f6b0b1d0a54e88bccaceb697d2a72

2023-10-31 11:05 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Memory consumed - monitors memory consumption in megabytes (memoryconsumed) or in percentage (memoryutil)
done https://github.com/mendix/docs/pull/6673/commits/be785809847f6b0b1d0a54e88bccaceb697d2a72

2023-10-31 11:06 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Dynamic scaling – scaling based on the values of metrics, see [Dynamic Scaling](#dynamic)section below
done https://github.com/mendix/docs/pull/6673/commits/be785809847f6b0b1d0a54e88bccaceb697d2a72

2023-10-31 11:06 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* Click **Download Configuration File** to create a file containing the correct JSON for your autoscaler configuration; you can then upload this file as a configuration of your autoscaler service.
done https://github.com/mendix/docs/pull/6673/commits/be785809847f6b0b1d0a54e88bccaceb697d2a72

2023-11-01 12:47 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-autoscaler.md
> +* **File** – the file which contains the JSON to configure the autoscaler — more information, including the contents of the configuration file can be found in [Application Autoscaler Service](https:/
Verified this link with developer and corrected. https://github.com/mendix/docs/pull/6673/commits/61678ca354771c2dc2d3f72944b74c1494af416b

2023-11-03 10:54 UTC, MarkvanMents approved these changes
@Karuna-Mendix 
This looks great. Approving.
Feel free to merge whenever you want.

2023-11-03 10:58 UTC, merged