DRAFT: Upgraded information about BYOK
mendix/docs pull request #6699
Opened 2023-10-25 09:10 UTC by stefanus-heath

* Removing whitespace
* Adding information about BYOK

2023-10-26 08:16 UTC, abhishekamte-mx requested changes

2023-10-26 08:16 UTC, abhishekamte-mx commented on content/en/docs/appstore/modules/business-events.md
> +As operating Own Kafka Cluster is outside of the scope of the Mendix Cloud environment, the following `DevOps` tasks should be taken into consideration (this list is not an extensive list of items):
`Own` need not be captialized. Maybe reword the sentence a bit 
`As operating your own Kafka Cluster is outside of the scope of the Mendix Cloud environment, the following `DevOps` tasks should be taken into consideration (this list is not extensive):`

2023-10-26 08:16 UTC, abhishekamte-mx commented on content/en/docs/appstore/modules/business-events.md
> +* Topic creation on Kafka - Unless the Kafka cluster is configured with `auto.create.topics.enable` set to true, topics will need to be created by the customer.
maybe add a link to the topic creation logic subsection

2023-10-26 08:16 UTC, abhishekamte-mx commented on content/en/docs/appstore/modules/business-events.md
> +* Access Control - Unless the Kafka cluster is configured with `allow.everyone.if.no.acl.found` set to true, the ACLs need to be maintained by the customer
maybe add a word as default `set to true (default setting in Apache Kafka)`

2023-10-26 08:16 UTC, abhishekamte-mx commented on content/en/docs/appstore/modules/business-events.md
> +    No, that is currently not supported when using Mendix Cloud Event Broker.  This can be achieved by using Own Kafka Cluster.
rather say BYOK and link to it

2023-10-26 08:16 UTC, abhishekamte-mx commented on content/en/docs/appstore/modules/business-events.md
> +| Publish events and<br>Subscribe to events | [Nothing required: if apps can do both, there is no obligation for the service to implement anything] | Publishing events and/or subscribing to events |
@stefanus-heath  i cant see to see the topic resolution documentation, where is it?

2023-10-27 09:59 UTC, stefanus-heath commented on content/en/docs/appstore/modules/business-events.md
> +| Publish events and<br>Subscribe to events | [Nothing required: if apps can do both, there is no obligation for the service to implement anything] | Publishing events and/or subscribing to events |
ah, I see the circular reference to nothingness ... will fix

2023-10-31 07:46 UTC, Adam-Dupaski commented
@quinntracy please approve this PR if it's ready. Also, there are conflicts that need to be resolved.

2023-10-31 10:06 UTC, quinntracy approved these changes

2023-10-31 10:56 UTC, merged