saml changes
mendix/docs pull request #6700
Opened 2023-10-25 10:16 UTC by Karuna-Mendix

2023-10-26 09:55 UTC, JaapF commented on content/en/docs/appstore/modules/saml.md
I would suggest inserting that new line of text here.
"The version of the SAML module below 3.5.0 is limited to single keypair: ..."
The "If you want [...] more details)." sentences explain that limitation in older versions in more detail.

2023-10-26 10:11 UTC, Karuna-Mendix commented on content/en/docs/appstore/modules/saml.md
Done https://github.com/mendix/docs/pull/6700/commits/8d7d61b8e6f639bba1da4a82d1b1da21b1f5ba74

2023-10-26 10:50 UTC, JaapF commented on content/en/docs/appstore/modules/saml.md
>  If you want to connect your app to multiple SAML IdPs, you cannot use different key pairs and certificates for each of the SSO federations. Instead, you must use a single key pair and certificate for
If you're using one of those older versions and you want to connect ....

2023-10-26 15:01 UTC, MarkvanMents requested changes
Looking good. We just need to be prepared for multiple versions of the module. The versioning of this module in particular is very complicated as there are different versions of the module for different Mendix versions, which is why the version information is complicated to add.

Let me know if you have any questions.

2023-10-26 15:01 UTC, MarkvanMents commented on content/en/docs/appstore/modules/saml.md
> +The version of the SAML module below 3.5.0 is limited to single keypair.
I think there are several versions below 3.5.0?
```suggestion
Versions of the SAML module below 3.5.0 are limited to single keypair.
```

2023-10-26 15:01 UTC, MarkvanMents commented on content/en/docs/appstore/modules/saml.md
> +The version of the SAML module 3.5.0 and above compatible with Mendix (v9.22.0 and above) supports multiple keypair.
I think there will be more versions, so I think we need to say:
```suggestion
SAML module versions 3.5.0 and above (compatible with Mendix version 9.22.0 and above) support multiple keypairs.
```

2023-10-27 09:51 UTC, Karuna-Mendix commented on content/en/docs/appstore/modules/saml.md
> +The version of the SAML module 3.5.0 and above compatible with Mendix (v9.22.0 and above) supports multiple keypair.
I agree with the change

2023-10-27 10:22 UTC, Karuna-Mendix commented on content/en/docs/appstore/modules/saml.md
>  If you want to connect your app to multiple SAML IdPs, you cannot use different key pairs and certificates for each of the SSO federations. Instead, you must use a single key pair and certificate for
Done https://github.com/mendix/docs/pull/6700/commits/d471f799f12f42326c32be29efbaae2ed96a7eb4

2023-10-27 10:22 UTC, Karuna-Mendix commented on content/en/docs/appstore/modules/saml.md
> +The version of the SAML module 3.5.0 and above compatible with Mendix (v9.22.0 and above) supports multiple keypair.
Done https://github.com/mendix/docs/pull/6700/commits/d471f799f12f42326c32be29efbaae2ed96a7eb4

2023-10-31 14:26 UTC, MarkvanMents requested changes
@Karuna-Mendix - let me know if you want to discuss this, or pick it up with Jaap if you understand what I'm trying to say.

2023-10-31 14:26 UTC, MarkvanMents commented on content/en/docs/appstore/modules/saml.md
I think that this should just be in the list of what is not supported (before the bit about DigID)? It doesn't need to be an alert as this section is already listing limitations.
In fact, I think that it is related to the paragraph which is already here about the SAML EntityID (highlighted in the attached image) which is, I think, a technical description of what happens in versions below 3.5.0, rather than a customer-friendly description.

Can you discuss with @JaapF ? Thanks.
![image](https://github.com/mendix/docs/assets/35492184/36be06a7-2f57-48f1-a97a-e7fbb05a4091)

2023-11-06 10:09 UTC, Karuna-Mendix commented on content/en/docs/appstore/modules/saml.md
The highlighted paragraph is about all versions of SAML module and not only for versions below 3.5.0. It is not completely related to versions 3.5.0 and below (the info in the alert box). Alert info doesn't go with the bulleted list as well as that list is about what is not supported for all versions. I removed the info alert and added the sentence in the paragraph where it talks about older version of the module and its related behavior.

2023-11-06 10:21 UTC, MarkvanMents approved these changes
Looks good. Thanks for resolving my question.
OK to go if Jaap is happy.

2023-11-06 10:56 UTC, merged