Document url prefix config
mendix/docs pull request #6702
Opened 2023-10-25 11:47 UTC by EnasAbdelrazek

2023-10-25 12:08 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +
'Otherwise' needs to be capitalised. I think the entire sentence 'otherwise you will get a consistency error' can be left out as we already state that you cannot use those values.

2023-10-25 12:11 UTC, brambrink requested changes
Some small points, looks good!

2023-10-25 12:11 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +Here you have the option to change the default URL prefix for all pages and microflows in your application. The defauilt prefix value is `/p/`.
`defauilt` => `default`

2023-10-25 12:11 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +
'Otherwise' needs to be capitalised. I think the entire sentence 'otherwise you will get a consistency error' can be left out as we already state that you cannot use those values.

2023-10-25 12:11 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +The URL prefix must be alphanumeric and can not be empty, whitespace, or be any of the following values: "ws", "ws-doc", "rest-doc", "odata", "odata-doc", "api-doc", "xas", "reload". otherwise you wi
I would use 'cannot' instead of 'can not' here. Although both are grammatically correct the former is more often used in formal language (https://www.merriam-webster.com/grammar/cannot-vs-can-not-is-there-a-difference)

2023-10-25 12:13 UTC, Robinfr commented
Should be merged for Mx10.5

2023-10-25 13:44 UTC, brambrink approved these changes

2023-11-22 14:31 UTC, ConnorLand commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +
I've edited it, but left in the error sentence. Readers appreciate the bluntness.

2023-11-22 14:33 UTC, ConnorLand commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +* "ws"
Question @EnasAbdelrazek : if the user makes a prefix that CONTAINS one of the values, is that also a violation?

Example: is "aws-doc" ok, or is that not permissible because it contains "ws-doc" inside it?

2023-11-22 14:43 UTC, Robinfr commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +* "ws"
@ConnorLand Good question, I checked, and it's specifically the values mentioned below. So `aws-doc` is OK 👍

2023-11-22 14:44 UTC, ConnorLand commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +* "ws"
Ok sweet, thanks Robin.

2023-11-22 14:46 UTC, ConnorLand approved these changes

2023-11-22 14:47 UTC, ConnorLand commented
LGTM except for one question: the screengrab has "prefix" in the field. Does it normally come empty, or with just a "p" character in it? I want to ensure the screengrab matches the default that we talk about in the text.

2023-11-28 13:15 UTC, merged