Proofreading- SAP SSO
mendix/docs pull request #6721
Opened 2023-10-30 05:55 UTC by Karuna-Mendix

2023-10-30 07:43 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +Mendix has single sign-on for SAP users (for some SAP regions). This means that you are authenticated to Mendix using SAP credentials.
assuming single sign-on as generic term

2023-10-30 07:43 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +## 2 Signing in to Mendix Using SSO
replacing logging in with signing in as per style guide

2023-10-30 07:44 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +{{< figure src="/attachments/developerportal/deploy/sap-single-sign-on/sign-in.png" >}}
I think, this image is more relevant for section 2.1

2023-10-30 07:46 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +Click **SAP** to use your SAP credentials. These credentials are region-specific, so you need to choose a region first.
Avoiding repetitive use of 'you' and 'select'. UI also indicates the 'choose' word instead of select.

2023-10-30 07:48 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +Click **Select region** and you will be asked for your SAP credentials.
Bold for UI element. SAP credentials is not a part of UI

2023-10-30 07:49 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +When you create an SAP app or a new SAP Business Technology Platform (SAP BTP) environment, you may be asked to sign in to SAP. For more information, see [Create a New Environment](/developerportal/d
trying to provide more cross reference. Not sure if it is really required here or not.

2023-10-30 07:52 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +This error occures when you work with SAP environments from within the Mendix Developer Portal. As described on the error page, it occurs when you use different usernames for signing in to Mendix pla
I found original sentences complex so, trying to make it simple.

2023-10-30 07:54 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +To resolve this problem, you must sign out of the SAP region so that you can then enter the correct credentials. The sign out page is based on the region you are using and has the format `https://log
Sentence was incomplete due to space.

2023-10-30 07:55 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +You cannot solve this problem by changing your email address on Mendix. This does not change your Mendix username.
No need to use bold to emphasis.

2023-10-30 17:37 UTC, MarkvanMents requested changes
Great improvement.
Could you look at the couple of comments below about the image and the link. And commit my suggestions if they look good to you.
Thanks.

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +Mendix has single sign-on for SAP users (for some SAP regions). This means that you are authenticated to Mendix using SAP credentials.
Yes. Well spotted.

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +## 2 Signing in to Mendix Using SSO
Great.

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +{{< figure src="/attachments/developerportal/deploy/sap-single-sign-on/sign-in.png" >}}
Looking at the image, I think it is pointing out where to choose signing in with SAP (that option has been put in a red box). The text in the Username and Password fields is just a placeholder. So I think this could go back to section 2?
![sign-in](https://github.com/mendix/docs/assets/35492184/533a12f4-78d5-4d9d-8d61-d8d297c3dddb)

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +Click **SAP** to use your SAP credentials. These credentials are region-specific, so you need to choose a region first.
Good change.

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +Click **Select region** and you will be asked for your SAP credentials.
Yes.

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +When you create an SAP app or a new SAP Business Technology Platform (SAP BTP) environment, you may be asked to sign in to SAP. For more information, see [Create a New Environment](/developerportal/d
The idea is good but it needs an article. Our [style guide has an example which you can use for the formatting](https://mendix.atlassian.net/wiki/spaces/RNDHB/pages/2520678744/Grammar+Formatting#Section). It's also missing a period.

But the main problem is that there is no #create anchor and you need to put that into /developerportal/deploy/sap-btp/_index.md using the `{#create}` format on a heading line.

```suggestion
When you create an SAP app or a new SAP Business Technology Platform (SAP BTP) environment, you may be asked to sign in to SAP. For more information, see the [Create a New Environment](/developerportal/deploy/sap-cloud-platform/#create) section in *SAP BTP*.
```

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +This error occures when you work with SAP environments from within the Mendix Developer Portal. As described on the error page, it occurs when you use different usernames for signing in to Mendix pla
Much clearer. I spotted a typo:
```suggestion
This error occurs when you work with SAP environments from within the Mendix Developer Portal. As described on the error page, it occurs when you use different usernames for signing in to Mendix platform and SAP region which you are working on.
```

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +To resolve this problem, you must sign out of the SAP region so that you can then enter the correct credentials. The sign out page is based on the region you are using and has the format `https://log
Great.

2023-10-30 17:37 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +You cannot solve this problem by changing your email address on Mendix. This does not change your Mendix username.
Agreed.

2023-10-31 12:17 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +{{< figure src="/attachments/developerportal/deploy/sap-single-sign-on/sign-in.png" >}}
Okay, got it now.

2023-10-31 12:24 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +{{< figure src="/attachments/developerportal/deploy/sap-single-sign-on/sign-in.png" >}}
https://github.com/mendix/docs/pull/6721/commits/46e0420989cea3ec28dbd05247d6944485a33883

2023-10-31 12:24 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +When you create an SAP app or a new SAP Business Technology Platform (SAP BTP) environment, you may be asked to sign in to SAP. For more information, see [Create a New Environment](/developerportal/d
Corrected in https://github.com/mendix/docs/pull/6721/commits/46e0420989cea3ec28dbd05247d6944485a33883

2023-10-31 12:24 UTC, Karuna-Mendix commented on content/en/docs/developerportal/deploy/sap-btp/sap-single-sign-on.md
> +This error occures when you work with SAP environments from within the Mendix Developer Portal. As described on the error page, it occurs when you use different usernames for signing in to Mendix pla
corrected https://github.com/mendix/docs/pull/6721/commits/46e0420989cea3ec28dbd05247d6944485a33883

2023-10-31 15:44 UTC, MarkvanMents approved these changes
Great improvements @Karuna-Mendix 
Feel free to merge this PR.

2023-11-01 12:02 UTC, Karuna-Mendix commented
Proofreading changes updated for -SAP SSO

2023-11-01 12:02 UTC, merged