Qt data hub removal
mendix/docs pull request #6733
Opened 2023-10-30 15:15 UTC by quinntracy

2023-10-31 08:21 UTC, MarkvanMents requested changes
@quinntracy 
Looks good. I just have a couple of things which I think we should check, but most of the changes are good to go.

2023-10-31 08:21 UTC, MarkvanMents commented on content/en/docs/quickstarts/part1.md
> +For additional information on right default panes, see the [Integration](/refguide/view-menu/#data-hub) and [Connector](/refguide/view-menu/#connector) sections of *View Menu*.
I wonder if we need to specify Mendix 10 for the Quickstarts. 
Alternatively, we might need to indicate the different UXes for Mx9 and Mx10.
Can you talk to @ConnorLand and see what his preference is?

2023-10-31 08:21 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/associations/association-properties.md
> +One-way navigable associations are associations that allow navigation to associated entities only in a single direction: from parent to child. These associations are typically introduced by OData ser
I think we should remove the subclause about external provider and data hub. And just talk about external entities (in the interests of making it more generic). But perhaps we need to check this with someone (Maurits or Joost?). Might as well make it more generic by removing OData as well. So perhaps:
```suggestion
One-way navigable associations are associations that allow navigation to associated entities only in a single direction: from parent to child. These associations are typically introduced by integration using [external entities](/refguide/external-entities/#associations). The major implications of one-way navigability are related to XPath use cases such as constraints and queries.
```

2023-10-31 08:21 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/view-menu/integration-pane.md
> +You can search in the Catalog through the [Integration Pane](/refguide/integration-pane/) to discover data sources that you can use in your app. Via this pane you can add the entities that are expose
FYI: This will be one of the changes we get to when we make integration more generic; we will be removing "OData services" in this paragraph.

Just for future consideration: that obviously isn't the aim of this PR.

2023-10-31 08:33 UTC, ConnorLand commented on content/en/docs/quickstarts/part1.md
> +For additional information on right default panes, see the [Integration](/refguide/view-menu/#data-hub) and [Connector](/refguide/view-menu/#connector) sections of *View Menu*.
Interesting point. The quickstarts do technically live outside versioned spaces. I think specifying "Mendix 10" and then using whatever Mendix 10 term is correct (data hub/integration) would be the best choice. 

This reminds me, I should go through the quickstarts and see if any screenshots need updating to Mx10.

2023-10-31 08:46 UTC, Adam-Dupaski commented on content/en/docs/quickstarts/part1.md
> +For additional information on right default panes, see the [Integration](/refguide/view-menu/#data-hub) and [Connector](/refguide/view-menu/#connector) sections of *View Menu*.
@ConnorLand 

Would be good to specify SP 10 - always latest major version.

Screenshot in section 3 displays 9.12.1 - this can be updated or removed.

Part 2 Quickstart specifies Make It Native 9.

2023-10-31 09:00 UTC, ConnorLand commented on content/en/docs/quickstarts/part1.md
> +For additional information on right default panes, see the [Integration](/refguide/view-menu/#data-hub) and [Connector](/refguide/view-menu/#connector) sections of *View Menu*.
Thanks Adam. I'll alter that screenshot, and I will update mentions of MIN9 in Part 2 to MIN 10.

2023-10-31 10:08 UTC, quinntracy commented on content/en/docs/refguide/modeling/menus/view-menu/integration-pane.md
> +You can search in the Catalog through the [Integration Pane](/refguide/integration-pane/) to discover data sources that you can use in your app. Via this pane you can add the entities that are expose
I saw that too, but wanted to do it in a separate PR. I'll tackle that next

2023-10-31 14:38 UTC, MarkvanMents approved these changes
Looks good to me now. I'll approve from my side, assuming you'll continue to work with Connor on resolving anything that needs to be changed for the Quick Start guide.
Thanks for this. Great to have Data Hub changed everywhere.

2023-10-31 14:40 UTC, quinntracy commented
I spoke with @ConnorLand and he said the wording is fine for the QuickStarts, so we should be good to go.

2023-11-02 10:52 UTC, ConnorLand commented on content/en/docs/quickstarts/part1.md
> +For additional information on right default panes, see the [Integration](/refguide/view-menu/#data-hub) and [Connector](/refguide/view-menu/#connector) sections of *View Menu*.
Done.

2023-11-03 16:35 UTC, closed without merging