Draft: Add explanation for setLabel attribute in pluggable widgets API (10.5)
mendix/docs pull request #6787
Opened 2023-11-09 13:16 UTC by alihcsumer

IMPORTANT: This PR is currently in the process of internal review by WTF team.

The PR includes:

New Feature: WTF-1671

2023-11-09 13:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=6787) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=6787) before we can accept your contribution.<br/><hr/>**Ali Haydar Sümer** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=6787) it.</sub>

2023-11-14 16:11 UTC, tamelbrun requested changes

2023-11-14 16:11 UTC, tamelbrun commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `setLabel`          | No       | Boolean        | `true` to enable setting [`Label`](#setLabel) value automatically with configured attribute, false `otherwise`                   |
This should be `entity` instead of `attribute`.

2023-11-16 13:00 UTC, ConnorLand approved these changes

2023-11-16 13:00 UTC, ConnorLand commented
@alihcsumer looks good, I'll make sure it has a RN in 10.5 and merge when that release occurs.

2023-11-28 13:40 UTC, merged