Rebase Introduction
mendix/docs pull request #6800
Opened 2023-11-13 07:26 UTC by blis-mendix

Introduction of Rebase flow

2023-11-13 10:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=6800) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=6800) before we can accept your contribution.<br/><hr/>**Tom Knippenberg** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=6800) it.</sub>

2023-11-23 15:22 UTC, MarkvanMents requested changes
Hi @blis-mendix and @tknippenberg
You can see all my changes in this pair of commits: https://github.com/mendix/docs/pull/6800/files/07c1c8a309687b2402770c032f2086c8f903e073..c2057506744e84cae103740d746c5ecd6e4144f2

I have a couple of questions, particularly about the way you resolve the second commit conflict which I don't understand at all.
Can you have a look and let me know what you think.

2023-11-23 15:22 UTC, MarkvanMents commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_End_state.png
This image looks completely different from what actually happened as shown in [Merge_Steps_4.png](https://github.com/mendix/docs/blob/c2057506744e84cae103740d746c5ecd6e4144f2/static/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_Step_4.png) where 2 and 4 are merged into the branch using 6! This looks like 3 and 5 are merged into the branch

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +    {{< figure src="/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_End_state.png" alt="Commits #1, #2, #4, and #6, with commit #6 including co
This looks reversed from what is shown when you are actually doing the merge.

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +Because the `Second_E_mail` attribute was removed on the server, while renaming it in your local work, there is another conflict. In this example we resolve this by adding another attribute ‘Login’,
I don't understand how adding another attribute resolves anything in this conflict.

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +Above you can see that your new change is represented as 'Mine', together with changes that were taken from the server.
I don't understand how this resolves a conflict between deleting an attribute and renaming it to `Second_Email`.

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +There are two entities `User` and `Game` which you have added to the domain model of your project.
Not sure what the benefit is to such a complex domain model. It could be explained with a single entity since we never refer to the `Game` entity or the association.

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
Can't see this in Release Candidate 4. Need to review in RC7 and check the text matches the UX and bold where necessary.

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +When the combined state is tested, a 'merge commit' can be created for the new version of the app. This is a new commit (`#6`) which will always show that it merged commits `#4` and `#5`.
I don't find it clear at what stage the new merge commit is created. Does this happen manually when you create a commit from the version control menu?
I think this is worth noting as a difference from rebase where the updated commits (`#3'` etc) are created during the conflict resolution process.

2023-11-23 15:22 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
I've moved all this to the Conflict resolution document to avoid duplication.

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
Makes sense

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +There are two entities `User` and `Game` which you have added to the domain model of your project.
Yeah you are right we never use game but I have felt that single entity look very poorly, and I do not think that this is such complex one.

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +    {{< figure src="/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_End_state.png" alt="Commits #1, #2, #4, and #6, with commit #6 including co
I don't understand why does it seem reversed? I checked the images and it seems they are in good order.

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
Yeah we were late :(

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +Above you can see that your new change is represented as 'Mine', together with changes that were taken from the server.
Hmmm my bad I overlooked it, it's not. Resolving this conflicts doesn't matter that much in here now we want to show that changes done in this moment are either mine/or theirs depending on merge/rebase. That's the very important point. So maybe something like: "After resolving the second conflict, you decided to add new attribute 'Login'"

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +Because the `Second_E_mail` attribute was removed on the server, while renaming it in your local work, there is another conflict. In this example we resolve this by adding another attribute ‘Login’,
as above

2023-11-23 16:02 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +When the combined state is tested, a 'merge commit' can be created for the new version of the app. This is a new commit (`#6`) which will always show that it merged commits `#4` and `#5`.
User must create new commit during this stage before push, we thought that it is clear by first sentence :/ "When the combined state is tested, a 'merge commit' can be created for the new version of the app"

2023-11-23 21:04 UTC, tknippenberg commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
Agreed. Does the name of the /merge/algorithm/ document still make sense, or should that be renamed?
It's also referred to from Studio Pro if I'm not mistaken, so if we rename it a redirect is needed.

2023-11-24 07:42 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
Updated in 45fc7475c6592023bb0b178242cfa43335cb273f - please review text.

2023-11-24 07:42 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
It is only the URL, but perhaps it would be a good idea to rename it. I don't have strong feelings either way. It still covers merging, but isn't so much about a specific algorithm.
Do you have a good suggestion for the URL?

2023-11-24 07:59 UTC, MarkvanMents reviewed
Resolved the issues.
Please check my latest changes and let me know what you want to do about the URL of the page.

2023-11-24 07:59 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +There are two entities `User` and `Game` which you have added to the domain model of your project.
OK, lets leave it for now.

2023-11-24 07:59 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +Above you can see that your new change is represented as 'Mine', together with changes that were taken from the server.
Updated.

2023-11-24 07:59 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +When the combined state is tested, a 'merge commit' can be created for the new version of the app. This is a new commit (`#6`) which will always show that it merged commits `#4` and `#5`.
OK, I'll make a slight adjustment to the text since I obviously missed something.

2023-11-24 07:59 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +    {{< figure src="/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_End_state.png" alt="Commits #1, #2, #4, and #6, with commit #6 including co
@blis-mendix: You are right. I misread the image, don't know what I was thinking. Sorry.

2023-11-24 08:24 UTC, tknippenberg commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
Something about 'conflict resolution and combining changes'..?

2023-11-24 08:25 UTC, blis-mendix commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_End_state.png
I don't get it in MergeStep3 we show that 6 is created by 5 and 4 and Step4  shows represents that it is pushed to the server

2023-11-24 08:25 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
Let's leave url for now at least as this would require a change in the code also and as we are in "freeze" I would love to avoid adding to it. @tknippenberg, @MarkvanMents  would this work for you to leave it as is?

2023-11-24 08:25 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +When the combined state is tested, a 'merge commit' can be created for the new version of the app. This is a new commit (`#6`) which will always show that it merged commits `#4` and `#5`.
That's why I like this process, we write something from our perspective and it is easy to miss the obvious or phrase it wrongly so it's nice you read it ;)

2023-11-24 08:25 UTC, blis-mendix commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/merge-algorithm.md
> +    {{< figure src="/attachments/refguide/version-control/using-version-control-in-studio-pro/combining_changes/Steps/Merge_End_state.png" alt="Commits #1, #2, #4, and #6, with commit #6 including co
Np, I was scared there for a second :D

2023-11-24 08:34 UTC, tknippenberg commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +See [Combining Changes and Conflict Resolution](/refguide/merge-algorithm/) for more information.
If there's a redirect I don't see how the freeze affects anything @blis-mendix. Older versions of Mendix would also still point to the old-url, so it needs to be taken care of anyway.

I'm also fine with keeping the url as-is, it's not that important. I'll leave it up to @MarkvanMents to decide.

2023-11-27 16:13 UTC, MarkvanMents approved these changes
Good to be published. Further changes will be made after the 10.5 release.

2023-11-28 13:01 UTC, merged