MG Reviews update
mendix/docs pull request #6919
Opened 2023-12-06 08:26 UTC by Adam-Dupaski

2024-03-05 14:43 UTC, MarkvanMents requested changes
I've made a couple of comments, but I really need access to see the changes to check that nothing has been missed. I hope to get that access today or tomorrow.

Please can you answer the two questions I have below?

Thanks

2024-03-05 14:43 UTC, MarkvanMents commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have created a new Write Review Screen with User Tips. This feature is available both in the Web and InIDE versions of the Marketplace. Now, when writing a review, users will have access to usef
Is this really a new screen, or is it an added feature to the existing screen.
In either case, does it need some documentation somewhere?

2024-03-05 14:43 UTC, MarkvanMents commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have added a new Reply to Review Screen with Supplier Tips. This improves communication between suppliers and reviewers.
Is this really a new screen, or is it an added feature to the existing screen.
In either case, does it need some documentation somewhere?

2024-03-05 15:25 UTC, JJdegroot1993 commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have created a new Write Review Screen with User Tips. This feature is available both in the Web and InIDE versions of the Marketplace. Now, when writing a review, users will have access to usef
I would say the features are the same but we made some adjustments. First it was a popup, now it is embedded in a page. The layout is different and we added the user tips, which is new. The user tips give some helpful information to the user how to write a review.

2024-03-05 15:27 UTC, MarkvanMents commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have created a new Write Review Screen with User Tips. This feature is available both in the Web and InIDE versions of the Marketplace. Now, when writing a review, users will have access to usef
Can we say "improved the Write Review screen"? Otherwise it sounds like a new feature rather than an improvement?

2024-03-05 15:48 UTC, JJdegroot1993 commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have added a new Reply to Review Screen with Supplier Tips. This improves communication between suppliers and reviewers.
I think some extra documentation in (1) Marketplace Overview and in (2) Sharing Marketplace Content might be good to add. For example that a user can now also use filters and that suppliers need to reply to reviews they get. In the user tips we have a link to the Marketplace Forum where the user can create a thread to continue the discussion or share an idea. Do we have to deliver some text for the documentation? Or can you guys create a PR for this?

2024-03-06 14:27 UTC, MarkvanMents reviewed
Hi @JJdegroot1993 
Finally got to look at the changes and work on the release notes text. Please let me know if my updates focus correctly on the changes.
I'll wait to hear from you that the release is successful and then publish, unless you have further changes that would be good.

We can work on additional documentation in a separate PR.

2024-03-06 14:27 UTC, MarkvanMents commented on content/en/docs/appstore/overview/_index.md
> +    * Browse, **Sort by review date**, and **Filter** these reviews for insights on the component
What do you mean by "Filter"? I can't see any filters available other than number of stars.

2024-03-06 14:27 UTC, MarkvanMents commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have improved the **Review** tab to give you tips when replying to a review of your Marketplace component.
Hi @JJdegroot1993 
I've updated these release notes to clarify what has changed and to apply our styling.
I have also removed some of the additional text on the "why" as it is down to customer to use the features in the way which gives most benefit. I think this moves the focus onto exactly what the changes are.

2024-03-06 14:29 UTC, MarkvanMents commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have added a new Reply to Review Screen with Supplier Tips. This improves communication between suppliers and reviewers.
Will pick up the additional documentation at the end of the week as a separate PR. Will be in touch over Slack.

2024-03-06 14:31 UTC, JJdegroot1993 commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have added a new Reply to Review Screen with Supplier Tips. This improves communication between suppliers and reviewers.
Sounds good! Thanks Mark

2024-03-06 14:35 UTC, JJdegroot1993 commented on content/en/docs/appstore/overview/_index.md
> +    * Browse, **Sort by review date**, and **Filter** these reviews for insights on the component
With ''Filter'' we mean a filter for the review rating (All stars, 5 stars, 4 stars, 3 stars etc.) so the user can filter those out. We have one sorting filter (ascending rating, descending rating) which sorts the reviews for the user as they like.

2024-03-06 14:38 UTC, JJdegroot1993 commented on content/en/docs/releasenotes/marketplace/_index.md
> +* We have improved the **Review** tab to give you tips when replying to a review of your Marketplace component.
Sounds good! I will let you know tomorrow once its released :)

2024-03-07 07:53 UTC, JJdegroot1993 commented
> Hi @JJdegroot1993 Finally got to look at the changes and work on the release notes text. Please let me know if my updates focus correctly on the changes. I'll wait to hear from you that the release is successful and then publish, unless you have further changes that would be good.
> 
> We can work on additional documentation in a separate PR.

The Marketplace Reviews have been released. The release notes can be published

2024-03-07 07:59 UTC, MarkvanMents approved these changes
Thanks for the go-ahead.
Approving and merging.

2024-03-07 07:59 UTC, merged