Beta release of the new Access Rule Editor
mendix/docs pull request #6942
Opened 2023-12-11 12:37 UTC by WimJongeneel

Documentation for the public beta release of the new access rule editor for 10.6.0.

2023-12-13 08:27 UTC, MarkvanMents commented
Hi Wim, @WimJongeneel 
Please let me know when this is ready for review.

2023-12-13 08:58 UTC, WimJongeneel commented
Hi @MarkvanMents, its ready for review

2023-12-13 10:21 UTC, EnasAbdelrazek requested changes

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +The new access rule editor works with normalised access rules. A normalised access rule is an access rule that has exactly one module role attached to it. This change is made because the new editor w
It can be changed to: This change is made because the new editor works with a table where the entity members make use of the rows and module roles (optionally with XPaths) use the columns.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Each module role from the module of the entity will have a default column for its access rigths without a XPath. Next to this default column a module role can have more columns if XPath's have been a
change to: without an XPath. Additionally, we can mention here that the default column can't be deleted.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +A XPath contraint can be be added to a module role by clicking on the XPath field of its default column. This will open the XPath editor dialog. After a XPath contraint has been entered a new column
An XPath constraint can be added to a module role by clicking on the XPath field of its default column. This will open the XPath editor dialogue. After an XPath constraint has been entered, a new column is added. This new column will be created with the same access rights as the default column. Alternatively, you can use the 'Add XPath' option in the context menu to add a new column based on any column [Read more](#add-xpath).

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +The non-default columns with a XPath contraint can be deleted via the context menu. The default column can not be deleted, but its content can be cleared in the same way. [Read more](#delete-clear)
Change to: with an XPath constraint.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +## 3 Editing Create rigths
typo (rights). It could be nice if we have all the rights under one bigger section called Editing Rights, what do you think?

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Toggle the setting shown below *on* or *off* to enable or disable Create rigths. Note that XPath contrains are not applied to create operations, meaning that if you enable create access for one colum
typo: Toggle the setting shown below *on* or *off* to enable or disable Create rights. Note that XPath constraints are not applied to create operations, meaning that if you enable create access for one column of a module role, any user with this module role can create objects of this entity.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Toggle the setting shown below *on* or *off* to enable or disable Delete rigths. In contrast to Create access, XPath contrains are applied to delete operations.
typo: Toggle the setting shown below *on* or *off* to enable or disable Delete rights. In contrast, to Create access, XPath constraints are applied to delete operations.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Toggle the setting shown below *on* or *off* to enable or disable Read rigths for the attribute or assosiation of that row. When disabling Read access, Write access is automatically disabled as well.
Typo: Toggle the setting shown below *on* or *off* to enable or disable Read rights for the attribute or association of that row. When disabling Read access, Write access is automatically disabled as well.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Next to this you can click the 'read' icon in the footer to enable or disable Read access for all attributes and associations in this column.
We can add that: and then Write access is automatically disabled for all members in this column.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +The context menu of a column can be openen by clicking on the three dots icon that is shown when hovering over a module role name in the header. Within the context menu you will find options to easil
typo: The context menu of a column can be opened by clicking on the three dot icon that is shown when hovering over a module role name in the header. Within the context menu, you will find options to easily reuse, add or remove access rules.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +This option allows you select another column and to copy the Create, Delete, Read and Write access of that column to this column.
allows you to select.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +This option allows you enter an XPath and create a new column with the same Create, Delete, Read and Write access of this column, but with the new XPath you just entered.
allows you to enter.

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +For columns with an XPath contraint this option allows you to remove this column from the table. For the default columns this option allows you to reset all the access rigths to their default values.
For columns with an XPath constraint, this option allows you to remove this column from the table. For the default columns, this option allows you to reset all the access rights to their default values.

Additionally, could you explain what is the default values?

2023-12-13 10:21 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
Why did you change this?

2023-12-13 10:22 UTC, EnasAbdelrazek commented
@WimJongeneel  Can we mention also that any newly added attributes will be added with the default access rights which is None?

2023-12-13 12:12 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
Yes, is accidental whitespace

2023-12-13 14:19 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +
I mean why did you change the link for (/refguide/logic-editors-beta/)?

2023-12-13 14:19 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +The non-default columns with an XPath contraint can be deleted via the context menu. The default column can not be deleted, but its content can be cleared in the same way. [Read more](#delete-clear)
Typo: an XPath constraint.

2023-12-13 14:19 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +### 3.1 Editing Create Rights
I think we can remove `Editing` from all the sections underneath.

2023-12-13 14:19 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Next to this you can click the 'read' icon in the footer to enable or disable Read access for all attributes and associations in this column. Disabling Read access for all rows will also disable Writ
Next to this, you can click the 'read' icon in the footer to enable or disable Read access for all attributes and associations in this column. Disabling Read access for all rows will also disable Write access for all of them.

2023-12-13 14:19 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/domain-model/entities/access-rules-editor-beta.md
> +Next to this you can click the 'write' icon in the footer to enable or disable Write access for all attributes and associations in this column. Enabling Write access for all rows will also enable Rea
Next to this, you can click the 'write' icon in the footer to enable or disable Write access for all attributes and associations in this column. Enabling Write access for all rows will also enable Read access for all of them.

2023-12-13 15:55 UTC, MarkvanMents commented
Hi @WimJongeneel 
Is there a reason you want this as a separate document and not just part of [Access Rules](https://docs.mendix.com/refguide/access-rules/)?
Once it comes out of beta, then we will need to have both editors documented, depending on whether the customer is using 10.6 or a later version where the editor is no longer beta.

I would rather put this new information into the current document and just point the customer to the correct section depending on what editor they are using. Do you have any objection to that?

2023-12-14 13:26 UTC, WimJongeneel commented
> Hi @WimJongeneel Is there a reason you want this as a separate document and not just part of [Access Rules](https://docs.mendix.com/refguide/access-rules/)? Once it comes out of beta, then we will need to have both editors documented, depending on whether the customer is using 10.6 or a later version where the editor is no longer beta.
> 
> I would rather put this new information into the current document and just point the customer to the correct section depending on what editor they are using. Do you have any objection to that?

Hi @MarkvanMents, I'm totally fine with putting this in the same document, I was just following what was done with the Beta Logic Editors.

2023-12-14 14:44 UTC, EnasAbdelrazek approved these changes

2023-12-15 13:26 UTC, MarkvanMents commented
> > Hi @WimJongeneel Is there a reason you want this as a separate document and not just part of [Access Rules](https://docs.mendix.com/refguide/access-rules/)? Once it comes out of beta, then we will need to have both editors documented, depending on whether the customer is using 10.6 or a later version where the editor is no longer beta.
> > I would rather put this new information into the current document and just point the customer to the correct section depending on what editor they are using. Do you have any objection to that?
> 
> Hi @MarkvanMents, I'm totally fine with putting this in the same document, I was just following what was done with the Beta Logic Editors.

Thanks for the response, Wim.
I'll move it into a single document and review.
I'll let you know when it's done.

2023-12-15 15:59 UTC, MarkvanMents commented
@WimJongeneel 
I've finished my first pass proofread.
I ran out of time as I have to finish now, so I'll have another look on Monday. But please make any comments if you manage to review it before then.

2023-12-18 15:08 UTC, MarkvanMents approved these changes
@WimJongeneel 
Thanks for your PR.
I've put all the changes into the access-rules document, rather than having a separate document.
I've also taken the opportunity to review the whole document so that the information in the two editor sections matches.
I will publish this PR with version 10.6. Please let me know if you have any comments before then. We can also make changes afterwards based on the customer feedback.

The new access rules editor looks much clearer and I think it will really help customers with their entity security.

Thanks for the comprehensive PR.

2023-12-21 14:21 UTC, merged