Siemens Industrial Edge
mendix/docs pull request #7028
Opened 2023-12-29 15:58 UTC by katarzyna-koltun-mx

2024-01-02 13:39 UTC, SharathNShyam commented on content/en/docs/developerportal/deploy/mendix-app-on-industrial-edge.md
In order to guarantee the best experience, you will need to set up your system accordingly.
Check out the following Link to understand dependencies and prerequisites to use Mendix on Edge

The above text is required under Prerequistes section.

2024-01-02 13:57 UTC, SharathNShyam commented on content/en/docs/developerportal/deploy/mendix-app-on-industrial-edge.md
> +For information about the dependencies and prerequisites to use Mendix on Edge, see [Mendix on Edge](https://docs.eu1.edge.siemens.cloud/develop_an_application/mendix/user_journey.html).
Replace the text with the below line:

In order to guarantee the best experience, you will need to set up your system accordingly.
Check out the following Link to understand dependencies and prerequisites to use Mendix on Edge
(https://docs.eu1.edge.siemens.cloud/develop_an_application/mendix/user_journey.html)

2024-01-03 12:27 UTC, SharathNShyam commented on content/en/docs/developerportal/deploy/mendix-app-on-industrial-edge.md
> +For more information about pushing your applications to the Industrial Edge Management system, see [Industrial Edge Management - Overview](https://docs.eu1.edge.siemens.cloud/get_started_and_operate/
please update the link with the following:
(https://docs.eu1.edge.siemens.cloud/develop_an_application/mendix/user_journey.html)

2024-01-03 12:56 UTC, SharathNShyam requested changes
I have reviewed and added my comments.

2024-01-03 13:42 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/mendix-app-on-industrial-edge.md
> +For information about the dependencies and prerequisites to use Mendix on Edge, see [Mendix on Edge](https://docs.eu1.edge.siemens.cloud/develop_an_application/mendix/user_journey.html).
The sense of the paragraph is the same, but my version is rewritten to match our standard documentation style. The original text does not match some of our requirements, so I can't use it directly, but I think my rewritten version covers the meaning.

2024-01-03 13:46 UTC, katarzyna-koltun-mx commented on content/en/docs/developerportal/deploy/mendix-app-on-industrial-edge.md
> +For more information about pushing your applications to the Industrial Edge Management system, see [Industrial Edge Management - Overview](https://docs.eu1.edge.siemens.cloud/get_started_and_operate/
Done.

2024-01-03 13:47 UTC, katarzyna-koltun-mx commented
@SharathNShyam I have made 1 requested change and decided not to make the other one, see my reasoning above. I've also reached out to the Academy contact responsible for the course, and will add the link to the course when it's public. Let me know if I should publish this PR now, or wait until the course is available.

2024-01-03 14:46 UTC, merged