[WTF-1633] Make selection api public [10.7.0]
mendix/docs pull request #7055
Opened 2024-01-05 10:18 UTC by jeffersonRibeiro

[TODO]

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA requested changes
First round of review is done.

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The property type was was introduced in Mendix [10.7](/releasenotes/studio-pro/10.7/).
The word 'was' is doubled in this sentence.

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +#### 4.9.1 XML Attributes
I think, one blank line should be enough before and after the sentence on line 747.

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +
I guess this table needs reformatting.

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `Multi`                   | `SelectionMultiValue`                         |
This table also seems to have formatting issues.

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +
After the link to the photo, one blank line should be enough I think. That would make it consistent with other places.

2024-01-08 12:59 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +* If only single are allowed, the component receives a `SelectionSingleValue` defined as `SelectionValue<Option_2<ObjectItem>> & { type: "Single" };`
Shouldn't that be `<Option<ObjectItem>>` instead of `<Option_2<ObjectItem>>`?

2024-01-08 13:17 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The property type was was introduced in Mendix [10.7](/releasenotes/studio-pro/10.7/).
Fixed ❇️

2024-01-08 13:17 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +#### 4.9.1 XML Attributes
Fixed ❇️

2024-01-08 13:17 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +
Fixed ❇️

2024-01-08 13:17 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `Multi`                   | `SelectionMultiValue`                         |
Fixed ❇️

2024-01-08 13:17 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +
Fixed ❇️

2024-01-08 13:17 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +* If only single are allowed, the component receives a `SelectionSingleValue` defined as `SelectionValue<Option_2<ObjectItem>> & { type: "Single" };`
Fixed ❇️

2024-01-08 14:15 UTC, legio-vi-ferrata commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +* If only single are allowed, the component receives a `SelectionSingleValue` defined as `SelectionValue<Option_2<ObjectItem>> & { type: "Single" };`
I'm not seeing the fix. 😅 It's still `Option_2` here.

2024-01-11 08:01 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`<selectionTypes>` (required) — This element encapsulates `<selectionType>` elements which declare supported selection types available while configuring the attribute property in Studio Pro.
Attribute property?

2024-01-11 08:01 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `None`                    | `any`                                         |
Is that really `any`? When `None` is configured isn't the value of the selection property undefined?

2024-01-11 08:01 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +	return "None";
This looks like a very big indent

2024-01-11 08:01 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The selection property allows a user to configure a [selection](/refguide/selection/).
With user we usually mean a user of Studio Pro, I think it is better to phrase it that the widget can read and set a selection, and that is can be used in actions and expressions.

2024-01-11 08:01 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +* If only single are allowed, the component receives a `SelectionSingleValue` defined as `SelectionValue<Option<ObjectItem>> & { type: "Single" };`
single -> single selection (similar change for the line below)

2024-01-11 08:47 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`<selectionTypes>` (required) — This element encapsulates `<selectionType>` elements which declare supported selection types available while configuring the attribute property in Studio Pro.
FIxed ❇️

2024-01-11 08:48 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +	return "None";
Fixed ❇️

2024-01-11 08:48 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +* If only single are allowed, the component receives a `SelectionSingleValue` defined as `SelectionValue<Option<ObjectItem>> & { type: "Single" };`
Fixed ❇️

2024-01-11 09:16 UTC, jeffersonRibeiro commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `None`                    | `any`                                         |
The exported ts type is `selection?: any` or `undefined | any` But in reality during js runtime it is always `undefined`.
In this case, I agree that we should go for `undefined`

2024-01-11 12:06 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +| `None`                    | `any`                                         |
❇️

2024-01-11 12:06 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +`<selectionTypes>` (required) — This element encapsulates `<selectionType>` elements which declare supported selection types available while configuring the attribute property in Studio Pro.
❇️

2024-01-11 12:09 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-property-types.md
> +The selection property allows a user to configure a [selection](/refguide/selection/).
❇️

2024-01-11 12:11 UTC, mlaponder commented on content/en/docs/apidocs-mxsdk/apidocs/pluggable-widgets/pluggable-widgets-client-apis/_index.md
> +	return "None";
❇️

2024-01-11 12:11 UTC, mlaponder approved these changes

2024-01-12 14:23 UTC, legio-vi-ferrata approved these changes

2024-01-12 14:23 UTC, mlaponder commented
lgtm @ConnorLand it is up to you now

2024-01-17 15:28 UTC, ConnorLand approved these changes

2024-01-30 09:46 UTC, merged