Workflow events
mendix/docs pull request #7155
Opened 2024-01-24 13:43 UTC by ishan1729

2024-01-25 09:50 UTC, hugomendix requested changes

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +events and there can be multiple event handlers. An event is triggered when the workflow or its activity goes through transformations which warrant the event.
Maybe 'transition' is a better term than 'transformation'?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +   * **When section** allows you to select multiple workflow event types
Suggestion: 'allows you to select the workflow event types, for which the handler should be triggered''

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +   * **Microflow** allows you to select a microflow that is triggered for each of the above selected workflow event types
Consider changing 'is' to 'should be'.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +You can use the data from the event handler microflows to build audit trails or for logging purposes. For example, it can be useful for a manager to see progress of an employee onboarding process.
Suggestion: 'microflows' -> microflow'

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +You can use the data from the event handler microflows to build audit trails or for logging purposes. For example, it can be useful for a manager to see progress of an employee onboarding process.
Should we add an info note here, stating that the attribute data is a snapshot of the data at the time the event occurs? And a warning, stating that all associations (with the exception of a sub `WorkflowRecord`) are associations to 'live' objects, whose state may have been updated since the event.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **EventTime** is the time at which the event is triggered.
Suggestion: 'is triggered' -> 'occurred'

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **WorkflowEvent_Initiator** is the identifier of the current user object which is logged in. The activity workflow events will have an initiator in cases where a user takes some action otherwis
It's not an identifier, is it? But an association to `System.User`.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
> +The Workflow Engine uses two different task queues. They can be configured in the **App Settings** > the **Workflows** tab > the **Optimization** section. There is one task queue for workflow executi
Unrelated to this story: I think we're missing the Microflow decision method for Multi user tasks.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +Workflow engine emits real time workflow events. These events provide a great way to get a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.
Should be maybe use 'near real time'?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When something happens in the workflow engine an event is emitted when subscribed to. This event is posted asynchronously using the task queues as described in [workflow engine](/refguide/workflow-en
Suggestions:
* 'when subcribed to' -> 'when subscribed to that event'
* 'task queues' -> 'task queue'

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When something happens in the workflow engine an event is emitted when subscribed to. This event is posted asynchronously using the task queues as described in [workflow engine](/refguide/workflow-en
The fact that we convert data in the task queue seems like an implementation detail to me, that we need/should not mention. It's sufficient to know/state that we include the data at the time of the event occurring in the NPEs.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWCOMPLETED           | Signifies the successful completion of a workflow                                                            |
Or: `Triggered with a workflow completes successfully`? To be more in line with the other descriptions.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWFAILED              | Triggered when a workflow instance fails                                                                     | When a user task fails, we fail the workflow
It's not just user tasks that cause this, right? Any failing activity will fail the workflow.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWUPDATED             | Triggered when a parent workflow is progressed after the sub-workflow is retried, restarted, or adhoc-jumped | See [Operation](/refguide/change-workflow-state/#operati
'is progressed' sounds a bit weird to me. Maybe we can rephrase it to: '... is put back into progress ...'

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWRESOLVED            | Triggered when the workflow is continued                                                                     | See [Operation](/refguide/change-workflow-state/#operati
Maybe add 'after being incompatible'?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWRETRIED             | Triggered when a workflow is retried                                                                         | See [Operation](/refguide/change-workflow-state/#operati
Maybe add 'after being failed'?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWJUMPTOOPTIONAPPLIED | Triggered when the workflow is adhoc jumped                                                                  | See [Jump-To](refguide/jump-to/)
Again, this sounds a bit wonky. Consider using 'when an ad-hoc jump is performed on the workflow'

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| DECISIONEXECUTED            | Triggered when `Decision` is executed                                                                   | See [Decision](/refguide/decision-in-workflows/)
Consider using 'when a `Decision` activity is executed'. Same for the other activities.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLWORKFLOWSTARTED         | Triggered in following cases:<br> - Sub-workflow is successfully instantiated<br> - Sub-workflow definition is not found<br> - Sub-workflow is retried, restarted or ad
'adhoc-jumped' is not really a verb that can be applied to a workflow; please rephrase it.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLWORKFLOWENDED           | Triggered in following cases:<br> - Workflow is `Completed`, `Failed` and `Aborted`<br> - Sub-workflow definition is not found<br> - Workflow suspended on `CallWorkflo
Should 'Sub-workflow definition is not found' here? Is it related to incompatibility? If so, please clarify that.

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWINITIATED           | Triggered when a new workflow instance is initiated                                                          |
I'm wondering whether it makes sense to make this list alphabetical, or use the same sequence as the Studio Pro dialog (which seems rather arbitrary to me; maybe we should make that alphabetical as well).

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLMICROFLOWENDED          | Triggered in following situations:<br> - Microflow is executed successfully with a valid outcome<br> - Workflow suspended on `CallMicroflow` is aborted, restarted or a
Should we add `empty` value to invalid outcome?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| USERTASKSTARTED             | Triggered in following cases:<br> - User targeting is evaluated or<br> - OnCreated microflow is successfully scheduled | See [UserTask](/refguide/user-task/) or [Multi
Is this true? Shouldn't it be **after** the OnCreatd microflow has executed?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| USERTASKENDED               | Triggered in following cases:<br> - User task fails<br> - Workflow suspended on `UserTask` is aborted, restarted or adhoc-jumped<br> - Parallel path containing `UserTa
Should we add here that it will only have an actor in case of a single-user task?

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| USERTASKENDED               | Triggered in following cases:<br> - User task fails<br> - Workflow suspended on `UserTask` is aborted, restarted or adhoc-jumped<br> - Parallel path containing `UserTa
Seems like there is an underscore at the end...

2024-01-25 09:50 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-properties.md
> +**Event Handlers** section allows you to override the app-wide event handlers in the **App Settings** and to set workflow-specific event handlers that will be triggered when the workflow or its activ
Suggestion: 'transformations' -> 'transitions'

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +events and there can be multiple event handlers. An event is triggered when the workflow or its activity goes through transformations which warrant the event.
I like it better. Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +   * **When section** allows you to select multiple workflow event types
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +   * **Microflow** allows you to select a microflow that is triggered for each of the above selected workflow event types
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +You can use the data from the event handler microflows to build audit trails or for logging purposes. For example, it can be useful for a manager to see progress of an employee onboarding process.
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +You can use the data from the event handler microflows to build audit trails or for logging purposes. For example, it can be useful for a manager to see progress of an employee onboarding process.
Yes, good idea. I added it to the `WorkflowEvents` file under `Event Mechanism`.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **EventTime** is the time at which the event is triggered.
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **WorkflowEvent_Initiator** is the identifier of the current user object which is logged in. The activity workflow events will have an initiator in cases where a user takes some action otherwis
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When something happens in the workflow engine an event is emitted when subscribed to. This event is posted asynchronously using the task queues as described in [workflow engine](/refguide/workflow-en
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWCOMPLETED           | Signifies the successful completion of a workflow                                                            |
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWRETRIED             | Triggered when a workflow is retried                                                                         | See [Operation](/refguide/change-workflow-state/#operati
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWUPDATED             | Triggered when a parent workflow is progressed after the sub-workflow is retried, restarted, or adhoc-jumped | See [Operation](/refguide/change-workflow-state/#operati
Yes, agree.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWRESOLVED            | Triggered when the workflow is continued                                                                     | See [Operation](/refguide/change-workflow-state/#operati
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWJUMPTOOPTIONAPPLIED | Triggered when the workflow is adhoc jumped                                                                  | See [Jump-To](refguide/jump-to/)
I also removed reference for ad-hoc as that is not the term we usually use.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| DECISIONEXECUTED            | Triggered when `Decision` is executed                                                                   | See [Decision](/refguide/decision-in-workflows/)
Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLWORKFLOWSTARTED         | Triggered in following cases:<br> - Sub-workflow is successfully instantiated<br> - Sub-workflow definition is not found<br> - Sub-workflow is retried, restarted or ad
Rephrased.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLWORKFLOWENDED           | Triggered in following cases:<br> - Workflow is `Completed`, `Failed` and `Aborted`<br> - Sub-workflow definition is not found<br> - Workflow suspended on `CallWorkflo
No, it not related to incompatibility. It is the case when the sub-workflow doesn't event exist when you start the parent workflow. I have made some additions to make it more clear.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| USERTASKENDED               | Triggered in following cases:<br> - User task fails<br> - Workflow suspended on `UserTask` is aborted, restarted or adhoc-jumped<br> - Parallel path containing `UserTa
Good idea. Done.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| USERTASKENDED               | Triggered in following cases:<br> - User task fails<br> - Workflow suspended on `UserTask` is aborted, restarted or adhoc-jumped<br> - Parallel path containing `UserTa
That's just to make it Italics.

2024-01-25 14:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-properties.md
> +**Event Handlers** section allows you to override the app-wide event handlers in the **App Settings** and to set workflow-specific event handlers that will be triggered when the workflow or its activ
Done.

2024-01-25 14:10 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWRETRIED             | Triggered when a workflow is retried after being failed or incompaible                                                                      | See [Operation](/refguide
Typo: 'incompaible' -> 'incompatible'

2024-01-25 14:26 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWRETRIED             | Triggered when a workflow is retried after being failed or incompaible                                                                      | See [Operation](/refguide
Oops: Fixed.

2024-01-25 14:27 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWFAILED              | Triggered when a workflow instance fails                                                                     | When a user task fails, we fail the workflow
I just added it as an example, also the column it is in has the heading as `Examples`. Shall I make it more explicit?

2024-01-25 14:27 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +Workflow engine emits real time workflow events. These events provide a great way to get a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.
On further thinking: Looks like a good idea indeed.

2024-01-25 14:29 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| USERTASKSTARTED             | Triggered in following cases:<br> - User targeting is evaluated or<br> - OnCreated microflow is successfully scheduled | See [UserTask](/refguide/user-task/) or [Multi
Yes, we don't wait for the microflow to be completed.

2024-01-25 14:38 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLMICROFLOWENDED          | Triggered in following situations:<br> - Microflow is executed successfully with a valid outcome<br> - Workflow suspended on `CallMicroflow` is aborted, restarted or a
As discussed on `empty` outcome we simply suspend the workflow. So, there is no event for that.

2024-01-25 14:50 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
> +The Workflow Engine uses two different task queues. They can be configured in the **App Settings** > the **Workflows** tab > the **Optimization** section. There is one task queue for workflow executi
Yes, you are right. Added.

2024-01-25 15:44 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +Workflow engine emits real time workflow events. These events provide a great way to get a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.
I don't see them in https://github.com/mendix/docs/pull/7155. Did you push your changes?

2024-01-25 15:46 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| CALLMICROFLOWENDED          | Triggered in following situations:<br> - Microflow is executed successfully with a valid outcome<br> - Workflow suspended on `CallMicroflow` is aborted, restarted or a
You're right. My bad.

2024-01-25 16:43 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +You can use the data from the event handler microflow to build audit trails or for logging purposes. For example, it can be useful for a manager to see progress of an employee onboarding process.
pls delete this line:  "For example, it can be useful for a manager to see progress of an employee onboarding process." It's confusing. Other example: You can define an event handler that (only) collects data from user task events.

2024-01-25 16:49 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +### 7.4 Events {#events} (Deprecated)
Add line: State change events are deprecated and replaced with the new event handlers, that also contain events for state changes. It's suggested to migrate the microflows to the new event handlers.

2024-01-25 16:54 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
> +In case one of these workflow-related tasks fail (the workflow execution fails or the microflow execution fails), then the task queue task still succeeds. However, the result is always reflected in t
"...or automate them using microflows on state-change events". Pls suggest another option because state change events are deprecated.

2024-01-25 17:00 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **WorkflowEvent_Initiator** is an association to the current user object which is logged in. The activity workflow events will have an initiator in cases where a user takes some action otherwis
"The activity workflow events". I don't understand the using of the word "activity" here. Maybe explain a bit differently. 
"when a user specifies the outcome of a user task". But this data is also in the activity record. Is it double? Are they always the same or can they be different? The user notifies a suspended workflow I understand.

2024-01-25 17:03 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +Workflow engine emits near real time workflow events. These events provide a great way to get a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.
The emphasis should be less on real-time. Remove this part "a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.". Use something like: "These events provide a great way to build audit trails, handle errors, update KPI dashboards, etc"

2024-01-25 17:04 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +
like it. Well explained!

2024-01-25 17:09 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When a particular action results in multiple events (e.g. abort or end of workflow), then we treat this action as an atomic action and include the state (workflow and activity) as it will be at the e
When a particular **workflow** action results in multiple events **beeing triggered**.  
Think this is a bit clearer.
"...as it will be at the end of the transaction ...". Difficult to understand. Can you add an example?

2024-01-25 17:16 UTC, PaulJongenMx reviewed
Well done. That was a lot of work.

2024-01-25 17:20 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +url: /refguide/workflow-events/
"Workflow events" might be confusing as it might also indicate Timer event and Wait for notification event.

I suggest to use: "Workflow Event Handlers"

2024-01-26 10:03 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **WorkflowEvent_Initiator** is an association to the current user object which is logged in. The activity workflow events will have an initiator in cases where a user takes some action otherwis
> "The activity workflow events". I don't understand the using of the word "activity" here. Maybe explain a bit differently.

I can understand the confusion. By `activity workflow events` I am talking about the events described in section `5.2` of `WorkflowEvents` document. For example, CallWorkflowStarted, UserTaskEnded etc. 

Or in other words, non workflow lifecycle events.

> But this data is also in the activity record. Is it double? Are they always the same or can they be different?

For the activity record indeed the `actor` field is copied as the initiator. If there is no `actor` the initiator will also be empty.  So, for activity related events they are always the same.

But the initiator association is also used for the Workflow Lifecycle events. So, its not just specific to activity related events.

2024-01-26 10:07 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +Workflow engine emits near real time workflow events. These events provide a great way to get a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.
Done.

2024-01-26 10:07 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +
Added.

2024-01-26 10:07 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When a particular action results in multiple events (e.g. abort or end of workflow), then we treat this action as an atomic action and include the state (workflow and activity) as it will be at the e
Yes, good idea. Done.

2024-01-26 10:08 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/_index.md
> +    * **WorkflowEvent_Initiator** is an association to the current user object which is logged in. The activity workflow events will have an initiator in cases where a user takes some action otherwis
For now, I have added a reference to the 5.2 section so that it becomes clear which events I am talking about. Can you please check if that makes it clear already?

2024-01-26 10:08 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +### 7.4 Events {#events} (Deprecated)
Good idea. Added.

2024-01-26 10:08 UTC, ishan1729 commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +You can use the data from the event handler microflow to build audit trails or for logging purposes. For example, it can be useful for a manager to see progress of an employee onboarding process.
Removed.

2024-01-26 10:11 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +url: /refguide/workflow-events/
> I suggest to use: "Workflow Event Handlers" or "Workflow Runtime Event Handlers"

I think these names still have the `Workflow Event` in them which is again like you said is generic. Can't we simply call these events as Workflow engine events or Workflow transition events?

2024-01-26 10:14 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +Workflow engine emits real time workflow events. These events provide a great way to get a real time check on the functioning of the workflow engine and to keep an eye on the workflow progress.
I didn't realize that real-time is mentioned multiple times. Anyways, the second statement has been removed now as suggested by Paul.

2024-01-26 10:18 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +| WORKFLOWINITIATED           | Triggered when a new workflow instance is initiated                                                          |
I believe we can't change the Studio Pro order because we are already in later phases of the current release. 
But I can make this alphabetical and we can later think about changing the Studio Pro order.

2024-01-26 10:20 UTC, hugomendix commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +url: /refguide/workflow-events/
It's unfortunate that event is such an overloaded term, but an event handler is something completely different thing. An event is something that occurs; an event handler is some logic that does something when it occurs.
In Studio Pro we also use both terms for setting up push data:

- On a workflow (or app level) we have an `Event handlers` property.
- It contains a list of Event handlers, identified by Name
- Each Event handler contains a list of Events, to which it applies
- Each Event handler also contains a Microflow with logic for handling the Event

![image](https://github.com/mendix/docs/assets/58431933/d2c26b3f-1353-4542-8c46-228c30905973)

Moreover, Event and Event handler are common terminology in Studio Pro generically, for instance on Entities, where one can set up an Event handler for a particular Event with some Microflow. Exactly the same concepts.

The fact that BPMN also defines Events doesn't change any of that. It's unfortunate, but calling them something else than the rest of Studio Pro is really confusing and should not be done IMHO. Mendix is more than a Workflows platform.

2024-01-29 13:07 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
> +When one of these workflow-related tasks fails (the workflow execution fails or the microflow execution fails), the task queue task still succeeds. However, the result is always reflected in the work
@ishan1729 Just want to verify with you, with the addition of "except for failures with event handlers", do we still need to rephrase "state-change events" in this sentence?

> You can handle the failures from the Workflow administration pages or automate them using microflows on state-change events.

2024-01-29 13:21 UTC, Yiyun333 commented
@ishan1729 
Thanks for creating this PR. Great work! 

I just finished my review :) Can you please have a quick review of my changes and make sure that all the technical details are still correct? 

I've also left a [small comment](https://github.com/mendix/docs/pull/7155#discussion_r1469564116) above (related to [Paul's comment](https://github.com/mendix/docs/pull/7155#discussion_r1466669150) above). Please let me know what you think. Thanks a lot!

CC  @PaulJongenMx @hugomendix

2024-01-29 14:20 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
> +When one of these workflow-related tasks fails (the workflow execution fails or the microflow execution fails), the task queue task still succeeds. However, the result is always reflected in the work
I think this is not related to the addition of "except for failures with event handlers" but more related to the fact that we are deprecating the on-state events.

So, I guess we can just rephrase it to say that now you can use event handlers instead of the state changes. Something like:

`You can handle the failures from the Workflow administration pages or automate them using event handlers.`

@PaulJongenMx What do you think?

2024-01-29 14:34 UTC, ishan1729 commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When something happens in the workflow engine an event is emitted when subscribed to. This event is posted asynchronously using the task queues as described in [workflow engine](/refguide/workflow-en
@PaulJongenMx Do you have any opinions on this?

2024-01-29 14:54 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-engine.md
> +When one of these workflow-related tasks fails (the workflow execution fails or the microflow execution fails), the task queue task still succeeds. However, the result is always reflected in the work
Yes correct. We should not mention state-change events, because they are deprecated. We should mention event handlers.

2024-01-29 14:59 UTC, PaulJongenMx commented on content/en/docs/refguide/modeling/application-logic/workflows/workflow-events.md
> +When something happens in the workflow engine an event is emitted when subscribed to. This event is posted asynchronously using the task queues as described in [workflow engine](/refguide/workflow-en
For initial understanding of events this line is not required. However we need to explain somewhere that events are placed on the task queue so people know the data they query in the event handler could be outdated and also that events handlers don't delay or stall wf execution.

2024-01-30 09:36 UTC, merged