[UFC-1051] Add docs for react client setting
mendix/docs pull request #7212
Opened 2024-02-01 08:45 UTC by WimJongeneel

Can be release ASAP, the React client went into Beta in 10.7

2024-02-01 09:31 UTC, EnasAbdelrazek commented
@WimJongeneel Could you please add a screenshot for this setting?

2024-02-01 09:46 UTC, WimJongeneel commented
@EnasAbdelrazek we could, but would that add anything? We don't have for the other 10 out of 11 settings in this panel, and I don't think a picture of the radio buttons with exact labels as described will explain anything father.

2024-02-01 10:00 UTC, EnasAbdelrazek commented
@WimJongeneel I wanted to show that it is part of the runtime tab, but now I see that it is in the runtime tab section.

2024-02-01 10:00 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +- _Yes_: Use the React client. In this mode you will get consistency errors for imcompatable widgets.
```suggestion
- _Yes_: Use the React client. In this mode, you will get consistency errors for incompatible widgets.
```

2024-02-01 10:00 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +- _Migration mode_: Use the React client, but ignore incompatable widgets. Recommended for trying out the new client.
```suggestion
- _Migration mode_: Use the React client and ignore incompatible widgets. Recommended for trying out the new client.
```

2024-02-01 11:37 UTC, EnasAbdelrazek approved these changes

2024-02-02 10:24 UTC, Robinfr requested changes

2024-02-02 10:24 UTC, Robinfr commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +- _Migration mode_: Use the React client and ignore incompatible widgets. Recommended for trying out the new client.
Should we mention that we will display placeholders for incompatible widgets in this case?

2024-02-02 10:24 UTC, Robinfr commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +- _No_: Don't use the React (default).
Meaning we use the Dojo client.

Also 
```suggestion
- _No_: Don't use the React client (default).
```

2024-02-02 10:34 UTC, ConnorLand commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +- _Migration mode_: Use the React client and ignore incompatible widgets. Recommended for trying out the new client.
Yes, I will add.

2024-02-02 10:36 UTC, ConnorLand commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +- _Migration mode_: Use the React client and ignore incompatible widgets. Recommended for trying out the new client.
Looks good?

2024-02-02 10:41 UTC, ConnorLand commented
> @EnasAbdelrazek we could, but would that add anything? We don't have for the other 10 out of 11 settings in this panel, and I don't think a picture of the radio buttons with exact labels as described will explain anything father.

True. Docs best practice is to not display screenshots of settings which are described in the doc's text. This best practice prevents duplication.

2024-02-02 14:47 UTC, ConnorLand approved these changes

2024-02-02 14:54 UTC, merged