Update some of the information about the Mendix Client for the React client
mendix/docs pull request #7256
Opened 2024-02-08 14:29 UTC by WimJongeneel

2024-02-12 14:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=7256) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=7256) before we can accept your contribution.<br/>**10** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: tswarmerdam-mx<br/>:white_check_mark: tinaengel<br/>:white_check_mark: loket4<br/>:white_check_mark: WimJongeneel<br/>:white_check_mark: dbreseman<br/>:white_check_mark: Luyao-Zhang-1<br/>:white_check_mark: MarkvanMents<br/>:white_check_mark: Karuna-Mendix<br/>:white_check_mark: katarzyna-koltun-mx<br/>:white_check_mark: MariaShaposhnikova<br/>:x: mx-awsdevteam<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=7256) it.</sub>

2024-02-12 16:22 UTC, MarkvanMents requested changes
@WimJongeneel 
I think we should have a warning at the top of the page that the React Client is in beta.

I also think the introduction should mention the two clients with a link to how to choose between React and Dojo,

Can you write that, or would you like me to draft something?

2024-02-13 10:18 UTC, WimJongeneel commented
@MarkvanMents I've added an info box at the top of the document

2024-02-13 13:26 UTC, MarkvanMents requested changes
Hi @WimJongeneel 
Thanks for making the updates.
I have one further suggestion to clarify what happens if you swap clients but still have some Dojo widgets in your app.
Please can you have a look and see if you agree.
Other than that, this is ready to be published.

2024-02-13 13:26 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client.md
> +The React client replaces [Dojo](https://dojotoolkit.org/) with [React](https://react.dev/) for the view layer. Other components of the Mendix Client are the same in both the React and Dojo client. S
I think we should warn people here that the Dojo widgets won't work. Perhaps:
```suggestion
The React client replaces [Dojo](https://dojotoolkit.org/) with [React](https://react.dev/) for the view layer. This means that widgets based on Dojo will no longer work. You will get consistency errors if your app contains Dojo widgets, or you can choose **Migration mode** which will allow you to build your app but will replace incompatible widgets with a placeholder.

Other components of the Mendix Client are the same in both the React and Dojo client. See our [Release Blog](https://www.mendix.com/blog/mendix-release-10-7-go-mac-it/#react-client-public-beta) for more information.
```

2024-02-13 14:30 UTC, MarkvanMents approved these changes
Looks good now. Publishing. Thanks for the PR.

2024-02-13 14:31 UTC, merged