Update react client docs
mendix/docs pull request #7331
Opened 2024-02-23 08:34 UTC by jdiehl

2024-02-28 12:08 UTC, Robinfr requested changes

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/content-readiness.md
> +The Mendix Marketplace contains many useful and reusable widgets and modules created by Mendix as well as by our partners and community. Not all content found in the Mendix Marketplace is ready for t
We capitalize React client in other places. Would be nice if it was consistent everywhere:

- react client
- React client
- React Client

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/content-readiness.md
> +If the Marketplace content you are interested in is not included in the list, add it to your application with the react client enabled and look out for cnosistency errors.
```suggestion
If the Marketplace content you are interested in is not included in the list, add it to your application with the react client enabled and look out for consistency errors.
```

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/content-readiness.md
> +The following tables shows for popular platform-supported marketplace content whether it is ready for the react client (✅) or not (❌). We will continuously update this table as we improve the compati
```suggestion
The following table shows which of the more popular platform-supported marketplace content is ready for the react client (✅) or not (❌). We will continuously update this table as we improve the compatibility of our marketplace content.
```

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/content-readiness.md
> +| Marketplace Content | React Ready |
```suggestion
| Marketplace Content | React Client Ready |
```

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +JavaScript actions must not use any of the following client apis:
It might be better to simply refer to the API docs here for the React client: https://apidocs.rnd.mendix.com/10/client-react/index.html

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +### 3.2 Dynamic & Static image
Every section here mentions that it is unsupported. Maybe it's better to just create a section that says these are the unsupported widgets and how to convert them instead of having to mention it in each section?

2024-02-28 12:08 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +If your application's navigation bar does not fill the entire screen, you are likely using an outdated version of the [Atlas Core](https://marketplace.mendix.com/link/component/117187) module. Please
>Also make sure to not set the SCSS variable `$use-modern-client` anywhere in your custom styles.

This shouldn't be needed anymore

2024-02-28 13:07 UTC, jdiehl commented on content/en/docs/refguide/runtime/mendix-client/content-readiness.md
> +The Mendix Marketplace contains many useful and reusable widgets and modules created by Mendix as well as by our partners and community. Not all content found in the Mendix Marketplace is ready for t
Unified to React Client

2024-02-28 13:09 UTC, jdiehl commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +JavaScript actions must not use any of the following client apis:
I think explicitly mentioning what will be removed is helpful. I have added a link to this documentation. Can you confirm that these are the only changes?

2024-02-28 13:11 UTC, jdiehl commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +### 3.2 Dynamic & Static image
Let's do that once the conversion for the combo box is ready - then we can explain: these widgets are not supported. Click on convert to use their react counterparts. Right now, the combo box needs more explanation.

2024-02-28 13:12 UTC, jdiehl commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +If your application's navigation bar does not fill the entire screen, you are likely using an outdated version of the [Atlas Core](https://marketplace.mendix.com/link/component/117187) module. Please
Will remove it

2024-02-29 15:02 UTC, ConnorLand commented on content/en/docs/refguide/runtime/mendix-client/react.md
> +JavaScript actions must not use any of the following client apis:
I agree mentioning them here is nice. @Robinfr are there any additional changes?

2024-03-01 11:37 UTC, ConnorLand approved these changes

2024-03-01 11:37 UTC, merged