[RUN 3912] Add information about SBOM in Dependency Synchronization section
mendix/docs pull request #7382
Opened 2024-03-04 16:22 UTC by akkrishnakumar

Add information about SBOM in Dependency Synchronization section

2024-03-05 13:25 UTC, MarkvanMents requested changes
Hi Akhil (@akkrishnakumar)
Just one question about where this json file is. Should we say where the customer might find it or see it as part of a commit?
If that is irrelevant, then I can merge this - unless it is for a future release.

2024-03-05 13:25 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +We also generate the `vendorlib-sbom.json` file. This is the Software Bill of Materials of the `vendorlib` directory.
Should we say where this file is? I presume it is in the `/vendorlib` folder?

2024-03-06 09:30 UTC, akkrishnakumar commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +We also generate the `vendorlib-sbom.json` file. This is the Software Bill of Materials of the `vendorlib` directory.
Yes, that can make it and sounds more explicit.

2024-03-07 08:17 UTC, MarkvanMents commented on content/en/docs/refguide/java-programming/managed-dependencies.md
> +We also generate the `vendorlib-sbom.json` file. This is the Software Bill of Materials of the `vendorlib` directory.
Updated here: 263b2e145df31b6d4f997f7ddaf0dc44bdf80c34

2024-03-07 08:18 UTC, MarkvanMents approved these changes
Approving and merging immediately as discussed on Slack.

2024-03-07 08:35 UTC, merged