Leading Mendix Implementation in Your Organization
mendix/docs pull request #7420
Opened 2024-03-11 10:27 UTC by Luyao-Zhang-1

2024-03-15 14:18 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +{{% alert color="info" %}}For more resources for this section, see [Value Template for End Customers](/attachments/quickstarts/leading-mendix-implementation/value-template-for-end-customers.pptx).{{%
@MarkvanMents I added a link to this static PPT file. By clicking this link, the user can download the PPT file directly. 
I don't know we have provided files to users like this before. I guess this should be OK, but thought it's good to check with you.

2024-03-15 14:21 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +After developing and publishing your first Mendix app, it's important to put proper maintenance measures in place. [Establishing a regular upgrade practice](https://www.mendix.com/wp-content/uploads/
By clicking this link, users can view the PDF file directly in the browser. So I guess this should be OK. What do you think? @MarkvanMents

2024-03-15 14:28 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +url: /quickstarts/leading-mendix-implementation-in-your-organization/
This large doc covers a lot of different aspects, such as Digital Execution Practice, software development, project management, as well as different parts of Mendix products. Do you think we should put it here under Quick Start Guide? @MarkvanMents  @ConnorLand

2024-03-19 08:37 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +{{% alert color="info" %}}For more resources for this section, see [Value Template for End Customers](/attachments/quickstarts/leading-mendix-implementation/value-template-for-end-customers.pptx).{{%
Yes, that's fine.

2024-03-19 08:43 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +{{% alert color="info" %}}For more resources for this section, see [Value Template for End Customers](/attachments/quickstarts/leading-mendix-implementation/value-template-for-end-customers.pptx).{{%
Although I don't like the name of the powerpoint file. It is a bit impersonal and looks like we are imposing a template on the "End Customer".
The "End Customer" in the case is the reader, so if we can come up with a nicer name ("Company Apps Value Template", for example?) I think that would be a nicer user experience.

2024-03-19 08:48 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +{{% alert color="info" %}}For more resources for this section, see [Value Template for End Customers](/attachments/quickstarts/leading-mendix-implementation/value-template-for-end-customers.pptx).{{%
That's a very good point. I will change the name and then merge the PR. Thanks Mark!

2024-03-19 09:06 UTC, MarkvanMents requested changes, later dismissed
Hi Luyao, (@Luyao-Zhang-1)
I've made a few general comments on things that I think would quickly make a big difference to the doc.
I don't know whether you need me to read through it more thoroughly or whether you still have work to do on it.
I don't think we should change much of the remaining text and formatting, but I think what I have suggested would make a big difference to how it is perceived.

Let me know if you want me to proofread this. And let me know if you have any questions.

Mark

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +url: /quickstarts/leading-mendix-implementation-in-your-organization/
I think it is OK here - although not really a "Quick Start". I'm not sure where else it fits?

It would be nice to have a shorter and more direct name as the short title. Perhaps "Implementing Mendix in Your Organization" or "Bringing Mendix into Your Organization"

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +## Overview
Can we have this as section **1 Introduction** to be the same as other docs?

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +## Module 1: Introduction
Then we can just remove this one?

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +### Lecture 1.1 Welcome! What You Will Learn in This Guide
Can we remove the word "Lecture" from all the level 3 headings and the word "Module" from all the level 2 headings?
Should be easy with a search and replace - and if the words are used elsewhere in the document we can just replace with "section"?
Let me (or ChatGPT) know if you need help, but I don't think you even need a regular expression for this?

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +  The [Mendix Forum](https://forum.mendixcloud.com/link/questions) is where you can find help when you get **stuck.** You can also help others when you know the answer! Be sure to first check whether
Not the Mendix Forum,  "Community Questions"

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +## Module 2: Get Familiar With the 5 P’s of the Digital Execution Practice
Reminder from above:
Can we remove the word "Lecture" from all the level 3 headings and the word "Module" from all the level 2 headings?
Should be easy with a search and replace - and if the words are used elsewhere in the document we can just replace with "section"?
Let me (or ChatGPT) know if you need help, but I don't think you even need a regular expression for this?

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +* Check out the [Mendix Documentation](/):
Don't think we need a link here - they are already reading the documentation 😀

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +  At the end of each guide, you will be asked to fill in a survey. Please tell us what you think. Your opinion will help us to keep improving!
This is only for Academy, I think?
```suggestion
```

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +### Learning Objectives
Annoying that this is a heading.
Perhaps change all the Learning Objectives headings into Normal bold so we don't have to renumber all the sections?
(Can do it with a search and replace, probably).
```suggestion
**Learning Objectives**
```

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +After developing and publishing your first Mendix app, it's important to put proper maintenance measures in place. [Establishing a regular upgrade practice](https://www.mendix.com/wp-content/uploads/
For me it opens in Adobe Acrobat Reader, but wherever it opens it looks good.

2024-03-19 09:06 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +We respect your privacy. Your feedback is anonymous. We do not use any information from the survey to identify the user.
I think we should drop this as it will confuse the feedback and is aimed at people who have done the learning path.
![image](https://github.com/mendix/docs/assets/35492184/1d14a77c-7a50-4fd9-ad57-1cea989a4c24)
Unless someone wants it particularly.

2024-03-19 09:13 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +  [Join the Mendix Community](https://forum.mendix.com/p/questions) to connect with over 290,000 community members. The Forum is a great place for developers to ask questions and post ideas for our p
Forum -> Community questions

2024-03-19 09:15 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +### Lecture 2.4 Stay up to Date With Mendix
Check with Grammarly but I think this should be 
> Stay Up-to-Date with Mendix

2024-03-19 09:18 UTC, MarkvanMents commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +You should have already created your portfolio in Lecture [2.5](#2.5), if you haven’t yet let’s start by creating your Portfolio board, you can do that by going [here](https://portfolio.mendix.com/),
I think we should just refer to them as sections, not lectures?

2024-03-19 12:20 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +### Lecture 2.4 Stay up to Date With Mendix
Grammarly thinks both are fine. I think hyphens here are probably not needed, because the words are not used before a noun.

2024-03-19 12:42 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +We respect your privacy. Your feedback is anonymous. We do not use any information from the survey to identify the user.
Checked with PM. We can remove it.

2024-03-21 15:15 UTC, Luyao-Zhang-1 commented on content/en/docs/quickstarts/leading-mendix-implementation.md
> +url: /quickstarts/leading-mendix-implementation-in-your-organization/
I checked with the PM. We will use "Bringing Mendix into Your Organization".

2024-03-21 15:36 UTC, merged