Auth Token Support Docs
mendix/docs pull request #7431
Opened 2024-03-12 11:57 UTC by EnasAbdelrazek

2024-03-12 13:43 UTC, EnasAbdelrazek commented
[Diagram link](https://www.plantuml.com/plantuml/uml/bPB1Rjim44Jl-efjV7M3n4Lww2687TSd5oZgzbOWeAMnj91Cgikb7AVklnTI65iA3BGv211dXyCt8E-y6j6mhP9tMc0BMbS1kPXzuaksjH6pfRL9ornSiDczgvpGQ5UmecVm-1LWKz3lP9ggauMp6grN7s_ci-b9Nl4JQ7ALJ4NSRkZffAFdUXA5yrap9ndaUJ07wbMvdrK1oP8tMB95VpwQVlXyivYTPhq-_VbN8yefryPg3tKeluRvazIdCLryWStuaUuhXjKBCfxIxlTuni3zBLZbBMW5QI2TtNU_D9fVBoQBUM9IvSOeOinn7Nr9J7z_UnkLJxHqELlQiHOKFAP1Y--kXANkgg0Gyb1IHoe1IJol7z10UBCdBT06o9XIWL5qWeVtxEoOl6b0tEPqUcRKh8t7c7vQCZQZdN3SqaByY13jg9z3gNCbmr-UAoBjg_9AEVGX-X_QS-WST5eWBRleVkcOFwOC5RG5xW1pMCXB9Js22LGO3GQ4mRFDpp1VzYcUwLjaNxksFMinsDDo9uV3eVtUrDLi53A8AemdFDOioFvnUusfE6FTazjqQnEqEBLboygcugTpVLbV-lr_lIJ3g-VQKo9Vr_yEDWlRwYy0)

2024-03-13 08:49 UTC, WimJongeneel commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
It think that "get_session_data action" will be confusing for users because get_session_data isn't an action like we use **action** in other places.

2024-03-13 08:49 UTC, WimJongeneel commented on content/en/docs/refguide/runtime/session-management.md
> +The key change is that Mendix now use authentication tokens to reinitialize the session  instead of the previous approach of keeping the users logged in for a longer period.
I think it is a bit strange to talk about "key changes" in the docs, we are only documenting the current behavior of the product

2024-03-13 08:49 UTC, WimJongeneel commented on content/en/docs/refguide/runtime/session-management.md
> +The key change is that Mendix now use HTTPOnly cookie to hold the authentication token instead of storing it on the device. This enhances security, as these cookies are inaccessible to anything other
I think it is a bit strange to talk about "key changes" in the docs, we are only documenting the current behavior of the product

2024-03-13 08:49 UTC, WimJongeneel commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, `com.mendix.webui.HybridAppLoginTimeOut` that determines the validity of the authentication token. If no value is set, the token remains valid for one year.
Do we truly use a `Hybrid` setting for this?

2024-03-13 09:32 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, `com.mendix.webui.HybridAppLoginTimeOut` that determines the validity of the authentication token. If no value is set, the token remains valid for one year.
Yes, Its name is confusing as we don't support Hybrid anymore, but it is already used for the native auth token and we wanted our solution to be backwards compatible so we didn't want to add a new one.

2024-03-13 09:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +The key change is that Mendix now use HTTPOnly cookie to hold the authentication token instead of storing it on the device. This enhances security, as these cookies are inaccessible to anything other
I mentioned that because we already support the old behaviour for the existing applications.

2024-03-13 09:34 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
what about changing it to `get_session_data` request?

2024-03-13 10:18 UTC, WimJongeneel commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, `com.mendix.webui.HybridAppLoginTimeOut` that determines the validity of the authentication token. If no value is set, the token remains valid for one year.
Oke :)

2024-03-13 10:19 UTC, WimJongeneel commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
Yes, or you could mention that it is during the client startup.

2024-03-13 13:07 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +The key change is that Mendix now use authentication tokens to reinitialize the session  instead of the previous approach of keeping the users logged in for a longer period.
Removed.

2024-03-13 13:07 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +The key change is that Mendix now use HTTPOnly cookie to hold the authentication token instead of storing it on the device. This enhances security, as these cookies are inaccessible to anything other
Removed. They can just go and check the refguid9

2024-03-13 13:11 UTC, WimJongeneel approved these changes

2024-03-14 10:14 UTC, MarkvanMents requested changes
Hi Enas, @EnasAbdelrazek 

The new doc, **Session Management** looks a good description of what is technically going on, but I'm not sure how to use it as a customer. As a customer, I don't call an API to sign in, I just set security to production and set up some users in my app. Does this new session management apply then? How do I pass this `useAuthToken` parameter in this case?

I've also made a few comments below about supporting customers who are not yet on 10.9.

Probably best to discuss this over Slack, or have a quick meeting if you have any questions.

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/auto-committed-objects.md
> -* **Long-lived sessions** – offline-first progressive web apps use [long-lived sessions](/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app/#sessions) with longer session timeou
Do we need to keep this in for customers who are on older versions? E.g. 10.6 MTS?

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> -| **reloginReason** | Runtime | Used to let the client know that a relogin reason should be displayed on the sign in page | `/` | until user closes their browser (session cookie) |  `true` |
Should this still be documented for customers using versions before 10.9? E.g. 10.6 MTS.

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken**<sup><small>2</small></sup> | Runtime | Used to hold the authentication token | `/` | until the authentication token expires |  `true` |
Are these new in 10.9? Then we need to indicate when they were introduced.

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken**<sup><small>2</small></sup> | Runtime | Used to hold the authentication token | `/` | until the authentication token expires |  `true` |
Footnote 2 isn't relevant here.
```suggestion
| **useAuthToken** | Runtime | Used to let the runtime know whether to generate an authtoken or not | `/` | until user closes their browser (session cookie) |  `true` | 
| **authtoken** | Runtime | Used to hold the authentication token | `/` | until the authentication token expires |  `true` | 
```

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken**<sup><small>2</small></sup> | Runtime | Used to hold the authentication token | `/` | until the authentication token expires |  `true` |
Also `useAuthToken` and `authtoken` have inconsistent camelcase for `token`/`Token`. I think that it should be consistent, otherwise customers will type it wrongly.

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app.md
> -For more information on sessions and how to customize the timeout, see the [Session Duration](/refguide/tricky-custom-runtime-settings/#session-duration) section of the *Advanced Custom Settings in M
The link to information on the `session-duration`  has not been carried forward into the new **Session Management** doc, so it is more difficult to find for customers using earlier versions of Mx10.

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app.md
> +Offline-first PWAs use an authentication token by default to keep the session active while users are not actively working in the app.
Do we still need to talk about long-lived sessions for customers using older versions, e.g. 10.6 MTS

2024-03-14 10:14 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
I think an example would be useful here. Or at least a link to the document which describes calling the new API.

And if the user has to call the API directly, perhaps a link to the API spec as well?

2024-03-14 10:18 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +{{< figure src="/attachments/refguide/runtime/session.png" alt="The Session Management Flow between client and the runtime." >}}
Could you add the link to plantuml which creates this image. The it is easier to update it, if necessary? Thanks.

2024-03-14 11:20 UTC, MarkvanMents commented on content/en/docs/refguide/mobile/building-efficient-mobile-apps/offlinefirst-data/auto-committed-objects.md
> +    * It is useful to keep in mind that a session may expire on the server if the end-user uses the app while there is no network condition. When this happens, the Mendix Client attempts to create a
Should this be 
```suggestion
    * It is useful to keep in mind that a session may expire on the server if the end-user uses the app while there is no network connection. When this happens, the Mendix Client attempts to create a new session automatically when the device sends a request to the Mendix Runtime.
```

2024-03-14 13:56 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken** | Runtime | Used to hold the authentication token—*introduced for apps created in Mendix version 10.9.0 and above* | `/` | until the authentication token expires |  `true` |
**Inconsistent Camel Case**
You have two cookies: `useAuthToken` and `authtoken`. The `token` part has inconsistent case. It should be one of

- `useAuthToken` and `authToken`
- `use Authtoken` and `authtoken`

Otherwise developers will make mistakes when using them.

2024-03-14 13:57 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, [`com.mendix.webui.HybridAppLoginTimeOut`](/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut) that determines how long the authentication token is vali
According to our documentation, the token never expires if this value isn't set.
https://docs.mendix.com/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut

2024-03-14 14:04 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +This feature maintains backward compatibility, so we preserve the previous session management approach for existing applications. For upgraded offline applications, whether native or web, that curren
I'm afraid I don't understand what we are saying here?
The best I can do is:
* this feature mimics the long-lived sessions for offline first apps
* old apps will continue to use the long-lived sessions mechanism even if they are upgraded to 10.9
* all apps created in 10.9 will have the same behavior as offline-first apps did before
* you can turn off this behavior if you are writing custom java or javascript using login2 by setting the value of the `useAuthToken` parameter to `false`.

I'm not sure I've understood it correctly, so I think it could do with some clarification once I'm sure I understand it.

2024-03-14 14:04 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +{{% todo %}}Need a link to login2 api documentation{{% /todo %}}
Where is the spec for the login2 API - would be good to link to it.

2024-03-14 14:09 UTC, MarkvanMents requested changes
I've now made some changes based on what @WimJongeneel told me over Slack.
Can you have a look at my remaining questions and review [the changes I've made](https://github.com/mendix/docs/pull/7431/files/e575c1a4a82e9822fe01197a25a2dea2c05c5a92..5c93f3ca950486a07133128a9e54b2f1dc288230).
Thanks.

2024-03-18 05:29 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +If you are using standard Mendix sign in flows in version 10.9.0 or above, the authentication token will be generated automatically. If you have custom JavaScript or Java sign in code, you will have
offline applications, whether native or web, that use the old login AP, are now supposed to use the new authentication token system by default.

2024-03-18 05:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +This feature maintains backward compatibility, so we preserve the previous session management approach for existing applications. For upgraded offline applications, whether native or web, that curren
Old offline PWA apps will continue to use the long-lived sessions mechanism, but upgraded apps will use the new system by default if they already use the old API but developers can disable this default system if they use the login2 and set useAuthToken param to false. 

Online apps can use the new login API to enable the authentication token system.

2024-03-18 05:39 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +This feature maintains backward compatibility, so we preserve the previous session management approach for existing applications. For upgraded offline applications, whether native or web, that curren
Since our solution is backwards compatible, existing offline PWA apps will continue to use the previous long-lived sessions mechanism and the existing native apps should continue to work as the previously old system of authentication tokens, in which the authentication token is generated during login and stored on the device.

Upgraded offline apps (native or web) will use the new system by default if they already use the old API; however, developers can disable this default system if they use the login2 and set useAuthToken param to false.

Online apps can use the new login2 API to enable the authentication token system.

2024-03-18 05:59 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
It is part of the client API docs which should be at the release of 10.9

2024-03-18 06:00 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +{{< figure src="/attachments/refguide/runtime/session.png" alt="The Session Management Flow between client and the runtime." >}}
[Plantuml link](https://www.plantuml.com/plantuml/uml/bPB1Rjim44Jl-efjV7M3n4Lww2687TSd5oZgzbOWeAMnj91Cgikb7AVklnTI65iA3BGv211dXyCt8E-y6j6mhP9tMc0BMbS1kPXzuaksjH6pfRL9ornSiDczgvpGQ5UmecVm-1LWKz3lP9ggauMp6grN7s_ci-b9Nl4JQ7ALJ4NSRkZffAFdUXA5yrap9ndaUJ07wbMvdrK1oP8tMB95VpwQVlXyivYTPhq-_VbN8yefryPg3tKeluRvazIdCLryWStuaUuhXjKBCfxIxlTuni3zBLZbBMW5QI2TtNU_D9fVBoQBUM9IvSOeOinn7Nr9J7z_UnkLJxHqELlQiHOKFAP1Y--kXANkgg0Gyb1IHoe1IJol7z10UBCdBT06o9XIWL5qWeVtxEoOl6b0tEPqUcRKh8t7c7vQCZQZdN3SqaByY13jg9z3gNCbmr-UAoBjg_9AEVGX-X_QS-WST5eWBRleVkcOFwOC5RG5xW1pMCXB9Js22LGO3GQ4mRFDpp1VzYcUwLjaNxksFMinsDDo9uV3eVtUrDLi53A8AemdFDOioFvnUusfE6FTazjqQnEqEBLboygcugTpVLbV-lr_lIJ3g-VQKo9Vr_yEDWlRwYy0)

2024-03-18 06:04 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +{{% todo %}}Need a link to login2 api documentation{{% /todo %}}
It should be released at 10.9

2024-03-18 06:06 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
// Example with useAuthToken set to true
Here is an example:
mx.login2("fred", "fred's unguessable password", true, function() {
    console.log("success");
}, function() {
    console.log("wrong password");
});

2024-03-18 08:37 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, [`com.mendix.webui.HybridAppLoginTimeOut`](/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut) that determines how long the authentication token is vali
Now, the authtoken is stored as an HttpOnly cookie, and we set the expiry value for the cookie using this timeout, but if it is not specified, we set a default value of one year.

2024-03-18 08:38 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken** | Runtime | Used to hold the authentication token—*introduced for apps created in Mendix version 10.9.0 and above* | `/` | until the authentication token expires |  `true` |
What do you mean by using them?

2024-03-18 08:44 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +{{< figure src="/attachments/refguide/runtime/session.png" alt="The Session Management Flow between client and the runtime." >}}
Sorry, missed that you had already put it in an earlier comment:
https://github.com/mendix/docs/pull/7431#issuecomment-1991684567

2024-03-18 11:55 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken** | Runtime | Used to hold the authentication token—*introduced for apps created in Mendix version 10.9.0 and above* | `/` | until the authentication token expires |  `true` |
I was thinking that the customer might have to read/write these cookies themselves if they are writing custom login functionality. But if it is all handled then it is only internal developers who have to make sure they type them correctly!

(Would still be nice if they were consistent 😀)

2024-03-18 11:58 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, [`com.mendix.webui.HybridAppLoginTimeOut`](/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut) that determines how long the authentication token is vali
So do I need to change the information in https://docs.mendix.com/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut
![image](https://github.com/mendix/docs/assets/35492184/b39ca583-5348-4dd5-8005-0838f83ce604)

2024-03-18 12:01 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +{{% todo %}}Need a link to login2 api documentation{{% /todo %}}
OK - do you have a link I could use, or do I need to ask nearer the time?

2024-03-18 12:03 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +If you are using standard Mendix sign in flows in version 10.9.0 or above, the authentication token will be generated automatically. If you have custom JavaScript or Java sign in code, you will have
This doesn't seem to be the same as what you say here: https://github.com/mendix/docs/pull/7431#discussion_r1527863770

> existing offline PWA apps will continue to use the previous long-lived sessions mechanism and the existing native apps should continue to work as the previously old system of authentication tokens,

2024-03-18 12:10 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +
Does it make it clearer with an example?
```suggestion
The `login2` API allows you to pass the parameter `useAuthToken`. The value `true` enables the authentication token, `false` disables it. If the login action passes `true` to the runtime, the runtime adds an HttpOnly cookie `useAuthToken` indicating that an authentication token should be generated during the client startup.

For example
```java {linenos=false}
mx.login2("fred", "fred's unguessable password", true, function() {
    console.log("success");
}, function() {
    console.log("wrong password");
});
```
```

2024-03-18 12:10 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
Should we add this example, as I suggest here: https://github.com/mendix/docs/pull/7431/files#r1528426157

2024-03-18 12:42 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +We now support a new core client login API, `login2`, that allows you to pass an extra parameter, `useAuthToken`. You can pass `true` to enable authentication token or `false` to disable it. When the
No, It should be part of the client API docs https://apidocs.rnd.mendix.com/10/client/mx.html or https://apidocs.rnd.mendix.com/10/client-react/mx.html depending on the used client.

2024-03-18 12:43 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **authtoken** | Runtime | Used to hold the authentication token—*introduced for apps created in Mendix version 10.9.0 and above* | `/` | until the authentication token expires |  `true` |
No, they are only accessible by the runtime.

2024-03-18 12:43 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, [`com.mendix.webui.HybridAppLoginTimeOut`](/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut) that determines how long the authentication token is vali
Yes, you can change it.

2024-03-18 12:45 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +{{% todo %}}Need a link to login2 api documentation{{% /todo %}}
https://apidocs.rnd.mendix.com/10/client/mx.html or https://apidocs.rnd.mendix.com/10/client-react/mx.html depending on the used client.

2024-03-18 12:46 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +If you are using standard Mendix sign in flows in version 10.9.0 or above, the authentication token will be generated automatically. If you have custom JavaScript or Java sign in code, you will have
I updated the comment. I hope now it is more clear.

2024-03-18 12:47 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +
This example will be included in the client API docs https://apidocs.rnd.mendix.com/10/client/mx.html or https://apidocs.rnd.mendix.com/10/client-react/mx.html depending on the used client.

2024-03-19 07:38 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +
OK - won't put it in this document as well, but have a link to the API spec.

2024-03-19 07:58 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +There is a custom runtime setting, [`com.mendix.webui.HybridAppLoginTimeOut`](/refguide/custom-settings/#commendixwebuiHybridAppLoginTimeOut) that determines how long the authentication token is vali
Added in 665c3a223a0b228da6615c1543f4974082af6797

2024-03-19 14:20 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +This feature maintains backward compatibility, so we preserve the previous session management approach for existing applications. For upgraded offline applications, whether native or web, that curren
Updated description in 48e98aeb43628fb87fe0628d302dfa9a7a21036e

2024-03-19 14:20 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +If you are using standard Mendix sign in flows in version 10.9.0 or above, the authentication token will be generated automatically. If you have custom JavaScript or Java sign in code, you will have
Updated description in 48e98aeb43628fb87fe0628d302dfa9a7a21036e

2024-03-19 14:20 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +{{% todo %}}Need a link to login2 api documentation{{% /todo %}}
Added,

2024-03-19 14:57 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +If you are using an app created in a version below 10.9.0, then long-lived sessions will be used for offline-first apps. See the [Sessions](/refguide/mobile/introduction-to-mobile-technologies/progre
Online apps below 10.9.0 should work with KeepAlive approach check this https://docs.mendix.com/refguide7/tricky-custom-runtime-settings/#21-web-client-settings

2024-03-19 14:57 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +If you want to generate authentication tokens in your online app, you will have to use custom JavaScript or Java sign in code using the `login2` API.
It is not correct to mention java action here. login2 is a client API.

2024-03-20 06:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +For offline-first apps using standard Mendix sign in with version 10.9.0 or above, the authentication token will be generated automatically.
```suggestion
For offline-first apps using the client API `login`, with version 10.9.0 or above, the authentication token will be generated automatically.
```

2024-03-20 06:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +If you want to generate authentication tokens in your online app, you will have to use custom JavaScript or Java sign in code using the `login2` API.
```suggestion
If you want to generate authentication tokens in your online app, you have to use the new client API `login2`. 
```

2024-03-20 06:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +The `login2` API allows you to pass the parameter `useAuthToken`. The value `true` enables the authentication token, `false` disables it. If the login action passes `true` to the runtime, the runtime
```suggestion
The `login2` API allows you to pass the parameter `useAuthToken`. The value `true` enables the authentication token, `false` disables it. If the login action passes `true` to the runtime, the runtime adds an HttpOnly cookie `useAuthToken` indicating that an authentication token should be generated during the client startup. 
```

2024-03-20 06:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +You could also provide end-users a "remember me" option so they can decide whether they want to be remembered or not.
```suggestion
You could also model your login page to provide end-users with a "remember me" option so they can decide whether they want to be remembered or not.
```

2024-03-20 06:33 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
```suggestion
This feature maintains backward compatibility, so we preserve the previous session management approaches for unupgraded applications.

Upgraded offline-first applications, that currently use the client API, `login`, are now supposed to use the new authentication token system by default. If you do not want your offline-first app to create an authentication token, you can disable the use of authentication tokens by using the new API, `login2`, but setting the `useAuthToken` parameter to `false`.

New offline-first applications created in version 10.9.0 or above will use the authentication token approach if they enable it.
```

2024-03-20 07:08 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/custom-settings/_index.md
> +| <a id="commendixwebuiHybridAppLoginTimeOut" href="#commendixwebuiHybridAppLoginTimeOut">com.<wbr>mendix.<wbr>webui.<wbr>HybridAppLoginTimeOut</a> | Determines how many minutes your token will remai
I don't think there is a need to change this since the one-year is related to the authtoken cookie expiry, not this timeout.

2024-03-20 07:27 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/custom-settings/_index.md
> +| <a id="commendixwebuiHybridAppLoginTimeOut" href="#commendixwebuiHybridAppLoginTimeOut">com.<wbr>mendix.<wbr>webui.<wbr>HybridAppLoginTimeOut</a> | Determines how many minutes your token will remai
If no value is set the token will expire after one year.

2024-03-20 08:46 UTC, MarkvanMents requested changes
Hi @EnasAbdelrazek 
Thanks for the suggestions, I've committed all but one of them where I have asked some questions about it as I find the language needs to be clearer.

I have also made one further suggestion based on your comments, can you see if that looks OK?

Thanks for working with me on this. I think we will end up with something which clearly states what is going on and how the customer should approach it, so the extra work is going to be worth it in the end.

Mark

2024-03-20 08:46 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +If you are using an app created in a version below 10.9.0, then long-lived sessions will be used for offline-first apps. See the [Sessions](/refguide/mobile/introduction-to-mobile-technologies/progre
So should we say 
```suggestion
If you are using an app created in a version below 10.9.0, then long-lived sessions will be used for offline-first apps. See the [Sessions](/refguide/mobile/introduction-to-mobile-technologies/progressive-web-app/#sessions) section of *Progressive Web App* for more information.

Online apps in Mendix versions below 10.9.0 have a different approach, using the [EnableKeepAlive](/refguide/tricky-custom-runtime-settings/#session-duration) setting to send keep alive requests from the client.
```

2024-03-20 08:46 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
This is the bit which I find is confusing.

> we preserve the previous session management approaches

I think it is clear that we are talking about apps in 10.9 and above so I don't think we should talk about "preserving" anything. My understanding is that in 10.9 and above they have to use the new mechanism. If you talk about preserving things it sounds like they don't have to do anything.

> are now supposed to use the new authentication token system by default

This doesn't tell me what I need to know. "supposed to" could mean "you should change it but you can leave it as it is if you want", or it could mean "the runtime assumes that this is the case". Saying it is "by default" suggests that this is implemented automatically and that you have to disable it if you don't want it. But you go on to say that it can be disabled and in the next paragraph you say that it has to be enabled (implemented?) by the developer.

*Can you make this clearer as to whether this is something that has to be implemented by the developer and that the login2 API gives them the ability to do this, or whether this is something that is being implemented "by default" for offline-first applications (i.e. by making an app offline-first this mechanism is automatically applied)*

2024-03-20 08:53 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/custom-settings/_index.md
> +| <a id="commendixwebuiHybridAppLoginTimeOut" href="#commendixwebuiHybridAppLoginTimeOut">com.<wbr>mendix.<wbr>webui.<wbr>HybridAppLoginTimeOut</a> | Determines how many minutes your token will remai
But we need to change something as now it says 

> If no value is set the token will never expire

So should we put it in the description instead?

```suggestion
| <a id="commendixwebuiHybridAppLoginTimeOut" href="#commendixwebuiHybridAppLoginTimeOut">com.<wbr>mendix.<wbr>webui.<wbr>HybridAppLoginTimeOut</a> | Determines how many minutes your token will remain valid before re-authenticating using your full credentials.  If no value is set the token will expire after One year *(Mendix version 10.9.0 and above)* or never expire *(Mendix versions below 10.9.0)*. |  |
```

I prefer this as the default (i.e what will happen if you don't explicitly set `commendixwebuiHybridAppLoginTimeOut`) as it is clearer to me. But I can make the change I've suggested if you think that is more accurate.

2024-03-20 14:22 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
Here I am referring to apps that have not been upgraded we kept our runtime backwards compatible (can handle both approaches).

2024-03-20 14:24 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
`New offline-first applications created in version 10.9.0 or above will use the authentication token approach if they enable it`.
 we expect they will use the new login2 client API but if they use login It will also utilize the token system by default as mentioned before as they are offline.

2024-03-20 14:25 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/custom-settings/_index.md
> +| <a id="commendixwebuiHybridAppLoginTimeOut" href="#commendixwebuiHybridAppLoginTimeOut">com.<wbr>mendix.<wbr>webui.<wbr>HybridAppLoginTimeOut</a> | Determines how many minutes your token will remai
I don't think `never` is a valid default value, so I prefer your suggestion.

2024-03-21 11:02 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
Here we are talking about apps which are above 10.9 (either new or upgraded) not ones below, so I don't think we should be talking about preserving anything. If they are below 10.9 they will be using an older runtime version.

And if they are below 10.9 they will be calling the login API, so they will get the behaviour that they had with the login API and I don't think we need to mention that either.

I don't understand how using the old API in an app above 10.9 can also utilize the token system by default - in the past they had to set up long-lived sessions if they were using the login API.

As far as I can see there are three situations we need to describe clearly:
1) If you are using Mx above 10.9 and new login2 this is what happens
2) If you are using Mx below 10.9 and old login this is what happens
3) If you use Mx above 10.9 and old login you should change to using login2 but it will carry on working as 2) if you don't.

I think that all this "maintains backward compatibility" is not relevant as we are mixing up talking about two different APIs and two different Mendix versions.

2024-03-21 11:05 UTC, MarkvanMents commented
One other question:
Can users with Mendix versions below 10.9 use the login2 call - or will it only work for Mendix 10.9?
If so, will this be included in the https://apidocs.rnd.mendix.com/10/client-react/mx.html#.login documentation. And will this documentation also tell users which version of login they should be using?

2024-03-21 11:07 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
and
4. You cannot use login2 with Mendix versions below 10.9

2024-03-21 15:20 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
- Regarding backward compatibility: If end users haven't updated their apps on their devices, but the runtime is a newer version, it should still function correctly to accommodate both old and new clients.
- Upgraded `offline` apps that utilize login API, they will use the new token system, as we internally call the new API login2 with authToken enabled.
- New apps (whether offline or online) created with version 10.9 or above now have two options: login2 or login. If they opt to use the authentication token system, they should use login2 and set the useAuthToken parameter to whatever value they prefer. However, as previously mentioned, if they used the login API and are offline, it will act login2 with the useAuthToken parameter set to true.

2024-03-21 15:37 UTC, EnasAbdelrazek commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
I updated the suggestion.

2024-03-22 06:48 UTC, MarkvanMents approved these changes
@EnasAbdelrazek 
Thanks for that final update. I think everything is much clearer now and I understand what is going on - which means our customers should too.

Sorry it has taken so long to get to this place - hope I wasn't being too stupid in not understanding it earlier - but I'm very happy that we now have documentation which is really clear.

The technical side of the documentation was always very clear - great use of the UML to explain the interaction of the client and the server. I think our customers should be very happy with this update.

Mark

2024-03-22 06:48 UTC, MarkvanMents commented on content/en/docs/refguide/runtime/session-management.md
> +In Mendix version 10.9.0 and above, login should always support authentication tokens.
That looks great. I now understand it and the documentation is also clear.
I'll commit your suggestion and now I think we are ready to publish.

2024-03-22 07:43 UTC, EnasAbdelrazek commented
@MarkvanMents No worries, I understand your confusion, it is a bit complicated, but the good news is we were able to come up with clear documentation. Thanks for your feedback as well! :)

2024-03-27 08:34 UTC, merged