Update automate-mendix-deployment-on-microsoft-windows.md
mendix/docs pull request #7480
Opened 2024-03-20 07:34 UTC by yatindrakulkarni-mendix

Add New-MxApp and Set-MxLogLevel cmdlets documentation

2024-03-20 07:34 UTC, yatindrakulkarni-mendix commented
Needs review by @jveldhuizen

2024-03-22 07:57 UTC, jveldhuizen requested changes

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to create a new Mendix app with an app folder and basic Settings.yaml file. Below is the command to create new Mendix app.
The second sentence repeats in fact the first sentence, right? (the following script exampe demonstrates how to vs. below is the command to)
```suggestion
The following script example demonstrates how to create a new Mendix app with an app folder and basic Settings.yaml file.
```

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +$APP_NAME = ‘Name of Mendix app’
```suggestion
$APP_NAME = 'Name of Mendix app'
```

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +$APP_NAME = ‘Name of Mendix app’
```suggestion
$APP_NAME = 'Name of Mendix app'
```

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to set log level for all nodes of a log subscriber at once. Below is the command to set log level for all log nodes.
```suggestion
The following script example demonstrates how to set a log level for all log nodes of a log subscriber at once.
```

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +$SubscriberName = ‘Log subscriber name of the app’
```suggestion
$SubscriberName = 'Log subscriber name of the app'
```

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +$Level = ‘Log level which needs to be assigned’
```suggestion
$Level = 'Log level which needs to be assigned'
```

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +$SubscriberName = ‘Log subscriber name of the app’
We now have all variants of upper casing in our variable names. Can you make that consistent? I think the best one is in example 4.2 (`$mxJson`, `$targetFile`). Can you use that format (camelCase) in example 4.1 as well and in these new examples?

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to set log level for all nodes of a log subscriber at once. Below is the command to set log level for all log nodes.
Can you add some text about the fact that this is only applicable when you have defined your own log subscribers in the `Settings.yaml` file?

2024-03-22 07:57 UTC, jveldhuizen commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to create a new Mendix app with an app folder and basic Settings.yaml file. Below is the command to create new Mendix app.
Can you add some text about the fact that you still need to extend the `Settings.yaml` file with database and other settings before the app can really start?

2024-03-26 09:51 UTC, yatindrakulkarni-mendix commented
Hi @jveldhuizen 
I have addressed all review comments. Please let me know if any changes required.

2024-03-26 10:28 UTC, jveldhuizen approved these changes

2024-03-28 09:40 UTC, MarkvanMents commented
Approved by Jonathan so marking all his comments as resolved.

2024-03-28 10:36 UTC, MarkvanMents requested changes
Hi Yatindra (@yatindrakulkarni-mendix)
Looks good. I've just made one suggestion for a change. Does it make things clearer without changing the sense?
Let me know if it looks good and I can approve and publish.
Thanks for the PR
Mark

2024-03-28 10:36 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to create a new Mendix app with an app folder and basic Settings.yaml file. You still need to extend Settings.yaml file with database settings and a vali
I would change "with an app folder". Should we say what the folder is going to be called once the app is created?
My initial suggestion would be:

```suggestion
The following script example demonstrates how to create a new Mendix app in its own folder and with a basic `Settings.yaml` file. You still need to extend the `Settings.yaml` file with database settings and a valid Java path before the app can really start.
```

2024-03-28 11:48 UTC, yatindrakulkarni-mendix commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to create a new Mendix app with an app folder and basic Settings.yaml file. You still need to extend Settings.yaml file with database settings and a vali
I would suggest to keep 'with its own folder' instead of 'in its own folder' as we are not creating any other files apart from folder with an app name and Settings.yaml file inside that folder.

2024-03-28 12:18 UTC, MarkvanMents approved these changes
Thanks for the PR Yatindra. I'm approving it.
Can I publish it immediately?

2024-03-28 12:18 UTC, MarkvanMents commented on content/en/docs/developerportal/deploy/on-premises-design/ms-windows/automate-mendix-deployment-on-microsoft-windows.md
> +The following script example demonstrates how to create a new Mendix app with an app folder and basic Settings.yaml file. You still need to extend Settings.yaml file with database settings and a vali
OK, that makes sense.
I won't commit this change and I'll approve the PR.

2024-03-28 12:27 UTC, yatindrakulkarni-mendix commented
Hi @MarkvanMents 
I have added the changes. Could you please merge the PR and publish?

2024-03-28 12:47 UTC, merged