Add section for new Foreign Key Constraints runtime setting
mendix/docs pull request #7543
Opened 2024-04-03 09:11 UTC by passalaqua

This setting will be added in Mendix 10.10.

2024-04-04 09:05 UTC, MarkvanMents requested changes
Thanks for the PR, Augusto.
I've made some additions and asked a couple of questions below. Can you review them?
Thanks.

2024-04-04 09:05 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +### 3.15 Foreign Key Constraints {#database-fkc}
Should we refer to this in https://docs.mendix.com/refguide/data-storage/#fkc?

2024-04-04 09:05 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +Default: *Yes* (for projects created with Mendix versions 10.6.0 and above)
What happens when upgrading from, say, 9.24 or 10.4 to 10.10? Is there a default set - what will it be?

2024-04-04 09:05 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +This option was added in Mendix version 10.10. From Mendix versions 10.6 to 10.9, foreign key constraints are always used. Mendix versions below 10.6 do not use foreign key constraints.
Are my additions here accurate?

2024-04-04 12:27 UTC, passalaqua commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +This option was added in Mendix version 10.10. From Mendix versions 10.6 to 10.9, foreign key constraints are always used. Mendix versions below 10.6 do not use foreign key constraints.
No. It really depends on which version the project was originally created. See the reply regarding Defaults.

2024-04-04 12:28 UTC, passalaqua commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +Default: *Yes* (for projects created with Mendix versions 10.6.0 and above)
If it was not created in 10.6 or above, then it is not enabled. That means upgrades should not affect the previous value.

Do you have a suggestion on how to write this without making it verbose and confusing?

2024-04-04 14:42 UTC, MarkvanMents requested changes
Thanks for the answers.
I've made a couple of suggestions for changes. Can you look at them and commit them if they look OK, or let me know if they still aren't clear/correct.
Mark.

2024-04-04 14:42 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +This option was added in Mendix version 10.10. From Mendix versions 10.6 to 10.9, foreign key constraints are always used. Mendix versions below 10.6 do not use foreign key constraints.
OK, so we should put it back to this?
```suggestion
This option was added in Mendix version 10.10.
```

2024-04-04 14:42 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +Default: *Yes* (for projects created with Mendix versions 10.6.0 and above)
Can we just say the following?
```suggestion
Default: *depends on the version of Mendix used to create the app:*

* *Yes* for apps created with Mendix versions 10.6.0 and above
* *No* for apps created with Mendix versions below 10.6
```
I assume that once they get to 10.10 they will be able to turn it on/off independently of which version was used to create the app.

2024-04-05 08:38 UTC, passalaqua commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +This option was added in Mendix version 10.10. From Mendix versions 10.6 to 10.9, foreign key constraints are always used. Mendix versions below 10.6 do not use foreign key constraints.
I think putting it back is better, indeed.

2024-04-05 08:40 UTC, passalaqua commented on content/en/docs/refguide/modeling/app-explorer/app/app-settings/_index.md
> +Default: *Yes* (for projects created with Mendix versions 10.6.0 and above)
Yes, turning on/off is precisely the point of exposing this setting.

2024-04-05 11:17 UTC, dahfjkg commented
Passed technical review

2024-04-05 11:24 UTC, MarkvanMents approved these changes
Ready for publication with Mendix 10.10
Thanks for the PR, Augusto.

2024-05-01 07:56 UTC, merged