No iiot for makers
mendix/docs pull request #7557
Opened 2024-04-05 08:23 UTC by StefanKellerSiemens

Please assign this Pull Request to Mark van Ments

With this pull request we have removed the complete documentation of the IIot for Makers case.
We have added a new chapter regarding the new Siemens Insights Hub API Authenticator and some details for the index.html patches.

2024-04-08 11:49 UTC, MarkvanMents requested changes
Hi Stefan,
Thanks for the PR.
I have proofread it in this commit: https://github.com/mendix/docs/pull/7557/commits/4e75b4f66b75a77cfd4b229d5a27d4aeb241f07b
And I have a couple of questions/comments.
Please can you let me know if everything is OK and I will mark this as ready for future release once the module is released in the Marketplace.
Yours
Mark

2024-04-08 11:49 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mindsphere-api-only.md
> +
Is this out of date. It seems to be repeating the information given in the paragraphs above.

2024-04-08 11:49 UTC, MarkvanMents commented on content/en/docs/partners/siemens/mindsphere/mindsphere-api-only.md
> +Storing the *Client Secret* inside the app is, from a security perspective, not a good idea. A better approach is to use a local environment variable. Create a user-specific environment variable with
From Mendix 10.9 there is a solution to this where you can have a "Private" constant.
https://docs.mendix.com/refguide/configuration/#constants
But most customers will be using a version below 10.9, unfortunately.

2024-04-09 09:22 UTC, StefanKellerSiemens commented on content/en/docs/partners/siemens/mindsphere/mindsphere-api-only.md
> +
That is not out of date, it explain in more detail what needs to be provided for each constant.
But yes, it is a little bit duplicated and we could maybe align it to have it only at one place.

2024-04-09 09:23 UTC, StefanKellerSiemens commented on content/en/docs/partners/siemens/mindsphere/mindsphere-api-only.md
> +Storing the *Client Secret* inside the app is, from a security perspective, not a good idea. A better approach is to use a local environment variable. Create a user-specific environment variable with
Good hint, we can maybe consider this for the next release. Right now we like to be compatible with the latest V9 LTS.

2024-04-11 12:55 UTC, MarkvanMents approved these changes
Thanks for the PR, Stefan.
Approving and will wait to hear from you about release date and link to the Marketplace component.

2024-05-13 09:53 UTC, MarkvanMents commented
@StefanKellerSiemens -
This looks ready to go now.
I have one question: in the [deployment guide](https://docs.mendix.com/developerportal/deploy/deploying-to-mindsphere/) we have a reference to **Insights Hub IIot for Makers**.
![image](https://github.com/mendix/docs/assets/35492184/9c1a696b-d959-464a-9018-0f5acd517a09)
Should we get rid of this as well, or do we need to keep it for now?

2024-05-13 10:24 UTC, StefanKellerSiemens commented
Yes, please get rid of this.

2024-05-13 14:11 UTC, MarkvanMents commented
Merge requested over email.

2024-05-13 14:11 UTC, merged