Create documentation for subqueries in OQL
mendix/docs pull request #7572
Opened 2024-04-08 14:48 UTC by dahfjkg

Requires technical review

2024-04-09 09:27 UTC, basdebakker requested changes

2024-04-09 09:27 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
> +`( sub_oql_query )` specifies another OQL query from which data must be retrieved. This will be the source for the current query. The subquery must be placed within parentheses. See [OQL Subqueries](
We should also add `( sub_oql_query )` to the JOIN syntax below.

2024-04-09 09:27 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
Should this have a `weight`?

2024-04-09 09:27 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +Similarly to subquery in `SELECT`, it can contain references to other entities and subqueries in `FROM` by alias if there is one and by name otherwise. Attributes can only be referenced by name.
I don't think this is true.

2024-04-12 09:37 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
They are currently in alphabetical order as none of these pages have a weight. So it will appear here:
![image](https://github.com/mendix/docs/assets/35492184/ec3aaa75-ea70-42d3-8f45-cb638c8740c4)
You can add weights if you want them in a different order.

2024-04-16 07:51 UTC, basdebakker requested changes

2024-04-16 07:51 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
> +In cases when an entity name or a subquery is used, `JOIN` condition (i.e. `ON` constrait) is mandatory to use.
typo: constrai[n]t

2024-04-16 07:51 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
That would be a non-obvious place. Better add some weights then.

2024-04-17 12:12 UTC, dahfjkg commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
Then I guess we can reorder all pages here. What would be the right order then? Something like this?
```
OQL Select Clause
OQL From Clause
OQL Where Clause
OQL Group by Clause
OQL Limit Clause
OQL Order by Clause
OQL Subqueries
```

2024-04-17 14:53 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
> +In cases when an entity name or a subquery is used, `JOIN` condition (i.e. `ON` constranit) is mandatory to use.
Typo:
```suggestion
In cases when an entity name or a subquery is used, `JOIN` condition (i.e. `ON` constraint) is mandatory to use.
```

2024-04-18 08:23 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
> +`( sub_oql_query )` specifies another OQL query from which data must be retrieved. This will be the source for the current query. The subquery must be placed within parentheses. See [OQL Subqueries](
Ok, this can be resolved.

2024-04-18 08:25 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
Order by comes before limit in the syntax, so I would do that here as well. Looks good otherwise.

2024-04-18 08:25 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +Similarly to subquery in `SELECT`, it can contain references to other entities and subqueries in `FROM` by alias if there is one and by name otherwise. Attributes can only be referenced by name.
This can be resolved.

2024-04-18 08:26 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-from-clause.md
> +In cases when an entity name or a subquery is used, `JOIN` condition (i.e. `ON` constrait) is mandatory to use.
This can be resolved.

2024-04-18 08:41 UTC, dahfjkg commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
done

2024-04-18 08:47 UTC, basdebakker commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +---
Thanks, this can be resolved.

2024-04-18 08:49 UTC, basdebakker commented
> Requires technical review

I approve this PR.

2024-04-19 17:06 UTC, MarkvanMents reviewed
Hi Pavel and Bas (@dahfjkg and @basdebakker)
Thanks for the PR and letting me know when the technical review was finished.

It is a long time since I used SQL, so I am reading this as a pretty novice user, but I found some confusion around the attributes that the "FROM" clause could reference.

I've asked some questions and made some comments, but it may be just my lack of knowledge rather than a failing in the documentation.

Please let me know if you have any questions, and let me know when you are happy with the PR and I'll approve it ready for version 10.10.

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/_index.md
> +```sql {linenos=false}
I've removed all the line number from the OQL/SQL as they weren't needed.

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-where-clause.md
>  title: "OQL Where Clause"
We don't mention subclauses anywhere in this document. Do we need something?

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-group-by-clause.md
>  title: "OQL Group by Clause"
We don't mention subclauses here HAVING is one of the things mentioned in the subclauses documentation - do we need to mention it here?

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +A subquery is a nested SELECT query inside a SELECT query. Subqueries can be used in a:
I was confused at first because it isn't just in the `SELECT` clause - but I realized that all the clauses below are part of a SELECT query.
I wondered if it would be clearer if we said something like:
```suggestion
A subquery is a nested SELECT query inside certain clauses of a SELECT query. Subqueries can be used in a:
```

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +* `HAVING` clause combined with `GROUP BY`
Subclauses are not explicitly mentioned in some of the related documentation. Should they be, or is this document sufficient?

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +Entities and subqueries in from, on the other hand, can only be referenced by alias, if there is one. They can be referenced by name only if there is no alias.
I don't understand this at all. Probably because there are two 'FROM' clauses, one in the main select and one in the subclause and the two paragraphs are referring to different ones.

Looking at the example, above, does it mean the following, or have I totally misunderstood?
```suggestion
The subquery can refer to attributes of the entities and subqueries in the `FROM` clause of the subquery. Those attributes can be referenced only by name, not by alias (for example `Module.Address` in the example above).

Entities and subqueries in the main `FROM` clause of the main`SELECT` query, on the other hand, (for example `ZipCode` in the example above) must be referenced by alias, if there is one. If no alias is set, they can be referenced by name. 
```
Perhaps the example could include a clearer example of using something from the `FROM` clause of the subquery?

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +In contrast with subquery in a `SELECT` clause, a subquery in a `FROM` clause cannot contain references to other entities and subqueries in `FROM`.
Again I find this confusing as there are two `FROM` clauses and I'm not sure which ones we are referring to.

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +### 4.1 Scalar Subqueries
I think the section titles and the introductory sentence should match to make navigation easier. So either we change this to **Value Subqueries** or we change the initial introduction to say **—as a scalar and as multiple rows**.

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +### 4.2 Multirow Subqueries
Or **Collection Subqueries** (see above).

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +A subquery can also be used in a `HAVING` clause similarly to how it is used in a `WHERE` clause. The difference is that only attributes and aggregates from the query can be referred to in the `HAVIN
```suggestion
A subquery can also be used in a `HAVING` clause in a similar way to a `WHERE` clause. The difference is that only attributes and aggregates from the query can be referred to in the `HAVING` subquery.
```

2024-04-19 17:06 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +title: "OQL Subqueries"
Is this new in 10.10? In this case, I think we should say which version it was introduced so we don't get questions from customers using 10.6 MTS.

2024-04-22 11:07 UTC, dahfjkg commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +title: "OQL Subqueries"
This was always somewhat supported, and some customers actually use it, but we fixed a couple of major bugs in 10.10

2024-04-22 11:38 UTC, dahfjkg commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +* `HAVING` clause combined with `GROUP BY`
I moved the document to `oql-expressions`. Documentation pages for Where and Group By already contain the link to OQL Expressions page

2024-04-22 11:39 UTC, dahfjkg commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +Entities and subqueries in from, on the other hand, can only be referenced by alias, if there is one. They can be referenced by name only if there is no alias.
I tried to make it clearer

2024-04-23 09:48 UTC, MarkvanMents approved these changes
Looks great.
I just have one question about whether you want to adjust the order of the OQL Expressions, but it is definitely OK as it is so doesn't need to be changed.

I'll commit the two typo/proofreading suggestions I've made and this looks ready to go.
Thanks for all your work on this.
Mark

2024-04-23 09:48 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-subqueries.md
> -weight: 70
OQL expressions are now in alphabetical order. Just checking that this is what you wanted
![image](https://github.com/mendix/docs/assets/35492184/0a609eb2-3435-4b97-b47c-c29ba87f49ef)

2024-04-23 09:48 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-subqueries.md
> +The subquery can refer to attributes of other entities and subqueries in the main query's `FROM` clause. Those attributes can be referenced only by name, not by alias (In the example above, attribute
Typo:
```suggestion
The subquery can refer to attributes of other entities and subqueries in the main query's `FROM` clause. Those attributes can be referenced only by name, not by alias (In the example above, attribute `ZipCodeValue` has an alias in the main query, but it is referenced by name in the subquery).
```

2024-04-23 09:48 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-expressions/oql-subqueries.md
> +In contrast with subquery in a `SELECT` clause, a subquery in a `FROM` clause cannot contain references to other entities and subqueries declared in the main query's `FROM` clause.
Typo
```suggestion
In contrast with a subquery in a `SELECT` clause, a subquery in a `FROM` clause cannot contain references to other entities and subqueries declared in the main query's `FROM` clause.
```

2024-04-23 09:49 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +* `HAVING` clause combined with `GROUP BY`
Great - thanks.

2024-04-23 09:50 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/data-sets/oql/oql-subqueries.md
> +title: "OQL Subqueries"
Then I don't think we need to mention anything here. I'll resolve this.

2024-05-01 07:56 UTC, merged