Document the Optimize bundle settings 10.10
mendix/docs pull request #7601
Opened 2024-04-15 12:12 UTC by EnasAbdelrazek

2024-04-17 07:23 UTC, WimJongeneel requested changes

2024-04-17 07:23 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/menus/edit-menu/preferences-dialog.md
> +This setting is visible and effective when the React client is enabled. By default, It's already enabled to reduce the size of the generated app bundle and speeds up the bundling process by diabling
diabling -> disabling.

I think we should mention that the bundling speed is relevant for local deployment speed, I don't think that is directly clear for all users. 

"Source maps are files that map code from its transformed state back to its original form" might also be a bit too in-dept from a low-code perspective, I would just mention that source maps are used for debugging the bundled code.

2024-04-22 06:45 UTC, WimJongeneel approved these changes

2024-04-25 09:05 UTC, ConnorLand approved these changes

2024-05-01 08:23 UTC, merged