Add documentation for new Strict Mode
mendix/docs pull request #7605
Opened 2024-04-16 11:04 UTC by brambrink

In 10.10, we will introduce a new Strict Mode. This PR adds the documentation for it.

2024-04-18 14:41 UTC, brambrink commented
The introduction of this feature has been postponed to 10.11

2024-04-24 11:51 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/app-explorer/security/app-security/strict-mode.md
> +## 3 Disallowing Save button on Page Templates
"Disallowing Save button on Layouts"

2024-04-24 11:52 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/app-explorer/security/app-security/_index.md
> +In React Client, Strict Mode mode will help making your app secure, even if the access rules are not set up correctly. For more information, see the [Strict Mode](/refguide/strict-mode/) page.
"more secure" instead of just "secure"

2024-04-24 11:53 UTC, WimJongeneel commented on content/en/docs/refguide/modeling/app-explorer/security/app-security/strict-mode.md
> +Strict Mode ensures that entities are accessible only in the ways defined within your model — through microflows, nanoflows, widgets, or pages — by restricting certain Client APIs.
Should be more along the lines of "Strict Mode will help ensuring that entities ..."

2024-04-24 11:54 UTC, WimJongeneel requested changes
see comments

2024-04-24 13:25 UTC, EnasAbdelrazek commented
I believe we should mention the improvement made to the save action button rather than just showing the restriction of placing a save button on layouts. Additionally, we have to mention an alternative solution of placing a save button on the layouts like using a snippet.

2024-04-25 08:08 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/security/app-security/_index.md
> +In React Client, Strict Mode mode will help making your app secure, even if the access rules are not set up correctly. For more information, see the [Strict Mode](/refguide/strict-mode/) page.
Without strict mode, when the access rules are not set up correctly, your app is not secure. So I think it is better to use "secure" instead "more secure". If you set up your access rules correctly Strict Mode is not as relevant.

2024-04-25 08:20 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/security/app-security/strict-mode.md
> +## 3 Disallowing Save button on Page Templates
Fixed

2024-04-25 08:20 UTC, brambrink commented on content/en/docs/refguide/modeling/app-explorer/security/app-security/strict-mode.md
> +Strict Mode ensures that entities are accessible only in the ways defined within your model — through microflows, nanoflows, widgets, or pages — by restricting certain Client APIs.
Fixed

2024-04-26 07:15 UTC, EnasAbdelrazek approved these changes

2024-04-26 11:24 UTC, WimJongeneel approved these changes

2024-05-17 14:45 UTC, brambrink commented
Hi, letting you know that this feature is delayed and will be released in 10.12 instead of 10.11

2024-05-28 05:10 UTC, ConnorLand approved these changes

2024-05-28 08:07 UTC, MariaShaposhnikova commented
Hi @brambrink, thanks for the PR! Can we add information on where and how to enable and set up the strict mode? I think we need some guidance on where to find it.

2024-05-29 08:02 UTC, brambrink commented
Thanks Connor and Maria! I've added instructions how to enable strict mode to the docs

2024-06-25 10:24 UTC, merged