Improvements for Security doc
mendix/docs pull request #7640
Opened 2024-04-23 13:51 UTC by MariaShaposhnikova

2024-04-23 13:51 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +## 4 App Authentication {#authentication}
Added this from the Eval guide

2024-04-23 13:53 UTC, MariaShaposhnikova commented
Hi @MarkvanMents, could you review the changes when you have time please? I am trying to make the Security doc more clear on what aspects it includes in general, not just in the SP in the App Explorer.

2024-04-24 12:58 UTC, MarkvanMents reviewed
Hi Maria,
This is going to be a big improvement - leading customers in to doing security well will help them understand it better.

I've made a lot of comments (many on paragraphs you didn't touch) so please come back to me if you have any questions or concerns.

I've made suggestions where small changes would be an improvement. There is one paragraph that I find confusing-it isn't wrong but I think could be rewritten from a different angle. Let me know if you want to know more about my thinking there.

I think it would be useful for Karuna to look at this as all her components are related to security and it would be good to make sure we are aligned.

But overall a huge improvement, I think.

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Security in Mendix has several aspects. One aspect is that your app is a project to work on in the backend, develop it and collaborate on it with your colleagues as a team. Yet you may want to contro
I know what you are saying here, but I think it could be more direct. Is it OK if I make a suggestion to rewrite it?

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Security in Studio Pro does not include scanning files that end-users upload or download from your application for viruses and malware. For more information, see the [Scanning Uploaded Files for Mali
No - this is security in the Mendix app, not Studio Pro. It is talking about an end-user uploading a file (an image or some other data the company needs to process).
```suggestion
Security in Mendix apps does not include scanning files that end-users upload or download from your application for viruses and malware. For more information, see the [Scanning Uploaded Files for Malicious Content](/howto/security/best-practices-security/#scanning-for-malicious-content) section in *How to Implement Best Practices for App Security*. 
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +You can also set app authentication and add SSO modules to your app using Mendix Marketplace. For more information, see [App Authentication](#authentication) section below.
```suggestion
You can also set app authentication and add SSO modules to your app using modules from the Mendix Marketplace. For more information, see the [App Authentication](#authentication) section below. 
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +## 2 Security in Studio Pro {#security-in-studio-pro}
Would this be better as something like
**App Security**
As it is about securing the app?
You set it up within Studio Pro, but you are not actually making Studio Pro any more secure.

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  If you want full security, you need to explicitly give access to forms, entities, microflows, and workflows before someone can access them. By default, no one can access anything. To make it easier t
```suggestion
If you want your app to be fully secure, you need to explicitly give access to forms, entities, microflows, and workflows before end-users can access them. When you turn production security on, the default is that no one can access anything. To make it easier to create prototypes and demos there are security levels that require less security than are needed for a production system.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  At the level of an app some global settings can be specified: the security level, the administrator account and whether or not to allow anonymous access.
```suggestion
At the level of an app some global settings can be specified: the security level, the administrator account, and whether or not to allow anonymous access.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  An end-user in a Mendix application has one or more user roles. These roles can be assigned from within the client when creating or editing a user. User roles are at the level of an app and can be ed
```suggestion
An end-user in a Mendix application has one or more user roles. These roles can be assigned from within the client when creating or editing an end-user. User roles are at the level of an app and can be edited in [App Security](/refguide/app-security/).
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  A user role is a combination of module roles. A user that signs into the system gets the access rights of all of their user roles and indirectly to the module roles that are contained by those user r
```suggestion
A user role is a combination of module roles. An end-user that signs into the system gets the access rights of all of their user roles and indirectly to the module roles that are contained within those user roles.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +For example, you have an app with two modules: System and ProjectManagement (PM). The PM module has three module roles: TeamMember, TeamLeader and Administrator. And let us say that in this case, we
```suggestion
Say, for example, you have an app with two modules: System and ProjectManagement (PM). The PM module has three module roles: TeamMember, TeamLeader, and Administrator. In this case, you do not need to make a distinction between team leaders and administrators so you only need two user roles. You define those two user roles and assign module roles to them. The table below shows which module roles are contained within the user roles. Note that you always need at least the User role in the System module.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  | User Role 'TeamMember' | User Role 'TeamLeader' |
Would it be clearer here to say
```suggestion
| Module Roles for User Role 'TeamMember' | Module Roles for User Role 'TeamLeader' |
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  Per entity you can specify who can read or write what members (attributes and associations) under what circumstances. Using XPath constraints you can express powerful security behavior (for example,
Don't really like "Per entity" as a formula. How about
```suggestion
You can specify for each entity who can read or write which members (attributes and associations) under what circumstances. Using XPath constraints you can express powerful security behavior (for example, "an employee can only see orders created by the department they are a part of").
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  Per entity you can specify who can read or write what members (attributes and associations) under what circumstances. Using XPath constraints you can express powerful security behavior (for example,
(Similarly for "per page" in the next paragraph!)

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
>  See [Entity Access](/refguide/module-security/#entity-access).
You could combine these if you wanted - I think having the link indication will encourage people to click it!
```suggestion
A combination of entity access and a page access is necessary because entities can also be accessed from microflows and custom widgets. Furthermore, you can express more advanced security through [entity access](/refguide/module-security/#entity-access).
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +## 4 App Authentication {#authentication}
Good idea - do we need to get someone from Collaboration or Engagement to review this as well?

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +If you would like to invite your colleagues to build the app, you can manage **Team** in Developer Portal. Only team members who are invited to your app can access your app (as a project to collabora
I think this is worth turning around so we define what team roles are first, then why they are different from end-user roles.

```suggestion
If you want to invite your colleagues to build your app, you can manage the **Team** in the Developer Portal. Only team members who are invited to your app can access it (as a project to collaborate on). You can assign app roles to them. These team member roles define what they can access and change in the app in the backend while developing the app and are different from end-user roles which define what users can access in a running app. For more information, see [Team](/developerportal/general/team/) in the *Developer Portal Guide*.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +The Mendix platform provides you with three approaches to the authentication of users of your app. Depending on your preference you can include modules in your app from the Mendix Marketplace for eac
```suggestion
The Mendix platform provides you with three approaches to the authentication of end-users of your app. Depending on your preference you can include modules in your app from the Mendix Marketplace for each of these approaches.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +The first approach is to have "local" authentication in your app. With this approach, the users of your app are managed by your app. Users are authenticated against their password that is also stored
```suggestion
The first approach is to have "local" authentication in your app. With this approach, the end-users of your app are managed by your app. End-users are authenticated against their password that is also stored within the app. In this approach the app is self-supporting and independent of any existing IAM (Identity and Access Management) infrastructure. The Mendix Marketplace also provides modules to also add multi-factor authentication to the local login process.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +A second approach is to have users authenticate via the Mendix Identity Provider through single sign on ([SSO](/appstore/modules/mendix-sso/)) using their Mendix credentials. This is the default opti
I think we are trying to move customers away from this method. Perhaps you could get @Karuna-Mendix to discuss this with Jaap and work out how best to present this.

```suggestion
A second approach is to have end-users authenticate via the Mendix Identity Provider through single sign on ([SSO](/appstore/modules/mendix-sso/)) using their Mendix credentials. This is the default option for developers who deploy their application to the Mendix Cloud.
```

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +The third approach is to integrate your app with a third-party Identity Provider (IDP) external to your app.
All the rest of the paragraphs in this section are related to this third approach (which should, perhaps be the second approach) - so perhaps we should make the sub-bullets in a bulleted list, or make headings for each of the three approaches to make it clearer?

And IDP should be IdP - I'll confirm with Karuna and put it into the terminology guide!

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Needless to say, the [SAML SSO](/appstore/modules/saml) module can be used with any IDP that supports the SAML 2.0 protocol. For example, this module module can be used with IDPs such as Okta, Micros
Should we put the SAML SSO link in the previous paragraph on the first mention, rather than here?

And I think that the example list is more something for the Evaluation Guide than here - we only need to specify "any IdP that supports the SAML 2.0 protocol" here, I think.

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Mendix also supports the OAuth protocol with the platform-supported [OIDC SSO](/appstore/modules/oidc/) module. OIDC/OAuth can be used in consumer facing applications to achieve single sign-on with i
I think we can miss out the example list of identity providers here as well.

2024-04-24 12:58 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Mendix applications that are deployed to SAP BTP can have SSO with SAP’s IDP. Mendix provides a platform supported XSUAA connector to implement this federation in your Mendix app.
```suggestion
Mendix applications that are deployed to SAP BTP can have SSO with SAP's IDP. Mendix provides a platform supported [XSUAA connector](/appstore/modules/sap/sap-xsuaa-connector/) to implement this federation in your Mendix app. 
```

2024-04-30 08:06 UTC, Karuna-Mendix requested changes

2024-04-30 08:06 UTC, Karuna-Mendix commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +The third approach is to integrate your app with a third-party Identity Provider (IDP) external to your app.
- I agree with @MarkvanMents . It would be nice to have three subsections for three approaches. 
- IDP should be IdP. I'll update terminology guide.
- multi-factor authentication (MFA)

2024-04-30 08:06 UTC, Karuna-Mendix commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Mendix also supports the OAuth protocol with the platform-supported [OIDC SSO](/appstore/modules/oidc/) module. OIDC/OAuth can be used in consumer facing applications to achieve single sign-on with i
It is mentioned as 'SAML' in the Marketplace and in the Docs as well; not SAML SSO. I think we can provide the cross link as [SAML](/appstore/modules/saml).

2024-04-30 12:25 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +A second approach is to have users authenticate via the Mendix Identity Provider through single sign on ([SSO](/appstore/modules/mendix-sso/)) using their Mendix credentials. This is the default opti
@Karuna-Mendix , this comment was automatically marked as resolved, because I accepted the suggestion, but the question is still open. Is it correct that we are trying to move customers away from the second approach?

2024-04-30 13:13 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Mendix also supports the OAuth protocol with the platform-supported [OIDC SSO](/appstore/modules/oidc/) module. OIDC/OAuth can be used in consumer facing applications to achieve single sign-on with i
I've got rid of the example and changed "SAML SSO"  to "SAML".

2024-04-30 13:16 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Needless to say, the [SAML SSO](/appstore/modules/saml) module can be used with any IDP that supports the SAML 2.0 protocol. For example, this module module can be used with IDPs such as Okta, Micros
I've incorporated both suggestions.

2024-04-30 13:18 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +The third approach is to integrate your app with a third-party Identity Provider (IDP) external to your app.
I've introduced sub-sections and changed the spelling. I will confirm with Karuna if we need to get rid of the second approach.

2024-04-30 13:19 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +## 2 Security in Studio Pro {#security-in-studio-pro}
I named it **App Security Set Up in Studio Pro** for now. Or shall I shorten it to **App Security**?

2024-04-30 13:44 UTC, MariaShaposhnikova commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Security in Mendix has several aspects. One aspect is that your app is a project to work on in the backend, develop it and collaborate on it with your colleagues as a team. Yet you may want to contro
I tried, but I am not sure if I made it any better. Do you mean to rewrite the whole intro or just this paragraph?

2024-05-03 10:19 UTC, MarkvanMents reviewed
Hi Maria,
I've made some suggestions to simplify the introduction. Let me know if you have any questions.

2024-05-03 10:19 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Security in Mendix has several aspects. One aspect is that your app is a project to work on in the backend, develop it and collaborate on it with your colleagues as a team. Yet you may want to contro
I'll make some suggestions - but feel free to adapt or ignore them if you think they aren't an improvement.
```suggestion
Security in Mendix has several aspects which are all covered on this page.

Firstly, you may be working as a team to create the app. You will want to control who is on the team and what each member can do. This is managed in the Developer Portal. For more information, see [Building an App as a Team](#team) section below. 
```

2024-05-03 10:19 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +Another aspect is controlling what end-users can access in the running app. If you want different end-users to see different parts of your running application and you want to prevent unauthorized acc
```suggestion
Secondly, you will want to control who can access your app once it is running. You will want to prevent unauthorized access to your running application. You may also want different end-users to see different parts of the app , so access to individual pages, data, and microflows can be limited to specific end-users. This is managed from within Studio Pro. For more information, see [App Security Set Up in Studio Pro](#security-in-studio-pro) section below.
```

2024-05-03 10:19 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +The last aspect is that you can also set app authentication and add SSO modules to your app using modules from the Mendix Marketplace. For more information, see the [App Authentication](#authenticati
This isn't really another aspect - it is just an extension of app security.

```suggestion
There are different ways in which you can set up app authentication, including local authentication and using a federated IdP to provide single sign-on (SSO). For more information, see the [App Authentication](#authentication) section below. 
```

2024-05-03 12:20 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/app-explorer/security/_index.md
> +## 4 App Authentication {#authentication}
Probably not worth it for now - perhaps see if we get any feedback once it is published.

2024-06-07 10:10 UTC, merged