OpenAI: Function Calling
mendix/docs pull request #7704
Opened 2024-05-07 07:09 UTC by liamsommer-mx

The OpenAI connector now supports "function calling" that can be used within the ChatCompletions operations. The documentation was updated to guide developers and reflect the technical changes. A new subpage for function calling was added to explain the concept.

2024-05-07 14:36 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Description`      | A description of what the function does, used by the model to choose when and how to call the function. This attribute is optional. |
If the model is using this to choose when to call the function how can it be optional?

2024-05-07 14:41 UTC, rik-bos commented on content/en/docs/appstore/modules/openai/function-calling.md
> +2. Based on the user prompt and the available functions, the model can intelligently decide whether to call one or more functions. If so, the content of the assistant's response will be a stringified
"whether to call one or more functions" --> "that it's needed to call one or more functions"

2024-05-07 14:41 UTC, rik-bos commented on content/en/docs/appstore/modules/openai/function-calling.md
> +1. Invoke the chat completions API with a user prompt and a list of available functions with expected input parameters.
functions --> functions (microflows)

2024-05-07 14:41 UTC, rik-bos commented on content/en/docs/appstore/modules/openai/function-calling.md
> +3. Parse the string into JSON and call the function with its input parameters.
function --> function (microflow)

2024-05-07 14:41 UTC, rik-bos commented on content/en/docs/appstore/modules/openai/function-calling.md
> +    * e.g., extractBirthday(String birthday), or getSqlQuery(String query)
Let's not including SQL query as an example since that may cause OQL like expectations. Let's not do that for now.

2024-05-07 14:41 UTC, rik-bos commented on content/en/docs/appstore/modules/openai/function-calling.md
> +    * e.g., createTicket(String subject)
Let's include a recommendation that if the function manipulates things (e.g. creating a ticket), user validation to confirm the action is recommended to prevent unexpected behavior

2024-05-07 14:41 UTC, rik-bos commented on content/en/docs/appstore/modules/openai/function-calling.md
> +### 1.2 Function calling with the OpenAI Connector {#openai-connecor}
Can we include that the microflows run in the original user session, and have access to `$currentUser` for applying user specific data / security constraints?

2024-05-07 15:18 UTC, tinaengel-mx commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Description`      | A description of what the function does, used by the model to choose when and how to call the function. This attribute is optional. |
It's optional in the OpenAI API, so we made it optional for our connector as well. If you give the function a very descriptive name, it may work just fine without the description
https://platform.openai.com/docs/api-reference/chat/create#chat-create-tools

2024-05-08 08:07 UTC, MarkvanMents requested changes
Hi @liamsommer-mx @tswarmerdam-mx @rik-bos and @tinaengel 
I have proofread this (see https://github.com/mendix/docs/pull/7704/files/42ee9160a7271837badebcd25909d4603067b1aa..d329670943e699c9e1e7c052711a6ae0a68c197c) but I have a few questions which I've asked in the comments. Can you look into these and get back as I feel that there a couple of things which need to be clarified.

Thanks
Mark

2024-05-08 08:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Temperature`    | Decimal                                               | optional                      | This can be used to control the randomness of the output. The value should be a decimal be
Since the default value is 1.0 I think it would be better to have a higher value than one as your example of a higher value. Otherwise you are saying that the default is more random than setting it explicitly to be more random.

2024-05-08 08:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
In what way relevant? Which one takes priority, first or last?

2024-05-08 08:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +Function calling is supported for all chat completions operations by adding the optional input parameter [FunctionCollection](#functioncollection). Functions in Mendix are essentially microflows that
This seems to contradict what we say before. If the connector calls the function with the parameters how can we check that the model hasn't hallucinated parameters before the function is called?

2024-05-08 08:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Description`      | A description of what the function does, used by the model to choose when and how to call the function. This attribute is optional. |
Thanks for explaining. Should we put something into the docs to explain this?

2024-05-08 08:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +
I don't find it clear which bits are done by the OpenAI connector and what the customer needs to do. I've tried to clarify it, based on my understanding of the rest of the document.

Here, and in the diagrams below, it seems that the OpenAI connector does everything and the customer just has to make a single call.

However, you also say that "the model may hallucinate parameters, so they should be validated before the function is actually called". But if the connector is calling the function directly you can't validate the parameters before you call the function - you can only validate the parameters inside the function after it has been called.

2024-05-08 08:10 UTC, liamsommer-mx commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
It's not really about priority, but rather the chronological order. So your last messages are the most current, while the first ones are "older". The model responds to the last message, but takes into account the older ones (like a normal conversation).

2024-05-08 08:14 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +        * If it calls a function, the content of the assistant's response will be a stringified JSON object containing the input parameters of the function as described in the request. Note that the
What is the response if it doesn't call a function?
What is the format of the JSON object? I can't see an example anywhere and so I'm not sure how I know which function was called, what the parameters were, and what the function returned before the AI parses it and sends it back.

The examples below do not return the JSON to the customer, they just return a natural language response ("The status of ticket 123 is in progress") so I'm not sure why the customer needs to know about the JSON or what they can do to get it.

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
it's a chronological order, from oldest message to most recent message being the last one

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/function-calling.md
> +
you can build validation inside the fucntion microflow. Even though the function microflow is called by the OpenAI connector, the function microflow is implemented by the developer and could some validation as the first action

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Description`      | A description of what the function does, used by the model to choose when and how to call the function. This attribute is optional. |
I would phrase it in a way that we recommend adding a description even though it is optional

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/function-calling.md
> +
@MarkvanMents can we go back to the structure with the 4 steps, which align with the process mentioned in the official openai docs? https://platform.openai.com/docs/guides/function-calling

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/function-calling.md
> +        * If it calls a function, the content of the assistant's response will be a stringified JSON object containing the input parameters of the function as described in the request. Note that the
the format of the JSON object was provided as part of the request so it depends on the input of your function microflow.
This is just some background information for developers who want to know how function calling works under the hood. Developers might need to handle the json object and the function call themselves if they are using the advanced operations, which we generally don't recommend. If they are using with/without history operations, we handle everything inside the connector

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Temperature`    | Decimal                                               | optional                      | This can be used to control the randomness of the output. The value should be a decimal be
Agree, can we just remove the "like 0.8"?

2024-05-08 08:25 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/function-calling.md
> +Function calling is supported for all chat completions operations by adding the optional input parameter [FunctionCollection](#functioncollection). Functions in Mendix are essentially microflows that
It can be validated inside the function microflow which needs to be implemented by the developer

2024-05-08 09:54 UTC, MarkvanMents requested changes
I've made some suggestions. Feel free to commit them if they look good. Or make different changes if you can think of something better.

@tinaengel would it be worth having a quick call about the high-level section at the beginning of `function-calling` as I think I am misunderstanding something.

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +
I find the four steps confusing for the Mendix documentation as the developer is only interested in step 1 and step 4 while steps 2 and 3 are hidden by the wrapper. 
So my idea is to have four steps, but make it clear that steps 2 and 3 are done automatically by the connector.

I'm happy to go for another structure, but I think it should be clear what is done by the developer and what is done by the connector.

As it was it just described what the openai API does, which the developer can get from the openai docs.

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +        * If it calls a function, the content of the assistant's response will be a stringified JSON object containing the input parameters of the function as described in the request. Note that the
I'm finding this confusing. Are we describing here how function calls work, or just how the OpenAI connector does it for you?

If developers are doing the calls themselves, then we should be able to point them at the OpenAI documentation. I think we should focus here on how the non-advanced calls work, or at least make it clear what the differences are. Here we are mixing the two things up which, as someone who doesn't know the internal workings of the connector, is confusing.

Additionally, we don't anywhere describe what JSON we create for a request, we only describe entities where the information is held, so the developer isn't going to know the structure.

I think that if we mention the JSON objects we should have a bit more information about them?

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Description`      | A description of what the function does, used by the model to choose when and how to call the function. This attribute is optional. |
How about
```suggestion
| `Description`      | A description of what the function does, used by the model to choose when and how to call the function. This attribute is optional, but Mendix suggests using it to help the model choose the correct function. |
```

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Name`    | The name of the function to call.                            |
Would it be a good idea to add something here to support what you answered below:
```suggestion
| `Name`    | The name of the function to call. The model will use this to help identify which function to call where it has a choice. |
```

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Temperature`    | Decimal                                               | optional                      | This can be used to control the randomness of the output. The value should be a decimal be
@tinaengel - is this OK?
```suggestion
| `Temperature`    | Decimal                                               | optional                      | This can be used to control the randomness of the output. The value should be a decimal between 0.0 and 2.0. The default value is 1.0. Higher values make the output more random, while lower values make it more focused and deterministic. Note: very high values for temperature (>1.7) may give unexpected results and even internal server errors. |
```

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Temperature`            | Decimal                                               | optional                      | This can be used to control the randomness of the output. The value should be a de
```suggestion
| `Temperature` | Decimal | optional | This can be used to control the randomness of the output. The value should be a decimal between 0.0 and 2.0. The default value is 1.0. Higher values make the output more random, while lower values make it more focused and deterministic. Note: very high values for temperature (>1.7) may give unexpected results and even internal server errors. |
```

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
Would it be worth making this explicit?
```suggestion
* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In the case of multiple historical messages the latest message has more influence than earlier ones.
```

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +        * If it calls a function, the content of the assistant's response will be a stringified JSON object containing the input parameters of the function as described in the request. Note that the
In any case, I think we should be clearer where the validation takes place:
```suggestion
        * If it calls a function, the content of the assistant's response will be a stringified JSON object containing the input parameters of the function as described in the request. Note that the model may hallucinate parameters, so they should be validated within the function before being used.
```

2024-05-08 09:54 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Arguments`| The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined b
If the function is being called automatically you can't always validate before it is called - so making the recommendation more generic.

```suggestion
| `Arguments`| The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments before using them. |
```

2024-05-08 10:17 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +        * Parse the string into JSON and call the function with its input parameters. The microflow runs in the original user's session and `$currentUser` can for example be used to apply security co
```suggestion
        * Parse the string into JSON and call the function (microflow) with its input parameters. The microflow runs in the original user's session and `$currentUser` can for example be used to apply security constraints.
```

2024-05-08 10:18 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +3. Parse the string into JSON and call the function with its input parameters.
https://github.com/mendix/docs/pull/7704/files#r1593792140

2024-05-08 10:23 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +Function calling is a very powerful capability, but this also introduces potential risks. Function microflows do not respect any entity access rules for the current end-user. Make sure to retrieve an
```suggestion
Function calling is a very powerful capability, but this also introduces potential risks. Function microflows do not respect any entity access rules for the current end-user. You can use `$currentUser` to help you ensure you retrieve and return only information that the end-user is allowed to view, otherwise confidential information may be visible to the current end-user in the assistant's response.
```

2024-05-08 10:23 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +### 1.2 Function calling with the OpenAI Connector {#openai-connecor}
https://github.com/mendix/docs/pull/7704/files#r1593797902

2024-05-08 10:52 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Name`    | The name of the function to call.                            |
It also functions as UUID in other specialization so this is not correct. In my opinion the suggestion to use the description is sufficient

2024-05-08 10:52 UTC, tinaengel-mx commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
How about: "If multiple messages are present, they should be ordered chronologically."

2024-05-08 11:28 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
Great suggestion - I'll put it here and commit it.

```suggestion
* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. If multiple messages are present, they should be ordered chronologically.
```

2024-05-08 11:35 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +| `Name`    | The name of the function to call.                            |
OK - I'll resolve this and not commit the suggestion.

2024-05-08 11:43 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
```suggestion
* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. If multiple messages are present, they should be ordered chronologically.
```

2024-05-08 11:44 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/_index.md
> +* `ChatCompletionsSession_AddMessage` is used to attach the historical messages to the `ChatCompletionsSession`. The content of such a message corresponds to a system, assistant, or user prompt. In t
Wrong suggestion committed. Now committed the right suggestion 54022f4b47c43a6cfe084a809db1977edd88fae5

2024-05-08 13:14 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +2. Invoke the chat completions API again and let the model answer your initial prompt with the new information provided by the function.
Does the developer even have to do this? From the examples in section 1.4 it looks like the connector does this step too and basically the function call is a single-step process.

2024-05-08 13:27 UTC, tinaengel commented on content/en/docs/appstore/modules/openai/function-calling.md
> +2. Invoke the chat completions API again and let the model answer your initial prompt with the new information provided by the function.
for with and without history operations, this is handled by the connector. For advanced it isn't

2024-05-08 13:48 UTC, MarkvanMents commented on content/en/docs/appstore/modules/openai/function-calling.md
> +2. Invoke the chat completions API again and let the model answer your initial prompt with the new information provided by the function.
OK, I'll remove this and just have it in the detailed description.

2024-05-08 14:54 UTC, MarkvanMents approved these changes
Thanks for all your input and help.
This looks great now, so I'll publish it immediately.

2024-05-08 15:00 UTC, merged