Generating a Software Bill of Materials
mendix/docs pull request #7712
Opened 2024-05-10 09:19 UTC by grootjans

2024-05-13 05:43 UTC, tknippenberg commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you make use of a lot of re-usable components such as Widgets, Javascript Action, Appstore modules and more. You want to be aware of what you use in your app, what other c
> Studio Pro does this by generating a Software Bill of Materials (SBOM) based on the standardized CycloneDX format.

At what point does Studio Pro do this?

2024-05-13 05:44 UTC, tknippenberg commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). Required fields are delivered, and fields such as `version`, `descripttion`. To identify the components fro
> Required fields are delivered, and fields such as `version`, `descripttion`.
Should `delivered` be between quotes as well? 
Typo in `descripttion`

2024-05-13 06:16 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you make use of a lot of re-usable components such as Widgets, Javascript Action, Appstore modules and more. You want to be aware of what you use in your app, what other c
I'm leaving it generic here, as I believe we are considering adding a menu option to do this. For now, the method is described in the 'Generating an SBOM' section

2024-05-13 06:18 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). Required fields are delivered, and fields such as `version`, `descripttion`. To identify the components fro
fixed.

2024-05-13 08:01 UTC, tknippenberg commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you make use of a lot of re-usable components such as Widgets, Javascript Action, Appstore modules and more. You want to be aware of what you use in your app, what other c
I thought currently this was only done when making a build in Mendix Cloud, but I might be wrong. If that's the case, perhaps we should remove the 'by Studio Pro' until it's built.

2024-05-13 08:43 UTC, cwesdorp commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you make use of a lot of re-usable components such as Widgets, Javascript Action, Appstore modules and more. You want to be aware of what you use in your app, what other c
Javascript Action by itself is not a re-usable (re-distributable) artefact. For Mendix we have Modules and Widgets, for 3rd party JARs and NPM.

2024-05-13 08:47 UTC, cwesdorp commented on content/en/docs/refguide/general/sbom-generation.md
> +You can generate an SBOM by using [mxbuild](/refguide/general/mxbuild). This generates an `sbom.json` file as part of your deployment folder or your package `.mda`. Bundling the SBOM together with yo
"or you package `.mda`"
Suggests the SBOM is also inside the MDA. That is not the case right?

2024-05-13 08:49 UTC, cwesdorp commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). Required fields are delivered, and fields such as `version`, `description`. To identify the components from
description is not a required field. Only name is. At minimal we provide name, version and purl.

2024-05-13 09:25 UTC, quinntracy commented
@cwesdorp @tknippenberg Is this PR ready for a language review, or should I wait until the existing comments/questions are resolved?

2024-05-13 09:27 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you make use of a lot of re-usable components such as Widgets, Javascript Action, Appstore modules and more. You want to be aware of what you use in your app, what other c
Good point, that does not make complete sense.

2024-05-13 09:30 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). Required fields are delivered, and fields such as `version`, `description`. To identify the components from
What I tried to convey with the sentence is that 
- required fields are delivered
- also other fields such as description, version, purl. These are not required according to the CycloneDX spec

2024-05-14 06:02 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +You can generate an SBOM by using [mxbuild](/refguide/general/mxbuild). This generates an `sbom.json` file as part of your deployment folder or your package `.mda`. Bundling the SBOM together with yo
The SBOM is inside the MDA if you do not specify an alternate location.

2024-05-14 08:28 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you make use of a lot of re-usable components such as Widgets, Javascript Action, Appstore modules and more. You want to be aware of what you use in your app, what other c
I made a slight update, hope this is better.

2024-05-15 09:44 UTC, quinntracy commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). This includes required fields, and information such as `version` and `description`. To identify the compone
> we use the `purl` field.

Who is "we"? Does Mendix or someone else recommend to use this field? Please clarify, as we want to avoid using personal pronouns.

2024-05-15 18:12 UTC, Sakshi-Dhakad requested changes
Added a few comments

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +You can generate an SBOM by using [MxBuild](/refguide/mxbuild/). This generates an `sbom.json` file as part of your deployment folder or your package `.mda`. Bundling the SBOM together with your depl
This isn't true. The SBOM is generated together with the deployment package only when online platform service is used to build a deployment package. Is a SBOM is being created from Studio Pro, it has no link with the .MDA. Would suggest removing the sentence or saying something like the SBOM is based on the current state code/project/branch in Studio Pro
> This generates an `sbom.json` file as part of your deployment folder or your package `.mda`. Bundling the SBOM together with your deployment ensures the components that were present during the build are clearly represented.

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). This includes required fields, and information such as `version` and `description`. To identify the compone
we = Mendix. purl is a common industry wide standard used to identify components

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). This includes required fields, and information such as `version` and `description`. To identify the compone
- SBOM also includes Widgets
- Instead of "Mendix modules", I'd suggest saying "Mendix marketplace modules and widgets" since we only detect the components which are identifiable via marketplace ids to my knowledge.

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you use many reusable components such as Widgets and App Store modules, which make use of components such as Java libraries and node modules. You should know what you use
1. Replace "App Store modules" with marketplace modules since "App store" is old speak and all our public documentation refers to it as marketplace content
2. One can also make use of java libraries and npm packages if they create custom java or javascript in their mendix app. By saying that we only detect the java and npm modules, we are saying that we won't detect direct dependencies which are dragged with the above use case, which isn't correct. So would suggest keeping it very generic or to lay out both use cases which lead to java and npms
3. What are "node modules"? Did you mean to say "npm" modules?

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +Since a full SBOM contains all project details, this is only a partial representation of a full example. To simplify, below is one of the Java libraries that is packaged; a full example would contain
1. Misses widgets, 2. Replace 'appstore' with 'marketplace' and 3. We need to use the same terminology, if we are using npm packages, then I'd suggest we stick to that in all cases. So replace "javascript libraries" with "npm packages"
> Example would contain all App Store modules, java libraries and java script libraries

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +| Mendix Modules | `9.24.14`, `10.4.0` | Mendix Modules in your projects and imported modules as, for instance, from the App Store. This does not include Add-on Modules, Solutions, or Extensions. |
Are all Mendix modules listed in the SBOM? I thought it was only standard marketplace modules that were identified. As a reader, when I read this, I'd also think that my custom modules will be listed here which isn't the case I think.

Additionally, content from both public and private marketplace will be listed in the SBOM. Many customers ask this question during interviews/feedback sessions, would suggest adding that.

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +## 5 Supported Features
Below are a few limitations I'd suggest documenting apart from the ones in the table:
1. Marketplace modules, or modules that are imported directly, so not via the marketplace will not be shown in the SBOM. When they contain Jars or other components that are listed, those components will be present in the SBOM. The module will not be listed as a marketplace module, and (should) not have a package url.
2. Widget packages will only have a App Store version guid when they were downloaded from the marketplace in Studio Pro. For widget packages which are part of a module or imported from the local file system there is no App Store version guid available. 

3. Module, widget, npm dependencies are not available.

2024-05-15 18:12 UTC, Sakshi-Dhakad commented on content/en/docs/refguide/general/sbom-generation.md
> +* [Package URL spec](https://github.com/package-url/purl-spec)
You can also add a reference to software composition. The docs url is going to be - https://docs.mendix.com/control-center/software-composition/

2024-05-17 12:25 UTC, MariaShaposhnikova commented
I've updated labels: removed 10.10 as it is already out and we use version labels for future releases (to not merge too early) and changed Internal/Peer Review to Internal WIP, as this PR is still work in progress.

2024-05-21 10:15 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). This includes required fields, and information such as `version` and `description`. To identify the compone
You should be able to change this into 'the purl field is used' and take out the personal pronoun. Thanks for the clarification Sakshi.

2024-05-21 10:19 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +| Mendix Modules | `9.24.14`, `10.4.0` | Mendix Modules in your projects and imported modules as, for instance, from the App Store. This does not include Add-on Modules, Solutions, or Extensions. |
Though I think it would be good to use 'marketplace modules' in general, I'll have to experiment to see what happens with custom modules.

2024-05-22 05:34 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +You can generate an SBOM by using [MxBuild](/refguide/mxbuild/). This generates an `sbom.json` file as part of your deployment folder or your package `.mda`. Bundling the SBOM together with your depl
the `sbom.json` is generated inside the `mda` by default. For the online services I would expect you specify the `--sbom-output-path=VALUE` parameter, allowing you to generate outside of the `mda`.

2024-05-22 05:36 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). This includes required fields, and information such as `version` and `description`. To identify the compone
I updated the structure, no longer using a personal pronoun.

2024-05-22 05:59 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +The SBOM is based on the [CycloneDX 1.4 JSON format](https://cyclonedx.org/docs/1.4/json/). This includes required fields, and information such as `version` and `description`. To identify the compone
Updated.

2024-05-22 06:01 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +Since a full SBOM contains all project details, this is only a partial representation of a full example. To simplify, below is one of the Java libraries that is packaged; a full example would contain
I've taken it out, as this is just a repetition of previous paragraphs.

2024-05-22 06:08 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +| Mendix Modules | `9.24.14`, `10.4.0` | Mendix Modules in your projects and imported modules as, for instance, from the App Store. This does not include Add-on Modules, Solutions, or Extensions. |
Good point, this was too general and this would not have been reflected. I updated the text.

2024-05-22 06:09 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +* [Package URL spec](https://github.com/package-url/purl-spec)
I can add it with a small PURL as soon as it is published.

2024-05-22 06:15 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +## 5 Supported Features
1. Added a clarification in the table, though let's further update this based on the actual behavior
2. Good point. Though I would really like us to move away from that limitation, that is likely a part of the larger topic of cross-mendix-module dependencies.
3. Modules do not have dependencies at this moment, I would not go with documenting that. NPM dependencies of modules are there (I just checked Nanoflow commons, the NPM dependencies are there), Widget dependencies are likely not present, only their used libraries.

 For now I will add:
he field `dependencies` will contain the dependency relationship from Mendix Marketplace Modules to npm modules and java libraries.

2024-05-22 06:31 UTC, grootjans commented on content/en/docs/refguide/general/sbom-generation.md
> +When building a Mendix app, you use many reusable components such as Widgets and App Store modules, which make use of components such as Java libraries and node modules. You should know what you use
1. Good point, will update
2. Good point, will update
3. Node module is the term for a javascript library, where npm is the 'Node Package Manager', who is able to resolve these dependencies. For clarity sake, let's choose a single term here, given that the SBOM uses the npm package manager as a PURL identifier for now, 'npm modules' is likely the better choice.

2024-05-24 09:31 UTC, merged