update rich text editor document
mendix/docs pull request #7733
Opened 2024-05-14 13:45 UTC by gjulivan

rich text v 3.2.0
(unreleased)

(WC-2479)[https://mendix.atlassian.net/browse/WC-2479]

2024-05-14 14:46 UTC, iobuhov approved these changes

2024-05-15 15:04 UTC, takumagott requested changes
Minor improvement suggestions

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +        * **Auto** – let the rich text decide which position is the best location for the toolbar.
```suggestion
        * **Auto** – automatically determine the best position for the toolbar.
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +        * **Top** – positioned the toolbar at the top of the editor.
```suggestion
        * **Top** – position the toolbar at the top of the editor.
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +        * **Bottom** – positioned the toolbar at the bottom of the editor.
```suggestion
        * **Bottom** – position the toolbar at the bottom of the editor.
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +        * **Inline** – positioned the toolbar floating at the current cursor location when editor is in focus. The toolbar will be hidden until the editable content is selected.
```suggestion
        * **Inline** – position the toolbar floating at the current cursor location when editor is in focus. The toolbar will be hidden until the editable content is selected.
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +        {{% alert color="info" %}}Inline toolbar does not wrap the editor within an iframe, but edits the content in place. Thus, styling that applies to the page, will directly applied to the editor
```suggestion
        {{% alert color="info" %}}Inline toolbar does not wrap the editor within an iframe, but edits the content in place. Thus, styling that applies to the page will be directly applied to the editor's content.{{% /alert %}}
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +    * **Enable quick toolbar** - If selected, quick toolbar will appear in when content is on focus.
```suggestion
    * **Enable quick toolbar** - If selected, quick toolbar will appear when content is on focus.
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +* **Additional stylesheet** - allow user to add additional stylesheet that will be included inside editor's iframe.
```suggestion
* **Additional stylesheet** - allow user to add an additional stylesheet that will be included inside the editor's iframe to apply custom styling.
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +    * User can include additional stylesheet file in theme's folder, and add the filename inside the **Additional stylesheet** input.
```suggestion
    * User can include an additional stylesheet file in the theme folder and add the filename inside the **Additional stylesheet** input. 
```

2024-05-15 15:04 UTC, takumagott commented on content/en/docs/appstore/widgets/richtext/_index.md
> +    * It is also possible to use built-in stylesheet called "_Default_" and "_Dark_", or alternate between them using the expression editor.
```suggestion
    * It is also possible to use built-in stylesheets called "_Default_" and "_Dark_", or alternate between them using the expression editor.
```

2024-05-21 08:28 UTC, gjulivan commented
widget release. 
this PR can be merged whenever review done.
@ConnorLand

2024-05-21 11:34 UTC, ConnorLand approved these changes

2024-05-21 11:48 UTC, merged