[UFC-1171] Add documentation for optional parameters in JavaScript Actions
mendix/docs pull request #7794
Opened 2024-05-24 12:30 UTC by brambrink

In 10.12 we are introducing support for optional parameters in JavaScript Actions. This PR updates the docs for that. Moreover, all screenshots are updated for consistency.

2024-05-24 13:01 UTC, ConnorLand commented
Thanks @brambrink !

2024-05-29 13:40 UTC, Robinfr requested changes
Did a review @brambrink

2024-05-29 13:40 UTC, Robinfr commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +In a JavaScript action's **Code** tab, you can see its parameters' values and handle its implementation. Each parameter has a name (1), type (2), category, description (3),return type (4), and requir
```suggestion
In a JavaScript action's **Code** tab, you can see its parameters' values and handle its implementation. Each parameter has a name (1), type (2), category, description (3), return type (4), and required (5):
```
Missing space

2024-05-29 13:40 UTC, Robinfr commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +If no argument is provided for an optional parameter, it defaults to undefined in the JavaScript Action. You can handle an optional parameter within the JavaScript Action by checking if it is undefin
```suggestion
If no argument is provided for an optional parameter, it defaults to `undefined` in the JavaScript Action. You can handle an optional parameter within the JavaScript Action by checking if it is `undefined`, allowing you to assign a default value or implement custom logic as needed. 
```
Adding some code blocks inline

2024-05-29 13:40 UTC, Robinfr commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +#### 2.2.4 Required
This should be 2.2.5

2024-05-29 13:40 UTC, Robinfr commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +If a parameter is set to required, a value should be selected for that parameter in every Javascript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible
```suggestion
If a parameter is set to required, a value should be selected for that parameter in every JavaScript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible to call the JavaScript Action without any value set for the parameter. This can be useful for flexibility and backward compatibility of JavaScript Actions by allowing new parameters to be added without breaking existing functionality. 
```

2024-05-29 13:40 UTC, Robinfr commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +If a parameter is set to required, a value should be selected for that parameter in every Javascript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible
```suggestion
If a parameter is set to required, a value should be selected for that parameter in every Javascript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible to call the JavaScript Action without any value set for the parameter. This can be useful for flexibility and backward compatibility of JavaScript Actions. 
```
I think the last part doesn't add any more information and can be left out.

2024-05-29 13:53 UTC, brambrink commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +#### 2.2.4 Required
Fixed!

2024-05-29 13:54 UTC, brambrink commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +If a parameter is set to required, a value should be selected for that parameter in every Javascript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible
I agree, removed it

2024-05-30 08:15 UTC, Robinfr requested changes
🐜

2024-05-30 08:15 UTC, Robinfr commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +If a parameter is set to required, a value should be selected for that parameter in every JavaScript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible
```suggestion
If a parameter is set to required, a value should be selected for that parameter in every JavaScript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible to call the JavaScript Action without any value set for the parameter. This can be useful for flexibility and backward compatibility of JavaScript actions.
```

2024-05-30 11:05 UTC, brambrink commented on content/en/docs/refguide/modeling/resources/javascript-actions.md
> +If a parameter is set to required, a value should be selected for that parameter in every JavaScript Action Call. In order to make a parameter optional, set 'required' to 'no'. This makes it possible
Fixed!

2024-05-30 12:51 UTC, Robinfr approved these changes
Approved. Can be checked by technical writers 😄

2024-06-25 09:57 UTC, ConnorLand approved these changes

2024-06-25 10:09 UTC, merged