Documented the Java and JS variable name setting
mendix/docs pull request #7861
Opened 2024-06-07 11:40 UTC by EnasAbdelrazek

It was implemented in 9.23 but we missed adding it to the docs.

2024-06-10 11:23 UTC, MarkvanMents requested changes
@EnasAbdelrazek 
Thanks for the PR, I've reviewed it and have a couple of comments below.
Is it a bug that the variable name is ignored if you use the toolbox to add the action?
Also, I've removed the images as they didn't add much to the documentation - they work in a standard way.
Please can you review and let me know if my changes are OK?
Thanks.

2024-06-10 11:23 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/java-actions.md
> +This setting allows you to give a name to the Java action's return value if a return type is selected. This name is used when you drag the action into a microflow. The default value is set to **Retur
I've changed the wording here as this only works if you drag your action into the flow. If you use the **Toolbox** to add your action, then the variable name is ignored.
Is this a bug? I used 10.10 to test it.

2024-06-10 11:23 UTC, MarkvanMents commented on content/en/docs/refguide9/modeling/resources/java-actions.md
> +The ability to name return variables was added in Mendix version 9.23.0
Added the version when this feature was added. Taken from Release Notes.

2024-06-18 08:13 UTC, EnasAbdelrazek commented on content/en/docs/refguide/modeling/resources/java-actions.md
> +This setting allows you to give a name to the Java action's return value if a return type is selected. This name is used when you drag the action into a microflow. The default value is set to **Retur
Hi Mark, Thanks for your finding. I tested it as well and it appears we missed it. We can improve this later.

2024-06-18 10:20 UTC, MarkvanMents approved these changes
@EnasAbdelrazek 
Thanks for your feedback.
I'm approving now - is it OK to merge immediately?

2024-06-18 12:43 UTC, exec-astraea approved these changes
Hey Enas! I see no issues from the technical side 👍

2024-06-18 12:46 UTC, EnasAbdelrazek commented
Thanks all for reviewing it. Yes @MarkvanMents You can merge it.

2024-06-18 12:49 UTC, merged