GenAI 10.12
mendix/docs pull request #7920
Opened 2024-06-20 09:48 UTC by rik-bos

Include:
* High level introduction into GenAI
* Basic capabilities / concepts & how-tos
* Conversational UI as new module
* GenAI as new module
* Updated Bedrock & OpenAI connector with dependency on GenAI
* Moved documents to create a section
* Bedrock referral page in the GenAI section

2024-06-20 09:49 UTC, rik-bos commented
content/en/docs/appstore/modules/genai/_index.md is ready for review.
Others will be added when we complete them.

2024-06-20 16:10 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/aws/amazon-bedrock.md
Reviewed.

2024-06-20 16:13 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/concepts/rag-example-implementation.md
>  title: "RAG Example Implementation in the OpenAI Showcase Application"
Reviewed.

2024-06-20 16:16 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/_index.md
> +---
In progress

2024-06-21 08:41 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/_index.md
> +| Asset | Description | Studio Pro Version |
@katarzyna-koltun-mx - everywhere where this table mentions 9.24 it's actually 9.24.2 (that was still TBD), can you update this?

2024-06-21 14:02 UTC, MarkvanMents commented
@katarzyna-koltun-mx - can you check that the URLs are consistent and have a think about what the URL structure should be?
I prefer all the docs to have the URL structure /appstore/modules/genai/<docname>, but do you think we need more distinction between specific technical solutions?

2024-06-21 14:23 UTC, MarkvanMents commented
Case question:
Are we going for "generative AI" as opposed to "Generative AI"?

2024-06-21 14:51 UTC, MarkvanMents requested changes
Reviewed concepts/_index.md
Have indicated some things I think should be removed or changed.
@rik-bos - can you have a look and see what you think?

2024-06-21 14:51 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +- **Not Conscious:** LLMs do not possess self-awareness or understanding. They generate text based on patterns in the data they were trained on.
Should we say what we mean by not having "understanding"?

```suggestion
- **Not Conscious:** LLMs do not possess self-awareness or semantic knowledge (understanding). They generate text based on patterns in the data they were trained on.
```

2024-06-21 14:51 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +Connecting to an agent from a Mendix application can easily be done via the Amazon Bedrock Connector. For detailed instructions please refer to the [Connector documentation](/appstore/modules/aws/ama
Should we get rid of this section - it doesn't seem to go with the rest of the document and is incomplete.
```suggestion
```

2024-06-21 14:51 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +* How to use a multi-lingual database of historical tickets & resolutions to propose resolutions to the users based on historical input.
This seems to be solution-specific information, and doesn't contain all the information (for example it implies you can't use RAG with OpenAI.
I think it should be removed and moved into the solution-specific documentation?

2024-06-21 14:51 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +This pattern is supported both by [OpenAI](https://platform.openai.com/docs/guides/function-calling) and [Bedrock in the Anthropic Claude v3 models](https://docs.anthropic.com/en/docs/tool-use).
This is not generic information and I think we should move it to the module-specific documentation.

2024-06-21 15:07 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/_index.md
> +| Asset | Description | Studio Pro Version |
Done

2024-06-21 15:10 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/_index.md
> +| AI Bot Starter App | Lets you kick-start the development of enterprise-grade AI chatbot experiences. For example, you can use it to create your own private enterprise-ready ChatGPT-like app. | 10.1
@rik-bos Let me know when the links in line 36 and 37 are available. I also deleted the line that said "diagram here" - if you have the diagram, please send it to me and I'll add it back.

2024-06-21 15:17 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/concepts/function-calling.md
> +---
Reviewed.

2024-06-24 08:08 UTC, MarkvanMents reviewed
Hi @rik-bos 
I have now reviewed the two documents which I was assigned. Gen AI Concepts and Prompt Engineering. Please have a look at the changes, and also the comments:

I left some suggested changes in my [review of the GenAI Concepts document](https://github.com/mendix/docs/pull/7920#pullrequestreview-2132770694).

I also have a couple of comments on the Prompt Engineering document.

2024-06-24 08:08 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +Tip: you can use export to JSON or XML to provide this information in a structured way.
Is this not just repeating section 2.4, below, or do you mean something different here?

2024-06-24 08:08 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +* give examples of the output style you want, for example a JSON structure, if you want to import the response to  generate data or get information about the reasoning
Not sure how JSON helps you get information about the reasoning.

2024-06-24 09:47 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +This pattern is supported both by [OpenAI](https://platform.openai.com/docs/guides/function-calling) and [Bedrock in the Anthropic Claude v3 models](https://docs.anthropic.com/en/docs/tool-use).
@MarkvanMents - In general I want to say that both OpenAI and Bedrock supports this pattern. Does that make sense? We can phrase it in a different way.

For example:

This pattern is supported both by [OpenAI](https://platform.openai.com/docs/guides/function-calling) and [Bedrock](https://docs.anthropic.com/en/docs/tool-use).

or

See [Function Calling](/appstore/modules/openai-connector/function-calling/) for more information on ReAct with OpenAI and Bedrock. You can see...

2024-06-24 09:53 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +* give examples of the output style you want, for example a JSON structure, if you want to import the response to  generate data or get information about the reasoning
Suggestion: 
> * give examples of the output style you want, for example a JSON structure, if you want to import the response to generate data or get structured information on the different steps performed in the propmt

Background:
When a prompt instructs a more complex process containing of multiple steps, you can instruct it to store substeps in JSON so you can import both the answer as well as the intermediate substeps.

Or in the case of this prompt you can ask the model to explain what is factual and what not:

```
When should I use Office 365 vs Google Docs. Give me a list of arguments and whether they are a preference or based on facts. Also give an example. Respond in a JSON array.
```

Response:
```
...
{
"argument": "Advanced features and functionalities",
"preference_or_fact": "fact",
"example": "Office 365 typically offers more advanced features such as better formatting options, more powerful data analysis tools in Excel, and advanced presentation features in PowerPoint."
},
{
"argument": "Ease of use",
"preference_or_fact": "preference",
"example": "Some users find Google Docs to be more intuitive and user-friendly, while others prefer the familiar interface of Office 365."
},
...
```

2024-06-24 09:59 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +- **Not Conscious:** LLMs do not possess self-awareness or understanding. They generate text based on patterns in the data they were trained on.
Yeah, that looks good.

2024-06-24 10:13 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +Tip: you can use export to JSON or XML to provide this information in a structured way.
Yes, this is different. If a user want's to add information to the context (so the prompt / LLM input) they can use Export to JSON/XML to present that information to the LLM in a structured way.

2.4 is that the LLM responds in JSON and that the reponse can be parsed with JSON afterwards.
For that you need to provide an example of the JSON in the prompt to make sure that the JSON structure is as expected.

2024-06-24 14:04 UTC, dbreseman commented on content/en/docs/appstore/modules/genai/openai/_index.md
> +    1. You might get an error saying `FAILURE: Build failed with an exception. The supplied javaHome seems to be invalid. I cannot find the java executable.`. In this case, verify that you have selec
> In this case, we replaced `grade-7.6` with `gradle-7.6.3`.

Could you clarify this? Could this just read "Make sure to use `gradle-7.6.3`."? Or is it that the user needs whatever the newest available version is in the Mendix folder?

2024-06-24 16:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +Connecting to an agent from a Mendix application can easily be done via the Amazon Bedrock Connector. For detailed instructions please refer to the [Connector documentation](/appstore/modules/aws/ama
Updated after discussion

2024-06-24 16:07 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +* How to use a multi-lingual database of historical tickets & resolutions to propose resolutions to the users based on historical input.
Updated after discussion.

2024-06-24 16:08 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/_index.md
> +This pattern is supported both by [OpenAI](https://platform.openai.com/docs/guides/function-calling) and [Bedrock in the Anthropic Claude v3 models](https://docs.anthropic.com/en/docs/tool-use).
Updated after discussion.
25745caee2806e6ccb8e3ee6799ce84cdc769080

2024-06-24 16:26 UTC, MarkvanMents reviewed
z

2024-06-24 16:26 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +* give examples of the output style you want, for example a JSON structure, if you want to import the response to  generate data or get information about the reasoning
```suggestion
* give examples of the output style you want, for example a JSON structure, if you want to use a structured response to generate data or get structured information about intermediate steps taken, or decisions made, in coming up with a final response to a prompt.
```

2024-06-24 16:34 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +Tip: you can export to JSON or XML to provide this information in a structured way.
```suggestion
Tip: you can provide information in a JSON or XML structure to ensure the information is presented in a consistent way. From Mendix apps, you can use [Export Mappings](/refguide/export-mappings/) to create JSON structures and [Export XML Documents](/howto/integration/export-xml-documents/) to create XML structures.
```

2024-06-24 16:35 UTC, MarkvanMents commented on content/en/docs/appstore/modules/genai/concepts/prompt-engineering.md
> +Tip: you can use export to JSON or XML to provide this information in a structured way.
See https://github.com/mendix/docs/pull/7920/files#r1651322302 for a suggested update.

2024-06-24 16:36 UTC, MarkvanMents requested changes
@rik-bos 
I have just made two final suggestions to resolve the discussion about JSON and XML structures. Hope they are good. Let me know and they can be committed and I can approve the PR.

2024-06-24 16:56 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/genai-commons.md
> +---
Reviewed.

2024-06-24 17:08 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/bedrock.md
> +---
Reviewed.

2024-06-25 07:07 UTC, dbreseman commented on content/en/docs/appstore/modules/genai/openai/_index.md
> +    1. You might get an error saying `FAILURE: Build failed with an exception. The supplied javaHome seems to be invalid. I cannot find the java executable.`. In this case, verify that you have selec
@rik-bos What do you think about this?

2024-06-25 07:12 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/openai/_index.md
> +    1. You might get an error saying `FAILURE: Build failed with an exception. The supplied javaHome seems to be invalid. I cannot find the java executable.`. In this case, verify that you have selec
> https://docs.mendix.com/refguide/install/#offline suggests to use:
> For Mendix 10.10.0 and above: gradle-8.5-bin.zip
> For Mendix 10 versions below 10.10.0: gradle-7.6.3-bin.zip

I'd indeed change this to something like:

You might get an error saying `FAILURE: Build failed with an exception. The supplied javaHome seems to be invalid. I cannot find the java executable.`. In this case, verify that you have selected the correct JDK directory containing the updated JDK version. You may also need to update Gradle. To do this, go to **Edit** > **Preferences** > **Deployment** > **Gradle directory**. Click **Browse** and select a newer Gradle version from the Mendix folder.
For Mendix 10.10.0 and above use gradle 8.5.
For Mendix 10 versions below 10.10.0 use gradle 7.6.3.

_NB: Can you check with the runtime tech writer whether there should be some generic piece somewhere on this? I don't belong it ultimately should be documented here. Perhaps only referred to from here._

2024-06-25 07:19 UTC, dbreseman commented on content/en/docs/appstore/modules/genai/openai/_index.md
> +    1. You might get an error saying `FAILURE: Build failed with an exception. The supplied javaHome seems to be invalid. I cannot find the java executable.`. In this case, verify that you have selec
Thanks. I'll implement this change and follow up with @MarkvanMents about longer-term options for documenting this.

2024-06-25 07:23 UTC, MarkvanMents approved these changes
`concepts/_index` and `prompt-engineering` are good to go from my end.

2024-06-25 11:44 UTC, katarzyna-koltun-mx commented on content/en/docs/appstore/modules/genai/conversational-ui.md
> +---
Reviewed but the Configuration section is very sparse and should be updated post-release.

2024-06-25 11:59 UTC, rik-bos commented on content/en/docs/appstore/modules/genai/conversational-ui.md
> +---
Agreed. @liamsommer-mx - can you include this in the docs enrichment story that we should include some screenshots and more text on how to do this?

2024-06-25 13:41 UTC, merged