Document clear-cache cookie in versions 9 and 10
mendix/docs pull request #7927
Opened 2024-06-21 09:20 UTC by EnasAbdelrazek

2024-06-24 10:39 UTC, MarkvanMents approved these changes
Looks good to me.
Approving.
Since this is for two versions, I will publish it with 10.13 as being the latest version.

2024-06-26 12:18 UTC, Robinfr requested changes

2024-06-26 12:18 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **clear_cache** | Runtime | Instructs the client to clear the cached session data whenever a new end-user signs in to an offline application—*introduced for apps created in Mendix version 10.13.0 a
@EnasAbdelrazek This is not offline specific?

2024-06-26 12:18 UTC, Robinfr commented on content/en/docs/refguide9/runtime/mendix-client.md
> +| **clear_cache** | Runtime | Instructs the client to clear the cached session data whenever a new end-user signs in to an offline application—*introduced for apps created in Mendix version 9.24.24 a
Same comment

2024-06-26 12:19 UTC, Robinfr commented
@EnasAbdelrazek Should we mention the better approach for 10? Ideally, people shouldn't use the cookie directly. Maybe we should reference the new API in the description of the cookie for Mx10?

2024-06-28 13:48 UTC, Robinfr requested changes

2024-06-28 13:48 UTC, Robinfr commented on content/en/docs/refguide/runtime/mendix-client/_index.md
> +| **clear_cache** | Runtime | Instructs the client to clear the cached session data whenever a new end-user signs in to an offline application. If the client is not directly used for the sign-in func
>which sets that cookie a long with all the necessry session cookies

should be 
> which sets all necessary cookies related to the session.

2024-06-28 13:53 UTC, Robinfr approved these changes

2024-06-28 13:53 UTC, EnasAbdelrazek commented
We have to update the Java API reference after releasing 10.13

2024-07-30 10:07 UTC, merged