Update scheduled-events with information about session object
mendix/docs pull request #7946
Opened 2024-06-26 07:14 UTC by jveldhuizen

2024-06-26 07:14 UTC, jveldhuizen commented
Approval needed from Runtime Core.

2024-06-26 07:26 UTC, hugomendix approved these changes
LGTM

PS: If we decide that we want to remedy this in the next major version, we may want to announce that here as well.

2024-06-27 13:46 UTC, MarkvanMents requested changes
Hi @jveldhuizen 
Jonathan, I have a small suggestion to clarify what we are talking about. I think the current description could be misinterpreted.

2024-06-27 13:46 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/scheduled-events.md
> +Each runtime node has one specific session in memory which is used for all scheduled events. Changes to this session are visible for all scheduled events on that node. Things like changing the time z
Hi @jveldhuizen 
I'm not sure about the last sentence. It implies that you can change the session, but I don't believe that it is possible to change that. I think we are talking about changing the session _environment_ (timezone, language, time). I'm not sure how best to say this? Perhaps
```suggestion
Each runtime node has one specific session in memory which is used for all scheduled events. Changes to this session are visible for all scheduled events on that node. Things like changing the time zone via a Java action in one scheduled event can lead to unexpected behavior in other scheduled events. You are therefore strongly discouraged from changing the global session environment for scheduled events.
```

@NielsKunst - I will copy this into the Mendix 9 documentation once this language has been agreed.

2024-07-01 14:14 UTC, jveldhuizen commented on content/en/docs/refguide/modeling/resources/scheduled-events.md
> +Each runtime node has one specific session in memory which is used for all scheduled events. Changes to this session are visible for all scheduled events on that node. Things like changing the time z
You cannot change the session of scheduled events to another session. That's true. But you can change the session object itself; you can change its timezone field, see the method `setTimeZone` on https://apidocs.rnd.mendix.com/10/runtime/com/mendix/systemwideinterfaces/core/ISession.html. If you think that that's more clear with talking about _session environment_, that's fine.

2024-07-01 14:32 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/resources/scheduled-events.md
> +Each runtime node has one specific session in memory which is used for all scheduled events. Changes to this session are visible for all scheduled events on that node. Things like changing the time z
> You cannot change the session of scheduled events to another session. That's true. But you can change the session object itself; you can change its timezone field, see the method `setTimeZone` on https://apidocs.rnd.mendix.com/10/runtime/com/mendix/systemwideinterfaces/core/ISession.html. If you think that that's more clear with talking about _session environment_, that's fine.

Ah, I see what you mean. How about I say
```suggestion
Each runtime node has one specific session in memory which is used for all scheduled events. Changes to this session are visible for all scheduled events on that node. Things like changing the time zone via a Java action in one scheduled event can lead to unexpected behavior in other scheduled events. You are therefore strongly discouraged from changing the session object for scheduled events.
```

2024-07-01 14:40 UTC, jveldhuizen commented on content/en/docs/refguide/modeling/resources/scheduled-events.md
> +Each runtime node has one specific session in memory which is used for all scheduled events. Changes to this session are visible for all scheduled events on that node. Things like changing the time z
Yes, that's a nice addition.

2024-07-01 14:53 UTC, MarkvanMents approved these changes
@jveldhuizen 
Looks good, I assume I can merge this immediately? I'll do that unless I hear from you today.

2024-07-02 07:36 UTC, merged