Titan image genai commons
mendix/docs pull request #8005
Opened 2024-07-09 07:28 UTC by strategicalliances

2024-07-09 08:18 UTC, MarkvanMents commented
Hi there @strategicalliances 
Kasia is away this week and I have a couple of questions.

1. Can this wait until Kasia is back next Tuesday (16th) or has it already been released and needs to be published immediately?
2. Which version of the Bedrock module was image generation introduced in?

I will pick this up if it needs to be published this week. Can you let me know the answer to the second question?

2024-07-09 12:08 UTC, MarkvanMents requested changes
Hi @strategicalliances - I've asked some questions and made some suggestions for changes. Can you have a look and get back to me?
Feel free to commit any suggestions you agree with.

2024-07-09 12:08 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `NegativeText` | The NegativeText attribute describes a text prompt to define what not to include in the image. |
Does it describe the text prompt? I think it **is** the text prompt?
```suggestion
| `NegativeText` | The NegativeText attribute is a string containing a prompt describing what not to include in the image. |
```

2024-07-09 12:08 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `Error` | The Error attribute describes the error message if the request violates the content moderation policy. |
```suggestion
| `Error` | The Error attribute contains the error message if the request violates the content moderation policy. |
```

2024-07-09 12:08 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +This helper entity solely serves the purpose of creating a flat entity to produce the correct export mapping.
What do you mean by a "flat entity"?

2024-07-09 12:08 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +`GenAICommons.ImageOptions` is an optional parameter that can be omitted by passing *empty* instead. If provided, it allows to set additional options for Image Generation.
If it has to be *empty* then it isn't optional, you have to pass something. How about:
```suggestion
| `UserPrompt (String)`,<br/>`AmazonBedrockConnection (object)`,<br/>`GenAICommons.ImageOptions (object)`| `GenAICommons.Response (object)`|

`GenAICommons.ImageOptions` can be an empty object. If provided, it allows you to set additional options for Image Generation. 
```

2024-07-09 12:08 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `GenAICommons.ImageOptions (object)`, `NegativeText (string, optional)` | `TitanImageOptions_Extension (object)` |
I think that you always have to supply a string here, so it shouldn't be optional (although it could be zero-length or spaces).
Also, there is no point in calling this microflow if you give it an empty NegativeText string as the only thing it does is add a NegativeText string to your image options.

2024-07-09 12:08 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `GenAICommons.ImageOptions (object)`, `Seed (integer, optional)`, `CfgScale (decimal, optional)` | `none` |
I don't think the Seed and CfgScale are optional, I think you will have to provide something as Microflows do not have optional parameters? Which values will be replaced by defaults? zero?

2024-07-09 16:12 UTC, strategicalliances commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `NegativeText` | The NegativeText attribute describes a text prompt to define what not to include in the image. |
I agree. Suggestion is fine

2024-07-09 16:13 UTC, strategicalliances commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `Error` | The Error attribute describes the error message if the request violates the content moderation policy. |
also fine. You can even shorten it: The Error attribute contains the error message if the request violates the content moderation policy.

2024-07-09 16:15 UTC, strategicalliances commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +This helper entity solely serves the purpose of creating a flat entity to produce the correct export mapping.
This is quite technical language which means that a data structure where several entities are connected over associations has been condensed into one entity instead.

2024-07-09 16:15 UTC, strategicalliances commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +`GenAICommons.ImageOptions` is an optional parameter that can be omitted by passing *empty* instead. If provided, it allows to set additional options for Image Generation.
fine. Or 'is optional'?

2024-07-10 08:22 UTC, MarkvanMents reviewed
Thanks for your responses. I've merged the changes that you agreed.
If you want to discuss my point about using "optional" for items which have to be provided then we can have a quick call.

If you have a parameter in a microflow or action it cannot be optional. You have to provide something, even if it is an empty entity, the value zero, or a zero-length string.

2024-07-10 08:22 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +This helper entity solely serves the purpose of creating a flat entity to produce the correct export mapping.
How about:
```suggestion
This helper entity summarizes data from several associated entities into a single entity where it can be formatted to produce the correct export mapping.
```

2024-07-10 08:22 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +`GenAICommons.ImageOptions` is an optional parameter that can be omitted by passing *empty* instead. If provided, it allows to set additional options for Image Generation.
My point is that it isn't "optional". If you use this operation you have to provide something in `GenAICommons.ImageOptions` even if what you provide is an empty entity.

2024-07-10 08:22 UTC, strategicalliances commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `GenAICommons.ImageOptions (object)`, `NegativeText (string, optional)` | `TitanImageOptions_Extension (object)` |
HI Mark, good find. Could you remove 'optional'?

2024-07-10 10:08 UTC, strategicalliances commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `GenAICommons.ImageOptions (object)`, `Seed (integer, optional)`, `CfgScale (decimal, optional)` | `none` |
By optional we mean that it is fine to set them 'empty' and then they are not part of the request at all. They are just not sent to the API.

2024-07-10 12:27 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `GenAICommons.ImageOptions (object)`, `NegativeText (string, optional)` | `TitanImageOptions_Extension (object)` |
Done

2024-07-10 12:34 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +| `GenAICommons.ImageOptions (object)`, `Seed (integer, optional)`, `CfgScale (decimal, optional)` | `none` |
Added this as an explanation.

2024-07-10 12:39 UTC, MarkvanMents approved these changes
Made some final small changes here: https://github.com/mendix/docs/pull/8005/files/2e48a2c129803fe59c5e6607918bece8f01f8cfe..d76e793f838877da80f85ec29576e668b1965d58

Approving.

Please let me know over Slack when the new version of Bedrock is released.

2024-07-10 12:43 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/aws/amazon-bedrock.md
> +This helper entity solely serves the purpose of creating a flat entity to produce the correct export mapping.
@strategicalliances - still one more change for you to approve.

2024-07-24 12:53 UTC, katarzyna-koltun-mx approved these changes

2024-07-24 12:53 UTC, katarzyna-koltun-mx commented
Reviewed and waiting for the go ahead.

2024-07-26 14:31 UTC, merged