Strategicalliances / rbac update
mendix/docs pull request #8017
Opened 2024-07-10 12:19 UTC by strategicalliances

2024-07-10 14:00 UTC, MarkvanMents commented
@strategicalliances - does this need to be reviewed immediately, or can it wait until Kasia is back next Tuesday?

2024-07-12 12:54 UTC, MarkvanMents requested changes
@strategicalliances - does this need to be reviewed immediately, or can it wait until Kasia is back next Tuesday?

Also, the two images seem to be corrupt.

2024-07-12 12:54 UTC, MarkvanMents commented on static/attachments/appstore/modules/snowflake-sso/RBAC-SSO-explanations.jpg
This file is corrupt. It only seems to be 2 bytes long.
Can you re-upload it and make it a .png file rather than a jpg (unless there is a very good reason for it to be a jpg).

2024-07-12 12:54 UTC, MarkvanMents commented on static/attachments/appstore/modules/snowflake-sso/RBACKeyPairExplanations.jpg
This file is corrupt. It only seems to be 2 bytes long.
Can you re-upload it and make it a .png file rather than a jpg (unless there is a very good reason for it to be a jpg).

2024-07-18 12:54 UTC, katarzyna-koltun-mx requested changes
The images included in this PR are corrupted and cannot be displayed. @strategicalliances please provide the correct images.

2024-07-18 13:35 UTC, katarzyna-koltun-mx commented
Merging into new branch to fix the image errors.

2024-07-18 13:35 UTC, merged