Push notifications for PWA
mendix/docs pull request #8043
Opened 2024-07-15 14:02 UTC by jdiehl

@ConnorLand

2024-07-15 14:09 UTC, jdiehl commented
Needs review from @allard-mx

2024-07-16 09:36 UTC, ConnorLand commented
@jdiehl and I need to duplicate these changes in Mx9, right?

2024-07-17 07:24 UTC, allard-mx requested changes
Looks very good to me! I left a few minor remarks.

2024-07-17 07:24 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-implement-pwa.md
> +Push notifications in progressive web apps require firebase to be set up as early as possible. To do so, you need to create a custom index.html and initialize firebase there. Follow these steps to do
Firebase is capitalized in other parts of the module docs, would prefer using a capital here as well (and the other mention in the second sentence)

2024-07-17 07:24 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-implement-pwa.md
> +5. Back in Studio Pro, set the constant `WebPushVapidKey` found in `_USE ME/Web/` in the Push Notifications module to the web certificate from part 3.
I would change `web certificate` to `public key of the Web Push certificate you created in part 3`

2024-07-17 07:24 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Not receiving push notifications on a PWA | Push notifications on PWAs are only shown when the app is not open | Close the app and try again |
Maybe change this in something like `not open on the foreground`?

2024-07-17 07:24 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Not receiving push notifications on a PWA on iOS | iOS PWAs require https to run | Deploy your app and try again |
We could mention that you can use a tool like ngrok during local development

2024-07-17 07:24 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Clicking on a push notification does not open the PWA | Push notifications for PWAs require a WebLink to be set. | Make sure the WebLink is set to a valid path of your application (for example "/")
I would change `WebLink` into `Web link`, since this is how it's shown in the send message pop-up

2024-07-17 07:24 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/setting-up-google-firebase-cloud-messaging-server.md
> +For progressive web apps, an additional certificate is needed. You can skip this step for native mobile apps. To obtain the certificate, again click the cogwheel on the upper-left side of the screen
I would change `certificate` into `public key`, since it is only the public part of the certificate. Using the word `certificate` might raise concerns, since the constant is exposed to the client in the app.

2024-07-17 08:14 UTC, jdiehl commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Not receiving push notifications on a PWA on iOS | iOS PWAs require https to run | Deploy your app and try again |
I'd rather not - I don't want to maintain references to external sites that might change or remove their service at any time. Developers can test web push notifications easily in Chrome.

2024-07-17 09:45 UTC, allard-mx approved these changes

2024-07-17 09:56 UTC, jdiehl commented
> @jdiehl and I need to duplicate these changes in Mx9, right?

Yes. The module will be compatible with 9.24. The setup is the same for mx 9

2024-07-17 09:57 UTC, jdiehl commented
> Looks very good to me! I left a few minor remarks.

@ConnorLand Allard approved the PR. Please align with him because the docs update should be in sync with a new marketplace release

2024-07-25 14:11 UTC, allard-mx requested changes

2024-07-25 14:11 UTC, allard-mx commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md
> +Skip this section if the [Native Mobile Resources](https://marketplace.mendix.com/link/component/109513/Mendix/Native-Mobile-Resources) module is already implemented in your app. This module is requi
The change for Nanoflow Commons (one section above this one) seems to be missing here, where the `or if you do not plan on using using local or native push notifications` part got removed

2024-07-25 14:11 UTC, allard-mx commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-build-native.md
> +Now you are able to build, the next step is to run your app in an emulator or test device. This will let you send your first test push notification in the next section.
The `notif-build-native.md` file seems to be deleted for the Mendix 10 refguide (see [this](https://github.com/jdiehl/docs/commit/4ba05aa394ff889603d5ec04be77703b8e3b0d32) commit), however, it seems the introduction still refers to it? The refguides for Mx 9 and 10 are not in sync now as far as I can see. @jdiehl Do you know why the file was deleted?

2024-07-25 14:11 UTC, allard-mx commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-implement-pwa.md
> +title: "Part 7: Implement Push Notifications in Your Progressive Web App"
Title mentions part 7, whilst the link title below says part 6, this seems incorrect to me? In `notif-config-push.md` this page gets referred to as part 6.

2024-07-25 14:11 UTC, allard-mx commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +title: "Part 8: Send Your First Test Push Notification"
Same here, seems like something happened with the part numbering, it is out of sync with the Mx 10 refguide

2024-07-25 14:17 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-implement-native.md
>  Now that you have everything set up, it is time to deploy your native app. See [Build a Native Mobile App with Push Notifications](/refguide/mobile/using-mobile-capabilities/push-notifications/notif-
Is this correct? It seems this part has been moved into the current file in section 5 below, so this link is broken?

2024-07-25 14:21 UTC, allard-mx commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-build-native.md
> +Now you are able to build, the next step is to run your app in an emulator or test device. This will let you send your first test push notification in the next section.
Never mind, it seems the part for building the native app has been moved into the `notif-implement-native.md` file (section 5, see my comment below). I do think there are still some broken links though, in the index/introduction and in `notif-implement-native.md` itself

2024-07-25 14:27 UTC, ConnorLand commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-implement-native.md
>  Now that you have everything set up, it is time to deploy your native app. See [Build a Native Mobile App with Push Notifications](/refguide/mobile/using-mobile-capabilities/push-notifications/notif-
Correct, therefore I've edited this paragraph.

2024-07-25 14:29 UTC, ConnorLand commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-build-native.md
> +Now you are able to build, the next step is to run your app in an emulator or test device. This will let you send your first test push notification in the next section.
Fixed here: https://github.com/mendix/docs/pull/8043/commits/6cd389fcbcb5457d6435e19f0feb4bec39b74f80

2024-07-25 14:41 UTC, ConnorLand commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-build-native.md
> +Now you are able to build, the next step is to run your app in an emulator or test device. This will let you send your first test push notification in the next section.
Sorry, actually finally fixed (with the Mx9 doc deleted as the Mx10 one is) here: https://github.com/mendix/docs/pull/8043/commits/fd92e20317edf11126bad1b378252dbd9a539d58

2024-07-26 11:33 UTC, ConnorLand commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md
> +Skip this section if the [Native Mobile Resources](https://marketplace.mendix.com/link/component/109513/Mendix/Native-Mobile-Resources) module is already implemented in your app. This module is requi
Added in this section

2024-07-26 12:18 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md
> +Skip this section if the [Native Mobile Resources](https://marketplace.mendix.com/link/component/109513/Mendix/Native-Mobile-Resources) module is already implemented in your app. This module is requi
It's also removed for **- 4 Implementing the Nanoflow commons module** line 37. `or if you do not plan on using using local or native push notifications` needs to be removed from there as well.

Note: it's removed for Mx10

2024-07-26 12:29 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-implement-pwa.md
> +title: "Part 7: Implement Push Notifications in Your Progressive Web App"
The title is still referring to part 7 whilst the link is to part 6.

Note: The Mx10 refguide is referring to part 6 for both.

2024-07-26 12:37 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-implement-pwa.md
> +title: "Part 7: Implement Push Notifications in Your Progressive Web App"
I think this should be part 6 and the parts afterwards should be reduced by 1?

I found sections (1-2-3-4-5-**7-8-9**) -> missing section 6 and incremented 7,8.9?

2024-07-26 12:38 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +title: "Part 8: Send Your First Test Push Notification"
This should be section part 7 as well as title part 7

2024-07-26 12:40 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-mult-devices.md
This should be Part 8?

2024-07-26 12:45 UTC, MendixMurshed commented on static/attachments/howto/mobile/native-mobile/implementation/notifications/setting-up-google-firebase-cloud-messaging-server/push_notifications_web_config.png
Is it ok to show the API key and the other project details? or should they be masked?

2024-07-26 12:46 UTC, MendixMurshed commented on static/attachments/howto/mobile/native-mobile/implementation/notifications/setting-up-google-firebase-cloud-messaging-server/push_notifications_web_certificate2.png
Shouldn't the key pair be masked?

2024-07-26 12:47 UTC, MendixMurshed commented on static/attachments/howto/mobile/native-mobile/implementation/notifications/notif-implement-pwa/vapid-idwizard.png
Shouldn't we mask the default value here as well?

2024-07-26 13:47 UTC, ConnorLand commented on static/attachments/howto/mobile/native-mobile/implementation/notifications/setting-up-google-firebase-cloud-messaging-server/push_notifications_web_certificate2.png
Masked this one with a blur effect.

2024-07-26 13:48 UTC, ConnorLand commented on static/attachments/howto/mobile/native-mobile/implementation/notifications/setting-up-google-firebase-cloud-messaging-server/push_notifications_web_config.png
Masked this one with a blur effect.

2024-07-26 13:49 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md
> +Skip this section if the [Native Mobile Resources](https://marketplace.mendix.com/link/component/109513/Mendix/Native-Mobile-Resources) module is already implemented in your app. This module is requi
@ConnorLand

2024-07-26 13:50 UTC, ConnorLand commented on static/attachments/howto/mobile/native-mobile/implementation/notifications/notif-implement-pwa/vapid-idwizard.png
Masked like Jim Carrey in the eponymous film.

2024-07-26 13:51 UTC, MendixMurshed commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md
Line 37: S`or if you do not plan on using using local or native push notifications` should be removed?

2024-07-26 13:59 UTC, ConnorLand commented on content/en/docs/refguide9/mobile/using-mobile-capabilities/push-notifications/notif-add-module-depends.md
Fixed: https://github.com/mendix/docs/pull/8043/commits/ff44bc4faeb1750b0a076352eb86a1b8ec497de5

2024-07-26 14:42 UTC, MendixMurshed approved these changes

2024-07-26 14:43 UTC, ConnorLand approved these changes

2024-07-26 14:43 UTC, merged