[WTF-1907] Fix and improve how-to guide for building pluggable web widgets
mendix/docs pull request #8044
Opened 2024-07-15 17:12 UTC by legio-vi-ferrata

We have previously refactored the [Part 1](https://docs.mendix.com/howto/extensibility/create-a-pluggable-widget-one/) of the guide for building pluggable web widgets. This PR is a follow-up story to upgrade Part 2 with the latest information and conventions as well. This has become necessary as the first part now uses functional React components in code examples with which following the Part 2 is not possible.

In addition, the PR contains several other improvements for both Part 1 and Part 2.

**Release Information:** The PR can be merged and released as soon as possible after its draft status is lifted.

2024-07-16 08:38 UTC, ConnorLand commented
Thanks @legio-vi-ferrata ! Is there a tester you recommend if I have questions or get error codes?

2024-07-16 10:59 UTC, legio-vi-ferrata commented
> Thanks @legio-vi-ferrata ! Is there a tester you recommend if I have questions or get error codes?

Hello @ConnorLand, are you intending to run through the guide to test it? That would be awesome to be honest. :)

2024-07-17 10:03 UTC, weirdwater requested changes
First pass of my review. So far I have checked the index and part 1. I will probably get to part 2 tomorrow.

2024-07-17 10:03 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
> +   ```
Observation rather than a request for change: The indentation of the code block is not necessary. All other code blocks are indented because they are in the context of an enumeration.

2024-07-17 10:03 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
> +* Mendix App path: *{/path/to/your/Mendix/app}*
If you are following the guide the widget will exist in `mendix-app/myPluggableWidgets/textBox`, so the previous path `../..` will point to the right location. Shouldn't we leave it as is?

2024-07-17 10:03 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
> +5. The container component *src/TextBox.tsx* receives the properties in the runtime, and forwards the data to the display component. The container works like glue between the Mendix application and t
The wording seems a bit awkward to me. Maybe something like "In *TextBox.tsx* update the component to look like this:" would be better?

2024-07-19 13:38 UTC, weirdwater requested changes
Finished my pass on Part 2

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children }) =>
This component definition is quite different from the others. To be more consistent I would rewrite the signature to:

```tsx
export function Alert({ alertStyle = "danger", className, children }: AlertProps): ReactElement | null {
```

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +                ></TextInput>
`TextInput` does not accept children and should remain a self closing tag.

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    const value = props.textAttribute.value || "";
The function body in this code block is missing an indentation

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +1. In *TextBox.tsx*, replace the return statement with `id`, `required`, and `hasError` properties:
The wording in this sentence does not seem right. How about:

> In *TextBox.tsx*, add the `id`, `required`, and `hasError` props to the TextInput and Alert components:

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +            <Alert>{validationFeedback}</Alert>
The id prop from the previous revision is omitted from the Alert component here.

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children, id }) =>
See previous comment about the signature of Alert.

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    import { FunctionComponent, createElement, ReactNode } from "react";
I would limit this code block to just the props and the component. The other snippets in this section don't include the imports either

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> -        const labelledby = `${this.props.id}-label`
The definition of `labelledby` is missing in the new version

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    3. Click **View App** to see your changes.
On line -508/+522 it says _"so that it can link the label to the `this` input"_.  I am not sure what it is referring to. Could it be that it is a reference to the this keyword in the class based component? Maybe we can replace `this` with `TextInput`, or remove change "the `this`" to "this"?

2024-07-19 13:38 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   export function preview(props: TextBoxPreviewProps): ReactNode {
This code snippet does not really serve any purpose as it is pretty much equivalent to the component that the generator generates for you. Maybe the entire section should be removed/rewritten?

2024-07-22 13:46 UTC, legio-vi-ferrata reviewed
Thanks for the review @weirdwater, a lot of nice catches! I addressed all threads. Can you do a re-review, please?

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
> +   ```
Yeah, I had thought I spotted a few non-enumerated examples but I was mistaken. Fixed.

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
> +* Mendix App path: *{/path/to/your/Mendix/app}*
Missed that part. Fixed.

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-one.md
> +5. The container component *src/TextBox.tsx* receives the properties in the runtime, and forwards the data to the display component. The container works like glue between the Mendix application and t
Done.

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children }) =>
Fixed. But I kept it as an arrow function.

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +                ></TextInput>
Fixed (including a bunch of other places).

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +1. In *TextBox.tsx*, replace the return statement with `id`, `required`, and `hasError` properties:
Fixed. And I also "codified" TextInput and Alert.

2024-07-22 13:46 UTC, LEGIO-SEXTA-FERRATA commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    const value = props.textAttribute.value || "";
God, it is difficult to format those lines manually. 😅 Fixed.

2024-07-22 13:46 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children, id }) =>
Fixed. In addition, the explanation of this (2nd) step includes something called an `alert` property. I'm not seeing any such prop, so I deleted it as well.

2024-07-22 13:46 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    import { FunctionComponent, createElement, ReactNode } from "react";
Fixed. This was a dilemma for me to be honest, during this whole story. Reasons: In my opinion, it is easier to follow the document with code snippets containing their respective whole files. The code snippets in our documentation, have an automatic "copy contents" feature, through a button that is revealed with hover. And this way you can easily copy/paste and use the diff highlighting features of the IDE to see the difference. On the other hand as the guide goes through, code files will progressively become longer.

I'm removing the import as it is better to stay consistent.

2024-07-22 13:46 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +            <Alert>{validationFeedback}</Alert>
Fixed. 👍🏻

2024-07-22 13:46 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   export function preview(props: TextBoxPreviewProps): ReactNode {
This whole document can be improved in various other ways to be honest. :) But this one, perhaps can be considered outside our scope for now?

2024-07-22 13:46 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> -        const labelledby = `${this.props.id}-label`
Fixed. I included a few other minor fixes with this one as well. Might be helpful to check the whole commit.

2024-07-22 13:46 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    3. Click **View App** to see your changes.
Let me think about this one. Because I'm having a hard time understanding it as well. :D

2024-07-22 13:59 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children }) =>
The updated version is not valid syntax. It should either be

```ts
export function Alert({ alertStyle = "danger", className, children }: AlertProps): ReactElement | null {
```

or

```ts
export const Alert = ({ alertStyle = "danger", className, children }: AlertProps): ReactElement | null =>
```

2024-07-22 14:02 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children, id }) =>
The updated version suffers the same syntax error as above

2024-07-22 14:13 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   export function preview(props: TextBoxPreviewProps): ReactNode {
I would then remove the declaration of `require` and replace `ReactNode` with `ReactElement` to be in line with the code that the generator produces.

2024-07-22 14:34 UTC, legio-vi-ferrata reviewed
@weirdwater, ready for re-re-review.

2024-07-22 14:34 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   export function preview(props: TextBoxPreviewProps): ReactNode {
Done. 👍🏻

2024-07-22 14:34 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children }) =>
Oh, god. I'm sorry. Fixed. I'm pushing this as a fixup! to keep commit history tidy.

2024-07-22 14:34 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    export const Alert: FunctionComponent<AlertProps> = ({ alertStyle = "danger", className, children, id }) =>
Fixed.

2024-07-23 07:13 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   export function preview(props: TextBoxPreviewProps): ReactNode {
I don't see any changes

2024-07-23 07:16 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   import { createElement, ReactNode } from "react";
This import should be updated from ReactNode to ReactElement for the snippet to work.

2024-07-23 07:49 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    3. Click **View App** to see your changes.
My proposed changes:

```md
Explaining the code:

In the previous guide the system property `Label` was added to the widget. This tells Mendix to surround the pluggable widget with a caption. The relationship between the label and the input may have been obvious to us, but not to browsers and screen readers. Proper labeling helps all your users to understand the purpose of elements on your page.

The `label` element generated by Mendix has a pre-filled [`for` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/for) which references the pluggable widget's id (`props.name`). Matching the `input` element's `id` attribute signals that they belong together.

If your widget contains an interactive element that does not have a built-in labeling mechanism, you can use [`aria-labelledby`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby). In our example we show both options, but for built-in input elements the `for` attribute on a label is sufficient.
```

2024-07-23 07:55 UTC, weirdwater commented
@legio-vi-ferrata I have "resolved" some of the threads, and provided a suggestion for the cryptic code description for the accessibility section. I also found some code snippet improvements along the way 🙈

2024-07-23 07:57 UTC, weirdwater requested changes
@legio-vi-ferrata I have "resolved" some of the threads, and provided a suggestion for the cryptic code description for the accessibility section. I also found some code snippet improvements along the way 🙈

2024-07-23 07:57 UTC, weirdwater commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +                    id={props.id}
The generated types do not include an `id` prop, but `name`.

2024-07-23 09:48 UTC, legio-vi-ferrata reviewed
I guess the final review is done now. :)

2024-07-23 09:48 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +    3. Click **View App** to see your changes.
Done.

2024-07-23 09:48 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +   import { createElement, ReactNode } from "react";
Done.

2024-07-23 09:48 UTC, legio-vi-ferrata commented on content/en/docs/howto/extensibility/pluggable-widgets/create-a-pluggable-widget-two.md
> +                    id={props.id}
Agreed IRL that this one is not necessary.

2024-07-23 11:17 UTC, weirdwater approved these changes

2024-07-23 11:17 UTC, legio-vi-ferrata commented
@ConnorLand, we have finished our internal review process. This one is all yours.

2024-07-30 12:44 UTC, ConnorLand approved these changes

2024-07-30 12:47 UTC, ConnorLand commented
@legio-vi-ferrata just a quick word about testing.

@weirdwater and I discussed it. Because the product changes for the widget generator are live, it's key to merge these docs ASAP. I've edited them for language and some formatting and will merge the PR presently.

I will do a full test of the docs myself and see if they require any tweaks to the instructions. I hope to finish that task this week. Thankfully, Arjo did some nice testing himself and the changes are almost all code-snippet improvements (thus, they don't break the doc's language/instructions).

2024-07-30 12:52 UTC, merged