Add troubleshooting hint for blank page to PDF Document Generation module docs
mendix/docs pull request #8046
Opened 2024-07-16 08:44 UTC by allard-mx

2024-07-16 14:32 UTC, MarkvanMents requested changes
Hi @allard-mx 
Can you have a look at my question and let me know if there is more we can say about layouts in section 4 to try and avoid this situation in the first place.

2024-07-16 14:32 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/document-generation.md
> +If the resulting PDF document contains an additional blank page at the end of the document, verify that the page contains an outer layout grid.
@allard-mx - Are you saying that the page must always contain an outer layout grid if you are generating a PDF document? Perhaps we should be more clear in section 4 when we say:

> Using the DocumentGeneration_Default layout is not required. You can use any layout of layout type Responsive, or create your own layout, as long as the layout does not include a scroll container. Layouts that do include a scroll container, such as Atlas_Default, will not work properly. 

and add "but there must be a layout to generate the PDF correctly"?

2024-07-19 13:43 UTC, MarkvanMents commented
@Luyao-Zhang-1 
I didn't get a response from Allard. Could you remind him, if you have time, otherwise I can pick this up when I'm back.

2024-07-22 11:50 UTC, allard-mx commented on content/en/docs/appstore/use-content/modules/document-generation.md
> +If the resulting PDF document contains an additional blank page at the end of the document, verify that the page contains an outer layout grid.
The layout grid is not required in all scenarios, but could help when running into the empty page issue. It depends on the exact page setup (in terms of widgets that are used in combination with the applied styling). I've pushed another commit to reflect that the layout grid could offer a potential solution, but is not a hard requirement.

2024-07-24 14:08 UTC, merged