Add a basic description of parameters when using the custom connection type in database replication
mendix/docs pull request #8057
Opened 2024-07-17 12:30 UTC by passalaqua

The custom connection option in database replication has no documentation. This PR adds some basic information.

2024-07-17 12:47 UTC, dahfjkg requested changes

2024-07-17 12:47 UTC, dahfjkg commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Connection string: A fully formed JDBC URL string (e.g. `jdbc:postgresql://localhost:5432/database` for a Postgres databas);
*database

2024-07-17 12:47 UTC, dahfjkg commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +#### 2.1.1 Common Parameters
I suspect that your goal is not to list available databases, but I would still create a short comment for every field.
Especially the following ones:
- Service name and SID — I'd mention that these are only for Oracle and that one excludes the other
- Use Integrated Security — this one is only for SQL Server

2024-07-17 12:47 UTC, dahfjkg commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
In the list in 2.1.1 there is nothing in the end of the string. In this list you use `;` and `.` — perhaps those can be dropped as well

2024-07-17 13:01 UTC, MarkvanMents reviewed
Although I haven't used these settings the documentation looks clear to me.
I've made a couple of suggestions.
I will still do another proofread once you have responded (for example, we use `*` for unordered lists) but looking good so far.

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +#### 2.1.1 Common Parameters
I agree, if these are common parameters, then it shouldn't depend on the database type as to which ones become available (see below).
If some of these are specific to specific cases (even if that case is "not Oracle" then I think it should be in a separate section).

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +In this page you must select the database type before filling in the connection details. Available database parameters vary per database type.
Proofread
```suggestion
On this page you must select the database type before filling in the connection details. Available database parameters vary depending on database type.
```

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Connection string: A fully formed JDBC URL string (e.g. `jdbc:postgresql://localhost:5432/database` for a Postgres databas);
```suggestion
- Connection string: A fully formed JDBC URL string (e.g. `jdbc:postgresql://localhost:5432/database` for a PostgreSQL database);
```

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Username and Password: The credentials given to the driver to connect to the database server;
Should we mention here not to hard code them in the app? Here is a good link: https://docs.mendix.com/refguide/dev-best-practices/#25-passwords-and-other-secrets (although I'll need to set up a permanent anchor).

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Open/Close escape character: Characters used to quote table and column names (e.g. `"` in Postgres or `[` and `]` in SQL Server);
I think the name of the product in PostgreSQL, so we should say:
```suggestion
- Open/Close escape character: Characters used to quote table and column names (e.g. `"` in PostgreSQL or `[` and `]` in SQL Server);
```

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Driver class: The full name of the driver to be loaded (e.g. `org.postgresql.Driver` for Postgres);
```suggestion
- Driver class: The full name of the driver to be loaded (e.g. `org.postgresql.Driver` for PostgreSQL);
```

2024-07-17 13:01 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
➕

2024-07-17 13:11 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
If anything, I'd add a `;` and `.` to the other list (following what seems to be the AP Stylebook). I couldn't find any mention of which style to use in our documentation, though.

2024-07-17 13:15 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +#### 2.1.1 Common Parameters
I tried adding a short description but all I got was noise. They are either self explanatory while reading the list or only relevant for the database types they appear on (and in which case it should be clear to the user what it is).

The only possible exception is `Use Integrated Security`, which seems to also be available for Informix as well.

2024-07-17 13:18 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
Actually, it does not look like it's AP's, but someone else's.

2024-07-17 13:18 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
There is something in Confluence - but it isn't clear. I'll update it.

Unordered lists should either not have any punctuation at the end, or should have a full stop if each item completes a sentence which introduces the list.

In this case, I would probably put a full stop at the end (although this is one thing which I am never 100% sure about😀).

2024-07-17 13:21 UTC, dahfjkg commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
Usually a label should have a full stop at the end if there are multiple sentences. If it has one sentence, no punctuation is required. For lists, I tend to follow the same rule.

2024-07-17 13:21 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
Oh, I've found the styling for bullets - I'll Slack you a link.

2024-07-17 13:21 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Username and Password: The credentials given to the driver to connect to the database server;
There is no hard coding here. This page is filled after the app is deployed and the credentials are stored in the database (which is just as bad, IMO, but that's how it currently is implemented).

2024-07-17 13:54 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Username and Password: The credentials given to the driver to connect to the database server;
OK - then the security is managed for them. I'll resolve this one.

2024-07-17 13:56 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +#### 2.1.1 Common Parameters
I agree there is no point in repeating the in-app explanation. But perhaps a short note that says "Oracle databases only" or something like that?

2024-07-18 09:14 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +- Close connection after query: Indicates if the connection to the database must be closed after every query.
I replaced them with periods in this list as there is a full description after each entry. The other lists I left period-less.

2024-07-18 09:41 UTC, dahfjkg commented
No more comments from my side, so technical verification is complete

2024-07-18 10:56 UTC, MarkvanMents requested changes
Hi Augusto,
Looks good. I have one further question - if you can let me know what you think, we can resolve it and publish.
Thanks for creating this PR - I think it will help our customers a lot.

2024-07-18 10:56 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +* Close connection after query: Indicates if the connection to the database must be closed after every query.
Should we indicate that these are Booleans. We imply that the other parameters are strings by indicating what goes into them.

2024-07-18 11:40 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +* Close connection after query: Indicates if the connection to the database must be closed after every query.
The boolean options are displayed as checkboxes, so I don't think (within their context) that this clarification is necessary.

2024-07-18 12:37 UTC, MarkvanMents approved these changes
Thanks for this PR.
Looks good to me.
Approving.

2024-07-18 12:37 UTC, MarkvanMents commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +* Close connection after query: Indicates if the connection to the database must be closed after every query.
OK - we've discussed. I'll resolve this.

2024-07-18 12:38 UTC, merged