Conversational AI Best Practices
mendix/docs pull request #8061
Opened 2024-07-17 15:07 UTC by MarkvanMents

2024-07-19 11:25 UTC, MarkvanMents reviewed
Hi Insuk,
I've proofread the document and have several questions and comments.
Can you look through these and respond to them. It would be best to respond to them in GitHub, but if that doesn't work you can respond in Slack.

My main concern is that this seems to be aimed at someone who is building a ChatGPT-like playground rather than someone who is incorporating conversational aspects into a business app. Many aspects, like changing initial prompts, LLM engine, or temperature, are not good practices as it changes the response that the designer intends.

If I have set up a ChatBot to be a support agent that always gives the same answer to the same question, I don't want end-users to be able to fiddle with the temperature or change the initial prompts to the Bot. I also don't want them to turn off history as I will need the context if the bot ends up making a support ticket.

So I think some of the recommendations should be looked at again, and more business-oriented examples given (rather than generating haikus or brainstorming designs).

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/cancel-button.png
End-user text is not inverted (white on black) as it is in the other images

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/data-is-protected.png
End-user avatar appears level with the hamburger whereas in other examples it is in the top bar or next to a prompt.

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/delete-conversation.png
End-user avatar appears level with the hamburger whereas in other examples it is in the top bar or next to a prompt.

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/protection-and-examples.png
End-user avatar appears level with the hamburger whereas in other examples it is in the top bar or next to a prompt.

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/regenerate.png
In other images, when the end-user selects the button it puts it into a (white on black) prompt to show a clear history of what was asked. But in this example it doesn't.

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/say-hi.png
End-user avatar appears level with the hamburger whereas in other examples it is in the top bar or next to a prompt.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/reply-quote-icon.png" max-width="320px" alt="Showing an icon in the Bot response to indicate a response is required" >}}
I'm not sure what the use of this is. When the Bot stops responding it is always the end-user's turn to prompt - the bot will not spontaneously start responding after a set length of time.

It is not clear that the reply function will only pick up part of the bot's response.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +Mendix suggests that you set up a Conversational AI service blueprint. This is a journey map for main user groups. It will contain the following design elements:
What do you mean by "main user groups"?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* [The end-user can set the temperature](#value)
I don't understand these features.
If I'm building conversational AI into my app, I want to be in control of the initial prompt - I don't want the user to be able to change my ChatBot to "respond as inaccurately and humorously as possible" when I want "respond accurately, using precise language".
Also, I don't want the end-user to fiddle with the temperature - if I know that a temperature of 0.2 gives consistently good results, I don't want them to change it to 0.8 to get more variability.

2024-07-19 11:25 UTC, MarkvanMents commented on static/attachments/howto/front-end/conversation-best-practices/upgraded-recommendations.png
We advise communicating the version of the system, but this isn't communicating that, it is just saying that it has changed from the previous one.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **System version**: Help end-users understand the capabilities and limitations of the system, setting appropriate expectations for their experience.
Don't really understand this point - I don't see how communicating a version does this.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* [The end-user can remove the interaction history](#local-control)
```suggestion
* [The end-user can remove the interaction history](#privacy)
```
This is described in section 5

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Allow the end-user to delete the conversation history, and turn off collecting the conversation.
This seems to be counter to a conversational AI. The whole point of conversational AI is that it is a conversation and the AI knows what has gone on before. By turning the history off, you no longer have a conversation, just a one-shot question and answer.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/cancel-button.png" max-width="320px" alt="Show a button to allow end-user to edit a prompt" >}}
I don't really understand this example. If the AI can't create a visual image what is the benefit of being able to change the original prompt?

In addition, I don't think a product containing conversational AI should allow the end-user to "override the AI action". The app designer knows what the AI is allowed, and not allowed, to do.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +This is the method for the end-user to provide information to the system. This can be through text, voice, buttons, menus, or a combination of these elements. However, it is always important for the
What do you mean by "facilitate the input"?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Clear affordance is key to where the end-user can enter their input.
What do you mean by "clear affordance"

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Don’t overload various inputs at the same time, it might confuse the end-user with which action to take.
Not sure what you mean here.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Allow the end-user to input free text, or initiate a conversation.
Isn't "free text" and "a conversation" the same thing?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    * Empower end-users with adjustable "temperature" settings for AI responses. This could range from factual and concise to creative and elaborate, allowing end-users to customize the level of deta
I don't think this is appropriate in a production app, only in a "playground" where end-users are evaluating conversational AI for their own use. In a production app, the designer needs to know how consistent the responses are going to be.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    * Move beyond reactive measures. Design systems that prioritize end-user privacy from the outset. Implement robust data encryption and access controls to safeguard end-user information.
Are we talking about what the end-user gives as a prompt here, not the resources the AI is using to respond to the prompt?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Input Character Handling**: Set realistic expectations for end-user input.
Is this just one point, rather than two?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +With conversational AI, the burden of discovering the capability of a bot or voice assistants is up to the end-user. They can only know a chatbot can’t do something after it fails to provide a good r
What do you mean by "affordances"?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Serendipity**: Algorithmic recommendations can create filter bubbles. Adding serendipity helps end-users discover new things outside their echo chambers.
What do you mean by serendipity. Is it the same as temperature?

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/drafts.png" max-width="320px" alt="Option is given to create multiple drafts of response from Bot with option to show or h
I'm not sure what this has to do with hinting and discoverability. In fact, the "drafts" functionality is completely unclear to me - are we forcing the AI to make some of its reasoning steps explicit? How does that help the end-user?

I'm not sure this sort of bot interaction is relevant to our customers, they might as well use a public interface to ChatGPT if they want to generate haikus about coffee.

2024-07-19 11:25 UTC, MarkvanMents commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Offer context**: Briefly explain why the error happened. For instance, "The password you entered doesn't meet our security requirements. It must be at least 8 characters long and contain a combin
I'm not sure I would rely on a chatbot to implement a security requirement - this is something which is much better done in deterministic code.

2024-07-23 12:32 UTC, Ichigoko requested changes
Added the new version of images, that have consistent top navigation (menu, protected badge, and user profile) also all the user avata in conversation are removed.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/cancel-button.png
This case is different, as the user is "modifing or editing" mode of the previous prompt.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/data-is-protected.png
This case the avata is the user profile, while the other one is the avatar in the conversation. But you are right. we will add the profile avata in every image.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/delete-conversation.png
This case the avata is the user profile, while the other one is the avatar in the conversation. But you are right. we will add the profile avata in every image.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/protection-and-examples.png
This case the avata is the user profile, while the other one is the avatar in the conversation. But you are right. we will add the profile avata in every image.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/regenerate.png
I don't get your point.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/say-hi.png
This case the avata is the user profile, while the other one is the avatar in the conversation. But you are right. we will add the profile avata in every image.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/upgraded-recommendations.png
It isn't explicitly mentioned the 'version' but some level of system change is communicated.

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/am-i-right.png
NEW image here
![Error_Confirmation1](https://github.com/user-attachments/assets/671ee8e3-47ce-4a8e-8265-ff347ef82c18)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/cancel-button.png
New image here (I've added 'user profile avata'
![LUC1](https://github.com/user-attachments/assets/b6edf5f0-d51b-42ca-9bf4-7fd56e178e83)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/context-driven-prompts.png
New image here, I've added user profile avata, removed the user avata in conversation
![PromptHelp3](https://github.com/user-attachments/assets/7784a399-41b8-4ac0-a49d-0daa31858882)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/data-is-protected.png
new updated version of image (user profile)
![Privacy1](https://github.com/user-attachments/assets/e877ba37-9e59-45ab-a0d2-9794f352be5a)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/delete-conversation.png
new updated version of image
![Privacy2](https://github.com/user-attachments/assets/9e5128ee-5dd1-445d-83ae-26b5bc455488)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/do-not-understand.png
![Error_Confirmation2](https://github.com/user-attachments/assets/4b610367-ea48-4cb9-93cc-e5fd16d68a15)
New image

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/drafts.png
new image
![Hint3](https://github.com/user-attachments/assets/dd88b5ca-be15-4e0d-85e8-e026be5fb41f)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/error.png
new image
![Error_Trans](https://github.com/user-attachments/assets/9408fdc4-6803-4833-96a8-cd6c5cf412bd)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/highlight-the-question.png
new
![Qute_Reprompt2](https://github.com/user-attachments/assets/b8817283-7ac2-4c2e-bd27-3c8bd4307942)
 image

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/modify-icon.png
new image
![Qute_Reprompt1](https://github.com/user-attachments/assets/b2a4ce00-bda3-4de9-9172-a62cf19325d1)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/modify-options.png
new image
![Hint2](https://github.com/user-attachments/assets/e10fba2d-5284-4c43-bd88-e714c550deaf)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/pause.png
new image
![LUC2](https://github.com/user-attachments/assets/33671355-9d5d-4c10-ad2e-42b7b651f1cf)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/protection-and-examples.png
new image
![AI_Value1](https://github.com/user-attachments/assets/00f4a8ec-9afd-4f31-a0e9-d87f441a7d03)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/regenerate.png
new image
![Hint3](https://github.com/user-attachments/assets/4334e534-4fc1-49bc-bf0f-e4d7b57d82a5)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/reply-quote-icon.png
new image
![Qute_Reprompt1](https://github.com/user-attachments/assets/b0c3ed72-7129-4c6e-b8b5-994839eb4b7e)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/say-hi.png
new image
![SayHi1](https://github.com/user-attachments/assets/f410f5df-490f-4df6-aeb6-882da35c5914)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/upgraded-recommendations.png
new image
![AI_Value2](https://github.com/user-attachments/assets/7793ccb4-fde5-4ed2-beb1-e2a32c6525d1)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/protection-and-examples.png
New images
![AI_Value1](https://github.com/user-attachments/assets/31488b6f-5cdc-4a19-b796-974703bb6e28)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/buttons-and-prompts.png
new image
![InputM1](https://github.com/user-attachments/assets/99a3f399-e482-4706-bcef-33b4cf43ee35)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/cancel-button.png
new image
![LUC1](https://github.com/user-attachments/assets/90cf2210-6a84-4d09-b254-c10bc4579519)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/data-is-protected.png
new image
![AI_Value1](https://github.com/user-attachments/assets/05aad137-acb0-4fbf-a1ea-521bd96c957b)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/delete-conversation.png
new image
![Privacy2](https://github.com/user-attachments/assets/cbcc65ae-3bb9-4976-9729-8943be75bfdc)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/regenerate.png
new image
![Hint3](https://github.com/user-attachments/assets/2fcec889-043d-49fc-a4ad-3073c2e19481)

2024-07-23 12:32 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/say-hi.png
new image
![SayHi1](https://github.com/user-attachments/assets/85c46df2-fbec-4b7c-b9de-62a3a82bbb9a)

2024-07-23 14:11 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +Mendix suggests that you set up a Conversational AI service blueprint. This is a journey map for main user groups. It will contain the following design elements:
The main user group(s) mean a targeted user group who will use the conversational AI. For example, in Mendix, there are developer group who will use MX chat in SP, business admins might use different conversational AI in control center in the platform. However, in this case, the customer need to cater conversational ai service blue print for their own user group to cater the tone of voice, conversational flow etc.

2024-07-23 14:16 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* [The end-user can set the temperature](#value)
Line 39: In general UX, all the systems need to give the user a feeling of control not control or trap the user in certain tasks. As you see in the visual example, one of the examples is 'disable text filed' and forcing the user to select one of the options. This is in general violating human-computer interaction principles, especially user control.  
Line 40: The temperature setting is common in conversational AI, you can find our AMA as well as Google Gemini and openAI.

2024-07-23 14:17 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* [The end-user can remove the interaction history](#local-control)
I don't get these points.

2024-07-23 14:21 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **System version**: Help end-users understand the capabilities and limitations of the system, setting appropriate expectations for their experience.
It isn't an explicit system version, as v1, or v2, but any type of system update count. Such as beta version or experiment version. If the system mentions system status, it helps the user understand system capabilities and features. Overall able to manage user's expectations.

2024-07-23 14:24 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Allow the end-user to delete the conversation history, and turn off collecting the conversation.
It is general converstional AI feature, that help user to review their conversational history.
Conversation and conversational history are different.
Please try to find similar features from OpenAI, Gemini and Bing. Our AMA also has a history removal feature.

2024-07-23 14:30 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/cancel-button.png" max-width="320px" alt="Show a button to allow end-user to edit a prompt" >}}
'Override the AI action' is critically important in AI-human interaction that human can maintain overall power of control the system. Particularly important AI can make biased suggestion and decision. 
In coversational AI, there's also a feature that user can rewrite the prompt, in this case it can help user to save time from re-writing completely new prompt. Help the user's metacognition to rewrite better prompts based on generated output.

2024-07-23 14:31 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +This is the method for the end-user to provide information to the system. This can be through text, voice, buttons, menus, or a combination of these elements. However, it is always important for the
provide input. 
In human computer interaction, there's always human side of input and computer side of output.
Facilitate input is literally the user is providing input to the system.

2024-07-23 14:32 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Clear affordance is key to where the end-user can enter their input.
please see "https://en.wikipedia.org/wiki/Affordance"

2024-07-23 14:34 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Clear affordance is key to where the end-user can enter their input.
Affordance is environment. So the user can sense the interaction cue by seeing or capturing information (whatever the form is) surrounded in the environment. For example, by seeing a door handle, you know how to operate the door.

2024-07-23 14:36 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Don’t overload various inputs at the same time, it might confuse the end-user with which action to take.
ah...
So feedback is the basic human-computer interaction.
The user provides input, and the system provides feedback that the system received the user's input.
Such as, if the user clicks a button, then the system privdes visual feedback (change the button color) as the user input (click) is recognized by the system.

2024-07-23 14:37 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Allow the end-user to input free text, or initiate a conversation.
Not same.
as you see the example, some system disable the input field.

2024-07-23 14:41 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    * Empower end-users with adjustable "temperature" settings for AI responses. This could range from factual and concise to creative and elaborate, allowing end-users to customize the level of deta
You mean temperature setting?
Please use professional conversational AI from all major tech. Temperature setting is general feature that the user can set the response creativeness. Also, there's a trend of custom instruction.

2024-07-23 14:44 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Input Character Handling**: Set realistic expectations for end-user input.
so?

2024-07-23 14:49 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +With conversational AI, the burden of discovering the capability of a bot or voice assistants is up to the end-user. They can only know a chatbot can’t do something after it fails to provide a good r
I've commented previous question regarding affordance.

2024-07-23 14:52 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/reply-quote-icon.png" max-width="320px" alt="Showing an icon in the Bot response to indicate a response is required" >}}
There are various interactions between the user and the conversational system. if their primary interaction is based on the user's prompt and system response, there are also quotes and re-prompt. Effective re-pompting helps users save time and the system to have a better context of understanding the user's intent.

2024-07-23 14:53 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Serendipity**: Algorithmic recommendations can create filter bubbles. Adding serendipity helps end-users discover new things outside their echo chambers.
Yes similar.

2024-07-23 14:54 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/drafts.png" max-width="320px" alt="Option is given to create multiple drafts of response from Bot with option to show or h
draft functionality is proactive ai responces that user can select one of the versions of ai responses.

2024-07-23 14:57 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Offer context**: Briefly explain why the error happened. For instance, "The password you entered doesn't meet our security requirements. It must be at least 8 characters long and contain a combin
this is "context". The baseline here is helpful guidance to the user side of the error.

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Serendipity**: Algorithmic recommendations can create filter bubbles. Adding serendipity helps end-users discover new things outside their echo chambers.
@Ichigoko Is it okay to use "temperature" here instead of "serendipity" then, to avoid introducing a new term that the reader may not understand?

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Input Character Handling**: Set realistic expectations for end-user input.
@Ichigoko Is it okay to combine these two bullet points into a single one?

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Use a salient discoverability of the functionality.
I don't understand what this means. Could you clarify please?

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Clear affordance is key to where the end-user can enter their input.
Can this bullet be simplified to "Make it clear where the end-user can enter their input."?

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +With conversational AI, the burden of discovering the capability of a bot or voice assistants is up to the end-user. They can only know a chatbot can’t do something after it fails to provide a good r
Is it okay to rephrase this to "hints or interface cues" to help keep this understandable to a wide range of readers?

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Don’t overload various inputs at the same time, it might confuse the end-user with which action to take.
> Don’t overload various inputs at the same time, it might confuse the end-user with which action to take.

Could this bullet point be rephrased to "Don't overwhelm the end-user with too many input options at once. Keep it simple or provide just-in-time input options to avoid confusing the end-user about which action they should take."?

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/drafts.png" max-width="320px" alt="Option is given to create multiple drafts of response from Bot with option to show or h
I'll rephrase to "The end-user can discover options to show or hide a few drafts of the generated text and then select their preferred version."

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Allow the end-user to input free text, or initiate a conversation.
I'll rephrase to "Allow the end-user initiate a conversation by using suggested topics or inputting free text."

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +This is the method for the end-user to provide information to the system. This can be through text, voice, buttons, menus, or a combination of these elements. However, it is always important for the
> However, it is always important for the end-user to feel free to facilitate the input, especially primary input, which should always be available.

Could this be simplified to "Regardless of the input mechanism, the end-user should always have a way to provide input to the system."

2024-07-24 08:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **System version**: Help end-users understand the capabilities and limitations of the system, setting appropriate expectations for their experience.
I can rephrase to "**System status or version**: Help end-users understand the capabilities and limitations of the system, setting appropriate expectations for their experience. For example, let the user know if the system is in beta."

2024-07-24 08:54 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **System version**: Help end-users understand the capabilities and limitations of the system, setting appropriate expectations for their experience.
That sound good. Thank you @dbreseman

2024-07-24 08:55 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +This is the method for the end-user to provide information to the system. This can be through text, voice, buttons, menus, or a combination of these elements. However, it is always important for the
it isn't just any input. the primary input should be the text input in the conversational interface and that shouldn't be block or disabled by any means.

2024-07-24 09:00 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Clear affordance is key to where the end-user can enter their input.
Affordance is well known vocabulary for human-computer interaction.
we can rephrase "Users must easily perceive where to provide input, whether it's text, a button, or another form element."

2024-07-24 09:01 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Don’t overload various inputs at the same time, it might confuse the end-user with which action to take.
Sound good. Thank you @dbreseman

2024-07-24 09:01 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Allow the end-user to input free text, or initiate a conversation.
Yes, perfect!

2024-07-24 09:02 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Input Character Handling**: Set realistic expectations for end-user input.
Yes that's fine :)

2024-07-24 09:08 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Use a salient discoverability of the functionality.
8.3 examples are 
8.3.1 about "prompt example" that normally displays inside of the input field. 
8.3.2 prompt example is catered for expert users, showcasing that a more granular or specific prompt can be possible.
8.3.3 showcasing ready to use prompts as chips displayed on top of the input field so that the user can simply click and use.

9. Displaying history: this seems massed up. the contents are "Quote and Re-prompt" but the title is completely different. Please refer my confluence page, it has original text.

2024-07-24 09:11 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +With conversational AI, the burden of discovering the capability of a bot or voice assistants is up to the end-user. They can only know a chatbot can’t do something after it fails to provide a good r
Yes. sound good. thank you!

2024-07-24 09:15 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* **Serendipity**: Algorithmic recommendations can create filter bubbles. Adding serendipity helps end-users discover new things outside their echo chambers.
Let's remove the serendifity line completely, if it is confusing. 
Serendifity is more discoverability, whereas temperature setting is the level of precision & creativity of the responce.

2024-07-24 09:15 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/drafts.png" max-width="320px" alt="Option is given to create multiple drafts of response from Bot with option to show or h
Thank you!

2024-07-24 10:34 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Use a salient discoverability of the functionality.
@Ichigoko I've reverted the title to match the Confluence page. Could you help me understand what is meant by "Use a salient discoverability of the functionality."? This is a caption in one of the examples on the Confluence page: https://mendix.atlassian.net/wiki/x/3wCurw.

2024-07-24 10:47 UTC, dbreseman commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +    {{< figure src="/attachments/howto/front-end/conversation-best-practices/cancel-button.png" max-width="320px" alt="Show a button to allow end-user to edit a prompt" >}}
I'll reword "Provide the end-user the ability to override AI action via editing the prompt." to "Make it easy for the end-user to edit a previous prompt to generate a new response."

2024-07-24 10:52 UTC, dbreseman commented on static/attachments/howto/front-end/conversation-best-practices/cancel-button.png
@Ichigoko There's a typo ("ypu") in the bot's response here.

2024-07-24 10:53 UTC, dbreseman commented on static/attachments/howto/front-end/conversation-best-practices/data-is-protected.png
@Ichigoko All three conversation style options in this image are "More Balanced".

2024-07-24 10:57 UTC, dbreseman commented on static/attachments/howto/front-end/conversation-best-practices/protection-and-examples.png
@Ichigoko All three conversation style options in this image are "More Balanced".

2024-07-24 11:03 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/data-is-protected.png
oh my! Thank you for spotting this! 
New image here
![AI_Value1](https://github.com/user-attachments/assets/9b997349-8f50-4008-9e1c-39a0c6696e32)

2024-07-24 11:03 UTC, dbreseman commented on static/attachments/howto/front-end/conversation-best-practices/regenerate.png
@Ichigoko The bot response has a typo ("steaming dar embrace")

2024-07-24 11:06 UTC, Ichigoko commented on static/attachments/howto/front-end/conversation-best-practices/regenerate.png
Thank you for spotting!
New image here
![Hint3](https://github.com/user-attachments/assets/bed52fef-4747-45a9-89cf-caba959d1a81)

2024-07-24 11:24 UTC, Ichigoko commented on content/en/docs/howto/front-end/conversation-best-practices.md
> +* Use a salient discoverability of the functionality.
Yes, discoverability or hints shouldn't overwhelm a visual presence that distracts the user's main task. We can rephrase like this "Functionality should be discoverable without overwhelming the interface. or,
Hints should guide users without distracting from the main task."

2024-07-25 11:25 UTC, merged