[RUN-4153] Update System requirements prerequisites
mendix/docs pull request #8070
Opened 2024-07-19 14:21 UTC by akkrishnakumar

2024-07-19 14:24 UTC, atennapel commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle 7.6 or above.
For the JDK it mentions " - if not yet installed on your machine, Mendix will install 'Eclipse Temurin JDK 21 (x64)'". Maybe for Gradle we can mention that it installs Gradle 8.5.

2024-07-19 14:34 UTC, atennapel commented
Looks good to me.

2024-07-19 14:34 UTC, atennapel commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle 7.6 or above.
Looks good. (I cannot resolve this comment)

2024-07-19 14:35 UTC, akkrishnakumar commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle 7.6 or above.
Its ok. Mark will resolve it

2024-07-19 15:19 UTC, MarkvanMents commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle 7.6 or above.
Resolving

2024-07-19 15:28 UTC, MarkvanMents requested changes
Hi @akkrishnakumar and @atennapel 
Thanks for the PR.
I'm afraid I'm off on holiday now. @dbreseman could you follow up on this last question and update the documentation accordingly (see JDK documentation just above this change) if these do not apply to all Mx9/10 versions. Or pass it on to @MariaShaposhnikova if you need someone else to deal with it.

Also, can this be published immediately, or is it related to 10.13/9.24.26?

2024-07-19 15:28 UTC, MarkvanMents commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle version 7.6 or above - if Gradle is not yet installed on your machine, Mendix will install Gradle version 8.5
Was this introduced in a specific Mendix version? If so, which?

2024-07-19 15:28 UTC, MarkvanMents commented on content/en/docs/refguide9/general/system-requirements.md
> +* Gradle version 7.6 or above - if Gradle is not yet installed on your machine, Mendix will install Gradle version 8.5
Was this introduced in a specific Mendix version? If so, which?

2024-07-19 15:51 UTC, atennapel commented on content/en/docs/refguide9/general/system-requirements.md
> +* Gradle version 7.6 or above - if Gradle is not yet installed on your machine, Mendix will install Gradle version 8.5
Gradle 7.6 was added in 9.24.0. Updated to 7.6.3 in 10.4.0 and updated to 8.5 in 10.10.0.

2024-07-19 15:51 UTC, atennapel commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle version 7.6 or above - if Gradle is not yet installed on your machine, Mendix will install Gradle version 8.5
Gradle 7.6 was added in 9.24.0. Updated to 7.6.3 in 10.4.0 and updated to 8.5 in 10.10.0.

2024-07-19 15:51 UTC, atennapel commented
Looks good to me.

2024-07-23 11:45 UTC, dbreseman commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle version 7.6 or above - if Gradle is not yet installed on your machine, Mendix will install Gradle version 8.5
Hi @atennapel, does this mean that Gradle 8.5 or higher is required for SP 10.0.0 onwards?

2024-07-23 11:46 UTC, atennapel commented on content/en/docs/refguide/installation/system-requirements.md
> +* Gradle version 7.6 or above - if Gradle is not yet installed on your machine, Mendix will install Gradle version 8.5
Gradle 8.5 is required IF you set your application Java version to 21. If your Java version is 11 or 17 then Gradle 7.6/7.6.3 will also work.

2024-07-24 10:03 UTC, merged