Updated push notifications troubleshooting
mendix/docs pull request #8134
Opened 2024-08-05 13:00 UTC by jdiehl

Added ngrok link (added this because deploying to sandbox will not work)
Explain that a licensed node is needed

@ConnorLand

2024-08-05 14:07 UTC, jdiehl commented
@allard-mx plese review

2024-08-06 10:08 UTC, allard-mx requested changes

2024-08-06 10:08 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Registration fails on a PWA on iOS | To receive push notifications on iOS the app must be served over https and added to the home page | Deploy your app (or use a tool such as [ngrok](https://ngrok
Can we change `home page` to `home screen` here? As far as I know, `Add to Home Screen` is the official name for this action/option in Safari

Maybe something like `Tap the 'Share' button in Safari, choose the 'Add to Home Screen' option and try again`

2024-08-06 10:08 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Messages are not sent (Status remains Pending) | The Push notifications connector relies on scheduled events to function, which are not supported in a free app running | Run your app on a licensed
Enabling the scheduled event should not be strictly required as far as I know, without it the module should still be able to send out push notifications (albeit to a limited extent). The main purpose for the scheduled event is to automatically retry failed messages. 

All the `CreateAndSendMessageTo*` actions call the `SendMessages` microflow in a task queue. Only if the message fails (and based on the exception), the scheduled event ensures an automatic retry.

2024-08-12 11:58 UTC, ConnorLand commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Registration fails on a PWA on iOS | To receive push notifications on iOS the app must be served over https and added to the home page | Deploy your app (or use a tool such as [ngrok](https://ngrok
Done.

2024-08-12 12:18 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Messages are not sent (Status remains Pending) | The Push notifications connector relies on scheduled events to function, which are not supported in a free app running | Run your app on a licensed
@jdiehl Any thoughts? Do you have some more background/context on this note?

2024-08-12 13:17 UTC, jdiehl commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Messages are not sent (Status remains Pending) | The Push notifications connector relies on scheduled events to function, which are not supported in a free app running | Run your app on a licensed
I have changed the wording. We did receive some comments from customers trying this out in the sandbox and failing to get it working (messages stay in status "Pending")

2024-08-12 14:00 UTC, allard-mx commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Messages are not sent (Status remains Pending) | The Push notifications connector relies on scheduled events to function, which are not supported in a free app running | Run your app on a licensed
Are you sure that this is related to the scheduled event though? If not, I think we should first research what the root cause of the issue could be when using the module in a sandbox environment

2024-08-21 12:19 UTC, jdiehl commented on content/en/docs/refguide/mobile/using-mobile-capabilities/push-notifications/notif-send-test.md
> +| Messages are not sent (Status remains Pending) | The Push notifications connector relies on scheduled events to function, which are not supported in a free app running | Run your app on a licensed
I have no way to replicate the issue. Let's see if others report it and hold back any changes for now.

2024-08-21 12:20 UTC, closed without merging