Update How-to - Testing Microflows with Unit Testing Module
mendix/docs pull request #8177
Opened 2024-08-13 16:02 UTC by Yiyun333

2024-08-15 09:40 UTC, Yiyun333 commented
This PR is linked to GitHub issue: https://github.com/mendix/docs/issues/8144

2024-08-20 12:05 UTC, allard-mx requested changes

2024-08-20 12:05 UTC, allard-mx commented on static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing/promote-microflow.png
Some minor aesthetic comments:
- The outgoing flow for `Medior` is slightly curved, I think it would be nice to make this a straight line, so that the end activity for the `Medior` flow is at the same height as the start of the microflow.
- Currently the height of the `Change Employee's level to Medior` activity is a bit taller than the others. It would be nice to give all of the activities an equal height,

2024-08-20 12:05 UTC, allard-mx commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
>  ### 4.2 Creating a Unit Test Microflow
I noticed that in line 111 of this section, it is mentioned that microflow names for unit tests should start with `Test`. This should actually be `Test_`, and it is also allowed to use `UT_` as a prefix. Not sure if it's necessary to mention here, but might be more complete to add it here as well. Both prefixes are case-insensitive. See the [module docs](https://docs.mendix.com/appstore/modules/unit-testing/#41-creating-microflow-unit-tests) for reference.

2024-08-20 12:05 UTC, allard-mx commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
> +10. To test if the employee is promoted to the right level by adding a **Microflow Call** activity with the following properties:
Should this not be something like `To test if the employee is promoted to the right level, add a ...`?

2024-08-20 12:05 UTC, allard-mx commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
>  14. Double-click the **End event**, and then specify the following properties:
I do not think this last step (setting the return value of the microflow) is required, I think it would be better to remove it, since the example does not really show/explain the use of it. If you do not specify a return value for the microflow, the test is considered to be successful as long as no exceptions are thrown. Whenever the assert action fails, the test will automatically fail by throwing an exception. See the [module documentation](https://docs.mendix.com/appstore/modules/unit-testing/#41-creating-microflow-unit-tests) for some more details.

2024-08-20 12:05 UTC, allard-mx commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
> +17. In the **Test_PromoteEmployeeToSenior** microflow, change the value of the **Level** member to *MyFirstModule.Level.Medior* for the **Create Employee** activity.
In the original, there was also a test called `Test_EmployeeStillSenior`. I think it would be nice to keep this, as it is an example of testing the non-happy path. The test should create an employee with level `Senior`, then call the `Promote` microflow, and then assert that after the promote action, the level is still set to `Senior`.

2024-08-21 15:57 UTC, Yiyun333 commented on static/attachments/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing/promote-microflow.png
Thanks a lot for the comments! I've updated the screenshot in this commit: https://github.com/mendix/docs/pull/8177/commits/2cf18f1a72933a12f661975e53c5bc71958a43cf

2024-08-21 15:58 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
>  ### 4.2 Creating a Unit Test Microflow
Great observation! I've added it to the how-to: https://github.com/mendix/docs/pull/8177/commits/eada0b364a5d3190ffdc51885fecb529af235e2f

2024-08-21 15:58 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
> +10. To test if the employee is promoted to the right level by adding a **Microflow Call** activity with the following properties:
Yes, that's indeed better. I've corrected it: https://github.com/mendix/docs/pull/8177/commits/eada0b364a5d3190ffdc51885fecb529af235e2f.

2024-08-21 16:00 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
>  14. Double-click the **End event**, and then specify the following properties:
Indeed, I was also a bit confused why we had this step. I've removed this step in the documentation: https://github.com/mendix/docs/pull/8177/commits/eada0b364a5d3190ffdc51885fecb529af235e2f.

2024-08-21 16:08 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/microflows/testing-microflows-with-unit-testing.md
> +17. In the **Test_PromoteEmployeeToSenior** microflow, change the value of the **Level** member to *MyFirstModule.Level.Medior* for the **Create Employee** activity.
Good point! Thanks for the clarification. I've added this test microflow back. You can see the final changes here: https://github.com/mendix/docs/pull/8177/files.
Please let me know if you think we can further improve the instructions here.

2024-08-22 15:01 UTC, allard-mx approved these changes

2024-08-22 16:15 UTC, merged