Enable Chroma syntax highlighting
mendix/docs pull request #8206
Opened 2024-08-20 13:25 UTC by dbreseman

2024-08-22 14:58 UTC, MarkvanMents requested changes
Looks good, but I think we need to think a bit more about the line numbers and keep some examples for where they are needed. And communicate/discuss it with the team.

But a great find that we can now do the copy with Chroma. Thanks.

2024-08-22 14:58 UTC, MarkvanMents commented on content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
> -#### HTTP Code Block with Line Numbers Disabled
What is the behavior now with line numbers. It sometimes seems to add them (`json {linenos=table,hl_lines=[6],linenostart=22}` adds them) but the default now seems to be _not_ to have them?
Do you now always have to add them using `{linenos=table}`?

2024-08-22 14:58 UTC, MarkvanMents commented on content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
> -#### Java Code Block with Lines 4-6 Highlighted, and Line Numbering Starting at 33
linenostart still works - I think it is worth having the example.

2024-08-22 14:58 UTC, MarkvanMents commented on config/_default/hugo.toml
> +        lineNos = false # DB - Turned off line numbers
This seems like a good change, but we should discuss it and make sure that we identify where line numbers are needed.

Didn't realize that we had the option 😀

2024-08-23 14:23 UTC, dbreseman commented
Migrating some notes from Slack for transparency's sake:
- The built-in copy button works fine—when there aren't any line numbers. I imagine there's a workaround for the line number issue, but I wonder how much we actually want line numbers? With Chroma, line highlighting and diffs work very well (pictured below), and that might be a clearer and more robust solution than referring to specific lines by number. Currently, it's set up with lineNos = false.
- There are several accessible themes available, and it's possible to customize them if needed. For an overview, see https://www.ctmartin.me/blog/2019/11/print-accessible-code/.
- I used guessSyntax = true to set it so code blocks without a language specification keep the same styling as the rest of the code blocks, rather than reverting to the Docsy default like Prism does.

2024-08-26 10:21 UTC, MarkvanMents commented on content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
> -#### HTTP Code Block with Line Numbers Disabled
Can we keep an example of this syntax with the warning that enabling linenos will disable the copy button. Just in case someone really has this use case?

2024-08-26 10:23 UTC, MarkvanMents commented on config/_default/hugo.toml
> +        lineNos = false # DB - Turned off line numbers
Can we also put something in the comment here to warn the next person that this has an impact on the copy button?
```suggestion
        lineNos = false # DB - Turned off line numbers as the default. Can turn them on individually, if required, but this causes the copy button to disappear.
```

2024-08-26 10:25 UTC, MarkvanMents commented on content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
> +```diff
Can we put a link to the Chroma documentation so it is easy to find the options like `diff` and `linenos=`?

2024-08-27 06:50 UTC, dbreseman commented on content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
> +```diff
This page is just for demos, but I'll add it to https://mendix.atlassian.net/wiki/spaces/RNDHB/pages/2735898685/Shortcodes+Markdown+and+HTML#Code-Blocks!

2024-08-27 06:51 UTC, dbreseman commented on content/en/docs/community-tools/contribute-to-mendix-docs/markdown-shortcodes.md
> -#### HTTP Code Block with Line Numbers Disabled
This page is intended to visualize common use cases—maybe it's sufficient to mention that over on Confluence (https://mendix.atlassian.net/wiki/spaces/RNDHB/pages/2735898685/Shortcodes+Markdown+and+HTML#Code-Blocks) instead?

2024-08-27 12:06 UTC, merged