Update Database replication documentation, fix custom(er) constraint
mendix/docs pull request #8342
Opened 2024-09-18 14:37 UTC by passalaqua

There was a typo in the database replication section, which was fixed.

I also changed the text slightly.

2024-09-19 07:42 UTC, dahfjkg requested changes

2024-09-19 07:42 UTC, dahfjkg commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +* **Normal** - All constraints will be joined together with the `AND` operator following their constraint number.
"joined" has connotations, so I would use a different synonym as there is no actual `JOIN` happening. Both on lines 268 and 270.

2024-09-19 08:01 UTC, passalaqua commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +* **Normal** - All constraints will be joined together with the `AND` operator following their constraint number.
Combined?

2024-09-19 08:51 UTC, dahfjkg commented on content/en/docs/appstore/use-content/modules/database-replication.md
> +* **Normal** - All constraints will be joined together with the `AND` operator following their constraint number.
Yep, could be "combined"

2024-09-19 09:22 UTC, dahfjkg approved these changes
Passed team review

2024-09-20 10:12 UTC, MarkvanMents approved these changes
Thanks for the PR. Have made some minor changes but looks good.

2024-09-20 10:20 UTC, merged