Update the release notes to include all the releases that happened since the last update
mendix/docs pull request #8373
Opened 2024-09-25 11:22 UTC by pavel-constantinov

2024-09-25 12:47 UTC, MarkvanMents requested changes
Hi @pavel-constantinov 
I'm sorry I haven't worked with this before so these may be stupid questions.

- It is not clear to me where all these different versions are available. I've looked in the [GitHub repo](https://github.com/mendix/ExtensionAPI-Samples) and there are no releases or packages set up there.
- Our documentation also doesn't point anywhere else to obtain the API, or to see all the calls available.
- I'm also not sure what "please keep the extension package version synced with Studio Pro" actually means? Does it mean that you have to use version 10.15 with Studio Pro 10.15? I can't see any documentation anywhere on how to update the version of the Extension APIs when you upgrade your Mendix app.

2024-09-25 12:47 UTC, MarkvanMents commented on content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/release-notes.md
> +## Version 10.12.0
I don't really understand why we are saying that 10.12.0 is the first beta when we released a beta on version 10.6.0 and published release notes for versions between 10.6 and 10.12.

2024-09-25 13:51 UTC, pavel-constantinov commented
> Hi @pavel-constantinov I'm sorry I haven't worked with this before so these may be stupid questions.
> 
> * It is not clear to me where all these different versions are available. I've looked in the [GitHub repo](https://github.com/mendix/ExtensionAPI-Samples) and there are no releases or packages set up there.
> * Our documentation also doesn't point anywhere else to obtain the API, or to see all the calls available.
> * I'm also not sure what "please keep the extension package version synced with Studio Pro" actually means? Does it mean that you have to use version 10.15 with Studio Pro 10.15? I can't see any documentation anywhere on how to update the version of the Extension APIs when you upgrade your Mendix app.

Hi @MarkvanMents, no worries, I'll do my best to bring you up to speed.

- Firstly, as it is a NuGet package it's available at nuget.org, the readme of that package is actually pointing to this release notes page.
- Secondly, it certainly does, not necessarily directly but our docs mention that the package is hosted on nuget.org.  
<img width="620" alt="image" src="https://github.com/user-attachments/assets/81ef0653-51dc-4854-a324-8553ec97e466">

  The wording could be improved and a link to nuget.org wouldn't hurt, but this is unrelated to this story.
- Finally, our package is meant to be updated through the NuGet tool in the user's IDE of choice.

2024-09-25 13:54 UTC, pavel-constantinov commented on content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/release-notes.md
> +## Version 10.12.0
I'm pretty sure 10.12 was the public beta release, not 10.6 that was the closed beta for partners. So there's no point mentioning the stuff up until 10.12, as no-one would be able to use those versions of the package, they're simply not there.

2024-09-25 14:23 UTC, MarkvanMents approved these changes
I've changed the wording a bit. Please check it still makes sense.
Approving - let me know if it OK and I'll merge it.

2024-09-25 14:23 UTC, MarkvanMents commented on content/en/docs/apidocs-mxsdk/apidocs/extensibility-api/release-notes.md
> +## Version 10.12.0
OK, I'll resolve this conversation.

2024-09-25 14:24 UTC, MarkvanMents commented
> > Hi @pavel-constantinov I'm sorry I haven't worked with this before so these may be stupid questions.
> > 
> > * It is not clear to me where all these different versions are available. I've looked in the [GitHub repo](https://github.com/mendix/ExtensionAPI-Samples) and there are no releases or packages set up there.
> > * Our documentation also doesn't point anywhere else to obtain the API, or to see all the calls available.
> > * I'm also not sure what "please keep the extension package version synced with Studio Pro" actually means? Does it mean that you have to use version 10.15 with Studio Pro 10.15? I can't see any documentation anywhere on how to update the version of the Extension APIs when you upgrade your Mendix app.
> 
> Hi @MarkvanMents, no worries, I'll do my best to bring you up to speed.
> 
>     * Firstly, as it is a NuGet package it's available at nuget.org, the readme of that package is actually pointing to this release notes page.
> 
>     * Secondly, it certainly does, not necessarily directly but our docs mention that the package is hosted on nuget.org.
> 
> 
> <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/93945068/370740631-81ef0653-51dc-4854-a324-8553ec97e466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzI1ODgsIm5iZiI6MTcyNzI3MjI4OCwicGF0aCI6Ii85Mzk0NTA2OC8zNzA3NDA2MzEtODFlZjA2NTMtNTFkYy00ODU0LWEzMjQtODU1M2VjOTdlNDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDEzNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyNTQ3YWU0MDdlODk5ZDU2NDBhY2VjNDRjYTVhMTdmODFhNzFkNGFlZDY4ZjQ4MmU2NjJmNWI0MjVlZDczMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-gLlbQGJHkBjO1qbxnRX9qmmJIXQPPF7PIk4aPmG08A">
> 
> The wording could be improved and a link to nuget.org wouldn't hurt, but this is unrelated to this story.
> 
>     * Finally, our package is meant to be updated through the NuGet tool in the user's IDE of choice.

Thanks for the update.
I'll add a task to look at whether we can make the use of NuGet a bit clearer. Now you have explained it I see that it is mentioned, but as someone who has never used NuGet it didn't stand out to me.

I've done a small proofread. Hope it still looks good. Let me know if I can merge. https://github.com/mendix/docs/pull/8373/commits/d803f09258db1da943050800822293553226f2af

2024-09-26 07:16 UTC, MarkvanMents commented
Approved over Slack.

2024-09-26 07:16 UTC, merged