Added best-practice for Version Control branching
mendix/docs pull request #8374
Opened 2024-09-25 11:28 UTC by tknippenberg

2024-09-26 11:57 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +In trunk-based development, all developers work on a single branch, typically the "trunk" or "main" branch. Changes are frequently committed to this branch, and developers continuously integrate thei
I don't think "mainline codebase" is clear. I think it would be better to talk about pushing and remotes as we do earlier (4.3, Pushing) in the document?

```suggestion
In trunk-based development, all developers work on a single branch, typically the "trunk" or "main" branch. Changes are frequently committed to this branch, and developers continuously push  their work to the remote repository. 
```

2024-09-26 12:13 UTC, MarkvanMents requested changes
Hi Tom,
I've proofread this in https://github.com/mendix/docs/pull/8374/commits/98cec35831347e3a6904adf1e0eb9805d539e8ec and have also made a couple of comments/suggestions.
Please let me know if you need more information.

2024-09-26 12:13 UTC, MarkvanMents commented on content/en/docs/refguide/version-control/using-version-control-in-studio-pro/_index.md
> +
See comment on picture, below.

2024-09-26 12:13 UTC, MarkvanMents commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/branching-advanced.png
Would it be better to put Feature2 above Feature1 so that there is no need for the timelines to cross? Or to make it clear in some other way that the Feature2 timeline does not touch Feature1 where the lines cross?

2024-09-30 11:30 UTC, tknippenberg commented on static/attachments/refguide/version-control/using-version-control-in-studio-pro/branching-advanced.png
Removed crossing in the images

2024-09-30 15:31 UTC, tknippenberg commented
Needs further changes on Branching image. Not ready to merge.

2024-10-01 09:25 UTC, MarkvanMents commented
The text looks good. Awaiting confirmation that images are correct before merging.

2024-10-01 10:16 UTC, tknippenberg commented
Added 'tips and tricks' section after customer feedback. Feel free to adjust phrasing.
Ready to merge from my perspective.

2024-10-02 14:52 UTC, MarkvanMents approved these changes
Proofread, Thanks for the PR @tknippenberg 
Approving and merging.

2024-10-02 15:03 UTC, merged