Added clone type in Mx9 documentation
mendix/docs pull request #8393
Opened 2024-09-30 11:45 UTC by tknippenberg

2024-09-30 11:46 UTC, tknippenberg commented
@blis-mendix , can you verify whether:
- Text about preferences dialog is correct
- "Convert to full clone..." is available in Mx9 or not

And perhaps a general quick scan if there are differences from the Mx10 docs (where I copied this from)

2024-09-30 13:20 UTC, blis-mendix requested changes

2024-09-30 13:20 UTC, blis-mendix commented on content/en/docs/refguide9/version-control/using-version-control-in-studio-pro/clone-type.md
> +You can also change this preference from the **Open App** dialog box selecting **Preferences** on the left.
On 9 you can't there is nothing like this.

2024-09-30 14:42 UTC, tknippenberg commented on content/en/docs/refguide9/version-control/using-version-control-in-studio-pro/clone-type.md
> +You can also change this preference from the **Open App** dialog box selecting **Preferences** on the left.
Feedback processed. Ready for review by Docs team.

2024-09-30 14:43 UTC, tknippenberg commented
Ready for review by Docs team, ready to merge once reviewed.

2024-10-02 14:37 UTC, MarkvanMents requested changes
@tknippenberg 
I've done a proofread of the document which you can review in these commits: https://github.com/mendix/docs/pull/8393/files/cfe004853c3b78123bda483d615b3bc62dcfae06..c15a5ede97fdffa04e487a22a4eb8e0a1b058c0e

Can you quickly check my changes. If they are good, I'll apply them to the Mx10 document as well and publish.
Thanks.

2024-10-03 05:52 UTC, tknippenberg commented
> @tknippenberg I've done a proofread of the document which you can review in these commits: https://github.com/mendix/docs/pull/8393/files/cfe004853c3b78123bda483d615b3bc62dcfae06..c15a5ede97fdffa04e487a22a4eb8e0a1b058c0e
> 
> Can you quickly check my changes. If they are good, I'll apply them to the Mx10 document as well and publish. Thanks.

Went through the changes and it LGTM! Thank you!

2024-10-03 08:53 UTC, MarkvanMents approved these changes
Thanks for the PR.
Approving and merging.

2024-10-03 08:53 UTC, merged