Documentation for OQL expressions
mendix/docs pull request #8434
Opened 2024-10-04 13:59 UTC by pijuskri

- Documentation for OQL expressions following the new structure
- Includes aggregates and parameters
- Needs team review
- To be merged with other OQL documentation MR's

2024-10-10 09:56 UTC, dahfjkg requested changes

2024-10-10 09:56 UTC, dahfjkg commented on content/en/docs/refguide/modeling/data/oql/oql-expressions.md
> +  | { COUNT | AVG | MAX | MIN | SUM } ( [ DISTINCT ] attribute_path )
Let's add `STRING_AGG` here

2024-10-10 09:56 UTC, dahfjkg commented on content/en/docs/refguide/modeling/data/oql/oql-expressions.md
> +SELECT SUM(Stock) AS StockSum FROM Sales.Product
This example is repeated twice

2024-10-10 09:56 UTC, dahfjkg commented on content/en/docs/refguide/modeling/data/oql/oql-expressions.md
> +Using `MAX` on a string column gives the last alphabetically sorted name:
TBH, this is probably too technical

2024-10-10 09:56 UTC, dahfjkg commented on content/en/docs/refguide/modeling/data/oql/oql-expressions.md
> +If the value of `$param` is not provided, the query will be equivalent to:
I think this is not entirely correct. If a parameter is empty, that part of the expression should be replaced with true, like this:
```
WHERE
    true 
    AND
    Active = true
```
This is even more relevant in case of `OR`, so maybe we should use `OR` in our examples

2024-10-10 14:06 UTC, pijuskri commented on content/en/docs/refguide/modeling/data/oql/oql-expressions.md
> +Using `MAX` on a string column gives the last alphabetically sorted name:
Agreed, i dont think the example is neccesary for more advanced users and this behaviour is mentioned in the documentation

2024-10-16 15:00 UTC, MarkvanMents reviewed
Hi @pijuskri and @dahfjkg 
I've proofread the whole of this document.
I think the style matches the clauses document quite well, I'm not worried that they will seem too different.
I've asked some questions for clarification. 
I'll go back to the clauses document while you digest my changes and come back to me.
Let me know if you want to set up a meeting.

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +* a constant
Can this also be a list of constants? Or can only some expressions return lists?

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +OQL expressions can be used in `WHERE`, `SELECT`, `GROUP BY`, `UNION`, and `JOIN` clauses.
Should probably link to the OQL Clauses doc here.

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +* When combined with a `GROUP BY` clause, aggregations can be used with any column normally available in `SELECT`, not just those specified in the `GROUP BY` clause. Aggregation is performed over gro
I don't understand this at all - and there is no example. How can you put an aggregation into a GROUP BY clause if the column isn't mentioned in the GROUP BY clause?

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +The same result can be retrieved by using `COUNT` on a single table:
On a single **attribute**?

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +#### COUNT
Should these examples be in the same order as we explain the expressions (i.e. with AVG first)?

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +|    34.333    |
This is only right because one of the **Tomatoes** rows has NULL. If it had a number in then the average would be wrong 😀 because we aren't filtering on distinct product names.

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +#### Distinct
I think we should link to the clauses doc here.
Also, DISTINCT isn't an expression - the example is about COUNT so I think we should move this to the COUNT examples.

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If you use undefined in `IN` and `LIKE` comparison expressions, the condition always returns `true`. In other cases, undefined parameters cause an exception.
We don't have any documentation for `IN` and `LIKE`. Are these expressions going to be added here, or will they be in a different document?

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If the value of `$param` is not provided, the query will be equivalent to:
Not sure exactly what "not provided" means in this context.
Does it mean that the parameter has not been created and therefore is not in the current scope, or can you create a variable but still not initialize it.
If it is the first, then perhaps say "If the parameter `$param` has not been created"?

2024-10-16 15:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +Parameters are external variables that are referenced to by name in an OQL query. To use a defined parameter in a query, prepend the `$` sign to the name of the parameter.
Do we have some documentation on how these are created - I guess they are just Java variables, but how does that work in data sets?
Perhaps this would become obvious if I was actually creating some OQL?

2024-10-17 10:39 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If the value of `$param` is not provided, the query will be equivalent to:
The query can reference a parameter and then the parameter mapping needs to be provided when calling the query, say in a java action. I wouldn't say "created" is the best word to use here, parameters are quite temporary.

2024-10-17 10:40 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If you use undefined in `IN` and `LIKE` comparison expressions, the condition always returns `true`. In other cases, undefined parameters cause an exception.
Yes they will be documented in `oql-expression-syntax`

2024-10-17 10:41 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +#### COUNT
Yes, did not notice the order, will change it.

2024-10-17 11:05 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +* When combined with a `GROUP BY` clause, aggregations can be used with any column normally available in `SELECT`, not just those specified in the `GROUP BY` clause. Aggregation is performed over gro
I misformated this. It should not be part of the "ways to use aggregations" list. 
The comment about group by is for aggregates the `SELECT` clause. Ill clarify this

2024-10-17 13:12 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +* a constant
There can be a list of of constants, but only when used with the `IN` operator. Don't think that single use case is important enough to mention here. Some expressions (like subquery) can return multiple values, so its useful to mention that here.

2024-10-17 13:23 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +Parameters are external variables that are referenced to by name in an OQL query. To use a defined parameter in a query, prepend the `$` sign to the name of the parameter.
The best we have now is the datasets documentation. There arent any visuals or examples there and honestly I dont know how that works either.
For java actions its partially explained in the [API docs](https://apidocs.rnd.mendix.com/8/runtime/com/mendix/systemwideinterfaces/connectionbus/requests/types/ITextGetRequest.html#createParameterMap())

2024-10-17 13:37 UTC, MarkvanMents reviewed
I've responded to some of your replies.

2024-10-17 13:37 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +* a constant
OK, Thanks.

2024-10-17 13:37 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If you use undefined in `IN` and `LIKE` comparison expressions, the condition always returns `true`. In other cases, undefined parameters cause an exception.
OK, thanks.

2024-10-17 13:37 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If the value of `$param` is not provided, the query will be equivalent to:
So could we say
```suggestion
If the value of `$param` is not provided as a parameter to the query, the query will be equivalent to:
```

2024-10-17 14:04 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +|    34.333    |
Thats true. Making this query distinct would require a subquery, so a change of the description is better.

2024-10-17 14:15 UTC, pijuskri commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +If the value of `$param` is not provided, the query will be equivalent to:
Yes that seems more clear

2024-10-21 09:03 UTC, dahfjkg commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +## Aggregations
I'm referring to this in Clauses using tag #aggregates. Please add it here

2024-10-29 15:24 UTC, dahfjkg commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +* a combination of attribute names, constants, system variables and functions connected by operators
A subquery can also be a part of "a combination of attribute names, constants, ...", so I'd put this line last and mention subquery in it

2024-10-29 15:24 UTC, dahfjkg commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +OQL expressions can be used in `WHERE`, `SELECT`, `GROUP BY`, `UNION`, and `JOIN` clauses. For more information, see [OQL clauses](/refguide/oql-clauses/).
1. I think `HAVING` too;
2. For `JOIN` clauses, I'd rephrase it as "and `ON` conditions of `JOIN` clauses"

2024-10-29 15:24 UTC, dahfjkg commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +There are duplicate values in the `Name` column, which might not want to be counted separately. [Distinct](/refguide/oql-clauses/#Distinct) can be used to get the number of unique rows:
Let's explain how `DISTINCT` works with `AVG` and `SUM` too

2024-10-29 15:24 UTC, dahfjkg commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +  | { COUNT | AVG | MAX | MIN | SUM | STRING_AGG } ( [ DISTINCT ] attribute_path )
This syntax is not entirely correct: `DISTINCT` is allowed with all functions except `STRING_AGG`

2024-11-01 10:34 UTC, dahfjkg commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +SELECT AVG(Distinct Stock) AS ProductCount FROM Sales.Product
Let's use more representative aliases for different aggregate functions. Both in queries and in result tables.

2024-11-01 12:19 UTC, dahfjkg commented
Passed technical review

2024-11-05 11:37 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +#### COUNT
I've reordered them as the initial description has it ordered COUNT (*) and then COUNT | AVG | MAX - so it seems better to present the descriptions in this order.

2024-11-05 12:34 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/domain-model/oql/oql-expressions.md
> +Parameters are external variables that are referenced to by name in an OQL query. To use a defined parameter in a query, prepend the `$` sign to the name of the parameter.
Thanks for the explanation. I've added a link to the API Docs.

2024-11-13 13:07 UTC, dahfjkg commented
This can be closed as it is merged into https://github.com/mendix/docs/pull/8431

2024-11-19 11:32 UTC, MarkvanMents commented
No unresolved comments. Merged into #8431 so closing this PR.

2024-11-19 11:32 UTC, closed without merging