Add documentation for Micrometer OpenTelemetry registry
mendix/docs pull request #8555
Opened 2024-10-28 15:21 UTC by serg-firsov

2024-10-28 15:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/mendix/docs?pullRequest=8555) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/mendix/docs?pullRequest=8555) before we can accept your contribution.<br/><hr/>**Sergey Firsov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/mendix/docs?pullRequest=8555) it.</sub>

2024-10-28 15:42 UTC, atennapel requested changes

2024-10-28 15:42 UTC, atennapel commented on content/en/docs/refguide/runtime/metrics.md
> +* `type` *(mandatory)* – the type of registry to use. Currently supported types are [`prometheus`](https://prometheus.io/docs/introduction/overview/), [`jmx`](https://www.oracle.com/java/technologies
I think the docs team employs the "Oxford comma" convention, meaning there should be a comma before the "and".

2024-10-28 15:42 UTC, atennapel commented on content/en/docs/refguide/runtime/metrics.md
> +#### OpenTelemetry{#opentelemetry}
I think we'll need a warning here that this was introduced in 10.17.0.

2024-10-28 15:42 UTC, atennapel commented on content/en/docs/refguide/runtime/metrics.md
> +#### OpenTelemetry{#opentelemetry}
Like this:
```
{{% alert color="info" %}}
This feature was introduced in Mendix versions 10.17.0.
{{% /alert %}}
```

2024-10-28 15:49 UTC, serg-firsov commented on content/en/docs/refguide/runtime/metrics.md
> +* `type` *(mandatory)* – the type of registry to use. Currently supported types are [`prometheus`](https://prometheus.io/docs/introduction/overview/), [`jmx`](https://www.oracle.com/java/technologies
Done

2024-10-28 15:49 UTC, serg-firsov commented on content/en/docs/refguide/runtime/metrics.md
> +#### OpenTelemetry{#opentelemetry}
Done

2024-10-28 15:49 UTC, atennapel commented on content/en/docs/refguide/runtime/metrics.md
> +* `type` *(mandatory)* – the type of registry to use. Currently supported types are [`prometheus`](https://prometheus.io/docs/introduction/overview/), [`jmx`](https://www.oracle.com/java/technologies
Approved.

2024-10-28 15:50 UTC, atennapel commented on content/en/docs/refguide/runtime/metrics.md
> +#### OpenTelemetry{#opentelemetry}
Approved.

2024-10-28 15:50 UTC, atennapel approved these changes

2024-10-28 15:50 UTC, atennapel commented
Technical review done, approved.

2024-11-04 11:06 UTC, MarkvanMents approved these changes
Thanks for the PR. Have done a very light proofread here: https://github.com/mendix/docs/pull/8555/commits/92b881316ea6221393a0f880fc3881d91b4b7703
Approving

2024-11-27 13:44 UTC, merged