[SOLP-2812] add analyze mpr tool description
mendix/docs pull request #8618
Opened 2024-11-06 12:09 UTC by mikita-haurykau

2024-11-14 07:33 UTC, tknippenberg commented
Can we get this PR merged? 
I'm aware the documentation mentions it's "available from 10.17" (and that's what we want it to say in the public docs), but actually it has been available for a longer time already. 
As we need to send out some mailings in the coming days where we would like to refer to this documentation, I'd appreciate it if we can already publish this Docs change now.

2024-11-14 08:44 UTC, quinntracy commented
Yes, we can merge it today.

________________________________
From: Tom ***@***.***>
Sent: 14 November 2024 08:34
To: mendix/docs ***@***.***>
Cc: Quinn Tracy ***@***.***>; Assign ***@***.***>
Subject: Re: [mendix/docs] [SOLP-2812] add analyze mpr tool description (PR #8618)


Can we get this PR merged?
I'm aware the documentation mentions it's "available from 10.17" (and that's what we want it to say in the public docs), but actually it has been available for a longer time already.
As we need to send out some mailings in the coming days where we would like to refer to this documentation, I'd appreciate it if we can already publish this Docs change now.

—
Reply to this email directly, view it on GitHub<https://github.com/mendix/docs/pull/8618#issuecomment-2475617035>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BB7DLZC2OGXWM3D2QUIMXHD2ARG7ZAVCNFSM6AAAAABRIV55TOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDINZVGYYTOMBTGU>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2024-11-15 10:08 UTC, quinntracy approved these changes
Approved doc placement

2024-11-25 16:26 UTC, MariaShaposhnikova commented on content/en/docs/refguide/general/mx-command-line-tool/analyze-mpr.md
> +This tool shipped with Mendix 10 can also be used to analyze MPR files created in Mendix 9.24 LTS.
Which tool do we mean here? Command-line tool?

2024-11-25 16:26 UTC, MariaShaposhnikova commented on content/en/docs/refguide/general/mx-command-line-tool/analyze-mpr.md
> +The exact output of this tool may change. You cannot rely on this format staying consistent over time.
I am not sure I understand what is meant in this warning. Could you please rewrite?

2024-11-26 08:58 UTC, MariaShaposhnikova requested changes
Please don't merge before comments are resolved.

2024-11-26 09:30 UTC, tknippenberg commented on content/en/docs/refguide/general/mx-command-line-tool/analyze-mpr.md
> +This tool shipped with Mendix 10 can also be used to analyze MPR files created in Mendix 9.24 LTS.
This specific command in `mx.exe`.

2024-11-26 09:31 UTC, tknippenberg commented on content/en/docs/refguide/general/mx-command-line-tool/analyze-mpr.md
> +The exact output of this tool may change. You cannot rely on this format staying consistent over time.
The intention is to say that this is not a "public API" where customers can count on the format not changing. They should not build tooling on top of this output, as the output may change over time.
I hope with that input you can make a suggestion for the text.

2024-11-26 13:46 UTC, MariaShaposhnikova approved these changes

2024-11-27 13:07 UTC, merged