Document the current index variable
mendix/docs pull request #8680
Opened 2024-11-20 08:18 UTC by WimJongeneel

2024-11-20 08:32 UTC, Robinfr requested changes

2024-11-20 08:32 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/loop.md
> +Within a loop body, the variable `$currentIndex` contains the current index of the loop. This index starts at zero and increments for each iteration. When a loop is nested inside another loop, the `$
>When a loop is nested inside another loop, the `$currentIndex` variable holds the index of its direct parent.

This part is confusing. I read this as, inner loops don't have their own `$currentIndex`. Meaning, it only works for the most outer loop. But what I think you mean is that the `$currentIndex` is always specific to the iteration of the loop action it is used in?

2024-11-20 08:32 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/loop.md
> +Within a loop body, the variable `$currentIndex` contains the current index of the loop. This index starts at zero and increments for each iteration. When a loop is nested inside another loop, the `$
```suggestion
Within a loop, the variable `$currentIndex` contains the current index of the loop. This index starts at zero and increments for each iteration. When a loop is nested inside another loop, the `$currentIndex` variable holds the index of its direct parent. The `$currentIndex` variable is also available inside the expression of a while loop. This feature was introduced in Mendix 10.17.
```

2024-11-20 08:32 UTC, Robinfr commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/loop.md
> +Within a loop body, the variable `$currentIndex` contains the current index of the loop. This index starts at zero and increments for each iteration. When a loop is nested inside another loop, the `$
>current index of the loop.

This is a bit weird in the context of the while loop. In fact, I'm not sure if this is clear enough for developers not familiar with these terms. Maybe we can specify it as "how many iterations the loop has gone through so far"?

2024-11-20 12:54 UTC, Robinfr approved these changes

2024-11-20 12:54 UTC, Robinfr commented
Can be reviewed by tech writers. 👍

2024-11-21 16:00 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/loop.md
> +Within a loop, the `$currentIndex` variable contains the current number of loop iterations. This index starts at zero and increments with each iteration. For nested loops, `$currentIndex` holds the i
@WimJongeneel @Robinfr Thanks for the PR!
I've reviewed the language. Please have a look at my [changes](https://github.com/mendix/docs/pull/8680/commits/91575a496feeff73af386775d94969316c317d3d) and let me know if they are okay.

Question: What does "it" refer to in the following sentence?
> For nested loops, `$currentIndex` holds the index of the innermost loop **it** is part of.

Can you please clarify a bit? Thanks!

2024-11-22 16:45 UTC, Yiyun333 commented on content/en/docs/refguide/modeling/application-logic/microflows-and-nanoflows/loop.md
> +Within a loop, the `$currentIndex` variable contains the current number of loop iterations. This index starts at zero and increments with each iteration. For nested loops, `$currentIndex` holds the i
Answer provided on Slack.

2024-11-22 16:46 UTC, Yiyun333 approved these changes

2024-11-27 13:30 UTC, merged