Add section on empty values in XPath expressions
mendix/docs pull request #8728
Opened 2024-11-29 12:54 UTC by basdebakker

2024-11-29 16:00 UTC, MarkvanMents reviewed
@basdebakker - I've made some changes but hopefully not messed with the logic.
And I've made one suggestion which (I think) makes it clearer.
Let me know what you think.

2024-11-29 16:00 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +* `[not(Attribute = 'value')]` is `true` if the attribute does not match the constant `'value'` or if the attribute is empty.
Can we not make this simpler and say
```suggestion
* `[Attribute = 'value']` is `false` if the attribute does not match the constant `'value'` or if the attribute is empty.
```
Otherwise the double-negative makes it more difficult to follow?

2024-11-29 16:11 UTC, basdebakker commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +* `[not(Attribute = 'value')]` is `true` if the attribute does not match the constant `'value'` or if the attribute is empty.
No. While the changed version is correct, it says something quite different. The changed version already follows from the general rule, in that it is false if the attribute is empty. But the original version is an exception to the general rule.

Though now that I'm writing this, I realize this only makes sense when you know the complete general rule, which is more than I've written. The thing is, in SQL almost any operation on `NULL` just returns `NULL`, so if `Attribute` is NULL, then `Attribute = 'value'` is NULL and then `not(Attribute = 'value')` is also NULL, which (when used as a condition) is treated as `false`.

Therefore, if you know SQL, you would expect `[not(Attribute = 'value')]` to be `false` when the attribute is empty. But because Mendix treats this case specially, it is actually `true`.

On the other hand, `[Attribute = 'value']` is not treated specially and behaves exactly as you would expect if you know SQL.

2024-11-29 17:08 UTC, MarkvanMents commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +* `[not(Attribute = 'value')]` is `true` if the attribute does not match the constant `'value'` or if the attribute is empty.
Ah - OK. So my change is wrong. I won't commit it. Sorry to cause confusion.
I also changed the text to say `true` instead of `match` - is that also misleading? I found it clearer, but perhaps I should go back to "match" as being more indicative of what the database is actually doing?

2024-12-02 08:31 UTC, basdebakker commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +* `[not(Attribute = 'value')]` is `true` if the attribute does not match the constant `'value'` or if the attribute is empty.
I think the "is `true`" is fine. I'm less sure about "attribute does not match the constant". I would say "attribute is not equal to the constant". To me, the verb "match" suggests some kind of pattern matching.

2024-12-02 11:48 UTC, dahfjkg requested changes

2024-12-02 11:48 UTC, dahfjkg commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +There are some exceptions that are treated as special cases:
I would mention explicitly that all these exceptions are related to the situation when one of the sides is constant. Or even split this in two subsections: comparison of attributes when one of them is empty and comparison of attribute to constant.

2024-12-02 11:48 UTC, dahfjkg commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +Here are two examples:
I would also mention the behavior of `<`, `>`, `<=`, `>=`. As I understand, those are always false if one side is empty.

2024-12-02 11:48 UTC, dahfjkg commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +There are some exceptions that are treated as special cases:
Also, we have a section on `empty` and `NULL` in XPath Keywords and System Variables document. Maybe the part about constants belongs there?

2024-12-02 11:55 UTC, basdebakker commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +Here are two examples:
The idea was that this falls under "any comparison".

2024-12-02 12:26 UTC, basdebakker commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +There are some exceptions that are treated as special cases:
1. How about we change this line to "If one of the sides of the comparison is a constant, there are some exceptions that are treated as special cases:"?
2. Does "the part about constants" refer to the last two examples below? Those are not about the keywords. Maybe a reference from there to here?

2024-12-02 12:30 UTC, dahfjkg commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +There are some exceptions that are treated as special cases:
1. Sounds good
2. True, then indeed maybe adding a reference would work

2024-12-02 12:32 UTC, dahfjkg commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +Here are two examples:
I would also add examples of what happens when a boolean is null: in that case, both `[flag]` and `[not(flag)]` are false

2024-12-02 12:41 UTC, basdebakker commented on content/en/docs/refguide/modeling/xpath/xpath-constraints/xpath-expressions.md
> +Here are two examples:
Mendix does not allow boolean values to be empty.

2024-12-02 13:42 UTC, dahfjkg commented
Passed team review

2024-12-05 11:23 UTC, MarkvanMents approved these changes
Thanks for the PR. Sorry the final review got delayed.
Approving.

2024-12-05 12:12 UTC, MarkvanMents commented
Approved in Slack.

2024-12-05 12:12 UTC, merged