Update new-app-node-request-template.md
mendix/docs pull request #8814
Opened 2024-12-20 15:32 UTC by ThijsSeppen

Please merge on the 13th of January, when the new node automation (public cloud) is released.

2024-12-31 14:30 UTC, MarkvanMents requested changes
@ThijsSeppen 
Thanks for the PR.
I've taken the opportunity to do a quick proofread of the whole document for the new year. Let me know if you spot anything which looks odd.

I wonder if we should be clearer about sending keys - see my comment.

2024-12-31 14:30 UTC, MarkvanMents commented on content/en/docs/support/new-app-node-request-template.md
> +Fill in the required details for the new licensed app node on the [Request New App Node](https://newnode.mendix.com/) page. If your request matches your entitlements, your Mendix Cloud node will be c
What do you mean by "requested keys"? Is this just for on-prem? I think we should perhaps mention this as most customers will be doing Mendix Cloud and might be puzzled by this reference?

2025-01-08 11:16 UTC, ThijsSeppen commented on content/en/docs/support/new-app-node-request-template.md
> +Fill in the required details for the new licensed app node on the [Request New App Node](https://newnode.mendix.com/) page. If your request matches your entitlements, your Mendix Cloud node will be c
That's indeed for on-premises customers. Good idea, let's add that information to avoid confusion

2025-01-08 12:11 UTC, MarkvanMents commented on content/en/docs/support/new-app-node-request-template.md
> +Fill in the required details for the new licensed app node on the [Request New App Node](https://newnode.mendix.com/) page. If your request matches your entitlements, your Mendix Cloud node will be c
Updated in a9aae24b5bd9d6f8e09854d6bd76f9fa406e4018

2025-01-08 12:15 UTC, MarkvanMents approved these changes
Looks good, @ThijsSeppen .
Thanks for the PR.
Approving - please let me know when the new template is released.

2025-01-20 15:51 UTC, MarkvanMents commented
Approved over Slack.

2025-01-20 15:51 UTC, merged